#!/usr/bin/env python3
"""F-NAR-008 — vraies histoires ATOM-AUT.ROU.001-01..08 (sans refrain d'étapes)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import LIMITS, relecture, words, write_story


def q_chose(name: str, elle: bool = False) -> dict:
    pron = "Elle" if elle else "Il"
    return {
        "expected_answer": "une chose",
        "accepted_examples": "une chose | puis l'autre | d'abord | doucement | une chose puis l'autre | puis la suivante",
        "retry_prompt": f"{pron} fait une chose, puis la suivante. Comment se prépare {name} ?",
    }


def preview(sid: str, age: str, scripts: dict) -> None:
    lim = LIMITS.get(age) or 12
    n = 0
    for cid, lines in scripts.items():
        for raw in lines:
            phrase = raw.split("|", 1)[1]
            w = words(phrase)
            n += w
            if w > lim:
                raise SystemExit(f"LONG {sid} {cid} {w}>{lim}: {phrase}")
    print(f"preview {sid} {n} mots")


# ---------------------------------------------------------------------------
# 01 N2 Chouchou — village, allée, train de bois, roue
# ---------------------------------------------------------------------------
S01 = {
    "CHK_T0000_P0000": [
        "narrateur|Sur le rebord, un petit train de bois attend.",
        "narrateur|Le toit du wagon est rouge, un peu pâle.",
        "narrateur|Une roue brille encore, toute ronde.",
        "narrateur|La nuit vient juste de partir.",
        "narrateur|Le jardin sent la terre mouillée.",
        "narrateur|Les dalles de l'allée sont fraîches.",
        "narrateur|Une goutte tombe d'une feuille.",
        "narrateur|Un merle chante tout au fond.",
        "narrateur|Dans la maison, le couloir sent le linge.",
        "papa|Chouchou, tu vois ton train ?",
        "enfant-f|Oui, papa.",
        "enfant-f|Il veut l'allée.",
        "maman|L'allée est encore un peu froide.",
        "narrateur|En ce moment, Chouchou est dans son lit.",
        "narrateur|La couverture est chaude, un peu lourde.",
        "narrateur|Elle sent le savon de la lessive.",
        "enfant-f|Je sors le train.",
        "narrateur|Chouchou prend le wagon d'une main.",
        "narrateur|De l'autre, elle attrape une chaussure.",
        "narrateur|Le wagon bascule.",
        "narrateur|Une petite roue part sous la chaise.",
        "enfant-f|Oh.",
        "enfant-f|La roue.",
        "papa|Le train a besoin de toi, toute entière.",
        "maman|Une chose, puis la suivante.",
        "narrateur|Chouchou pose la chaussure près du lit.",
        "narrateur|Elle cherche la roue du bout des doigts.",
        "narrateur|Le bois est lisse, un peu frais.",
        "enfant-f|Je l'ai.",
        "papa|D'abord on se lève.",
        "narrateur|Chouchou pousse la couverture.",
        "narrateur|Ses pieds trouvent le tapis beige.",
        "narrateur|Le tapis est doux sous les orteils.",
        "maman|Tu es debout ?",
        "enfant-f|Oui, maman.",
        "papa|Ensuite le pull, pour conduire.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Chouchou veut l'allée.",
        "narrateur|Comment se prépare-t-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Chouchou a la petite roue dans la main.",
        "maman|Une chose, puis la suivante.",
        "papa|Maintenant, le pull du train.",
        "narrateur|Le pull bleu est sur la chaise.",
        "narrateur|Les manches sont un peu longues.",
        "narrateur|Chouchou enfile le pull.",
        "papa|Je relève une manche.",
        "enfant-f|Je peux conduire.",
        "maman|Oui.",
        "maman|Ensuite, on va à table.",
        "narrateur|La cuisine sent le lait tiède.",
        "narrateur|La fenêtre est un peu embuée.",
        "narrateur|Chouchou s'assoit.",
        "narrateur|Ses pieds touchent le carrelage frais.",
        "maman|Tu veux le bol bleu ?",
        "enfant-f|Oui, le bleu.",
        "narrateur|Elle mange un bout de pain.",
        "narrateur|La croûte fait un petit bruit.",
        "papa|C'est la gare, ici.",
        "enfant-f|Le train attend.",
        "maman|Il attend dans le sac.",
        "papa|Merci, Chouchou.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|Le sac, maintenant.",
        "narrateur|Le sac bleu est près de la porte.",
        "narrateur|Chouchou pose le wagon dedans.",
        "narrateur|Elle remet la petite roue.",
        "narrateur|Ça fait toc, tout doux.",
        "maman|Tu as mis le train ?",
        "enfant-f|Oui, maman.",
        "narrateur|Chouchou met ses chaussures.",
        "narrateur|Les lacets font un petit bruit.",
        "papa|On ouvre ?",
        "enfant-f|L'allée.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air sent la terre mouillée.",
        "narrateur|Les dalles commencent à être tièdes.",
        "narrateur|Chouchou sort le train.",
        "narrateur|Elle le pose sur une dalle.",
        "enfant-f|Roule.",
        "narrateur|Le wagon avance.",
        "narrateur|Toc.",
        "narrateur|Une autre dalle, plus loin.",
        "papa|Il va jusqu'au merle.",
        "maman|Une chose, puis la suivante.",
        "maman|Et le train est parti.",
        "narrateur|Le merle penche la tête.",
        "enfant-f|Il me regarde.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Le toit est rouge au soleil.",
        "papa|Il a fait tout le chemin.",
        "maman|Toi aussi.",
        "narrateur|Le merle chante encore, tout au fond.",
        "papa|Bravo, tu as avancé tout doux.",
        "narrateur|Les dalles sont chaudes maintenant.",
    ],
}
preview("ATOM-AUT.ROU.001-01", "N2", S01)
write_story(
    "ATOM-AUT.ROU.001-01",
    "Chouchou veut faire rouler son train sur l'allée. Elle prend tout à la fois, une roue part. Une chose puis la suivante, le wagon avance sur les dalles tièdes.",
    "Le train de l'allée",
    "Chouchou, papa, maman",
    "maison du village, chambre puis jardin, le matin",
    S01,
    {"CHK_T0000_P0000_END": "porte"},
    q_chose("Chouchou", elle=True),
)
relecture(
    "ATOM-AUT.ROU.001-01",
    "Le train de l'allée",
    "Chouchou veut l'allée. Roue perdue. Elle se lève, s'habille, déjeune, pose le train. Dalles tièdes.",
    "Sans refrain une étape après l'autre. Fin sensorielle.",
)


# ---------------------------------------------------------------------------
# 02 N1 Victorina — jardin, oiseau, miettes
# ---------------------------------------------------------------------------
S02 = {
    "CHK_T0000_P0000": [
        "narrateur|Un oiseau gris tape la vitre.",
        "narrateur|Toc.",
        "narrateur|Toc.",
        "narrateur|Il a un ventre tout rond.",
        "narrateur|Il penche la tête.",
        "narrateur|Dehors, l'herbe est mouillée.",
        "narrateur|Une goutte brille sur une feuille.",
        "narrateur|Le ciel est rose, tout pâle.",
        "narrateur|Une branche frotte le mur, tout bas.",
        "narrateur|Le jardin sent la rosée.",
        "maman|Victorina, tu entends l'oiseau ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Il chante.",
        "papa|Il dit bonjour.",
        "narrateur|En ce moment, Victorina ouvre les yeux.",
        "narrateur|Le drap jaune est chaud.",
        "narrateur|Ça sent le linge propre.",
        "enfant-f|Je veux le voir.",
        "narrateur|Victorina va vers la fenêtre.",
        "narrateur|Elle est encore en chemise de nuit.",
        "narrateur|L'oiseau s'envole vers la barrière.",
        "enfant-f|Il part.",
        "maman|Il va au jardin.",
        "papa|Nous aussi, tout à l'heure.",
        "maman|D'abord le matin.",
        "maman|Une chose, puis la suivante.",
        "narrateur|Victorina pose la main sur la vitre.",
        "narrateur|La vitre est un peu froide.",
        "narrateur|Le rideau blanc bouge très peu.",
        "papa|On se lève ?",
        "enfant-f|Oui.",
        "narrateur|Victorina quitte le drap.",
        "narrateur|Ses pieds touchent le tapis.",
        "narrateur|Le tapis est doux.",
        "papa|Le pull, maintenant.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Victorina veut l'oiseau.",
        "narrateur|Comment se prépare-t-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "papa|Le pull vert, sur la chaise.",
        "narrateur|Victorina enfile le pull.",
        "narrateur|Le pull sent le jardin, un peu.",
        "enfant-f|C'est vert, comme l'herbe.",
        "maman|Oui.",
        "maman|Ensuite, le pain.",
        "narrateur|Victorina va à la cuisine.",
        "narrateur|Le carrelage est froid.",
        "narrateur|La table est déjà mise.",
        "maman|Tu veux le pain d'abord ?",
        "enfant-f|Le pain.",
        "narrateur|Elle s'assoit.",
        "narrateur|Elle croque un bout de pain.",
        "narrateur|Le pain est un peu dur.",
        "maman|On garde une miette ?",
        "enfant-f|Pour l'oiseau.",
        "papa|Oui.",
        "papa|Dans ta main, tout doux.",
        "maman|Merci, Victorina.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|Ensuite, le sac.",
        "narrateur|Le sac rouge attend près du banc.",
        "narrateur|Victorina met la gourde.",
        "narrateur|Elle met le doudou.",
        "papa|Les miettes, avec nous.",
        "enfant-f|Dans ma main.",
        "narrateur|Victorina met ses chaussures.",
        "narrateur|Les chaussures sont un peu serrées.",
        "papa|On les ajuste ?",
        "enfant-f|Oui.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|L'air sent le jardin.",
        "narrateur|L'herbe brille encore.",
        "narrateur|L'oiseau est sur la barrière.",
        "enfant-f|Il est là !",
        "maman|Pose les miettes.",
        "narrateur|Victorina pose les miettes.",
        "narrateur|L'oiseau penche la tête.",
        "narrateur|Il picore une miette.",
        "narrateur|Puis une autre.",
        "papa|Il dit merci.",
        "maman|On reste un peu, tout calmes.",
        "enfant-f|Il a le ventre rond.",
        "narrateur|Une goutte brille encore sur la feuille.",
        "narrateur|L'herbe est froide sous les chaussures.",
        "maman|Tu lui as dit bonjour ?",
        "enfant-f|Oui, tout doux.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Bonjour, oiseau.",
        "maman|Tu as avancé tout doucement.",
        "papa|Une chose, puis la suivante.",
        "narrateur|L'oiseau picore encore.",
        "papa|Bravo, Victorina.",
        "narrateur|Le ventre rond brille au soleil.",
    ],
}
preview("ATOM-AUT.ROU.001-02", "N1", S02)
write_story(
    "ATOM-AUT.ROU.001-02",
    "Victorina veut dire bonjour à l'oiseau gris. Elle va trop vite, l'oiseau part. Une chose puis la suivante, elle pose des miettes sur la barrière.",
    "Les miettes de Victorina",
    "Victorina, papa, maman",
    "chambre puis jardin, le matin",
    S02,
    {"CHK_T0000_P0000": "oiseau", "CHK_T0000_P0000_END": "porte"},
    q_chose("Victorina", elle=True),
)
relecture(
    "ATOM-AUT.ROU.001-02",
    "Les miettes de Victorina",
    "Victorina veut l'oiseau. Trop vite, il part. Pull, pain, miettes, barrière. Il picore.",
    "Sans refrain interdit. Fin = l'oiseau.",
)


# ---------------------------------------------------------------------------
# 03 N1 Nino — escalier, pain chaud
# ---------------------------------------------------------------------------
S03 = {
    "CHK_T0000_P0000": [
        "narrateur|Une odeur de pain monte l'escalier.",
        "narrateur|Ça sent le beurre.",
        "narrateur|Ça sent la croûte dorée.",
        "narrateur|Une petite vapeur grimpe, toute blanche.",
        "narrateur|Les marches de bois sont lisses.",
        "narrateur|La rampe est ronde sous la main.",
        "narrateur|En bas, un plat se pose.",
        "narrateur|Ça fait un petit bruit.",
        "maman|Nino, tu sens le pain ?",
        "enfant-m|Oui, maman.",
        "enfant-m|C'est chaud.",
        "papa|Il est sur la planche.",
        "narrateur|En ce moment, Nino est dans son lit.",
        "narrateur|L'oreiller est plat.",
        "narrateur|Le drap sent le sommeil.",
        "enfant-m|Je veux le pain.",
        "narrateur|Nino pose un pied par terre.",
        "narrateur|Il va vers la première marche.",
        "narrateur|Il est encore en pyjama.",
        "papa|Le pain t'attend, Nino.",
        "papa|D'abord le pull.",
        "maman|Une chose, puis la suivante.",
        "narrateur|Nino s'arrête.",
        "narrateur|L'odeur est encore là.",
        "narrateur|Elle est douce, très douce.",
        "enfant-m|Il part, le pain ?",
        "maman|Non.",
        "maman|Il reste au chaud.",
        "papa|On se lève ?",
        "enfant-m|Oui.",
        "narrateur|Nino revient vers le lit.",
        "narrateur|Ses pieds touchent le tapis.",
        "papa|Le pull jaune, d'abord.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nino veut le pain.",
        "narrateur|Comment se prépare-t-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le pull jaune est près du lit.",
        "narrateur|Nino enfile le pull.",
        "narrateur|Le pull est doux sur les bras.",
        "enfant-m|C'est fait.",
        "maman|Ensuite, les marches.",
        "narrateur|Nino pose la main sur la rampe.",
        "maman|Une marche, puis l'autre.",
        "enfant-m|Oui, maman.",
        "narrateur|Les marches sentent le bois.",
        "narrateur|La cuisine est chaude.",
        "narrateur|Le pain est sur la planche.",
        "narrateur|La croûte craque un peu.",
        "papa|Tu t'assois ?",
        "narrateur|Nino s'assoit à table.",
        "maman|Un peu de beurre ?",
        "enfant-m|Oui, un peu.",
        "papa|Merci, Nino.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Nino mord la croûte.",
        "narrateur|Le pain est tiède.",
        "narrateur|Le beurre fond un peu.",
        "enfant-m|C'est bon.",
        "papa|Tu as une miette ici.",
        "narrateur|Papa montre le menton.",
        "enfant-m|Je l'essuie.",
        "maman|Ensuite, le sac.",
        "narrateur|Le sac vert est près du banc.",
        "narrateur|Nino met la gourde.",
        "narrateur|Il met le doudou.",
        "papa|Tu as mis ce qu'il faut ?",
        "enfant-m|Oui, papa.",
        "narrateur|Nino met ses chaussures.",
        "papa|Le pied gauche d'abord ?",
        "enfant-m|Oui.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air sent encore le pain.",
        "enfant-m|Ça sent bon.",
        "maman|Oui.",
        "narrateur|Nino sent ses doigts.",
        "narrateur|Ils sentent encore le beurre.",
        "papa|Le pain est venu jusqu'à toi.",
        "narrateur|Une miette dore encore sur la planche.",
        "narrateur|La rampe de bois reste tiède.",
        "maman|Tu as pris le temps ?",
        "enfant-m|Oui, une chose, puis l'autre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le pain était chaud.",
        "maman|Tu es venu jusqu'à lui.",
        "papa|Une chose, puis la suivante.",
        "narrateur|Une petite vapeur flotte encore.",
        "maman|Bravo, Nino.",
        "narrateur|La croûte tiède reste sur sa langue.",
    ],
}
preview("ATOM-AUT.ROU.001-03", "N1", S03)
write_story(
    "ATOM-AUT.ROU.001-03",
    "Nino sent le pain chaud et veut descendre tout de suite. Papa l'attend à la marche. Une chose puis la suivante, il mord la croûte tiède.",
    "Le pain chaud de Nino",
    "Nino, papa, maman",
    "chambre, escalier, cuisine, le matin",
    S03,
    {"CHK_T0000_P0000": "pain", "CHK_T0000_P0000_END": "porte"},
    q_chose("Nino"),
)
relecture(
    "ATOM-AUT.ROU.001-03",
    "Le pain chaud de Nino",
    "Nino veut le pain. Pyjama, marche trop tôt. Pull, marches, beurre, croûte.",
    "Sans refrain interdit. Fin = la croûte.",
)


# ---------------------------------------------------------------------------
# 04 N3 Sarah — marché, fraises
# ---------------------------------------------------------------------------
S04 = {
    "CHK_T0000_P0000": [
        "narrateur|Le rideau bleu se soulève avec le vent.",
        "narrateur|Il gonfle comme une petite voile.",
        "narrateur|Un anneau frotte la tringle, tout doux.",
        "narrateur|Un carré de lumière glisse sur le plancher.",
        "narrateur|Dehors, on pose déjà des caisses.",
        "narrateur|Une charrette roule tout loin.",
        "narrateur|Ça sent les fruits, même d'ici.",
        "narrateur|Une caisse racle le pavé, tout loin.",
        "papa|Sarah, tu vois le rideau ?",
        "enfant-f|Oui, papa.",
        "enfant-f|Il danse.",
        "maman|Le marché commence, tout doucement.",
        "narrateur|En ce moment, Sarah est encore au lit.",
        "narrateur|Elle a envie des fraises, tout de suite.",
        "enfant-f|On y va maintenant ?",
        "narrateur|Sarah prend le cabas rayé près de la porte.",
        "narrateur|Le cabas est vide, tout plat.",
        "narrateur|Elle n'a pas encore de chaussures.",
        "maman|Les fraises seront là.",
        "papa|D'abord notre matin.",
        "papa|Une chose, puis la suivante.",
        "narrateur|Sarah repose le cabas.",
        "narrateur|Le tissu rayé tombe contre le mur.",
        "enfant-f|J'ai trop faim pour attendre.",
        "maman|Alors on déjeune ici, d'abord.",
        "maman|Après, tu auras encore faim pour les fraises.",
        "papa|On se lève ?",
        "enfant-f|Oui.",
        "narrateur|Sarah pousse le drap.",
        "narrateur|Ses pieds trouvent le parquet lisse.",
        "narrateur|Le parquet est un peu frais.",
        "maman|Le t-shirt blanc, sur la commode.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Sarah veut les fraises.",
        "narrateur|Comment se prépare-t-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Sarah enfile le t-shirt.",
        "narrateur|Le coton est encore un peu tiède.",
        "enfant-f|Je suis habillée.",
        "papa|La cuisine, maintenant.",
        "narrateur|La nappe à carreaux est déjà mise.",
        "narrateur|Ça sent le yaourt et le miel.",
        "maman|Tu veux un peu de miel ?",
        "enfant-f|Oui, un peu.",
        "narrateur|Sarah s'assoit.",
        "narrateur|Elle pose les pieds par terre.",
        "narrateur|Le miel est sucré sur la cuillère.",
        "papa|Tu as encore faim pour le marché ?",
        "enfant-f|Un peu, oui.",
        "maman|C'est bien.",
        "maman|Les fraises aiment ça.",
        "papa|Merci, Sarah.",
        "maman|Ensuite, le cabas.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Sarah prend le cabas rayé.",
        "narrateur|Elle met la gourde.",
        "narrateur|Elle met le petit sac aussi.",
        "maman|Tu as mis ce qu'il faut ?",
        "enfant-f|Oui, maman.",
        "narrateur|Sarah met ses chaussures.",
        "papa|On prend le cabas ?",
        "enfant-f|Oui, papa.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|Sarah donne la main.",
        "narrateur|La rue sent les fruits.",
        "narrateur|Un panier passe, tout plein.",
        "enfant-f|Les fraises !",
        "maman|Choisis.",
        "narrateur|Sarah choisit une barquette rouge.",
        "narrateur|Une fraise est déjà un peu chaude.",
        "papa|Tu la goûtes ?",
        "enfant-f|Elle est sucrée.",
        "narrateur|Un peu de jus rouge reste sur le doigt.",
        "maman|Tu l'as choisie, celle-là.",
        "narrateur|Une caisse racle encore, tout près.",
        "papa|On en prend une autre ?",
        "enfant-f|Celle-ci, la plus rouge.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|J'ai du rouge sur le doigt.",
        "maman|C'est le marché.",
        "papa|Une chose, puis la suivante, et les fraises étaient là.",
        "narrateur|Le rideau, derrière eux, danse encore.",
        "maman|Bravo, Sarah.",
        "narrateur|Le jus sucré reste chaud sur son doigt.",
    ],
}
preview("ATOM-AUT.ROU.001-04", "N3", S04)
write_story(
    "ATOM-AUT.ROU.001-04",
    "Sarah veut les fraises du marché tout de suite. Le cabas est vide. Une chose puis la suivante, elle goûte une fraise sucrée dans la rue.",
    "Les fraises de Sarah",
    "Sarah, papa, maman",
    "maison puis rue du marché, le matin",
    S04,
    {"CHK_T0000_P0000": "rideau", "CHK_T0000_P0000_END": "porte"},
    q_chose("Sarah", elle=True),
)
relecture(
    "ATOM-AUT.ROU.001-04",
    "Les fraises de Sarah",
    "Sarah veut les fraises. Cabas vide, pas de chaussures. Matin, miel, marché, jus rouge.",
    "Sans refrain interdit. Fin = le doigt sucré.",
)


# ---------------------------------------------------------------------------
# 05 N3 Amir — bassin, noix-bateau
# ---------------------------------------------------------------------------
S05 = {
    "CHK_T0000_P0000": [
        "narrateur|Sur la table de nuit, une noix attend.",
        "narrateur|À côté, une petite feuille sèche.",
        "narrateur|La feuille est légère, presque rien.",
        "narrateur|La noix a un dos tout ridé.",
        "narrateur|Un rayon jaune allonge deux pantoufles.",
        "narrateur|On dirait deux petits quais.",
        "narrateur|La poussière danse dans le rayon.",
        "papa|Amir, tu vois ta noix ?",
        "enfant-m|Oui, papa.",
        "enfant-m|C'est le bateau.",
        "maman|Le bassin est dans le jardin.",
        "narrateur|En ce moment, Amir ouvre les yeux.",
        "narrateur|Il prend la noix tout de suite.",
        "narrateur|Il glisse les pieds dans les pantoufles.",
        "enfant-m|On va à l'eau.",
        "narrateur|Il marche vers la porte, encore en pyjama.",
        "narrateur|Le bassin, dehors, est encore vide.",
        "papa|L'eau arrive, tout doucement.",
        "papa|Et nous aussi.",
        "maman|Une chose, puis la suivante.",
        "narrateur|Amir s'arrête sur le tapis crème.",
        "narrateur|La noix est chaude dans sa main.",
        "enfant-m|Elle veut flotter.",
        "maman|Elle flottera.",
        "maman|D'abord on s'habille.",
        "papa|On se lève pour de bon ?",
        "enfant-m|Oui.",
        "narrateur|Amir repose la noix près de la feuille.",
        "narrateur|Le rayon touche encore les pantoufles.",
        "papa|Le pull rouge, sur le dossier.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Amir veut le bassin.",
        "narrateur|Comment se prépare-t-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Amir enfile le pull.",
        "narrateur|Le pull est un peu rêche aux poignets.",
        "enfant-m|Je suis habillé.",
        "maman|La cuisine, maintenant.",
        "narrateur|Ça sent la banane et le lait tiède.",
        "maman|Tu veux la banane coupée ?",
        "enfant-m|Oui, maman.",
        "narrateur|Amir s'assoit à table.",
        "narrateur|La banane est douce, un peu sucrée.",
        "papa|Dehors, je verse l'eau.",
        "papa|Tu finis ton bol, et l'eau sera prête.",
        "enfant-m|D'accord.",
        "narrateur|Il boit une gorgée de lait.",
        "narrateur|Le lait est tiède contre la lèvre.",
        "maman|Merci, Amir.",
        "maman|Ensuite, le sac.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Amir met la gourde dans le sac.",
        "narrateur|Il met le cahier.",
        "narrateur|Il met la noix, tout au-dessus.",
        "narrateur|La petite feuille aussi.",
        "papa|Tu as mis le bateau ?",
        "enfant-m|Oui, papa.",
        "narrateur|Amir range les pantoufles près du tapis.",
        "maman|Tu les as remises au quai ?",
        "enfant-m|Oui.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air sent le jardin, un peu humide.",
        "narrateur|Le bassin a un peu d'eau, toute calme.",
        "narrateur|Amir pose la noix.",
        "narrateur|Il pose la feuille dessus.",
        "enfant-m|Souffle, papa.",
        "narrateur|Papa souffle.",
        "narrateur|La noix avance, tout doucement.",
        "maman|Elle flotte.",
        "narrateur|Un petit rond d'eau s'ouvre.",
        "enfant-m|Encore, papa.",
        "narrateur|Papa souffle encore, plus fort.",
        "narrateur|La feuille-voile tremble, puis repart.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le bateau est parti.",
        "papa|Une chose, puis la suivante.",
        "maman|Les pantoufles ont attendu, et toi tu as avancé.",
        "narrateur|Le rayon revient sur le tapis, là-bas.",
        "papa|Bravo, Amir.",
        "narrateur|La noix glisse encore, toute petite, sur l'eau calme.",
    ],
}
preview("ATOM-AUT.ROU.001-05", "N3", S05)
write_story(
    "ATOM-AUT.ROU.001-05",
    "Amir veut faire flotter sa noix dans le bassin. Il part en pyjama, le bassin est vide. Une chose puis la suivante, la feuille-voile avance sur l'eau.",
    "Le bateau d'Amir",
    "Amir, papa, maman",
    "chambre, cuisine, jardin, le matin",
    S05,
    {"CHK_T0000_P0000_END": "porte"},
    q_chose("Amir"),
)
relecture(
    "ATOM-AUT.ROU.001-05",
    "Le bateau d'Amir",
    "Amir veut le bassin. Pyjama, bassin vide. Pull, banane, eau, noix. Elle flotte.",
    "Sans refrain interdit. Fin = la noix sur l'eau.",
)


# ---------------------------------------------------------------------------
# 06 N1 Mila — doudou, porte fermée, promenade
# ---------------------------------------------------------------------------
S06 = {
    "CHK_T0000_P0000": [
        "narrateur|Sur la chaise, un doudou rouge attend.",
        "narrateur|Il a deux oreilles toutes molles.",
        "narrateur|Une oreille penche un peu.",
        "narrateur|L'autre oreille est droite.",
        "narrateur|Le nez est un fil tout doux.",
        "narrateur|Les murs sont couleur pêche.",
        "narrateur|Un mobile tourne très lentement.",
        "narrateur|Une étoile de bois passe, puis un oiseau.",
        "narrateur|Ça fait un tout petit vent.",
        "maman|Mila, tu vois le doudou ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Il attend.",
        "papa|Il t'attend pour la promenade.",
        "narrateur|En ce moment, Mila ouvre les yeux.",
        "narrateur|Ça sent le doudou, tout près.",
        "enfant-f|Je le prends.",
        "narrateur|Mila prend le doudou.",
        "narrateur|Elle va vers la porte.",
        "narrateur|Elle est encore en pyjama.",
        "narrateur|La porte est fermée.",
        "enfant-f|On sort.",
        "maman|Oui.",
        "maman|Le doudou viendra dans le sac.",
        "papa|D'abord le matin.",
        "papa|Une chose, puis la suivante.",
        "narrateur|Mila serre une oreille molle.",
        "narrateur|L'oreille est chaude contre sa joue.",
        "maman|On se lève ?",
        "enfant-f|Oui.",
        "narrateur|Mila pose le doudou sur la chaise.",
        "narrateur|Ses pieds touchent le tapis.",
        "narrateur|Le tapis est doux.",
        "maman|Le pull, maintenant.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Mila veut la promenade.",
        "narrateur|Comment se prépare-t-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le pull rose est sur le dossier.",
        "narrateur|Mila enfile le pull.",
        "narrateur|Le coton est un peu tiède.",
        "enfant-f|C'est fait.",
        "papa|Ensuite, le bol.",
        "narrateur|Mila va à la cuisine.",
        "narrateur|Le carrelage est froid.",
        "narrateur|Ça sent le lait.",
        "maman|Tu veux le bol rouge ?",
        "enfant-f|Oui, le rouge.",
        "narrateur|Elle s'assoit.",
        "narrateur|Elle boit une gorgée.",
        "narrateur|Le lait est tiède.",
        "papa|Le doudou t'attend sur la chaise.",
        "enfant-f|Après, dans le sac.",
        "maman|Merci, Mila.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|Ensuite, le sac.",
        "narrateur|Le sac jaune est près de la porte.",
        "narrateur|Mila met la gourde.",
        "narrateur|Elle glisse le doudou.",
        "narrateur|Une oreille dépasse un peu.",
        "papa|Tu as mis le doudou ?",
        "enfant-f|Oui, papa.",
        "narrateur|Mila met ses chaussures.",
        "maman|Le bon pied ?",
        "enfant-f|Oui.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|L'air du matin entre, frais.",
        "narrateur|Le chemin sent l'herbe coupée.",
        "narrateur|Ils marchent, tout doux.",
        "narrateur|Le sac tape contre la hanche.",
        "enfant-f|L'oreille dépasse.",
        "maman|Elle voit la promenade.",
        "papa|Toi aussi.",
        "narrateur|Une feuille sèche roule sur le chemin.",
        "enfant-f|On continue ?",
        "maman|Oui, encore un peu.",
        "narrateur|Mila serre la sangle.",
        "narrateur|Le doudou chauffe contre son dos.",
        "narrateur|Le mobile, derrière eux, ne tourne plus.",
        "narrateur|Le chemin sent encore l'herbe.",
        "maman|Tu es sortie, tout doucement ?",
        "enfant-f|Oui, une chose, puis l'autre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|On est dehors.",
        "papa|Une chose, puis la suivante.",
        "maman|Le doudou a fait le chemin avec toi.",
        "narrateur|L'oreille rouge dépasse encore.",
        "papa|Bravo, Mila.",
        "narrateur|L'air frais reste sur ses joues.",
    ],
}
preview("ATOM-AUT.ROU.001-06", "N1", S06)
write_story(
    "ATOM-AUT.ROU.001-06",
    "Mila veut sortir tout de suite avec le doudou rouge. La porte est fermée. Une chose puis la suivante, une oreille dépasse du sac, et ils marchent.",
    "Le doudou de Mila",
    "Mila, papa, maman",
    "chambre petite, cuisine, promenade du matin",
    S06,
    {"CHK_T0000_P0000_END": "porte"},
    q_chose("Mila", elle=True),
)
relecture(
    "ATOM-AUT.ROU.001-06",
    "Le doudou de Mila",
    "Mila veut sortir. Porte fermée, pyjama. Pull, lait, sac, chemin. Oreille dehors.",
    "Sans refrain interdit. Fin = l'air frais.",
)


# ---------------------------------------------------------------------------
# 07 N1 Raphaël — gouttière, flaque, bottes
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|Dehors, il pleut tout doux.",
        "narrateur|La rue est brillante.",
        "narrateur|Les toits sont tout mouillés.",
        "narrateur|La gouttière chante goutte à goutte.",
        "narrateur|Ploc.",
        "narrateur|Ploc.",
        "narrateur|La fenêtre est un peu embuée.",
        "narrateur|On peut dessiner un rond sur la buée.",
        "narrateur|Le zinc chante encore, tout près.",
        "papa|Raphaël, tu entends la gouttière ?",
        "enfant-m|Oui, papa.",
        "enfant-m|Ça chante.",
        "maman|La pluie fait sa musique.",
        "narrateur|En ce moment, Raphaël ouvre les yeux.",
        "narrateur|On entend encore les gouttes.",
        "enfant-m|Je veux la flaque.",
        "narrateur|Les bottes vertes sont près du lit.",
        "narrateur|Raphaël met une botte.",
        "narrateur|Il est encore en pyjama.",
        "narrateur|La botte est trop grande.",
        "narrateur|Il s'assoit sur le tapis.",
        "enfant-m|Elle glisse.",
        "papa|La flaque t'attend.",
        "maman|D'abord les vêtements.",
        "maman|Une chose, puis la suivante.",
        "narrateur|Raphaël retire la botte.",
        "narrateur|Il touche la buée du doigt.",
        "narrateur|Le doigt laisse un petit trait.",
        "papa|On se lève ?",
        "enfant-m|Oui.",
        "narrateur|Raphaël se lève.",
        "narrateur|Ses pieds touchent le tapis.",
        "papa|Le pull, maintenant.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Raphaël veut la flaque.",
        "narrateur|Comment se prépare-t-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le pull bleu est sur la chaise.",
        "narrateur|Raphaël enfile le pull.",
        "narrateur|Le pull est un peu rêche.",
        "enfant-m|C'est fait.",
        "maman|Ensuite, le bol.",
        "narrateur|Raphaël va à la cuisine.",
        "narrateur|Le carrelage est froid.",
        "narrateur|Ça sent le lait.",
        "papa|Tu veux le bol vert ?",
        "enfant-m|Oui, le vert.",
        "narrateur|Il s'assoit.",
        "narrateur|Il boit une gorgée.",
        "maman|Les bottes, après le bol.",
        "enfant-m|Pour la flaque.",
        "papa|Merci, Raphaël.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|Ensuite, les bottes.",
        "narrateur|Raphaël enfile une botte.",
        "narrateur|Puis l'autre.",
        "narrateur|Elles ne glissent plus.",
        "papa|Le bon pied ?",
        "enfant-m|Oui.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air sent la pluie.",
        "narrateur|La gouttière chante encore.",
        "narrateur|Sous le zinc, une flaque ronde attend.",
        "enfant-m|Elle est là.",
        "papa|Un pied, puis l'autre.",
        "narrateur|Raphaël pose une botte dans l'eau.",
        "narrateur|Ça fait ploc.",
        "narrateur|Puis l'autre botte.",
        "narrateur|Ça fait ploc encore.",
        "enfant-m|C'est froid.",
        "maman|Oui, tout doux.",
        "narrateur|Un cercle d'eau s'ouvre.",
        "papa|On en fait un autre ?",
        "enfant-m|Oui.",
        "narrateur|Raphaël saute un tout petit peu.",
        "narrateur|L'eau saute aussi, toute claire.",
        "narrateur|Un rond de buée reste à la fenêtre.",
        "narrateur|La rue brille encore, tout loin.",
        "maman|Tes pieds sont au chaud ?",
        "enfant-m|Oui, dans les bottes.",
        "narrateur|Une goutte tombe encore du zinc.",
        "narrateur|Elle fait un nouveau cercle.",
        "papa|Tu as attendu tes vêtements ?",
        "enfant-m|Oui, une chose, puis l'autre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Mes bottes ont chanté.",
        "papa|Une chose, puis la suivante.",
        "maman|La gouttière et toi, ensemble.",
        "narrateur|Le zinc chante encore, tout près.",
        "papa|Bravo, Raphaël.",
        "narrateur|La flaque ronde tremble encore sous les bottes.",
    ],
}
preview("ATOM-AUT.ROU.001-07", "N1", S07)
write_story(
    "ATOM-AUT.ROU.001-07",
    "Raphaël veut la flaque sous la gouttière. Il met une botte trop grande sur le pyjama. Une chose puis la suivante, ses bottes font ploc.",
    "La flaque de Raphaël",
    "Raphaël, papa, maman",
    "maison sous la pluie, gouttière, le matin",
    S07,
    {"CHK_T0000_P0000": "pluie,gouttiere", "CHK_T0000_P0000_END": "porte"},
    q_chose("Raphaël"),
)
relecture(
    "ATOM-AUT.ROU.001-07",
    "La flaque de Raphaël",
    "Raphaël veut la flaque. Botte trop grande. Pull, bol, bottes, ploc. Cercle d'eau.",
    "Sans refrain interdit. Fin = la flaque.",
)


# ---------------------------------------------------------------------------
# 08 N1 Nina — cacao, radiateur, moustache
# ---------------------------------------------------------------------------
S08 = {
    "CHK_T0000_P0000": [
        "narrateur|La maison sent déjà le cacao.",
        "narrateur|Dans la cuisine, une casserole chante.",
        "narrateur|Elle fait des petites bulles.",
        "narrateur|Une vapeur glisse sous la porte.",
        "narrateur|Elle est tiède.",
        "narrateur|Elle sent le sucre.",
        "narrateur|Elle sent aussi le lait chaud.",
        "narrateur|La vapeur chatouille un peu le nez.",
        "maman|Nina, tu sens le chocolat ?",
        "enfant-f|Oui, maman.",
        "enfant-f|C'est bon.",
        "papa|Il n'est pas encore dans le bol.",
        "narrateur|Près du radiateur, des chaussettes sèchent.",
        "narrateur|Elles sont épaisses et brunes.",
        "narrateur|En ce moment, Nina ouvre les yeux.",
        "enfant-f|Je veux le chocolat.",
        "narrateur|Nina va vers la cuisine.",
        "narrateur|Elle est encore en pyjama.",
        "narrateur|La casserole chante encore.",
        "maman|Il finit de se faire.",
        "papa|D'abord le pull.",
        "papa|Une chose, puis la suivante.",
        "narrateur|Nina s'arrête près du radiateur.",
        "narrateur|Elle touche une chaussette.",
        "narrateur|La chaussette est tiède.",
        "maman|On se lève ?",
        "enfant-f|Oui.",
        "narrateur|Nina revient vers le lit.",
        "narrateur|Ses pieds touchent le tapis.",
        "narrateur|Le tapis est doux.",
        "maman|Le pull, maintenant.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nina veut le chocolat.",
        "narrateur|Comment se prépare-t-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le pull brun est sur la chaise.",
        "narrateur|Nina enfile le pull.",
        "narrateur|Le pull est chaud, un peu lourd.",
        "enfant-f|C'est fait.",
        "papa|Les chaussettes, ensuite.",
        "narrateur|Nina prend une chaussette du radiateur.",
        "narrateur|Elle est tiède encore.",
        "narrateur|Elle enfile une, puis l'autre.",
        "maman|Tu as les pieds au chaud ?",
        "enfant-f|Oui, maman.",
        "papa|La casserole a fini.",
        "maman|On va au bol.",
        "narrateur|Nina marche vers la cuisine.",
        "narrateur|Le carrelage n'est plus froid, avec les chaussettes.",
        "papa|Merci, Nina.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Maman verse le cacao.",
        "narrateur|Ça fait un petit chuchotis dans le bol.",
        "narrateur|Une vapeur monte encore.",
        "maman|Tu souffles ?",
        "enfant-f|Oui.",
        "narrateur|Nina souffle.",
        "narrateur|La vapeur danse, puis s'en va.",
        "papa|Tu goûtes ?",
        "enfant-f|Il est chaud.",
        "maman|Encore un peu.",
        "narrateur|Nina souffle encore.",
        "narrateur|Elle boit une gorgée.",
        "narrateur|Le cacao est doux, un peu sucré.",
        "enfant-f|C'est bon.",
        "papa|Tu as une moustache.",
        "narrateur|Une ligne brune reste sur la lèvre.",
        "enfant-f|Je la garde.",
        "maman|Oui, un moment.",
        "narrateur|La casserole ne chante plus.",
        "papa|Le sac, après le bol ?",
        "enfant-f|Oui.",
        "narrateur|Nina pose le bol vide.",
        "narrateur|Le fond est encore un peu chaud.",
        "narrateur|Les chaussettes brunes restent tièdes.",
        "narrateur|Le radiateur fait un petit bruit.",
        "papa|Tu as attendu le bol ?",
        "enfant-f|Oui, une chose, puis l'autre.",
        "narrateur|Une bulle éclate encore dans la casserole.",
        "narrateur|Le sucre sent encore, tout bas.",
        "maman|Tu as soufflé assez ?",
        "enfant-f|Oui, maintenant il est bon.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|J'ai une moustache.",
        "papa|Une chose, puis la suivante.",
        "maman|Le chocolat est arrivé jusqu'à toi.",
        "narrateur|La vapeur n'est plus sous la porte.",
        "maman|Bravo, Nina.",
        "narrateur|La moustache brune reste tiède sur sa lèvre.",
    ],
}
preview("ATOM-AUT.ROU.001-08", "N1", S08)
write_story(
    "ATOM-AUT.ROU.001-08",
    "Nina sent le cacao et veut le bol tout de suite. La casserole chante encore. Une chose puis la suivante, elle souffle, boit, et une moustache brune apparaît.",
    "Le chocolat de Nina",
    "Nina, papa, maman",
    "chambre, radiateur, cuisine, le matin",
    S08,
    {"CHK_T0000_P0000": "casserole"},
    q_chose("Nina", elle=True),
)
relecture(
    "ATOM-AUT.ROU.001-08",
    "Le chocolat de Nina",
    "Nina veut le cacao. Pyjama, casserole. Pull, chaussettes, souffle, moustache.",
    "Sans refrain interdit. Fin = la moustache.",
)
