#!/usr/bin/env python3
"""F-NAR-008 — ATOM-JEU.REG.002-01..07 (attendre, sans jamais dire « règle »)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import LIMITS, relecture, words, write_story


def q_attend(name: str, elle: bool = False) -> dict:
    pron = "Elle" if elle else "Il"
    return {
        "expected_answer": "attendre",
        "accepted_examples": (
            "attendre | on attend | un peu | son tour | elle attend | il attend | "
            "attendre un peu | on attend un peu | à son tour"
        ),
        "retry_prompt": f"{pron} reste un peu. Que fait {name} d'abord ?",
    }


def preview(sid: str, age: str, scripts: dict) -> None:
    lim = LIMITS.get(age) or 12
    n = 0
    for cid, lines in scripts.items():
        for raw in lines:
            phrase = raw.split("|", 1)[1]
            w = words(phrase)
            n += w
            if w > lim:
                raise SystemExit(f"LONG {sid} {cid} {w}>{lim}: {phrase}")
            low = phrase.lower()
            if "règle" in low or "regle" in low:
                raise SystemExit(f"{sid} mot interdit « règle »: {phrase}")
    print(f"preview {sid} {n} mots")


# ---------------------------------------------------------------------------
# 01 N1 Mila, papa — village, figuier, cerceau
# ---------------------------------------------------------------------------
S01 = {
    "CHK_T0000_P0000": [
        "narrateur|Le figuier du jardin a des feuilles chaudes.",
        "narrateur|Une abeille tourne tout près.",
        "narrateur|Ça sent le fruit mûr.",
        "narrateur|Le linge blanc sèche sur la corde.",
        "narrateur|Il claque un peu, tout doux.",
        "narrateur|La terre est sèche, un peu rose.",
        "narrateur|Des haricots grimpent le long d'un fil.",
        "narrateur|Le village est calme, derrière le mur.",
        "papa|Mila, tu vois le cerceau ?",
        "enfant-f|Oui, papa.",
        "enfant-f|Il est rouge.",
        "narrateur|Le cerceau est posé contre le figuier.",
        "narrateur|Il brille un peu au soleil.",
        "narrateur|En ce moment, Mila court vers lui.",
        "enfant-f|Je veux passer.",
        "enfant-f|Comme un tunnel.",
        "papa|Moi je le tiens.",
        "papa|Toi tu passes.",
        "narrateur|Papa pose un pied près du bois.",
        "narrateur|Il n'a pas encore les deux mains.",
        "narrateur|Mila tire déjà le cerceau.",
        "narrateur|Le cerceau penche.",
        "narrateur|Il tombe.",
        "narrateur|Toc.",
        "narrateur|Il roule vers les haricots.",
        "enfant-f|Oh.",
        "enfant-f|Il part.",
        "papa|Il est tombé.",
        "papa|On attend un peu ?",
        "narrateur|Mila s'arrête.",
        "narrateur|L'abeille s'éloigne.",
        "narrateur|Une feuille de figuier bouge.",
        "narrateur|Le cerceau est dans les feuilles.",
        "enfant-f|Je le prends.",
        "papa|Doucement.",
        "papa|On y va ensemble.",
        "narrateur|Ils marchent entre les haricots.",
        "narrateur|Les feuilles frottent les genoux.",
        "narrateur|Ça sent le vert, tout fort.",
        "narrateur|Mila touche le cerceau.",
        "narrateur|Le plastique est chaud, un peu poussiéreux.",
        "enfant-f|Je l'ai.",
        "papa|On le ramène près de l'arbre.",
        "narrateur|Papa tient le cerceau, cette fois.",
        "narrateur|Ses deux mains sont dessus.",
        "papa|Tu attends que je sois prêt ?",
        "enfant-f|Oui.",
        "papa|On attend un peu.",
        "narrateur|Mila reste les pieds dans la terre.",
        "narrateur|Elle regarde le trou du cerceau.",
        "narrateur|Le jardin est tout calme.",
        "narrateur|L'abeille revient, tout bas.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Mila veut passer.",
        "narrateur|Que fait-elle d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Mila reste encore un peu.",
        "papa|J'ai les deux mains.",
        "papa|Tu peux passer.",
        "enfant-f|J'y vais.",
        "narrateur|Elle plie les genoux.",
        "narrateur|Elle passe dans le trou rouge.",
        "narrateur|Le cerceau ne bouge pas.",
        "narrateur|Il tient, tout rond.",
        "enfant-f|Je suis passée !",
        "papa|Oui.",
        "papa|Il est resté debout.",
        "narrateur|Mila se retourne.",
        "narrateur|Le figuier fait une ombre ronde.",
        "narrateur|Une figue sent très fort.",
        "papa|Encore une fois ?",
        "enfant-f|Encore.",
        "papa|On attend un peu.",
        "narrateur|Papa replace le cerceau.",
        "narrateur|Mila compte dans sa tête.",
        "narrateur|Un.",
        "narrateur|Deux.",
        "papa|Maintenant.",
        "narrateur|Elle passe encore.",
        "narrateur|Ses cheveux touchent le plastique.",
        "papa|Merci, Mila.",
        "enfant-f|C'est un tunnel.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On va boire ?",
        "enfant-f|J'ai chaud.",
        "narrateur|La pompe du jardin est froide.",
        "narrateur|Papa verse de l'eau.",
        "narrateur|Ça fait un petit bruit.",
        "narrateur|Mila boit.",
        "narrateur|Une goutte tombe sur le pied.",
        "enfant-f|Elle est froide.",
        "papa|Le cerceau attend encore.",
        "enfant-f|Je repasse ?",
        "papa|Oui.",
        "papa|Quand je tiens bien.",
        "narrateur|Ils reviennent sous le figuier.",
        "narrateur|Le linge claque, plus loin.",
        "narrateur|Papa lève le cerceau.",
        "narrateur|Mila attend, les mains ouvertes.",
        "papa|Tu es prête ?",
        "enfant-f|Oui, papa.",
        "narrateur|Elle passe tout droit.",
        "narrateur|Le plastique reste chaud.",
        "narrateur|L'abeille tourne autour d'une figue.",
        "enfant-f|Elle me regarde.",
        "papa|Elle aussi, elle attend.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Le tunnel est rouge.",
        "papa|Et toi, tu es passée.",
        "papa|Bravo, Mila.",
        "narrateur|Le figuier sent encore le fruit.",
        "narrateur|Le cerceau tient contre le tronc.",
    ],
}
preview("ATOM-JEU.REG.002-01", "N1", S01)
write_story(
    "ATOM-JEU.REG.002-01",
    "Mila veut passer dans le cerceau rouge du figuier. Elle tire trop vite, "
    "le cerceau tombe dans les haricots. Ils attendent un peu. Papa tient, "
    "elle passe. Le fruit sent encore.",
    "Le cerceau du figuier",
    "Mila, papa",
    "jardin du village, figuier, après-midi d'été",
    S01,
    {},
    q_attend("Mila", elle=True),
)
relecture(
    "ATOM-JEU.REG.002-01",
    "Le cerceau du figuier",
    "Mila veut le tunnel rouge. Cerceau tombé dans les haricots. "
    "On attend un peu. Elle passe, le figuier sent.",
    "Sans le mot règle. Imprévu = chute du cerceau. Fin = fruit et cerceau debout.",
)


# ---------------------------------------------------------------------------
# 02 N1 Amir, maman — cour d'immeuble, ballon
# ---------------------------------------------------------------------------
S02 = {
    "CHK_T0000_P0000": [
        "narrateur|Les draps blancs claquent au-dessus de la cour.",
        "narrateur|Ça sent le savon chaud.",
        "narrateur|Les dalles sont tièdes sous le soleil.",
        "narrateur|Un pigeon gratte près du caniveau.",
        "narrateur|Les vélos sont alignés contre le mur.",
        "narrateur|Le caoutchouc des pneus sent un peu.",
        "narrateur|Un store orange descend à une fenêtre.",
        "maman|Amir, tu vois le ballon ?",
        "enfant-m|Oui, maman.",
        "enfant-m|Il est bleu.",
        "narrateur|Le ballon attend près du banc.",
        "narrateur|Il a une tache de poussière.",
        "narrateur|En ce moment, Amir court vers lui.",
        "enfant-m|Je veux le lancer.",
        "enfant-m|Vers toi.",
        "maman|J'ouvre les mains.",
        "maman|Toi tu lances.",
        "narrateur|Maman pose encore le panier.",
        "narrateur|Ses mains ne sont pas prêtes.",
        "narrateur|Amir prend déjà le ballon.",
        "narrateur|Il le lance trop vite.",
        "narrateur|Le ballon tape une dalle.",
        "narrateur|Il part sous les vélos.",
        "narrateur|Le pigeon s'envole.",
        "enfant-m|Oh.",
        "enfant-m|Il est parti.",
        "maman|Il a roulé.",
        "maman|On attend un peu ?",
        "narrateur|Amir s'arrête.",
        "narrateur|Les draps claquent encore.",
        "narrateur|Un vélo penche un peu.",
        "narrateur|Le ballon est dans l'ombre.",
        "enfant-m|Je le prends.",
        "maman|Doucement.",
        "maman|Les pédales piquent.",
        "narrateur|Ils se baissent près des roues.",
        "narrateur|Le métal est froid.",
        "narrateur|Amir touche le ballon.",
        "narrateur|Il est un peu rêche, un peu chaud.",
        "enfant-m|Je l'ai.",
        "maman|On revient au milieu.",
        "narrateur|Maman pose le panier contre le mur.",
        "narrateur|Elle ouvre les deux mains.",
        "maman|Tu attends que je sois prête ?",
        "enfant-m|Oui.",
        "maman|On attend un peu.",
        "narrateur|Amir tient le ballon contre le ventre.",
        "narrateur|Il sent le caoutchouc.",
        "narrateur|La cour est tout calme.",
        "narrateur|Le pigeon revient, tout bas.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Amir veut lancer.",
        "narrateur|Que fait-il d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Amir reste encore un peu.",
        "maman|Mes mains sont ouvertes.",
        "maman|Tu peux lancer.",
        "enfant-m|J'y vais.",
        "narrateur|Il lance tout doux.",
        "narrateur|Le ballon tape une dalle.",
        "narrateur|Clac.",
        "narrateur|Il arrive dans les mains de maman.",
        "enfant-m|Tu l'as !",
        "maman|Oui.",
        "maman|Il n'est pas parti.",
        "narrateur|Maman le renvoie.",
        "narrateur|Amir tend les bras.",
        "narrateur|Le ballon est un peu lourd.",
        "maman|Encore une fois ?",
        "enfant-m|Encore.",
        "maman|On attend un peu.",
        "narrateur|Amir pose le ballon contre lui.",
        "narrateur|Il regarde les mains de maman.",
        "maman|Maintenant.",
        "narrateur|Clac, encore.",
        "narrateur|Les draps bougent au-dessus.",
        "maman|Merci, Amir.",
        "enfant-m|Il est bleu, tout rond.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|On va boire ?",
        "enfant-m|J'ai soif.",
        "narrateur|La gourde est dans le panier.",
        "narrateur|Maman verse de l'eau.",
        "narrateur|Amir boit.",
        "narrateur|Une goutte tombe sur une dalle.",
        "narrateur|Elle sèche tout de suite.",
        "enfant-m|Elle est tiède.",
        "maman|Le ballon attend encore.",
        "enfant-m|Je relance ?",
        "maman|Oui.",
        "maman|Quand j'ai les mains.",
        "narrateur|Ils reviennent au milieu.",
        "narrateur|Le pigeon picore près du caniveau.",
        "narrateur|Amir attend, le ballon au ventre.",
        "maman|Tu es prêt ?",
        "enfant-m|Oui, maman.",
        "narrateur|Il lance.",
        "narrateur|Le ballon revient.",
        "narrateur|Les draps claquent, plus loin.",
        "enfant-m|Le pigeon reste.",
        "maman|Oui.",
        "maman|Il n'a pas peur.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le ballon est chaud.",
        "maman|Et toi, tu as lancé.",
        "maman|Bravo, Amir.",
        "narrateur|Les draps blancs claquent encore.",
        "narrateur|Le ballon bleu tient dans ses mains.",
    ],
}
preview("ATOM-JEU.REG.002-02", "N1", S02)
write_story(
    "ATOM-JEU.REG.002-02",
    "Amir veut lancer le ballon bleu à maman dans la cour. Il lance trop vite, "
    "le ballon part sous les vélos. Ils attendent un peu. Le ballon claque "
    "sur les dalles. Les draps claquent encore.",
    "Le ballon sous les vélos",
    "Amir, maman",
    "cour d'immeuble, draps, dalles, après-midi",
    S02,
    {},
    q_attend("Amir"),
)
relecture(
    "ATOM-JEU.REG.002-02",
    "Le ballon sous les vélos",
    "Amir veut lancer. Ballon sous les vélos, pigeon parti. "
    "On attend un peu. Clac sur les dalles.",
    "Sans le mot règle. Imprévu = ballon sous les vélos. Fin = draps et ballon chaud.",
)


# ---------------------------------------------------------------------------
# 03 N3 Sarah, papa, Chouchou — parc, rivière, marelle
# ---------------------------------------------------------------------------
S03 = {
    "CHK_T0000_P0000": [
        "narrateur|La craie jaune sent encore le papier.",
        "narrateur|Le parc descend vers la rivière.",
        "narrateur|Les châtaignes tapent l'herbe, toutes brunes.",
        "narrateur|Un bateau passe, très loin, tout bas.",
        "narrateur|Le banc de bois est froid d'un côté.",
        "narrateur|L'autre côté a pris le soleil.",
        "papa|Sarah, tu vois les cases ?",
        "enfant-f|Oui, papa.",
        "enfant-f|Elles sont jaunes.",
        "narrateur|Chouchou tient un caillou plat.",
        "narrateur|Le caillou est gris, un peu mouillé.",
        "copine|Je commence.",
        "copine|C'est mon caillou.",
        "narrateur|En ce moment, Sarah se penche déjà.",
        "enfant-f|Je saute.",
        "enfant-f|Jusqu'au bout.",
        "papa|Chouchou n'a pas encore posé.",
        "narrateur|Sarah saute quand même.",
        "narrateur|Son pied écrase une case.",
        "narrateur|La craie devient une poudre grise.",
        "narrateur|Le caillou de Chouchou glisse.",
        "narrateur|Il part dans l'herbe.",
        "copine|Oh.",
        "copine|Mon caillou.",
        "narrateur|Chouchou a les joues toutes plates.",
        "narrateur|Elle ne saute plus.",
        "papa|La marelle s'est arrêtée.",
        "papa|On attend un peu ?",
        "enfant-f|Je voulais le bout.",
        "papa|Le bout est encore là.",
        "papa|Chouchou d'abord.",
        "narrateur|Sarah s'arrête au bord des cases.",
        "narrateur|Ses chaussures ont de la craie.",
        "narrateur|Ça sent la poussière chaude.",
        "enfant-f|Je ramasse le caillou ?",
        "papa|Oui.",
        "papa|Tout doux, dans l'herbe.",
        "narrateur|Sarah cherche près d'une châtaigne.",
        "narrateur|Le caillou est froid, un peu mouillé.",
        "enfant-f|Le voilà.",
        "copine|Merci.",
        "narrateur|Chouchou le pose sur la première case.",
        "narrateur|La craie tient, cette fois.",
        "papa|Tu attends le tour de Chouchou ?",
        "enfant-f|Oui.",
        "papa|On attend un peu.",
        "narrateur|Sarah reste sur le banc tiède.",
        "narrateur|Elle entend la rivière, tout bas.",
        "narrateur|Chouchou saute une case, puis l'autre.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Sarah veut sauter.",
        "narrateur|Que fait-elle d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Chouchou arrive au bout des cases.",
        "copine|C'est bon.",
        "copine|À toi.",
        "papa|Sarah, tu peux y aller.",
        "enfant-f|J'y vais.",
        "narrateur|Elle pose le caillou sur une case.",
        "narrateur|Elle saute, un pied, puis l'autre.",
        "narrateur|La craie reste jaune, pas grise.",
        "enfant-f|Je n'ai pas écrasé.",
        "papa|Oui.",
        "papa|Les cases tiennent.",
        "narrateur|Chouchou tape des mains, tout petit.",
        "narrateur|Un bateau glisse encore, plus loin.",
        "papa|Encore une fois ?",
        "enfant-f|Encore.",
        "papa|On attend un peu.",
        "narrateur|Sarah revient près du banc.",
        "narrateur|Chouchou reprend le caillou gris.",
        "copine|Moi d'abord.",
        "enfant-f|Toi d'abord.",
        "narrateur|Chouchou saute.",
        "narrateur|Sarah compte les cases, sans bouger.",
        "papa|Merci, Sarah.",
        "enfant-f|Le bout est jaune.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On s'assoit un peu ?",
        "enfant-f|Le banc est chaud.",
        "narrateur|Papa casse une châtaigne.",
        "narrateur|La coque fait un petit bruit.",
        "narrateur|Sarah tient le fruit, tout lisse.",
        "copine|Elle est douce.",
        "papa|La marelle attend encore.",
        "enfant-f|Je rejoue ?",
        "papa|Oui.",
        "papa|Quand Chouchou a fini.",
        "narrateur|Ils reviennent vers les cases.",
        "narrateur|La rivière brille entre les arbres.",
        "narrateur|Sarah attend, les mains ouvertes.",
        "papa|Tu es prête ?",
        "enfant-f|Oui, papa.",
        "copine|À toi.",
        "narrateur|Sarah saute jusqu'au bout.",
        "narrateur|La dernière case est encore jaune.",
        "narrateur|Chouchou rit, tout bas.",
        "enfant-f|On a fini ensemble.",
        "papa|Oui.",
        "papa|Une après l'autre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Le bout est jaune au soleil.",
        "papa|Et toi, tu as attendu.",
        "papa|Bravo, Sarah.",
        "narrateur|La rivière brille encore, tout bas.",
        "narrateur|Le caillou gris tient dans la main de Chouchou.",
    ],
}
preview("ATOM-JEU.REG.002-03", "N3", S03)
write_story(
    "ATOM-JEU.REG.002-03",
    "Sarah veut sauter jusqu'au bout de la marelle. Elle saute trop tôt, "
    "la craie s'efface, Chouchou perd son caillou. Elles attendent un peu. "
    "Une après l'autre, le bout reste jaune. La rivière brille.",
    "La marelle de la rivière",
    "Sarah, Chouchou, papa",
    "parc au bord de la rivière, automne, craie jaune",
    S03,
    {"CHK_T0000_P0000": "enfants_parc"},
    q_attend("Sarah", elle=True),
)
relecture(
    "ATOM-JEU.REG.002-03",
    "La marelle de la rivière",
    "Sarah veut le bout. Case écrasée, Chouchou triste. "
    "On attend un peu. Elles sautent une après l'autre.",
    "Sans le mot règle. Imprévu = craie grise et caillou perdu. Fin = rivière.",
)


# ---------------------------------------------------------------------------
# 04 N3 Nina, papa — jardin de montagne, quilles puis balle
# ---------------------------------------------------------------------------
S04 = {
    "CHK_T0000_P0000": [
        "narrateur|Les aiguilles de pin tapissent le gravier.",
        "narrateur|Ça sent la résine chaude.",
        "narrateur|Le romarin fait un nuage gris, tout bas.",
        "narrateur|La montagne est proche, toute bleue.",
        "narrateur|Un lézard part sous une pierre.",
        "narrateur|Les quilles de bois attendent en tas.",
        "papa|Nina, tu vois les quilles ?",
        "enfant-f|Oui, papa.",
        "enfant-f|Elles sont blondes.",
        "narrateur|Papa pose déjà trois quilles.",
        "narrateur|La quatrième penche encore.",
        "narrateur|En ce moment, Nina prend la balle.",
        "enfant-f|Je veux les faire tomber.",
        "enfant-f|Toutes.",
        "papa|J'ai pas fini le rang.",
        "narrateur|Nina lance quand même.",
        "narrateur|La balle part trop vite.",
        "narrateur|Elle tape le gravier, à côté.",
        "narrateur|Une quille roule dans le romarin.",
        "narrateur|Les autres s'éparpillent.",
        "enfant-f|Oh.",
        "enfant-f|Elle est partie.",
        "papa|Le jeu s'est arrêté.",
        "papa|On attend un peu ?",
        "narrateur|Nina s'arrête au bord du gravier.",
        "narrateur|Les aiguilles collent à ses chaussures.",
        "narrateur|Ça sent le pin, tout fort.",
        "enfant-f|Je cherche la quille ?",
        "papa|Oui.",
        "papa|Dans le romarin, tout doux.",
        "narrateur|Les feuilles piquent un peu les doigts.",
        "narrateur|Nina trouve le bois lisse.",
        "enfant-f|Je l'ai.",
        "papa|On les remet, une par une.",
        "narrateur|Papa pose la dernière quille.",
        "narrateur|Le rang est droit, cette fois.",
        "papa|Tu attends que je sois prêt ?",
        "enfant-f|Oui.",
        "papa|On attend un peu.",
        "narrateur|Nina tient la balle contre le ventre.",
        "narrateur|Elle est ronde, un peu rêche.",
        "narrateur|Le lézard revient sur la pierre.",
        "narrateur|Le romarin ne bouge plus.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nina veut lancer.",
        "narrateur|Que fait-elle d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Nina reste encore un peu.",
        "papa|Le rang est prêt.",
        "papa|Tu peux lancer.",
        "enfant-f|J'y vais.",
        "narrateur|Elle fait rouler la balle.",
        "narrateur|La balle avance sur le gravier.",
        "narrateur|Toc.",
        "narrateur|Deux quilles tombent, tout net.",
        "enfant-f|Elles sont tombées !",
        "papa|Oui.",
        "papa|Le rang a tenu, d'abord.",
        "narrateur|Le bois sent encore la résine.",
        "narrateur|Nina ramasse les quilles blondes.",
        "papa|Encore une fois ?",
        "enfant-f|Encore.",
        "papa|On attend un peu.",
        "narrateur|Papa remet le rang.",
        "narrateur|Nina compte, sans lancer.",
        "narrateur|Un.",
        "narrateur|Deux.",
        "papa|Maintenant.",
        "narrateur|Toc, encore.",
        "papa|Merci, Nina.",
        "enfant-f|Le bois fait un beau bruit.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|Plus tard, le ballon ?",
        "enfant-f|Oui, le rouge.",
        "narrateur|Le ballon rouge attend près du thym.",
        "narrateur|Le thym sent le citron, un peu.",
        "narrateur|Papa ouvre les mains.",
        "enfant-f|Je le prends.",
        "papa|Attends un peu.",
        "narrateur|Nina s'arrête.",
        "narrateur|Elle ne lance pas tout de suite.",
        "papa|Mes mains sont ouvertes.",
        "papa|Tu es prête ?",
        "enfant-f|Oui, papa.",
        "narrateur|Elle envoie le ballon, tout doux.",
        "narrateur|Il ne part pas dans le thym.",
        "narrateur|Il arrive dans les mains de papa.",
        "enfant-f|Tu l'as !",
        "papa|Oui.",
        "papa|Comme les quilles.",
        "narrateur|La montagne est plus bleue, maintenant.",
        "narrateur|Un oiseau passe au-dessus des pins.",
        "enfant-f|On rejoue aux quilles ?",
        "papa|Un dernier rang.",
        "papa|Quand elles sont droites.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Les quilles sont blondes au soleil.",
        "papa|Et toi, tu as attendu.",
        "papa|Bravo, Nina.",
        "narrateur|Le romarin sent encore, tout bas.",
        "narrateur|Le bois tiède tient dans ses mains.",
    ],
}
preview("ATOM-JEU.REG.002-04", "N3", S04)
write_story(
    "ATOM-JEU.REG.002-04",
    "Nina veut faire tomber les quilles blondes. Elle lance trop tôt, "
    "une quille part dans le romarin. Ils attendent un peu. Toc. Plus tard, "
    "le ballon rouge ne part pas dans le thym.",
    "Les quilles dans le romarin",
    "Nina, papa",
    "jardin de montagne, pins, gravier, après-midi",
    S04,
    {},
    q_attend("Nina", elle=True),
)
relecture(
    "ATOM-JEU.REG.002-04",
    "Les quilles dans le romarin",
    "Nina veut les quilles. Quille dans le romarin. On attend un peu. "
    "Toc. Puis le ballon, mêmes mains ouvertes.",
    "Sans le mot règle. Deux jeux vécus, pas une leçon répétée. Fin = bois tiède.",
)


# ---------------------------------------------------------------------------
# 05 N2 Nino, papa — salon de ville, pluie, tour de cubes
# ---------------------------------------------------------------------------
S05 = {
    "CHK_T0000_P0000": [
        "narrateur|La pluie tape la vitre du salon.",
        "narrateur|Ça sent la soupe, tout bas.",
        "narrateur|Le tapis rouge est un peu rêche.",
        "narrateur|Un radiateur chauffe près du mur.",
        "narrateur|Les cubes de bois sont dans une boîte.",
        "narrateur|La boîte sent le sapin.",
        "papa|Nino, tu vois les cubes ?",
        "enfant-m|Oui, papa.",
        "enfant-m|Je veux une tour.",
        "narrateur|Papa pose déjà un cube bleu.",
        "narrateur|Le cube jaune est encore dans sa main.",
        "narrateur|En ce moment, Nino se penche.",
        "enfant-m|Le rouge, en haut.",
        "papa|J'ai pas encore posé le jaune.",
        "narrateur|Nino pose le rouge trop vite.",
        "narrateur|La tour penche.",
        "narrateur|Elle tombe.",
        "narrateur|Les cubes roulent sous le canapé.",
        "enfant-m|Oh.",
        "enfant-m|Elle est par terre.",
        "papa|La tour s'est arrêtée.",
        "papa|On attend un peu ?",
        "narrateur|Nino s'arrête à genoux.",
        "narrateur|Le tapis gratte un peu.",
        "narrateur|La pluie tape encore, plus fort.",
        "enfant-m|Je les cherche ?",
        "papa|Oui.",
        "papa|Sous le canapé, tout doux.",
        "narrateur|Nino allonge le bras.",
        "narrateur|Le dessous est frais, un peu sombre.",
        "narrateur|Il touche un cube, puis l'autre.",
        "enfant-m|Le bleu.",
        "enfant-m|Le jaune.",
        "papa|On les remet, un par un.",
        "narrateur|Papa pose le bleu, bien à plat.",
        "papa|Tu attends que je sois prêt ?",
        "enfant-m|Oui.",
        "papa|On attend un peu.",
        "narrateur|Nino tient le cube rouge.",
        "narrateur|Le bois est lisse, un peu chaud.",
        "narrateur|La soupe sent encore, plus près.",
        "narrateur|La vitre est toute piquée de gouttes.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nino veut la tour.",
        "narrateur|Que fait-il d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Nino reste encore un peu.",
        "papa|Le bleu est à plat.",
        "papa|Tu peux poser le jaune.",
        "enfant-m|Le jaune.",
        "narrateur|Il pose tout doux.",
        "narrateur|La tour ne penche pas.",
        "papa|Maintenant le rouge ?",
        "enfant-m|Le rouge, en haut.",
        "narrateur|Nino attend que papa lâche.",
        "narrateur|Puis il pose.",
        "narrateur|La tour tient, toute droite.",
        "enfant-m|Elle est haute !",
        "papa|Oui.",
        "papa|Comme le fauteuil, presque.",
        "narrateur|Un cube vert reste dans la boîte.",
        "papa|Encore un ?",
        "enfant-m|Le vert.",
        "papa|On attend un peu.",
        "narrateur|Papa tient la base.",
        "narrateur|Nino compte, sans poser.",
        "papa|Maintenant.",
        "narrateur|Le vert se pose, tout léger.",
        "papa|Merci, Nino.",
        "enfant-m|Elle ne tombe plus.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On va voir la pluie ?",
        "enfant-m|Elle tape fort.",
        "narrateur|Ils s'approchent de la vitre.",
        "narrateur|Les gouttes glissent, l'une après l'autre.",
        "enfant-m|Comme les cubes.",
        "papa|Une, puis l'autre.",
        "narrateur|La tour reste au milieu du tapis.",
        "narrateur|Le radiateur fait un petit bruit.",
        "papa|On goûte la soupe ?",
        "enfant-m|Un peu.",
        "narrateur|La cuillère est tiède.",
        "narrateur|Ça sent la carotte.",
        "enfant-m|Elle est bonne.",
        "papa|La tour attend encore.",
        "enfant-m|Je rajoute un cube ?",
        "papa|Oui.",
        "papa|Quand je tiens le bas.",
        "narrateur|Ils reviennent au tapis.",
        "narrateur|Nino attend, le cube orange en main.",
        "papa|Tu es prêt ?",
        "enfant-m|Oui, papa.",
        "narrateur|Il pose.",
        "narrateur|La tour touche presque le fauteuil.",
        "enfant-m|Elle est grande.",
        "papa|Oui.",
        "papa|Un cube, puis l'autre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|La tour est plus haute que moi.",
        "papa|Et toi, tu as attendu.",
        "papa|Bravo, Nino.",
        "narrateur|La pluie tape encore la vitre.",
        "narrateur|Le bois de la tour sent le sapin.",
    ],
}
preview("ATOM-JEU.REG.002-05", "N2", S05)
write_story(
    "ATOM-JEU.REG.002-05",
    "Nino veut une tour de cubes pendant la pluie. Il pose trop tôt, "
    "la tour tombe sous le canapé. Ils attendent un peu. Un cube, puis "
    "l'autre. La tour sent le sapin, presque aussi haute que le fauteuil.",
    "La tour sous la pluie",
    "Nino, papa",
    "salon de ville, tapis rouge, pluie, soupe",
    S05,
    {},
    q_attend("Nino"),
)
relecture(
    "ATOM-JEU.REG.002-05",
    "La tour sous la pluie",
    "Nino veut la tour. Cubes sous le canapé. On attend un peu. "
    "Un cube puis l'autre, la tour tient.",
    "Sans le mot règle. Imprévu = chute. Fin = sapin et pluie.",
)


# ---------------------------------------------------------------------------
# 06 N3 Raphaël, papa — maison au bord de mer, cubes puis ballon
# ---------------------------------------------------------------------------
S06 = {
    "CHK_T0000_P0000": [
        "narrateur|Le sel de la mer entre par la fenêtre.",
        "narrateur|Les carreaux de la cuisine sont froids.",
        "narrateur|Une coquille sèche sur le rebord.",
        "narrateur|Dehors, les dunes font un bruit de sable.",
        "narrateur|Les cubes de bois sont près du seau.",
        "narrateur|Le seau sent encore la plage.",
        "papa|Raphaël, tu veux une tour ?",
        "enfant-m|Oui, papa.",
        "enfant-m|Plus haute que la coquille.",
        "narrateur|Papa pose un cube pâle.",
        "narrateur|Le suivant est encore dans sa main.",
        "narrateur|En ce moment, Raphaël se penche.",
        "enfant-m|Celui-là, en haut.",
        "papa|J'ai pas encore lâché.",
        "narrateur|Raphaël pose trop vite.",
        "narrateur|La tour penche vers le seau.",
        "narrateur|Elle tombe.",
        "narrateur|Un cube part sous la table.",
        "enfant-m|Oh.",
        "enfant-m|Elle est cassée.",
        "papa|La tour s'est arrêtée.",
        "papa|On attend un peu ?",
        "narrateur|Raphaël s'arrête à genoux.",
        "narrateur|Le carreau est froid sous les os.",
        "narrateur|Le sel pique un peu les lèvres.",
        "enfant-m|Je cherche le cube ?",
        "papa|Oui.",
        "papa|Sous la table, tout doux.",
        "narrateur|Raphaël rampe un peu.",
        "narrateur|Il touche le bois, collé de sable.",
        "enfant-m|Je l'ai.",
        "papa|On recommence, un par un.",
        "narrateur|Papa pose le cube pâle, bien à plat.",
        "papa|Tu attends que je sois prêt ?",
        "enfant-m|Oui.",
        "papa|On attend un peu.",
        "narrateur|Raphaël tient le cube, sans le poser.",
        "narrateur|La coquille ne bouge pas sur le rebord.",
        "narrateur|Les dunes chantent encore, plus loin.",
        "narrateur|Une mouette crie, tout haut.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Raphaël veut la tour.",
        "narrateur|Que fait-il d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Raphaël reste encore un peu.",
        "papa|Le bas est à plat.",
        "papa|Tu peux poser.",
        "enfant-m|J'y vais.",
        "narrateur|Il pose tout doux.",
        "narrateur|La tour ne penche pas.",
        "enfant-m|Plus haute que la coquille.",
        "papa|Oui.",
        "papa|Un cube, puis l'autre.",
        "narrateur|Le bois sent le sel, un peu.",
        "narrateur|La tour tient près du seau.",
        "papa|Plus tard, le ballon dehors ?",
        "enfant-m|Le ballon de la terrasse.",
        "papa|On attend un peu, d'abord.",
        "narrateur|Ils regardent encore la tour.",
        "narrateur|Elle ne tombe pas.",
        "papa|Merci, Raphaël.",
        "enfant-m|Elle est droite.",
        "narrateur|Une mouette passe devant la fenêtre.",
        "narrateur|Son ombre traverse les cubes.",
        "papa|On sort les pieds nus ?",
        "enfant-m|Oui.",
        "enfant-m|Le sable est chaud.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La terrasse donne sur les dunes.",
        "narrateur|Le bois des lames est chaud, un peu rêche.",
        "narrateur|Le ballon jaune attend près du bac.",
        "enfant-m|Je le prends.",
        "papa|Attends un peu.",
        "narrateur|Raphaël s'arrête.",
        "narrateur|Le vent pousse déjà le ballon.",
        "papa|Si on lance trop tôt, il va au sable.",
        "enfant-m|Comme le cube, sous la table.",
        "papa|Oui.",
        "papa|Mes mains sont ouvertes.",
        "papa|Tu es prêt ?",
        "enfant-m|Oui, papa.",
        "narrateur|Il envoie le ballon, tout doux.",
        "narrateur|Le ballon ne part pas vers les dunes.",
        "narrateur|Il revient dans les mains de papa.",
        "enfant-m|Tu l'as !",
        "papa|Oui.",
        "papa|Comme la tour.",
        "narrateur|La mer fait un bruit rond, tout près.",
        "narrateur|Le sel colle encore aux cheveux.",
        "enfant-m|On relance ?",
        "papa|Oui.",
        "papa|Quand j'ai les mains.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le ballon est jaune comme le sable.",
        "papa|Et toi, tu as attendu.",
        "papa|Bravo, Raphaël.",
        "narrateur|La mer chante encore, tout bas.",
        "narrateur|La tour tient derrière la fenêtre.",
    ],
}
preview("ATOM-JEU.REG.002-06", "N3", S06)
write_story(
    "ATOM-JEU.REG.002-06",
    "Raphaël veut une tour plus haute que la coquille, puis le ballon "
    "sur la terrasse. Il pose trop tôt, un cube part sous la table. "
    "Ils attendent un peu. La tour tient. Le ballon jaune ne part pas aux dunes.",
    "La tour et le ballon salé",
    "Raphaël, papa",
    "maison au bord de mer, cuisine puis terrasse, matin",
    S06,
    {},
    q_attend("Raphaël"),
)
relecture(
    "ATOM-JEU.REG.002-06",
    "La tour et le ballon salé",
    "Raphaël veut la tour, puis le ballon. Cube sous la table. "
    "On attend un peu. Terrasse : le ballon ne va pas aux dunes.",
    "Sans le mot règle. Deux jeux, sel et dunes. Fin = mer et tour derrière la vitre.",
)


# ---------------------------------------------------------------------------
# 07 N3 Victorino, maman — cour de ferme, poules, cerceau
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|Une poule rousse picore près du cerceau.",
        "narrateur|La cour de la ferme sent le foin chaud.",
        "narrateur|Le mur de pierre est encore tiède.",
        "narrateur|Le soir descend, tout orange.",
        "narrateur|Un seau de grain cliquette, un peu.",
        "narrateur|Le cerceau vert est posé contre le puits.",
        "maman|Victorino, tu vois le cerceau ?",
        "enfant-m|Oui, maman.",
        "enfant-m|Je veux passer.",
        "narrateur|Maman prend déjà le cerceau.",
        "narrateur|Elle n'a pas encore les deux mains.",
        "narrateur|En ce moment, Victorino court.",
        "enfant-m|Comme un tunnel.",
        "maman|J'ai pas encore tenu.",
        "narrateur|Victorino pousse le cerceau trop vite.",
        "narrateur|Le cerceau tombe.",
        "narrateur|Il tape le seau.",
        "narrateur|Le grain s'éparpille.",
        "narrateur|La poule rousse s'envole, tout bas.",
        "enfant-m|Oh.",
        "enfant-m|Elle a peur.",
        "maman|Le jeu s'est arrêté.",
        "maman|On attend un peu ?",
        "narrateur|Victorino s'arrête près du puits.",
        "narrateur|La pierre est rêche sous la main.",
        "narrateur|Ça sent le grain, tout fort.",
        "enfant-m|Je ramasse le grain ?",
        "maman|Oui.",
        "maman|Pour la poule, tout doux.",
        "narrateur|Il ramasse des grains, un par un.",
        "narrateur|Ils sont secs, un peu ronds.",
        "narrateur|La poule revient, la tête penchée.",
        "enfant-m|Elle est là.",
        "maman|Elle attend, elle aussi.",
        "narrateur|Maman tient le cerceau, cette fois.",
        "narrateur|Ses deux mains sont dessus.",
        "maman|Tu attends que je sois prête ?",
        "enfant-m|Oui.",
        "maman|On attend un peu.",
        "narrateur|Victorino reste les pieds dans la poussière.",
        "narrateur|Il regarde le trou vert.",
        "narrateur|La poule picore, tout calme.",
        "narrateur|Le mur orange tient la chaleur.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Victorino veut passer.",
        "narrateur|Que fait-il d'abord ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Victorino reste encore un peu.",
        "maman|J'ai les deux mains.",
        "maman|Tu peux passer.",
        "enfant-m|J'y vais.",
        "narrateur|Il plie les genoux.",
        "narrateur|Il passe dans le trou vert.",
        "narrateur|Le cerceau ne tombe pas.",
        "enfant-m|Je suis passé !",
        "maman|Oui.",
        "maman|Il est resté debout.",
        "narrateur|La poule picore près du seau.",
        "narrateur|Elle n'a plus peur.",
        "maman|Encore une fois ?",
        "enfant-m|Encore.",
        "maman|On attend un peu.",
        "narrateur|Maman replace le cerceau.",
        "narrateur|Victorino compte, sans courir.",
        "narrateur|Un.",
        "narrateur|Deux.",
        "maman|Maintenant.",
        "narrateur|Il passe encore.",
        "narrateur|Ses cheveux touchent le plastique.",
        "maman|Merci, Victorino.",
        "enfant-m|C'est un tunnel.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|On donne le reste du grain ?",
        "enfant-m|Pour la poule.",
        "narrateur|Victorino tend le poing, tout doux.",
        "narrateur|Les grains tombent près des pattes.",
        "narrateur|La poule picore, un grain, puis l'autre.",
        "enfant-m|Elle attend, elle aussi.",
        "maman|Oui.",
        "maman|Un peu, puis elle mange.",
        "narrateur|Le cerceau vert attend contre le puits.",
        "enfant-m|Je repasse ?",
        "maman|Oui.",
        "maman|Quand je tiens bien.",
        "narrateur|Ils reviennent près du mur tiède.",
        "narrateur|Le soir est plus orange, maintenant.",
        "narrateur|Victorino attend, les mains ouvertes.",
        "maman|Tu es prêt ?",
        "enfant-m|Oui, maman.",
        "narrateur|Il passe tout droit.",
        "narrateur|Le plastique reste chaud.",
        "narrateur|Une autre poule arrive, plus sombre.",
        "enfant-m|Elles regardent.",
        "maman|Oui.",
        "maman|Le jeu a repris.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le tunnel est vert au soir.",
        "maman|Et toi, tu as attendu.",
        "maman|Bravo, Victorino.",
        "narrateur|Le foin sent encore, tout chaud.",
        "narrateur|La poule rousse picore près du cerceau.",
    ],
}
preview("ATOM-JEU.REG.002-07", "N3", S07)
write_story(
    "ATOM-JEU.REG.002-07",
    "Victorino veut passer dans le cerceau vert de la ferme. Il pousse trop tôt, "
    "le cerceau tombe, le grain s'éparpille, la poule a peur. Ils attendent un peu. "
    "Maman tient, il passe. La poule picore, le soir est orange.",
    "Le cerceau des poules",
    "Victorino, maman",
    "cour de ferme, puits, soir d'été",
    S07,
    {},
    q_attend("Victorino"),
)
relecture(
    "ATOM-JEU.REG.002-07",
    "Le cerceau des poules",
    "Victorino veut le tunnel. Cerceau tombé, grain, poule qui s'envole. "
    "On attend un peu. Il passe, le foin sent.",
    "Sans le mot règle. Imprévu = chute et poule. Fin = soir orange et poule.",
)
