#!/usr/bin/env python3
"""F-NAR-009 — merged.json pour 8 atomiques SAN.MOV / SAN.SOM."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIMITS = {"N1": 10, "N2": 15, "N3": 18}
ROLES = {"narrateur", "papa", "maman", "enfant-m", "enfant-f"}
FORBIDDEN = (
    "on va apprendre",
    "voici le geste",
    "papa sourit",
    "maman sourit",
    "papa est là",
    "maman est là",
    "il était une fois",
    "ceci est l'histoire",
    "aujourd'hui,",
)
BAD_NAMES = (
    "rania", "kilian", "béatrice", "beatrice", "bruno", "brice",
    "inès", "ines", "maya", "jules", "théo", "theo", "océane",
    "oceane", "malo", "tom ", "léa", "lea ", "lina", "iris",
)


def words(s: str) -> int:
    return len(s.replace("'", " ").replace("’", " ").replace("-", " ").split())


def from_script(lines: list[str]) -> tuple[str, str]:
    phrases, out = [], []
    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        role, phrase = raw.split("|", 1)
        phrase = phrase.strip()
        out.append(f"{role}|{phrase}")
        phrases.append(phrase)
    return " ".join(phrases), "\n".join(out)


def make_chunk(src: dict, lines: list[str], sons) -> dict:
    text, script = from_script(lines)
    nc = dict(src)
    nc["text"] = text
    nc["script"] = script
    nc["sons"] = sons if sons is not None else (src.get("sons") or "")
    if nc["sons"] is None:
        nc["sons"] = ""
    return nc


def check(sid: str, age: str, chunks: list[dict], need_msgs: tuple[str, ...]) -> None:
    lim = LIMITS[age]
    joined = "\n".join(c["script"] for c in chunks)
    low = joined.lower()
    for bad in FORBIDDEN:
        if bad in low:
            raise SystemExit(f"{sid} interdit: {bad}")
    for name in BAD_NAMES:
        if name in low:
            raise SystemExit(f"{sid} prénom hors troupe: {name}")
    adults = [ln for ln in joined.splitlines() if ln.startswith("papa|") or ln.startswith("maman|")]
    if not adults:
        raise SystemExit(f"{sid}: aucun papa/maman")
    aj = " ".join(a.split("|", 1)[1] for a in adults).lower()
    if "bravo" not in aj and "bon travail" not in aj:
        raise SystemExit(f"{sid}: pas de félicitation")
    if not any("?" in a for a in adults):
        raise SystemExit(f"{sid}: aucune question d'adulte")
    all_text = " ".join(c["text"] for c in chunks).lower()
    for m in need_msgs:
        if m.lower() not in all_text:
            raise SystemExit(f"{sid}: message manquant: {m}")
    nwords = sum(words(c["text"]) for c in chunks)
    if nwords < 380:
        raise SystemExit(f"{sid}: trop court ({nwords} mots)")
    for c in chunks:
        rebuilt, _ = from_script(c["script"].splitlines())
        if rebuilt != c["text"]:
            raise SystemExit(f"{sid} {c['chunk_id']}: text ≠ script")
        for ln in c["script"].splitlines():
            if "|" not in ln:
                raise SystemExit(f"{sid} ligne sans | : {ln}")
            role, phrase = ln.split("|", 1)
            if role not in ROLES:
                raise SystemExit(f"{sid} rôle {role}")
            n = words(phrase)
            if n > lim:
                raise SystemExit(f"{sid} {c['chunk_id']} {n}>{lim}: {phrase}")
            if n == 0:
                raise SystemExit(f"{sid} phrase vide")
            if not phrase.endswith((".", "?", "!")):
                raise SystemExit(f"{sid} sans ponctuation: {phrase}")
            if phrase.count(".") + phrase.count("?") + phrase.count("!") > 1:
                raise SystemExit(f"{sid} plusieurs phrases: {phrase}")
    print(f"OK {sid} {nwords} mots")


def write_story(sid: str, fil: str, title: str, chars: str, setting: str,
                scripts: dict, sons: dict, secondary: str | None = None) -> None:
    folder = ROOT / sid
    src = json.loads((folder / "source.json").read_text(encoding="utf-8"))
    by = {}
    missing = [c["chunk_id"] for c in src["chunks"] if c["chunk_id"] not in scripts]
    extra = set(scripts) - {c["chunk_id"] for c in src["chunks"]}
    if missing or extra:
        raise SystemExit(f"{sid} chunks missing={missing} extra={extra}")
    for c in src["chunks"]:
        cid = c["chunk_id"]
        by[cid] = make_chunk(c, scripts[cid], sons.get(cid, c.get("sons") or ""))
    out = dict(src)
    out["fil_rouge"] = fil
    out["title"] = title
    out["characters"] = chars
    out["setting"] = setting
    if secondary:
        out["secondary_lessons"] = secondary
    out["chunks"] = [by[c["chunk_id"]] for c in src["chunks"]]
    age = out["age_band"]
    need = {
        "SAN.MOV.001": ("dehors", "avec un adulte"),
        "SAN.SOM.001": ("soir", "pyjama", "dodo"),
    }[out["lesson_id"]]
    check(sid, age, out["chunks"], need)
    (folder / "merged.json").write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# ATOM-SAN.MOV.001-05 N2 Mila, maman, jardin, brouette, cerisier
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.MOV.001-05",
    "La gouttière chante encore. Mila et maman vont au jardin. La brouette attend sous le cerisier. Elles jouent dehors, avec un adulte.",
    "La brouette sous le cerisier",
    "Mila, maman",
    "jardin après la pluie, cerisier, petite brouette",
    {
        "CHK_T0000_P0000": [
            "narrateur|La gouttière chante encore.",
            "narrateur|Une goutte.",
            "narrateur|Puis une autre.",
            "narrateur|Les tuiles brillent, toutes mouillées.",
            "narrateur|L'herbe sent le vert coupé.",
            "narrateur|Une coccinelle marche sur la vitre.",
            "narrateur|Elle est rouge, avec des points.",
            "narrateur|Mila vit ici, avec maman.",
            "narrateur|Les chaussures attendent près du paillasson.",
            "narrateur|Elles sont encore un peu humides.",
            "enfant-f|Maman, la gouttière chante !",
            "maman|Oui.",
            "maman|La pluie est finie.",
            "maman|Tu vois la coccinelle ?",
            "enfant-f|Oui.",
            "enfant-f|Elle est rouge.",
            "narrateur|En ce moment, les pieds de Mila gigotent.",
            "narrateur|Ils veulent l'herbe fraîche.",
            "maman|On va dehors, Mila ?",
            "enfant-f|Oui, maman.",
            "maman|On y va ensemble.",
            "narrateur|Maman tend la petite veste.",
            "narrateur|La veste est douce, un peu chaude.",
            "maman|Tu mets tes chaussures ?",
            "narrateur|Mila enfile la gauche.",
            "narrateur|Puis la droite.",
            "narrateur|Les lacets font un petit bruit.",
            "maman|Tu as fini tes chaussures ?",
            "enfant-f|Oui.",
            "maman|Bravo, Mila.",
            "narrateur|Maman ouvre la porte du jardin.",
            "narrateur|L'air sent l'herbe coupée.",
            "narrateur|Un merle chante tout près.",
            "enfant-f|Ça sent bon !",
            "maman|Oui.",
            "maman|Ça sent le jardin.",
            "narrateur|Le cerisier a des feuilles luisantes.",
            "narrateur|Une goutte tombe d'une feuille.",
            "narrateur|Sous l'arbre, la petite brouette attend.",
            "narrateur|Elle est rouge, un peu piquée.",
            "enfant-f|La brouette !",
            "maman|Elle t'attendait.",
            "maman|On joue dehors, avec un adulte.",
            "narrateur|Mila pousse la brouette.",
            "narrateur|Les roues font un bruit doux.",
            "narrateur|Cric, cric, sur l'herbe.",
            "maman|Tu pousses bien.",
            "maman|Je reste près de toi.",
            "narrateur|Mila court un peu sur l'herbe.",
            "narrateur|L'herbe chatouille ses chevilles.",
            "narrateur|Elle saute près du cerisier.",
            "narrateur|Maman reste tout près.",
            "maman|Tu cours dehors, avec moi.",
            "enfant-f|Je joue dehors, avec un adulte.",
            "maman|Oui.",
            "maman|Bravo.",
            "narrateur|Une balle bleue dort dans l'herbe.",
            "narrateur|Elle est un peu mouillée.",
            "maman|Tu veux la lancer ?",
            "enfant-f|Oui !",
            "narrateur|Mila lance la balle.",
            "narrateur|Maman la renvoie.",
            "narrateur|La balle fait un petit ploc.",
            "maman|Bien lancé, Mila.",
            "narrateur|Elles jouent un moment.",
            "narrateur|Les joues de Mila deviennent roses.",
            "narrateur|Son corps est content de bouger.",
            "maman|Tu as soif ?",
            "enfant-f|Un peu.",
            "maman|On rentre ensemble, alors.",
            "narrateur|Mila pose la balle dans la brouette.",
            "narrateur|Elles marchent vers la porte.",
            "narrateur|La gouttière chante encore, tout doux.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila veut bouger.",
            "narrateur|Où joue-t-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila a joué dehors.",
            "narrateur|Maman, un adulte, était avec elle.",
            "narrateur|Le corps a bougé.",
            "maman|Tu as joué dehors, avec un adulte ?",
            "enfant-f|Oui, maman.",
            "enfant-f|Dehors.",
            "maman|Bravo, Mila.",
            "maman|Tu as fait du bon travail.",
            "narrateur|La brouette reste sous le cerisier.",
            "narrateur|Les roues sont encore un peu humides.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Dans la cuisine, un verre d'eau attend.",
            "maman|Tu bois un peu d'eau ?",
            "narrateur|Mila boit une gorgée.",
            "narrateur|L'eau est fraîche.",
            "enfant-f|Merci, maman.",
            "maman|Merci, Mila.",
            "maman|Tu ranges la balle ?",
            "narrateur|Mila pose la balle près des chaussures.",
            "narrateur|Le paillasson sent l'herbe.",
            "maman|Tu as fini de ranger ?",
            "enfant-f|Oui.",
            "maman|Bravo.",
            "narrateur|Une goutte glisse encore sur la vitre.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai poussé la brouette.",
            "enfant-f|J'ai joué dehors.",
            "maman|Avec un adulte.",
            "maman|Bravo.",
            "maman|C'est du bon travail.",
            "narrateur|Le cerisier garde encore une goutte.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "gouttiere,brouette",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    "SAN.ALI.003",
)

# ---------------------------------------------------------------------------
# ATOM-SAN.MOV.001-06 N2 Nino, papa, pré, cerceau bleu
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.MOV.001-06",
    "Une abeille tape à la vitre. Derrière la haie, le pré est doré. Nino et papa emmènent le cerceau bleu. Ils jouent dehors, avec un adulte.",
    "Le cerceau bleu dans le pré",
    "Nino, papa",
    "pré près de la maison, haie, cerceau bleu",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une abeille tape à la vitre.",
            "narrateur|Elle fait un petit bzz.",
            "narrateur|Derrière la haie, le pré est doré.",
            "narrateur|Les herbes hautes bougent au vent.",
            "narrateur|Une clochette tinte, très loin.",
            "narrateur|Le chapeau de paille pend au crochet.",
            "narrateur|Nino vit ici, avec papa.",
            "narrateur|Le cerceau bleu attend près des bottes.",
            "enfant-m|Papa, l'abeille tape !",
            "papa|Oui.",
            "papa|Elle veut les fleurs.",
            "papa|Tu vois le pré, derrière la haie ?",
            "enfant-m|Oui.",
            "enfant-m|C'est tout jaune.",
            "narrateur|En ce moment, les jambes de Nino gigotent.",
            "narrateur|Elles veulent l'herbe haute.",
            "papa|On va dehors, Nino ?",
            "enfant-m|Oui, papa.",
            "papa|On y va ensemble.",
            "papa|On joue dehors, avec un adulte.",
            "narrateur|Ils mettent les chaussures près de la porte.",
            "narrateur|Les semelles sentent encore la terre.",
            "papa|Tu as fini tes chaussures ?",
            "enfant-m|Oui.",
            "papa|Bravo.",
            "narrateur|Papa prend le cerceau bleu.",
            "narrateur|Le plastique est lisse et frais.",
            "enfant-m|Il est bleu, papa.",
            "papa|Oui.",
            "papa|Ton cerceau.",
            "narrateur|Ils ouvrent le petit portail.",
            "narrateur|Le portail fait un grincement doux.",
            "narrateur|Dehors, l'air sent l'herbe chaude.",
            "narrateur|Les oiseaux chantent dans la haie.",
            "enfant-m|Ça sent le foin !",
            "papa|Oui.",
            "papa|Le pré sent le soleil.",
            "narrateur|Nino court sur l'herbe.",
            "narrateur|Les tiges lui chatouillent les genoux.",
            "narrateur|Papa reste près de lui.",
            "papa|Je reste tout près.",
            "narrateur|Nino fait tourner le cerceau.",
            "narrateur|Le cerceau roule, puis tombe.",
            "narrateur|Il fait un petit toc dans l'herbe.",
            "papa|Tu le relances ?",
            "enfant-m|Oui !",
            "narrateur|Nino relance le cerceau.",
            "narrateur|Papa tapote dans ses mains.",
            "papa|Bien roulé, Nino.",
            "enfant-m|Je joue dehors, avec un adulte.",
            "papa|Oui.",
            "papa|Bravo.",
            "narrateur|Un papillon jaune passe tout bas.",
            "narrateur|Nino le suit de l'œil.",
            "papa|Tu le vois, le papillon ?",
            "enfant-m|Oui.",
            "enfant-m|Il est jaune.",
            "narrateur|Ils jouent un moment.",
            "narrateur|Nino sent son corps content.",
            "narrateur|Ses joues sont chaudes.",
            "papa|Tu as assez bougé ?",
            "enfant-m|Encore un peu.",
            "papa|Encore un tour de cerceau, alors.",
            "narrateur|Le cerceau roule une dernière fois.",
            "narrateur|Il s'arrête près de la haie.",
            "papa|On rentre ensemble ?",
            "enfant-m|Oui, papa.",
            "narrateur|Nino porte le cerceau.",
            "narrateur|Le portail se referme, tout doux.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino veut bouger.",
            "narrateur|Où joue-t-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino a joué dehors.",
            "narrateur|Papa, un adulte, était avec lui.",
            "narrateur|Le corps a bougé.",
            "papa|Tu as joué dehors, avec un adulte ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Dehors.",
            "papa|Bravo, Nino.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le cerceau bleu repose près des bottes.",
            "narrateur|Il garde un brin d'herbe.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sur la table, un verre d'eau attend.",
            "papa|Tu bois un peu d'eau ?",
            "narrateur|Nino boit une gorgée.",
            "narrateur|L'eau est fraîche.",
            "enfant-m|Merci, papa.",
            "papa|Tu ranges le cerceau ?",
            "narrateur|Nino accroche le cerceau au clou.",
            "papa|Tu as fini de ranger ?",
            "enfant-m|Oui.",
            "papa|Bravo.",
            "narrateur|L'abeille s'éloigne vers les fleurs.",
            "narrateur|Le pré reste doré, derrière la haie.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai fait tourner le cerceau.",
            "enfant-m|J'ai joué dehors.",
            "papa|Avec un adulte.",
            "papa|Bravo.",
            "papa|C'est du bon travail.",
            "narrateur|Le chapeau de paille pend encore.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "abeille,cerceau",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    "SAN.ALI.003",
)

# ---------------------------------------------------------------------------
# ATOM-SAN.MOV.001-07 N2 Sarah, papa, jardin, ballon jaune, bottes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.MOV.001-07",
    "La soupe a embué la vitre. Deux bottes jaunes attendent comme des bateaux. Sarah et papa vont au jardin avec le ballon. Ils jouent dehors, avec un adulte.",
    "Les bottes jaunes de Sarah",
    "Sarah, papa",
    "jardin, bottes jaunes, ballon, vitre embuée",
    {
        "CHK_T0000_P0000": [
            "narrateur|La soupe a embué la vitre.",
            "narrateur|Un petit nuage colle au verre.",
            "narrateur|On voit le jardin, tout flou.",
            "narrateur|Deux bottes jaunes attendent au paillasson.",
            "narrateur|On dirait deux petits bateaux.",
            "narrateur|La veste de papa sent le bois.",
            "narrateur|Sarah vit ici, avec papa.",
            "enfant-f|Papa, la vitre est toute blanche !",
            "papa|Oui.",
            "papa|La soupe a fait un nuage.",
            "papa|Tu vois tes bottes, là ?",
            "enfant-f|Oui.",
            "enfant-f|Deux bateaux jaunes.",
            "narrateur|En ce moment, Sarah essuie un rond.",
            "narrateur|Le jardin redevient net.",
            "narrateur|Le ballon jaune brille dans l'herbe.",
            "papa|On va dehors, Sarah ?",
            "enfant-f|Oui, papa.",
            "papa|On y va ensemble.",
            "papa|On joue dehors, avec un adulte.",
            "narrateur|Ils mettent les bottes près de la porte.",
            "narrateur|Les bottes font un bruit de caoutchouc.",
            "papa|Tu as fini tes bottes ?",
            "enfant-f|Oui.",
            "papa|Bravo, Sarah.",
            "narrateur|Papa prend le ballon jaune.",
            "narrateur|Il est lisse, un peu froid.",
            "enfant-f|Il est jaune, papa.",
            "papa|Oui.",
            "papa|Comme tes bottes.",
            "narrateur|Ils ouvrent la porte du jardin.",
            "narrateur|L'air sent l'herbe et la soupe, encore.",
            "narrateur|Les oiseaux chantent sur le toit.",
            "enfant-f|Ça sent l'herbe !",
            "papa|Oui.",
            "papa|Et un peu la soupe.",
            "narrateur|Sarah court sur l'herbe.",
            "narrateur|Les bottes font flop, flop.",
            "narrateur|Papa reste près d'elle.",
            "papa|Je reste avec toi.",
            "narrateur|Sarah tape le ballon.",
            "narrateur|Le ballon roule vers papa.",
            "narrateur|Papa le renvoie.",
            "papa|Bien tapé.",
            "enfant-f|Je joue dehors, avec un adulte.",
            "papa|Oui.",
            "papa|Bravo.",
            "narrateur|Une feuille mouillée colle à une botte.",
            "narrateur|Sarah la montre.",
            "enfant-f|Une feuille, papa !",
            "papa|Elle est verte et brillante.",
            "narrateur|Ils jouent un moment.",
            "narrateur|Sarah sent son corps content.",
            "narrateur|Ses joues sont chaudes.",
            "papa|Tu as les joues roses.",
            "papa|On rentre ensemble ?",
            "enfant-f|Encore un peu.",
            "papa|Encore une passe, alors.",
            "narrateur|Sarah tape encore le ballon.",
            "narrateur|Papa tape des mains.",
            "papa|On rentre, maintenant.",
            "narrateur|Sarah porte le ballon contre son ventre.",
            "narrateur|Les bottes jaunes reviennent au paillasson.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah veut bouger.",
            "narrateur|Où joue-t-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah a joué dehors.",
            "narrateur|Papa, un adulte, était avec elle.",
            "narrateur|Le corps a bougé.",
            "papa|Tu as joué dehors, avec un adulte ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Dehors.",
            "papa|Bravo, Sarah.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Les bottes jaunes sèchent au paillasson.",
            "narrateur|Une feuille reste collée.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa verse un peu d'eau.",
            "papa|Tu bois un peu d'eau ?",
            "narrateur|Sarah boit une gorgée.",
            "narrateur|L'eau est tiède, un peu.",
            "enfant-f|Merci, papa.",
            "papa|Tu ranges le ballon ?",
            "narrateur|Sarah pose le ballon près des bottes.",
            "papa|Tu as fini de ranger ?",
            "enfant-f|Oui.",
            "papa|Bravo.",
            "narrateur|La vitre n'a plus de nuage.",
            "narrateur|Le jardin est net, tout vert.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai tapé le ballon jaune.",
            "enfant-f|J'ai joué dehors.",
            "papa|Avec un adulte.",
            "papa|Bravo.",
            "papa|C'est du bon travail.",
            "narrateur|Les deux bateaux jaunes se reposent.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "bottes,ballon",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    "SAN.ALI.003",
)

# ---------------------------------------------------------------------------
# ATOM-SAN.MOV.001-08 N2 Raphaël, papa, jardin après goûter
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.MOV.001-08",
    "Des miettes restent sur la table. Une mouche tourne autour du pot de confiture. La poignée du jardin est chaude. Raphaël et papa jouent au ballon dehors, avec un adulte.",
    "Les miettes et le ballon",
    "Raphaël, papa",
    "cuisine puis jardin, après le goûter",
    {
        "CHK_T0000_P0000": [
            "narrateur|Des miettes dorées restent sur la table.",
            "narrateur|Le bois sent le gâteau.",
            "narrateur|Une mouche tourne autour du pot.",
            "narrateur|Le pot de confiture est collant.",
            "narrateur|La poignée du jardin est chaude.",
            "narrateur|Le soleil l'a touchée.",
            "narrateur|Un rayon glisse sur le carrelage.",
            "narrateur|Il est long, tout jaune.",
            "narrateur|Raphaël vit ici, avec papa.",
            "enfant-m|Papa, la mouche tourne !",
            "papa|Oui.",
            "papa|Elle aime le sucre.",
            "papa|Tu as fini ton goûter ?",
            "enfant-m|Oui, papa.",
            "narrateur|En ce moment, les jambes de Raphaël bougent.",
            "narrateur|Sous la table, ses pieds tapent.",
            "papa|Tes jambes veulent dehors ?",
            "enfant-m|Oui !",
            "papa|On va dehors, alors.",
            "papa|On y va ensemble.",
            "papa|On joue dehors, avec un adulte.",
            "narrateur|Ils poussent la porte du jardin.",
            "narrateur|L'air est frais, après le gâteau.",
            "narrateur|L'herbe sent le vert.",
            "enfant-m|Ça sent l'herbe, papa.",
            "papa|Oui.",
            "papa|Tout vert.",
            "narrateur|Un ballon rouge attend dans l'herbe.",
            "narrateur|Il a une tache de soleil.",
            "enfant-m|Le ballon !",
            "papa|Il t'attendait.",
            "narrateur|Raphaël court jusqu'au ballon.",
            "narrateur|Papa reste près de lui.",
            "papa|Je reste avec toi.",
            "narrateur|Raphaël tape le ballon.",
            "narrateur|Les pieds tapent l'herbe.",
            "narrateur|Papa le renvoie.",
            "papa|Bien tapé, Raphaël.",
            "enfant-m|Je joue dehors, avec un adulte.",
            "papa|Oui.",
            "papa|Bravo.",
            "narrateur|Raphaël souffle un peu.",
            "narrateur|Il rit.",
            "papa|Encore un moment dehors ?",
            "enfant-m|Oui !",
            "narrateur|Raphaël saute.",
            "narrateur|Il touche une feuille basse.",
            "narrateur|La feuille est lisse et tiède.",
            "papa|Tu vois la feuille ?",
            "enfant-m|Oui.",
            "enfant-m|Elle est douce.",
            "narrateur|Ils jouent encore.",
            "narrateur|Les joues de Raphaël deviennent chaudes.",
            "papa|Tes joues sont chaudes.",
            "papa|On rentre ?",
            "enfant-m|Oui, papa.",
            "narrateur|Raphaël range le ballon près du bac.",
            "narrateur|Une miette est encore collée à sa manche.",
            "papa|Tu as bougé dehors, avec un adulte.",
            "enfant-m|Oui.",
            "papa|Bravo.",
            "narrateur|La poignée est encore chaude.",
            "narrateur|Ils rentrent ensemble.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël veut bouger.",
            "narrateur|Où joue-t-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël a joué dehors.",
            "narrateur|Papa, l'adulte, était avec lui.",
            "narrateur|Les jambes ont bougé.",
            "papa|Tu as joué dehors, avec un adulte ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Dehors.",
            "papa|Bravo, Raphaël.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le ballon rouge se repose près du bac.",
            "narrateur|L'herbe a laissé une tache verte.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa verse un verre d'eau.",
            "papa|Tu bois un peu d'eau ?",
            "narrateur|Raphaël boit une gorgée.",
            "narrateur|Il sent encore l'herbe sur ses chaussures.",
            "enfant-m|Merci, papa.",
            "papa|Tu as fini de boire ?",
            "enfant-m|Oui.",
            "papa|Bravo.",
            "narrateur|Les miettes ne sont plus sur la table.",
            "narrateur|Le pot de confiture a un couvercle.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai tapé le ballon.",
            "enfant-m|J'ai joué dehors.",
            "papa|Avec un adulte.",
            "papa|Bravo.",
            "papa|C'est du bon travail.",
            "narrateur|La poignée du jardin refroidit.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "porte_jardin,ballon",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    "SAN.ALI.003",
)

# ---------------------------------------------------------------------------
# ATOM-SAN.MOV.001-09 N2 Aniss, maman, square, marelle
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.MOV.001-09",
    "Les platanes jettent des ronds d'ombre. Une marelle rose attend sur les dalles. Aniss et maman sautent dehors, avec un adulte.",
    "La marelle rose du square",
    "Aniss, maman",
    "square, marelle à la craie, platanes",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les platanes jettent des ronds d'ombre.",
            "narrateur|Les ronds bougent sur les dalles.",
            "narrateur|L'air sent la poussière chaude.",
            "narrateur|Une feuille sèche tourne au vent.",
            "narrateur|Elle fait un petit bruit de papier.",
            "narrateur|Une craie rose repose au bord.",
            "narrateur|Elle a déjà dessiné une marelle.",
            "narrateur|Le sac de maman sent le pain.",
            "narrateur|Aniss vit ici, tout près du square.",
            "enfant-m|Maman, les ronds bougent !",
            "maman|Oui.",
            "maman|Ce sont les feuilles.",
            "maman|Tu vois la marelle ?",
            "enfant-m|Oui.",
            "enfant-m|Elle est rose.",
            "narrateur|En ce moment, les jambes d'Aniss démangent.",
            "narrateur|Elles veulent sauter.",
            "maman|On va dehors, Aniss ?",
            "enfant-m|Oui, maman.",
            "maman|On y va ensemble.",
            "maman|On joue dehors, avec un adulte.",
            "narrateur|Ils marchent jusqu'au square.",
            "narrateur|Les chaussures font un bruit de gravier.",
            "narrateur|Un oiseau picore sous un banc.",
            "enfant-m|Un oiseau !",
            "maman|Il cherche des miettes.",
            "narrateur|La marelle attend au sol.",
            "narrateur|Les cases sont roses et bleues.",
            "narrateur|Un peu de craie craque sous le pied.",
            "maman|Tu sautes dans les cases ?",
            "enfant-m|Oui !",
            "narrateur|Aniss saute.",
            "narrateur|Un pied.",
            "narrateur|Puis deux pieds.",
            "narrateur|Maman reste près de lui.",
            "maman|Je reste avec toi.",
            "enfant-m|Je joue dehors, avec un adulte.",
            "maman|Oui.",
            "maman|Bravo.",
            "narrateur|Parce qu'Aniss a bougé, ses joues sont roses.",
            "narrateur|Il rit.",
            "maman|Encore un moment dehors ?",
            "enfant-m|Oui !",
            "narrateur|Aniss saute encore.",
            "narrateur|Il entend le craquement de la craie.",
            "maman|Tu entends la craie ?",
            "enfant-m|Oui.",
            "enfant-m|Ça craque.",
            "maman|Tu as bien sauté.",
            "narrateur|Un rond d'ombre glisse sur la case.",
            "narrateur|Aniss pose les deux pieds dedans.",
            "maman|Bravo, Aniss.",
            "narrateur|Quand il souffle fort, maman s'accroupit.",
            "maman|On rentre ensemble ?",
            "enfant-m|Oui, maman.",
            "narrateur|Aniss a joué dehors, avec un adulte.",
            "narrateur|La craie reste sur ses chaussures.",
            "narrateur|Ils quittent le square, tout près l'un de l'autre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss veut bouger.",
            "narrateur|Où joue-t-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss a joué dehors.",
            "narrateur|Maman, l'adulte, était avec lui.",
            "narrateur|Les jambes ont bougé.",
            "maman|Tu as joué dehors, avec un adulte ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Dehors.",
            "maman|Bravo, Aniss.",
            "maman|Tu as fait du bon travail.",
            "narrateur|La marelle rose reste au soleil.",
            "narrateur|Un rond d'ombre la traverse.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman tend une gourde.",
            "maman|Tu bois un peu d'eau ?",
            "narrateur|Aniss boit une gorgée.",
            "narrateur|La craie reste sur ses chaussures.",
            "enfant-m|Merci, maman.",
            "maman|Tu as fini de boire ?",
            "enfant-m|Oui.",
            "maman|Bravo.",
            "narrateur|Le sac de maman sent encore le pain.",
            "narrateur|Ils marchent vers la maison.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai sauté dans les cases.",
            "enfant-m|J'ai joué dehors.",
            "maman|Avec un adulte.",
            "maman|Bravo.",
            "maman|C'est du bon travail.",
            "narrateur|La craie rose attend le prochain saut.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "enfants_parc,craie",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    "SAN.ALI.003",
)

# ---------------------------------------------------------------------------
# ATOM-SAN.SOM.001-01 N1 Victorina, papa, maman, pyjama
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.SOM.001-01",
    "La lampe fait un rond jaune. Le doudou attend sur l'oreiller. Victorina met le pyjama. Puis c'est le dodo.",
    "Le doudou sur l'oreiller",
    "Victorina, papa, maman",
    "chambre le soir, lampe, doudou",
    {
        "CHK_T0000_P0000": [
            "narrateur|La lampe fait un rond.",
            "narrateur|Le rond est jaune.",
            "narrateur|Il est sur le mur.",
            "narrateur|La maison sent le savon.",
            "narrateur|Un grillon chante, dehors.",
            "narrateur|Les volets sentent le bois.",
            "narrateur|Le tapis est doux, un peu épais.",
            "narrateur|Le doudou attend.",
            "narrateur|Il est sur l'oreiller.",
            "narrateur|L'oreiller est tout blanc.",
            "narrateur|Victorina vit ici.",
            "narrateur|Avec papa et maman.",
            "maman|Victorina, tu vois le rond ?",
            "enfant-f|Oui, maman.",
            "enfant-f|Il est jaune.",
            "papa|C'est la lampe.",
            "papa|Un petit soleil, sur le mur.",
            "narrateur|En ce moment, le soir arrive.",
            "narrateur|Les volets sont fermés.",
            "narrateur|La rue devient calme.",
            "maman|Tu entends le grillon ?",
            "enfant-f|Oui.",
            "enfant-f|Il chante.",
            "maman|C'est l'heure.",
            "maman|On met le pyjama.",
            "enfant-f|Le pyjama ?",
            "maman|Oui.",
            "maman|Le pyjama doux.",
            "narrateur|Maman tend le pyjama.",
            "narrateur|Il est bleu, tout doux.",
            "narrateur|Il sent le savon.",
            "enfant-f|Ça sent bon.",
            "papa|Oui.",
            "papa|Ça sent le savon.",
            "papa|Tu mets le pantalon ?",
            "narrateur|Victorina enfile le pantalon.",
            "narrateur|Le coton est chaud.",
            "narrateur|Elle tire un peu.",
            "papa|Tu mets le haut ?",
            "narrateur|Elle enfile le haut.",
            "narrateur|Le col est tout doux.",
            "enfant-f|Il est doux, papa.",
            "papa|Oui.",
            "papa|Bravo.",
            "maman|Tu as mis le pyjama ?",
            "enfant-f|Oui, maman.",
            "maman|Bravo, Victorina.",
            "maman|Tu as fait du bon travail.",
            "narrateur|Papa ouvre le lit.",
            "narrateur|Le drap est frais.",
            "narrateur|Il sent le propre.",
            "papa|Tu te couches ?",
            "narrateur|Victorina se couche.",
            "narrateur|Elle glisse les pieds.",
            "narrateur|Elle pose la tête.",
            "narrateur|L'oreiller est moelleux.",
            "narrateur|Le doudou est contre sa joue.",
            "enfant-f|Le doudou m'attendait.",
            "maman|Oui.",
            "maman|Il t'attendait.",
            "papa|Une petite histoire ?",
            "enfant-f|Oui, papa.",
            "narrateur|Papa raconte une histoire.",
            "narrateur|C'est une histoire courte.",
            "narrateur|Victorina écoute.",
            "narrateur|Sa main tient le doudou.",
            "narrateur|Ses yeux se ferment.",
            "maman|C'est l'heure du dodo.",
            "maman|Le corps a besoin de dormir.",
            "enfant-f|Dodo, maman.",
            "papa|Oui.",
            "papa|Dodo.",
            "narrateur|Victorina respire doucement.",
            "narrateur|Papa baisse la lumière.",
            "narrateur|Le rond jaune devient petit.",
            "narrateur|Victorina est au lit.",
            "narrateur|C'est le dodo.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorina va dormir.",
            "narrateur|Que met-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorina a mis le pyjama.",
            "narrateur|Elle s'est couchée.",
            "narrateur|Le soir, c'est le dodo.",
            "maman|Tu as mis le pyjama ?",
            "enfant-f|Oui.",
            "enfant-f|Le pyjama.",
            "papa|Bravo, Victorina.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le doudou reste contre sa joue.",
            "narrateur|La chambre est calme.",
            "maman|Tu es bien au lit ?",
            "enfant-f|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorina dort.",
            "narrateur|Le pyjama est chaud.",
            "narrateur|La chambre est calme.",
            "papa|Tu entends encore le grillon ?",
            "enfant-f|Un peu.",
            "maman|Il chante tout doux.",
            "papa|Bravo.",
            "narrateur|Le grillon chante encore.",
            "narrateur|Le rond jaune est tout petit.",
            "narrateur|Le tapis n'a plus de pas.",
            "maman|Bonne nuit.",
            "enfant-f|Bonne nuit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai mis le pyjama.",
            "enfant-f|C'est le dodo.",
            "maman|Bravo.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le doudou reste sur l'oreiller.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "grillon,lampe",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
)

# ---------------------------------------------------------------------------
# ATOM-SAN.SOM.001-02 N2 Chouchou, papa, maman, pyjama
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.SOM.001-02",
    "La bouilloire fait un dernier clic. Un chat passe sur le mur. Le livre reste ouvert. Chouchou met le pyjama. Puis c'est le dodo.",
    "Le livre sur le canapé",
    "Chouchou, papa, maman",
    "salon puis chambre, le soir, bouilloire, chat sur le mur",
    {
        "CHK_T0000_P0000": [
            "narrateur|La bouilloire fait un dernier clic.",
            "narrateur|La cuisine sent le tilleul.",
            "narrateur|La vapeur s'en va, tout doux.",
            "narrateur|La nuit s'assoit sur les toits.",
            "narrateur|Les tuiles sont encore tièdes.",
            "narrateur|Un chat passe sur le mur.",
            "narrateur|Ses pas sont tout doux.",
            "narrateur|Sa queue fait un petit S.",
            "narrateur|Un livre reste ouvert sur le canapé.",
            "narrateur|La couverture est lisse, un peu froide.",
            "narrateur|Une page tremble près de la fenêtre.",
            "narrateur|Chouchou vit ici, avec papa et maman.",
            "enfant-f|Maman, le chat passe !",
            "maman|Oui.",
            "maman|Il rentre chez lui.",
            "papa|Tu as vu le livre, aussi ?",
            "enfant-f|Oui.",
            "enfant-f|Il est ouvert.",
            "narrateur|En ce moment, le salon devient calme.",
            "narrateur|Chouchou referme le livre.",
            "maman|C'est l'heure.",
            "maman|Le corps a besoin de dormir.",
            "papa|On met le pyjama ?",
            "enfant-f|Oui, papa.",
            "narrateur|Le pyjama sent le savon.",
            "narrateur|Il est crème, tout doux.",
            "papa|Tu enfiles le pantalon ?",
            "narrateur|Chouchou enfile le pantalon.",
            "narrateur|Elle sent le coton chaud.",
            "maman|Tu enfiles le haut ?",
            "narrateur|Elle enfile le haut.",
            "enfant-f|Il sent le savon.",
            "maman|Oui.",
            "maman|Bravo.",
            "maman|Tu as mis le pyjama ?",
            "enfant-f|Oui, maman.",
            "papa|Bravo, Chouchou.",
            "narrateur|Puis Chouchou va dans la chambre.",
            "narrateur|Le plancher est un peu froid.",
            "narrateur|Papa ouvre le lit.",
            "narrateur|Le drap sent le propre.",
            "papa|Tu te couches ?",
            "narrateur|Chouchou se couche.",
            "narrateur|Elle pose la tête sur l'oreiller.",
            "enfant-f|L'oreiller est doux.",
            "maman|Oui.",
            "maman|Tout doux.",
            "maman|Une petite histoire ?",
            "enfant-f|Oui, maman.",
            "narrateur|Maman raconte une petite histoire.",
            "narrateur|Chouchou écoute.",
            "narrateur|Ses yeux se ferment.",
            "papa|C'est l'heure du dodo.",
            "narrateur|Parce qu'elle a mis le pyjama, le dodo arrive.",
            "narrateur|Papa baisse la lumière.",
            "narrateur|Chouchou respire.",
            "maman|Le soir, c'est le dodo.",
            "enfant-f|Dodo, maman.",
            "papa|Oui.",
            "papa|Dodo.",
            "narrateur|Le chat n'est plus sur le mur.",
            "narrateur|Le livre attend, fermé, sur le canapé.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou va dormir.",
            "narrateur|Que met-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou a mis le pyjama.",
            "narrateur|Elle s'est couchée.",
            "narrateur|Le soir, c'est le dodo.",
            "maman|Tu as mis le pyjama ?",
            "enfant-f|Oui.",
            "enfant-f|Le pyjama.",
            "papa|Bravo, Chouchou.",
            "papa|Tu as fait du bon travail.",
            "maman|On reste tout près.",
            "narrateur|La chambre est calme.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Chouchou dort.",
            "narrateur|Le pyjama est chaud.",
            "narrateur|La chambre est calme.",
            "maman|Tu es bien au lit ?",
            "enfant-f|Oui, maman.",
            "papa|Tu as mis le pyjama ?",
            "enfant-f|Oui, papa.",
            "papa|Bravo.",
            "narrateur|La bouilloire s'est tue.",
            "narrateur|Le tilleul sent encore un peu.",
            "narrateur|Le canapé garde le livre fermé.",
            "maman|Bonne nuit, Chouchou.",
            "enfant-f|Bonne nuit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai mis le pyjama.",
            "enfant-f|C'est le dodo.",
            "maman|Bravo.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le livre reste fermé sur le canapé.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "bouilloire,chat",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
)

# ---------------------------------------------------------------------------
# ATOM-SAN.SOM.001-03 N3 Nina, papa, maman, deux soirs
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SAN.SOM.001-03",
    "Le plancher est encore tiède du jour. Un soir avec papa, un soir avec maman. Nina met le pyjama bleu. Puis c'est le dodo.",
    "Deux soirs, le pyjama bleu",
    "Nina, papa, maman",
    "salon puis chambre, deux soirs",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le plancher est encore tiède du jour.",
            "narrateur|Le bois garde la chaleur du soleil.",
            "narrateur|Une mite tourne autour de la lampe.",
            "narrateur|Elle fait un petit rond d'or.",
            "narrateur|Ses ailes font un bruit de papier.",
            "narrateur|Le salon sent le bois chaud.",
            "narrateur|Un cube rouge attend sous la table.",
            "narrateur|Nina vit ici, avec papa et maman.",
            "enfant-f|Papa, la mite tourne !",
            "papa|Oui.",
            "papa|Elle aime la lumière.",
            "maman|Le jour a été long.",
            "narrateur|En ce moment, Nina range un cube.",
            "narrateur|Le cube est rouge, un peu rêche.",
            "papa|C'est l'heure du dodo.",
            "papa|Le corps a besoin de dormir.",
            "maman|On met le pyjama ?",
            "enfant-f|Oui.",
            "enfant-f|Le bleu.",
            "narrateur|Nina prend son pyjama bleu.",
            "narrateur|Le tissu est doux, un peu froissé.",
            "narrateur|Elle le met.",
            "papa|Tu as mis le pyjama ?",
            "enfant-f|Oui, papa.",
            "papa|Bravo, Nina.",
            "narrateur|Papa ouvre le lit.",
            "narrateur|Il lit une petite histoire.",
            "narrateur|Nina se couche.",
            "enfant-f|Dodo, papa.",
            "papa|Oui.",
            "papa|Dodo.",
            "narrateur|La chambre est calme.",
            "narrateur|Le plancher refroidit, tout doux.",
            "narrateur|Le lendemain, le soleil revient.",
            "narrateur|Nina a passé la journée au parc.",
            "narrateur|Le soir revient.",
            "narrateur|La lumière baisse sur les toits.",
            "narrateur|Les chaussures ont un peu de sable.",
            "narrateur|Le sable est chaud, encore.",
            "narrateur|Nina a les yeux lourds.",
            "enfant-f|Maman, j'ai du sable.",
            "maman|Oui.",
            "maman|Le parc reste aux pieds.",
            "maman|C'est le soir.",
            "maman|On met le pyjama.",
            "narrateur|Puis c'est le dodo.",
            "narrateur|Nina se souvient.",
            "narrateur|Elle prend le pyjama bleu.",
            "narrateur|Elle le met encore.",
            "maman|Tu t'es souvenue ?",
            "enfant-f|Oui.",
            "enfant-f|Pyjama, puis dodo.",
            "maman|Bravo, Nina.",
            "maman|Tu as fait du bon travail.",
            "narrateur|Maman raconte une histoire.",
            "narrateur|Nina se couche.",
            "narrateur|Le corps a besoin de dormir.",
            "enfant-f|Dodo, maman.",
            "papa|Comme hier soir.",
            "maman|Pyjama, puis dodo.",
            "narrateur|La mite n'est plus autour de la lampe.",
            "narrateur|Le plancher est frais, maintenant.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le soir, Nina va dormir.",
            "narrateur|Que met-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina a mis le pyjama.",
            "narrateur|Un soir avec papa.",
            "narrateur|Un soir avec maman.",
            "narrateur|Puis dodo.",
            "maman|Tu as mis le pyjama, les deux soirs ?",
            "enfant-f|Oui.",
            "enfant-f|Le pyjama.",
            "papa|Bravo, Nina.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le pyjama bleu repose au bord du lit.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina ferme les yeux.",
            "narrateur|La chambre est douce.",
            "narrateur|Le pyjama bleu sent encore le savon.",
            "maman|Tu es bien au lit ?",
            "enfant-f|Oui, maman.",
            "papa|Bonne nuit, Nina.",
            "enfant-f|Bonne nuit.",
            "maman|Bravo.",
            "narrateur|Le sable n'est plus aux chaussures.",
            "narrateur|Les chaussures sèchent près de la porte.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Deux soirs, j'ai mis le pyjama.",
            "enfant-f|Puis dodo.",
            "maman|Bravo.",
            "papa|Tu as fait du bon travail.",
            "narrateur|Le plancher est calme.",
            "narrateur|L'histoire est finie.",
        ],
    },
    {
        "CHK_T0000_P0000": "lampe,plancher",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
)
