#!/usr/bin/env python3
"""w73 — ATOM-SOC.PAY.001-02..07 et ATOM-SOC.TRA.001-01..02."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-02 N3 Sarah, maman — carte d'Espagne, timbre qui se décolle
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-02",
    "Sarah veut coller à la fenêtre la carte d'Espagne qui sent encore l'enveloppe. Le timbre se décolle. Elles le recollent. La mer bleue reste dans la lumière.",
    "La carte d'Espagne de Sarah",
    "Sarah, maman",
    "cuisine puis fenêtre, après le courrier",
    {
        "CHK_T0000_P0000": [
            "narrateur|La boîte aux lettres sent le papier chaud.",
            "narrateur|Un rayon glisse sur le carrelage rouge.",
            "narrateur|La cuisine sent le café un peu froid.",
            "narrateur|Une enveloppe crème attend sur la table.",
            "narrateur|Le bord de l'enveloppe est un peu rêche.",
            "narrateur|Sarah vit ici, avec maman.",
            "maman|Tu as vu l'enveloppe, Sarah ?",
            "enfant-f|Elle sent le papier.",
            "enfant-f|Et un peu la colle.",
            "maman|C'est une carte d'Espagne.",
            "narrateur|En ce moment, Sarah ouvre l'enveloppe.",
            "narrateur|Le papier fait un petit bruit sec.",
            "narrateur|Une carte postale glisse dans sa main.",
            "narrateur|Le recto est tout bleu.",
            "enfant-f|De l'eau !",
            "enfant-f|Beaucoup d'eau bleue.",
            "maman|Oui.",
            "maman|C'est la mer d'Espagne.",
            "enfant-f|L'Espagne.",
            "enfant-f|Et la mer.",
            "narrateur|Sarah approche la carte de son nez.",
            "narrateur|Ça sent encore l'enveloppe.",
            "narrateur|Un peu de sel, presque.",
            "maman|Tu veux la mettre où ?",
            "enfant-f|À la fenêtre.",
            "enfant-f|Pour voir la mer.",
            "narrateur|Un petit bateau blanc est dessiné.",
            "narrateur|Sarah le suit du doigt.",
            "narrateur|Le doigt laisse une trace chaude.",
            "maman|Tu le sens, le papier ?",
            "enfant-f|Il est un peu rêche.",
            "narrateur|Le timbre est orange, un peu gondolé.",
            "narrateur|Sarah veut coller la carte.",
            "narrateur|Elle tient le timbre du pouce.",
            "narrateur|Le timbre se décolle, tout seul.",
            "enfant-f|Oh.",
            "enfant-f|Il part !",
            "maman|Doucement.",
            "maman|On le recolle ensemble ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le timbre tremble entre deux doigts.",
            "narrateur|Un coin blanc montre la colle sèche.",
            "narrateur|Sarah souffle dessus, tout bas.",
            "enfant-f|Il ne tient plus.",
            "maman|Le bâton de colle est dans le tiroir.",
            "narrateur|Sarah tire le tiroir.",
            "narrateur|Les cuillères tintent un peu.",
            "narrateur|Le bâton est bleu, un peu dur.",
            "enfant-f|Je le tourne ?",
            "maman|Oui, tout doucement.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah tient la carte d'Espagne.",
            "narrateur|Elle nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah tourne le bâton de colle.",
            "narrateur|Une petite lune blanche apparaît.",
            "maman|Un peu, pas trop.",
            "narrateur|Sarah pose la colle sur le timbre.",
            "narrateur|Le papier devient un peu luisant.",
            "enfant-f|C'est froid.",
            "maman|Oui.",
            "maman|Maintenant on presse.",
            "narrateur|Sarah pose le timbre orange.",
            "narrateur|Elle appuie avec le pouce.",
            "narrateur|Le pouce reste une seconde.",
            "maman|Il tient ?",
            "enfant-f|Il tient.",
            "maman|Merci, Sarah.",
            "narrateur|La carte sent encore l'enveloppe.",
            "narrateur|Et un peu la colle neuve.",
            "enfant-f|L'Espagne.",
            "enfant-f|La mer.",
            "maman|Un pays.",
            "maman|Un paysage.",
            "narrateur|Elles marchent vers la fenêtre.",
            "narrateur|Le carreau est tiède sous la main.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sarah pose la carte contre le verre.",
            "maman|Tu la tiens.",
            "maman|Je mets le scotch.",
            "narrateur|Un petit bruit de papier collant.",
            "narrateur|La mer bleue se tient toute seule.",
            "enfant-f|Elle reste !",
            "maman|Oui.",
            "maman|Tu la verras demain matin.",
            "narrateur|Le timbre orange est bien plat.",
            "narrateur|Sarah le caresse du bout du doigt.",
            "enfant-f|Il ne part plus.",
            "maman|Vous avez recollé ensemble.",
            "maman|Tu as fini de presser ?",
            "enfant-f|Oui, maman.",
            "narrateur|Un nuage passe sur le bleu.",
            "narrateur|Puis le soleil revient.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La carte d'Espagne reste à la fenêtre.",
            "narrateur|Ça sent encore l'enveloppe, tout près.",
            "enfant-f|La mer est là.",
            "maman|L'Espagne aussi.",
            "narrateur|Le timbre orange tient dans la lumière.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "la mer",
        "accepted_examples": "mer | la mer | mer d'Espagne | l'eau | eau bleue",
        "retry_prompt": "La carte montre la mer. Sarah nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-02",
    "La carte d'Espagne de Sarah",
    "Cuisine, enveloppe, carte d'Espagne, mer bleue. Timbre qui se décolle. Elles recollent. Carte à la fenêtre.",
    "Hugo → Sarah. Pays/paysage greffés dans la carte, pas une liste. Fin : timbre qui tient.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-03 N3 Amir, maman — photo d'Italie, trouver le cyprès
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-03",
    "Amir veut trouver le cyprès sur la photo d'Italie de tante. Le cadre penche, la poussière cache l'arbre. Ils essuient, ils trouvent la flamme verte.",
    "Le cyprès d'Amir",
    "Amir, maman",
    "salle à manger, buffet et cadre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un cadre penche un peu sur le buffet.",
            "narrateur|La poussière danse dans un carré de soleil.",
            "narrateur|La salle sent le bois et le café.",
            "narrateur|Un napperon blanc a un fil qui pend.",
            "narrateur|Amir vit ici, avec maman.",
            "maman|Tu as vu le cadre, Amir ?",
            "enfant-m|Il penche.",
            "maman|C'est la photo de tante.",
            "maman|En Italie.",
            "narrateur|En ce moment, Amir se hausse.",
            "narrateur|Le verre du cadre est un peu terne.",
            "narrateur|Tante sourit, toute petite.",
            "narrateur|Derrière elle, un ciel très pâle.",
            "enfant-m|Je cherche le cyprès.",
            "enfant-m|Celui de la photo.",
            "maman|Il est en Italie.",
            "maman|Un pays, l'Italie.",
            "narrateur|Amir passe le doigt sur le verre.",
            "narrateur|Une trace ronde apparaît.",
            "enfant-m|Je ne le vois pas.",
            "maman|La poussière le cache, peut-être.",
            "narrateur|Le cadre glisse d'un cran.",
            "narrateur|Amir le rattrape des deux mains.",
            "enfant-m|Il voulait tomber.",
            "maman|On le pose à plat.",
            "maman|Sur le napperon.",
            "narrateur|Ils posent le cadre tout doucement.",
            "narrateur|Le bois tape un tout petit coup.",
            "maman|Tu prends le chiffon ?",
            "enfant-m|Oui.",
            "narrateur|Le chiffon sent le citron sec.",
            "narrateur|Amir essuie le verre, en rond.",
            "narrateur|Tante devient plus nette.",
            "enfant-m|Le ciel est plus bleu.",
            "maman|Et à côté de tante ?",
            "narrateur|Amir plisse les yeux.",
            "narrateur|Un coin reste encore gris.",
            "enfant-m|Là, c'est sombre.",
            "maman|On essuie encore ce coin ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le chiffon passe sur le coin.",
            "narrateur|Une forme mince se lève.",
            "narrateur|Vert très foncé, comme une flamme.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir a nommé l'Italie.",
            "narrateur|Il nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "enfant-m|Le cyprès !",
            "enfant-m|Je l'ai trouvé.",
            "maman|Oui.",
            "maman|Le cyprès d'Italie.",
            "narrateur|Amir suit l'arbre du doigt.",
            "narrateur|Il est droit, tout étroit.",
            "maman|C'est un paysage.",
            "maman|Un arbre d'Italie.",
            "enfant-m|Il ressemble à une flamme.",
            "maman|Tu l'as cherché longtemps.",
            "maman|Merci d'avoir essuyé le verre.",
            "narrateur|Amir redresse le cadre.",
            "narrateur|Le buffet le reçoit, bien droit.",
            "enfant-m|Il ne penche plus.",
            "maman|On le voit, maintenant.",
            "maman|Tante, et le cyprès.",
            "narrateur|Un oiseau crie dehors, tout près.",
            "enfant-m|Ce n'est pas un cyprès, dehors.",
            "maman|Dehors, c'est le pin du jardin.",
            "maman|Le cyprès est sur la photo.",
            "narrateur|Amir compare les deux verts.",
            "narrateur|Le pin est plus large.",
            "narrateur|Le cyprès reste une flamme.",
        ],
        "CHK_T0000_P0000_END": [
            "maman|Tu veux le regarder encore ?",
            "enfant-m|Oui.",
            "narrateur|Amir s'assoit sur le tabouret.",
            "narrateur|Le tabouret grince un peu.",
            "narrateur|Le cyprès tient dans le soleil.",
            "enfant-m|L'Italie.",
            "enfant-m|Et le cyprès.",
            "maman|Un pays.",
            "maman|Un paysage.",
            "maman|Tu as fini de chercher ?",
            "enfant-m|Je l'ai.",
            "narrateur|Le napperon a encore son fil.",
            "narrateur|Le cadre, lui, ne penche plus.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le verre est clair, enfin.",
            "narrateur|Tante reste au soleil du buffet.",
            "enfant-m|Le cyprès est trouvé.",
            "maman|Il était là, tout le temps.",
            "narrateur|La flamme verte ne bouge plus.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "le cyprès",
        "accepted_examples": "cyprès | le cyprès | un cyprès | montagne | paysage | arbre",
        "retry_prompt": "Amir a trouvé le cyprès. Il nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-03",
    "Le cyprès d'Amir",
    "Buffet, cadre penché, photo de tante en Italie. Désir : trouver le cyprès. Poussière, chiffon, flamme verte.",
    "Cléa → Amir. Pas de classe. Paysage = cyprès, pas une liste de pays.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-04 N1 Mila, maman — livre cartonné France et mer, page collée
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-04",
    "Mila veut voir la mer de France dans le livre cartonné. Une page colle. Elles tirent doucement. Le bleu s'ouvre.",
    "Le livre de mer de Mila",
    "Mila, maman",
    "salon, canapé au soleil",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un rayon jaune chauffe le canapé bleu.",
            "narrateur|Le coussin sent encore le savon.",
            "narrateur|Une mouche tourne près de la vitre.",
            "narrateur|Le salon est calme et chaud.",
            "narrateur|Un livre cartonné attend par terre.",
            "narrateur|Le livre est épais et lisse.",
            "narrateur|Mila vit ici, avec maman.",
            "maman|Tu as vu le livre, Mila ?",
            "enfant-f|Il est bleu, maman.",
            "maman|Oui.",
            "maman|C'est le livre de la mer.",
            "narrateur|En ce moment, Mila s'assoit.",
            "narrateur|Elle pose la main sur le livre.",
            "enfant-f|Je veux voir la mer.",
            "maman|On ouvre ensemble ?",
            "enfant-f|Oui, maman.",
            "narrateur|Mila tire une page.",
            "narrateur|La page colle un peu.",
            "enfant-f|Elle colle !",
            "maman|On tire tout doucement ?",
            "enfant-f|Oui.",
            "narrateur|Maman tient le bord.",
            "narrateur|Mila tire encore un peu.",
            "narrateur|Un bruit de papier se fait.",
            "enfant-f|Elle vient !",
            "maman|Encore un peu.",
            "narrateur|La page se décolle, lentement.",
            "narrateur|Un fil de colle reste brillant.",
            "enfant-f|Ça brille.",
            "maman|C'est la colle.",
            "narrateur|La page montre de l'eau bleue.",
            "enfant-f|La mer !",
            "maman|Oui, c'est la mer.",
            "maman|Et le pays, tu vois ?",
            "narrateur|Mila pose le doigt.",
            "maman|C'est la France.",
            "enfant-f|La France.",
            "enfant-f|Et la mer.",
            "maman|Un pays.",
            "maman|Un paysage.",
            "narrateur|Le carton est un peu chaud.",
            "narrateur|Mila caresse le bleu.",
            "enfant-f|C'est mou ?",
            "maman|Non.",
            "maman|C'est du carton.",
            "narrateur|Une petite tache de colle reste.",
            "narrateur|Mila la touche du doigt.",
            "enfant-f|Ça colle encore.",
            "maman|On laisse sécher ?",
            "enfant-f|Oui.",
            "narrateur|Un bateau tout petit est dessiné.",
            "enfant-f|Un bateau !",
            "maman|Oui, sur la mer.",
            "maman|La mer de France.",
            "narrateur|Mila souffle sur la tache.",
            "enfant-f|Fffff.",
            "narrateur|La colle devient moins brillante.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila nomme la France.",
            "narrateur|Elle nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "enfant-f|La mer.",
            "maman|Oui, la mer.",
            "narrateur|La page veut se refermer.",
            "narrateur|Le carton ramène un peu.",
            "enfant-f|Elle se recolle !",
            "maman|On la tient ouverte.",
            "narrateur|Mila pose la paume à plat.",
            "narrateur|Maman tient l'autre bord.",
            "narrateur|La mer reste toute bleue.",
            "maman|Tu la vois bien ?",
            "enfant-f|Oui.",
            "enfant-f|Elle est grande.",
            "maman|Merci, Mila.",
            "narrateur|Le fil de colle sèche.",
            "narrateur|Il ne brille plus.",
            "enfant-f|Le bateau est petit.",
            "maman|Il glisse sur l'eau.",
            "narrateur|Mila suit le bateau du doigt.",
            "narrateur|Le carton fait un bruit mat.",
        ],
        "CHK_T0000_P0000_END": [
            "maman|On ferme tout doucement ?",
            "enfant-f|Encore un peu.",
            "narrateur|Elles regardent le bleu encore.",
            "narrateur|La mouche a quitté la vitre.",
            "maman|Tu as fini de regarder ?",
            "enfant-f|Oui, maman.",
            "narrateur|Mila referme le livre.",
            "narrateur|La page ne colle plus.",
            "enfant-f|La France.",
            "enfant-f|La mer.",
            "maman|Oui.",
            "narrateur|Le livre reste sur le canapé.",
            "narrateur|Le rayon jaune le touche encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le carton sent encore la colle.",
            "narrateur|Un coin bleu dépasse un peu.",
            "enfant-f|La mer est dedans.",
            "maman|Elle t'attend.",
            "narrateur|Le canapé garde le livre au chaud.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "la mer",
        "accepted_examples": "mer | la mer | eau | l'eau | mer de France",
        "retry_prompt": "Mila nomme aussi la mer. Elle nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-04",
    "Le livre de mer de Mila",
    "Canapé, livre cartonné, page collée, France et mer. Elles décollent. Le bleu reste ouvert.",
    "William → Mila. N1. Page collée = imprévu. Pas de liste de pays.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-05 N3 Nino, maman — puzzle du Mont, pièce sous la table
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-05",
    "Nino veut finir le puzzle du Mont, en Italie. Une pièce manque. Elle est sous la table. Il la trouve. La neige se pose.",
    "Le puzzle du Mont de Nino",
    "Nino, maman",
    "salon, table basse et tapis",
    {
        "CHK_T0000_P0000": [
            "narrateur|La table basse sent le bois ciré.",
            "narrateur|Des pièces de carton brillent comme des tuiles.",
            "narrateur|Le tapis rouge est épais sous les genoux.",
            "narrateur|Une boîte montre une montagne blanche.",
            "narrateur|Nino vit ici, avec maman.",
            "maman|Tu as vu la boîte, Nino ?",
            "enfant-m|C'est le Mont.",
            "maman|Oui.",
            "maman|Le Mont, en Italie.",
            "narrateur|En ce moment, Nino étale les pièces.",
            "narrateur|Le carton est rêche sous les doigts.",
            "enfant-m|Je veux finir le Mont.",
            "maman|On commence par le ciel ?",
            "enfant-m|Le ciel est bleu pâle.",
            "narrateur|Ils posent trois pièces de ciel.",
            "narrateur|Les bords s'emboîtent avec un clic.",
            "enfant-m|Clic.",
            "maman|Et la roche, maintenant ?",
            "narrateur|Nino cherche les bruns.",
            "narrateur|Une pièce a un peu de neige.",
            "enfant-m|L'Italie.",
            "enfant-m|Et la montagne.",
            "maman|Un pays.",
            "maman|Un paysage.",
            "narrateur|Le Mont grandit, tout doucement.",
            "narrateur|Il manque un trou, tout en haut.",
            "enfant-m|La neige du sommet.",
            "enfant-m|Elle n'est pas là.",
            "maman|Tu l'as vue tomber ?",
            "enfant-m|Non.",
            "narrateur|Nino regarde la boîte.",
            "narrateur|Le sommet blanc est sur l'image.",
            "narrateur|Sur la table, le trou reste vide.",
            "maman|On cherche autour ?",
            "enfant-m|Oui.",
            "narrateur|Nino se penche vers le tapis.",
            "narrateur|Un fil rouge chatouille le nez.",
            "enfant-m|Je ne la vois pas.",
            "maman|Et sous la table ?",
            "narrateur|Nino pose la joue au sol.",
            "narrateur|L'ombre de la table est fraîche.",
            "narrateur|Une petite forme blanche attend.",
            "enfant-m|Là !",
            "enfant-m|Sous la table !",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino nomme l'Italie.",
            "narrateur|Il nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino glisse le bras sous le bois.",
            "narrateur|La pièce est un peu poussiéreuse.",
            "enfant-m|Je l'ai.",
            "maman|Doucement.",
            "maman|Tu la sors ?",
            "narrateur|La pièce blanche revient à la lumière.",
            "narrateur|Un peu de tapis rouge dessus.",
            "maman|On souffle.",
            "enfant-m|Fffff.",
            "narrateur|La poussière part.",
            "narrateur|La neige du sommet est nette.",
            "maman|Merci, Nino.",
            "maman|Tu l'as trouvée.",
            "narrateur|Nino pose la pièce dans le trou.",
            "narrateur|Le clic est plus fort, cette fois.",
            "enfant-m|Le Mont est fini !",
            "maman|L'Italie.",
            "maman|Et la montagne.",
            "narrateur|Ils regardent le sommet ensemble.",
            "narrateur|Le blanc tient contre le ciel pâle.",
            "enfant-m|Il neige, là-haut.",
            "maman|Sur le puzzle, oui.",
        ],
        "CHK_T0000_P0000_END": [
            "maman|On range les bords de la boîte ?",
            "enfant-m|Encore une minute.",
            "narrateur|Nino suit la crête du doigt.",
            "narrateur|Le carton est encore un peu froid.",
            "maman|Tu as fini de chercher la pièce ?",
            "enfant-m|Oui, maman.",
            "narrateur|Ils glissent le puzzle dans la boîte.",
            "narrateur|Le Mont rentre sous le couvercle.",
            "enfant-m|Il est à l'abri.",
            "maman|Oui.",
            "narrateur|Le tapis garde une petite poussière blanche.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La table basse sent encore le bois ciré.",
            "narrateur|La boîte montre le Mont, bien fermée.",
            "enfant-m|La pièce était dessous.",
            "maman|Et maintenant le sommet est là.",
            "narrateur|Le tapis rouge redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "la montagne",
        "accepted_examples": "montagne | la montagne | le Mont | mont | neige | paysage",
        "retry_prompt": "Nino nomme aussi la montagne. Il nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-05",
    "Le puzzle du Mont de Nino",
    "Table cirée, puzzle du Mont en Italie. Pièce de neige sous la table. Nino la trouve. Sommet complet.",
    "Olympe → Nino. Paysage = montagne. Imprévu vécu, pas une liste de cartes.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-06 N3 Nina, papa — Grèce, coquillage et photo bleue
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-06",
    "Nina veut entendre la mer de Grèce dans le coquillage, en regardant la photo bleue. Le coquillage roule. Ils le rattrapent. Le hush arrive.",
    "Le coquillage de Nina",
    "Nina, papa",
    "rebord de fenêtre, lumière de midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La lumière de midi rend le mur tout blanc.",
            "narrateur|Un coquillage froid attend près de la fenêtre.",
            "narrateur|Une photo bleue est coincée sous le cadre.",
            "narrateur|Le rebord sent la poussière chaude.",
            "narrateur|Nina vit ici, avec papa.",
            "papa|Tu as vu le coquillage, Nina ?",
            "enfant-f|Il est froid.",
            "papa|Oui.",
            "papa|Il vient de la Grèce.",
            "narrateur|En ce moment, Nina prend la photo.",
            "narrateur|Le papier est lisse et un peu gondolé.",
            "enfant-f|Tout bleu.",
            "papa|C'est la mer de Grèce.",
            "enfant-f|La Grèce.",
            "enfant-f|Et la mer.",
            "papa|Un pays.",
            "papa|Un paysage.",
            "narrateur|Nina pose la photo contre le verre.",
            "narrateur|Le bleu du papier rejoint le ciel.",
            "enfant-f|Je veux entendre la mer.",
            "enfant-f|Dans le coquillage.",
            "papa|Tu le mets à l'oreille ?",
            "enfant-f|Oui.",
            "narrateur|Nina lève le coquillage.",
            "narrateur|La coquille glisse entre ses doigts.",
            "narrateur|Elle roule sur le rebord.",
            "enfant-f|Il part !",
            "papa|Doucement.",
            "papa|On le rattrape.",
            "narrateur|Papa tend la main.",
            "narrateur|Nina tend la sienne aussi.",
            "narrateur|Le coquillage s'arrête contre un caillou.",
            "enfant-f|Il a failli tomber.",
            "papa|Il est là.",
            "papa|Tu le reprends ?",
            "enfant-f|Oui, papa.",
            "narrateur|La coquille est encore plus froide.",
            "narrateur|Nina la serre des deux mains.",
            "papa|À l'oreille, maintenant.",
            "narrateur|Nina pose la coquille contre sa joue.",
            "enfant-f|Je n'entends rien.",
            "papa|Tourne-le un peu.",
            "papa|L'ouverture vers toi.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina nomme la Grèce.",
            "narrateur|Elle nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina tourne le coquillage.",
            "narrateur|L'ouverture touche son oreille.",
            "enfant-f|Chhh.",
            "enfant-f|J'entends !",
            "papa|Oui.",
            "papa|Comme la mer.",
            "narrateur|Le hush est doux, tout près.",
            "narrateur|Nina regarde la photo en même temps.",
            "enfant-f|La mer de Grèce.",
            "papa|Tu l'entends, et tu la vois.",
            "papa|Merci, Nina.",
            "narrateur|Elle tient le coquillage plus fort.",
            "narrateur|Le rebord n'a plus de place pour rouler.",
            "papa|On le pose dans le creux.",
            "enfant-f|Ici, près de la photo.",
            "narrateur|Le bleu du papier touche la coquille.",
            "narrateur|Froid contre lisse.",
            "enfant-f|Ils sont ensemble.",
            "papa|La Grèce, tout près.",
        ],
        "CHK_T0000_P0000_END": [
            "papa|Tu as fini d'écouter ?",
            "enfant-f|Encore un peu.",
            "narrateur|Nina remet la coquille à l'oreille.",
            "narrateur|Le hush revient, plus bas.",
            "enfant-f|La mer est petite, dedans.",
            "papa|Et grande, sur la photo.",
            "narrateur|Un nuage passe sur le mur blanc.",
            "narrateur|Le bleu de la photo reste.",
            "enfant-f|La Grèce.",
            "enfant-f|La mer.",
            "papa|Oui.",
            "narrateur|Nina pose enfin le coquillage.",
            "narrateur|Il ne roule plus.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La photo bleue garde son gondolement.",
            "narrateur|Le coquillage reste dans le creux.",
            "enfant-f|J'ai entendu la mer.",
            "papa|Elle est encore là, si tu colles l'oreille.",
            "narrateur|Le mur blanc redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "la mer",
        "accepted_examples": "mer | la mer | mer de Grèce | hush | l'eau",
        "retry_prompt": "Nina nomme aussi la mer. Elle nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-06",
    "Le coquillage de Nina",
    "Fenêtre de midi, photo bleue, coquillage de Grèce. Il roule. Elles écoutent le hush. Mer vue et entendue.",
    "Romane → Nina. Papa. Paysage = mer. Pas une boîte de cartes.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.PAY.001-07 N2 Chouchou, maman — Portugal, sardine, odeur de cuisine
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.PAY.001-07",
    "Chouchou veut voir la mer du Portugal sur l'image de sardine pendant que ça sent la cuisine. Une goutte d'huile tache le coin. Elles essuient. Le bleu revient.",
    "La sardine de Chouchou",
    "Chouchou, maman",
    "cuisine, huile de citron et boîte illustrée",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'huile chaude sent le citron dans la cuisine.",
            "narrateur|Une poêle fait un petit chant gras.",
            "narrateur|La fenêtre est ouverte sur la cour.",
            "narrateur|Une sardine dessinée attend près du pain.",
            "narrateur|Chouchou vit ici, avec maman.",
            "maman|Tu as vu la boîte, Chouchou ?",
            "enfant-f|Il y a un poisson.",
            "maman|Une sardine.",
            "maman|Dessinée, sur le Portugal.",
            "narrateur|En ce moment, Chouchou prend la boîte.",
            "narrateur|Le métal est froid, un peu huileux.",
            "enfant-f|Derrière le poisson, c'est bleu.",
            "maman|C'est la mer du Portugal.",
            "enfant-f|Le Portugal.",
            "enfant-f|Et la mer.",
            "maman|Un pays.",
            "maman|Un paysage.",
            "narrateur|Chouchou veut poser l'image près d'elle.",
            "enfant-f|Pour voir la mer, en mangeant.",
            "maman|Tu la mets contre le sel ?",
            "enfant-f|Oui.",
            "narrateur|La poêle crache une goutte.",
            "narrateur|La goutte d'huile tombe sur le coin.",
            "enfant-f|Oh.",
            "enfant-f|Le bleu est taché !",
            "maman|On essuie tout de suite ?",
            "enfant-f|Oui, maman.",
            "narrateur|Maman tend un torchon sec.",
            "narrateur|Chouchou tamponne le coin, tout doux.",
            "narrateur|L'huile fait un rond brillant.",
            "enfant-f|Ça part ?",
            "maman|Encore un peu.",
            "narrateur|Le torchon sent le citron, maintenant.",
            "narrateur|Le rond devient plus pâle.",
            "enfant-f|La sardine est encore là.",
            "maman|Et la mer, derrière ?",
            "enfant-f|Elle revient.",
            "maman|Tu tamponnes bien.",
            "narrateur|Une miette de pain roule près de la boîte.",
            "narrateur|Chouchou la pousse du doigt.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou nomme le Portugal.",
            "narrateur|Elle nomme aussi quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "enfant-f|La mer.",
            "maman|Oui, la mer du Portugal.",
            "narrateur|Le coin de la boîte est presque sec.",
            "narrateur|Le bleu a repris sa place.",
            "maman|Merci, Chouchou.",
            "maman|Tu as sauvé l'image.",
            "enfant-f|Je la mets ici.",
            "narrateur|Chouchou pose la boîte contre le sel.",
            "narrateur|La sardine dessinée regarde la poêle.",
            "maman|On voit la mer, en cuisinant.",
            "enfant-f|Oui.",
            "narrateur|La poêle chante moins fort.",
            "narrateur|Maman coupe le citron en deux.",
            "enfant-f|Ça pique le nez.",
            "maman|Comme au Portugal, presque.",
            "narrateur|Une goutte de citron tombe dans l'huile.",
            "narrateur|Ça sent plus fort, tout à coup.",
            "enfant-f|La mer, et le citron.",
            "maman|Et la sardine.",
        ],
        "CHK_T0000_P0000_END": [
            "maman|Tu as fini d'essuyer ?",
            "enfant-f|Oui, maman.",
            "narrateur|Elles s'assoient près de la table.",
            "narrateur|Le pain est tiède sous les doigts.",
            "enfant-f|Je regarde la boîte.",
            "maman|Le Portugal.",
            "maman|Et la mer.",
            "narrateur|Chouchou mange une bouchée.",
            "narrateur|Elle garde les yeux sur le bleu.",
            "enfant-f|Ça sent la cuisine.",
            "maman|Et un peu le large, aussi.",
            "narrateur|La fenêtre amène un air de cour.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La boîte reste contre le sel.",
            "narrateur|Le torchon sent encore le citron.",
            "enfant-f|La sardine garde la mer.",
            "maman|Pour demain, aussi.",
            "narrateur|L'huile chaude se tait, enfin.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "la mer",
        "accepted_examples": "mer | la mer | mer du Portugal | bleu | paysage",
        "retry_prompt": "Chouchou nomme aussi la mer. Elle nomme aussi quoi ?",
    },
)
relecture(
    "ATOM-SOC.PAY.001-07",
    "La sardine de Chouchou",
    "Cuisine au citron, boîte de sardine du Portugal, mer dessinée. Goutte d'huile. Elles essuient. On mange en regardant le bleu.",
    "Tessa → Chouchou. N2. Odeur de cuisine = monde. Pas une liste de cartes.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-01 N1 Raphaël, papa — vrai train, rivière, goûter qui roule
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-01",
    "Raphaël veut voir la rivière par le hublot du train. Le goûter roule. Ils restent assis avec papa et le rattrapent. L'eau apparaît.",
    "La rivière du train de Raphaël",
    "Raphaël, papa",
    "quai puis banc du train",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le quai sent le fer et le vent.",
            "narrateur|Une valise passe tout doucement.",
            "narrateur|Le banc du quai est froid.",
            "narrateur|Papa tient un petit sac brun.",
            "narrateur|Raphaël vit ici, avec papa.",
            "papa|Tu entends le quai, Raphaël ?",
            "enfant-m|Ça sent le fer.",
            "papa|Oui.",
            "papa|Le train arrive bientôt.",
            "narrateur|En ce moment, ils attendent.",
            "narrateur|Raphaël pose les mains sur le bois.",
            "enfant-m|Je veux voir la rivière.",
            "papa|On la verra par la fenêtre.",
            "papa|Dans le train.",
            "narrateur|Un bruit s'approche, tout long.",
            "narrateur|Le sol vibre un peu.",
            "enfant-m|Tchou tchou.",
            "papa|C'est le train.",
            "papa|On reste avec papa.",
            "narrateur|Ils montent ensemble.",
            "narrateur|Raphaël donne la main.",
            "papa|On s'assoit ici.",
            "papa|Sur le banc.",
            "narrateur|Le banc du train est chaud.",
            "narrateur|Un hublot rond montre le quai.",
            "enfant-m|Le hublot !",
            "papa|On reste assis.",
            "papa|Avec un adulte.",
            "narrateur|Le train part, tout doucement.",
            "narrateur|Les maisons glissent.",
            "enfant-m|La rivière ?",
            "papa|Bientôt.",
            "narrateur|Papa pose le sac brun.",
            "narrateur|Le goûter est dedans.",
            "narrateur|Une pomme roule sur le banc.",
            "enfant-m|Elle part !",
            "papa|On reste assis.",
            "papa|On la rattrape d'ici.",
            "narrateur|Raphaël reste sur le banc.",
            "narrateur|Il tend la main.",
            "narrateur|La pomme arrive vers lui.",
            "enfant-m|Je l'ai !",
            "papa|Bravo.",
            "papa|Assis, avec papa.",
            "narrateur|La pomme est un peu froide.",
            "narrateur|Raphaël la remet dans le sac.",
            "papa|Tu as vu le hublot ?",
            "enfant-m|Oui.",
            "narrateur|Dehors, les champs sont verts.",
            "narrateur|Un ruban brille, tout loin.",
            "enfant-m|L'eau !",
            "papa|La rivière.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël voyage avec papa.",
            "narrateur|Quel véhicule roule ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "enfant-m|Le train.",
            "papa|Oui, le train.",
            "narrateur|Ils restent assis sur le banc.",
            "narrateur|Le hublot se remplit d'eau.",
            "enfant-m|La rivière est large.",
            "papa|Tu la voulais.",
            "papa|La voilà.",
            "narrateur|L'eau file, très vite.",
            "narrateur|Un pont passe au-dessus.",
            "enfant-m|On est dessus ?",
            "papa|Oui.",
            "papa|On reste assis.",
            "narrateur|Raphaël tient encore la pomme.",
            "narrateur|Puis il la range.",
            "papa|Merci, Raphaël.",
            "papa|Tu es resté assis.",
            "enfant-m|Avec toi.",
            "papa|Avec un adulte.",
            "narrateur|Le train fait un bruit rond.",
            "narrateur|Le hublot tremble un peu.",
            "enfant-m|Ça chatouille.",
            "papa|C'est le pont.",
        ],
        "CHK_T0000_P0000_END": [
            "papa|Tu as fini de regarder l'eau ?",
            "enfant-m|Encore un peu.",
            "narrateur|La rivière devient plus étroite.",
            "narrateur|Des arbres la cachent.",
            "enfant-m|Elle part.",
            "papa|Elle suit le train, un moment.",
            "narrateur|Raphaël pose le front au hublot.",
            "narrateur|Le verre est frais.",
            "enfant-m|Le train.",
            "enfant-m|Et la rivière.",
            "papa|Oui.",
            "narrateur|Le sac brun reste entre eux.",
            "narrateur|La pomme ne roule plus.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le banc garde encore le sac.",
            "narrateur|Le hublot redevient vert.",
            "enfant-m|J'ai vu l'eau.",
            "papa|Assis, avec papa.",
            "narrateur|Le train continue, tout rond.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "le train",
        "accepted_examples": "train | le train | un train",
        "retry_prompt": "C'est le train. Quel véhicule roule ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-01",
    "La rivière du train de Raphaël",
    "Quai, banc, hublot. Désir : voir la rivière. Pomme qui roule. Restent assis, rattrapent. L'eau apparaît.",
    "Sami → Raphaël. POS-001 : rester assis avec l'adulte. Véhicule vécu, pas une liste.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-02 N2 Victorino, maman — vrai petit bac, rester avec maman
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-02",
    "Victorino veut voir la maison rouge de l'autre rive, en bac avec maman. Le banc est mouillé. Ils s'assoient au sec. Le bac glisse. La maison arrive.",
    "Le bac de Victorino",
    "Victorino, maman",
    "ponton puis banc du petit bac",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les cordes du bac sentent l'eau salée.",
            "narrateur|Le ponton mouillé brille par plaques.",
            "narrateur|Une mouette crie, tout près.",
            "narrateur|Le petit bac attend, tout bas.",
            "narrateur|Victorino vit ici, avec maman.",
            "maman|Tu as vu le bac, Victorino ?",
            "enfant-m|Il est petit.",
            "maman|Oui.",
            "maman|C'est un bateau.",
            "narrateur|En ce moment, ils donnent la main.",
            "narrateur|Ils montent sur le bac ensemble.",
            "enfant-m|Je veux la maison rouge.",
            "enfant-m|Sur l'autre rive.",
            "maman|On la verra en glissant.",
            "maman|On reste avec maman.",
            "narrateur|Le banc du bac est mouillé.",
            "narrateur|Une flaque tient au milieu.",
            "enfant-m|Il est mouillé !",
            "maman|On s'assoit sur le bord sec.",
            "maman|Ici, près de moi.",
            "narrateur|Victorino s'assoit contre maman.",
            "narrateur|Le bois sec est rêche.",
            "enfant-m|Je reste.",
            "maman|Oui.",
            "maman|Assis, avec un adulte.",
            "narrateur|Une corde tombe dans l'eau.",
            "narrateur|Le bac se détache du ponton.",
            "enfant-m|On part !",
            "maman|On reste assis.",
            "narrateur|L'eau clapote sous le plancher.",
            "narrateur|Victorino tient la manche de maman.",
            "enfant-m|Ça bouge.",
            "maman|Le bateau glisse.",
            "maman|Toi, tu restes.",
            "narrateur|Une petite vague lèche le bord.",
            "narrateur|Des gouttes sautent sur la chaussure.",
            "enfant-m|Ma chaussure !",
            "maman|Elle va sécher.",
            "maman|On ne se lève pas.",
            "narrateur|Victorino garde les pieds au bois.",
            "narrateur|Au loin, un toit rouge apparaît.",
            "enfant-m|La maison !",
            "maman|Bientôt.",
            "narrateur|Le bac tourne un peu.",
            "narrateur|La maison se cache, puis revient.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorino glisse sur l'eau.",
            "narrateur|Quel véhicule le porte ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "enfant-m|Le bateau.",
            "enfant-m|Le bac.",
            "maman|Oui, le bateau.",
            "narrateur|Ils restent assis sur le bord sec.",
            "narrateur|La maison rouge grossit.",
            "enfant-m|Je la vois bien.",
            "maman|Tu l'as voulue.",
            "maman|La voilà.",
            "narrateur|Une mouette suit le bac.",
            "narrateur|Son ombre passe sur l'eau.",
            "enfant-m|Elle vole avec nous.",
            "maman|Nous, on reste assis.",
            "maman|Merci, Victorino.",
            "narrateur|Le ponton de l'autre rive s'approche.",
            "narrateur|Une corde attend, déjà.",
            "enfant-m|On arrive.",
            "maman|On se lève avec maman.",
            "maman|Quand le bac est arrêté.",
            "narrateur|Le bois donne un petit choc.",
            "narrateur|L'eau se calme contre le ponton.",
            "enfant-m|Il ne bouge plus.",
            "maman|Maintenant on peut descendre.",
        ],
        "CHK_T0000_P0000_END": [
            "maman|Tu donnes la main ?",
            "enfant-m|Oui, maman.",
            "narrateur|Ils descendent ensemble.",
            "narrateur|Le ponton sent encore le sel.",
            "enfant-m|La maison rouge.",
            "maman|Elle est là, tout près.",
            "narrateur|Victorino regarde le bac derrière lui.",
            "narrateur|Le petit bateau attend déjà.",
            "enfant-m|On est venus en bateau.",
            "maman|Avec un adulte.",
            "narrateur|Sa chaussure laisse une trace humide.",
            "narrateur|Puis le bois du ponton la boit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La maison rouge a un volet ouvert.",
            "narrateur|Le bac reste collé au ponton.",
            "enfant-m|J'ai vu l'autre rive.",
            "maman|Assis, avec maman.",
            "narrateur|L'eau salée clapote encore, tout bas.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "le bateau",
        "accepted_examples": "bateau | le bateau | un bateau | bac | le bac",
        "retry_prompt": "C'est le bateau. Quel véhicule le porte ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-02",
    "Le bac de Victorino",
    "Ponton, petit bac vécu. Désir : maison rouge de l'autre rive. Banc mouillé. Restent assis avec maman.",
    "Léa → Victorino. Véhicule vécu, pas train-avion-bateau en liste. POS-001 : rester avec l'adulte.",
)
