#!/usr/bin/env python3
"""F-NAR-008 — REL.CON.002-04/07/08, REL.MOQ.001-02/06/07, REL.MOQ.004-01/03 (implicite)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-REL.CON.002-04  N3  Victorina, Chouchou, papa — fournil, cerceau, plots
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.CON.002-04",
    "Victorina veut faire rouler le cerceau jusqu'au mur. Chouchou passe trop près. "
    "Elle dit stop, marche vers la maîtresse. Plus tard, près des plots chauds, "
    "le cerceau retombe. Elle dit stop encore, va près d'elle. Le pain du fournil reste.",
    "Le cerceau sous les feuilles",
    "Victorina, Chouchou, papa",
    "cour d'école, feuilles, fournil, plots oranges",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le fournil envoie une bouffée de pain chaud.",
            "narrateur|La bouffée passe au-dessus du grillage.",
            "narrateur|Des feuilles jaunes collent aux chaussures.",
            "narrateur|Elles font un bruit doux, tout plat.",
            "narrateur|Une feuille reste sous le talon de Victorina.",
            "narrateur|Le préau sent encore le bois mouillé.",
            "narrateur|Papa pose le cartable près d'un pilier.",
            "papa|Tu as senti le pain, Victorina ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Il sent le chaud.",
            "papa|Le fournil est juste derrière.",
            "papa|Je reviens ce soir.",
            "enfant-f|D'accord.",
            "narrateur|Papa part vers le grillage.",
            "narrateur|La maîtresse est près du préau.",
            "narrateur|En ce moment, Victorina prend le cerceau.",
            "narrateur|Le bois du cerceau est lisse, un peu froid.",
            "enfant-f|Je veux le faire rouler jusqu'au mur.",
            "narrateur|Elle pousse le cerceau entre les feuilles.",
            "narrateur|Il roule, puis s'arrête près d'une flaque.",
            "enfant-f|Encore.",
            "narrateur|Une feuille colle au bois.",
            "narrateur|Elle la retire, tout doux.",
            "narrateur|Le cerceau repart, plus loin.",
            "narrateur|Chouchou arrive très vite.",
            "narrateur|Chouchou passe trop près du cerceau.",
            "narrateur|Le cerceau penche, puis tombe.",
            "narrateur|Victorina sent ses pieds bouger.",
            "narrateur|Son cœur tape.",
            "enfant-f|Stop.",
            "narrateur|Sa voix est claire.",
            "narrateur|Elle fait un pas vers le préau.",
            "narrateur|Ses chaussures froissent les feuilles.",
            "narrateur|Elle marche jusqu'à la maîtresse.",
            "enfant-f|Chouchou est passé trop près.",
            "narrateur|La maîtresse l'écoute.",
            "narrateur|Victorina reste près d'elle.",
            "narrateur|Elle pose une main sur le pilier.",
            "narrateur|Le pilier est froid et un peu rugueux.",
            "enfant-f|Je reste ici.",
            "narrateur|Le cerceau attend dans les feuilles.",
            "narrateur|Victorina souffle.",
            "narrateur|Son cœur tape moins vite.",
            "narrateur|Plus tard, le soleil a bougé.",
            "narrateur|Les plots oranges sont chauds au milieu.",
            "narrateur|Victorina reprend le cerceau.",
            "enfant-f|Je veux passer entre les plots.",
            "narrateur|Le cerceau roule vers l'orange.",
            "narrateur|Il frappe un plot, tout doux.",
            "narrateur|Le plot tremble, puis tient.",
            "enfant-f|Encore.",
            "narrateur|Chouchou arrive encore, très vite.",
            "narrateur|Il passe trop près des plots.",
            "narrateur|Le cerceau tombe contre un plot.",
            "narrateur|Le plastique fait un petit bruit creux.",
            "narrateur|Victorina sent encore son cœur.",
            "enfant-f|Stop.",
            "narrateur|Elle fait un pas.",
            "narrateur|La maîtresse est près du portail, maintenant.",
            "narrateur|Victorina marche vers elle.",
            "narrateur|L'orange des plots reste derrière.",
            "enfant-f|Encore trop près.",
            "narrateur|La maîtresse l'écoute encore.",
            "narrateur|Victorina reste près d'elle.",
            "narrateur|Elle touche un plot, au passage.",
            "narrateur|Le plot est lisse et tiède.",
            "enfant-f|Je reste ici.",
            "narrateur|Elle souffle.",
            "narrateur|Le cerceau ne roule plus.",
            "narrateur|Le soir, papa revient.",
            "narrateur|Les feuilles collent encore aux chaussures.",
            "narrateur|Victorina secoue une feuille du talon.",
            "narrateur|La feuille tombe, toute plate.",
            "papa|Tu as senti le pain, encore ?",
            "enfant-f|Un peu.",
            "enfant-f|Le cerceau a roulé.",
            "enfant-f|Chouchou est passé trop près.",
            "enfant-f|J'ai dit stop.",
            "enfant-f|Je suis allée vers la maîtresse.",
            "papa|Près du préau ?",
            "enfant-f|Oui.",
            "papa|Et près des plots ?",
            "enfant-f|Stop encore.",
            "papa|Bravo, Victorina.",
            "papa|Tu es allée près d'elle.",
            "enfant-f|Oui, papa.",
            "narrateur|Victorina serre la main de papa.",
            "narrateur|La bouffée de pain revient, tout doux.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade bouscule Victorina.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorina a dit stop.",
            "narrateur|Elle a fait un pas.",
            "narrateur|Elle a rejoint la maîtresse.",
            "papa|Bravo.",
            "papa|Près du préau, et près des plots.",
            "enfant-f|Stop, puis la maîtresse.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorina range son manteau.",
            "narrateur|Une feuille mouillée reste sous la chaussure.",
            "papa|On marche à côté ?",
            "enfant-f|Oui, papa.",
            "papa|Tu tiens ma main ?",
            "enfant-f|Oui.",
            "papa|Tu sens encore le pain ?",
            "enfant-f|Un tout petit peu.",
            "narrateur|Les plots oranges restent dans la cour.",
            "narrateur|Le cerceau ne roule plus.",
            "papa|On laisse le cerceau près du mur ?",
            "enfant-f|Oui.",
            "narrateur|Une feuille sèche sur le chemin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai dit stop.",
            "enfant-f|Je suis allée vers la maîtresse.",
            "papa|Bravo, Victorina.",
            "narrateur|Les feuilles jaunes restent au sol, toutes plates.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "stop",
        "accepted_examples": "stop | s'éloigner | maîtresse | vers la maîtresse",
        "retry_prompt": "Elle dit stop, puis elle va vers la maîtresse. Que fait Victorina ?",
    },
)
relecture(
    "ATOM-REL.CON.002-04",
    "Le cerceau sous les feuilles",
    "Victorina veut le cerceau jusqu'au mur. Chouchou trop près. Stop, préau. "
    "Puis plots chauds, stop encore. Le pain du fournil referme.",
    "- Second lieu vécu (plots), pas « même leçon ».\n"
    "- Pas de définition de s'éloigner. Troupe : Victorina, Chouchou, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.CON.002-07  N3  Victorino, Aniss, papa — buée, crochet, récréation
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.CON.002-07",
    "Victorino veut accrocher son manteau mouillé au crochet du bateau. "
    "Aniss passe trop près dans le couloir. Stop, porte de la classe. "
    "À la récréation, près du soleil peint, Aniss trop près encore. "
    "Stop, mur. Le soir, la vitre est claire.",
    "La buée du couloir",
    "Victorino, Aniss, papa",
    "école, couloir embué, récréation",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une buée ronde tient sur la vitre du couloir.",
            "narrateur|Les carreaux sont froids et lisses.",
            "narrateur|Les chaussures font un petit écho.",
            "narrateur|L'écho revient, tout mince.",
            "narrateur|Une lumière pâle passe à travers la buée.",
            "narrateur|Papa pose le cartable sous le crochet.",
            "papa|Tu as vu la buée, Victorino ?",
            "enfant-m|Oui, papa.",
            "enfant-m|La vitre est floue.",
            "papa|C'est le chaud du couloir.",
            "papa|Je reviens ce soir.",
            "enfant-m|D'accord.",
            "narrateur|Papa part vers la porte.",
            "narrateur|En ce moment, Victorino range son manteau.",
            "narrateur|Le manteau sent encore la pluie.",
            "narrateur|La manche est un peu humide.",
            "enfant-m|Je veux le crochet du bateau.",
            "narrateur|Un petit bateau est collé au bois.",
            "narrateur|Victorino pousse le crochet.",
            "narrateur|Le crochet tinte, tout court.",
            "narrateur|Aniss arrive dans le couloir.",
            "narrateur|Aniss passe trop près de l'épaule.",
            "narrateur|Victorino sent le choc.",
            "narrateur|Son cœur tape.",
            "enfant-m|Stop.",
            "narrateur|Sa voix est claire.",
            "narrateur|Il fait un pas vers la classe.",
            "narrateur|Ses chaussures sonnent sur les carreaux.",
            "narrateur|Il marche jusqu'à la porte.",
            "enfant-m|Aniss est passé trop près.",
            "narrateur|La maîtresse l'écoute.",
            "narrateur|Victorino reste près d'elle.",
            "narrateur|Il pose une main sur le montant.",
            "narrateur|Le bois est lisse et un peu froid.",
            "enfant-m|Je reste ici.",
            "narrateur|Le manteau pend, calme, sous le bateau.",
            "narrateur|Victorino souffle.",
            "narrateur|Son cœur tape moins vite.",
            "narrateur|Plus tard, la cloche sonne.",
            "narrateur|La cour sent l'herbe mouillée.",
            "narrateur|Un soleil jaune est peint sur le mur.",
            "narrateur|Victorino veut poser une pomme de pin au pied.",
            "enfant-m|Elle va là, près du soleil.",
            "narrateur|La pomme de pin est rêche sous les doigts.",
            "narrateur|Il s'accroupit près du mur.",
            "narrateur|Aniss arrive trop près encore.",
            "narrateur|La pomme de pin roule.",
            "narrateur|Victorino sent son épaule.",
            "enfant-m|Stop.",
            "narrateur|Il fait un pas.",
            "narrateur|La maîtresse est près du mur, maintenant.",
            "narrateur|Victorino marche vers elle.",
            "narrateur|Le soleil peint reste derrière.",
            "enfant-m|Encore trop près.",
            "narrateur|La maîtresse l'écoute encore.",
            "narrateur|Victorino reste près d'elle.",
            "narrateur|Il pose une main sur le mur.",
            "narrateur|Le mur est lisse et un peu froid.",
            "enfant-m|Je reste ici.",
            "narrateur|Il souffle.",
            "narrateur|La pomme de pin attend dans l'herbe.",
            "narrateur|Le soir, papa arrive.",
            "narrateur|La vitre n'est plus embuée.",
            "narrateur|Victorino passe un doigt sur le verre.",
            "narrateur|Le verre est lisse, maintenant.",
            "papa|Tu as rangé ton manteau ?",
            "enfant-m|Oui.",
            "enfant-m|Au crochet du bateau.",
            "enfant-m|Aniss trop près, dans le couloir.",
            "enfant-m|Puis près du soleil peint.",
            "enfant-m|J'ai dit stop.",
            "enfant-m|Je suis allé vers la maîtresse.",
            "papa|Dans le couloir ?",
            "enfant-m|Oui.",
            "papa|Et dans la cour ?",
            "enfant-m|Stop encore.",
            "papa|Bravo, Victorino.",
            "papa|Tu es allé près d'elle.",
            "enfant-m|Oui, papa.",
            "narrateur|Papa prend sa main.",
            "narrateur|L'écho des chaussures redevient petit.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade bouscule Victorino.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorino a dit stop.",
            "narrateur|Il a fait un pas.",
            "narrateur|Il a rejoint la maîtresse.",
            "papa|Bravo.",
            "papa|Dans le couloir, et près du mur.",
            "enfant-m|Stop, puis la maîtresse.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorino prend la main de papa.",
            "papa|On marche vers la maison ?",
            "enfant-m|Oui, papa.",
            "narrateur|Les carreaux ne sonnent plus.",
            "papa|Tu as encore un peu froid à l'épaule ?",
            "enfant-m|Non.",
            "papa|La vitre est claire, maintenant ?",
            "enfant-m|Oui.",
            "narrateur|Le manteau pend, calme, sous le crochet.",
            "papa|On ferme la porte du couloir ?",
            "enfant-m|Oui, papa.",
            "narrateur|Les carreaux redeviennent silencieux.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai dit stop.",
            "enfant-m|Je suis allé vers la maîtresse.",
            "papa|Bravo, Victorino.",
            "narrateur|La vitre du couloir est claire, maintenant.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "stop",
        "accepted_examples": "stop | il dit stop | s'éloigner | maîtresse | vers la maîtresse",
        "retry_prompt": "Il dit stop. Il s'éloigne. Vers qui va-t-il ?",
    },
)
relecture(
    "ATOM-REL.CON.002-07",
    "La buée du couloir",
    "Victorino veut le crochet du bateau. Aniss trop près. Stop, porte. "
    "Puis pomme de pin au soleil peint, stop encore. Vitre claire.",
    "- Second lieu vécu (cour, soleil peint), pas « même leçon ».\n"
    "- Troupe : Victorino, Aniss, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.CON.002-08  N3  Amir, Nino, papa — bateau de papier, flaque, préau
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.CON.002-08",
    "Amir veut que le bateau de papier traverse la flaque. Nino passe trop près. "
    "Stop, maîtresse. Sous le préau, il veut sécher un pli sur la pierre. "
    "Nino trop près encore. Stop. Le bateau reste mou dans l'herbe.",
    "Le bateau dans la flaque",
    "Amir, Nino, papa",
    "cour, flaque, préau, pierre plate",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un bateau de papier penche dans l'eau grise.",
            "narrateur|Le pli blanc est un peu mouillé.",
            "narrateur|Un coin du bateau s'ouvre, tout doux.",
            "narrateur|L'ombre du préau commence au bord de l'eau.",
            "narrateur|Une pierre plate tient le soleil.",
            "narrateur|Papa pose le cartable près du grillage.",
            "papa|Tu as vu le bateau, Amir ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Il penche tout seul.",
            "papa|La flaque le pousse.",
            "papa|Je reviens ce soir.",
            "enfant-m|D'accord.",
            "narrateur|Papa part le long du grillage.",
            "narrateur|En ce moment, Amir s'accroupit près de la flaque.",
            "narrateur|L'eau est froide sous un doigt.",
            "enfant-m|Je veux qu'il aille de l'autre côté.",
            "narrateur|Il souffle tout doux vers le pli.",
            "narrateur|Le bateau avance d'un tout petit bout.",
            "enfant-m|Encore.",
            "narrateur|Nino arrive très vite.",
            "narrateur|Nino passe trop près de l'épaule.",
            "narrateur|Le bateau se renverse un peu.",
            "narrateur|Amir sent le choc.",
            "narrateur|Son cœur tape.",
            "enfant-m|Stop.",
            "narrateur|Il fait un pas vers le préau.",
            "narrateur|Ses chaussures clapotent au bord.",
            "narrateur|Il marche jusqu'à la maîtresse.",
            "enfant-m|Nino est passé trop près.",
            "narrateur|La maîtresse l'écoute.",
            "narrateur|Amir reste près d'elle.",
            "narrateur|Il pose une main sur le pilier.",
            "narrateur|Le pilier est froid et un peu rugueux.",
            "enfant-m|Je reste ici.",
            "narrateur|Le bateau attend dans l'eau, tout mou.",
            "narrateur|Amir souffle.",
            "narrateur|Son cœur tape moins vite.",
            "narrateur|Plus tard, l'ombre du préau a grandi.",
            "narrateur|Amir ramasse le bateau.",
            "narrateur|Le papier colle à ses doigts.",
            "enfant-m|Je veux sécher le pli, sur la pierre.",
            "narrateur|La pierre plate est encore un peu chaude.",
            "narrateur|Il pose le bateau dessus.",
            "narrateur|Un coin se redresse, tout lentement.",
            "narrateur|Nino passe trop près encore.",
            "narrateur|Le bateau glisse vers le bord.",
            "narrateur|Amir sent son épaule.",
            "enfant-m|Stop.",
            "narrateur|Il fait un pas.",
            "narrateur|La maîtresse est sous le préau, maintenant.",
            "narrateur|Amir marche vers elle.",
            "narrateur|La pierre reste derrière.",
            "enfant-m|Encore trop près.",
            "narrateur|La maîtresse l'écoute encore.",
            "narrateur|Amir reste près d'elle.",
            "narrateur|Il pose une main sur le pilier du préau.",
            "narrateur|Le ciment est froid.",
            "enfant-m|Je reste ici.",
            "narrateur|Il souffle.",
            "narrateur|Le bateau a arrêté de tourner.",
            "narrateur|Papa vient le soir.",
            "narrateur|La pierre plate n'est plus chaude.",
            "narrateur|Amir la touche du bout du doigt.",
            "narrateur|Elle est juste tiède.",
            "papa|Tu as vu le bateau, encore ?",
            "enfant-m|Il ne tourne plus.",
            "enfant-m|Dans la flaque, trop près.",
            "enfant-m|Puis sur la pierre.",
            "enfant-m|J'ai dit stop.",
            "enfant-m|Je suis allé vers la maîtresse.",
            "papa|Près de l'eau ?",
            "enfant-m|Oui.",
            "papa|Et sous le préau ?",
            "enfant-m|Stop encore.",
            "papa|Bravo, Amir.",
            "papa|Tu es allé près d'elle.",
            "enfant-m|Oui, papa.",
            "narrateur|Papa prend sa main.",
            "narrateur|Le bateau de papier reste dans l'herbe, tout mou.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade bouscule Amir.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir a dit stop.",
            "narrateur|Il a fait un pas.",
            "narrateur|Il a rejoint la maîtresse.",
            "papa|Bravo.",
            "papa|Près de la flaque, et sous le préau.",
            "enfant-m|Stop, puis la maîtresse.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Amir range son cartable.",
            "papa|Je marche à côté.",
            "enfant-m|Oui, papa.",
            "papa|On laisse le bateau dans l'herbe ?",
            "enfant-m|Oui.",
            "papa|Il est trop mou, maintenant ?",
            "enfant-m|Oui, papa.",
            "narrateur|La flaque ne pousse plus rien.",
            "narrateur|L'ombre du préau a grandi.",
            "papa|La pierre est tiède, encore ?",
            "enfant-m|Juste un peu.",
            "narrateur|Le pli du bateau reste ouvert.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai dit stop.",
            "enfant-m|Je suis allé vers la maîtresse.",
            "papa|Bravo, Amir.",
            "narrateur|Le bateau de papier sèche tout bas dans l'herbe.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "stop",
        "accepted_examples": "stop | il dit stop | s'éloigner | la maîtresse | vers la maîtresse",
        "retry_prompt": "Il dit stop. Il s'éloigne. Vers qui va-t-il ?",
    },
)
relecture(
    "ATOM-REL.CON.002-08",
    "Le bateau dans la flaque",
    "Amir veut le bateau de l'autre côté. Nino trop près. Stop. "
    "Puis pli sur la pierre, stop encore. Bateau mou dans l'herbe.",
    "- Second lieu vécu (préau, pierre), pas « même leçon ».\n"
    "- Troupe : Amir, Nino, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.MOQ.001-02  N3  Nino, Sarah, maman — crayons, soleil, gant au parc
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.MOQ.001-02",
    "Nino veut dessiner un soleil avec Sarah. Le crayon jaune tombe. "
    "Un rire commence. Sarah a le visage triste. Nino s'arrête, tend le crayon. "
    "Ils dessinent. Au parc, le gant tombe. Même geste vécu. Ils jouent au sable.",
    "Le crayon jaune au soleil",
    "Nino, Sarah, maman",
    "classe, boîte de crayons, puis parc",
    {
        "CHK_T0000_P0000": [
            "narrateur|La boîte des crayons sent le bois chaud.",
            "narrateur|Un rayon de poussière danse au-dessus.",
            "narrateur|Ça sent le crayon gras et le savon.",
            "narrateur|Le plancher craque un peu.",
            "maman|Nino, ta veste est sur le crochet.",
            "maman|Tu as vu le rayon sur les crayons ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Il brille.",
            "maman|Je reviens te chercher après l'école.",
            "maman|On ira au parc.",
            "enfant-m|D'accord.",
            "narrateur|Maman part vers la porte.",
            "narrateur|En ce moment, Nino prend un crayon jaune.",
            "narrateur|Le bois est lisse, encore chaud.",
            "enfant-m|Sarah, on dessine le soleil ?",
            "copine|Oui.",
            "narrateur|Sarah tient le crayon.",
            "narrateur|Le crayon glisse.",
            "narrateur|Il tombe près de la boîte.",
            "narrateur|Un petit rire commence dans la gorge de Nino.",
            "narrateur|Sarah baisse les yeux.",
            "narrateur|Sa bouche devient toute petite.",
            "narrateur|Le crayon reste par terre.",
            "narrateur|Nino referme la bouche.",
            "narrateur|Le rire ne sort plus.",
            "narrateur|Il ramasse le crayon jaune.",
            "narrateur|Il le tend.",
            "copine|Merci, Nino.",
            "narrateur|Sarah reprend le crayon.",
            "enfant-m|On dessine ?",
            "copine|Oui.",
            "narrateur|Le jaune pose un rond sur le papier.",
            "narrateur|La maîtresse s'approche.",
            "maitresse|Vous dessinez le soleil ?",
            "enfant-m|Oui.",
            "maitresse|Il est bien rond.",
            "narrateur|Plus tard, le parc sent l'herbe coupée.",
            "narrateur|Une chaîne de balançoire tinte, loin.",
            "narrateur|Un grain de sable brille sur le bac.",
            "narrateur|Maman tient le gant de Nino.",
            "maman|Tu veux le bac à sable ?",
            "enfant-m|Oui.",
            "enfant-m|Avec Sarah.",
            "narrateur|Sarah a un gant bleu.",
            "narrateur|Le gant glisse.",
            "narrateur|Il tombe, mou, près du bac.",
            "narrateur|Un petit rire recommence, tout court.",
            "narrateur|Sarah regarde le gant.",
            "narrateur|Ses joues baissent.",
            "narrateur|Nino referme encore la bouche.",
            "narrateur|Il ramasse le gant.",
            "narrateur|La laine est froide, un peu humide.",
            "narrateur|Il le tend.",
            "copine|Merci.",
            "enfant-m|On fait un gâteau de sable ?",
            "copine|Oui.",
            "narrateur|Le sable coule entre leurs doigts.",
            "narrateur|Le gant bleu est remis.",
            "maman|Vous jouez ensemble ?",
            "enfant-m|Oui, maman.",
            "maman|Bravo, Nino.",
            "maman|Tu as du sable sur les genoux ?",
            "enfant-m|Un peu.",
            "maman|On le secoue ?",
            "enfant-m|Oui.",
            "narrateur|Nino serre la main de maman.",
            "narrateur|Il reste l'herbe, et le calme.",
            "maman|On rentre tout doux ?",
            "enfant-m|Oui, maman.",
            "narrateur|Un oiseau crie, puis plus.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade rit.",
            "narrateur|Que fait Nino ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino a vu le visage de Sarah.",
            "narrateur|Le rire s'est arrêté.",
            "narrateur|Il a tendu le crayon, puis le gant.",
            "maman|Bravo.",
            "maman|Vous avez dessiné, puis joué.",
            "enfant-m|Le soleil, et le sable.",
            "maman|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nino range son cartable près du portail.",
            "narrateur|Le zip chante un peu.",
            "maman|Tu as fini de ranger ?",
            "enfant-m|Oui, maman.",
            "maman|Le gant de Sarah est au chaud.",
            "maman|On rentre ?",
            "enfant-m|Oui.",
            "narrateur|Maman marche à côté.",
            "narrateur|L'herbe sent encore fort.",
            "maman|Le soleil est sur le papier, à la classe ?",
            "enfant-m|Oui, tout rond.",
            "narrateur|La chaîne de balançoire tinte, plus loin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|On a dessiné.",
            "enfant-m|Puis le sable.",
            "maman|Bravo.",
            "narrateur|Le crayon jaune est dans la boîte, au chaud.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc", "CHK_T0000_P0000_C0001": "enfants_parc"},
    {
        "expected_answer": "pas rire",
        "accepted_examples": "pas rire | pas gentil | ne pas rire | pas répéter | ramasse | il ramasse | il tend",
        "retry_prompt": "Nino voit le visage de Sarah. Que fait-il ?",
    },
)
relecture(
    "ATOM-REL.MOQ.001-02",
    "Le crayon jaune au soleil",
    "Nino veut un soleil avec Sarah. Crayon tombé, rire, visage triste. "
    "Il s'arrête, tend, ils dessinent. Au parc, le gant, puis le sable.",
    "- Pas « il ne faut pas ». Rire vécu, arrêt, objet rendu, jeu.\n"
    "- Troupe : Nino, Sarah, maman. Maîtresse parle sans leçon.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.MOQ.001-06  N3  Victorino, Mila, maman — bonnet laine, dessin maison
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.MOQ.001-06",
    "Victorino veut dessiner une maison avec Mila. Le bonnet jaune tombe. "
    "Un rire commence. Mila a le visage triste. Il s'arrête, tend le bonnet. "
    "À la maison, le dessin glisse. Même geste vécu. Ils dessinent ensemble.",
    "Le bonnet sur la tablette",
    "Victorino, Mila, maman",
    "école, tablette de laine, puis table à la maison",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un fil de laine brille sur la tablette.",
            "narrateur|Les bonnets sentent le mouton doux.",
            "narrateur|La porte vitrée laisse un carré de lumière.",
            "narrateur|Le carré est chaud sur le bois.",
            "maman|Ton bonnet gris est à sa place, Victorino.",
            "maman|Tu as vu le carré de soleil ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Il est chaud.",
            "maman|Je reviens te chercher.",
            "maman|On dessinera à la maison.",
            "enfant-m|D'accord.",
            "narrateur|Maman part vers la porte vitrée.",
            "narrateur|En ce moment, Mila tient un bonnet jaune.",
            "narrateur|La laine est douce, un peu lourde.",
            "enfant-m|On le met sur la tablette ?",
            "copine|Oui.",
            "narrateur|Le bonnet glisse.",
            "narrateur|Il tombe près de la tablette.",
            "narrateur|Un petit rire commence dans la gorge de Victorino.",
            "narrateur|Mila baisse les yeux.",
            "narrateur|Sa lèvre tremble un peu.",
            "narrateur|Le bonnet reste par terre.",
            "narrateur|Victorino referme la bouche.",
            "narrateur|Le rire ne sort plus.",
            "narrateur|Il ramasse le bonnet.",
            "narrateur|La laine est douce sous les doigts.",
            "narrateur|Il le tend.",
            "copine|Merci, Victorino.",
            "narrateur|Mila remet le bonnet.",
            "enfant-m|Il est bien là.",
            "copine|Oui.",
            "narrateur|La maîtresse s'approche.",
            "maitresse|Votre bonnet est à sa place ?",
            "copine|Oui.",
            "maitresse|Vous pouvez aller dessiner, alors.",
            "narrateur|Plus tard, à la maison, la table sent le crayon.",
            "narrateur|Une chaise frotte un peu le carrelage.",
            "narrateur|Un verre d'eau fait un rond clair.",
            "maman|On dessine ici, Victorino.",
            "maman|Le papier est à plat.",
            "enfant-m|Une maison, Mila ?",
            "copine|Oui.",
            "narrateur|Un dessin de Mila glisse.",
            "narrateur|Il tombe près de la chaise.",
            "narrateur|Un petit rire recommence, tout court.",
            "narrateur|Mila regarde le papier.",
            "narrateur|Ses joues baissent.",
            "narrateur|Victorino referme encore la bouche.",
            "narrateur|Il ramasse le dessin.",
            "narrateur|Le papier est un peu froid.",
            "narrateur|Il le tend.",
            "copine|Merci.",
            "enfant-m|On dessine la porte ?",
            "copine|Oui, et une fenêtre.",
            "narrateur|Le crayon pose un toit, tout doux.",
            "maman|Vous dessinez ensemble ?",
            "enfant-m|Oui, maman.",
            "maman|Bravo, Victorino.",
            "maman|Tu as du crayon sur le pouce ?",
            "enfant-m|Un peu.",
            "maman|On essuie ?",
            "enfant-m|Oui.",
            "narrateur|Victorino serre la main de maman.",
            "narrateur|Le carré de lumière a bougé sur le plancher.",
            "narrateur|Le dessin est à plat, sur la table.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade rit.",
            "narrateur|Que fait Victorino ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorino a vu le visage de Mila.",
            "narrateur|Le rire s'est arrêté.",
            "narrateur|Il a tendu le bonnet, puis le dessin.",
            "maman|Bravo.",
            "maman|Vous avez une maison, maintenant.",
            "enfant-m|Avec une fenêtre.",
            "maman|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorino range son cartable près de la porte.",
            "narrateur|Le zip fait un petit bruit.",
            "maman|Tu as fini de ranger ?",
            "enfant-m|Oui, maman.",
            "maman|Le dessin de Mila est à plat.",
            "maman|On reste un peu à table ?",
            "enfant-m|Oui.",
            "narrateur|Maman marche à côté.",
            "maman|Le toit est bien droit ?",
            "enfant-m|Oui, tout droit.",
            "narrateur|La laine des bonnets sent encore le mouton, loin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|On a dessiné la maison.",
            "enfant-m|Avec Mila.",
            "maman|Bravo.",
            "narrateur|Le carré de lumière a glissé jusqu'à la table.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "pas rire",
        "accepted_examples": "pas rire | pas gentil | ne pas rire | pas répéter | ramasse | il ramasse | il tend",
        "retry_prompt": "Victorino voit le visage de Mila. Que fait-il ?",
    },
)
relecture(
    "ATOM-REL.MOQ.001-06",
    "Le bonnet sur la tablette",
    "Victorino veut une maison avec Mila. Bonnet tombé, rire, visage triste. "
    "Il s'arrête, tend. À la table, le dessin, puis le toit ensemble.",
    "- Pas « il ne faut pas ». Rire vécu, arrêt, objet rendu, dessin.\n"
    "- Troupe : Victorino, Mila, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.MOQ.001-07  N3  Aniss, Nina, papa — gant, escalier, livre, pain
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.MOQ.001-07",
    "Aniss veut lire avec Nina, puis goûter le pain. Le gant rose tombe. "
    "Un rire commence. Nina a le visage triste. Il s'arrête, tend le gant. "
    "À la maison, le livre glisse. Même geste vécu. Ils lisent. Le pain sent chaud.",
    "Le gant près de l'escalier",
    "Aniss, Nina, papa",
    "école, casiers, puis tapis et pain à la maison",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'escalier en bois craque, une marche après l'autre.",
            "narrateur|Les cartables tapent doucement contre les casiers.",
            "narrateur|Ça sent le pain du goûter, tout loin.",
            "narrateur|Une lanière de cuir claque, puis plus.",
            "papa|Ton gant vert est dans la poche, Aniss.",
            "papa|Tu as entendu l'escalier ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Il parle un peu.",
            "papa|On accroche le cartable.",
            "papa|Je reviens te chercher.",
            "enfant-m|D'accord, papa.",
            "narrateur|Papa part vers la porte.",
            "narrateur|En ce moment, Nina tient un gant rose.",
            "narrateur|Le tissu est doux, un peu froid.",
            "enfant-m|On le met près du casier ?",
            "copine|Oui.",
            "narrateur|Le gant glisse.",
            "narrateur|Il tombe près du casier.",
            "narrateur|Un petit rire commence dans la gorge d'Aniss.",
            "narrateur|Nina baisse les yeux.",
            "narrateur|Sa bouche devient toute petite.",
            "narrateur|Le gant reste par terre.",
            "narrateur|Aniss referme la bouche.",
            "narrateur|Le rire ne sort plus.",
            "narrateur|Il ramasse le gant.",
            "narrateur|Le tissu est doux, un peu froid.",
            "narrateur|Il le tend.",
            "copine|Merci, Aniss.",
            "narrateur|Nina remet le gant.",
            "enfant-m|Il est chaud, maintenant ?",
            "copine|Un peu.",
            "narrateur|La maîtresse s'approche.",
            "maitresse|Votre gant est remis ?",
            "copine|Oui.",
            "maitresse|Vous pouvez aller lire, alors.",
            "narrateur|Plus tard, à la maison, le tapis est doux.",
            "narrateur|Ça sent le pain, tout près.",
            "papa|On pose le livre ici, Aniss.",
            "papa|Les pages sont bien à plat.",
            "enfant-m|On lit, Nina ?",
            "copine|Oui.",
            "narrateur|Un livre glisse.",
            "narrateur|Il tombe près du tapis.",
            "narrateur|Les pages font un bruit de papier.",
            "narrateur|Un petit rire recommence, tout court.",
            "narrateur|Nina regarde le livre.",
            "narrateur|Ses joues baissent.",
            "narrateur|Aniss referme encore la bouche.",
            "narrateur|Il ramasse le livre.",
            "narrateur|Il le tend à Nina.",
            "copine|Merci.",
            "enfant-m|On lit la page des oiseaux ?",
            "copine|Oui.",
            "narrateur|Les pages restent à plat, sur le tapis.",
            "papa|Vous lisez ensemble ?",
            "enfant-m|Oui, papa.",
            "papa|Bravo, Aniss.",
            "papa|Tu as senti le pain, tout à l'heure ?",
            "enfant-m|Oui, papa.",
            "papa|On en prendra une tranche ?",
            "enfant-m|Oui.",
            "narrateur|Aniss serre la main de papa.",
            "narrateur|Le livre est refermé, sur le tapis.",
            "narrateur|L'escalier ne craque plus.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Un camarade rit.",
            "narrateur|Que fait Aniss ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss a vu le visage de Nina.",
            "narrateur|Le rire s'est arrêté.",
            "narrateur|Il a tendu le gant, puis le livre.",
            "papa|Bravo.",
            "papa|Vous avez lu, et le pain attend.",
            "enfant-m|La page des oiseaux.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Aniss range son cartable près de la porte.",
            "narrateur|Le zip fait un petit bruit.",
            "papa|Tu as fini de ranger ?",
            "enfant-m|Oui, papa.",
            "papa|Le livre de Nina est refermé.",
            "papa|On prend le pain ?",
            "enfant-m|Oui.",
            "narrateur|Papa marche à côté.",
            "papa|La tranche est encore tiède ?",
            "enfant-m|Oui, un peu.",
            "narrateur|Ça sent le pain, tout près, maintenant.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|On a lu.",
            "enfant-m|Puis le pain.",
            "papa|Bravo.",
            "narrateur|Le livre reste fermé, bien à plat.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "pas rire",
        "accepted_examples": "pas rire | pas gentil | ne pas rire | pas répéter | ramasse | il ramasse | il tend",
        "retry_prompt": "Aniss voit le visage de Nina. Que fait-il ?",
    },
)
relecture(
    "ATOM-REL.MOQ.001-07",
    "Le gant près de l'escalier",
    "Aniss veut lire avec Nina, puis le pain. Gant tombé, rire, visage triste. "
    "Il s'arrête, tend. À la maison, le livre, les oiseaux, le pain tiède.",
    "- Pas « il ne faut pas ». Rire vécu, arrêt, objet rendu, lecture.\n"
    "- Troupe : Aniss, Nina, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.MOQ.004-01  N3  Nina, Victorina, maman, papa — lavande, gâteau, photo
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.MOQ.004-01",
    "Nina veut un souvenir près des lavandes. Victorina a du gâteau sur la joue. "
    "Nina avance la main vers le téléphone. Maman attend. Nina parle. "
    "Alors la photo. Plus tard, les abeilles. Papa attend. Nina parle encore.",
    "La lavande du muret",
    "Nina, Victorina, maman, papa",
    "jardin, muret, lavande, gâteau",
    {
        "CHK_T0000_P0000": [
            "narrateur|La lavande du jardin sent le savon chaud.",
            "narrateur|Les abeilles font un bruit tout fin.",
            "narrateur|Le muret de pierre tient encore le soleil.",
            "narrateur|Une miette sucrée brille près d'une assiette.",
            "narrateur|Une fourchette a un peu de crème au bout.",
            "maman|Le jardin sent bon, Nina.",
            "maman|Victorina est là aussi.",
            "enfant-f|Les abeilles font un bruit tout fin.",
            "maman|Oui.",
            "maman|On les regarde, sans les toucher.",
            "narrateur|En ce moment, Nina et Victorina sont près du muret.",
            "narrateur|Victorina a un peu de gâteau sur la joue.",
            "narrateur|Nina voit le téléphone de maman.",
            "narrateur|Il est sur la nappe, près du verre.",
            "enfant-f|Je veux un souvenir, près des fleurs.",
            "narrateur|Nina avance la main vers le téléphone.",
            "narrateur|Maman ne bouge pas.",
            "narrateur|Maman attend, tout près.",
            "narrateur|Nina pose sa main.",
            "enfant-f|Maman, je peux demander une photo ?",
            "maman|Oui.",
            "maman|Victorina, tu veux essuyer ta joue ?",
            "narrateur|Victorina essuie sa joue.",
            "narrateur|Le gâteau n'est plus là.",
            "maman|Vous souriez toutes les deux ?",
            "enfant-f|Oui, maman.",
            "copine|Oui.",
            "narrateur|Maman lève le téléphone.",
            "narrateur|Le téléphone reste dans sa main.",
            "narrateur|Maman prend la photo.",
            "narrateur|Nina et Victorina sont près des lavandes.",
            "enfant-f|Merci, maman.",
            "maman|Bravo, Nina.",
            "narrateur|Les abeilles butinent encore près des fleurs.",
            "narrateur|Papa arrive plus tard, par le petit portail.",
            "papa|Je vous trouve au jardin.",
            "papa|Ça sent la lavande.",
            "enfant-f|On a un souvenir.",
            "papa|Vous me montrez ?",
            "maman|Oui.",
            "narrateur|Maman montre la photo.",
            "narrateur|Le téléphone reste avec elle.",
            "narrateur|Une abeille tourne près du muret.",
            "enfant-f|Encore une, papa.",
            "enfant-f|Avec l'abeille.",
            "narrateur|Nina avance encore la main.",
            "narrateur|Papa ne bouge pas.",
            "narrateur|Papa attend.",
            "enfant-f|Papa, tu peux ?",
            "papa|Oui.",
            "narrateur|Papa lève le téléphone.",
            "narrateur|Le téléphone reste dans sa main.",
            "narrateur|La photo se fait, près de la fleur.",
            "enfant-f|Merci, papa.",
            "papa|De rien.",
            "maman|Le téléphone rentre dans ma poche, après.",
            "enfant-f|On a souri.",
            "papa|Oui.",
            "narrateur|Un verre de limonade laisse un rond d'eau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina veut une photo.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina a parlé à maman.",
            "narrateur|Puis à papa.",
            "narrateur|Alors les photos sont arrivées.",
            "maman|Bravo.",
            "enfant-f|J'ai parlé avant.",
            "enfant-f|À maman.",
            "papa|Oui.",
            "narrateur|Les abeilles s'éloignent un peu.",
            "narrateur|Le muret reste chaud.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina et Victorina rangent les assiettes.",
            "narrateur|La nappe a un peu de sucre.",
            "maman|Merci, les filles.",
            "narrateur|Maman glisse le téléphone dans sa poche.",
            "papa|Les verres sont encore un peu froids.",
            "enfant-f|On a un souvenir, maintenant.",
            "maman|Oui.",
            "papa|On reste encore un peu au jardin ?",
            "enfant-f|Oui, papa.",
            "narrateur|La lavande sent toujours fort.",
            "narrateur|Le portail reste entrouvert.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|On a un souvenir.",
            "enfant-f|Près des fleurs.",
            "maman|Bravo.",
            "papa|C'est pour nous.",
            "narrateur|Les abeilles ont fini leur ronde.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "demander",
        "accepted_examples": "demander | à maman | adulte | demander à l'adulte | je peux",
        "retry_prompt": "Nina parle à maman. Que fait-elle ?",
    },
)
relecture(
    "ATOM-REL.MOQ.004-01",
    "La lavande du muret",
    "Nina veut un souvenir près des lavandes. Elle avance la main. "
    "Maman attend. Nina parle. La photo. Puis papa, l'abeille.",
    "- Pas de définition de demander. Adulte qui attend, puis photo.\n"
    "- Troupe : Nina, Victorina, maman, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-REL.MOQ.004-03  N2  Raphaël, Mila, maman — vanille, farine, gâteau
# ---------------------------------------------------------------------------
write_story(
    "ATOM-REL.MOQ.004-03",
    "Raphaël veut un souvenir de la farine sur le nez de Mila. "
    "Il avance la main vers le téléphone. Maman attend. Il parle. "
    "Alors la photo. Le gâteau sort. Il parle encore. Ils lèchent la cuillère.",
    "La farine sur le nez",
    "Raphaël, Mila, maman",
    "cuisine, buée, saladier, four",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vitre de la cuisine est toute embuée.",
            "narrateur|La vapeur sent la vanille chaude.",
            "narrateur|Une cuillère en bois tape le saladier jaune.",
            "narrateur|La farine fait un petit nuage blanc.",
            "narrateur|Le plancher est un peu collant sous les chaussettes.",
            "narrateur|Une miette sucrée brille près du pot.",
            "maman|Tu entends le four, Raphaël ?",
            "enfant-m|Il fait un petit bruit.",
            "maman|Oui.",
            "maman|Il chauffe le gâteau.",
            "narrateur|En ce moment, Raphaël mélange la pâte.",
            "narrateur|La pâte est épaisse et douce.",
            "narrateur|Mila est là, tout près du saladier.",
            "narrateur|Mila a de la farine sur le nez.",
            "narrateur|Ça fait un petit point blanc.",
            "enfant-m|Mila, tu as de la farine.",
            "narrateur|Mila se touche le nez.",
            "narrateur|Elle rit un peu.",
            "enfant-m|Je veux un souvenir.",
            "narrateur|Raphaël voit le téléphone de maman.",
            "narrateur|Le téléphone est sur la table.",
            "narrateur|Il est loin de la pâte.",
            "narrateur|Raphaël avance la main.",
            "narrateur|Maman ne bouge pas.",
            "narrateur|Maman attend, tout près.",
            "narrateur|Raphaël pose sa main.",
            "enfant-m|Maman, je peux demander une photo ?",
            "maman|Oui.",
            "narrateur|Raphaël se tourne vers Mila.",
            "enfant-m|Mila, on peut ?",
            "copine|Oui.",
            "narrateur|Mila essuie un peu son nez.",
            "narrateur|Un point blanc reste.",
            "narrateur|Maman prend le téléphone.",
            "narrateur|Le téléphone reste dans sa main.",
            "narrateur|Maman prend la photo.",
            "narrateur|Raphaël et Mila sourient.",
            "enfant-m|Merci, maman.",
            "maman|Bravo, Raphaël.",
            "narrateur|Le saladier brille encore.",
            "narrateur|Le gâteau sent plus fort.",
            "narrateur|Plus tard, le four s'ouvre.",
            "narrateur|Le gâteau est doré, tout chaud.",
            "enfant-m|Et le gâteau ?",
            "enfant-m|Un souvenir du gâteau ?",
            "narrateur|Raphaël avance encore la main.",
            "narrateur|Maman attend encore.",
            "enfant-m|On peut, maman ?",
            "maman|Oui.",
            "narrateur|Maman photographie le gâteau doré.",
            "narrateur|Le téléphone reste avec elle.",
            "enfant-m|Le téléphone est avec toi.",
            "maman|Oui.",
            "narrateur|Ils lèchent un peu de pâte.",
            "narrateur|C'est sucré et doux.",
            "maman|Tu as fini de mélanger ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le four continue son petit bruit.",
            "narrateur|La fenêtre reste embuée.",
            "narrateur|Raphaël dessine un petit rond dans la buée.",
            "maman|Un rond, c'est joli.",
            "narrateur|Mila dessine un soleil à côté.",
            "enfant-m|On a le souvenir.",
            "maman|Oui.",
            "narrateur|Le gâteau cuit tout doucement.",
            "narrateur|La cuisine est chaude et douce.",
            "narrateur|Mila pose sa joue sur la table.",
            "narrateur|Le bois est un peu collant.",
            "maman|Tu veux un verre d'eau ?",
            "enfant-m|Oui, maman.",
            "narrateur|L'eau est fraîche.",
            "narrateur|Elle fait un petit cloc dans le verre.",
            "enfant-m|Et le téléphone est avec toi.",
            "maman|Oui.",
            "narrateur|Une goutte de vanille brille sur la cuillère.",
            "narrateur|Mila la montre du doigt.",
            "enfant-m|C'est sucré.",
            "maman|Oui.",
            "maman|On goûtera le gâteau plus tard.",
            "narrateur|Le four fait toujours son petit bruit.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël veut une photo.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël a parlé à maman.",
            "narrateur|Alors les photos sont arrivées.",
            "narrateur|Le téléphone est resté avec elle.",
            "maman|Bravo, Raphaël.",
            "enfant-m|J'ai parlé.",
            "enfant-m|Le téléphone est avec toi.",
            "maman|Oui.",
            "maman|Avec moi.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Raphaël et Mila rangent le saladier.",
            "narrateur|La cuillère tapote encore un peu.",
            "maman|Tu glisses le saladier ici ?",
            "enfant-m|Oui, maman.",
            "narrateur|Maman range le téléphone.",
            "narrateur|Il n'est plus sur la table.",
            "maman|On attend le gâteau, maintenant.",
            "enfant-m|Il sent bon.",
            "maman|Oui.",
            "narrateur|La buée part tout doucement.",
            "narrateur|Un rond reste sur la vitre.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|On a un souvenir.",
            "enfant-m|Le téléphone est avec maman.",
            "maman|Bravo.",
            "narrateur|Le gâteau cuit encore.",
            "narrateur|La cuisine sent la vanille.",
        ],
    },
    {"CHK_T0000_P0000": "cuillere_saladier"},
    {
        "expected_answer": "demander",
        "accepted_examples": "demander | à maman | adulte | demander à l'adulte | je peux",
        "retry_prompt": "Raphaël parle à maman. Que fait-il ?",
    },
)
relecture(
    "ATOM-REL.MOQ.004-03",
    "La farine sur le nez",
    "Raphaël veut un souvenir du point blanc. Il avance la main. "
    "Maman attend. Il parle. La photo. Puis le gâteau doré. La cuillère sucrée.",
    "- Pas de définition de demander. N2. Troupe : Raphaël, Mila, maman.",
)
