#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-VIV.PLA.001-08 à 12."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

CHUNKS = (
    "CHK_T0000_P0000",
    "CHK_T0000_P0000_Q0001",
    "CHK_T0000_P0000_C0001",
    "CHK_T0000_P0000_END",
    "CHK_T0000_P0000_END_F0001",
)
EMPTY = {k: "" for k in CHUNKS}

# ---------------------------------------------------------------------------
# 08 N3 Sarah, papa — basilic + thym, huile, tomate. Thym trop sec, soir.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-08",
    "Sarah veut une tomate à l'huile avec du basilic. Le thym est trop sec. Ils l'arrosent le soir. La tomate sent le jardin.",
    "La tomate à l'huile de Sarah",
    "Sarah, papa",
    "cuisine, rebord de fenêtre, soir",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une goutte d'huile d'olive brille sur la tomate.",
            "narrateur|La planche de bois sent encore le fruit.",
            "narrateur|Un couteau repose près de l'assiette.",
            "narrateur|Le soleil de fin de jour entre à la fenêtre.",
            "narrateur|Deux pots attendent sur le rebord.",
            "narrateur|Le basilic a des feuilles bien vertes.",
            "narrateur|Le thym a des tiges un peu grises.",
            "papa|Sarah, tu sens l'huile ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Je veux de l'huile sur la tomate.",
            "papa|Avec une feuille de basilic ?",
            "enfant-f|Oui.",
            "enfant-f|Comme au jardin.",
            "narrateur|En ce moment, Sarah frotte une feuille de basilic.",
            "narrateur|Ses doigts sentent tout de suite le jardin.",
            "enfant-f|Ça sent bon.",
            "papa|Le basilic a soif, tu vois ?",
            "narrateur|Les feuilles du basilic sont un peu molles.",
            "papa|Il a besoin d'eau.",
            "papa|Il a besoin de lumière.",
            "enfant-f|On l'arrose ?",
            "papa|Oui, avec moi.",
            "narrateur|Sarah prend le petit arrosoir.",
            "narrateur|Papa tient aussi l'anse.",
            "narrateur|Ils versent un peu d'eau au pied du basilic.",
            "narrateur|La terre devient sombre.",
            "enfant-f|Il boit.",
            "papa|Oui.",
            "narrateur|Sarah touche ensuite le thym.",
            "narrateur|Une petite feuille sèche casse entre ses doigts.",
            "enfant-f|Il est trop sec, papa.",
            "papa|Le soleil a trop chauffé, cet après-midi.",
            "papa|On l'arrose ce soir, d'accord ?",
            "enfant-f|Ce soir.",
            "narrateur|Papa recule le thym un peu de la vitre.",
            "narrateur|L'assiette attend encore, avec l'huile.",
            "enfant-f|Le basilic, on le met déjà ?",
            "papa|Une feuille, oui.",
            "papa|Le thym, plus tard.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le basilic a soif.",
            "narrateur|Que fait Sarah avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le soir, la lampe de la cuisine s'allume.",
            "narrateur|La fenêtre est encore un peu bleue.",
            "papa|C'est le moment du thym, Sarah ?",
            "enfant-f|Oui.",
            "enfant-f|Il a trop soif.",
            "narrateur|Sarah porte l'arrosoir à deux mains.",
            "narrateur|L'eau chante un peu dans le métal.",
            "papa|Doucement, au pied.",
            "narrateur|Ils versent un filet d'eau.",
            "narrateur|La terre du thym devient foncée.",
            "papa|Il a de l'eau.",
            "papa|La lampe lui donne un peu de lumière.",
            "enfant-f|Il va aller mieux ?",
            "papa|Oui.",
            "papa|Merci, Sarah.",
            "narrateur|Sarah essuie une goutte sur le rebord.",
            "narrateur|Ses doigts sentent encore le basilic.",
            "papa|On finit la tomate ?",
            "enfant-f|Avec l'huile.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa coupe un morceau de tomate.",
            "narrateur|Sarah pose une feuille de basilic dessus.",
            "narrateur|Une toute petite branche de thym rejoint l'huile.",
            "papa|Tu goûtes ?",
            "enfant-f|Oui.",
            "narrateur|Sarah croque.",
            "enfant-f|Ça sent le jardin.",
            "papa|Le basilic et le thym aussi.",
            "narrateur|L'assiette brille un peu sous la lampe.",
            "narrateur|Le rebord est calme.",
            "enfant-f|Le thym boit, maintenant.",
            "papa|Oui, ce soir il boit.",
            "narrateur|Sarah essuie ses mains sur le linge.",
            "narrateur|Le linge sent l'huile, un peu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|L'huile brille encore sur la tomate.",
            "enfant-f|On a arrosé.",
            "papa|Oui.",
            "narrateur|Le basilic sent bon près de la fenêtre.",
            "narrateur|Le thym tient mieux dans son pot.",
            "narrateur|La cuisine sent le jardin.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "arroser",
        "accepted_examples": "arroser | de l'eau | eau | lumière | avec papa",
        "retry_prompt": "Ils versent de l'eau. Que fait Sarah ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-08",
    "La tomate à l'huile de Sarah",
    "Sarah veut une tomate à l'huile. Basilic à la fenêtre, thym trop sec. Ils arrosent le thym le soir. La tomate sent le jardin.",
    "D16 Sarah (Sélène). Deux plantes, deux scènes. N3. Pas « L'histoire est finie ».",
)

# ---------------------------------------------------------------------------
# 09 N1 Mila, papa — menthe, thé. Feuille amère trop vieille ; jeune feuille.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-09",
    "Mila veut du thé à la menthe. Une vieille feuille est amère. Ils en cueillent une jeune. Ils arrosent. Le thé sent bon.",
    "Le thé de menthe de Mila",
    "Mila, papa",
    "cuisine près de la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|La bouilloire fait un petit chant.",
            "narrateur|Une vapeur colle au carreau.",
            "narrateur|Le carreau devient un peu flou.",
            "narrateur|Un pot de menthe attend au rebord.",
            "narrateur|Les tiges sont minces.",
            "narrateur|Quelques feuilles sont sombres.",
            "narrateur|Papa pose deux tasses.",
            "narrateur|Les tasses sont déjà un peu chaudes.",
            "papa|Tu sens la menthe, Mila ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Je veux du thé.",
            "papa|On fait du thé, alors.",
            "narrateur|En ce moment, Mila cueille une feuille.",
            "narrateur|Cette feuille est sombre.",
            "narrateur|Elle est un peu sèche.",
            "enfant-f|Je la mets dans l'eau ?",
            "papa|Goûte d'abord, tout doux.",
            "narrateur|Mila pose la feuille sur sa langue.",
            "enfant-f|C'est amer, papa.",
            "papa|Cette feuille est trop vieille.",
            "papa|On cherche une jeune feuille ?",
            "enfant-f|Oui.",
            "narrateur|Papa penche le pot vers le jour.",
            "narrateur|Une petite feuille brille au milieu.",
            "narrateur|Elle est bien verte.",
            "enfant-f|Celle-là ?",
            "papa|Oui, celle-là est jeune.",
            "narrateur|Mila la cueille tout doux.",
            "narrateur|Le pot penche un peu.",
            "papa|La terre est trop sèche.",
            "papa|La menthe a besoin d'eau.",
            "papa|Elle a besoin de lumière.",
            "enfant-f|On arrose ?",
            "papa|Oui, avec moi.",
            "narrateur|Mila tient l'arrosoir avec papa.",
            "narrateur|Ils versent un peu d'eau.",
            "narrateur|La terre devient sombre.",
            "narrateur|Papa pousse le pot.",
            "narrateur|Le jour arrive sur les feuilles.",
            "enfant-f|Elle tient plus droit.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La menthe a soif.",
            "narrateur|Que fait Mila avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila pose la jeune feuille dans la tasse.",
            "narrateur|Papa verse l'eau tout doux.",
            "narrateur|La vapeur sent tout de suite la menthe.",
            "enfant-f|Ça sent bon.",
            "papa|Ce n'est plus amer.",
            "papa|Merci, Mila.",
            "narrateur|Ils soufflent un peu.",
            "narrateur|L'eau est encore chaude.",
            "papa|On attend un peu ?",
            "enfant-f|Oui, papa.",
            "narrateur|Mila regarde le pot au rebord.",
            "narrateur|Les jeunes feuilles brillent.",
            "enfant-f|Elle a de l'eau.",
            "papa|Et de la lumière.",
            "narrateur|Une goutte reste sur la terre.",
            "narrateur|Mila ne la touche pas.",
            "papa|La tasse est prête ?",
            "enfant-f|Presque.",
            "narrateur|Mila souffle encore un peu.",
            "narrateur|La vapeur danse au-dessus de l'eau.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Mila goûte le thé.",
            "enfant-f|Ce n'est pas amer.",
            "papa|C'est la jeune feuille.",
            "narrateur|La tasse chauffe ses mains.",
            "narrateur|Papa goûte aussi.",
            "papa|Ça sent la menthe.",
            "enfant-f|Oui.",
            "narrateur|Le carreau n'est plus flou.",
            "narrateur|La vapeur est partie.",
            "papa|On range l'arrosoir ?",
            "enfant-f|Oui, papa.",
            "narrateur|Mila pose l'arrosoir près du mur.",
            "narrateur|Le métal est encore un peu mouillé.",
            "enfant-f|La menthe a de l'eau.",
            "papa|Oui, et de la lumière.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le thé sent encore la menthe.",
            "enfant-f|La jeune feuille est dedans.",
            "papa|Oui.",
            "narrateur|Le pot tient droit au rebord.",
            "narrateur|Le jour reste sur les feuilles.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "arroser",
        "accepted_examples": "arroser | de l'eau | eau | lumière | avec papa",
        "retry_prompt": "Ils versent de l'eau. Que fait Mila ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-09",
    "Le thé de menthe de Mila",
    "Mila veut du thé. Une feuille trop vieille est amère. Une jeune feuille, de l'eau, de la lumière. Le thé sent la menthe.",
    "D16 Mila (Élodie). N1. Imprévu : feuille amère. Pas « L'histoire est finie ».",
)

# ---------------------------------------------------------------------------
# 10 N1 Nino, papa — tomate en pot. Tuteur qui penche ; ils le redressent.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-10",
    "Nino veut que la tomate tienne droit. Le tuteur penche. Ils le redressent. Ils arrosent. La tige tient au soleil.",
    "Le tuteur de Nino",
    "Nino, papa",
    "rebord de fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un fil de soleil coupe le rebord.",
            "narrateur|Un pot de tomate est là.",
            "narrateur|La terre est un peu claire.",
            "narrateur|Un tuteur en bois penche.",
            "narrateur|La tige penche avec lui.",
            "narrateur|Une petite tomate verte tient encore.",
            "narrateur|Papa pose un arrosoir près du mur.",
            "narrateur|L'arrosoir est rouge et lisse.",
            "papa|Tu vois la tomate, Nino ?",
            "enfant-m|Elle penche, papa.",
            "enfant-m|Je veux qu'elle tienne droit.",
            "papa|Le tuteur penche trop.",
            "narrateur|En ce moment, Nino touche le bois.",
            "narrateur|Le bois est sec.",
            "enfant-m|On le redresse ?",
            "papa|Oui, doucement.",
            "narrateur|Nino tient le tuteur.",
            "narrateur|Papa tient le pot.",
            "narrateur|Ils poussent tout doux.",
            "narrateur|Le tuteur se redresse.",
            "narrateur|La tige aussi.",
            "enfant-m|Elle est droite.",
            "papa|La terre est sèche, tu vois ?",
            "papa|Elle a besoin d'eau.",
            "papa|Elle a besoin de lumière.",
            "enfant-m|On arrose ?",
            "papa|Oui, avec moi.",
            "narrateur|Nino prend l'arrosoir avec papa.",
            "narrateur|Ils versent un peu d'eau.",
            "narrateur|La terre devient sombre.",
            "narrateur|Une goutte file sur le rebord.",
            "narrateur|Nino l'essuie.",
            "enfant-m|Elle boit.",
            "papa|Oui.",
            "narrateur|Papa pousse le pot vers le soleil.",
            "narrateur|Le fil de soleil touche les feuilles.",
            "enfant-m|Elle a de la lumière.",
            "papa|Oui, Nino.",
            "narrateur|Une feuille se redresse un peu.",
            "narrateur|Nino la touche, tout doux.",
            "enfant-m|Elle est douce.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La tomate a soif.",
            "narrateur|Que fait Nino avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino regarde encore le tuteur.",
            "narrateur|Il ne penche plus.",
            "papa|Il tient bien ?",
            "enfant-m|Oui, papa.",
            "narrateur|Papa noue un brin de raphia.",
            "narrateur|Le nœud est doux, pas serré.",
            "enfant-m|Pour la tige.",
            "papa|Oui, pour qu'elle reste droite.",
            "papa|Merci, Nino.",
            "narrateur|Nino pose la main sur la terre.",
            "narrateur|Elle est fraîche, maintenant.",
            "enfant-m|Elle a de l'eau.",
            "papa|Et le soleil, là.",
            "narrateur|La petite tomate verte brille.",
            "papa|On range l'arrosoir ?",
            "enfant-m|Oui.",
            "narrateur|Nino pose l'arrosoir près du mur.",
            "narrateur|Une goutte tombe encore.",
            "narrateur|Nino l'essuie avec le doigt.",
            "enfant-m|Le tuteur est droit.",
            "papa|Oui, il tient.",
            "narrateur|La petite tomate verte brille encore.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le rebord est un peu mouillé.",
            "narrateur|Nino passe le linge.",
            "papa|Tu as fini le rebord ?",
            "enfant-m|Oui, papa.",
            "narrateur|La tige tient droit.",
            "narrateur|Le tuteur aussi.",
            "enfant-m|Elle va grandir ?",
            "papa|Avec de l'eau.",
            "papa|Avec de la lumière.",
            "narrateur|Le fil de soleil reste sur les feuilles.",
            "enfant-m|Je la vois.",
            "papa|Moi aussi.",
            "narrateur|Nino pose le linge près du mur.",
            "narrateur|Le rebord redevient sec.",
            "enfant-m|Elle tient droit, maintenant.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La tomate tient droit dans son pot.",
            "enfant-m|Le tuteur aussi.",
            "papa|Oui.",
            "narrateur|Le fil de soleil reste sur les feuilles.",
            "narrateur|La petite tomate verte attend le jour.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "arroser",
        "accepted_examples": "arroser | de l'eau | eau | lumière | tuteur | avec papa",
        "retry_prompt": "Ils versent de l'eau. Que fait Nino ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-10",
    "Le tuteur de Nino",
    "Nino veut une tomate droite. Le tuteur penche. Ils le redressent, ils arrosent. Le soleil touche les feuilles.",
    "D16 Nino (Bertrand). N1. Imprévu : tuteur. Pas « L'histoire est finie ».",
)

# ---------------------------------------------------------------------------
# 11 N2 Nina, papa — tomate cerise. Une verte, une rouge. Goûter la rouge.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-11",
    "Nina veut goûter la tomate cerise rouge avec papa. Elle croque d'abord une verte, trop dure. Ils arrosent. Ils goûtent la rouge, tiède.",
    "La tomate rouge de Nina",
    "Nina, papa",
    "jardin, pied de tomate cerise",
    {
        "CHK_T0000_P0000": [
            "narrateur|Des tomates cerises pendent, toutes petites.",
            "narrateur|Une est verte, bien ronde.",
            "narrateur|Une autre est rouge, déjà chaude.",
            "narrateur|L'herbe gratte un peu les chevilles.",
            "narrateur|Un arrosoir bleu attend près du pied.",
            "narrateur|La terre du pot est un peu pâle.",
            "papa|Tu les vois, Nina ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Je veux goûter la rouge.",
            "papa|Avec moi ?",
            "enfant-f|Oui, avec toi.",
            "narrateur|En ce moment, Nina tend la main.",
            "narrateur|Ses doigts trouvent d'abord la verte.",
            "narrateur|Elle la détache tout doux.",
            "papa|Celle-là, tu es sûre ?",
            "enfant-f|Elle est ronde.",
            "narrateur|Nina croque un tout petit peu.",
            "enfant-f|Elle est dure, papa.",
            "papa|Elle n'est pas prête.",
            "papa|La rouge a eu plus de soleil.",
            "narrateur|Nina pose la verte dans la main de papa.",
            "narrateur|Les feuilles du pied sont un peu molles.",
            "papa|La terre a soif, tu vois ?",
            "papa|La plante a besoin d'eau.",
            "papa|Elle a besoin de lumière.",
            "enfant-f|On arrose, alors ?",
            "papa|Oui, avec moi.",
            "narrateur|Nina prend l'arrosoir bleu.",
            "narrateur|Papa tient aussi l'anse.",
            "narrateur|Ils versent un peu d'eau au pied.",
            "narrateur|La terre devient sombre.",
            "enfant-f|Elle boit.",
            "papa|Oui.",
            "narrateur|Une abeille passe tout près, puis s'en va.",
            "narrateur|Nina essuie une goutte sur une feuille.",
            "enfant-f|La rouge est encore là.",
            "papa|Elle attend un peu.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La tomate a soif.",
            "narrateur|Que fait Nina avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina pose l'arrosoir dans l'herbe.",
            "narrateur|L'herbe est un peu mouillée.",
            "papa|La rouge, maintenant ?",
            "enfant-f|Oui.",
            "narrateur|Papa penche une feuille.",
            "narrateur|La tomate rouge est tiède.",
            "papa|On la cueille ensemble ?",
            "enfant-f|Oui, papa.",
            "narrateur|Nina la tient, et papa aide.",
            "narrateur|La tomate se détache, toute ronde.",
            "papa|Merci, Nina.",
            "papa|Tu as arrosé, d'abord.",
            "enfant-f|Pour la plante.",
            "papa|Pour qu'elle fasse encore des rouges.",
            "narrateur|Nina souffle un peu sur la tomate.",
            "narrateur|Un grain de terre tombe.",
            "papa|Tu goûtes ?",
            "enfant-f|Avec toi.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina croque la rouge.",
            "enfant-f|Elle est sucrée.",
            "papa|Et tiède.",
            "narrateur|Papa croque l'autre moitié.",
            "narrateur|Le jus sent le soleil.",
            "enfant-f|La verte, on la laisse ?",
            "papa|Oui, elle va mûrir.",
            "papa|Avec de l'eau et de la lumière.",
            "narrateur|Nina essuie ses doigts sur l'herbe.",
            "narrateur|L'arrosoir bleu reste près du pied.",
            "papa|On range l'arrosoir ?",
            "enfant-f|Oui, papa.",
            "narrateur|Nina pose l'arrosoir près du pied.",
            "narrateur|Le bleu de l'arrosoir brille un peu.",
            "enfant-f|La verte va devenir rouge ?",
            "papa|Avec de l'eau, et du soleil.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La tomate rouge a goûté le soleil.",
            "enfant-f|On l'a goûtée aussi.",
            "papa|Oui.",
            "narrateur|Le pied tient dans la terre sombre.",
            "narrateur|La verte attend encore un peu de jour.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "arroser",
        "accepted_examples": "arroser | de l'eau | eau | lumière | avec papa",
        "retry_prompt": "Ils versent de l'eau. Que fait Nina ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-11",
    "La tomate rouge de Nina",
    "Nina veut la tomate cerise rouge. Elle croque une verte, trop dure. Ils arrosent. Ils goûtent la rouge, tiède.",
    "D16 Nina (Maxime). N2. Désir : goûter. Pas « L'histoire est finie ».",
)

# ---------------------------------------------------------------------------
# 12 N3 Raphaël, papa, maman — tomate et thym, deux arrosages. Sauce du jardin.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-12",
    "Raphaël veut une sauce qui sent le jardin. L'arrosoir est vide. Il arrose la tomate avec papa, le thym avec maman. La casserole sent le thym.",
    "La sauce du jardin de Raphaël",
    "Raphaël, papa, maman",
    "jardin puis cuisine, rebord de fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le gravier du jardin craque sous les pas.",
            "narrateur|Une casserole attend déjà dans la cuisine.",
            "narrateur|Dehors, le pied de tomate a des feuilles tièdes.",
            "narrateur|Deux tomates pendent, encore un peu vertes.",
            "papa|Tu sens la terre, Raphaël ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Je veux une sauce du jardin.",
            "maman|Avec du thym, alors.",
            "papa|D'abord la tomate.",
            "narrateur|En ce moment, Raphaël soulève l'arrosoir.",
            "narrateur|L'arrosoir est trop léger.",
            "enfant-m|Il n'y a plus d'eau.",
            "papa|On le remplit au robinet ?",
            "enfant-m|Oui.",
            "narrateur|L'eau tape le métal, tout fort, puis tout doux.",
            "papa|La plante a besoin d'eau.",
            "papa|Elle a besoin de lumière.",
            "narrateur|Ils versent au pied de la tomate.",
            "narrateur|La terre devient foncée.",
            "enfant-m|Elle boit.",
            "maman|Le thym, lui, est à la fenêtre.",
            "papa|On y va après ?",
            "enfant-m|Après, pour la sauce.",
            "narrateur|Raphaël pose l'arrosoir un moment.",
            "narrateur|Une coccinelle traverse une feuille, puis s'en va.",
            "enfant-m|On va au thym, maman ?",
            "maman|Oui, à la fenêtre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël s'occupe des plantes.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Dans la cuisine, le store de la fenêtre est fermé.",
            "narrateur|Le thym est dans l'ombre, un peu terne.",
            "maman|Il n'a pas de lumière, tu vois ?",
            "enfant-m|On ouvre le store ?",
            "maman|Oui, doucement.",
            "narrateur|Raphaël tire le store avec maman.",
            "narrateur|Le jour arrive sur les tiges.",
            "maman|Maintenant, un peu d'eau.",
            "narrateur|Papa tend l'arrosoir.",
            "narrateur|Il est encore un peu lourd.",
            "enfant-m|Avec toi, maman.",
            "maman|Oui, avec un adulte.",
            "narrateur|Ils versent un filet au pied du thym.",
            "narrateur|L'eau sent déjà l'herbe.",
            "papa|Deux arrosages, alors.",
            "papa|La tomate, et le thym.",
            "maman|Merci, Raphaël.",
            "enfant-m|Pour la sauce.",
            "papa|On coupe une branche, tout petit ?",
            "maman|Une seule, le pied reste.",
            "narrateur|Raphaël tient la petite branche.",
            "narrateur|Ses doigts sentent le jardin.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman fait chauffer la casserole.",
            "narrateur|Papa coupe deux tomates du jardin.",
            "narrateur|Le jus tombe dans la sauce, tout rouge.",
            "enfant-m|Le thym, maintenant ?",
            "maman|Oui, tes doigts tout doux.",
            "narrateur|Raphaël effeuille la petite branche.",
            "narrateur|Les feuilles tombent dans le rouge.",
            "papa|Tu sens ?",
            "enfant-m|Ça sent le jardin.",
            "maman|La tomate et le thym, ensemble.",
            "narrateur|La vapeur monte, un peu verte, un peu sucrée.",
            "papa|On a arrosé, avant.",
            "enfant-m|Deux fois.",
            "maman|Oui, l'eau et la lumière.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La casserole chuchote tout bas.",
            "enfant-m|La sauce est prête ?",
            "papa|Bientôt.",
            "maman|Elle sent déjà le jardin.",
            "narrateur|Le thym brille encore au rebord.",
            "narrateur|La vapeur sent le jardin, tout entier.",
        ],
    },
    {**EMPTY, "CHK_T0000_P0000": "enfants_parc"},
    q={
        "expected_answer": "arroser",
        "accepted_examples": "arroser | de l'eau | eau | lumière | tomate | thym",
        "retry_prompt": "Il arrose. Que fait Raphaël ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-12",
    "La sauce du jardin de Raphaël",
    "Raphaël veut une sauce du jardin. Arrosoir vide, tomate avec papa, thym avec maman. La casserole sent le jardin.",
    "D16 Raphaël (Émeline). N3. Deux arrosages. Pas « L'histoire est finie ».",
)
