#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-TMP.MOI.001-06/07 et ATOM-TMP.SAI.001-01..06."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-06  N2  Chouchou, maman
# Calendrier : trouver novembre pour la soupe de courge. Pages qui collent.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-06",
    "Chouchou veut la soupe de courge. Maman dit novembre. Les pages du calendrier collent. Chouchou essuie, trouve novembre, et la casserole chante.",
    "La soupe de novembre",
    "Chouchou, maman",
    "cuisine, calendrier mural, courge sur la table",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vitre de la cuisine a des gouttes.",
            "narrateur|Ça sent l'écorce d'orange, un peu.",
            "narrateur|Une courge orange attend sur le bois.",
            "narrateur|Elle est lourde, presque ronde.",
            "narrateur|Un couteau repose près de l'évier.",
            "narrateur|Maman essuie une miette de pain.",
            "enfant-f|Je veux la soupe, maman.",
            "maman|La soupe de courge ?",
            "enfant-f|Oui.",
            "enfant-f|Celle qui est douce.",
            "maman|On la fait en novembre.",
            "narrateur|Un calendrier pend près de la fenêtre.",
            "narrateur|Les pages sont épaisses, un peu jaunes.",
            "narrateur|Un crayon rouge est coincé dessus.",
            "narrateur|En ce moment, Chouchou touche une page.",
            "narrateur|Le papier est rêche sous son doigt.",
            "enfant-f|Où est novembre ?",
            "maman|Cherche la page, tout doucement.",
            "narrateur|Chouchou tourne une feuille.",
            "narrateur|Une image d'arbre nu apparaît.",
            "enfant-f|C'est novembre ?",
            "maman|Ça, c'est octobre.",
            "maman|Les feuilles tombent encore.",
            "narrateur|Chouchou a les doigts un peu mouillés.",
            "narrateur|Elle a touché la courge, avant.",
            "narrateur|Une goutte reste sur le pouce.",
            "narrateur|Elle tourne encore.",
            "narrateur|Deux pages collent, bien fort.",
            "enfant-f|Elles ne viennent pas.",
            "maman|Tes doigts sont mouillés, Chouchou.",
            "narrateur|Le papier fait un bruit mou.",
            "narrateur|Chh.",
            "narrateur|Les deux pages restent ensemble.",
            "narrateur|Une image d'étoile passe trop vite.",
            "enfant-f|J'ai sauté un mois ?",
            "maman|Peut-être.",
            "maman|On essuie, puis on cherche.",
            "narrateur|Maman tend un linge tiède.",
            "narrateur|Le linge sent le savon de vaisselle.",
            "narrateur|Chouchou frotte ses paumes.",
            "narrateur|Le linge devient un peu orange.",
            "enfant-f|Mes mains sont sèches.",
            "maman|Merci.",
            "maman|Tu peux décoller, maintenant ?",
            "narrateur|Chouchou souffle sur le bord.",
            "narrateur|Elle pince le coin, tout doux.",
            "narrateur|Le papier se sépare, lentement.",
            "narrateur|Une page cachée apparaît.",
            "narrateur|Il y a une petite courge dessinée.",
            "enfant-f|Novembre !",
            "maman|Oui.",
            "maman|C'est le mois de la soupe.",
            "narrateur|Chouchou pose le crayon rouge.",
            "narrateur|Elle fait un rond sur novembre.",
            "narrateur|Le crayon gratte, tout léger.",
            "enfant-f|On coupe la courge ?",
            "maman|Oui.",
            "maman|Tu tiens le saladier ?",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou a trouvé un mois pour la soupe.",
            "narrateur|Lequel ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le couteau tape le bois, tout doux.",
            "narrateur|Toc.",
            "narrateur|La courge s'ouvre, orange dedans.",
            "enfant-f|Elle est comme un soleil.",
            "maman|On met les morceaux dans la casserole.",
            "narrateur|Chouchou pousse un cube orange.",
            "narrateur|Il glisse, puis tombe dans l'eau.",
            "narrateur|Ça sent déjà le chaud, un peu.",
            "maman|Novembre est sur le calendrier.",
            "enfant-f|Et la soupe est dans la casserole.",
            "maman|Les deux ensemble.",
            "narrateur|Une bulle monte, toute ronde.",
            "narrateur|Chouchou regarde novembre, puis la vapeur.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman verse la soupe dans deux bols.",
            "narrateur|La vapeur fait un nuage bas.",
            "narrateur|Chouchou souffle, tout long.",
            "enfant-f|Elle est douce.",
            "maman|C'est la soupe de novembre.",
            "narrateur|Le crayon rouge reste sur la page.",
            "narrateur|La petite courge dessinée brille un peu.",
            "maman|Tu as décollé les pages.",
            "enfant-f|Et j'ai trouvé le mois.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le bol tiédit sous ses mains.",
            "narrateur|La vitre a encore des gouttes.",
            "narrateur|Novembre est ouvert, tout grand.",
            "enfant-f|Encore une cuillère.",
            "maman|Oui.",
            "narrateur|La courge sent le bois et le chaud.",
            "narrateur|Chouchou pose la cuillère, enfin rassasiée.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "novembre",
        "accepted_examples": "novembre | en novembre | le mois | la soupe | courge",
        "retry_prompt": "La soupe de courge, c'est en novembre. Quel mois ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-06",
    "La soupe de novembre",
    "Chouchou veut la soupe de courge. Maman dit novembre. Les pages collent. Elle essuie, trouve la page, la casserole chante.",
    "- Désir : la soupe, pas réciter douze mois.\n"
    "- Imprévu : pages collées (doigts mouillés).\n"
    "- Leçon greffée : novembre, un mois du calendrier.\n"
    "- Troupe D16 : Chouchou, maman. Fin : bol tiède, vitre.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-07  N3  Amir, papa, maman
# Mois : gâteau d'anniversaire d'hiver (décembre), cannelle.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-07",
    "Amir veut un gâteau à la cannelle pour son anniversaire d'hiver. L'étoile colle sur novembre. Il la pose sur décembre. Le four sent le bois chaud.",
    "Le gâteau de décembre",
    "Amir, papa, maman",
    "cuisine d'hiver, calendrier, sachet de cannelle",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un sachet de cannelle est ouvert sur le bois.",
            "narrateur|La poudre brune sent le bois chaud.",
            "narrateur|Un peu de poudre tache la table.",
            "narrateur|Dehors, la haie est grise et immobile.",
            "narrateur|La vitre a un liseré blanc, tout fin.",
            "narrateur|Papa souffle sur ses mains.",
            "maman|Le four est déjà tiède.",
            "enfant-m|Je veux mon gâteau.",
            "enfant-m|Celui à la cannelle.",
            "papa|C'est ton gâteau d'hiver.",
            "maman|On le fait en décembre.",
            "narrateur|Un calendrier pend près du frigo.",
            "narrateur|Une petite étoile en papier attend.",
            "narrateur|Elle est dorée, un peu froissée.",
            "narrateur|En ce moment, Amir prend l'étoile.",
            "narrateur|Le papier brille sous son pouce.",
            "enfant-m|Je la mets sur mon mois.",
            "papa|Quel mois, Amir ?",
            "enfant-m|Décembre.",
            "maman|Celui du gâteau.",
            "narrateur|Les doigts d'Amir ont de la cannelle.",
            "narrateur|Ils sont un peu collants, tout doux.",
            "narrateur|Il appuie l'étoile trop vite.",
            "narrateur|Elle reste sur la page d'avant.",
            "enfant-m|Elle tient.",
            "papa|Regarde bien le mot.",
            "narrateur|Amir se penche.",
            "narrateur|Le mot est long, avec des v.",
            "enfant-m|Novembre ?",
            "maman|Oui.",
            "maman|C'est le mois d'avant.",
            "enfant-m|Ce n'est pas le mien.",
            "papa|On décolle, tout doucement.",
            "narrateur|L'étoile résiste, puis vient.",
            "narrateur|Un peu de poudre brune reste sur novembre.",
            "narrateur|Amir tourne la page.",
            "narrateur|Décembre a un dessin d'étoile, déjà.",
            "enfant-m|Là.",
            "maman|Oui.",
            "maman|Décembre, c'est ton mois.",
            "narrateur|Amir pose l'étoile au bon endroit.",
            "narrateur|Il appuie avec un doigt propre.",
            "narrateur|Papa lui tend un linge.",
            "enfant-m|Mes mains sentent encore la cannelle.",
            "papa|C'est pour la pâte.",
            "maman|Tu verses un peu, Amir ?",
            "narrateur|La poudre tombe en pluie fine.",
            "narrateur|Ça sent plus fort, tout de suite.",
            "enfant-m|Mon gâteau d'hiver.",
            "papa|En décembre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir a un gâteau en décembre.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Maman enfourne le moule.",
            "narrateur|Le four fait un petit clac.",
            "narrateur|L'air de la cuisine devient plus chaud.",
            "enfant-m|Ça sent déjà.",
            "papa|La cannelle aime le four.",
            "narrateur|Amir regarde le calendrier.",
            "narrateur|L'étoile dorée tient sur décembre.",
            "maman|C'est le mois de ton anniversaire.",
            "enfant-m|Et du gâteau.",
            "papa|Les deux, le même mois.",
            "narrateur|Une minute passe, puis une autre.",
            "narrateur|Le liseré blanc fond un peu sur la vitre.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le gâteau sort, tout rond.",
            "narrateur|Le dessus est brun, un peu craquelé.",
            "enfant-m|Il fume.",
            "maman|On attend une minute.",
            "papa|Merci, Amir.",
            "papa|Tu as mis l'étoile au bon mois.",
            "narrateur|Amir pose le sachet, presque vide.",
            "narrateur|Un peu de cannelle reste dans le pli.",
            "enfant-m|Décembre sent bon.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Une part tiède attend dans l'assiette.",
            "narrateur|Amir souffle, puis goûte.",
            "enfant-m|C'est doux.",
            "maman|C'est ton gâteau d'hiver.",
            "papa|En décembre.",
            "narrateur|L'étoile dorée brille encore sur la page.",
            "narrateur|La haie, dehors, reste grise et calme.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "décembre",
        "accepted_examples": "décembre | en décembre | anniversaire | un mois | gâteau | cannelle",
        "retry_prompt": "Le gâteau d'anniversaire est en décembre. Quel mois ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-07",
    "Le gâteau de décembre",
    "Amir veut un gâteau à la cannelle pour décembre. L'étoile colle sur novembre. Il la pose sur décembre. Le four sent le bois.",
    "- Désir : le gâteau d'hiver, pas la liste des douze mois.\n"
    "- Imprévu : étoile collée au mauvais mois (cannelle aux doigts).\n"
    "- Troupe D16 : Amir, papa, maman. Fin : part tiède, haie grise.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-01  N1  Sarah, papa
# Automne vécu : feuille rouge, tas, vent, ils recommencent.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-01",
    "Sarah veut un tas de feuilles rouges. Le vent l'éparpille. Papa et elle recommencent. Le tas revient près du banc.",
    "Le tas rouge de Sarah",
    "Sarah, papa",
    "parc en automne, banc, feuilles",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une feuille rouge colle au banc du parc.",
            "narrateur|Le bois du banc est froid.",
            "narrateur|Ça sent la terre mouillée.",
            "narrateur|Une mousse verte tient au bois.",
            "narrateur|Un oiseau pique une graine.",
            "narrateur|Le bec tape, tout petit.",
            "narrateur|Papa boutonne le manteau.",
            "narrateur|Le vent passe dans les arbres.",
            "narrateur|Des feuilles tombent, tout doux.",
            "papa|Tu as vu la feuille rouge ?",
            "enfant-f|Elle est rouge.",
            "papa|Oui.",
            "narrateur|En ce moment, Sarah la ramasse.",
            "narrateur|Elle est sèche, un peu cassante.",
            "narrateur|Ses doigts sont froids, un peu rouges.",
            "enfant-f|Je veux un tas.",
            "papa|Un tas de feuilles ?",
            "enfant-f|Un grand tas.",
            "papa|On en ramasse beaucoup.",
            "narrateur|Sarah prend une feuille jaune.",
            "narrateur|Elle la pose près du banc.",
            "narrateur|Papa en apporte une brune.",
            "narrateur|Le tas est encore petit.",
            "enfant-f|Encore.",
            "narrateur|Ils marchent sous l'arbre.",
            "narrateur|Les feuilles craquent, sous les bottes.",
            "narrateur|Ça fait cric, cric.",
            "narrateur|Sarah pousse avec le pied.",
            "narrateur|Le tas monte un peu.",
            "papa|Il devient grand.",
            "enfant-f|Encore des rouges.",
            "narrateur|Une feuille rouge vole.",
            "narrateur|Sarah court un peu.",
            "narrateur|Elle l'attrape.",
            "narrateur|Elle la pose sur le tas.",
            "narrateur|Une feuille jaune tient dans les cheveux.",
            "papa|Elle s'est accrochée.",
            "enfant-f|Je la prends.",
            "papa|En été, elles sont vertes.",
            "enfant-f|Là, elles sont rouges.",
            "papa|Oui.",
            "papa|C'est l'automne.",
            "narrateur|Le tas arrive aux genoux.",
            "enfant-f|Il est beau.",
            "narrateur|Le ciel est bas, tout gris.",
            "narrateur|Un vent fort arrive.",
            "narrateur|Il vient de la rue.",
            "narrateur|Les feuilles s'envolent.",
            "narrateur|Le tas s'éparpille.",
            "enfant-f|Oh.",
            "enfant-f|Mon tas.",
            "papa|Le vent l'a pris.",
            "papa|On recommence ?",
            "enfant-f|Oui.",
            "narrateur|Sarah court après une feuille.",
            "narrateur|Papa en ramasse trois.",
            "narrateur|Ils les portent au banc.",
            "narrateur|Le tas recommence, tout bas.",
            "papa|Tu veux encore des rouges ?",
            "enfant-f|Oui, des rouges.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Les feuilles sont rouges.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah pousse encore, tout doux.",
            "narrateur|Papa tient le tas avec le bras.",
            "narrateur|Le vent passe, plus faible.",
            "enfant-f|Il reste.",
            "papa|Oui.",
            "papa|On le garde près du banc.",
            "narrateur|Une feuille rouge tombe sur le chapeau.",
            "narrateur|Papa la pose tout en haut.",
            "enfant-f|Le tas est revenu.",
            "papa|Bravo, Sarah.",
            "papa|Tu as recommencé.",
            "narrateur|Des petits bouts collent aux bottes.",
            "narrateur|Sarah souffle sur une feuille.",
            "narrateur|Elle ne vole plus.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils s'assoient sur le banc froid.",
            "narrateur|Le tas est là, tout près.",
            "enfant-f|Il est à nous.",
            "papa|Oui.",
            "narrateur|Sarah tient une feuille rouge.",
            "narrateur|Elle la fait tourner.",
            "papa|L'automne sent la terre.",
            "enfant-f|Et les feuilles.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le soleil est bas, tout jaune.",
            "narrateur|Le tas fait une ombre ronde.",
            "enfant-f|Je le garde.",
            "papa|On le regardera encore.",
            "narrateur|Sarah pose la feuille sur ses genoux.",
            "narrateur|Le parc craque, tout doucement.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "automne",
        "accepted_examples": "automne | l'automne | en automne | feuilles | rouge",
        "retry_prompt": "Les feuilles sont rouges. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-01",
    "Le tas rouge de Sarah",
    "Sarah veut un tas de feuilles rouges. Le vent l'éparpille. Ils recommencent. Le tas revient près du banc.",
    "- Une saison vécue (automne), pas quatre puces.\n"
    "- Été nommé une fois par papa, pas listé.\n"
    "- Troupe D16 : Sarah, papa. Fin : feuille sur les genoux.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-02  N2  Mila, papa, maman
# Jardin : bourgeon au printemps, tomate en été. Pas quatre puces.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-02",
    "Mila veut voir la tomate du jardin. Au printemps le bourgeon est collé. Plus tard l'été chauffe, la tomate rougit. Elle la cueille.",
    "La tomate de Mila",
    "Mila, papa, maman",
    "jardin, pied de tomate, deux moments de l'année",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le cerisier du jardin a un bourgeon collé.",
            "narrateur|La terre sent l'eau douce.",
            "narrateur|Un arrosoir bleu penche près du mur.",
            "narrateur|Maman ouvre le petit portail.",
            "narrateur|Ça claque, tout léger.",
            "papa|Viens voir le pied, Mila.",
            "narrateur|En ce moment, Mila s'accroupit.",
            "narrateur|Un bourgeon vert brille sur la tige.",
            "enfant-f|Il est fermé.",
            "maman|Il s'ouvre, plus tard.",
            "papa|C'est le printemps, tout petit.",
            "narrateur|Mila touche le bourgeon, un doigt.",
            "narrateur|Il est frais, un peu collant.",
            "enfant-f|Je veux une tomate.",
            "maman|Pas encore.",
            "maman|Il faut le soleil des jours chauds.",
            "narrateur|Ils arrosent un peu, pas trop.",
            "narrateur|L'eau fait un rond sombre.",
            "narrateur|Un oiseau boit dans la soucoupe.",
            "enfant-f|Pousse, petit.",
            "papa|On reviendra.",
            "narrateur|Plus tard, le jardin est chaud.",
            "narrateur|Les dalles brûlent un peu les pieds.",
            "narrateur|Ça sent la feuille chaude, et la terre.",
            "narrateur|Le pied de tomate a grandi.",
            "narrateur|Des feuilles piquent, tout doux.",
            "enfant-f|Une tomate !",
            "maman|Elle est encore pâle.",
            "papa|On attend le rouge.",
            "narrateur|Mila revient le lendemain.",
            "narrateur|Une tomate a un flanc rose.",
            "enfant-f|Presque.",
            "maman|Encore un peu de chaud.",
            "narrateur|Le soleil tape le mur du fond.",
            "narrateur|Une abeille tourne, puis part.",
            "narrateur|Mila attend, les mains sur les genoux.",
            "narrateur|Un jour, la tomate est rouge.",
            "narrateur|Elle est chaude au toucher.",
            "enfant-f|Je la cueille ?",
            "papa|Oui.",
            "papa|Tout doucement, près de la tige.",
            "narrateur|Mila tourne, puis tire.",
            "narrateur|La tomate reste dans sa paume.",
            "enfant-f|Elle est lourde.",
            "maman|C'est l'été, dans le jardin.",
            "papa|Tu t'en souviens, du bourgeon ?",
            "enfant-f|Il était fermé.",
            "enfant-f|Maintenant elle est rouge.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La tomate est rouge et chaude.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Maman rince la tomate sous le robinet.",
            "narrateur|L'eau fait une perle sur la peau.",
            "enfant-f|Je goûte ?",
            "papa|Un morceau chacun.",
            "narrateur|Papa coupe, tout net.",
            "narrateur|Le dedans est rose, avec des pépins.",
            "enfant-f|C'est doux, et un peu chaud.",
            "maman|Merci, Mila.",
            "maman|Tu as attendu le rouge.",
            "narrateur|Un pépin reste sur l'assiette.",
            "narrateur|Mila le pousse du doigt.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils reviennent près du pied.",
            "narrateur|La tige a un petit chapeau vide.",
            "enfant-f|Il reste des vertes.",
            "papa|Elles rougiront aussi.",
            "maman|Le jardin a le temps.",
            "narrateur|L'arrosoir bleu fait une ombre ronde.",
            "narrateur|Mila sent encore la tomate aux doigts.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le mur du fond garde la chaleur.",
            "narrateur|Une abeille revient, puis s'en va.",
            "enfant-f|Le bourgeon a bien poussé.",
            "papa|Oui.",
            "narrateur|La tige vide bouge un peu, dans l'air.",
            "narrateur|Mila referme le petit portail.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "été",
        "accepted_examples": "été | l'été | en été | tomate | chaud",
        "retry_prompt": "La tomate est rouge. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-02",
    "La tomate de Mila",
    "Printemps : bourgeon collé. Été : tomate rouge. Mila cueille, goûte. Pas quatre saisons en puces.",
    "- Deux moments vécus, pas une liste.\n"
    "- Imprévu : tomate encore pâle, elle attend.\n"
    "- Troupe D16 : Mila, papa, maman. Fin : portail, tige vide.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-03  N2  Nino, maman
# Neige puis dégel (hiver → printemps senti).
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-03",
    "Nino veut un chemin dans la neige du jardin. Le tas est blanc. Puis les gouttières gouttent, la neige fond, une pousse verte sort.",
    "Les bottes de Nino",
    "Nino, maman",
    "jardin sous la neige, puis dégel",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les bottes de Nino sont raides près de la porte.",
            "narrateur|Le jardin est blanc, tout silencieux.",
            "narrateur|La haie porte un chapeau de neige.",
            "narrateur|Un oiseau laisse trois petites traces.",
            "narrateur|Ça sent le froid, et la laine du manteau.",
            "maman|On met les bottes, Nino.",
            "enfant-m|Je veux un chemin.",
            "maman|Dans la neige ?",
            "enfant-m|Jusqu'au cerisier.",
            "narrateur|En ce moment, Nino enfile une botte.",
            "narrateur|Le caoutchouc est froid, un peu dur.",
            "narrateur|La seconde botte résiste, puis entre.",
            "maman|Tu as tes gants ?",
            "enfant-m|Oui.",
            "narrateur|Ils ouvrent la porte.",
            "narrateur|L'air pique le nez.",
            "narrateur|Une fumée sort de la bouche de Nino.",
            "narrateur|La neige craque sous les pas.",
            "narrateur|Cric.",
            "narrateur|Nino pousse la neige avec le pied.",
            "narrateur|Un petit chemin apparaît, tout étroit.",
            "enfant-m|Il va au cerisier.",
            "maman|Oui.",
            "maman|Le jardin est tout blanc, ce matin.",
            "narrateur|Nino fait un petit tas, à côté.",
            "narrateur|Le tas est mou, presque brillant.",
            "narrateur|Un gant a une tache mouillée.",
            "enfant-m|Il est à moi.",
            "maman|Il est beau.",
            "narrateur|Plus tard, un bruit commence.",
            "narrateur|Les gouttières gouttent, une par une.",
            "narrateur|Ploc.",
            "narrateur|Ploc.",
            "enfant-m|Ça tombe.",
            "maman|La neige devient de l'eau.",
            "narrateur|Le chemin de Nino s'élargit, tout mou.",
            "narrateur|Les bottes glissent un peu.",
            "enfant-m|Mon tas baisse.",
            "maman|Il fond.",
            "maman|Tu vois la terre, là ?",
            "narrateur|Une tache brune apparaît près de la dalle.",
            "narrateur|Nino s'accroupit.",
            "narrateur|Une toute petite pousse verte sort.",
            "enfant-m|Elle était sous la neige ?",
            "maman|Oui.",
            "maman|Le jardin se réveille.",
            "enfant-m|Il n'est plus tout blanc.",
            "maman|Le froid s'en va, tout doucement.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La neige fond, une pousse sort.",
            "narrateur|Quelle saison arrive ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino touche la pousse, un doigt.",
            "narrateur|Elle est froide, et très tendre.",
            "enfant-m|Ne marche pas dessus.",
            "maman|On fait un rond, avec des cailloux.",
            "narrateur|Nino pose trois cailloux mouillés.",
            "narrateur|L'eau brille dessus.",
            "maman|Merci, Nino.",
            "maman|Tu as gardé la pousse.",
            "enfant-m|Le chemin est de la boue, maintenant.",
            "maman|On rince les bottes, après.",
            "narrateur|Une goutte tombe encore de la gouttière.",
            "narrateur|Nino essuie un caillou sur sa manche.",
            "narrateur|La pousse brille, toute petite.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils rentrent.",
            "narrateur|Les bottes laissent deux traces mouillées.",
            "enfant-m|Mon tas n'est plus là.",
            "maman|Il est devenu de l'eau.",
            "maman|Et la pousse est là.",
            "narrateur|Nino pose les gants sur le radiateur.",
            "narrateur|Ils sentent encore le froid du jardin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La haie a perdu son chapeau blanc.",
            "narrateur|Une branche goutte, tout lentement.",
            "enfant-m|Je reviendrai voir la pousse.",
            "maman|Oui.",
            "narrateur|Les bottes sèchent près de la porte.",
            "narrateur|Le jardin sent la terre, enfin.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "printemps",
        "accepted_examples": "printemps | le printemps | au printemps | dégel | pousse",
        "retry_prompt": "La neige fond, une pousse sort. Quelle saison arrive ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-03",
    "Les bottes de Nino",
    "Nino veut un chemin dans la neige. Les gouttières gouttent. La neige fond. Une pousse verte sort.",
    "- Hiver senti puis printemps senti, pas une liste de quatre.\n"
    "- Imprévu : le tas fond, le chemin devient boue.\n"
    "- Troupe D16 : Nino, maman. Fin : bottes, terre.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-04  N2  Nina, maman
# Été : orage puis lumière, criquets.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-04",
    "Nina veut écouter les criquets dans le jardin chaud. L'orage arrive. Elles attendent sous l'auvent. La lumière revient, les criquets aussi.",
    "Les criquets de Nina",
    "Nina, maman",
    "jardin d'été, auvent, orage",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'air de la cuisine est lourd, presque collant.",
            "narrateur|Les volets laissent une bande de soleil.",
            "narrateur|Ça sent l'abricot, sur l'assiette.",
            "narrateur|Nina a les genoux chauds, déjà.",
            "enfant-f|On va au jardin ?",
            "maman|Oui.",
            "maman|Les dalles sont chaudes, attention.",
            "narrateur|En ce moment, Nina pousse la porte.",
            "narrateur|L'air dehors est encore plus lourd.",
            "narrateur|Un criquet chante près du mur.",
            "maman|Tu l'entends, Nina ?",
            "enfant-f|Je l'entends.",
            "maman|Il aime le chaud.",
            "narrateur|Nina s'assoit sur la marche.",
            "narrateur|La pierre brûle un peu les cuisses.",
            "narrateur|Elle pose l'abricot à côté.",
            "enfant-f|Encore un criquet.",
            "maman|Ils sont plusieurs, dans l'herbe sèche.",
            "narrateur|Le ciel, au fond, devient gris.",
            "narrateur|Un vent court passe, tout sec.",
            "narrateur|Les feuilles du figuier se retournent.",
            "enfant-f|Il va pleuvoir ?",
            "maman|Un orage, je crois.",
            "narrateur|Un grognement arrive, loin.",
            "narrateur|Nina serre l'abricot.",
            "maman|On va sous l'auvent.",
            "narrateur|Elles reculent de deux pas.",
            "narrateur|La première goutte tape le zinc.",
            "narrateur|Toc.",
            "narrateur|Puis beaucoup, toutes ensemble.",
            "enfant-f|Les criquets ?",
            "maman|Ils se taisent, le temps de la pluie.",
            "narrateur|L'eau court sur les dalles chaudes.",
            "narrateur|Ça sent la terre mouillée, tout fort.",
            "narrateur|L'abricot a une goutte sur la peau.",
            "enfant-f|Mon abricot est mouillé.",
            "maman|On l'essuie, après.",
            "narrateur|Le tonnerre passe au-dessus du toit.",
            "narrateur|Nina se colle un peu à maman.",
            "maman|On attend la lumière.",
            "narrateur|La pluie ralentit, puis s'arrête.",
            "narrateur|Un rayon revient sur le figuier.",
            "narrateur|Les feuilles brillent, toutes neuves.",
            "enfant-f|C'est fini ?",
            "maman|Oui.",
            "maman|Écoute.",
            "narrateur|Un criquet recommence, tout près.",
            "enfant-f|Il est là !",
            "maman|L'été reprend, après l'orage.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait chaud, les criquets chantent.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina essuie l'abricot sur sa robe.",
            "narrateur|Une tache d'eau reste, toute claire.",
            "enfant-f|Il est encore bon.",
            "maman|Oui.",
            "maman|Tu as attendu sous l'auvent.",
            "narrateur|Les dalles fument un peu, au soleil.",
            "narrateur|Ça sent le chaud et l'eau, ensemble.",
            "enfant-f|Encore un criquet.",
            "maman|Bravo, Nina.",
            "maman|Tu l'as entendu revenir.",
            "narrateur|Le figuier goutte encore, une feuille.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles restent sur la marche.",
            "narrateur|La pierre est plus douce, maintenant.",
            "enfant-f|L'orage est parti.",
            "maman|Et la lumière est revenue.",
            "narrateur|Nina croque l'abricot.",
            "narrateur|Le jus est tiède, un peu sucré.",
            "maman|C'est l'été, dans notre jardin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le zinc sèche, tout lentement.",
            "narrateur|Un criquet chante encore près du mur.",
            "enfant-f|Je reste un peu.",
            "maman|Oui.",
            "narrateur|La bande de soleil a grandi sur le sol.",
            "narrateur|Nina pose le noyau sur la marche chaude.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "été",
        "accepted_examples": "été | l'été | en été | chaud | criquets",
        "retry_prompt": "Il fait chaud, les criquets chantent. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-04",
    "Les criquets de Nina",
    "Nina veut les criquets du jardin chaud. Orage, auvent, lumière, les criquets reprennent.",
    "- Été vécu (chaleur, orage, criquets), pas quatre puces.\n"
    "- Imprévu : orage, abricot mouillé.\n"
    "- Troupe D16 : Nina, maman. Fin : noyau sur la marche.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-05  N3  Raphaël, papa
# Quatre objets : gland, coquillage, pomme, flocon de laine. Mini-scènes.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-05",
    "Raphaël ouvre la boîte de papa. Gland, coquillage, pomme, flocon de laine : chaque chose ouvre une petite scène. Il range, la boîte sent encore le carton.",
    "La boîte de Raphaël",
    "Raphaël, papa",
    "salon près de la fenêtre, puis un pas au jardin",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sous la fenêtre, une boîte en carton attend.",
            "narrateur|Un carré de soleil la touche, tout bas.",
            "narrateur|Ça sent le papier sec, et un peu de poussière.",
            "narrateur|Papa s'assoit par terre, les jambes pliées.",
            "enfant-m|Je peux l'ouvrir ?",
            "papa|Oui.",
            "papa|C'est la boîte des choses gardées.",
            "narrateur|En ce moment, Raphaël soulève le couvercle.",
            "narrateur|Le carton fait un bruit doux.",
            "narrateur|Un gland roule vers le bord.",
            "enfant-m|Il est dur.",
            "papa|Prends-le.",
            "narrateur|Le gland est brun, un peu luisant.",
            "narrateur|Raphaël le serre dans la paume.",
            "papa|Tu te souviens du grand chêne ?",
            "enfant-m|Les feuilles craquaient.",
            "narrateur|Ils regardent par la vitre.",
            "narrateur|Le chêne du jardin a des feuilles sèches.",
            "narrateur|Une tombe, tout lentement.",
            "papa|Le gland vient de là.",
            "enfant-m|On le remettra sous l'arbre.",
            "narrateur|Raphaël cherche encore dans la boîte.",
            "narrateur|Un coquillage blanc apparaît.",
            "narrateur|Il est rêche d'un côté, lisse de l'autre.",
            "enfant-m|Je l'écoute ?",
            "papa|Approche-le de l'oreille.",
            "narrateur|Raphaël entend un souffle, tout loin.",
            "enfant-m|Ça fait la mer.",
            "papa|Le sable était chaud, ce jour-là.",
            "papa|On avait soif, et les pieds brûlaient.",
            "enfant-m|Et le sel, sur les lèvres.",
            "narrateur|Le coquillage reste un moment contre sa joue.",
            "narrateur|Il est frais, malgré le souvenir du chaud.",
            "narrateur|Une pomme ronde attend au fond.",
            "narrateur|Elle sent encore un peu le sucré.",
            "enfant-m|On la mange ?",
            "papa|On va la voir près de l'arbre.",
            "narrateur|Ils sortent un pas, dans le jardin.",
            "narrateur|Le pommier a une petite fleur blanche.",
            "narrateur|Elle tient à une branche basse.",
            "papa|Au printemps, l'arbre s'ouvre comme ça.",
            "enfant-m|La pomme vient de ces fleurs ?",
            "papa|Oui.",
            "papa|D'abord la fleur, ensuite le fruit.",
            "narrateur|Raphaël pose la pomme sous la fleur.",
            "narrateur|Une abeille passe, puis s'en va.",
            "narrateur|Ils rentrent, la pomme dans la main.",
            "narrateur|Au fond de la boîte, un flocon de laine.",
            "narrateur|Il est blanc, tout léger.",
            "enfant-m|On souffle ?",
            "papa|Doucement.",
            "narrateur|Le flocon vole, puis retombe.",
            "narrateur|La vitre, à côté, est un peu froide.",
            "papa|Comme la neige, quand elle flotte.",
            "enfant-m|Il ne fond pas.",
            "papa|C'est de la laine.",
            "papa|On le garde pour le jour blanc.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël entend la mer dans le coquillage.",
            "narrateur|Le sable était chaud.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël repose le coquillage.",
            "narrateur|Il le met à côté du gland.",
            "enfant-m|La pomme, et le flocon aussi.",
            "papa|Quatre choses, quatre moments.",
            "narrateur|Le flocon de laine reste un peu sur le bord.",
            "narrateur|Raphaël le pousse, tout doux.",
            "papa|Merci, Raphaël.",
            "papa|Tu as ouvert chaque chose.",
            "enfant-m|Le chêne, la mer, la fleur, la neige.",
            "papa|Oui.",
            "narrateur|Le carré de soleil a bougé sur le carton.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Raphaël referme le couvercle.",
            "narrateur|Le carton sent encore le papier sec.",
            "enfant-m|On la range sous la fenêtre ?",
            "papa|Oui.",
            "papa|Elle attendra.",
            "narrateur|Une feuille du chêne colle encore à la vitre.",
            "narrateur|Raphaël la montre, sans rien dire.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le flocon a glissé, tout seul.",
            "narrateur|Il repose sur le rebord, dans le soleil.",
            "enfant-m|Il vole encore un peu.",
            "papa|On le remettra, tout à l'heure.",
            "narrateur|La boîte est fermée, chaude au toucher.",
            "narrateur|Raphaël pose la main dessus, et reste.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "été",
        "accepted_examples": "été | l'été | en été | mer | chaud | coquillage",
        "retry_prompt": "Le sable était chaud, près de la mer. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-05",
    "La boîte de Raphaël",
    "Quatre objets, quatre mini-scènes : gland (chêne), coquillage (mer chaude), pomme (fleur du pommier), flocon (neige). Pas une liste de noms.",
    "- Saisons via objets, pas « printemps, été, automne, hiver ».\n"
    "- Question greffée sur le coquillage / l'été.\n"
    "- Troupe D16 : Raphaël, papa. Fin : flocon sur le rebord.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-06  N1  Aniss, maman, papa
# Printemps : pousse dans le pot. Trop d'eau, terre déborde, ils essuient.
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-06",
    "Aniss veut voir une pousse dans le pot. Il verse trop d'eau. La terre déborde. Ils essuient. La pousse verte reste.",
    "Le pot d'Aniss",
    "Aniss, maman, papa",
    "rebord de fenêtre, pot en terre cuite",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sur le rebord, un pot en terre cuite chauffe.",
            "narrateur|La terre sent l'eau et le bois.",
            "narrateur|Un grain de terre cuite brille.",
            "narrateur|Un rai de soleil traverse la vitre.",
            "narrateur|Maman ouvre un peu la fenêtre.",
            "narrateur|Un oiseau chante, tout près.",
            "papa|Tu vois le pot, Aniss ?",
            "enfant-m|Oui.",
            "enfant-m|Il y a une pousse ?",
            "maman|Regarde bien.",
            "narrateur|En ce moment, Aniss se hausse.",
            "narrateur|Un fil vert sort de la terre.",
            "narrateur|Il est recourbé, tout tendre.",
            "enfant-m|Elle est là !",
            "papa|Tout petit, tout vert.",
            "enfant-m|Je veux l'arroser.",
            "maman|Un peu d'eau, pas trop.",
            "narrateur|Papa tend le petit arrosoir.",
            "narrateur|Il est bleu, un peu lourd.",
            "narrateur|Aniss le penche.",
            "narrateur|L'eau tombe trop vite.",
            "narrateur|Glou, glou.",
            "enfant-m|Oh.",
            "narrateur|La terre devient boue.",
            "narrateur|Elle déborde sur le rebord.",
            "narrateur|Un filet brun court vers le bois.",
            "narrateur|Ça sent la boue, tout fort.",
            "maman|C'est trop d'eau.",
            "papa|On arrête.",
            "enfant-m|La pousse ?",
            "maman|Elle est encore là.",
            "narrateur|Le fil vert brille, tout mouillé.",
            "papa|On essuie, Aniss.",
            "narrateur|Maman tend un linge.",
            "narrateur|Le linge est rêche, déjà tiède.",
            "enfant-m|Je frotte ?",
            "maman|Oui.",
            "narrateur|Aniss frotte le rebord.",
            "narrateur|Ses doigts sont bruns, un peu.",
            "narrateur|La terre tache le linge.",
            "narrateur|Papa tient le pot, bien droit.",
            "enfant-m|C'est sale.",
            "papa|On peut nettoyer.",
            "narrateur|Le bois redevient clair, un peu.",
            "maman|La pousse aime un peu d'eau.",
            "maman|Pas toute la carafe.",
            "enfant-m|La prochaine fois, un peu.",
            "papa|Oui.",
            "narrateur|Un oiseau reprend, derrière la vitre.",
            "narrateur|Le soleil chauffe le pot, encore.",
            "enfant-m|Elle pousse, au printemps.",
            "maman|Oui.",
            "papa|En été, elle sera plus grande.",
            "enfant-m|Pas trop d'eau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La pousse est verte, dans le pot.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss pose l'arrosoir, bien droit.",
            "narrateur|Une goutte tombe encore, puis plus.",
            "enfant-m|Elle est sauve.",
            "maman|Oui.",
            "maman|Tu as essuyé le rebord.",
            "papa|Merci, Aniss.",
            "narrateur|Le fil vert se redresse un peu.",
            "narrateur|La terre est sombre, plus calme.",
            "enfant-m|Je la regarde.",
            "papa|On la regarde ensemble.",
            "narrateur|Une goutte sèche sur la terre cuite.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman referme un peu la fenêtre.",
            "narrateur|Le linge taché reste sur le bord.",
            "papa|On le rince, après.",
            "enfant-m|Le pot est lourd, maintenant.",
            "maman|Il a trop bu, un moment.",
            "narrateur|Aniss pose un doigt près de la pousse.",
            "narrateur|Il ne touche pas, il regarde.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le rai de soleil a bougé.",
            "narrateur|Il touche encore le pot chaud.",
            "enfant-m|Pousse, petit.",
            "papa|Oui.",
            "maman|Tout doucement.",
            "narrateur|La terre sent encore l'eau, tout près.",
            "narrateur|Aniss reste, le nez contre la vitre.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "printemps",
        "accepted_examples": "printemps | le printemps | au printemps | pousse | vert",
        "retry_prompt": "La pousse est verte. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-06",
    "Le pot d'Aniss",
    "Aniss veut la pousse du pot. Trop d'eau, terre déborde. Ils essuient. La pousse reste.",
    "- Printemps vécu (pousse), été nommé une fois par papa.\n"
    "- Imprévu : trop d'eau, rebord sale.\n"
    "- Troupe D16 : Aniss, maman, papa. Fin : nez contre la vitre.",
)
