#!/usr/bin/env python3
"""F-NAR-008 — second beat lived, never named as a lesson."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

CHUNKS = (
    "CHK_T0000_P0000",
    "CHK_T0000_P0000_Q0001",
    "CHK_T0000_P0000_C0001",
    "CHK_T0000_P0000_END",
    "CHK_T0000_P0000_END_F0001",
)
EMPTY = {k: "" for k in CHUNKS}

# ---------------------------------------------------------------------------
# ATOM-EMO.LEX.005-04  N3  Raphaël, Nina, papa — puzzle, cartes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-EMO.LEX.005-04",
    "Raphaël veut le toit rouge du puzzle. Nina prend la pièce. "
    "Il dit sa colère, recule, rejoint papa. Le soir, une carte glisse. "
    "Il recule encore. Le toit retrouve sa place.",
    "Le puzzle de Raphaël",
    "Raphaël, Nina, papa",
    "salon puis table, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vitre de la salle est toute embuée.",
            "narrateur|Un petit rond y est dessiné au doigt.",
            "narrateur|Dedans, ça sent la soupe à la carotte.",
            "narrateur|Un plaid de laine attend sur le fauteuil.",
            "narrateur|Le plaid est beige, un peu rêche.",
            "narrateur|Une boîte de cartes dort sous la table.",
            "narrateur|Le carton sent le papier sec.",
            "papa|Raphaël, tes pieds sont au chaud ?",
            "enfant-m|Oui, papa.",
            "enfant-m|J'ai mes chaussettes épaisses.",
            "papa|Le puzzle est sur le tapis.",
            "enfant-m|Je veux le toit rouge.",
            "papa|Le milieu est encore vide.",
            "narrateur|En ce moment, Raphaël pose des pièces.",
            "narrateur|Les pièces sont lisses et un peu froides.",
            "narrateur|Nina est là, près de lui.",
            "narrateur|Le tapis est épais sous les genoux.",
            "enfant-m|Le milieu, c'est le toit rouge.",
            "papa|Tu y es presque.",
            "narrateur|Nina prend la pièce du milieu.",
            "narrateur|Le puzzle se défait.",
            "narrateur|Les pièces glissent sur le tapis.",
            "narrateur|Raphaël sent son visage chaud.",
            "narrateur|Son ventre est dur.",
            "enfant-m|Je suis en colère.",
            "narrateur|Il ouvre les doigts.",
            "narrateur|Ses mains restent loin de Nina.",
            "narrateur|Il recule d'un pas.",
            "narrateur|Il marche vers le canapé.",
            "narrateur|Le plaid rêche touche son bras.",
            "narrateur|Il souffle trois fois.",
            "narrateur|Puis il va vers papa.",
            "enfant-m|Papa, la pièce du milieu est partie.",
            "papa|Je t'écoute.",
            "papa|Tu veux venir près du plaid ?",
            "enfant-m|Oui, papa.",
            "narrateur|Raphaël s'assoit contre le fauteuil.",
            "narrateur|Le ventre se desserre un peu.",
            "papa|On reste ici un moment ?",
            "enfant-m|Un moment.",
            "narrateur|Nina pose la pièce près de la boîte.",
            "narrateur|Le toit rouge attend, tout seul.",
            "narrateur|Plus tard, la lampe fait un cercle jaune.",
            "narrateur|La table est lisse sous les cartes.",
            "narrateur|Papa glisse une carte dans la boîte.",
            "enfant-m|Je veux celle-là, la bleue.",
            "papa|Elle est un peu glissante.",
            "narrateur|La carte part sur le bois.",
            "narrateur|Nina la prend.",
            "narrateur|Le visage de Raphaël redevient chaud.",
            "narrateur|Son ventre se durcit.",
            "narrateur|Il ouvre encore les doigts.",
            "narrateur|Il recule vers le fauteuil.",
            "narrateur|Le plaid est tiède, maintenant.",
            "narrateur|Il va près de papa.",
            "enfant-m|Nina a pris la carte.",
            "papa|Je t'écoute.",
            "papa|On s'assoit un peu ?",
            "enfant-m|Oui.",
            "narrateur|Raphaël pose les mains sur ses genoux.",
            "narrateur|Les cartes restent sur la table.",
            "papa|La soupe sent encore, tu trouves ?",
            "enfant-m|Oui.",
            "enfant-m|La carotte.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël est en colère.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël revient près du tapis.",
            "narrateur|Les pièces sont froides, encore.",
            "papa|On cherche le toit rouge ?",
            "enfant-m|Il est près de la boîte.",
            "narrateur|Nina pousse la pièce vers lui.",
            "narrateur|Raphaël la pose au milieu.",
            "narrateur|Le toit retrouve la maison.",
            "papa|Bravo, Raphaël.",
            "enfant-m|Elle tient.",
            "papa|Oui.",
            "narrateur|Le plaid reste sur le fauteuil.",
            "narrateur|La soupe sent encore un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Raphaël s'assoit près de papa.",
            "narrateur|Les cartes rentrent dans le carton.",
            "papa|On pose la boîte sous la table ?",
            "enfant-m|Oui, papa.",
            "narrateur|Le carton sent encore le papier sec.",
            "enfant-m|Le toit est rouge, maintenant.",
            "papa|Il brille un peu.",
            "narrateur|La vitre n'est plus embuée.",
            "narrateur|Le cercle jaune de la lampe reste.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le puzzle est entier.",
            "papa|Merci, Raphaël.",
            "narrateur|Le toit rouge reste au milieu.",
            "narrateur|La soupe fume encore, tout doux.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "s'éloigner",
        "accepted_examples": "s'éloigner | vers papa | adulte | mains loin | colère",
        "retry_prompt": "Raphaël ouvre les doigts. Puis il va où ?",
    },
)
relecture(
    "ATOM-EMO.LEX.005-04",
    "Le puzzle de Raphaël",
    "Raphaël veut le toit rouge. Nina prend la pièce. Il dit sa colère, "
    "recule vers le canapé, rejoint papa. Le soir, une carte glisse. "
    "Il recule encore. Le toit retrouve sa place.",
    "Second temps : cartes sous la lampe, vécu, pas nommé. "
    "Pas « même leçon », pas « tu as repris le geste ».",
)

# ---------------------------------------------------------------------------
# ATOM-EMO.LEX.005-06  N3  Victorina, Sarah, papa — arrosoir, puzzle
# ---------------------------------------------------------------------------
write_story(
    "ATOM-EMO.LEX.005-06",
    "Victorina veut arroser la menthe. Sarah prend l'arrosoir. "
    "Elle dit sa colère, va au banc, rejoint papa. Au salon, une pièce glisse. "
    "Elle recule encore. La menthe boit, le soir.",
    "L'arrosoir de Victorina",
    "Victorina, Sarah, papa",
    "jardin puis salon",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une goutte tombe du bec de zinc.",
            "narrateur|Elle éclate sur le gravier.",
            "narrateur|Le gravier fait un petit bruit clair.",
            "narrateur|La menthe sent fort, tout près.",
            "narrateur|Les feuilles sont fraîches et un peu poilues.",
            "narrateur|Une coccinelle marche sur une tige.",
            "narrateur|Des sandales mouillées attendent près de la porte.",
            "papa|Victorina, tu as vu la coccinelle ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Elle a des points noirs.",
            "papa|L'eau est fraîche, ce matin.",
            "enfant-f|Je veux arroser la menthe.",
            "papa|Tout doux, un peu d'eau.",
            "narrateur|En ce moment, Victorina arrose les fleurs.",
            "narrateur|L'eau est fraîche sur ses doigts.",
            "narrateur|Sarah est là, près des plants.",
            "enfant-f|La menthe a soif.",
            "papa|Le bec de zinc goutte encore.",
            "narrateur|Sarah prend l'arrosoir.",
            "narrateur|L'eau part sur le gravier.",
            "narrateur|Victorina sent son visage chaud.",
            "narrateur|Son ventre est dur.",
            "enfant-f|Je suis en colère.",
            "narrateur|Elle ouvre les doigts.",
            "narrateur|Les mains restent loin de Sarah.",
            "narrateur|Elle recule vers le banc.",
            "narrateur|Le bois du banc est tiède.",
            "narrateur|Elle souffle trois fois.",
            "narrateur|Puis elle va vers papa.",
            "enfant-f|Papa, l'arrosoir est parti.",
            "papa|Je t'écoute.",
            "papa|Tu veux t'asseoir un peu ?",
            "enfant-f|Oui, papa.",
            "narrateur|Victorina pose sa main dans la main de papa.",
            "narrateur|La menthe sent encore.",
            "narrateur|Plus tard, au salon, le tapis est doux.",
            "narrateur|Un puzzle attend près de la table basse.",
            "narrateur|Une pièce bleue brille un peu.",
            "enfant-f|Je veux le ciel, là.",
            "papa|Elle est lisse, cette pièce.",
            "narrateur|La pièce glisse.",
            "narrateur|Sarah la prend.",
            "narrateur|Le visage de Victorina redevient chaud.",
            "narrateur|Son ventre se durcit.",
            "narrateur|Elle ouvre encore les doigts.",
            "narrateur|Elle recule vers la fenêtre.",
            "narrateur|Le bois du rebord est froid.",
            "narrateur|Elle va près de papa.",
            "enfant-f|Sarah a pris la pièce.",
            "papa|Je t'écoute.",
            "papa|On reste près de la fenêtre ?",
            "enfant-f|Un moment.",
            "narrateur|Victorina souffle.",
            "narrateur|Le ventre se desserre un peu.",
            "papa|La menthe t'attend dehors, tu crois ?",
            "enfant-f|Oui.",
            "enfant-f|Elle a encore soif.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|L'arrosoir de Victorina part.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorina revient près de la porte.",
            "narrateur|L'arrosoir repose contre le zinc.",
            "papa|On va voir la menthe ?",
            "enfant-f|Oui.",
            "enfant-f|Tout doux.",
            "narrateur|Sarah tend l'anse.",
            "narrateur|Victorina verse un filet d'eau.",
            "narrateur|La terre devient sombre.",
            "papa|Bravo, Victorina.",
            "enfant-f|Elle boit.",
            "papa|Oui.",
            "narrateur|Les sandales sèchent près de la porte.",
            "narrateur|Le zinc est encore un peu mouillé.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorina s'assoit près de papa.",
            "narrateur|Le puzzle reste sur la table.",
            "papa|On laisse les pièces pour plus tard ?",
            "enfant-f|Oui, papa.",
            "narrateur|Une feuille de menthe colle à son doigt.",
            "enfant-f|Ça sent fort.",
            "papa|C'est la menthe.",
            "narrateur|La coccinelle n'est plus sur la tige.",
            "narrateur|Le banc du jardin reste tiède.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|La menthe a de l'eau.",
            "papa|Merci, Victorina.",
            "narrateur|Une goutte brille encore sur une feuille.",
            "narrateur|Le gravier redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "jardin",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "jardin",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "s'éloigner",
        "accepted_examples": "s'éloigner | vers papa | adulte | mains loin | colère",
        "retry_prompt": "Victorina ouvre les doigts. Puis elle va où ?",
    },
)
relecture(
    "ATOM-EMO.LEX.005-06",
    "L'arrosoir de Victorina",
    "Victorina veut arroser la menthe. Sarah prend l'arrosoir. "
    "Elle dit sa colère, va au banc, rejoint papa. Au salon, une pièce glisse. "
    "Elle recule vers la fenêtre. La menthe boit.",
    "Second temps : puzzle au salon, vécu. Fin : la menthe a de l'eau.",
)

# ---------------------------------------------------------------------------
# ATOM-EMO.LEX.005-07  N3  Nina, Victorino, papa — tour, cuillère
# ---------------------------------------------------------------------------
write_story(
    "ATOM-EMO.LEX.005-07",
    "Nina veut une tour, le cube rouge en haut. Victorino pose trop vite. "
    "Elle dit sa colère, recule, rejoint papa. À la cuisine, la cuillère part. "
    "Elle recule encore. La tour se relève.",
    "La tour de Nina",
    "Nina, Victorino, papa",
    "chambre puis cuisine",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un rayon jaune traverse la chambre.",
            "narrateur|La poussière danse au-dessus du tapis.",
            "narrateur|Une chaussette attend près du lit.",
            "narrateur|Elle est un peu retournée.",
            "narrateur|Une pile de livres penche contre le mur.",
            "narrateur|Les livres sentent le papier chaud.",
            "narrateur|Des cubes en bois sont au milieu.",
            "narrateur|Le bois sent la forêt, tout doux.",
            "papa|Nina, je pose les livres.",
            "enfant-f|Moi, je fais une tour.",
            "papa|Une tour bien droite ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Le rouge tout en haut.",
            "narrateur|En ce moment, Nina pose un cube.",
            "narrateur|Puis un autre.",
            "narrateur|La tour monte.",
            "narrateur|Victorino est là, près du tapis.",
            "narrateur|Papa empile encore un livre.",
            "enfant-f|Encore un, le rouge.",
            "papa|Tu y es presque.",
            "narrateur|Victorino pose un cube trop vite.",
            "narrateur|La tour tombe.",
            "narrateur|Les cubes roulent.",
            "narrateur|Nina sent son visage chaud.",
            "narrateur|Son ventre est dur.",
            "enfant-f|Je suis en colère.",
            "narrateur|Elle ouvre les doigts.",
            "narrateur|Les mains restent loin de Victorino.",
            "narrateur|Elle recule vers le tapis du lit.",
            "narrateur|Elle souffle trois fois.",
            "narrateur|Puis elle va vers papa.",
            "enfant-f|Papa, la tour est tombée.",
            "papa|Je t'écoute.",
            "papa|Tu veux venir près des livres ?",
            "enfant-f|Oui, papa.",
            "narrateur|Nina s'assoit contre la pile.",
            "narrateur|Le papier est tiède sous sa joue.",
            "papa|On reste ici un moment ?",
            "enfant-f|Un moment.",
            "narrateur|Plus tard, à la cuisine, la table est tiède.",
            "narrateur|Ça sent le lait chaud.",
            "narrateur|Une petite cuillère brille dans le bol.",
            "enfant-f|C'est ma cuillère.",
            "papa|Le lait est encore un peu chaud.",
            "narrateur|Victorino prend la cuillère de Nina.",
            "narrateur|Le lait tremble dans le bol.",
            "narrateur|Nina sent encore la chaleur au visage.",
            "narrateur|Son ventre se durcit.",
            "narrateur|Elle ouvre encore les doigts.",
            "narrateur|Elle recule vers l'évier.",
            "narrateur|Le carrelage est froid sous ses pieds.",
            "narrateur|Elle va près de papa.",
            "enfant-f|Victorino a pris ma cuillère.",
            "papa|Je t'écoute.",
            "papa|On s'assoit un peu ?",
            "enfant-f|Oui.",
            "narrateur|Nina pose les mains sur ses genoux.",
            "narrateur|Le lait fume encore, tout doux.",
            "papa|Ta tour t'attend, tu crois ?",
            "enfant-f|Oui.",
            "enfant-f|Le rouge tout en haut.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La tour de Nina tombe.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina revient près du tapis.",
            "narrateur|Les cubes sont épars, un peu tièdes.",
            "papa|On reprend le rouge ?",
            "enfant-f|Tout en haut.",
            "narrateur|Victorino pousse un cube vers elle.",
            "narrateur|Nina pose, puis pose encore.",
            "narrateur|La tour se relève.",
            "papa|Bravo, Nina.",
            "enfant-f|Elle tient.",
            "papa|Oui.",
            "narrateur|Le rayon tient encore la poussière.",
            "narrateur|La chaussette attend près du lit.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina s'assoit près de papa.",
            "narrateur|Le lait n'est plus trop chaud.",
            "papa|Tu goûtes, tout doux ?",
            "enfant-f|Oui, papa.",
            "narrateur|La cuillère revient dans le bol.",
            "enfant-f|Le rouge est en haut.",
            "papa|Il brille un peu.",
            "narrateur|Les livres restent droits contre le mur.",
            "narrateur|Le bois des cubes sent encore la forêt.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Ma tour est droite.",
            "papa|Merci, Nina.",
            "narrateur|Le cube rouge reste tout en haut.",
            "narrateur|Le rayon jaune glisse sur le bois.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "s'éloigner",
        "accepted_examples": "s'éloigner | vers papa | adulte | mains loin | colère",
        "retry_prompt": "Nina ouvre les doigts. Puis elle va où ?",
    },
)
relecture(
    "ATOM-EMO.LEX.005-07",
    "La tour de Nina",
    "Nina veut une tour, le rouge en haut. Victorino pose trop vite. "
    "Elle dit sa colère, recule, rejoint papa. À la cuisine, la cuillère part. "
    "Elle recule vers l'évier. La tour se relève.",
    "Second temps : lait et cuillère, vécu. Pas de recap de geste.",
)

# ---------------------------------------------------------------------------
# ATOM-EMO.LEX.008-07  N3  Nino, papa, maman — eau, puzzle
# ---------------------------------------------------------------------------
write_story(
    "ATOM-EMO.LEX.008-07",
    "Nino veut verser l'eau pour la soupe. Le verre penche. "
    "Il dit qu'il est gêné, essuie. Au salon, une pièce tombe. "
    "Il la remet. La soupe fume. Le bleu retrouve le bleu.",
    "L'eau de Nino",
    "Nino, papa, maman",
    "cuisine et salon",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vitre de la cuisine a de la buée.",
            "narrateur|Un doigt y a dessiné une petite goutte.",
            "narrateur|Ça sent la soupe, tout chaud.",
            "narrateur|La bouilloire fait tic, tic, tic.",
            "narrateur|Un torchon humide pend au dossier.",
            "narrateur|La table a un tapis à carreaux.",
            "maman|La soupe est presque prête, Nino.",
            "papa|On met l'eau, tout doucement.",
            "enfant-m|La vitre est floue, papa.",
            "papa|C'est la buée.",
            "maman|Tu portes le petit verre ?",
            "enfant-m|Oui.",
            "enfant-m|Il est froid.",
            "papa|On reste près de la table ?",
            "enfant-m|Oui.",
            "enfant-m|Je veux verser.",
            "narrateur|En ce moment, Nino verse l'eau.",
            "narrateur|Le verre penche.",
            "narrateur|L'eau glisse sur le tapis à carreaux.",
            "narrateur|Une flaque ronde brille.",
            "narrateur|Nino sent ses joues chaudes.",
            "narrateur|Il baisse un peu le menton.",
            "enfant-m|Je suis gêné.",
            "enfant-m|J'ai versé.",
            "papa|Ce n'est pas grave.",
            "maman|Le torchon est là, Nino.",
            "enfant-m|Je veux essuyer.",
            "narrateur|Nino essuie la table.",
            "narrateur|Le torchon devient plus lourd.",
            "narrateur|La flaque disparaît.",
            "maman|La table redevient sèche.",
            "papa|Merci d'avoir dit, Nino.",
            "enfant-m|J'ai essuyé.",
            "papa|Oui.",
            "narrateur|Plus tard, le salon est calme.",
            "narrateur|Un puzzle attend sur le tapis.",
            "narrateur|Une pièce bleue brille.",
            "enfant-m|Je veux le ciel, là.",
            "maman|Elle est un peu rugueuse.",
            "narrateur|Nino s'assoit près du puzzle.",
            "narrateur|Son genou touche une pièce.",
            "narrateur|La pièce tombe sur le tapis.",
            "narrateur|Les joues de Nino chauffent encore.",
            "enfant-m|La pièce est tombée.",
            "papa|On la voit, près de toi.",
            "enfant-m|Je la remets.",
            "narrateur|Nino pose la pièce à sa place.",
            "narrateur|Le bleu retrouve le bleu.",
            "maman|Elle tient, maintenant.",
            "enfant-m|Oui.",
            "papa|La soupe sent encore, tu trouves ?",
            "enfant-m|Oui.",
            "enfant-m|Tout chaud.",
            "narrateur|Le torchon reste un peu lourd.",
            "narrateur|La buée sèche un peu, là-bas.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino a les joues chaudes.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino plie le torchon.",
            "narrateur|Le puzzle est de nouveau entier.",
            "papa|On pose le torchon près de l'évier ?",
            "enfant-m|Oui, papa.",
            "maman|La table est sèche.",
            "maman|Bravo, Nino.",
            "enfant-m|J'ai essuyé.",
            "papa|La pièce bleue aussi est rentrée.",
            "narrateur|Le torchon est plié sur la table.",
            "narrateur|La soupe sent encore, tout doux.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nino touche la pièce bleue.",
            "narrateur|Elle est un peu rugueuse.",
            "maman|On goûte la soupe, tout à l'heure ?",
            "enfant-m|Oui.",
            "enfant-m|Elle sent bon.",
            "papa|Le verre est vide, maintenant.",
            "enfant-m|Je suis moins chaud.",
            "maman|La table est sèche.",
            "narrateur|La buée a presque disparu.",
            "narrateur|Un rond clair est sur la vitre.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|La table est sèche.",
            "papa|Merci, Nino.",
            "narrateur|La pièce bleue reste à sa place.",
            "narrateur|La soupe fume encore, tout doux.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "gêné",
        "accepted_examples": "gêné | je suis gêné | réparer | il répare | une erreur | essuyer",
        "retry_prompt": "Nino a versé. Que dit-il, puis que fait-il ?",
    },
)
relecture(
    "ATOM-EMO.LEX.008-07",
    "L'eau de Nino",
    "Nino veut verser l'eau. Le verre penche. Il dit qu'il est gêné, essuie. "
    "Au salon, une pièce tombe. Il la remet. La soupe fume.",
    "Second temps : pièce bleue, vécu. Pas « même leçon, autre pièce ».",
)

# ---------------------------------------------------------------------------
# ATOM-EMO.LEX.009-03  N3  Chouchou, Nina, papa, maman — crayons, livre
# ---------------------------------------------------------------------------
write_story(
    "ATOM-EMO.LEX.009-03",
    "Chouchou veut colorier aussi. Nina a le crayon jaune. "
    "Chouchou dit qu'elle est jalouse, demande, attend. "
    "Au salon, elle attend le livre. Le nuage est bleu. Le livre s'ouvre vers elle.",
    "Les crayons de Chouchou",
    "Chouchou, Nina, papa, maman",
    "chambre puis salon",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un cahier ouvert dort sur la couette.",
            "narrateur|La page a un grand soleil commencé.",
            "narrateur|Une boîte en métal tient les crayons.",
            "narrateur|Elle fait un petit bruit, si on la touche.",
            "narrateur|Une bande de soleil est sur le mur.",
            "narrateur|Elle est jaune, un peu poussiéreuse.",
            "narrateur|Ça sent le papier neuf.",
            "maman|Je plie les chaussettes, Chouchou.",
            "papa|Nina a déjà le crayon jaune.",
            "enfant-f|La bande est chaude, papa.",
            "papa|Oui.",
            "papa|C'est le soleil du mur.",
            "maman|Le cahier est bien ouvert.",
            "narrateur|En ce moment, Nina colorie.",
            "narrateur|Elle colorie un grand soleil.",
            "narrateur|Chouchou la regarde longtemps.",
            "narrateur|Son ventre se serre.",
            "narrateur|Ses mains restent sur ses genoux.",
            "enfant-f|Je suis jalouse.",
            "papa|Je t'écoute.",
            "papa|Tu veux colorier aussi ?",
            "enfant-f|Oui.",
            "narrateur|Chouchou va près de Nina.",
            "enfant-f|Nina, je peux après toi ?",
            "enfant-f|Encore un peu.",
            "papa|On écoute Nina ?",
            "narrateur|Chouchou attend.",
            "narrateur|Elle compte tout bas.",
            "narrateur|Un.",
            "narrateur|Deux.",
            "narrateur|Trois.",
            "narrateur|Puis Nina tend un crayon.",
            "enfant-f|Le bleu, pour un nuage.",
            "enfant-f|Merci, Nina.",
            "narrateur|Chouchou a le bleu.",
            "narrateur|Elle colorie un nuage.",
            "maman|Le nuage est joli, Chouchou.",
            "enfant-f|Il est pâle, encore.",
            "narrateur|Plus tard, au salon, un livre d'images attend.",
            "narrateur|Papa tient le livre sur ses genoux.",
            "narrateur|Les pages sont épaisses, un peu lisses.",
            "narrateur|Chouchou a encore le ventre serré.",
            "enfant-f|Papa, je voudrais voir aussi.",
            "papa|Encore deux pages.",
            "papa|Tu t'assoies près de moi ?",
            "enfant-f|Oui.",
            "narrateur|Chouchou attend sur le coussin.",
            "narrateur|Ses mains restent sur ses genoux.",
            "narrateur|Le papier des pages sent le bois.",
            "narrateur|Puis papa ouvre le livre vers elle.",
            "papa|C'est pour toi, maintenant.",
            "enfant-f|Un bateau.",
            "maman|Il a une voile blanche.",
            "enfant-f|Je la vois.",
            "narrateur|La bande de soleil a glissé un peu.",
            "narrateur|Le cahier reste ouvert, là-bas.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou veut les crayons.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou reprend le crayon bleu.",
            "narrateur|Le nuage s'épaissit sur la page.",
            "papa|Le jaune de Nina est fini ?",
            "enfant-f|Oui.",
            "enfant-f|Le soleil est grand.",
            "maman|Et ton nuage, aussi.",
            "papa|Bravo, Chouchou.",
            "narrateur|La boîte en métal est refermée.",
            "narrateur|Elle fait encore un petit bruit.",
            "enfant-f|J'ai eu le bleu.",
            "maman|Oui.",
            "narrateur|Le cahier reste ouvert sur la couette.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Chouchou range un crayon.",
            "narrateur|Papa ferme le livre tout doux.",
            "maman|On pose le cahier sur la table ?",
            "enfant-f|Oui, maman.",
            "papa|Merci d'avoir attendu, Chouchou.",
            "enfant-f|Le soleil de la page est fini.",
            "enfant-f|Et mon nuage, aussi.",
            "maman|La voile du bateau est blanche.",
            "papa|On peut éteindre la petite lampe ?",
            "enfant-f|Oui.",
            "narrateur|Chouchou touche la couette.",
            "narrateur|Elle est un peu froissée, toute douce.",
            "narrateur|La bande de soleil a presque disparu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|J'ai colorié le nuage.",
            "papa|Merci, Chouchou.",
            "narrateur|Le livre reste fermé sur les genoux.",
            "narrateur|La boîte de crayons reste calme.",
        ],
    },
    EMPTY,
    q={
        "expected_answer": "demander un tour",
        "accepted_examples": "demander un tour | un tour | jaloux | jalouse | attendre | demander",
        "retry_prompt": "Chouchou est jalouse. Que peut-elle demander ?",
    },
)
relecture(
    "ATOM-EMO.LEX.009-03",
    "Les crayons de Chouchou",
    "Chouchou veut colorier. Nina a le jaune. Chouchou dit qu'elle est jalouse, "
    "demande, attend le bleu. Au salon, elle attend le livre. Le nuage est bleu.",
    "Chouchou = enfant-f. Second temps : livre, vécu. Pas « même leçon ».",
)

# ---------------------------------------------------------------------------
# ATOM-FAM.SEC.001-03  N3  Sarah, papa, maman — dessin, fleur
# ---------------------------------------------------------------------------
write_story(
    "ATOM-FAM.SEC.001-03",
    "Sarah veut un soleil pour l'anniversaire de maman. "
    "Elle le cache sous le livre. Le soir, elle le tend. "
    "Au jardin, une petite fleur attend derrière son dos. Maman la reçoit.",
    "Le dessin et la fleur de Sarah",
    "Sarah, papa, maman",
    "chambre puis jardin",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le parquet de la chambre craque tout bas.",
            "narrateur|Un livre est ouvert sur le lit.",
            "narrateur|Les pages sentent le papier tiède.",
            "narrateur|Un signet rouge dépasse un peu.",
            "narrateur|Par la fenêtre, le jardin est vert.",
            "narrateur|Une abeille passe, tout loin.",
            "narrateur|Papa s'assoit par terre, près de Sarah.",
            "papa|Les crayons sentent le bois, tu trouves ?",
            "enfant-f|Oui, le bois.",
            "maman|J'arrive dans un instant.",
            "narrateur|Maman plie le linge, plus loin.",
            "papa|Bientôt, c'est l'anniversaire de maman.",
            "enfant-f|Je veux un soleil pour elle.",
            "papa|Un grand soleil, alors.",
            "narrateur|En ce moment, Sarah prend un crayon orange.",
            "narrateur|Le soleil devient grand, tout rond.",
            "narrateur|Des rayons remplissent la feuille.",
            "papa|Un rayon plus long, ici.",
            "enfant-f|Et un petit, là.",
            "enfant-f|Il est pour maman.",
            "papa|On le cache sous le livre ?",
            "enfant-f|Oui.",
            "enfant-f|Pour tout à l'heure.",
            "narrateur|Sarah glisse le dessin sous le livre.",
            "narrateur|Le livre est lourd, un peu froid.",
            "narrateur|Maman entre.",
            "maman|Ça sent les crayons ici.",
            "enfant-f|Je garde encore un peu.",
            "papa|Encore un tout petit peu ?",
            "enfant-f|Oui.",
            "narrateur|Sarah serre les lèvres.",
            "narrateur|Le signet rouge dépasse toujours.",
            "narrateur|Le soir, la table est prête.",
            "narrateur|Le dessin est là, près de l'assiette.",
            "papa|C'est le moment, Sarah ?",
            "enfant-f|Maman, surprise.",
            "enfant-f|C'est pour toi.",
            "narrateur|Maman ouvre les yeux, tout grands.",
            "maman|Un soleil.",
            "maman|Merci, Sarah.",
            "enfant-f|Il a un petit rayon, là.",
            "maman|Je le vois.",
            "narrateur|Plus tard, au jardin, l'herbe est tiède.",
            "narrateur|Un oiseau picore près du cerisier.",
            "narrateur|Papa coupe une petite fleur.",
            "narrateur|La tige est verte, un peu humide.",
            "enfant-f|Pour maman, encore ?",
            "papa|Si tu veux.",
            "papa|Tu la tiens derrière toi ?",
            "enfant-f|Oui.",
            "narrateur|Sarah tient la fleur derrière son dos.",
            "narrateur|Une goutte glisse sur son doigt.",
            "narrateur|Maman arrive près du cerisier.",
            "enfant-f|Maman, c'est pour toi.",
            "narrateur|Sarah tend la fleur.",
            "maman|Une fleur.",
            "maman|Merci, ma grande.",
            "papa|Elle sent bon, tu trouves ?",
            "enfant-f|Un peu sucré.",
            "narrateur|Le cerisier bouge un peu.",
            "narrateur|L'abeille n'est plus là.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le dessin pour maman, c'est quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Maman pose la fleur dans un verre.",
            "narrateur|L'eau fait un tout petit bruit.",
            "papa|Le soleil reste près de l'assiette ?",
            "enfant-f|Oui.",
            "maman|Deux cadeaux.",
            "maman|Bravo, Sarah.",
            "enfant-f|Le dessin, puis la fleur.",
            "papa|Oui.",
            "narrateur|Le cerisier bouge un peu.",
            "narrateur|Une feuille tombe dans l'herbe.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sarah range un crayon.",
            "narrateur|Le parquet craque encore.",
            "papa|Le jardin sent l'herbe.",
            "enfant-f|Et la fleur sent bon.",
            "maman|Oui, un peu sucré.",
            "papa|On rentre, tout doux ?",
            "enfant-f|Oui.",
            "enfant-f|Le signet est encore rouge.",
            "maman|La fleur nous suit.",
            "narrateur|Le livre est refermé sur le lit.",
            "narrateur|Le verre tremble un peu, dans la main de maman.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le soleil est pour toi.",
            "maman|Merci, Sarah.",
            "narrateur|La fleur tient dans le verre.",
            "narrateur|L'eau est claire, tout calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "jardin",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "surprise",
        "accepted_examples": "surprise | une surprise | surprise gentille | un dessin",
        "retry_prompt": "Sarah cache le dessin. C'est quoi, pour maman ?",
    },
)
relecture(
    "ATOM-FAM.SEC.001-03",
    "Le dessin et la fleur de Sarah",
    "Sarah veut un soleil pour maman. Elle le cache sous le livre, le tend le soir. "
    "Au jardin, une fleur attend derrière son dos. Maman la reçoit.",
    "Second temps : fleur au cerisier, vécu. Pas « même leçon, autre moment ».",
)
