#!/usr/bin/env python3
"""avis2 — ATOM-EMO.LEX.001-05 et ATOM-FAM.AID.001-01, sans récap pédagogique."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story  # noqa: E402

L = lambda *rows: list(rows)


def sarah() -> None:
    write_story(
        "ATOM-EMO.LEX.001-05",
        "Sarah dessine la maison pour maman, qui n'est pas rentrée. Le crayon jaune casse. Elle attend, puis montre.",
        "Sarah et le dessin du soleil",
        "Sarah, papa, maman",
        "salon, fin d'après-midi",
        {
            "CHK_T0000_P0000": L(
                "narrateur|Un rayon traverse la poussière du salon.",
                "narrateur|Les crayons dorment dans leur boîte en fer.",
                "narrateur|La boîte est froide, un peu cabossée.",
                "narrateur|Le tapis sent la laine.",
                "narrateur|Un coussin a glissé sous la table.",
                "narrateur|La pendule fait tic, tout bas.",
                "narrateur|Papa coud un bouton près de la fenêtre.",
                "narrateur|Maman n'est pas encore rentrée.",
                "narrateur|Dehors, un vélo passe, très loin.",
                "papa|Sarah, tu as choisi une feuille ?",
                "enfant-f|La grande, blanche.",
                "enfant-f|C'est pour maman.",
                "papa|Elle va rentrer bientôt.",
                "narrateur|En ce moment, Sarah s'assoit au bas du canapé.",
                "narrateur|Elle pose la feuille sur le tapis.",
                "narrateur|Le crayon jaune fait un bruit sec.",
                "narrateur|Un soleil rond, puis des rayons.",
                "narrateur|Une petite maison, une porte, deux fenêtres.",
                "narrateur|Le crayon jaune casse, net.",
                "enfant-f|Oh.",
                "papa|Il en reste un bout.",
                "narrateur|Sarah souffle la mine tombée sur le tapis.",
                "narrateur|Elle finit le toit avec le bout.",
                "narrateur|Un rayon manque encore, tout petit.",
                "enfant-f|Maman va voir le trou ?",
                "papa|Elle verra la maison, d'abord.",
                "narrateur|Sarah pose le bout de crayon.",
                "narrateur|La porte d'entrée clique.",
                "narrateur|Maman pose son sac.",
                "maman|Je rentre.",
                "maman|Ça sent les crayons.",
                "enfant-f|Attends.",
                "narrateur|Sarah attend que maman s'assoie.",
                "narrateur|Ses joues sont chaudes.",
                "narrateur|Elle tend la feuille, sans bousculer.",
                "enfant-f|C'est notre maison.",
                "enfant-f|Je suis contente.",
                "maman|Merci, Sarah.",
                "papa|Le soleil est très jaune.",
                "maman|On le met où ?",
            ),
            "CHK_T0000_P0000_Q0001": L(
                "narrateur|Sarah sourit, la feuille encore chaude.",
                "maman|Que dit-elle ?",
            ),
            "CHK_T0000_P0000_C0001": L(
                "narrateur|Maman tient la feuille par les bords.",
                "narrateur|Elle ne plie pas le soleil.",
                "enfant-f|Le vrai soleil est à la fenêtre.",
                "maman|On va le voir ensemble ?",
                "narrateur|Ils se lèvent.",
                "narrateur|Le sac de maman reste près de la porte.",
                "papa|J'apporte la pince à linge ?",
                "enfant-f|Oui.",
                "narrateur|Papa prend une pince sur le radiateur.",
                "narrateur|La pince est un peu tiède.",
                "enfant-f|Comme le rayon.",
            ),
            "CHK_T0000_P0000_END": L(
                "narrateur|Ils collent le dessin contre la vitre.",
                "narrateur|La pince tient le coin.",
                "narrateur|Dehors, le vrai soleil est plus pâle.",
                "enfant-f|Le mien est plus rond.",
                "maman|Le tien attendait, sur le tapis.",
                "papa|Le crayon cassé reste dans la boîte.",
                "narrateur|Sarah range les autres crayons, un par un.",
                "narrateur|Le jaune cassé rentre le dernier.",
                "narrateur|La boîte fait un petit clac.",
                "papa|On laisse le dessin pour la nuit ?",
                "enfant-f|Oui.",
                "enfant-f|Il garde la fenêtre.",
            ),
            "CHK_T0000_P0000_END_F0001": L(
                "narrateur|Le rayon a bougé sur le tapis.",
                "narrateur|Sur la vitre, la maison reste.",
                "enfant-f|Maman l'a vue.",
                "maman|Je la verrai encore demain.",
                "narrateur|Le sac de maman sent encore le dehors.",
                "narrateur|Ils restent au salon, tout près.",
            ),
        },
        {
            "CHK_T0000_P0000": "crayon",
            "CHK_T0000_P0000_Q0001": "",
            "CHK_T0000_P0000_C0001": "",
            "CHK_T0000_P0000_END": "clic",
            "CHK_T0000_P0000_END_F0001": "",
        },
        q={
            "expected_answer": "contente",
            "accepted_examples": "contente | je suis contente | joie",
            "retry_prompt": "Sarah sourit. Que dit-elle ?",
        },
    )
    relecture(
        "ATOM-EMO.LEX.001-05",
        "Sarah et le dessin du soleil",
        "crayon cassé, attente de maman, dessin à la vitre",
        "avis2 : plus de récap joie/bravo. Audio non cuit.",
    )


def chouchou() -> None:
    write_story(
        "ATOM-FAM.AID.001-01",
        "Chouchou veut le bateau du puzzle. La boîte est trop haute. Elle va vers papa. Ensemble ils finissent le bateau.",
        "La boîte trop haute",
        "Chouchou, papa, maman",
        "chambre, puis tapis",
        {
            "CHK_T0000_P0000": L(
                "narrateur|Le doudou attend sur l'oreiller.",
                "narrateur|Il a une oreille un peu pliée.",
                "narrateur|Un rayon traverse la chambre.",
                "narrateur|Des poussières brillent dans le rayon.",
                "narrateur|Sur l'étagère, une boîte colorée.",
                "narrateur|Dedans, il y a le bateau du puzzle.",
                "maman|Je suis dans la cuisine, Chouchou.",
                "maman|Ça sent la soupe, déjà.",
                "papa|Moi, je suis dans le salon.",
                "enfant-f|Le doudou attend le bateau.",
                "narrateur|En ce moment, Chouchou veut le puzzle.",
                "narrateur|Elle lève les yeux.",
                "narrateur|La boîte est en haut.",
                "narrateur|Trop haut.",
                "enfant-f|Je n'arrive pas.",
                "narrateur|Elle baisse les bras.",
                "narrateur|Elle va vers la porte.",
                "narrateur|Elle va vers papa.",
                "enfant-f|Papa.",
                "enfant-f|La boîte est trop haute.",
                "papa|Je t'écoute, Chouchou.",
                "papa|Le bateau du puzzle, c'est ça ?",
                "enfant-f|Oui.",
                "narrateur|Papa se lève.",
                "narrateur|Il prend la boîte, tout doux.",
                "narrateur|Elle est lourde.",
                "enfant-f|Merci, papa.",
                "papa|Merci d'être venue me voir.",
                "narrateur|Ils reviennent près du tapis.",
                "narrateur|Le doudou garde l'oreiller.",
                "papa|Tu ouvres, tout doux ?",
                "enfant-f|Oui.",
                "narrateur|Une pièce rouge.",
                "narrateur|Une pièce bleue.",
                "narrateur|Un coin de voile blanche.",
                "narrateur|Une pièce sent le carton.",
                "enfant-f|Celle-ci, c'est la coque.",
                "papa|Et ça, la petite cheminée ?",
                "enfant-f|Oui.",
                "maman|La soupe attend encore un peu.",
                "papa|On finit le bateau, d'abord ?",
            ),
            "CHK_T0000_P0000_Q0001": L(
                "narrateur|La boîte est trop haute.",
                "maman|Que fait Chouchou ?",
            ),
            "CHK_T0000_P0000_C0001": L(
                "narrateur|Chouchou s'assoit près du tapis.",
                "narrateur|Papa s'assoit aussi.",
                "enfant-f|La rouge, d'abord.",
                "narrateur|La pièce clique sur le carton.",
                "narrateur|Une autre pièce manque encore.",
                "enfant-f|Elle est sous la boîte.",
                "papa|Tu la prends ?",
                "narrateur|Chouchou glisse la main dessous.",
                "narrateur|La pièce bleue revient.",
                "papa|Et la voile ?",
                "enfant-f|Elle est un peu pliée.",
                "papa|On la lisse du doigt ?",
                "narrateur|Chouchou lisse le papier.",
                "narrateur|La voile se tient.",
            ),
            "CHK_T0000_P0000_END": L(
                "narrateur|Le bateau a une coque rouge.",
                "narrateur|La voile est blanche, un peu froissée.",
                "enfant-f|Il peut partir.",
                "papa|Souffle, tout doux.",
                "narrateur|Chouchou souffle.",
                "narrateur|La voile bouge.",
                "enfant-f|Il avance.",
                "papa|Jusqu'à l'oreiller ?",
                "enfant-f|Jusqu'au doudou.",
                "narrateur|Le bateau s'arrête contre le doudou.",
                "maman|Je vous entends, depuis la cuisine.",
                "narrateur|Le doudou a l'oreille moins pliée.",
            ),
            "CHK_T0000_P0000_END_F0001": L(
                "narrateur|Le bateau reste sur le tapis.",
                "narrateur|La boîte est vide, à côté.",
                "enfant-f|Le doudou a vu le voyage.",
                "papa|On range les pièces plus tard.",
                "maman|La soupe est prête, maintenant.",
                "narrateur|Le rayon a bougé sur l'oreiller.",
                "enfant-f|Le bateau attend encore.",
                "papa|On le laisse pour ce soir.",
                "narrateur|La boîte reste ouverte, tout près.",
                "narrateur|Ça sent encore la soupe, dans l'escalier.",
            ),
        },
        {
            "CHK_T0000_P0000": "boite",
            "CHK_T0000_P0000_Q0001": "",
            "CHK_T0000_P0000_C0001": "piece",
            "CHK_T0000_P0000_END": "",
            "CHK_T0000_P0000_END_F0001": "",
        },
        q={
            "expected_answer": "papa",
            "accepted_examples": "papa | maman | appeler | elle va vers papa | dire",
            "retry_prompt": "La boîte est trop haute. Que fait Chouchou ?",
        },
    )
    relecture(
        "ATOM-FAM.AID.001-01",
        "La boîte trop haute",
        "boîte trop haute, papa, bateau fini, voile qui bouge",
        "avis2 : plus de j'ai dit le besoin / bravo. Chouchou = enfant-f. Audio non cuit.",
    )


if __name__ == "__main__":
    sarah()
    chouchou()
    print("ok avis2 atom")
