#!/usr/bin/env python3
"""F-NAR-008 — ATOM-SEC.RUE.003-07/08 + ATOM-SOC.ARG.001-01..06."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-07 N1 — Nina, maman, rue du village sous la pluie fine
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|La gouttière de zinc fait tic tic.",
        "narrateur|La pluie fine mouille les toits.",
        "narrateur|Les pavés brillent, tout gris.",
        "narrateur|Ça sent la laine mouillée.",
        "narrateur|Un capuchon jaune attend au crochet.",
        "narrateur|Le manteau de maman est épais.",
        "narrateur|Nina vit ici, avec maman.",
        "enfant-f|Maman, le zinc chante !",
        "maman|Oui.",
        "maman|La pharmacie est ouverte.",
        "maman|Tu as vu le savon dans la vitre ?",
        "enfant-f|Le rond, qui sent le miel.",
        "maman|On y va ensemble ?",
        "enfant-f|Oui.",
        "narrateur|En ce moment, Nina prend le capuchon.",
        "narrateur|Le tissu est un peu rêche.",
        "narrateur|Elle enfile les bottes jaunes.",
        "narrateur|Les gouttes tapent déjà dehors.",
        "maman|Tu tiens le manteau, Nina ?",
        "enfant-f|Oui, maman.",
        "narrateur|Nina prend la manche épaisse.",
        "narrateur|Le tissu est chaud, un peu humide.",
        "maman|Près de moi.",
        "maman|Main ou manteau.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air sent le zinc et la pluie.",
        "narrateur|Elles marchent sur les pavés.",
        "narrateur|Nina reste près de l'adulte.",
        "narrateur|Ses pieds collent à ceux de maman.",
        "enfant-f|Les pavés brillent !",
        "maman|Oui.",
        "maman|On reste tout près.",
        "narrateur|Une flaque ronde barre le passage.",
        "narrateur|L'eau tremble, toute grise.",
        "enfant-f|Elle est grande.",
        "maman|On la contourne ensemble.",
        "narrateur|Nina serre la manche.",
        "narrateur|La manche glisse un peu.",
        "narrateur|Le tissu est trop mouillé.",
        "enfant-f|Ça glisse !",
        "maman|Prends ma main, alors.",
        "narrateur|Nina prend la main de maman.",
        "narrateur|La main est chaude, un peu rêche.",
        "narrateur|Elles passent la flaque, tout près.",
        "maman|Tes pieds sont à côté ?",
        "enfant-f|Oui.",
        "narrateur|La croix verte clignote au loin.",
        "narrateur|Ça sent déjà le savon, tout doux.",
        "enfant-f|Le savon rond !",
        "maman|Bientôt.",
        "maman|On reste près de l'adulte.",
        "narrateur|Un pigeon secoue ses plumes.",
        "narrateur|Nina lève les yeux, tout court.",
        "narrateur|Elle garde la main.",
        "maman|Tu as vu le pigeon ?",
        "enfant-f|Oui.",
        "narrateur|La vitre de la pharmacie arrive.",
        "narrateur|Le savon rond brille derrière.",
        "narrateur|Il est jaune, comme le miel.",
        "enfant-f|Je le veux.",
        "maman|On entre ensemble.",
        "narrateur|La porte est lourde, un peu collante.",
        "narrateur|Nina reste collée au manteau.",
        "narrateur|Elles poussent la porte, tout près.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nina marche dans la rue.",
        "narrateur|Où est-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Nina est près de maman.",
        "narrateur|La main tient encore maman.",
        "narrateur|Les pieds restent à côté.",
        "maman|Tu es près de moi ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Main ou manteau.",
        "maman|Bravo, Nina.",
        "narrateur|La clochette de la porte tinte.",
        "narrateur|Ça sent le savon et le papier.",
        "narrateur|Le savon rond est sur une tablette.",
        "enfant-f|Il est tout jaune !",
        "maman|Oui.",
        "maman|On le prend ensemble.",
        "narrateur|Maman tend le savon à Nina.",
        "narrateur|Nina le sent, tout près.",
        "enfant-f|Ça sent le miel !",
        "maman|Oui.",
        "narrateur|Le papier craque autour du savon.",
        "narrateur|Nina serre le paquet contre elle.",
        "narrateur|Elle reste près de l'adulte.",
        "maman|On ressort ?",
        "enfant-f|Oui.",
        "narrateur|Nina reprend la manche du manteau.",
        "narrateur|Le tissu est encore un peu mouillé.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Elles ressortent sous la pluie fine.",
        "narrateur|Les pavés brillent toujours.",
        "maman|Près de moi.",
        "narrateur|Nina marche à côté.",
        "narrateur|Le paquet sent le miel, tout fort.",
        "narrateur|La flaque est encore là.",
        "maman|On la contourne encore ?",
        "enfant-f|Oui.",
        "narrateur|Nina serre la manche.",
        "narrateur|Cette fois, ça ne glisse pas.",
        "maman|Tu tiens bien.",
        "maman|Merci, Nina.",
        "narrateur|Le zinc chante encore sur le toit.",
        "narrateur|La porte de la maison arrive.",
        "narrateur|Le paillasson est tout mouillé.",
        "enfant-f|On est rentrées !",
        "maman|Oui.",
        "narrateur|Nina pose le savon sur la table.",
        "narrateur|Une goutte tombe du capuchon.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|J'ai tenu le manteau.",
        "enfant-f|J'ai le savon de miel.",
        "maman|Bravo, Nina.",
        "narrateur|Le savon sent encore le miel.",
        "narrateur|Le capuchon sent encore la pluie.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-08 N1 — Victorina, maman, ruelle aux volets bleus
# ---------------------------------------------------------------------------
S08 = {
    "CHK_T0000_P0000": [
        "narrateur|Les volets bleus claquent tout doux.",
        "narrateur|La peinture s'écaille un peu.",
        "narrateur|La ruelle sent le linge au soleil.",
        "narrateur|Un chat gris dort sur une marche.",
        "narrateur|Le manteau de maman est bleu aussi.",
        "narrateur|Un sac de toile pend au bras.",
        "narrateur|Victorina vit ici, avec maman.",
        "enfant-f|Maman, les volets sont bleus !",
        "maman|Oui.",
        "maman|Le four du boulanger est allumé.",
        "maman|Tu as vu le sac chaud, hier ?",
        "enfant-f|Les brioches ?",
        "maman|Oui.",
        "enfant-f|Je les veux.",
        "maman|On y va ensemble ?",
        "enfant-f|Oui.",
        "narrateur|En ce moment, Victorina prend le manteau.",
        "narrateur|Le tissu est doux, un peu rêche.",
        "maman|Main ou manteau.",
        "maman|Près de moi.",
        "narrateur|Maman ferme la porte.",
        "narrateur|La ruelle est étroite, toute calme.",
        "narrateur|Victorina reste près de l'adulte.",
        "narrateur|Ses pieds collent à ceux de maman.",
        "narrateur|Le chat ouvre un œil.",
        "enfant-f|Il dort encore.",
        "maman|On le laisse.",
        "narrateur|Un volet claque plus fort.",
        "narrateur|Le bleu tremble au vent.",
        "enfant-f|Ça a fait peur !",
        "maman|Je suis là, tout près.",
        "narrateur|Victorina serre la manche.",
        "narrateur|La manche est chaude.",
        "maman|Tes pieds sont à côté ?",
        "enfant-f|Oui, maman.",
        "narrateur|Elles avancent entre les murs.",
        "narrateur|Ça sent déjà le beurre chaud.",
        "narrateur|Une bille rouge brille au sol.",
        "enfant-f|Une bille !",
        "maman|On reste près.",
        "maman|On la prend ensemble.",
        "narrateur|Maman se baisse, tout doux.",
        "narrateur|Victorina se baisse aussi, collée.",
        "narrateur|La bille est lisse, un peu froide.",
        "enfant-f|Elle est rouge.",
        "maman|Oui.",
        "maman|Dans le sac, avec nous.",
        "narrateur|Victorina reprend la manche.",
        "narrateur|Elles restent près de l'adulte.",
        "narrateur|La maison aux volets bleus arrive.",
        "narrateur|Le four sent le beurre, tout fort.",
        "enfant-f|Les brioches !",
        "maman|On sonne ensemble.",
        "narrateur|Victorina reste collée au manteau.",
        "narrateur|La cloche de la porte tinte.",
        "narrateur|Un sac chaud passe dans les mains.",
        "enfant-f|Il est chaud !",
        "maman|Oui.",
        "maman|On rentre près de moi.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Victorina marche dans la ruelle.",
        "narrateur|Où est-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Victorina est près de maman.",
        "narrateur|La main tient le manteau bleu.",
        "narrateur|Les pieds restent à côté.",
        "maman|Tu es près de moi ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Main ou manteau.",
        "maman|Bravo, Victorina.",
        "narrateur|Le sac de toile est tout tiède.",
        "narrateur|Ça sent le beurre et le sucre.",
        "narrateur|La bille rouge roule dans le sac.",
        "enfant-f|Elle fait du bruit.",
        "maman|Oui.",
        "maman|On rentre ensemble.",
        "narrateur|Le chat est encore sur la marche.",
        "narrateur|Victorina le regarde, tout près.",
        "narrateur|Elle garde la manche.",
        "maman|Tu tiens bien le manteau ?",
        "enfant-f|Oui.",
        "narrateur|Un autre volet claque, plus loin.",
        "narrateur|Victorina serre plus fort.",
        "maman|Près de moi.",
        "narrateur|Elles passent le chat, tout doux.",
        "narrateur|La porte de la maison arrive.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air de la maison est tiède.",
        "maman|Tu poses le sac ?",
        "enfant-f|Oui.",
        "narrateur|Victorina pose le sac sur la table.",
        "narrateur|Le papier craque, tout chaud.",
        "narrateur|Deux brioches sentent le beurre.",
        "enfant-f|Elles sont dorées !",
        "maman|Oui.",
        "maman|Merci d'avoir tenu le manteau.",
        "narrateur|La bille rouge sort du sac.",
        "narrateur|Elle brille près du pain.",
        "enfant-f|On l'a prise ensemble.",
        "maman|Oui.",
        "maman|Dans la ruelle, près de moi.",
        "narrateur|Le manteau bleu sèche un peu.",
        "narrateur|La peinture des volets reste dehors.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|J'ai tenu le manteau.",
        "enfant-f|Les brioches sont chaudes.",
        "maman|Bravo, Victorina.",
        "narrateur|Le beurre sent encore le sac.",
        "narrateur|Une brioche chauffe sa main."
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-01 N2 — Mila, papa, marché, petit pain chaud
# ---------------------------------------------------------------------------
A01 = {
    "CHK_T0000_P0000": [
        "narrateur|La bâche du marché sent la farine chaude.",
        "narrateur|Un pigeon picore une miette grise.",
        "narrateur|Les caisses de bois sont encore humides.",
        "narrateur|Ça sent le beurre et le café.",
        "narrateur|Papa range une pièce dans sa poche.",
        "narrateur|Mila vit ici, avec papa.",
        "enfant-f|Papa, ça sent le four !",
        "papa|Oui.",
        "papa|Le stand du pain est ouvert.",
        "enfant-f|Je veux un petit pain chaud.",
        "papa|Le rond, bien doré ?",
        "enfant-f|Oui.",
        "narrateur|En ce moment, Mila tient le cabas.",
        "narrateur|Le tissu râpe un peu ses doigts.",
        "narrateur|Elles avancent sous la bâche.",
        "narrateur|La vitrine du stand est pleine.",
        "narrateur|Des petits pains dorés alignés.",
        "enfant-f|Celui-là, le bien doré !",
        "papa|Tu le montres du doigt ?",
        "enfant-f|Oui.",
        "narrateur|Mila montre le petit pain du milieu.",
        "narrateur|Il brille encore un peu.",
        "narrateur|Une main le prend, plus loin.",
        "narrateur|Le pain part dans un autre sac.",
        "enfant-f|Il n'est plus là.",
        "papa|Il est déjà vendu.",
        "papa|On en prend un autre ?",
        "enfant-f|Encore chaud ?",
        "papa|Oui.",
        "narrateur|Papa montre un pain tout près.",
        "narrateur|La croûte est plus claire, encore tiède.",
        "enfant-f|Celui-là.",
        "papa|J'ai une pièce, dans la poche.",
        "papa|Elle sert à prendre le pain.",
        "narrateur|Papa tend la pièce.",
        "narrateur|La pièce sonne dans le tiroir.",
        "narrateur|Le tiroir se ferme, tout court.",
        "narrateur|Le petit pain passe dans le cabas.",
        "enfant-f|Il est chaud !",
        "papa|Oui.",
        "papa|Tu le tiens ?",
        "enfant-f|Oui, papa.",
        "narrateur|Mila pose les deux mains autour.",
        "narrateur|La croûte pique un peu les paumes.",
        "narrateur|Ça sent le four, tout près.",
        "papa|Tu as fini de le sentir ?",
        "enfant-f|Presque.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Papa a donné une pièce.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le petit pain est dans les mains de Mila.",
        "narrateur|Il chauffe encore les doigts.",
        "papa|La pièce a servi à le prendre.",
        "enfant-f|Pour le pain chaud.",
        "papa|Oui.",
        "papa|On achète le pain avec ça.",
        "narrateur|Une graine tombe sur le cabas.",
        "narrateur|Mila la pose sur la croûte.",
        "enfant-f|Elle est restée.",
        "papa|Oui.",
        "papa|Tu as choisi l'autre pain.",
        "papa|Bravo, Mila.",
        "narrateur|Le pigeon n'a plus de miette.",
        "narrateur|La bâche claque un peu au vent.",
        "narrateur|Le cabas sent le four, tout fort.",
        "papa|On rentre ?",
        "enfant-f|Oui.",
        "narrateur|Mila garde le pain contre elle.",
        "narrateur|La croûte fait un petit bruit.",
        "papa|Il est encore chaud, non ?",
        "enfant-f|Oui, papa.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La porte de la maison claque doucement.",
        "narrateur|La table de bois est froide.",
        "papa|Tu poses le pain ?",
        "enfant-f|Oui.",
        "narrateur|Mila pose le petit pain au milieu.",
        "narrateur|Une petite vapeur monte encore.",
        "enfant-f|Il fume !",
        "papa|Oui.",
        "papa|Merci d'avoir tenu le cabas.",
        "narrateur|Papa coupe le pain en deux.",
        "narrateur|La mie est blanche, toute douce.",
        "enfant-f|Je goûte ?",
        "papa|Un morceau, tout petit.",
        "narrateur|Mila croque un coin.",
        "narrateur|Ça croustille, puis c'est tiède.",
        "enfant-f|C'est bon.",
        "papa|Le four était encore allumé.",
        "narrateur|La graine reste collée à sa lèvre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Le premier était vendu.",
        "enfant-f|On a pris l'autre, chaud.",
        "papa|Bravo, Mila.",
        "narrateur|La mie sent encore le four.",
        "narrateur|Le petit pain chauffe encore sa main.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-02 N3 — Sarah, maman, papa — halles, fromage + fruit
# ---------------------------------------------------------------------------
A02 = {
    "CHK_T0000_P0000": [
        "narrateur|La sciure du sol colle aux semelles.",
        "narrateur|Les piliers de fer sont froids, un peu verts.",
        "narrateur|Ça sent le lait et les pommes, sous les halles.",
        "narrateur|Un rayon tombe entre deux toiles.",
        "narrateur|Papa porte un cabas de toile rêche.",
        "narrateur|Maman range deux pièces dans sa poche.",
        "narrateur|Sarah vit ici, avec maman et papa.",
        "enfant-f|Le sol fait un bruit de bois !",
        "maman|C'est la sciure.",
        "papa|Tu as vu le stand du fromage ?",
        "enfant-f|Il est blanc, tout rond.",
        "enfant-f|Je veux un morceau.",
        "maman|On y va.",
        "narrateur|En ce moment, Sarah marche dans la sciure.",
        "narrateur|Les copeaux collent à sa chaussure.",
        "narrateur|Le stand du fromage est bas, en bois.",
        "narrateur|Un gros fromage blanc attend sous une cloche.",
        "enfant-f|Celui-là, le gros.",
        "papa|Il est trop grand pour nous.",
        "maman|On prend un petit morceau ?",
        "enfant-f|Oui.",
        "narrateur|Maman sort une pièce de la poche.",
        "narrateur|La pièce brille un instant.",
        "maman|Ça sert à prendre le fromage.",
        "narrateur|La pièce tombe dans une boîte en fer.",
        "narrateur|Ça sonne, tout court.",
        "narrateur|Un petit triangle de fromage arrive.",
        "narrateur|Il est enveloppé dans un papier huilé.",
        "enfant-f|Il sent le lait !",
        "papa|Oui.",
        "papa|Tu le poses dans le cabas ?",
        "enfant-f|Oui, papa.",
        "narrateur|Sarah pose le papier, tout doux.",
        "narrateur|Le cabas devient un peu lourd.",
        "enfant-f|Je veux aussi un fruit.",
        "maman|Plus loin, les poires.",
        "narrateur|Elles avancent entre les piliers.",
        "narrateur|La sciure marque leurs pas.",
        "narrateur|Les poires sont jaunes, un peu tachetées.",
        "enfant-f|Celle-là, la brillante.",
        "narrateur|Sarah montre une poire du doigt.",
        "narrateur|La poire roule, tout d'un coup.",
        "narrateur|Elle part dans la sciure.",
        "enfant-f|Elle est partie !",
        "papa|On la ramasse ensemble.",
        "narrateur|Sarah se baisse près de papa.",
        "narrateur|La poire a un peu de sciure dessus.",
        "enfant-f|Elle est encore belle.",
        "maman|On en prend une autre, propre.",
        "papa|J'ai encore une pièce.",
        "narrateur|Papa tend la pièce.",
        "narrateur|Le tiroir du fruitier sonne.",
        "narrateur|Une poire propre passe dans le cabas.",
        "enfant-f|Elle est lourde.",
        "maman|Oui.",
        "maman|La pièce a servi à la prendre.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Maman et papa ont donné des pièces.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le cabas tient le fromage et la poire.",
        "narrateur|Le papier huilé sent encore le lait.",
        "maman|Les pièces ont servi à les prendre.",
        "enfant-f|Le fromage, puis le fruit.",
        "papa|Oui.",
        "papa|On achète avec ça.",
        "narrateur|Sarah essuie un copeau de sciure.",
        "narrateur|Il était collé à la semelle.",
        "enfant-f|Le sol était tout jaune.",
        "maman|C'est les halles.",
        "maman|Bravo, Sarah.",
        "narrateur|Le pilier de fer reste froid.",
        "narrateur|Un rayon glisse encore sur la toile.",
        "papa|Tu as fini de porter le cabas ?",
        "enfant-f|Il est un peu lourd.",
        "maman|On le porte à deux.",
        "narrateur|Sarah tient une anse.",
        "narrateur|Papa tient l'autre.",
        "narrateur|La poire roule un peu, puis s'arrête.",
        "enfant-f|Elle reste.",
        "papa|Oui.",
        "maman|On rentre ?",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La table de la cuisine est claire.",
        "narrateur|Sarah pose le papier huilé.",
        "narrateur|Le fromage est blanc, un peu gras.",
        "papa|Tu poses la poire à côté ?",
        "enfant-f|Oui.",
        "narrateur|La poire a une tache dorée.",
        "enfant-f|On goûte le fromage ?",
        "maman|Un tout petit bout.",
        "narrateur|Sarah goûte.",
        "narrateur|C'est doux, un peu salé.",
        "enfant-f|C'est bon.",
        "papa|Merci d'avoir ramassé la poire.",
        "narrateur|Maman coupe la poire en quartiers.",
        "narrateur|Le jus brille sur la planche.",
        "enfant-f|Elle sent le sucre.",
        "maman|Oui.",
        "narrateur|Un copeau de sciure tombe du cabas.",
        "narrateur|Sarah le pose près de la fenêtre.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|On a le fromage.",
        "enfant-f|On a la poire aussi.",
        "maman|Bravo, Sarah.",
        "papa|Deux choses, sous les halles.",
        "narrateur|La poire sent le sucre, tout près.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-03 N2 — Amir, papa, poissonnier du port, citron
# ---------------------------------------------------------------------------
A03 = {
    "CHK_T0000_P0000": [
        "narrateur|Les caisses de glace sentent le sel.",
        "narrateur|Un goéland crie au-dessus du quai.",
        "narrateur|L'eau du port claque contre la pierre.",
        "narrateur|Ça sent le poisson et le citron, déjà.",
        "narrateur|Papa porte un sac de toile rêche.",
        "narrateur|Amir vit ici, avec papa.",
        "enfant-m|Papa, le goéland crie fort !",
        "papa|Oui.",
        "papa|Le poissonnier est ouvert.",
        "enfant-m|Je veux un citron, pour le poisson.",
        "papa|Le jaune, bien rond ?",
        "enfant-m|Oui.",
        "narrateur|En ce moment, Amir tient le bord du sac.",
        "narrateur|La glace brille dans les caisses.",
        "narrateur|Un poisson argenté attend sur le zinc.",
        "papa|Celui-là, pour ce soir.",
        "narrateur|Papa montre le poisson du doigt.",
        "narrateur|Le poissonnier le glisse dans un papier.",
        "enfant-m|Il est mouillé.",
        "papa|Oui.",
        "papa|Il lui faut un citron.",
        "narrateur|Un tas de citrons jaunes attend.",
        "narrateur|Amir en montre un, bien rond.",
        "narrateur|Le citron glisse sur la glace.",
        "narrateur|Il roule vers le bord du zinc.",
        "enfant-m|Il part !",
        "papa|Tu peux le rattraper, tout doux.",
        "narrateur|Amir tend la main.",
        "narrateur|Le citron est froid, un peu mouillé.",
        "enfant-m|Je l'ai.",
        "papa|Bravo, Amir.",
        "papa|J'ai une pièce, pour le prendre.",
        "narrateur|Papa tend la pièce.",
        "narrateur|La pièce sonne dans le tiroir mouillé.",
        "narrateur|Le tiroir se ferme.",
        "narrateur|Le citron reste dans la main d'Amir.",
        "enfant-m|Il pique un peu.",
        "papa|C'est le zeste.",
        "papa|Tu le poses dans le sac ?",
        "enfant-m|Avec le poisson.",
        "narrateur|Amir pose le citron près du papier.",
        "narrateur|Ça sent le sel et le jaune, ensemble.",
        "papa|Tu as fini de le sentir ?",
        "enfant-m|Encore un peu.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Papa a donné une pièce.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le citron est dans le sac, près du poisson.",
        "narrateur|Le papier reste un peu mouillé.",
        "papa|La pièce a servi à prendre le citron.",
        "enfant-m|Pour le poisson.",
        "papa|Oui.",
        "papa|On achète le citron avec ça.",
        "narrateur|Un goéland se pose plus loin.",
        "narrateur|L'eau claque encore contre la pierre.",
        "enfant-m|Il nous regarde.",
        "papa|On lui laisse les miettes, pas le citron.",
        "narrateur|Amir referme le sac.",
        "narrateur|Le zeste sent encore ses doigts.",
        "papa|Tu as rattrapé le citron.",
        "papa|Merci, Amir.",
        "narrateur|La glace fond un peu sur le zinc.",
        "papa|On rentre ?",
        "enfant-m|Oui, papa.",
        "narrateur|Le sac tape contre la jambe.",
        "narrateur|Ça sent le port, tout le long.",
        "papa|Le poisson attend le citron, ce soir.",
        "enfant-m|Je le presserai.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La cuisine sent encore le quai, un peu.",
        "narrateur|Papa pose le papier sur l'évier.",
        "papa|Tu poses le citron ?",
        "enfant-m|Oui.",
        "narrateur|Amir pose le citron près du robinet.",
        "narrateur|Une goutte d'eau brille sur le zeste.",
        "enfant-m|On le coupe ?",
        "papa|En deux, tout doux.",
        "narrateur|Papa coupe le citron.",
        "narrateur|Le jus pique un peu l'air.",
        "enfant-m|Ça pique le nez !",
        "papa|Oui.",
        "papa|Tu presses un peu ?",
        "narrateur|Amir presse un demi-citron.",
        "narrateur|Le jus tombe sur le poisson.",
        "enfant-m|Il est prêt.",
        "papa|Oui.",
        "narrateur|Les doigts d'Amir sentent le jaune.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le citron a roulé.",
        "enfant-m|On l'a pris, pour le poisson.",
        "papa|Bravo, Amir.",
        "narrateur|Le jus brille encore sur le zinc.",
        "narrateur|Le citron pique un peu les doigts.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-04 N3 — Nino, maman, épicerie de village, bocal
# ---------------------------------------------------------------------------
A04 = {
    "CHK_T0000_P0000": [
        "narrateur|La clochette de l'épicerie tinte deux fois.",
        "narrateur|Le comptoir de bois sent la cire.",
        "narrateur|Des bocaux alignés brillent contre le mur.",
        "narrateur|Ça sent le miel et le café moulu.",
        "narrateur|Maman range des pièces dans un petit filet.",
        "narrateur|Nino vit ici, avec maman.",
        "enfant-m|Maman, la clochette a chanté !",
        "maman|Oui.",
        "maman|On est dans l'épicerie du village.",
        "enfant-m|Je veux le bocal de miel.",
        "maman|Celui qui est tout doré ?",
        "enfant-m|Oui.",
        "narrateur|En ce moment, Nino regarde la tablette.",
        "narrateur|Le bocal doré est un peu haut.",
        "narrateur|Le verre est épais, un peu poussiéreux.",
        "enfant-m|Je le montre.",
        "maman|Tout doux.",
        "narrateur|Nino tend le doigt vers le verre.",
        "narrateur|Le bocal penche un peu.",
        "enfant-m|Il est lourd !",
        "maman|On le prend à deux.",
        "narrateur|Maman tient le haut.",
        "narrateur|Nino tient le bas, tout près.",
        "narrateur|Le verre est froid dans ses paumes.",
        "narrateur|Ils posent le bocal sur le comptoir.",
        "maman|J'ai des pièces, dans le filet.",
        "maman|Elles servent à prendre le miel.",
        "narrateur|Maman pose deux pièces sur le bois.",
        "narrateur|Une pièce glisse, puis tombe.",
        "narrateur|Elle tinte contre le carrelage.",
        "enfant-m|Elle chante !",
        "maman|Tu peux la ramasser ?",
        "narrateur|Nino se baisse près du comptoir.",
        "narrateur|La pièce est tiède, un peu lisse.",
        "enfant-m|Je l'ai.",
        "maman|Merci, Nino.",
        "narrateur|Nino pose la pièce près de l'autre.",
        "narrateur|Les deux pièces tintent encore une fois.",
        "narrateur|Elles tombent dans le tiroir du comptoir.",
        "narrateur|Le tiroir sonne, puis se ferme.",
        "enfant-m|Le bocal est à nous.",
        "maman|Oui.",
        "maman|Tu le portes ?",
        "enfant-m|Il est encore lourd.",
        "maman|On le met dans le filet.",
        "narrateur|Nino glisse le bocal dans le filet.",
        "narrateur|Le verre tape un peu le tissu.",
        "narrateur|Ça sent le miel, tout près.",
        "maman|Tu as fini de le sentir ?",
        "enfant-m|Encore un peu.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Maman a donné des pièces.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le bocal doré est dans le filet.",
        "narrateur|Le miel colle un peu sous le couvercle.",
        "maman|Les pièces ont servi à le prendre.",
        "enfant-m|Pour le miel.",
        "maman|Oui.",
        "maman|On achète le bocal avec ça.",
        "narrateur|La clochette tinte encore, derrière eux.",
        "narrateur|Le comptoir de bois reste luisant.",
        "enfant-m|La pièce a tinté par terre.",
        "maman|Et tu l'as ramassée.",
        "maman|Bravo, Nino.",
        "narrateur|Le filet tape contre la jambe de Nino.",
        "narrateur|Le verre fait un petit bruit sourd.",
        "maman|On rentre ?",
        "enfant-m|Oui, maman.",
        "narrateur|La rue du village sent le pain, plus loin.",
        "narrateur|Nino garde une main sous le filet.",
        "maman|Tu aides à le porter.",
        "enfant-m|Oui.",
        "narrateur|Une abeille passe, tout loin.",
        "enfant-m|Elle aime le miel aussi.",
        "maman|On lui en laisse, dans les fleurs.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La table de la cuisine est claire.",
        "narrateur|Nino pose le filet tout doux.",
        "maman|Tu sors le bocal ?",
        "enfant-m|Oui.",
        "narrateur|Le verre est encore froid.",
        "narrateur|Le miel est épais, tout lent.",
        "enfant-m|On ouvre ?",
        "maman|Un tout petit peu.",
        "narrateur|Maman dévisse le couvercle.",
        "narrateur|Ça sent le chaud, tout sucré.",
        "enfant-m|C'est fort !",
        "maman|Oui.",
        "maman|Tu goûtes le bout de la cuillère ?",
        "narrateur|Nino goûte.",
        "narrateur|C'est collant, puis doux.",
        "enfant-m|C'est bon.",
        "maman|Merci d'avoir tenu le bas.",
        "narrateur|Une goutte de miel brille sur le bois.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|La pièce a tinté.",
        "enfant-m|On a le bocal de miel.",
        "maman|Bravo, Nino.",
        "narrateur|Le couvercle sent encore le sucre.",
        "narrateur|Le miel sent encore le bocal.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-05 N3 — Chouchou, maman, foire aux plants, menthe
# ---------------------------------------------------------------------------
A05 = {
    "CHK_T0000_P0000": [
        "narrateur|Les pots de terre sont encore humides.",
        "narrateur|Une allée de planches sent la sève.",
        "narrateur|Ça sent la terre mouillée, sous les tentes.",
        "narrateur|Des feuilles de menthe brillent au soleil.",
        "narrateur|Maman porte un panier d'osier rêche.",
        "narrateur|Chouchou vit ici, avec maman.",
        "enfant-f|Maman, ça sent fort, les feuilles !",
        "maman|C'est la menthe.",
        "maman|Tu as vu le petit pot, devant ?",
        "enfant-f|Je le veux.",
        "maman|Pour le rebord de la fenêtre ?",
        "enfant-f|Oui.",
        "narrateur|En ce moment, Chouchou se baisse.",
        "narrateur|La terre colle déjà à ses doigts.",
        "narrateur|Le pot de menthe est bas, un peu lourd.",
        "enfant-f|Il est froid.",
        "maman|La terre est encore mouillée.",
        "narrateur|Chouchou touche une feuille.",
        "narrateur|La feuille est rêche, puis parfumée.",
        "enfant-f|Ça sent dans mes doigts !",
        "maman|Oui.",
        "maman|On le prend.",
        "narrateur|Chouchou veut soulever le pot.",
        "narrateur|Le pot penche, trop lourd.",
        "enfant-f|Il ne vient pas.",
        "maman|À deux, tout doux.",
        "narrateur|Maman tient un côté.",
        "narrateur|Chouchou tient l'autre.",
        "narrateur|Ils posent le pot dans le panier.",
        "narrateur|Un peu de terre tombe sur la planche.",
        "maman|J'ai une pièce, dans ma poche.",
        "maman|Elle sert à prendre le pot.",
        "narrateur|Maman tend la pièce.",
        "narrateur|La pièce sonne dans une boîte en fer.",
        "narrateur|La boîte se ferme.",
        "enfant-f|Le pot est à nous.",
        "maman|Oui.",
        "maman|Tu as de la terre aux doigts.",
        "enfant-f|C'est la menthe.",
        "narrateur|Chouchou frotte un doigt à l'osier.",
        "narrateur|La terre reste un peu, sous l'ongle.",
        "maman|On laisse cette terre.",
        "maman|Elle a voyagé avec la plante.",
        "enfant-f|Elle sent bon.",
        "maman|Tu as fini de la sentir ?",
        "enfant-f|Encore un peu.",
        "narrateur|Une abeille passe au-dessus des feuilles.",
        "narrateur|Chouchou reste toute calme.",
        "maman|On la laisse.",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Maman a donné une pièce.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le pot de menthe est dans le panier.",
        "narrateur|Les feuilles bougent un peu, au vent.",
        "maman|La pièce a servi à le prendre.",
        "enfant-f|Pour la menthe.",
        "maman|Oui.",
        "maman|On achète le pot avec ça.",
        "narrateur|Chouchou regarde ses doigts.",
        "narrateur|La terre y fait deux petits ronds.",
        "enfant-f|Mes doigts sentent les feuilles.",
        "maman|Bravo, Chouchou.",
        "narrateur|Le panier d'osier râpe un peu le bras.",
        "narrateur|Le pot tape un coup, puis s'arrête.",
        "maman|On rentre ?",
        "enfant-f|Oui, maman.",
        "narrateur|Les tentes de la foire claquent.",
        "narrateur|Ça sent encore la sève, derrière eux.",
        "enfant-f|Le rebord va aimer.",
        "maman|Oui.",
        "maman|La menthe aime le soleil, là.",
        "narrateur|Chouchou garde une main sous le panier.",
        "narrateur|La terre ne tombe plus.",
        "maman|Tu aides à le porter.",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Le rebord de la fenêtre est chaud.",
        "maman|Tu poses le pot ?",
        "enfant-f|Oui.",
        "narrateur|Chouchou pose le pot, tout doux.",
        "narrateur|Une feuille touche la vitre.",
        "enfant-f|Elle est fraîche.",
        "maman|Oui.",
        "maman|Tu frottes une feuille ?",
        "narrateur|Chouchou frotte une feuille entre deux doigts.",
        "narrateur|L'odeur monte, toute verte.",
        "enfant-f|C'est fort !",
        "maman|Oui.",
        "maman|Merci d'avoir tenu le pot.",
        "narrateur|Un peu de terre reste sur le rebord.",
        "narrateur|Chouchou la pousse près de la plante.",
        "enfant-f|Elle reste avec la menthe.",
        "maman|Oui.",
        "narrateur|La vitre a une petite buée, maintenant.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|J'ai de la terre aux doigts.",
        "enfant-f|On a le pot de menthe.",
        "maman|Bravo, Chouchou.",
        "narrateur|La feuille froissée sent encore.",
        "narrateur|La menthe sent fort, contre son nez.",
    ],
}

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.001-06 N2 — Raphaël, maman, kiosque à journaux + crayon
# ---------------------------------------------------------------------------
A06 = {
    "CHK_T0000_P0000": [
        "narrateur|Les journaux du kiosque sentent l'encre.",
        "narrateur|Une pince à linge tient une une pliée.",
        "narrateur|Le bois du comptoir est rêche, un peu gris.",
        "narrateur|Un gobelet de crayons attend au bord.",
        "narrateur|Maman range une pièce dans sa poche.",
        "narrateur|Raphaël vit ici, avec maman.",
        "enfant-m|Maman, ça sent le papier !",
        "maman|Oui.",
        "maman|Le kiosque est ouvert.",
        "enfant-m|Je veux un crayon, le jaune.",
        "maman|Celui du gobelet ?",
        "enfant-m|Oui.",
        "narrateur|En ce moment, Raphaël se hausse un peu.",
        "narrateur|Le gobelet est trop près du bord.",
        "narrateur|Il tend la main vers le jaune.",
        "narrateur|Le crayon roule hors du gobelet.",
        "narrateur|Il part sur le bois du comptoir.",
        "enfant-m|Il part !",
        "maman|Tu peux le rattraper.",
        "narrateur|Raphaël pose la main, tout doux.",
        "narrateur|Le crayon s'arrête contre ses doigts.",
        "enfant-m|Je l'ai.",
        "maman|Oui.",
        "maman|J'ai une pièce, pour le prendre.",
        "narrateur|Maman tend la pièce.",
        "narrateur|La pièce tombe dans le tiroir du kiosque.",
        "narrateur|Le tiroir sonne, puis se ferme.",
        "enfant-m|Le crayon est à nous.",
        "maman|Oui.",
        "maman|Tu le tiens ?",
        "enfant-m|Oui, maman.",
        "narrateur|Raphaël tient le crayon jaune.",
        "narrateur|Le bois est lisse, un peu hexagonal.",
        "narrateur|Ça sent le bois neuf, tout près.",
        "enfant-m|Il a une gomme au bout.",
        "maman|Oui.",
        "maman|Pour tes dessins, à la maison.",
        "narrateur|Un journal claque un peu au vent.",
        "narrateur|La pince à linge tient encore.",
        "maman|Tu as fini de le sentir ?",
        "enfant-m|Encore un peu.",
        "narrateur|Raphaël passe le crayon sous son nez.",
        "narrateur|Le bois sent la mine, un peu.",
        "maman|On rentre ?",
        "enfant-m|Oui.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Maman a donné une pièce.",
        "narrateur|L'argent sert à quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le crayon jaune est dans la main de Raphaël.",
        "narrateur|La gomme du bout est encore neuve.",
        "maman|La pièce a servi à le prendre.",
        "enfant-m|Pour le crayon.",
        "maman|Oui.",
        "maman|On achète le crayon avec ça.",
        "narrateur|Le tiroir du kiosque reste fermé.",
        "narrateur|L'encre des journaux sent encore.",
        "enfant-m|La pièce est dans le tiroir.",
        "maman|Et le crayon est avec toi.",
        "maman|Bravo, Raphaël.",
        "narrateur|Raphaël range le crayon dans sa poche.",
        "narrateur|Le bois fait un petit bruit contre le tissu.",
        "maman|Il ne roule plus.",
        "enfant-m|Il est à l'abri.",
        "maman|On rentre dessiner ?",
        "enfant-m|Oui, maman.",
        "narrateur|Le kiosque reste derrière, tout gris.",
        "narrateur|La pince à linge tient encore la une.",
        "maman|Tu as rattrapé le crayon.",
        "enfant-m|Tout doux.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La table de la cuisine est claire.",
        "narrateur|Une feuille blanche attend.",
        "maman|Tu sors le crayon ?",
        "enfant-m|Oui.",
        "narrateur|Raphaël pose le crayon sur la feuille.",
        "narrateur|Il dessine un soleil, tout rond.",
        "enfant-m|Il est jaune, comme le crayon.",
        "maman|Oui.",
        "maman|Merci d'avoir rattrapé le crayon.",
        "narrateur|La mine laisse un trait doux.",
        "narrateur|Ça sent encore un peu l'encre, sur ses doigts.",
        "enfant-m|Le kiosque sentait pareil.",
        "maman|Oui.",
        "narrateur|Le soleil a des rayons un peu croches.",
        "enfant-m|C'est le mien.",
        "maman|Oui.",
        "narrateur|La gomme du bout n'a pas encore servi.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le crayon a roulé.",
        "enfant-m|On l'a pris, avec la pièce.",
        "maman|Bravo, Raphaël.",
        "narrateur|Le soleil jaune sèche sur la feuille.",
        "narrateur|Le crayon sent encore le bois neuf.",
    ],
}


def main() -> None:
    write_story(
        "ATOM-SEC.RUE.003-07",
        "Sous la pluie fine du village, Nina veut le savon rond au miel de la pharmacie. La manche glisse, elle prend la main, contourne la flaque, et rentre avec le savon chaud d'odeur.",
        "Le savon de miel de Nina",
        "Nina, maman",
        "rue du village sous la pluie fine, gouttière de zinc, pharmacie à la croix verte",
        S07,
        {"CHK_T0000_P0000": ""},
        {
            "expected_answer": "près de maman",
            "accepted_examples": "près de maman | près | la main | manteau | à côté",
            "retry_prompt": "Elle tient la main ou le manteau. Où est Nina ?",
        },
    )
    relecture(
        "ATOM-SEC.RUE.003-07",
        "Le savon de miel de Nina",
        "Pluie fine, zinc, pavés, savon au miel. Nina veut le savon. Manche mouillée qui glisse, flaque. Elle prend la main, reste près, tient le savon.",
        "POS-001 : rester près, main ou manteau, contourner la flaque. Pas de course. Ouverture gouttière. Fin savon/miel, pas « L'histoire est finie ».",
    )

    write_story(
        "ATOM-SEC.RUE.003-08",
        "Dans la ruelle aux volets bleus, Victorina veut des brioches chaudes. Un volet claque, une bille au sol : elles restent près, prennent la bille ensemble, et le sac sent le beurre.",
        "Les brioches de la ruelle",
        "Victorina, maman",
        "ruelle aux volets bleus, chat sur la marche, four du boulanger",
        S08,
        {},
        {
            "expected_answer": "près de maman",
            "accepted_examples": "près de maman | près | la main | manteau | à côté",
            "retry_prompt": "Elle reste près. Elle tient le manteau. Où est Victorina ?",
        },
    )
    relecture(
        "ATOM-SEC.RUE.003-08",
        "Les brioches de la ruelle",
        "Volets bleus, linge, chat, brioches. Volet qui claque, bille au sol. Elles se baissent ensemble, restent près, sac tiède.",
        "POS-001 : pas de course après la bille. Main ou manteau. Ouverture volets. Fin brioche dans la main.",
    )

    write_story(
        "ATOM-SOC.ARG.001-01",
        "Au marché sous la bâche, Mila veut un petit pain chaud. Celui qu'elle montre est déjà vendu. Papa paie un autre, encore tiède. Elle croque la mie.",
        "Le petit pain chaud de Mila",
        "Mila, papa",
        "marché sous la bâche, stand du pain, cabas de toile",
        A01,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | le pain | le petit pain | prendre le pain | la pièce",
            "retry_prompt": "On prend le petit pain. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-01",
        "Le petit pain chaud de Mila",
        "Bâche, farine, pigeon. Mila veut le pain doré. Déjà vendu. Autre pain, pièce dans le tiroir, mie tiède.",
        "Pas un cours : désir du pain, imprévu vendu, pièce comme geste. Fin mie/four.",
    )

    write_story(
        "ATOM-SOC.ARG.001-02",
        "Sous les halles, la sciure colle aux semelles. Sarah veut un fromage, puis un fruit. Le gros fromage est trop grand ; une poire roule dans la sciure. Deux pièces, deux choses dans le cabas.",
        "Le fromage des halles",
        "Sarah, maman, papa",
        "halles, sciure au sol, piliers de fer, stand du fromage puis des poires",
        A02,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | le fromage | le fruit | la poire | les pièces | prendre",
            "retry_prompt": "On prend le fromage et la poire. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-02",
        "Le fromage des halles",
        "Sciure, piliers, fromage trop grand, poire qui roule. Deux moments, deux pièces. Goût lait puis sucre.",
        "Monde unique halles. Deux achats vécus, pas une liste. Papa et maman parlent.",
    )

    write_story(
        "ATOM-SOC.ARG.001-03",
        "Au port, Amir veut un citron pour le poisson. Le citron roule sur la glace. Il le rattrape. Papa paie. Le jus pique les doigts.",
        "Le citron du port",
        "Amir, papa",
        "poissonnier du port, caisses de glace, quai, goéland",
        A03,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | le citron | le poisson | prendre le citron | la pièce",
            "retry_prompt": "On prend un citron. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-03",
        "Le citron du port",
        "Glace, sel, goéland, poisson, citron qui roule. Pièce, zeste, jus sur le poisson.",
        "Argent greffé au citron, pas un cours. Fin sensorielle zeste/jus.",
    )

    write_story(
        "ATOM-SOC.ARG.001-04",
        "À l'épicerie du village, Nino veut le bocal de miel. Le verre est lourd. Une pièce tombe et tinte. Il la ramasse. Le miel colle à la cuillère.",
        "Le bocal de miel de Nino",
        "Nino, maman",
        "épicerie de village, clochette, comptoir de cire, bocaux",
        A04,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | le miel | le bocal | prendre le miel | les pièces",
            "retry_prompt": "On prend le bocal de miel. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-04",
        "Le bocal de miel de Nino",
        "Clochette, cire, bocal lourd, pièce qui tinte. Nino ramasse, goûte le miel.",
        "Monnaie vécue (tinte), pas une leçon. Fin miel/bocal.",
    )

    write_story(
        "ATOM-SOC.ARG.001-05",
        "À la foire aux plants, Chouchou veut un pot de menthe. La terre colle aux doigts, le pot est lourd. Maman paie. La feuille froissée sent fort sur le rebord.",
        "Le pot de menthe de Chouchou",
        "Chouchou, maman",
        "foire aux plants, tentes, planches, pots de terre, rebord de fenêtre",
        A05,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | la menthe | le pot | prendre le pot | la pièce",
            "retry_prompt": "On prend le pot de menthe. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-05",
        "Le pot de menthe de Chouchou",
        "Terre humide, sève, menthe, pot trop lourd, pièce, doigts sales, rebord chaud.",
        "Désir du pot, monnaie greffée. Fin odeur de menthe.",
    )

    write_story(
        "ATOM-SOC.ARG.001-06",
        "Au kiosque, Raphaël veut le crayon jaune. Le crayon roule. Il le rattrape. La pièce tombe dans le tiroir. Il dessine un soleil.",
        "Le crayon jaune de Raphaël",
        "Raphaël, maman",
        "kiosque à journaux, gobelet de crayons, tiroir, table de la cuisine",
        A06,
        {},
        {
            "expected_answer": "acheter",
            "accepted_examples": "acheter | le crayon | prendre le crayon | la pièce | le tiroir",
            "retry_prompt": "On prend le crayon. L'argent sert à quoi ?",
        },
    )
    relecture(
        "ATOM-SOC.ARG.001-06",
        "Le crayon jaune de Raphaël",
        "Encre, pince à linge, crayon qui roule, pièce dans le tiroir, soleil sur la feuille.",
        "Pas une liste d'achats. Fin bois neuf / soleil jaune.",
    )


if __name__ == "__main__":
    main()
