#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-TMP.SAI.001-07 et ATOM-TMP.SEM.001-01..07."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-TMP.SAI.001-07  N3  Sarah, papa — poire, quatre visites au poirier
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SAI.001-07",
    "Sarah veut une poire du poirier du jardin. Au printemps, des bourgeons. En été, des feuilles et la chaleur. En automne, le fruit est trop haut. En hiver, la branche est nue, la poire est dans sa main.",
    "La poire du poirier",
    "Sarah, papa",
    "jardin du poirier, puis fenêtre en hiver",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une abeille rase le poirier du fond.",
            "narrateur|L'écorce sent le bois mouillé.",
            "narrateur|De la mousse verte tient au pied.",
            "narrateur|Un seau de zinc brille près des tulipes du massif.",
            "narrateur|Le seau est vide, un peu bosselé.",
            "papa|Tu as vu l'abeille, Sarah ?",
            "enfant-f|Elle tourne.",
            "papa|Elle cherche une fleur.",
            "narrateur|En ce moment, Sarah pose la joue contre l'écorce.",
            "enfant-f|Je veux une poire.",
            "enfant-f|Une poire pour moi.",
            "papa|On va regarder l'arbre.",
            "narrateur|Sarah lève le nez.",
            "narrateur|Des bourgeons durs pointent sur les branches.",
            "narrateur|Ils sont verts, tout petits.",
            "enfant-f|Où est la poire ?",
            "papa|C'est le printemps.",
            "papa|Le poirier a des bourgeons.",
            "papa|Pas encore de poire.",
            "narrateur|Sarah touche un bourgeon du doigt.",
            "narrateur|Il est froid et fermé.",
            "enfant-f|Il s'ouvre ?",
            "papa|Plus tard.",
            "papa|On revient.",
            "narrateur|Ils reviennent quand l'herbe est sèche.",
            "narrateur|Le soleil tape le seau de zinc.",
            "narrateur|Les feuilles du poirier sont grandes.",
            "narrateur|Elles font une ombre ronde.",
            "enfant-f|Il fait chaud, papa.",
            "papa|C'est l'été.",
            "papa|Les feuilles sont le signe.",
            "narrateur|Sarah cherche une poire jaune.",
            "narrateur|Une petite boule verte pend très haut.",
            "narrateur|Elle est dure, encore trop petite.",
            "enfant-f|Je la prends ?",
            "papa|Elle n'est pas prête.",
            "papa|Elle ferait mal aux dents.",
            "enfant-f|J'ai trop soif de poire.",
            "papa|On attend encore.",
            "papa|Le poirier a quatre saisons.",
            "papa|Chaque saison a son signe.",
            "narrateur|Sarah s'assoit dans l'herbe chaude.",
            "narrateur|L'abeille passe encore, trop pressée.",
            "narrateur|Le seau reste vide.",
            "enfant-f|Quand la poire ?",
            "papa|Quand elle sera jaune.",
            "papa|On reviendra.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait chaud sous les feuilles.",
            "narrateur|Quelle saison est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'air sent la terre et le fruit.",
            "narrateur|Une feuille jaune tourne, puis tombe.",
            "papa|C'est l'automne, Sarah.",
            "papa|Tu vois le fruit ?",
            "enfant-f|Une poire !",
            "narrateur|La poire est jaune, un peu tachetée.",
            "narrateur|Elle penche au bout d'une branche haute.",
            "enfant-f|Je n'arrive pas.",
            "papa|Elle est trop haute.",
            "narrateur|Sarah pousse le seau sous l'arbre.",
            "narrateur|Le zinc sonne, tîn.",
            "narrateur|Elle monte un pied, tout doux.",
            "papa|J'attrape le seau.",
            "papa|Tu montres la poire.",
            "enfant-f|Celle-là, papa.",
            "narrateur|Papa lève les bras.",
            "narrateur|La poire se détache avec une petite craque.",
            "narrateur|Elle tombe dans le seau.",
            "enfant-f|Elle est à moi.",
            "papa|Merci, Sarah.",
            "papa|Tu as attendu les saisons.",
            "narrateur|Le jus tache déjà le zinc.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils rentrent, le seau entre eux.",
            "narrateur|La poire roule un peu, puis s'arrête.",
            "papa|On la coupe près de la fenêtre ?",
            "enfant-f|Oui.",
            "narrateur|Plus tard, le jardin est blanc de givre.",
            "narrateur|La branche du poirier est nue.",
            "papa|C'est l'hiver.",
            "papa|Le signe, c'est la branche nue.",
            "enfant-f|Plus de feuilles.",
            "papa|Quatre saisons sur le même arbre.",
            "narrateur|Sarah tient encore un quartier de poire.",
            "narrateur|Le quartier est froid, très sucré.",
            "papa|Tu as ta poire.",
            "enfant-f|Elle a attendu, comme moi.",
            "papa|Oui.",
            "narrateur|Une goutte de givre pend à la branche.",
            "narrateur|Elle brille, puis tombe.",
            "papa|On la range dans le seau ?",
            "enfant-f|Le seau a encore l'odeur.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sarah pose le quartier contre la vitre.",
            "narrateur|Le jus laisse un trait brillant.",
            "enfant-f|Ma poire est sucrée.",
            "papa|Oui.",
            "papa|Le poirier a tenu sa promesse.",
            "narrateur|La branche nue tient une perle de givre.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "été",
        "accepted_examples": "été | l'été | en été | chaud",
        "retry_prompt": "Il fait chaud. Les feuilles sont grandes. Quelle saison ?",
    },
)
relecture(
    "ATOM-TMP.SAI.001-07",
    "La poire du poirier",
    "Sarah veut une poire. Quatre visites : bourgeon, feuille et chaleur, fruit trop haut, branche nue. Elle pousse le seau. La poire tombe dedans.",
    "- Désir : la poire, pas la liste des saisons.\n"
    "- Ouverture : abeille, écorce, seau de zinc. Pas une fenêtre recopiée.\n"
    "- Leçon greffée : quatre saisons, un signe sur l'arbre.\n"
    "- Troupe D16 : Sarah, papa. Question : été.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-01  N1  Amir, maman — demain le marché, prunes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-01",
    "Amir veut des prunes. Maman dit : demain, c'est samedi, le marché. Ils y vont trop tôt, c'est vendredi, volets fermés. Ils reviennent le bon jour. Les prunes sont là.",
    "Les prunes de samedi",
    "Amir, maman",
    "cuisine, puis rue de la boutique",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le filet de maman sent encore le thym.",
            "narrateur|Deux brins restent collés au filet.",
            "narrateur|La cuisine est tiède, un peu sucrée.",
            "narrateur|Une tache violette brille sur la table.",
            "narrateur|C'est le jus d'une prune.",
            "maman|Tu as vu la tache, Amir ?",
            "enfant-m|Elle est violette.",
            "maman|C'est une prune d'hier.",
            "enfant-m|Je veux des prunes.",
            "enfant-m|Des prunes maintenant.",
            "maman|Demain, c'est samedi.",
            "maman|Samedi, c'est le marché.",
            "maman|Le marché a des prunes.",
            "narrateur|En ce moment, Amir prend le filet.",
            "narrateur|Le filet est vide et mou.",
            "enfant-m|On y va ?",
            "maman|On peut aller voir.",
            "narrateur|Ils marchent dans la rue calme.",
            "narrateur|Le pain froid sent encore.",
            "narrateur|Un chat dort sur une marche.",
            "narrateur|La boutique a les volets gris.",
            "enfant-m|C'est fermé.",
            "maman|C'est encore vendredi.",
            "maman|Vendredi, le marché dort.",
            "narrateur|Amir se penche sous un volet.",
            "narrateur|Il voit une caisse vide.",
            "narrateur|Une mouche tourne, puis part.",
            "enfant-m|Toc toc.",
            "narrateur|Personne ne répond.",
            "enfant-m|Les prunes ?",
            "maman|Demain, les volets s'ouvrent.",
            "maman|Demain, c'est samedi.",
            "maman|La semaine a sept jours.",
            "maman|On revient le bon jour.",
            "enfant-m|Je veux entrer.",
            "maman|On rentre à la maison.",
            "maman|Quel jour vient après vendredi ?",
            "enfant-m|Samedi.",
            "maman|Oui.",
            "narrateur|Ils reprennent le chemin.",
            "narrateur|Les chaussures font un bruit doux.",
            "narrateur|Le filet reste vide.",
            "narrateur|La tache violette attend à la maison.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après vendredi, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, la rue sent le fruit.",
            "narrateur|Les volets sont ouverts, tout grands.",
            "maman|C'est samedi, Amir.",
            "maman|C'est le bon jour.",
            "enfant-m|Les prunes !",
            "narrateur|Des prunes violettes brillent en tas.",
            "narrateur|Elles sont froides, un peu poudreuses.",
            "narrateur|Amir tend le filet.",
            "maman|Tu choisis ?",
            "enfant-m|Celles-là.",
            "narrateur|Maman les glisse dans le filet.",
            "narrateur|Le filet devient lourd, tout rond.",
            "enfant-m|Elles sont à nous.",
            "maman|Merci, Amir.",
            "maman|Tu as attendu samedi.",
            "narrateur|Une prune roule vers le bord.",
            "narrateur|Amir la rattrape avec la main.",
            "narrateur|Elle est lisse et froide.",
            "maman|On rentre ?",
            "enfant-m|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La table a encore la tache.",
            "narrateur|Amir pose le filet dessus.",
            "maman|Tu mords la tienne ?",
            "enfant-m|Oui.",
            "narrateur|Le jus coule sur son menton.",
            "narrateur|Il est froid, très sucré.",
            "enfant-m|Elle est bonne.",
            "maman|Vendredi, c'était fermé.",
            "maman|Samedi, le marché ouvre.",
            "enfant-m|J'ai attendu.",
            "maman|Oui.",
            "narrateur|Le thym sent encore le filet.",
            "narrateur|Deux noyaux brillent dans une coupelle.",
            "maman|On en garde pour demain ?",
            "enfant-m|Demain, c'est dimanche.",
            "maman|Oui.",
            "narrateur|Amir essuie son menton.",
            "narrateur|La tache violette a un ami.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Les doigts d'Amir sont un peu violets.",
            "enfant-m|J'ai mes prunes.",
            "maman|Oui.",
            "maman|Le bon jour était samedi.",
            "narrateur|Le filet sent le thym et le fruit.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "samedi",
        "accepted_examples": "samedi | le samedi | c'est samedi",
        "retry_prompt": "Vendredi, c'est fermé. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-01",
    "Les prunes de samedi",
    "Amir veut des prunes. Vendredi la boutique est fermée. Samedi les volets s'ouvrent. Il rattrape une prune qui roule.",
    "- Désir : les prunes, pas la liste des jours.\n"
    "- Un jour nommé : samedi, le marché. Imprévu : trop tôt, vendredi.\n"
    "- Troupe D16 : Amir, maman. N1. Question : samedi.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-02  N3  Mila, papa — samedi marché, dimanche square
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-02",
    "Mila veut un ballon rouge. Samedi au marché, le monsieur du ballon n'est pas là. Un écriteau dit dimanche, au square. Dimanche, le ballon s'envole un peu, puis tient.",
    "Le ballon du square",
    "Mila, papa",
    "marché du samedi, puis square du dimanche",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un chariot de paille grince sur les pavés.",
            "narrateur|L'air sent l'oignon et le sucre chaud.",
            "narrateur|Une caisse d'oranges brille au soleil bas.",
            "narrateur|Papa tient un sac de toile rêche.",
            "papa|Tu as senti l'oignon, Mila ?",
            "enfant-f|Il pique un peu.",
            "papa|C'est samedi.",
            "papa|C'est le jour du marché.",
            "narrateur|En ce moment, Mila cherche un fil rouge.",
            "enfant-f|Je veux un ballon.",
            "enfant-f|Un ballon rouge.",
            "papa|On le cherche.",
            "narrateur|Ils passent entre les caisses.",
            "narrateur|Un poulet rôti fume tout près.",
            "narrateur|Mila lève les yeux.",
            "narrateur|Pas de fil.",
            "narrateur|Pas de ballon.",
            "enfant-f|Il n'est pas là.",
            "papa|Le monsieur du ballon n'est pas au marché.",
            "narrateur|Un écriteau jaune penche contre une caisse.",
            "narrateur|Mila s'approche.",
            "enfant-f|Il y a un dessin de ballon.",
            "papa|Dimanche, au square.",
            "papa|C'est écrit.",
            "enfant-f|Pas ce samedi ?",
            "papa|Ce samedi, c'est le marché.",
            "papa|Demain, c'est dimanche.",
            "papa|La semaine a sept jours.",
            "narrateur|Mila serre le bord du sac.",
            "narrateur|Le tissu râpe sa paume.",
            "enfant-f|On prend des oignons alors.",
            "papa|Oui.",
            "papa|Et demain, le square.",
            "narrateur|Papa glisse deux oignons dans le sac.",
            "narrateur|Ils sont secs, un peu bruns.",
            "enfant-f|Le ballon m'attend ?",
            "papa|Au square, demain.",
            "papa|Quel jour vient après samedi ?",
            "enfant-f|Dimanche.",
            "papa|Oui.",
            "narrateur|Le chariot de paille grince encore, plus loin.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après samedi, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le square sent l'herbe coupée.",
            "narrateur|Un manège tourne tout doux, sans musique forte.",
            "papa|C'est dimanche, Mila.",
            "papa|Le bon jour du square.",
            "enfant-f|Le monsieur !",
            "narrateur|Un homme tient un bouquet de ballons.",
            "narrateur|Le rouge est au milieu, un peu plus petit.",
            "narrateur|Mila tend les deux mains.",
            "papa|Tu le tiens bien ?",
            "enfant-f|Oui.",
            "narrateur|Le fil est lisse, un peu collant.",
            "narrateur|Le ballon tire vers le ciel.",
            "enfant-f|Il veut partir.",
            "papa|On fait un nœud au poignet.",
            "narrateur|Papa noue le fil tout doux.",
            "narrateur|Le ballon reste, il danse.",
            "enfant-f|Il est à moi.",
            "papa|Merci, Mila.",
            "papa|Tu as attendu dimanche.",
            "narrateur|Un oignon du sac sent encore, dans le fond.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils s'assoient sur le banc du square.",
            "narrateur|Le bois est tiède.",
            "papa|Samedi, le marché.",
            "papa|Dimanche, le square.",
            "enfant-f|Et le ballon.",
            "papa|Oui.",
            "narrateur|Le ballon tape l'épaule de Mila.",
            "narrateur|Toc, tout léger.",
            "enfant-f|Il est rouge comme l'orange.",
            "papa|Presque.",
            "narrateur|Un pigeon picore une miette.",
            "narrateur|Mila tient le fil plus fort.",
            "papa|On rentre ?",
            "enfant-f|Le ballon vient.",
            "papa|Oui.",
            "narrateur|Le manège s'arrête un moment.",
            "narrateur|Le square redevient calme.",
            "enfant-f|Demain, c'est lundi.",
            "papa|Oui.",
            "papa|Le ballon reste avec nous.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le ballon rouge frotte le linteau de la porte.",
            "enfant-f|Il est rentré.",
            "papa|Oui.",
            "papa|Samedi le marché, dimanche le square.",
            "narrateur|Le fil fait une ombre mince sur le carrelage.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "dimanche",
        "accepted_examples": "dimanche | le dimanche | c'est dimanche",
        "retry_prompt": "Samedi, le marché. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-02",
    "Le ballon du square",
    "Mila veut un ballon rouge. Samedi au marché, personne. Dimanche au square, le fil se noue au poignet.",
    "- Deux jours vécus, pas sept noms dumpés.\n"
    "- Désir : le ballon. Imprévu : le monsieur n'est pas au marché.\n"
    "- Troupe D16 : Mila, papa. Question : dimanche.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-03  N2  Nino, maman — dimanche crêpes, lundi cartable
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-03",
    "Nino veut une crêpe sucrée. Dimanche, la première se déchire. Il en réussit une autre. Lundi, il glisse un morceau dans le cartable. La sangle est tordue. Il la remet.",
    "Les crêpes de dimanche",
    "Nino, maman",
    "cuisine le dimanche, puis entrée le lundi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La poêle chante un petit bruit de beurre.",
            "narrateur|Une fumée douce monte vers la fenêtre.",
            "narrateur|La table a une nappe à carreaux.",
            "narrateur|Un bol de pâte tremble un peu.",
            "maman|Tu as senti le beurre, Nino ?",
            "enfant-m|Il sent le gâteau.",
            "maman|C'est dimanche.",
            "maman|Dimanche, on fait des crêpes.",
            "narrateur|En ce moment, Nino tient la spatule.",
            "narrateur|La spatule est trop grande pour sa main.",
            "enfant-m|Je veux une crêpe sucrée.",
            "maman|On la tourne ensemble ?",
            "enfant-m|Oui.",
            "narrateur|La pâte s'étale, trop vite.",
            "narrateur|Un trou s'ouvre au milieu.",
            "enfant-m|Elle se déchire.",
            "maman|La première se déchire souvent.",
            "maman|On recommence.",
            "narrateur|Nino souffle sur la poêle.",
            "narrateur|La deuxième crêpe reste ronde.",
            "narrateur|Elle dore, tout doux.",
            "enfant-m|Celle-là, elle tient.",
            "maman|Bravo.",
            "maman|Tu as attendu le bon moment.",
            "narrateur|Maman plie la crêpe en deux.",
            "narrateur|Le sucre tombe comme une neige.",
            "enfant-m|Elle est à moi.",
            "maman|Oui.",
            "narrateur|Nino mord un coin.",
            "narrateur|Le sucre pique un peu, puis fond.",
            "enfant-m|J'en garde une pour demain ?",
            "maman|Demain, c'est lundi.",
            "maman|Lundi, c'est le cartable.",
            "maman|La semaine a sept jours.",
            "maman|Quel jour vient après dimanche ?",
            "enfant-m|Lundi.",
            "maman|Oui.",
            "narrateur|Une crêpe refroidit dans une serviette.",
            "narrateur|La poêle se tait.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après dimanche, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, l'entrée sent encore le beurre.",
            "narrateur|Le cartable bleu attend près des chaussures.",
            "maman|C'est lundi, Nino.",
            "maman|Le jour du cartable.",
            "enfant-m|Ma crêpe ?",
            "narrateur|La serviette est sur la table.",
            "narrateur|Nino glisse le morceau dans une boîte.",
            "narrateur|Il pose la boîte dans le cartable.",
            "enfant-m|Elle vient avec moi.",
            "maman|Oui.",
            "narrateur|La sangle du cartable est tordue.",
            "narrateur|Elle refuse de passer.",
            "enfant-m|Elle est de travers.",
            "maman|Tu peux la remettre.",
            "narrateur|Nino tourne la sangle tout doux.",
            "narrateur|Elle se cale sur l'épaule.",
            "maman|Merci, Nino.",
            "maman|Tu as préparé ton lundi.",
            "narrateur|La boîte fait un petit bruit de carton.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils ouvrent la porte.",
            "narrateur|L'air frais entre.",
            "maman|Dimanche, les crêpes.",
            "maman|Lundi, le cartable.",
            "enfant-m|Et ma crêpe dedans.",
            "maman|Oui.",
            "narrateur|Nino touche la boîte à travers le tissu.",
            "narrateur|Elle est un peu chaude encore.",
            "enfant-m|Elle sent le sucre.",
            "maman|Tu la mangeras à l'école.",
            "narrateur|Les chaussures tapent le palier.",
            "narrateur|Un oiseau crie dehors.",
            "maman|On y va ?",
            "enfant-m|Oui, maman.",
            "narrateur|La poêle, derrière, est déjà froide.",
            "narrateur|La nappe a une miette de sucre.",
            "enfant-m|J'ai réussi la ronde.",
            "maman|Oui.",
            "maman|La première s'était déchirée.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le cartable bleu tape la hanche de Nino.",
            "enfant-m|Ma crêpe voyage.",
            "maman|Oui.",
            "maman|Dimanche la poêle, lundi le cartable.",
            "narrateur|Une miette de sucre brille encore sur la nappe.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "lundi",
        "accepted_examples": "lundi | le lundi | c'est lundi",
        "retry_prompt": "Dimanche, les crêpes. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-03",
    "Les crêpes de dimanche",
    "Nino veut une crêpe sucrée. La première se déchire. Lundi, il met un morceau dans le cartable. La sangle est tordue.",
    "- Deux jours vécus : dimanche, lundi.\n"
    "- Désir : la crêpe. Imprévu : trou dans la pâte, sangle tordue.\n"
    "- Troupe D16 : Nino, maman. Question : lundi.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-04  N2  Nina, papa — mercredi bibliothèque, jeudi pain
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-04",
    "Nina veut un livre de bateau. Mercredi à la bibliothèque, le livre est trop haut. Papa l'aide à le montrer. Jeudi, le pain chaud. Elle ouvre le livre, des miettes tombent sur la voile.",
    "Le livre et le pain",
    "Nina, papa",
    "bibliothèque le mercredi, puis boulangerie le jeudi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un marque-page rouge dépasse du gros livre.",
            "narrateur|La salle sent le papier et le bois ciré.",
            "narrateur|Une chaise racle tout doux.",
            "narrateur|La lumière tombe en carré sur le tapis.",
            "papa|Tu as senti le papier, Nina ?",
            "enfant-f|Il sent le calme.",
            "papa|C'est mercredi.",
            "papa|Mercredi, c'est la bibliothèque.",
            "narrateur|En ce moment, Nina cherche un bateau.",
            "enfant-f|Je veux le livre du bateau.",
            "enfant-f|Celui avec la voile bleue.",
            "papa|On le cherche.",
            "narrateur|Les dos des livres sont serrés.",
            "narrateur|Nina passe le doigt sur les titres.",
            "narrateur|Le doigt s'arrête trop bas.",
            "enfant-f|Il est tout en haut.",
            "papa|Trop haut pour ta main.",
            "narrateur|Nina pousse le tabouret.",
            "narrateur|Le tabouret glisse, puis tient.",
            "enfant-f|Je montre lequel.",
            "papa|Tu montes un pied.",
            "papa|Je tiens le tabouret.",
            "narrateur|Nina pointe le dos bleu.",
            "narrateur|Papa le descend tout doux.",
            "enfant-f|La voile !",
            "papa|Tu l'as trouvé.",
            "narrateur|Le livre est lourd, un peu froid.",
            "enfant-f|Je le lis avec du pain.",
            "papa|Demain, c'est jeudi.",
            "papa|Jeudi, on prend le pain.",
            "papa|La semaine a sept jours.",
            "papa|Quel jour vient après mercredi ?",
            "enfant-f|Jeudi.",
            "papa|Oui.",
            "narrateur|Nina serre le livre contre elle.",
            "narrateur|Le marque-page rouge tape son poignet.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après mercredi, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, la rue sent le four.",
            "narrateur|Une miche dorée brille derrière la vitre.",
            "papa|C'est jeudi, Nina.",
            "papa|Le jour du pain.",
            "enfant-f|Il est chaud ?",
            "papa|On va le prendre.",
            "narrateur|Nina tient encore le livre sous le bras.",
            "narrateur|La couverture frotte son manteau.",
            "narrateur|Papa prend la miche.",
            "narrateur|Le papier craque.",
            "enfant-f|Je l'ouvre à la maison.",
            "papa|Le livre ou le pain ?",
            "enfant-f|Les deux.",
            "papa|Merci, Nina.",
            "papa|Tu as attendu jeudi.",
            "narrateur|La miche chauffe le creux du sac.",
            "narrateur|Le livre reste contre Nina.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La table de la cuisine est claire.",
            "narrateur|Nina pose le livre.",
            "papa|Tu tournes la page ?",
            "enfant-f|La voile bleue.",
            "narrateur|Papa casse le pain.",
            "narrateur|Une miette tombe sur la voile.",
            "enfant-f|Le bateau a du pain.",
            "papa|On souffle.",
            "narrateur|La miette part.",
            "narrateur|Le papier sent le four, un peu.",
            "papa|Mercredi, le livre.",
            "papa|Jeudi, le pain.",
            "enfant-f|J'ai les deux.",
            "papa|Oui.",
            "narrateur|Nina mord un morceau de croûte.",
            "narrateur|La croûte casse, tout net.",
            "enfant-f|Il est chaud.",
            "papa|Comme tu voulais.",
            "narrateur|Le marque-page rouge garde la page.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nina pose la main à plat sur la voile.",
            "enfant-f|Le bateau est à moi.",
            "papa|Oui.",
            "papa|Le pain aussi.",
            "narrateur|Une miette dore encore au creux de la page.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "jeudi",
        "accepted_examples": "jeudi | le jeudi | c'est jeudi",
        "retry_prompt": "Mercredi, la bibliothèque. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-04",
    "Le livre et le pain",
    "Nina veut le livre du bateau. Mercredi il est trop haut. Jeudi le pain chaud. Une miette tombe sur la voile.",
    "- Deux jours vécus : mercredi, jeudi.\n"
    "- Désir : le livre, puis le pain pour le lire. Imprévu : trop haut.\n"
    "- Troupe D16 : Nina, papa. Question : jeudi.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-05  N2  Raphaël, maman — vendredi poisson, samedi gâteau
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-05",
    "Raphaël veut le gâteau de samedi. Vendredi, ils vont au port pour le poisson. L'étal range la glace. Samedi, un œuf roule. Il le rattrape. Le gâteau dore.",
    "Le poisson et le gâteau",
    "Raphaël, maman",
    "port le vendredi, cuisine le samedi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une écaille d'argent brille entre deux planches.",
            "narrateur|Les cordes des bateaux claquent contre le bois.",
            "narrateur|L'air sent le sel et le citron.",
            "narrateur|Une caisse de glace fume tout bas.",
            "maman|Tu as vu l'écaille, Raphaël ?",
            "enfant-m|Elle brille.",
            "maman|C'est vendredi.",
            "maman|Vendredi, on prend le poisson du port.",
            "narrateur|En ce moment, Raphaël touche la glace.",
            "narrateur|Elle pique ses doigts.",
            "enfant-m|Je veux le gâteau.",
            "enfant-m|Le gâteau de demain.",
            "maman|Demain, c'est samedi.",
            "maman|Samedi, on le fait.",
            "maman|D'abord le poisson.",
            "narrateur|L'étal range déjà les caisses.",
            "narrateur|Un tas de glace glisse vers le bord.",
            "enfant-m|Ils s'en vont.",
            "maman|On demande le petit.",
            "narrateur|Maman montre un poisson court.",
            "narrateur|Il a l'œil encore clair.",
            "enfant-m|Celui-là.",
            "narrateur|Le papier se ferme, tout froid.",
            "maman|Vendredi, le port.",
            "maman|Samedi, la farine.",
            "maman|La semaine a sept jours.",
            "maman|Quel jour vient après vendredi ?",
            "enfant-m|Samedi.",
            "maman|Oui.",
            "narrateur|Raphaël tient le sac contre lui.",
            "narrateur|Le poisson tape, tout mou.",
            "enfant-m|Il sent la mer.",
            "maman|On rentre.",
            "narrateur|Une mouette crie au-dessus du quai.",
            "narrateur|L'écaille reste coincée entre les planches.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après vendredi, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, la cuisine sent le citron.",
            "narrateur|Un sac de farine attend sur la table.",
            "maman|C'est samedi, Raphaël.",
            "maman|Le jour du gâteau.",
            "enfant-m|Je casse l'œuf ?",
            "maman|Tout doux.",
            "narrateur|L'œuf roule vers le bord.",
            "narrateur|Raphaël tend la main.",
            "narrateur|Il le rattrape contre la farine.",
            "enfant-m|Je l'ai.",
            "maman|Merci, Raphaël.",
            "maman|Tu as rattrapé l'œuf.",
            "narrateur|Ils cassent l'œuf dans le bol.",
            "narrateur|La farine fait un nuage blanc.",
            "enfant-m|Il neige.",
            "maman|Un peu.",
            "narrateur|La pâte devient jaune, puis lisse.",
            "maman|Au four.",
            "narrateur|La porte du four claque, tiède.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le gâteau dore derrière la vitre.",
            "narrateur|La cuisine sent le beurre chaud.",
            "maman|Vendredi, le poisson.",
            "maman|Samedi, le gâteau.",
            "enfant-m|Les deux jours.",
            "maman|Oui.",
            "narrateur|Raphaël colle le nez à la vitre.",
            "narrateur|Le gâteau gonfle, tout lent.",
            "enfant-m|Il est presque prêt.",
            "maman|Encore un peu.",
            "narrateur|Le sac du poisson, lui, est déjà vide.",
            "narrateur|Il reste une odeur de sel sur le manteau.",
            "maman|On le sort ?",
            "enfant-m|Oui.",
            "narrateur|Le gâteau tremble, puis se tient.",
            "enfant-m|Il est à nous.",
            "maman|Oui.",
            "maman|Tu as attendu samedi.",
            "narrateur|Une miette de citron brille sur la table.",
            "narrateur|Raphaël pose la spatule, encore farineuse.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Raphaël souffle sur le gâteau, tout doux.",
            "enfant-m|Il est chaud.",
            "maman|Oui.",
            "maman|Le port hier, le four maintenant.",
            "narrateur|Une écaille d'argent sèche encore sur la planche du quai.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "samedi",
        "accepted_examples": "samedi | le samedi | c'est samedi",
        "retry_prompt": "Vendredi, le port. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-05",
    "Le poisson et le gâteau",
    "Raphaël veut le gâteau de samedi. Vendredi au port, l'étal range. Samedi, l'œuf roule. Il le rattrape. Le gâteau dore.",
    "- Deux jours vécus : vendredi, samedi.\n"
    "- Désir : le gâteau. Imprévu : étal qui range, œuf qui roule.\n"
    "- Troupe D16 : Raphaël, maman. Question : samedi.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-06  N2  Chouchou, maman — lundi chaussettes, mardi flaque
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-06",
    "Chouchou veut la grande flaque de la cour. Lundi, les chaussettes rouges sèchent, encore mouillées. Mardi, une chaussette reste humide. Elle attend un peu. Puis la flaque.",
    "La flaque de mardi",
    "Chouchou, maman",
    "entrée le lundi, cour le mardi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les chaussettes rouges dansent sur la corde.",
            "narrateur|Une goutte tombe du talon.",
            "narrateur|Elle fait un rond sur le carrelage.",
            "narrateur|Le radiateur tic tout doux.",
            "maman|Tu as vu la goutte, Chouchou ?",
            "enfant-f|Elle tombe encore.",
            "maman|C'est lundi.",
            "maman|Lundi, les chaussettes sèchent.",
            "narrateur|En ce moment, Chouchou touche une chaussette.",
            "narrateur|Elle est froide, encore lourde d'eau.",
            "enfant-f|Je veux la flaque.",
            "enfant-f|La grande, dans la cour.",
            "maman|Tes chaussettes sont mouillées.",
            "maman|Demain, c'est mardi.",
            "maman|Mardi, elles seront sèches.",
            "enfant-f|On y va maintenant ?",
            "maman|Les pieds seraient froids.",
            "narrateur|Chouchou appuie le nez à la vitre.",
            "narrateur|La flaque de la cour brille, ronde.",
            "narrateur|La pluie a cessé.",
            "enfant-f|Elle m'attend.",
            "maman|Elle attend mardi aussi.",
            "maman|La semaine a sept jours.",
            "maman|Quel jour vient après lundi ?",
            "enfant-f|Mardi.",
            "maman|Oui.",
            "narrateur|Une autre goutte tombe.",
            "narrateur|Le rond sur le carrelage s'agrandit.",
            "enfant-f|Je peux les aider à sécher ?",
            "maman|On les rapproche du radiateur.",
            "narrateur|Chouchou tend la corde un peu.",
            "narrateur|Les chaussettes rouges dansent plus près.",
            "maman|Merci, Chouchou.",
            "narrateur|Le tic du radiateur continue.",
            "narrateur|La corde tremble encore un peu.",
            "enfant-f|Demain, je saute.",
            "maman|Mardi, oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après lundi, quel jour vient ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, le carrelage est sec.",
            "narrateur|Une chaussette est légère.",
            "narrateur|L'autre reste un peu froide.",
            "maman|C'est mardi, Chouchou.",
            "enfant-f|Celle-là est encore humide.",
            "maman|On la pose un moment ici.",
            "narrateur|Chouchou pose la chaussette sur le radiateur.",
            "narrateur|Le tissu fume un tout petit peu.",
            "enfant-f|Elle sèche.",
            "maman|Puis les bottes.",
            "narrateur|Les bottes jaunes attendent sous le banc.",
            "narrateur|Chouchou enfile la sèche d'abord.",
            "narrateur|Puis l'autre, enfin tiède.",
            "enfant-f|Je suis prête.",
            "maman|La flaque est encore là.",
            "maman|Tu as attendu mardi.",
            "narrateur|La poignée de la porte est froide.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La cour brille encore.",
            "narrateur|La flaque est ronde, un peu brune.",
            "maman|Lundi, les chaussettes.",
            "maman|Mardi, la flaque.",
            "enfant-f|J'y vais.",
            "narrateur|Chouchou pose un pied.",
            "narrateur|L'eau fait plouf, tout doux.",
            "enfant-f|Elle est froide !",
            "maman|Les bottes tiennent.",
            "narrateur|Elle pose l'autre pied.",
            "narrateur|Deux ronds s'ouvrent dans l'eau.",
            "enfant-f|Je suis au milieu.",
            "maman|Oui.",
            "maman|Tes chaussettes sont sèches, dedans.",
            "narrateur|Une feuille tourne à la surface.",
            "narrateur|Chouchou la pousse du bout de la botte.",
            "enfant-f|Encore un plouf.",
            "maman|Encore un, tout doux.",
            "narrateur|Les bottes jaunes ont des gouttes.",
            "narrateur|La cour sent la terre mouillée.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Les bottes jaunes sèchent près de la porte.",
            "enfant-f|J'ai eu ma flaque.",
            "maman|Oui.",
            "maman|Lundi la corde, mardi l'eau.",
            "narrateur|Les chaussettes rouges pendent, enfin légères.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "mardi",
        "accepted_examples": "mardi | le mardi | c'est mardi",
        "retry_prompt": "Lundi, les chaussettes sèchent. Quel jour vient après ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-06",
    "La flaque de mardi",
    "Chouchou veut la flaque. Lundi les chaussettes gouttent. Mardi une reste humide. Elle attend. Puis plouf.",
    "- Deux jours vécus : lundi, mardi.\n"
    "- Désir : la flaque. Imprévu : chaussette encore humide.\n"
    "- Troupe D16 : Chouchou, maman. Question : mardi.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.SEM.001-07  N3  Victorino, papa — pluie, puis samedi de soleil
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.001-07",
    "Victorino veut poser son bateau de bois sur la fontaine du square. La pluie dure. Mardi encore, vendredi le seau déborde. Samedi le soleil. Le bateau a une fente. Ils collent une feuille. Il flotte.",
    "Le bateau de samedi",
    "Victorino, papa",
    "maison sous la pluie, puis square le samedi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les tuiles luisent comme des dos de poissons.",
            "narrateur|Un seau sous la descente d'eau déborde tout doux.",
            "narrateur|L'entrée sent la laine mouillée.",
            "narrateur|Le bateau de bois attend sur le rebord.",
            "papa|Tu as entendu le seau, Victorino ?",
            "enfant-m|Il déborde.",
            "papa|Mardi, la pluie encore.",
            "papa|Vendredi, le seau était déjà plein.",
            "narrateur|En ce moment, Victorino prend le bateau.",
            "narrateur|Le bois est froid, un peu rêche.",
            "enfant-m|Je veux la fontaine.",
            "enfant-m|Mon bateau dessus.",
            "papa|Sous la pluie, le square est trop mouillé.",
            "enfant-m|On y va quand même ?",
            "papa|On attend un jour de soleil.",
            "papa|Samedi, peut-être.",
            "narrateur|Victorino souffle sur la voile de papier.",
            "narrateur|La voile est un peu gondolée.",
            "enfant-m|Il s'ennuie, le bateau.",
            "papa|La semaine a sept jours.",
            "papa|Un jour de soleil va venir.",
            "narrateur|Une goutte frappe la vitre.",
            "narrateur|Puis une autre.",
            "enfant-m|Encore la pluie.",
            "papa|Oui.",
            "papa|On range le bateau au sec.",
            "narrateur|Victorino le pose près du radiateur.",
            "narrateur|Le bois commence à sentir le chaud.",
            "papa|Quel jour on essaie, si le soleil vient ?",
            "enfant-m|Samedi.",
            "papa|Oui.",
            "narrateur|Le seau, dehors, chante encore.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le soleil est revenu.",
            "narrateur|Quel jour est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lendemain, un carré de soleil pose sur le bateau.",
            "narrateur|Les tuiles sèchent, une à une.",
            "papa|C'est samedi, Victorino.",
            "papa|Le jour de soleil.",
            "enfant-m|La fontaine !",
            "papa|On y va.",
            "narrateur|Ils marchent vers le square.",
            "narrateur|Les flaques du chemin brillent encore.",
            "narrateur|Victorino tient le bateau contre lui.",
            "narrateur|Au bord de la fontaine, il s'arrête.",
            "enfant-m|Il y a une fente.",
            "papa|Le bois a trop attendu au sec, puis au froid.",
            "narrateur|Une fente mince court sous la coque.",
            "enfant-m|Il va couler.",
            "papa|On peut coller une feuille.",
            "narrateur|Victorino choisit une feuille plate.",
            "narrateur|Papa l'appuie sous la coque, tout doux.",
            "enfant-m|Elle tient ?",
            "papa|On essaie.",
            "papa|Merci, Victorino.",
            "papa|Tu as choisi la feuille.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Victorino pose le bateau sur l'eau.",
            "narrateur|L'eau de la fontaine est froide, très claire.",
            "enfant-m|Il flotte !",
            "papa|La feuille tient.",
            "narrateur|Le bateau tourne, tout lent.",
            "narrateur|La voile de papier se gonfle un peu.",
            "papa|Mardi la pluie.",
            "papa|Vendredi le seau.",
            "papa|Samedi le soleil.",
            "enfant-m|Et mon bateau.",
            "papa|Oui.",
            "narrateur|Une goutte tombe encore d'un arbre.",
            "narrateur|Elle fait un rond, loin du bateau.",
            "enfant-m|Il n'a pas coulé.",
            "papa|Tu as attendu le bon jour.",
            "narrateur|Le seau, à la maison, ne chante plus.",
            "enfant-m|On le reprend ?",
            "papa|Encore un tour.",
            "narrateur|Le bateau revient vers la main de Victorino.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le bateau sèche sur le rebord, au soleil.",
            "enfant-m|Il a flotté.",
            "papa|Oui.",
            "papa|Samedi a tenu sa promesse.",
            "narrateur|La feuille collée brille encore, toute plate.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "samedi",
        "accepted_examples": "samedi | le samedi | c'est samedi | le soleil",
        "retry_prompt": "La pluie est partie. Le soleil est là. Quel jour ?",
    },
)
relecture(
    "ATOM-TMP.SEM.001-07",
    "Le bateau de samedi",
    "Victorino veut la fontaine. Pluie. Samedi soleil, fente dans le bois. Une feuille sous la coque. Il flotte.",
    "- Quelques jours en dialogue (mardi, vendredi, samedi), pas une liste de sept.\n"
    "- Désir : le bateau sur la fontaine. Imprévu : fente.\n"
    "- Troupe D16 : Victorino, papa. Question : samedi.",
)

