#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-SEC.RUE.002-01 à 07."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

ROOT = Path(__file__).resolve().parent

EX = "feu vert | la main | avec maman | avec papa | avec l'adulte | attendre | le vert"


def story(sid, fil, title, chars, setting, scripts, sons, retry, vecu, notes):
    if (ROOT / sid / "merged.json").exists():
        print(f"skip {sid}")
        return
    q = {
        "expected_answer": "feu vert",
        "accepted_examples": EX,
        "retry_prompt": retry,
    }
    write_story(sid, fil, title, chars, setting, scripts, sons, q)
    relecture(sid, title, vecu, notes)


# ---------------------------------------------------------------------------
# 01 N1 Raphaël, maman — village, platane, pain du four, ballon, feu
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-01",
    "Le platane tremble. Raphaël veut le pain du four. Un ballon roule vers la bordure. Il serre la main, attend le vert. Le pain sent encore.",
    "Le pain du platane",
    "Raphaël, maman",
    "village, platane, chemin vers la boulangerie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le platane du village tremble un peu.",
            "narrateur|Ses feuilles jaunes tapent le banc.",
            "narrateur|L'air sent le pain du four.",
            "narrateur|Une fumée tiède sort tout doux.",
            "narrateur|Le soleil est bas, presque orange.",
            "narrateur|Un oiseau picore près du tronc.",
            "narrateur|Raphaël vit ici, avec maman.",
            "narrateur|La maison sent encore la confiture.",
            "narrateur|Un sac en toile pend au crochet.",
            "enfant-m|Maman, ça sent le pain !",
            "maman|Oui.",
            "maman|Le four est encore chaud.",
            "maman|On va chercher le pain ?",
            "enfant-m|Oui, maman.",
            "narrateur|En ce moment, Raphaël prend son manteau.",
            "narrateur|Le manteau sent la laine.",
            "maman|Tu mets tes chaussures ?",
            "narrateur|Raphaël enfile la gauche.",
            "narrateur|Puis la droite, tout doucement.",
            "narrateur|Les lacets font un petit bruit.",
            "maman|Tu as fini tes chaussures ?",
            "enfant-m|Oui, maman.",
            "narrateur|Maman tend la main ouverte.",
            "enfant-m|Je prends ta main.",
            "maman|Merci, Raphaël.",
            "narrateur|Dehors, le platane fait une ombre ronde.",
            "narrateur|Ils marchent sur le trottoir.",
            "narrateur|Des feuilles craquent sous les pas.",
            "narrateur|Un volet claque, tout loin.",
            "narrateur|Ils passent près de la fontaine.",
            "narrateur|L'eau chante, toute fine.",
            "enfant-m|Elle chante !",
            "maman|Oui.",
            "maman|On reste sur le trottoir.",
            "narrateur|La boulangerie est un peu plus loin.",
            "enfant-m|J'ai faim de pain.",
            "maman|Bientôt.",
            "narrateur|Le bord gris arrive, tout net.",
            "narrateur|Une pierre marque la bordure.",
            "narrateur|Un ballon rouge roule vers la bordure.",
            "narrateur|Raphaël ouvre les yeux tout grand.",
            "enfant-m|Le ballon !",
            "maman|On reste sur le trottoir.",
            "maman|Tu serres ma main ?",
            "narrateur|Raphaël serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|Le ballon s'arrête contre la pierre.",
            "narrateur|Il tremble, puis ne bouge plus.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "maman|On attend le vert.",
            "narrateur|Raphaël regarde le feu piéton.",
            "narrateur|Une voiture passe tout doucement.",
            "narrateur|Le sac de maman tape la hanche.",
            "enfant-m|Il est long, le rouge.",
            "maman|On attend ensemble.",
            "narrateur|Le pain sent encore, tout près.",
            "narrateur|Raphaël sent le four dans l'air.",
            "narrateur|Ses doigts restent dans la main.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "maman|Feu vert.",
            "maman|On avance ensemble.",
            "narrateur|Ils marchent, main dans la main.",
            "narrateur|La cloche de la porte tinte.",
            "narrateur|La boulangerie est chaude, dorée.",
            "enfant-m|Le pain !",
            "maman|Tu le prends ?",
            "narrateur|Raphaël tient le pain tiède.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël attend avec maman.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël a serré la main.",
            "narrateur|Il a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "maman|Tu as attendu le vert ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le ballon dort encore contre la pierre.",
            "narrateur|La main de maman est chaude.",
            "narrateur|Le pain pèse un peu, tout doux.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils reviennent sous le platane.",
            "narrateur|Raphaël pose le pain sur ses genoux.",
            "narrateur|La croûte est un peu dorée.",
            "enfant-m|Ça sent le four.",
            "maman|Oui.",
            "maman|Tu casses un bout ?",
            "narrateur|Un bout craque, tout doux.",
            "narrateur|Des miettes tombent sur le manteau.",
            "narrateur|Les feuilles jaunes bougent encore.",
            "enfant-m|C'est bon.",
            "maman|On rentre après ?",
            "enfant-m|Encore un bout.",
            "narrateur|L'oiseau picore une miette.",
            "narrateur|La fontaine chante toujours.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Raphaël souffle sur la mie chaude.",
            "narrateur|L'ombre du platane les couvre.",
            "enfant-m|Le pain est à nous.",
            "maman|Oui.",
            "narrateur|Le pain sent encore le four.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    "Il serre la main. Il attend le feu vert. Que fait Raphaël ?",
    "Raphaël veut le pain du four. Un ballon roule vers la bordure. Il serre la main, attend le vert. Ils croquent sous le platane.",
    "- Désir : le pain, pas la leçon.\n"
    "- Imprévu : le ballon. POS-001 : il reste sur le trottoir, main serrée.\n"
    "- Fin : mie chaude, platane. Troupe : Raphaël, maman.",
)

# ---------------------------------------------------------------------------
# 02 N3 Sarah, Chouchou, maman — marché, auvent mouillé, deux rues, feu ×2
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-02",
    "Sous l'auvent mouillé, Sarah et Chouchou rentrent du marché. Deux rues. Un citron roule. Elles serrent la main, attendent le vert deux fois.",
    "L'auvent mouillé",
    "Sarah, Chouchou, maman",
    "marché sous un auvent mouillé, deux rues vers la maison",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'auvent du marché goutte encore.",
            "narrateur|Une goutte tombe sur une caisse d'oranges.",
            "narrateur|La toile mouillée sent l'eau et le citron.",
            "narrateur|Sarah tient un sac de toile, déjà un peu lourd.",
            "narrateur|Chouchou marche à côté, capuche encore humide.",
            "narrateur|Maman porte le second sac, plus rond.",
            "maman|Tu as vu la goutte sur l'orange, Sarah ?",
            "enfant-f|Elle brille.",
            "copine|Moi, je veux un citron.",
            "maman|On en prend un, alors.",
            "narrateur|En ce moment, Sarah pose le citron dans le sac.",
            "narrateur|Il est froid, un peu rêche.",
            "enfant-f|On rentre ?",
            "maman|Oui.",
            "maman|On marche sur le trottoir.",
            "narrateur|Elles quittent l'auvent.",
            "narrateur|Le pavé est sombre et luisant.",
            "narrateur|Une orange roule dans le sac, tout doux.",
            "copine|Ça sent bon.",
            "narrateur|Le premier passage arrive, tout large.",
            "maman|On s'arrête.",
            "maman|Tu donnes la main ?",
            "narrateur|Sarah donne la main.",
            "narrateur|Chouchou prend l'autre main.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "maman|On attend le vert.",
            "narrateur|Un vélo glisse au loin, sans bruit.",
            "enfant-f|Il est long, le rouge.",
            "maman|On attend ensemble.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "maman|Feu vert.",
            "maman|On avance ensemble.",
            "narrateur|Elles avancent avec maman, sans se lâcher.",
            "narrateur|Le sac tape la jambe de Sarah.",
            "narrateur|Une deuxième rue s'ouvre, plus étroite.",
            "narrateur|Un bus souffle au loin.",
            "narrateur|Le citron glisse du sac.",
            "narrateur|Il roule vers la bordure.",
            "copine|Le citron !",
            "copine|Je le prends !",
            "maman|On reste sur le trottoir.",
            "maman|Sarah, tu serres ma main ?",
            "narrateur|Sarah serre la main.",
            "narrateur|Elle pose les pieds au bord, et elle attend.",
            "narrateur|Chouchou s'arrête aussi, capuche trempée.",
            "narrateur|Le citron s'immobilise contre une feuille mouillée.",
            "narrateur|Le petit bonhomme est rouge, encore.",
            "maman|On attend le vert.",
            "maman|Merci, Sarah.",
            "enfant-f|J'attends.",
            "copine|Moi aussi.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah est au passage, avec maman.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah a serré la main.",
            "narrateur|Elle a attendu le feu vert.",
            "narrateur|Chouchou a attendu aussi, sur le trottoir.",
            "maman|Vous avez attendu le vert ?",
            "enfant-f|Oui, maman.",
            "copine|Oui.",
            "narrateur|Le citron brille encore contre la feuille.",
            "narrateur|Les sacs sentent l'auvent mouillé.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le petit bonhomme devient vert.",
            "maman|Feu vert.",
            "maman|On avance ensemble.",
            "narrateur|Sarah ramasse le citron, sur le trottoir.",
            "narrateur|Il est froid et un peu luisant.",
            "copine|Il est à nous.",
            "enfant-f|On le met dans le sac.",
            "narrateur|Elles avancent avec maman jusqu'à la porte.",
            "narrateur|La clé fait un petit clic.",
            "maman|Vous posez les sacs ?",
            "enfant-f|Oui.",
            "narrateur|Les oranges roulent dans le saladier.",
            "narrateur|Ça sent le marché, encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sarah frotte une orange contre sa joue.",
            "narrateur|La peau est froide, un peu cireuse.",
            "copine|Ça sent l'auvent.",
            "maman|Oui.",
            "narrateur|La toile mouillée sent encore l'orange.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    "Elle donne la main. Elle attend le feu vert. Que fait Sarah ?",
    "Sarah et Chouchou rentrent du marché. Deux rues. Un citron roule. Elles attendent le vert deux fois. Les oranges sentent l'auvent.",
    "- Désir : rentrer avec oranges et citron.\n"
    "- Deux feux. POS-001 : rester sur le trottoir, main tenue.\n"
    "- Troupe : Sarah, Chouchou (copine), maman. Fin : peau d'orange froide.",
)

# ---------------------------------------------------------------------------
# 03 N3 Amir, papa — châtaignier, école, feu ×2
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-03",
    "Le châtaignier jette des ombres. Amir veut montrer une châtaigne à l'école. Deux rues. La châtaigne roule. Il serre la main, attend le vert deux fois.",
    "Le châtaignier d'Amir",
    "Amir, papa",
    "chemin sous le châtaignier vers l'école",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le châtaignier jette des ombres longues.",
            "narrateur|Une bogue éclatée brille dans l'herbe.",
            "narrateur|L'air sent la feuille mouillée et le bois.",
            "narrateur|Amir glisse une châtaigne lisse dans sa poche.",
            "narrateur|Elle est froide, un peu luisante.",
            "narrateur|Le cartable tape sa hanche, tout rythmé.",
            "papa|Tu as pris ta châtaigne, Amir ?",
            "enfant-m|Oui, papa.",
            "enfant-m|Je la montre à l'école.",
            "papa|Elle est belle.",
            "narrateur|En ce moment, Amir donne la main.",
            "narrateur|La main de papa est chaude, un peu rêche.",
            "papa|On marche sur le trottoir.",
            "narrateur|Ils passent sous les branches basses.",
            "narrateur|Une feuille tourne, puis se pose.",
            "enfant-m|Elle tourne !",
            "papa|Oui.",
            "narrateur|Le premier passage arrive près du kiosque.",
            "papa|On s'arrête.",
            "papa|Tu serres ma main ?",
            "narrateur|Amir serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|Le petit bonhomme est rouge.",
            "papa|On attend le vert.",
            "narrateur|Un camion passe, tout lent.",
            "enfant-m|Il fait du vent.",
            "papa|On attend ensemble.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "papa|Feu vert.",
            "papa|On avance ensemble.",
            "narrateur|Ils avancent avec papa, sans se lâcher.",
            "narrateur|Le cartable se balance encore.",
            "narrateur|Une deuxième rue coupe le chemin de l'école.",
            "narrateur|La châtaigne glisse de la poche.",
            "narrateur|Elle roule vers la bordure.",
            "enfant-m|Ma châtaigne !",
            "papa|On reste sur le trottoir.",
            "papa|Tu serres ma main ?",
            "narrateur|Amir serre plus fort.",
            "narrateur|Il pose les pieds au bord, et il attend.",
            "narrateur|La châtaigne s'arrête contre une racine, sur le trottoir.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "papa|On attend le vert.",
            "papa|Merci, Amir.",
            "enfant-m|J'attends.",
            "narrateur|Le portail de l'école brille, un peu plus loin.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir est au passage, avec papa.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir a serré la main.",
            "narrateur|Il a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "papa|Tu as attendu le vert ?",
            "enfant-m|Oui, papa.",
            "narrateur|La châtaigne brille encore contre la racine.",
            "narrateur|Le cartable sent le crayon et le bois.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le petit bonhomme devient vert.",
            "papa|Feu vert.",
            "papa|On avance ensemble.",
            "narrateur|Amir ramasse la châtaigne, sur le trottoir.",
            "narrateur|Elle est froide, toute lisse.",
            "enfant-m|Elle est à moi.",
            "papa|Tu la remets dans la poche ?",
            "enfant-m|Oui.",
            "narrateur|Ils avancent avec papa jusqu'au portail.",
            "narrateur|La cour sent les feuilles et la craie.",
            "enfant-m|Je la montre.",
            "papa|Oui.",
            "narrateur|Une cloche d'école tinte, toute claire.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Amir touche la châtaigne dans sa poche.",
            "narrateur|Elle tiédit un peu contre le tissu.",
            "enfant-m|Elle est chaude maintenant.",
            "papa|Oui.",
            "narrateur|Une châtaigne tiède reste dans la poche.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    "Il serre la main. Il attend le feu vert. Que fait Amir ?",
    "Amir veut montrer sa châtaigne à l'école. Deux rues. Elle roule vers la bordure. Il attend le vert deux fois. Elle tiédit dans la poche.",
    "- Désir : la châtaigne à l'école.\n"
    "- Deux feux. POS-001 : ramasser sur le trottoir, main tenue.\n"
    "- Troupe : Amir, papa. Fin : châtaigne tiède.",
)

# ---------------------------------------------------------------------------
# 04 N1 Mila, maman — port, mâts, goéland, feu
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-04",
    "Un goéland crie. Mila veut la galette du port. Le ruban vole vers la bordure. Elle serre la main, attend le vert. Le sel reste sur les lèvres.",
    "Le goéland du port",
    "Mila, maman",
    "quai du port, mâts au loin, boulangerie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un goéland crie au-dessus des mâts.",
            "narrateur|Les mâts sont minces, tout loin.",
            "narrateur|L'air sent le sel et le pain.",
            "narrateur|Une corde frappe un mât, toc toc.",
            "narrateur|L'eau clignote, toute plate.",
            "narrateur|Mila vit ici, près du port.",
            "narrateur|Son manteau sent encore le vent.",
            "enfant-f|Maman, le goéland !",
            "maman|Oui.",
            "maman|Il a un bec jaune.",
            "maman|On va chercher la galette ?",
            "enfant-f|Oui, maman.",
            "narrateur|En ce moment, Mila prend le ruban.",
            "narrateur|Le ruban bleu vole un peu.",
            "maman|Tu mets ton bonnet ?",
            "enfant-f|Il chatouille.",
            "maman|Il te tient chaud.",
            "narrateur|Maman tend la main.",
            "enfant-f|Je prends ta main.",
            "maman|Merci, Mila.",
            "narrateur|Elles marchent sur le trottoir du quai.",
            "narrateur|Les dalles sont froides et râpeuses.",
            "narrateur|Un bateau cliquette, tout loin.",
            "enfant-f|J'entends l'eau.",
            "maman|On reste sur le trottoir.",
            "narrateur|La boulangerie du port est plus loin.",
            "enfant-f|La galette est chaude ?",
            "maman|Oui.",
            "maman|Bientôt.",
            "narrateur|Le bord du quai arrive, tout blanc.",
            "narrateur|Une chaîne froide marque la bordure.",
            "narrateur|Le vent pousse le ruban bleu.",
            "narrateur|Le ruban vole vers la bordure.",
            "enfant-f|Mon ruban !",
            "maman|On reste sur le trottoir.",
            "maman|Tu serres ma main ?",
            "narrateur|Mila serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|Le ruban s'accroche à la chaîne.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "maman|On attend le vert.",
            "narrateur|Mila regarde le feu piéton.",
            "narrateur|Le goéland glisse, tout blanc.",
            "narrateur|Une voiture passe tout doucement.",
            "enfant-f|Il crie encore.",
            "maman|On attend ensemble.",
            "narrateur|Le pain du port sent, tout près.",
            "narrateur|Mila sent le beurre dans l'air.",
            "narrateur|Ses doigts restent dans la main.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "maman|Feu vert.",
            "maman|On avance ensemble.",
            "narrateur|Elles marchent, main dans la main.",
            "narrateur|La clochette de la porte tinte.",
            "narrateur|La galette est ronde et dorée.",
            "enfant-f|Elle est chaude !",
            "maman|Tu la tiens ?",
            "narrateur|Mila tient la galette tiède.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila attend avec maman.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila a serré la main.",
            "narrateur|Elle a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "maman|Tu as attendu le vert ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le ruban bleu dort sur la chaîne.",
            "narrateur|La galette chauffe les paumes.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles s'assoient sur le banc du quai.",
            "narrateur|Mila souffle sur la galette.",
            "narrateur|Le beurre brille un peu.",
            "enfant-f|Ça sent le sel.",
            "maman|Oui.",
            "maman|Tu mords un bout ?",
            "narrateur|Un bout craque, tout doux.",
            "narrateur|Des miettes tombent sur le manteau.",
            "narrateur|Le goéland les regarde, puis part.",
            "enfant-f|Il s'envole.",
            "maman|On ramasse le ruban ?",
            "enfant-f|Sur le trottoir.",
            "narrateur|Maman décroche le ruban, tout près.",
            "narrateur|Le vent sent encore le large.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Mila lèche une miette salée.",
            "narrateur|Les mâts bougent un tout petit peu.",
            "enfant-f|La galette est à nous.",
            "maman|Oui.",
            "narrateur|Le goéland glisse au-dessus des mâts.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    "Elle serre la main. Elle attend le feu vert. Que fait Mila ?",
    "Mila veut la galette du port. Le ruban vole vers la bordure. Elle attend le vert. Mie salée, mâts au loin.",
    "- Désir : la galette, pas la leçon.\n"
    "- Imprévu : le ruban. POS-001 : rester sur le trottoir.\n"
    "- Troupe : Mila, maman. Fin : goéland et mâts.",
)

# ---------------------------------------------------------------------------
# 05 N1 Nino, papa — village de montagne, cloche, feu
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-05",
    "Une cloche lointaine traverse la vallée. Nino veut le pain de seigle. Une pomme de pin roule. Il serre la main, attend le vert. La cloche revient.",
    "La cloche de la montagne",
    "Nino, papa",
    "village de montagne, chemin vers la boulangerie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une cloche lointaine traverse la vallée.",
            "narrateur|L'air est froid, un peu piquant.",
            "narrateur|Les sapins sentent la résine.",
            "narrateur|Un toit d'ardoise brille, tout bas.",
            "narrateur|La fumée d'un four sort tout droit.",
            "narrateur|Nino vit ici, avec papa.",
            "narrateur|Son bonnet gratte un peu les oreilles.",
            "enfant-m|Papa, j'entends la cloche !",
            "papa|Oui.",
            "papa|Elle vient du clocher.",
            "papa|On va chercher le pain ?",
            "enfant-m|Le pain de seigle.",
            "narrateur|En ce moment, Nino boutonne son manteau.",
            "narrateur|Les boutons sont froids et ronds.",
            "papa|Tu mets tes gants ?",
            "enfant-m|Ils sont rudes.",
            "papa|Ils te tiennent chaud.",
            "narrateur|Papa tend la main.",
            "enfant-m|Je prends ta main.",
            "papa|Merci, Nino.",
            "narrateur|Ils marchent sur le trottoir étroit.",
            "narrateur|La pierre est grise, un peu rugueuse.",
            "narrateur|Une gouttière fait tic, tout lent.",
            "enfant-m|Ça sent le bois.",
            "papa|On reste sur le trottoir.",
            "narrateur|La boulangerie est plus bas, au virage.",
            "enfant-m|Le pain est chaud ?",
            "papa|Oui.",
            "papa|Bientôt.",
            "narrateur|Le bord du trottoir arrive, tout net.",
            "narrateur|Une pierre grise marque la bordure.",
            "narrateur|Une pomme de pin roule vers la bordure.",
            "narrateur|Elle fait un bruit de bois sec.",
            "enfant-m|La pomme de pin !",
            "papa|On reste sur le trottoir.",
            "papa|Tu serres ma main ?",
            "narrateur|Nino serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|La pomme de pin s'arrête contre une pierre.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "papa|On attend le vert.",
            "narrateur|Nino regarde le feu piéton.",
            "narrateur|La cloche revient, plus douce.",
            "narrateur|Une voiture passe tout doucement.",
            "enfant-m|Elle chante encore.",
            "papa|On attend ensemble.",
            "narrateur|Le seigle sent encore, tout près.",
            "narrateur|Nino sent le four dans l'air froid.",
            "narrateur|Ses doigts restent dans la main.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "papa|Feu vert.",
            "papa|On avance ensemble.",
            "narrateur|Ils marchent, main dans la main.",
            "narrateur|La cloche de la porte tinte.",
            "narrateur|Le pain de seigle est sombre et chaud.",
            "enfant-m|Il est lourd !",
            "papa|Tu le tiens ?",
            "narrateur|Nino tient le pain contre lui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino attend avec papa.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino a serré la main.",
            "narrateur|Il a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "papa|Tu as attendu le vert ?",
            "enfant-m|Oui, papa.",
            "narrateur|La pomme de pin dort contre la pierre.",
            "narrateur|Le pain chauffe le manteau.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils s'assoient sur le muret.",
            "narrateur|Nino pose le pain sur ses genoux.",
            "narrateur|La croûte est un peu rêche.",
            "enfant-m|Ça sent le seigle.",
            "papa|Oui.",
            "papa|Tu casses un bout ?",
            "narrateur|Un bout craque, tout sec.",
            "narrateur|Des miettes tombent sur le gant.",
            "narrateur|Les sapins bougent un peu.",
            "enfant-m|C'est bon.",
            "papa|On ramasse la pomme de pin ?",
            "enfant-m|Sur le trottoir.",
            "narrateur|Papa la pose dans la poche de Nino.",
            "narrateur|Elle sent la résine, toute vive.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nino souffle sur la mie chaude.",
            "narrateur|La vallée est calme, toute bleue.",
            "enfant-m|Le pain est à nous.",
            "papa|Oui.",
            "narrateur|La cloche lointaine traverse encore la vallée.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    "Il serre la main. Il attend le feu vert. Que fait Nino ?",
    "Nino veut le pain de seigle. Une pomme de pin roule. Il attend le vert. Mie chaude, cloche dans la vallée.",
    "- Désir : le pain de seigle.\n"
    "- Imprévu : pomme de pin. POS-001 : rester sur le trottoir.\n"
    "- Troupe : Nino, papa. Fin : cloche lointaine.",
)

# ---------------------------------------------------------------------------
# 06 N1 Nina, maman — ville, tram, trottoir luisant, feu
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-06",
    "Le tram glisse. Nina veut les fraises du marché. Un gant rouge glisse vers la bordure. Elle serre la main, attend le vert. Le trottoir luisant reste.",
    "Le tram luisant",
    "Nina, maman",
    "ville après la pluie, tram, marché",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le tram glisse sur les rails mouillés.",
            "narrateur|Le trottoir luisant sent la pluie.",
            "narrateur|Une flaque tient le ciel, tout petit.",
            "narrateur|L'air sent le métal et la fraise.",
            "narrateur|Un store rouge claque au marché.",
            "narrateur|Nina vit ici, avec maman.",
            "narrateur|Son manteau fait un bruit de tissu mouillé.",
            "enfant-f|Maman, le tram !",
            "maman|Oui.",
            "maman|Il file tout doux.",
            "maman|On va chercher les fraises ?",
            "enfant-f|Oui, maman.",
            "narrateur|En ce moment, Nina enfile un gant rouge.",
            "narrateur|L'autre gant pend, encore vide.",
            "maman|Tu mets le second ?",
            "enfant-f|Il est un peu grand.",
            "maman|Il te tiendra chaud.",
            "narrateur|Maman tend la main.",
            "enfant-f|Je prends ta main.",
            "maman|Merci, Nina.",
            "narrateur|Elles marchent sur le trottoir luisant.",
            "narrateur|Les pas font un bruit collé.",
            "narrateur|Le tram tinte, plus loin.",
            "enfant-f|Il chante.",
            "maman|On reste sur le trottoir.",
            "narrateur|Le marché est un peu plus loin.",
            "enfant-f|Les fraises sont rouges ?",
            "maman|Oui.",
            "maman|Bientôt.",
            "narrateur|Le bord du trottoir arrive, tout net.",
            "narrateur|Une ligne blanche marque la bordure.",
            "narrateur|Le second gant glisse vers la bordure.",
            "narrateur|Il est rouge sur le gris luisant.",
            "enfant-f|Mon gant !",
            "maman|On reste sur le trottoir.",
            "maman|Tu serres ma main ?",
            "narrateur|Nina serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|Le gant s'arrête contre la ligne blanche.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "maman|On attend le vert.",
            "narrateur|Nina regarde le feu piéton.",
            "narrateur|Le tram passe, tout long.",
            "narrateur|Les vitres brillent, puis s'en vont.",
            "enfant-f|Il est parti.",
            "maman|On attend ensemble.",
            "narrateur|Les fraises sentent encore, tout près.",
            "narrateur|Nina sent le sucré dans l'air.",
            "narrateur|Ses doigts restent dans la main.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "maman|Feu vert.",
            "maman|On avance ensemble.",
            "narrateur|Elles marchent, main dans la main.",
            "narrateur|Le store rouge claque encore.",
            "narrateur|Les fraises sont petites et brillantes.",
            "enfant-f|Elles sentent bon !",
            "maman|Tu portes la barquette ?",
            "narrateur|Nina tient la barquette froide.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina attend avec maman.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina a serré la main.",
            "narrateur|Elle a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "maman|Tu as attendu le vert ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le gant rouge dort sur la ligne.",
            "narrateur|Les fraises parfument les doigts.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles s'abritent sous le store.",
            "narrateur|Nina pose la barquette contre elle.",
            "narrateur|Une fraise laisse un jus rose.",
            "enfant-f|Elle est sucrée.",
            "maman|Oui.",
            "maman|Tu en manges une ?",
            "narrateur|Nina croque, tout doux.",
            "narrateur|Le jus tache un peu le gant.",
            "narrateur|Le trottoir luisant tremble encore.",
            "enfant-f|C'est bon.",
            "maman|On ramasse l'autre gant ?",
            "enfant-f|Sur le trottoir.",
            "narrateur|Maman le ramasse, tout près du bord.",
            "narrateur|Le tram tinte, déjà loin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nina lèche un doigt rose.",
            "narrateur|La flaque tient encore un bout de ciel.",
            "enfant-f|Les fraises sont à nous.",
            "maman|Oui.",
            "narrateur|Le tram file, tout doux, au loin.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    "Elle serre la main. Elle attend le feu vert. Que fait Nina ?",
    "Nina veut les fraises. Un gant glisse. Elle attend le vert. Jus rose, tram au loin.",
    "- Désir : les fraises du marché.\n"
    "- Imprévu : le gant. POS-001 : rester sur le trottoir.\n"
    "- Troupe : Nina, maman. Fin : tram au loin.",
)

# ---------------------------------------------------------------------------
# 07 N1 Aniss, papa — jardin, grille de la rue, feu
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.RUE.002-07",
    "Le thym chauffe. Aniss veut poser son bateau dans le bassin du square. À la grille, un arrosoir bascule. Il serre la main, attend le vert.",
    "La grille du jardin",
    "Aniss, papa",
    "jardin puis grille de la rue vers le square",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le thym du jardin chauffe au soleil.",
            "narrateur|Une abeille visite une fleur violette.",
            "narrateur|La terre sent le chaud et le vert.",
            "narrateur|Un arrosoir bleu est penché.",
            "narrateur|Aniss tient un bateau de bois.",
            "narrateur|Le bateau sent le copeau neuf.",
            "enfant-m|Papa, il flotte ?",
            "papa|Oui.",
            "papa|Au bassin du square.",
            "papa|On y va ?",
            "enfant-m|Oui, papa.",
            "narrateur|En ce moment, Aniss essuie la quille.",
            "narrateur|Le bois est lisse, un peu tiède.",
            "papa|Tu mets tes chaussures ?",
            "narrateur|Aniss enfile la gauche.",
            "narrateur|Puis la droite.",
            "narrateur|Les lacets font un petit bruit.",
            "papa|Tu as fini tes chaussures ?",
            "enfant-m|Oui, papa.",
            "narrateur|Papa tend la main.",
            "enfant-m|Je prends ta main.",
            "papa|Merci, Aniss.",
            "narrateur|Ils passent près des pots d'argile.",
            "narrateur|Le thym frotte le pantalon.",
            "narrateur|La grille de la rue attend, noire.",
            "enfant-m|La grille crisse.",
            "papa|Oui.",
            "narrateur|Papa ouvre la grille, tout lent.",
            "narrateur|L'arrosoir bascule contre le seuil.",
            "narrateur|Un filet d'eau court vers la bordure.",
            "enfant-m|L'eau part !",
            "papa|On reste sur le trottoir.",
            "papa|Tu serres ma main ?",
            "narrateur|Aniss serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "narrateur|L'eau s'arrête dans une fissure.",
            "narrateur|Le bord de la rue est tout proche.",
            "narrateur|Le petit bonhomme est encore rouge.",
            "papa|On attend le vert.",
            "narrateur|Aniss regarde le feu piéton.",
            "narrateur|Le bateau tape un peu sa poche.",
            "narrateur|Une voiture passe tout doucement.",
            "enfant-m|Il veut flotter.",
            "papa|Bientôt.",
            "papa|On attend ensemble.",
            "narrateur|Le square sent l'herbe, tout près.",
            "narrateur|Aniss sent le thym sur ses doigts.",
            "narrateur|Ses doigts restent dans la main.",
            "narrateur|Puis le petit bonhomme devient vert.",
            "papa|Feu vert.",
            "papa|On avance ensemble.",
            "narrateur|Ils marchent, main dans la main.",
            "narrateur|Le portail du square grince.",
            "narrateur|Le bassin brille, tout rond.",
            "enfant-m|L'eau !",
            "papa|Tu poses le bateau ?",
            "narrateur|Aniss pose le bateau sur l'eau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss attend avec papa.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss a serré la main.",
            "narrateur|Il a attendu le feu vert.",
            "narrateur|Ses pieds restaient sur le trottoir.",
            "papa|Tu as attendu le vert ?",
            "enfant-m|Oui, papa.",
            "narrateur|L'arrosoir dort contre le seuil.",
            "narrateur|Le bateau avance, tout lent.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le bateau fait un petit sillage.",
            "narrateur|Aniss souffle, tout doux.",
            "narrateur|L'eau sent le soleil et la pierre.",
            "enfant-m|Il flotte !",
            "papa|Oui.",
            "papa|Tu le rattrapes au bord ?",
            "narrateur|Aniss le prend au rebord du bassin.",
            "narrateur|Le bois est mouillé, plus foncé.",
            "narrateur|Une feuille tourne sur l'eau.",
            "enfant-m|Encore.",
            "papa|On le pose encore ?",
            "enfant-m|Oui.",
            "narrateur|Le bateau repart, tout fier.",
            "narrateur|Les mains d'Aniss sentent le thym.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Aniss essuie le bateau sur son genou.",
            "narrateur|Une goutte tombe dans le bassin.",
            "enfant-m|Il a voyagé.",
            "papa|Oui.",
            "narrateur|Le thym du jardin sent encore le soleil.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    "Il serre la main. Il attend le feu vert. Que fait Aniss ?",
    "Aniss veut faire flotter son bateau. L'arrosoir bascule à la grille. Il attend le vert. Le bateau glisse, le thym reste.",
    "- Désir : le bateau au bassin.\n"
    "- Imprévu : arrosoir. POS-001 : rester sur le trottoir, main tenue.\n"
    "- Troupe : Aniss, papa. Fin : thym au soleil.",
)
