#!/usr/bin/env python3
"""F-NAR-008 — ATOM-VIV.ANI.003-08 + ATOM-VIV.PLA.001-01..07."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.003-08  N2  Sarah, maman — clapier, paille, feuille
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-08",
    "Sarah veut donner une feuille fraîche au lapin. La paille sent le foin. "
    "La bouteille est trop pleine. Avec maman, elle verse tout doux. Le lapin boit, puis croque.",
    "La feuille du clapier",
    "Sarah, maman",
    "jardin, clapier à la fenêtre de paille",
    {
        "CHK_T0000_P0000": [
            "narrateur|La paille du clapier sent le foin chaud.",
            "narrateur|Un carré de soleil pose sur le loquet.",
            "narrateur|Dehors, une abeille passe près du bois.",
            "narrateur|Le jardin sent l'herbe coupée.",
            "narrateur|Sarah vit ici, avec maman.",
            "maman|Tu as vu la petite fenêtre ?",
            "enfant-f|Elle est ouverte, un peu.",
            "narrateur|En ce moment, Sarah s'approche du clapier.",
            "narrateur|Le bois est rêche sous ses doigts.",
            "narrateur|Une oreille rose bouge derrière la paille.",
            "enfant-f|Il est là.",
            "enfant-f|Je veux lui donner une feuille.",
            "maman|Une feuille bien verte ?",
            "enfant-f|Oui.",
            "enfant-f|Et de l'eau, aussi.",
            "narrateur|Le bol de terre est presque vide.",
            "narrateur|Une croûte sèche au fond.",
            "narrateur|Le lapin a le nez poudreux.",
            "maman|Il a soif, je crois.",
            "maman|On va être tout doux ?",
            "enfant-f|Tout doux.",
            "narrateur|Maman tient la bouteille d'eau.",
            "narrateur|Sarah pose la main sur le plastique.",
            "enfant-f|Elle est lourde.",
            "maman|Oui.",
            "maman|On verse ensemble, tout lentement.",
            "narrateur|Sarah penche un peu trop.",
            "narrateur|Une goutte saute sur la paille.",
            "enfant-f|Oh.",
            "maman|Doucement.",
            "maman|La paille n'aime pas le bain.",
            "narrateur|Le lapin recule sous le foin.",
            "narrateur|On ne voit plus que le bout du nez.",
            "enfant-f|Il a peur ?",
            "maman|Il attend.",
            "maman|On reste près de lui ?",
            "enfant-f|Oui, maman.",
            "narrateur|Sarah respire.",
            "narrateur|Sa main redevient lente.",
            "narrateur|L'eau glisse, un fil très mince.",
            "narrateur|Le bol se remplit sans éclabousser.",
            "narrateur|Ça fait un tout petit cloc.",
            "enfant-f|Cloc.",
            "maman|Voilà.",
            "maman|Avec maman, tout doux.",
            "narrateur|Le nez poudreux avance.",
            "narrateur|Les moustaches tremblent.",
            "narrateur|Le lapin boit, par petites gorgées.",
            "enfant-f|Il boit !",
            "maman|Tu as versé avec un adulte.",
            "maman|Merci, Sarah.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah donne l'eau au lapin.",
            "narrateur|Comment, et avec qui ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah a versé tout doux, avec maman.",
            "narrateur|Le bol est plein, pas trop.",
            "narrateur|La paille reste sèche autour.",
            "enfant-f|Il a encore soif ?",
            "maman|Il boit à sa vitesse.",
            "maman|On le regarde, on ne le presse pas.",
            "narrateur|Sarah glisse la feuille verte.",
            "narrateur|Elle passe entre les barreaux.",
            "narrateur|Le bois sent encore le foin.",
            "enfant-f|Prends, petit.",
            "narrateur|Le lapin croque.",
            "narrateur|Ça fait un bruit de salade.",
            "maman|Tu entends ?",
            "enfant-f|Croc, croc.",
            "maman|Tu as été douce.",
            "maman|On referme le loquet ensemble ?",
            "enfant-f|Oui.",
            "narrateur|Sarah pousse le loquet.",
            "narrateur|Il fait un petit clic de bois.",
            "maman|Clic.",
            "narrateur|Une paille reste collée à sa paume.",
            "narrateur|Elle la garde, tout contre le pouce.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le soleil a glissé sur le toit du clapier.",
            "narrateur|L'ombre est plus longue, plus douce.",
            "enfant-f|Il a fini sa feuille.",
            "maman|Il en a encore une, près du bol.",
            "narrateur|Sarah se baisse.",
            "narrateur|Le jardin sent l'herbe et le foin.",
            "maman|Tu veux rester un peu ?",
            "enfant-f|Un peu.",
            "narrateur|Le lapin se lèche la patte.",
            "narrateur|Ses oreilles retombent, calmes.",
            "enfant-f|Il est bien.",
            "maman|Oui.",
            "maman|Parce qu'on a été doux.",
            "narrateur|Sarah pose le front au bois.",
            "narrateur|Le bois est tiède.",
            "narrateur|Dedans, on entend un tout petit souffle.",
            "maman|Tu lui diras bonsoir ?",
            "enfant-f|Bonsoir, lapin.",
            "narrateur|Une abeille passe encore, plus loin.",
            "narrateur|Le loquet tient.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sarah ouvre la main.",
            "narrateur|Le brin de paille sent encore le foin.",
            "enfant-f|Il a bu.",
            "enfant-f|Il a croqué.",
            "maman|Oui.",
            "maman|Avec toi, tout doux.",
            "narrateur|Le foin tiède reste dans sa main.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "avec maman",
        "accepted_examples": "avec maman | avec un adulte | doux | doucement",
        "retry_prompt": "On est doux. On est avec un adulte. Que fait Sarah ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-08",
    "La feuille du clapier",
    "Sarah veut une feuille pour le lapin. La bouteille est trop pleine. "
    "Avec maman, elle verse tout doux. Le lapin boit, puis croque.",
    "- Désir : la feuille, pas la consigne « avec un adulte ».\n"
    "- Imprévu : goutte sur la paille, lapin caché.\n"
    "- Troupe D16 : Sarah, maman. Fin vécue : foin dans la main.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-01  N1  Amir, maman — basilic, pâtes, trop d'eau
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-01",
    "Amir veut l'odeur du basilic sur les pâtes du soir. Le basilic a soif. "
    "Trop d'eau, la soucoupe déborde. Ils vident. Une feuille se redresse.",
    "L'odeur des pâtes d'Amir",
    "Amir, maman",
    "cuisine, basilic à la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le rebord de la fenêtre est tiède.",
            "narrateur|Un carré de soleil pose sur le pot.",
            "narrateur|Ça sent la sauce tomate.",
            "narrateur|La casserole chante tout bas.",
            "narrateur|Les pâtes du soir attendent.",
            "narrateur|Amir vit ici, avec maman.",
            "maman|Tu as vu le basilic ?",
            "enfant-m|Il est tout mou.",
            "narrateur|Les feuilles pendent, un peu.",
            "narrateur|La terre est claire, presque grise.",
            "enfant-m|Je veux son odeur.",
            "enfant-m|Sur les pâtes du soir.",
            "maman|Il a soif, alors.",
            "maman|Tu viens près du pot ?",
            "narrateur|En ce moment, Amir s'approche.",
            "narrateur|Il touche une feuille.",
            "narrateur|La feuille est chaude et molle.",
            "enfant-m|Elle est triste.",
            "maman|Elle a besoin d'eau.",
            "maman|Un peu, pas trop.",
            "narrateur|L'arrosoir bleu attend près de l'évier.",
            "narrateur|Amir le tire par l'anse.",
            "narrateur|L'eau cloche dedans.",
            "enfant-m|C'est lourd.",
            "maman|On verse ensemble ?",
            "enfant-m|Oui, maman.",
            "narrateur|Amir penche l'arrosoir.",
            "narrateur|Maman tient l'anse aussi.",
            "narrateur|L'eau tombe sur la terre.",
            "narrateur|La terre devient sombre.",
            "enfant-m|Elle boit !",
            "maman|Oui.",
            "maman|Tout doux.",
            "narrateur|Une goutte reste sur une feuille.",
            "narrateur|Elle brille, toute ronde.",
            "enfant-m|Une perle.",
            "maman|On verra si c'est assez.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La plante a soif.",
            "narrateur|Que fait Amir avec maman ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir penche encore un peu.",
            "narrateur|L'eau tombe trop vite.",
            "narrateur|La soucoupe se remplit.",
            "enfant-m|Oh.",
            "narrateur|L'eau déborde sur le bois.",
            "maman|Trop d'eau.",
            "maman|On vide la soucoupe ?",
            "enfant-m|Oui.",
            "narrateur|Maman soulève le pot.",
            "narrateur|Amir tient la soucoupe.",
            "narrateur|Elle est froide, toute ronde.",
            "narrateur|Ils versent dans l'évier.",
            "narrateur|Ça fait un petit chhh.",
            "enfant-m|Chhh.",
            "maman|Merci, Amir.",
            "maman|Tu as vidé avec moi.",
            "narrateur|Ils reposent le pot.",
            "narrateur|Une feuille se redresse, un peu.",
            "enfant-m|Elle se lève !",
            "maman|Un peu, oui.",
            "maman|Elle a eu trop d'eau.",
            "maman|Puis juste assez.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le soir arrive dans la cuisine.",
            "narrateur|La vapeur des pâtes est chaude.",
            "enfant-m|On prend une feuille ?",
            "maman|Une seule, la plus grande.",
            "narrateur|Amir pince la tige.",
            "narrateur|La feuille sent fort, tout de suite.",
            "enfant-m|Ça pique le nez !",
            "maman|C'est le basilic.",
            "maman|Tu la poses sur les pâtes ?",
            "enfant-m|Oui.",
            "narrateur|La feuille tombe dans la vapeur.",
            "narrateur|Elle devient brillante.",
            "narrateur|La sauce sent le vert.",
            "maman|Tu as aidé le basilic.",
            "maman|Merci.",
            "enfant-m|Il a bu.",
            "narrateur|Une goutte sèche sur le bois.",
            "narrateur|Le pot reste près de la vitre.",
            "maman|Tu as fini ta fourchette ?",
            "enfant-m|Presque.",
            "narrateur|Amir reprend une pâte.",
            "narrateur|Elle est chaude, un peu glissante.",
            "enfant-m|Encore l'odeur.",
            "maman|Oui.",
            "maman|Le basilic est dans l'assiette.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Amir souffle sur sa fourchette.",
            "narrateur|La vapeur sent le basilic.",
            "enfant-m|Les pâtes du soir.",
            "maman|Oui.",
            "maman|Avec l'odeur que tu voulais.",
            "narrateur|La vapeur des pâtes sent le basilic.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | il arrose | de l'eau | eau",
        "retry_prompt": "Ils versent de l'eau. Que fait Amir ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-01",
    "L'odeur des pâtes d'Amir",
    "Amir veut l'odeur du basilic sur les pâtes. Trop d'eau, la soucoupe déborde. "
    "Ils vident. Une feuille se redresse. Le soir, la vapeur sent le vert.",
    "- Désir : l'odeur sur les pâtes, pas la liste d'arrosage.\n"
    "- Imprévu : trop d'eau, soucoupe, évier.\n"
    "- Troupe D16 : Amir, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-02  N2  Mila, maman — basilic, chenille
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-02",
    "Mila veut sentir une feuille de basilic. Une chenille est dessus. "
    "On regarde, on n'écrase pas. Maman la pose sur une plante sauvage. Puis elles arrosent.",
    "La chenille du basilic",
    "Mila, maman",
    "cuisine puis cour, basilic à la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une mouche tape le carreau de la cuisine.",
            "narrateur|Le carreau vibre, tout petit.",
            "narrateur|Ça sent le pain d'hier, un peu rassis.",
            "narrateur|Le basilic est dans son pot gris.",
            "narrateur|Mila vit ici, avec maman.",
            "maman|Tu veux une feuille pour la tomate ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux la sentir d'abord.",
            "narrateur|En ce moment, Mila se hausse.",
            "narrateur|Ses orteils cherchent le rebord du meuble.",
            "narrateur|Une feuille brille, bien large.",
            "enfant-f|Celle-là.",
            "narrateur|Mila approche le nez.",
            "narrateur|Quelque chose bouge sur le vert.",
            "enfant-f|Il y a un ver !",
            "narrateur|Ce n'est pas un ver.",
            "narrateur|C'est une chenille, toute rayée.",
            "narrateur|Elle avance comme un soufflet.",
            "maman|On la regarde.",
            "maman|On ne l'écrase pas, d'accord ?",
            "enfant-f|Elle mange ma feuille.",
            "maman|Un tout petit bout.",
            "maman|On va lui trouver une autre plante ?",
            "enfant-f|Dehors ?",
            "maman|Dehors, une plante sauvage.",
            "narrateur|Maman glisse un carton sous la feuille.",
            "narrateur|La chenille marche sur le carton.",
            "narrateur|Mila ouvre la porte de la cour.",
            "narrateur|L'air sent la poussière chaude.",
            "narrateur|Une plante rêche pousse contre le mur.",
            "maman|Ici.",
            "maman|Elle a des feuilles plus dures.",
            "narrateur|La chenille glisse sur le vert sauvage.",
            "enfant-f|Elle est partie.",
            "maman|Oui.",
            "maman|Ton basilic a encore soif, tu as vu ?",
            "narrateur|Les feuilles du pot pendent un peu.",
            "narrateur|La terre est claire, presque grise.",
            "enfant-f|Il veut de l'eau.",
            "maman|On rentre l'arrosoir ?",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le basilic a soif.",
            "narrateur|Que fait Mila avec maman ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila tient l'arrosoir à deux mains.",
            "narrateur|Maman pose les doigts sur l'anse.",
            "narrateur|L'eau tombe, un filet mince.",
            "narrateur|La terre devient sombre, tout de suite.",
            "enfant-f|Elle boit.",
            "maman|Oui.",
            "maman|Un peu, pas trop.",
            "narrateur|Une goutte reste sur une feuille.",
            "narrateur|Elle brille comme un grain.",
            "enfant-f|Je peux sentir, maintenant ?",
            "maman|La grande feuille, oui.",
            "narrateur|Mila froisse tout doux le vert.",
            "narrateur|L'odeur saute, poivrée, chaude.",
            "enfant-f|Ça pique !",
            "maman|C'est le basilic.",
            "maman|Merci, Mila.",
            "maman|Tu as regardé la chenille.",
            "maman|Tu n'as pas écrasé.",
            "enfant-f|Elle mange dehors.",
            "maman|Sur sa plante à elle.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman coupe une feuille pour la tomate.",
            "narrateur|Le couteau fait un tout petit clic.",
            "enfant-f|Et la chenille ?",
            "maman|On va voir, si tu veux.",
            "narrateur|Dans la cour, le mur est chaud.",
            "narrateur|La plante sauvage sent l'herbe amère.",
            "enfant-f|Elle est encore là.",
            "narrateur|La chenille mange, très lente.",
            "maman|Chacun sa feuille.",
            "maman|Le basilic pour nous.",
            "maman|Celle-là pour elle.",
            "enfant-f|D'accord.",
            "narrateur|Mila pose un doigt près, sans toucher.",
            "narrateur|La chenille ne s'arrête pas.",
            "maman|On laisse ?",
            "enfant-f|On laisse.",
            "narrateur|Le basilic, derrière la vitre, tient plus droit.",
            "narrateur|Une goutte sèche sur le rebord.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Mila rentre.",
            "narrateur|La tomate attend, rouge, sur l'assiette.",
            "enfant-f|Ça sent le basilic.",
            "maman|Oui.",
            "maman|La feuille que tu voulais.",
            "narrateur|La feuille sent encore le soleil.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | elle arrose | de l'eau | eau",
        "retry_prompt": "Elles versent de l'eau. Que fait Mila ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-02",
    "La chenille du basilic",
    "Mila veut sentir une feuille. Une chenille est dessus. On regarde, on n'écrase pas. "
    "Maman la pose sur une plante sauvage. Elles arrosent. La tomate sent le vert.",
    "- Désir : sentir la feuille, pas la leçon d'arrosage.\n"
    "- Imprévu : chenille, regarder, ne pas écraser.\n"
    "- Troupe D16 : Mila, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-03  N1  Nino, papa — basilic, arrosoir trop lourd
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-03",
    "Nino veut sentir une feuille de basilic. L'arrosoir est trop lourd. "
    "Papa tient l'anse avec lui. Ils versent. La feuille sent fort.",
    "L'arrosoir trop lourd",
    "Nino, papa",
    "cuisine près de la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'évier fait tic, tout doux.",
            "narrateur|Une goutte tombe dans la cuve.",
            "narrateur|Le basilic attend près de la vitre.",
            "narrateur|Ça sent le savon de vaisselle.",
            "narrateur|Nino vit ici, avec papa.",
            "papa|Tu as vu les feuilles ?",
            "enfant-m|Elles pendent.",
            "narrateur|La terre est claire, toute sèche.",
            "enfant-m|Je veux sentir.",
            "enfant-m|Une grande feuille.",
            "papa|Il a soif, d'abord.",
            "papa|Tu prends l'arrosoir ?",
            "narrateur|En ce moment, Nino se baisse.",
            "narrateur|L'arrosoir vert est près du seau.",
            "narrateur|Nino tire l'anse.",
            "narrateur|L'arrosoir ne bouge pas.",
            "enfant-m|Il est trop lourd.",
            "papa|L'eau est dedans.",
            "papa|On tient l'anse ensemble ?",
            "enfant-m|Oui, papa.",
            "narrateur|La main de papa pose sur l'anse.",
            "narrateur|La main de Nino est dessous.",
            "narrateur|L'arrosoir se lève, tout lent.",
            "enfant-m|Il monte !",
            "papa|Ensemble.",
            "papa|On va jusqu'au pot ?",
            "narrateur|Ils marchent tout près.",
            "narrateur|L'eau cloche, un peu.",
            "narrateur|Nino souffle.",
            "papa|On verse un peu.",
            "papa|Pas tout.",
            "narrateur|Le basilic attend, tout mou.",
            "narrateur|Une feuille touche le rebord.",
            "enfant-m|Vite.",
            "papa|Tout doux, pas vite.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La plante a soif.",
            "narrateur|Que fait Nino avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino penche avec papa.",
            "narrateur|L'eau tombe sur la terre.",
            "narrateur|La terre devient sombre.",
            "enfant-m|Elle boit.",
            "papa|Oui.",
            "papa|Tu tiens encore l'anse ?",
            "enfant-m|Oui.",
            "narrateur|Une goutte glisse sur le pot.",
            "narrateur|Elle fait un trait brillant.",
            "papa|On arrête.",
            "papa|C'est assez.",
            "narrateur|Ils reposent l'arrosoir.",
            "narrateur|Il fait un bruit de plastique.",
            "enfant-m|Mes bras sont lourds.",
            "papa|Merci, Nino.",
            "papa|Tu as tenu avec moi.",
            "narrateur|Nino sèche les mains au torchon.",
            "narrateur|Le torchon sent le citron.",
            "enfant-m|Je peux sentir, maintenant ?",
            "papa|La grande feuille, oui.",
            "narrateur|Une goutte sèche sur le pot.",
            "narrateur|Elle laisse un trait clair.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nino froisse la feuille.",
            "narrateur|L'odeur saute, toute verte.",
            "enfant-m|Ça pique le nez !",
            "papa|C'est le basilic.",
            "papa|Tu l'as aidé à boire.",
            "narrateur|Une feuille se redresse, un peu.",
            "narrateur|Le soleil la touche.",
            "enfant-m|Elle se lève.",
            "papa|Oui.",
            "papa|Parce qu'il y a de l'eau.",
            "narrateur|L'évier fait encore tic.",
            "narrateur|Nino pose l'arrosoir près du seau.",
            "papa|L'anse est à toi, la prochaine fois ?",
            "enfant-m|Avec toi.",
            "papa|Avec moi.",
            "narrateur|Le pot reste près de la vitre.",
            "narrateur|La terre est sombre, enfin.",
            "papa|Tu as fini de sentir ?",
            "enfant-m|Encore un peu.",
            "narrateur|Nino rapproche le nez.",
            "narrateur|L'odeur reste sur sa joue.",
            "enfant-m|Elle reste.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nino garde l'odeur dans les doigts.",
            "enfant-m|Je l'ai sentie.",
            "papa|Oui.",
            "papa|La grande feuille.",
            "narrateur|L'évier fait tic, encore.",
            "narrateur|Le basilic sent fort, tout près.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | il arrose | de l'eau | eau",
        "retry_prompt": "Ils versent de l'eau. Que fait Nino ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-03",
    "L'arrosoir trop lourd",
    "Nino veut sentir une feuille. L'arrosoir est trop lourd. Papa tient l'anse avec lui. "
    "Ils versent. L'odeur saute.",
    "- Désir : sentir la feuille.\n"
    "- Imprévu : arrosoir trop lourd, anse à deux.\n"
    "- Troupe D16 : Nino, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-04  N2  Nina, papa — basilic, soleil trop fort
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-04",
    "Nina veut une feuille de basilic pour son pain. Le soleil est trop fort. "
    "Les feuilles cuisent. Ils arrosent, puis déplacent le pot à l'ombre du rideau.",
    "Le basilic trop au soleil",
    "Nina, papa",
    "cuisine puis rebord de fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le carrelage brûle un peu les pieds.",
            "narrateur|Un rai de soleil coupe la table en deux.",
            "narrateur|Le pain de midi attend, encore tiède.",
            "narrateur|Ça sent la croûte et le beurre.",
            "narrateur|Nina vit ici, avec papa.",
            "papa|Tu veux du basilic sur le pain ?",
            "enfant-f|Oui.",
            "enfant-f|Une feuille qui sent fort.",
            "narrateur|En ce moment, Nina va vers la fenêtre.",
            "narrateur|Le pot est dans le rai, tout blanc.",
            "narrateur|Les feuilles sont molles, un peu jaunes.",
            "enfant-f|Elles sont chaudes.",
            "papa|Trop de soleil.",
            "papa|Il cuit, le pauvre.",
            "narrateur|Nina touche la terre.",
            "narrateur|La terre est chaude et sèche.",
            "enfant-f|Il a soif aussi.",
            "papa|Oui.",
            "papa|On lui donne de l'eau d'abord ?",
            "enfant-f|D'abord l'eau.",
            "narrateur|Papa glisse l'arrosoir vers elle.",
            "narrateur|L'anse est tiède, le plastique aussi.",
            "narrateur|Nina tient avec lui.",
            "narrateur|L'eau tombe, puis fume un tout petit peu.",
            "enfant-f|La terre fume !",
            "papa|Elle était trop chaude.",
            "papa|On va le déplacer après.",
            "enfant-f|Où ?",
            "papa|À côté, sous le rideau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La plante a soif.",
            "narrateur|Que fait Nina avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina pose l'arrosoir.",
            "narrateur|Le pot est encore dans le rai blanc.",
            "papa|On le prend à deux ?",
            "enfant-f|Oui.",
            "narrateur|Nina tient le bord du pot.",
            "narrateur|La terre cuite est chaude sous les doigts.",
            "narrateur|Papa tient le fond.",
            "narrateur|Ils glissent le pot hors du rai.",
            "narrateur|Le rideau fait une ombre mauve.",
            "enfant-f|Ici ?",
            "papa|Ici.",
            "papa|Il voit encore le jour.",
            "papa|Mais plus le feu du soleil.",
            "narrateur|Une feuille qui pendait se calme.",
            "narrateur|Elle ne se redresse pas encore.",
            "enfant-f|Elle est fatiguée.",
            "papa|Oui.",
            "papa|Merci, Nina.",
            "papa|Tu as bougé le pot.",
            "narrateur|Le pain attend toujours sur la table.",
            "narrateur|La croûte a refroidi, un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina choisit une feuille à l'ombre.",
            "narrateur|Celle-là est encore bien verte.",
            "papa|On en prend une petite.",
            "papa|Le basilic se repose.",
            "enfant-f|Je la froisse ?",
            "papa|Tout doux, oui.",
            "narrateur|L'odeur arrive, moins brûlée.",
            "narrateur|Elle sent le vert, enfin.",
            "enfant-f|Sur le pain.",
            "narrateur|Nina pose la feuille sur le beurre.",
            "narrateur|Le beurre fond un peu autour.",
            "papa|Tu as aidé le basilic.",
            "papa|Eau, puis ombre.",
            "enfant-f|Il cuit plus, là ?",
            "papa|Non.",
            "papa|Le rideau le garde.",
            "narrateur|Le rai blanc reste sur la table, vide.",
            "narrateur|Le pot respire dans le mauve.",
            "papa|Tu as fini ta tartine ?",
            "enfant-f|Presque.",
            "narrateur|Nina reprend une bouchée.",
            "narrateur|Le beurre sent encore le vert.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nina croque le pain.",
            "narrateur|Le basilic est frais sur le beurre.",
            "enfant-f|Il sent bon.",
            "papa|Oui.",
            "papa|Parce qu'il n'a plus trop chaud.",
            "narrateur|L'ombre du rideau est douce sur le pot.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | elle arrose | de l'eau | eau",
        "retry_prompt": "Ils versent de l'eau. Que fait Nina ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-04",
    "Le basilic trop au soleil",
    "Nina veut une feuille pour son pain. Le soleil cuit le pot. Ils arrosent, "
    "puis glissent le pot sous le rideau. Le pain sent le vert.",
    "- Désir : la feuille sur le pain.\n"
    "- Imprévu : soleil trop fort, déplacement du pot.\n"
    "- Troupe D16 : Nina, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-05  N1  Raphaël, papa — terre comme du sable
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-05",
    "Raphaël veut sentir une feuille de basilic. La terre est sèche comme du sable. "
    "L'eau glisse sur le côté. Une goutte, puis encore. La terre s'assombrit.",
    "La terre comme du sable",
    "Raphaël, papa",
    "rebord de fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un rayon jaune coupe la table.",
            "narrateur|Des miettes brillent dedans.",
            "narrateur|Le basilic est sur le rebord.",
            "narrateur|Ça sent le bois chaud.",
            "narrateur|Une chaise racle un peu le sol.",
            "narrateur|Raphaël vit ici, avec papa.",
            "papa|Tu as vu la terre ?",
            "enfant-m|Elle est claire.",
            "narrateur|Papa pince un peu de terre.",
            "narrateur|Elle tombe, comme du sable.",
            "enfant-m|Du sable ?",
            "papa|Elle a trop soif.",
            "papa|Tu veux sentir une feuille ?",
            "enfant-m|Oui.",
            "enfant-m|Mais elle est molle.",
            "papa|On lui donne de l'eau.",
            "papa|Tu prends l'arrosoir ?",
            "narrateur|En ce moment, Raphaël tire l'anse.",
            "narrateur|L'arrosoir est petit, rouge.",
            "narrateur|L'eau cloche, pas trop.",
            "enfant-m|Je verse ?",
            "papa|Une goutte d'abord.",
            "papa|Puis encore.",
            "narrateur|Raphaël penche.",
            "narrateur|L'eau glisse sur le côté.",
            "narrateur|Elle tombe sur le bois.",
            "enfant-m|Elle ne rentre pas !",
            "papa|La terre est trop sèche.",
            "papa|Elle fait un toit.",
            "narrateur|Une miette brille encore.",
            "narrateur|Raphaël la pousse du doigt.",
            "enfant-m|On recommence ?",
            "papa|Oui.",
            "papa|Au milieu, cette fois.",
            "narrateur|Le petit arrosoir rouge tremble.",
            "narrateur|Raphaël le tient à deux mains.",
            "enfant-m|J'ai peur de trop verser.",
            "papa|Une goutte seulement.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le basilic a soif.",
            "narrateur|Que fait Raphaël avec papa ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Papa pose un doigt au milieu.",
            "papa|Ici.",
            "papa|Une goutte, au centre.",
            "narrateur|Raphaël verse une goutte.",
            "narrateur|La goutte reste, un instant.",
            "narrateur|Puis elle s'enfonce.",
            "enfant-m|Elle est partie.",
            "papa|Encore une.",
            "narrateur|Encore une goutte.",
            "narrateur|Puis encore.",
            "narrateur|Un rond sombre s'ouvre.",
            "enfant-m|Elle boit, là.",
            "papa|Oui.",
            "papa|Tout doux.",
            "narrateur|La terre n'est plus du sable.",
            "narrateur|Elle devient sombre, au milieu.",
            "papa|Merci, Raphaël.",
            "papa|Tu as versé goutte à goutte.",
            "enfant-m|Je peux sentir ?",
            "papa|Bientôt.",
            "papa|On attend un peu.",
            "narrateur|Ils regardent le rond sombre.",
            "narrateur|Il s'élargit, tout lentement.",
            "enfant-m|Il grandit.",
            "papa|La terre boit, au fond.",
            "narrateur|Une feuille bouge, à peine.",
            "narrateur|Le rayon jaune la touche.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils attendent près du rebord.",
            "narrateur|Le rayon jaune a bougé.",
            "enfant-m|La feuille ?",
            "papa|Touche, tout doux.",
            "narrateur|Raphaël touche.",
            "narrateur|La feuille est moins molle.",
            "enfant-m|Elle se lève.",
            "papa|Un peu, oui.",
            "narrateur|Raphaël approche le nez.",
            "narrateur|L'odeur est encore faible.",
            "enfant-m|Presque.",
            "papa|Froisse tout doux.",
            "narrateur|Raphaël froisse.",
            "narrateur|L'odeur arrive, verte, nette.",
            "enfant-m|Ça y est !",
            "papa|Oui.",
            "papa|Une goutte, puis encore.",
            "narrateur|Une dernière goutte brille.",
            "narrateur|Puis elle s'enfonce.",
            "papa|Tu as fini de sentir ?",
            "enfant-m|Encore.",
            "narrateur|Raphaël froisse une deuxième fois.",
            "narrateur|L'odeur est plus forte.",
            "enfant-m|Maintenant, oui.",
            "papa|Bien.",
            "narrateur|Raphaël essuie une goutte sur le bois.",
            "narrateur|Le bois redevient sec.",
            "papa|Tu as fini le rebord ?",
            "enfant-m|Oui, papa.",
            "papa|Merci.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Raphaël garde le vert aux doigts.",
            "enfant-m|J'ai senti.",
            "papa|Oui.",
            "papa|La terre n'est plus du sable.",
            "narrateur|Une dernière goutte brille sur la terre.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | il arrose | de l'eau | eau",
        "retry_prompt": "Ils versent de l'eau. Que fait Raphaël ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-05",
    "La terre comme du sable",
    "Raphaël veut sentir une feuille. La terre est du sable. L'eau glisse. "
    "Une goutte, puis encore. L'odeur arrive.",
    "- Désir : sentir la feuille.\n"
    "- Imprévu : terre sèche, eau qui fuit, goutte à goutte.\n"
    "- Troupe D16 : Raphaël, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-06  N2  Chouchou, maman — menthe pour le thé
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-06",
    "Chouchou veut une feuille de menthe pour le thé. La petite feuille ne sent rien. "
    "La grande sent fort. La menthe a soif. Elles arrosent. Le thé sent le vert.",
    "La grande feuille de menthe",
    "Chouchou, maman",
    "jardin, pot de menthe sur la table",
    {
        "CHK_T0000_P0000": [
            "narrateur|La bouilloire attend, encore froide, près du miel.",
            "narrateur|Un grain de sucre brille sur le bois.",
            "narrateur|Le jardin sent la terre chaude.",
            "narrateur|Le pot de menthe est sur la table dehors.",
            "narrateur|Chouchou vit ici, avec maman.",
            "maman|On fait du thé ?",
            "enfant-f|Oui.",
            "enfant-f|Avec la menthe.",
            "narrateur|En ce moment, Chouchou se hausse vers le pot.",
            "narrateur|Les tiges sont grêles, un peu pâles.",
            "narrateur|Chouchou pince une toute petite feuille.",
            "narrateur|Elle la froisse sous le nez.",
            "enfant-f|Elle ne sent rien.",
            "maman|Trop petite.",
            "maman|Essaie la grande, là-bas.",
            "narrateur|La grande feuille est plus sombre.",
            "narrateur|Chouchou la froisse.",
            "narrateur|L'odeur saute, froide, très forte.",
            "enfant-f|Elle pique !",
            "maman|C'est la menthe.",
            "maman|Celle-là, pour le thé.",
            "narrateur|Chouchou regarde la terre.",
            "narrateur|La terre est claire, craquelée.",
            "enfant-f|Elle a soif, la menthe.",
            "maman|Oui.",
            "maman|Avant le thé, on lui donne à boire ?",
            "enfant-f|Oui, maman.",
            "narrateur|L'arrosoir de zinc est sous la table.",
            "narrateur|Il est froid, un peu bosselé.",
            "maman|Tu tiens avec moi ?",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La menthe a besoin de quoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou tient le zinc avec maman.",
            "narrateur|L'eau tombe, claire, sur la terre craquelée.",
            "narrateur|Les fentes se ferment, une à une.",
            "enfant-f|Elle boit.",
            "maman|Oui.",
            "maman|Eau, et un peu de lumière.",
            "narrateur|Le soleil touche déjà les tiges.",
            "narrateur|Les feuilles brillent, plus vertes.",
            "enfant-f|La grande, je la prends ?",
            "maman|Oui.",
            "maman|Une seule, pour le thé.",
            "narrateur|Chouchou pince la grande feuille.",
            "narrateur|La tige fait un tout petit clic.",
            "narrateur|L'odeur remplit les mains.",
            "maman|Merci, Chouchou.",
            "maman|Tu as choisi la grande.",
            "enfant-f|La petite, elle grandira ?",
            "maman|Avec de l'eau, oui.",
            "narrateur|Elles rentrent.",
            "narrateur|La bouilloire s'éveille, tout bas.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|L'eau chaude chante dans les tasses.",
            "narrateur|Chouchou glisse la grande feuille.",
            "narrateur|Elle tourne, puis s'ouvre.",
            "enfant-f|Ça sent fort.",
            "maman|Comme dans le jardin.",
            "maman|Tu souffles ?",
            "enfant-f|Fffff.",
            "narrateur|La vapeur sent le froid de la menthe.",
            "narrateur|Le miel fond, un fil d'or.",
            "maman|La petite feuille, dehors, boit encore.",
            "enfant-f|On lui parlera demain ?",
            "maman|Demain, si tu veux.",
            "narrateur|Chouchou tient la tasse à deux mains.",
            "narrateur|Le bord est chaud, le thé est vert.",
            "maman|Tu as aidé la menthe.",
            "maman|Puis tu as pris la grande.",
            "enfant-f|Pour le thé.",
            "narrateur|Une abeille passe près de la vitre.",
            "narrateur|Le miel sent encore la ruche.",
            "maman|Tu as fini ta tasse ?",
            "enfant-f|Presque.",
            "narrateur|Chouchou souffle encore.",
            "narrateur|La feuille tourne au fond.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Chouchou boit une gorgée.",
            "narrateur|C'est chaud, et vert, et doux.",
            "enfant-f|La grande feuille.",
            "maman|Oui.",
            "maman|Celle qui sentait fort.",
            "narrateur|Le thé sent la grande feuille.",
        ],
    },
    {"CHK_T0000_P0000": ""},
    {
        "expected_answer": "eau",
        "accepted_examples": "eau | lumière | arroser | un adulte | de l'eau",
        "retry_prompt": "On arrose avec un adulte. Eau et lumière. De quoi a-t-elle besoin ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-06",
    "La grande feuille de menthe",
    "Chouchou veut de la menthe pour le thé. La petite feuille ne sent rien. "
    "La grande sent fort. Elles arrosent. Le thé est vert.",
    "- Désir : le thé à la menthe, pas la liste d'arrosage.\n"
    "- Imprévu : feuille trop petite, la grande sent.\n"
    "- Troupe D16 : Chouchou, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.PLA.001-07  N2  Aniss, maman, papa — basilic, matin sec / soir encore
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.PLA.001-07",
    "Aniss veut du basilic sur les tomates du soir. Le matin, la terre est sèche. "
    "Ils arrosent un peu. Le soir, le dessus est encore sec. Un peu d'eau, le store s'ouvre.",
    "Le basilic du matin et du soir",
    "Aniss, maman, papa",
    "fenêtre de la cuisine, matin puis soir",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le store de la cuisine claque un peu.",
            "narrateur|Un filet de jour passe dessous.",
            "narrateur|Ça sent le pain grillé.",
            "narrateur|Le basilic est dans son pot, près du store.",
            "narrateur|Aniss vit ici, avec maman et papa.",
            "maman|Tu as vu la terre ?",
            "enfant-m|Elle est claire.",
            "papa|Le matin, il a souvent soif.",
            "enfant-m|Ce soir, les tomates.",
            "enfant-m|Je veux l'odeur dessus.",
            "maman|Alors on l'aide, ce matin.",
            "maman|Tu prends l'arrosoir ?",
            "narrateur|En ce moment, Aniss glisse l'arrosoir.",
            "narrateur|Le plastique est froid, encore.",
            "narrateur|Maman pose la main sur l'anse.",
            "narrateur|L'eau tombe, un filet mince.",
            "narrateur|Un rond sombre s'ouvre au milieu.",
            "enfant-m|Il boit.",
            "papa|Un peu, pas tout le seau.",
            "maman|Le soir, on regardera encore.",
            "enfant-m|Encore ?",
            "papa|Parfois le dessus sèche deux fois.",
            "narrateur|Aniss pose l'arrosoir.",
            "narrateur|Une feuille se redresse, à peine.",
            "maman|C'est le matin.",
            "maman|Il a le temps.",
            "narrateur|Le store claque encore, plus loin.",
            "narrateur|Le pain grillé refroidit dans l'assiette.",
            "papa|Tu as fini ton pain ?",
            "enfant-m|Oui.",
            "narrateur|Aniss essuie une miette.",
            "narrateur|La miette tombe près du pot.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss s'occupe du basilic.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le soir, la cuisine est orange.",
            "narrateur|Les tomates attendent dans le plat.",
            "enfant-m|Le basilic.",
            "narrateur|Aniss touche la terre.",
            "narrateur|Le dessus est encore sec, un peu.",
            "enfant-m|Encore soif.",
            "maman|Un tout petit peu, alors.",
            "papa|Je lève le store.",
            "narrateur|Le store monte, avec un bruit de toile.",
            "narrateur|La lumière arrive, plus douce qu'à midi.",
            "narrateur|Aniss verse trois gouttes, pas plus.",
            "narrateur|La terre s'assombrit, juste au milieu.",
            "papa|Voilà.",
            "papa|Eau, et de la lumière.",
            "maman|Merci, Aniss.",
            "maman|Tu as regardé deux fois.",
            "enfant-m|Matin, et soir.",
            "papa|Oui.",
            "narrateur|Une feuille tient plus droit, maintenant.",
            "narrateur|Aniss la pince, tout doux.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|L'odeur saute, verte, sur les doigts.",
            "enfant-m|Pour les tomates.",
            "maman|On coupe deux feuilles ?",
            "enfant-m|Deux.",
            "narrateur|Maman coupe.",
            "narrateur|Le couteau fait un clic de bois.",
            "narrateur|Les feuilles tombent sur le rouge.",
            "papa|Tu froisses un peu ?",
            "enfant-m|Fffff.",
            "narrateur|Aniss souffle.",
            "narrateur|L'odeur se mêle aux tomates.",
            "maman|C'est ce que tu voulais, ce matin.",
            "enfant-m|Oui.",
            "papa|Le store reste ouvert, un peu.",
            "papa|Pour la nuit, pas trop d'air.",
            "narrateur|Aniss essuie ses mains au torchon.",
            "narrateur|Le torchon sent le vert, maintenant.",
            "maman|On goûte ?",
            "enfant-m|On goûte.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Aniss croque une tomate.",
            "narrateur|Le basilic est dessus, tout frais.",
            "enfant-m|Matin, et soir.",
            "maman|Oui.",
            "papa|Deux fois, tout doux.",
            "narrateur|Le basilic du soir sent les tomates.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "arroser",
        "accepted_examples": "arroser | il arrose | de l'eau | avec maman",
        "retry_prompt": "Il arrose avec l'adulte. Que fait Aniss ?",
    },
)
relecture(
    "ATOM-VIV.PLA.001-07",
    "Le basilic du matin et du soir",
    "Aniss veut du basilic sur les tomates. Matin sec, un peu d'eau. "
    "Soir encore sec, trois gouttes, le store s'ouvre. Les tomates sentent le vert.",
    "- Désir : l'odeur sur les tomates du soir.\n"
    "- Imprévu : deux moments, le dessus sèche encore.\n"
    "- Troupe D16 : Aniss, maman, papa.",
)
