#!/usr/bin/env python3
"""F-NAR-008 — ATOM-VIV.ANI.001-02..09 (cris d'animaux, un désir par histoire)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

EMPTY = {
    "CHK_T0000_P0000": "",
    "CHK_T0000_P0000_Q0001": "",
    "CHK_T0000_P0000_C0001": "",
    "CHK_T0000_P0000_END": "",
    "CHK_T0000_P0000_END_F0001": "",
}

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-02  N2  Sarah, maman  — étang, canard (grenouille d'abord)
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-02",
    "Sarah veut le canard de l'étang. Une grenouille coasse d'abord. Puis le canard cancane derrière les roseaux.",
    "Le canard de l'étang",
    "Sarah, maman",
    "étang du village, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les roseaux de l'étang bruissent tout bas.",
            "narrateur|L'eau clignote entre les tiges vertes.",
            "narrateur|Une libellule tremble au-dessus d'une pierre.",
            "narrateur|La pierre est chaude et un peu glissante.",
            "narrateur|Ça sent la vase et l'herbe mouillée.",
            "maman|Tu entends les roseaux, Sarah ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux le canard.",
            "maman|Le canard de l'étang ?",
            "enfant-f|Celui qui nage.",
            "narrateur|En ce moment, Sarah marche près de l'eau.",
            "narrateur|Ses bottes font un bruit mou dans la boue.",
            "narrateur|Un nénuphar rond cache un petit trou.",
            "narrateur|Quelque chose claque dans les feuilles.",
            "enfant-f|Le canard !",
            "maman|On écoute encore ?",
            "narrateur|Sarah s'arrête.",
            "narrateur|Le bruit revient, tout près.",
            "narrateur|Ce n'est pas un coin coin.",
            "narrateur|C'est un coa, rêche et court.",
            "maman|Tu entends bien, Sarah ?",
            "enfant-f|Ce n'est pas lui.",
            "narrateur|Une grenouille verte saute sur la feuille.",
            "narrateur|Elle gonfle sa gorge.",
            "narrateur|Elle fait coa encore une fois.",
            "enfant-f|Une grenouille.",
            "maman|Oui.",
            "maman|Elle coasse.",
            "narrateur|Sarah regarde l'eau plus loin.",
            "narrateur|Les roseaux bougent au fond de l'étang.",
            "enfant-f|Le canard est là-bas.",
            "maman|On continue tout doux ?",
            "enfant-f|Oui.",
            "narrateur|Elles suivent la berge.",
            "narrateur|Une branche morte flotte, toute grise.",
            "narrateur|Sarah pose un genou sur la pierre chaude.",
            "narrateur|Un sillon d'eau tremble entre les roseaux.",
            "narrateur|Alors un cri rond arrive.",
            "narrateur|Coin coin.",
            "enfant-f|Là !",
            "maman|Tu as entendu ?",
            "enfant-f|Coin coin.",
            "maman|Le canard cancane.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah entend coin coin.",
            "narrateur|Quel est le cri du canard ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Un bec orange perce les roseaux.",
            "narrateur|Le canard glisse sur l'eau sombre.",
            "narrateur|Il laisse un sillon tout droit.",
            "enfant-f|Je le vois.",
            "maman|Merci d'avoir écouté, Sarah.",
            "maman|Tu as trouvé son cri.",
            "enfant-f|Il cancane.",
            "maman|Oui.",
            "maman|Coin coin.",
            "narrateur|Le canard tourne la tête.",
            "narrateur|Des gouttes tombent de son dos.",
            "narrateur|Sarah reste sur la pierre chaude.",
            "maman|On le regarde d'ici ?",
            "enfant-f|Oui.",
            "narrateur|Un nénuphar penche sous le sillon.",
            "narrateur|L'eau sent encore la vase tiède.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le canard s'éloigne vers le milieu.",
            "narrateur|L'eau redevient calme derrière lui.",
            "enfant-f|Il nage.",
            "maman|Tu voulais le canard.",
            "maman|Le voilà.",
            "narrateur|Sarah pose la main dans l'eau.",
            "narrateur|L'eau est tiède et un peu trouble.",
            "narrateur|La grenouille s'est tue.",
            "narrateur|Seul le canard cancane encore, plus loin.",
            "enfant-f|Coin coin.",
            "maman|C'est son cri.",
            "narrateur|Une libellule revient sur la pierre.",
            "narrateur|Sarah ne la chasse pas.",
            "narrateur|Elle écoute le canard, tout bas.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le soleil glisse sur le sillon d'or.",
            "narrateur|Sarah tient la main de maman.",
            "enfant-f|Le canard est là.",
            "maman|Oui.",
            "narrateur|Les roseaux bruissent encore tout bas.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "cancane",
        "accepted_examples": "cancane | il cancane | coin coin | le cri | le canard",
        "retry_prompt": "Le canard cancane. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-02",
    "Le canard de l'étang",
    "Sarah veut le canard. Une grenouille coasse d'abord. Puis le canard cancane. Elles le regardent d'ici.",
    "- Désir : le canard, pas un catalogue.\n"
    "- Imprévu : grenouille. Fin : sillon d'or.\n"
    "- Troupe D16 : Sarah, maman. Question : cancane.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-03  N2  Amir, maman  — chemin des prés, vache, barrière
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-03",
    "Amir veut la vache du pré. Le meuh est loin, puis plus près. La barrière est fermée. Ils écoutent par la haie.",
    "Le meuh derrière la haie",
    "Amir, maman",
    "chemin des prés, après la coupe du foin",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le chemin des prés sent le foin coupé.",
            "narrateur|Des brins jaunes collent aux chaussettes.",
            "narrateur|Un papillon poussiéreux se pose sur une tige.",
            "narrateur|La terre du sentier est sèche et claire.",
            "maman|Tu sens le foin, Amir ?",
            "enfant-m|Oui.",
            "enfant-m|Il pique le nez.",
            "narrateur|Un meuh arrive, tout loin.",
            "enfant-m|La vache !",
            "maman|Tu l'as entendue ?",
            "enfant-m|Je veux la voir.",
            "narrateur|En ce moment, Amir accélère un peu.",
            "narrateur|Le sentier monte entre deux buissons.",
            "narrateur|Le meuh revient, plus fort.",
            "enfant-m|Elle est près.",
            "maman|On continue ?",
            "enfant-m|Oui.",
            "narrateur|Une barrière de bois barre le chemin.",
            "narrateur|Le loquet est fermé, tout gris.",
            "enfant-m|On ne passe pas.",
            "maman|La barrière est fermée.",
            "maman|On reste de ce côté.",
            "narrateur|Amir pose les mains sur le bois chaud.",
            "narrateur|Le bois sent la sève sèche.",
            "narrateur|Derrière, une haie d'aubépine tremble.",
            "maman|On écoute par la haie ?",
            "enfant-m|Oui.",
            "narrateur|Ils se baissent près des feuilles.",
            "narrateur|Une épine accroche le pull d'Amir.",
            "narrateur|Maman la décroche tout doux.",
            "narrateur|Le meuh passe à travers les feuilles.",
            "enfant-m|Meuh.",
            "maman|La vache meugle.",
            "narrateur|Amir colle l'oreille vers la haie.",
            "narrateur|Un œil brun cligne entre les branches.",
            "narrateur|Une tache blanche marque le poil.",
            "enfant-m|Elle mâche.",
            "maman|On la regarde par les feuilles.",
            "narrateur|Le foin coupé pique encore les chevilles.",
            "narrateur|Amir ne touche pas le loquet.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir entend meuh.",
            "narrateur|Quel est le cri de la vache ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La vache lève le museau derrière la haie.",
            "narrateur|Un brin de foin paille son poil.",
            "enfant-m|Je la vois.",
            "maman|Merci d'être resté de ce côté.",
            "maman|On écoute par la haie.",
            "enfant-m|Elle meugle.",
            "maman|Oui.",
            "maman|Meuh.",
            "narrateur|La vache mâche tout lentement.",
            "narrateur|Sa cloche fait un petit toc.",
            "narrateur|Amir ne pousse pas le loquet.",
            "maman|On reste ici ?",
            "enfant-m|Oui.",
            "narrateur|Une feuille d'aubépine chatouille son oreille.",
            "narrateur|Le meuh revient, tout proche.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le papillon repart vers le foin.",
            "narrateur|Amir garde les mains sur le bois.",
            "enfant-m|Elle est grande.",
            "maman|Tu voulais la vache.",
            "maman|Elle est derrière la haie.",
            "narrateur|Un nuage passe sur le pré.",
            "narrateur|L'œil brun cligne encore.",
            "narrateur|La cloche fait toc, toc.",
            "enfant-m|Meuh.",
            "maman|C'est son cri.",
            "narrateur|Le sentier sent encore le foin coupé.",
            "narrateur|Amir recule d'un pas, tout seul.",
            "maman|Tu as bien écouté.",
            "narrateur|Un brin de foin reste collé au pull.",
            "narrateur|Amir le souffle vers le pré.",
            "enfant-m|Meuh encore.",
            "maman|Elle est toujours là.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La barrière reste fermée, tiède.",
            "narrateur|Amir prend la main de maman.",
            "enfant-m|Je l'ai entendue.",
            "maman|Oui.",
            "narrateur|Le meuh passe encore à travers les feuilles.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "meuh",
        "accepted_examples": "meuh | elle meugle | meugle | le cri | la vache",
        "retry_prompt": "La vache meugle. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-03",
    "Le meuh derrière la haie",
    "Amir veut la vache. Le meuh se rapproche. Barrière fermée. Ils écoutent par la haie.",
    "- Désir : voir la vache, pas un catalogue.\n"
    "- Imprévu : loquet fermé. Fin : meuh à travers les feuilles.\n"
    "- Troupe D16 : Amir, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-04  N2  Mila, papa  — pré, cheval, pomme à terre
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-04",
    "Mila veut donner une pomme au cheval. La pomme de l'arbre est trop haute. Ils en trouvent une à terre. Papa la donne.",
    "La pomme du cheval",
    "Mila, papa",
    "pré près de la ferme, pommier contre la clôture",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le pommier du pré penche vers la clôture.",
            "narrateur|Une pomme verte brille tout en haut.",
            "narrateur|Des mouches tournent au-dessus de l'herbe.",
            "narrateur|Ça sent le sucré et le crottin chaud.",
            "papa|Tu vois le pommier, Mila ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux le cheval.",
            "papa|Le cheval du pré ?",
            "enfant-f|Lui donner une pomme.",
            "narrateur|En ce moment, Mila lève le nez.",
            "narrateur|La pomme du haut est trop loin.",
            "enfant-f|Je n'arrive pas.",
            "papa|Elle est trop haute.",
            "narrateur|Un hennissement arrive du pré.",
            "narrateur|Hiii, long et doux.",
            "enfant-f|Le cheval !",
            "papa|Tu as entendu ?",
            "enfant-f|Il appelle.",
            "papa|Le cheval hennit.",
            "narrateur|Mila marche le long de la clôture.",
            "narrateur|L'herbe racle ses mollets.",
            "narrateur|Une pomme brune dort dans l'herbe.",
            "enfant-f|Une à terre !",
            "papa|On la ramasse ?",
            "enfant-f|Oui.",
            "narrateur|Mila se baisse.",
            "narrateur|La pomme est froide et un peu molle.",
            "narrateur|Elle la tend vers le pré.",
            "papa|On ne donne pas tout seuls.",
            "papa|Je la donne, d'accord ?",
            "enfant-f|D'accord.",
            "narrateur|Papa prend la pomme dans sa main.",
            "narrateur|Le cheval s'approche de la clôture.",
            "narrateur|Son museau est velours et tiède.",
            "narrateur|Il souffle.",
            "narrateur|Hiii.",
            "narrateur|Une mouche se pose sur l'encolure.",
            "enfant-f|Il attend la pomme.",
            "papa|Oui.",
            "narrateur|Les naseaux du cheval s'ouvrent tout grand.",
            "narrateur|La clôture tremble un peu sous le poil.",
            "enfant-f|Il est tout près.",
            "papa|On reste de ce côté.",
            "narrateur|Mila sent le sucré de la pomme froide.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le cheval fait hiii.",
            "narrateur|Quel est le cri du cheval ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Papa pose la pomme sur sa paume ouverte.",
            "narrateur|Le cheval croque.",
            "narrateur|Ça fait un bruit sec.",
            "enfant-f|Il mange.",
            "papa|Merci d'avoir attendu, Mila.",
            "papa|On donne avec un adulte.",
            "enfant-f|Il hennit.",
            "papa|Oui.",
            "papa|Hiii.",
            "narrateur|Un filet de jus coule sur le poil.",
            "narrateur|Mila reste derrière la clôture.",
            "narrateur|Elle ne tend plus la main.",
            "papa|On le regarde d'ici ?",
            "enfant-f|Oui.",
            "narrateur|La queue du cheval chasse une mouche.",
            "narrateur|L'herbe sent encore le sucré.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La pomme a disparu d'un coup.",
            "narrateur|Il reste un trognon minuscule.",
            "enfant-f|Il a tout pris.",
            "papa|Tu voulais lui donner une pomme.",
            "papa|C'est fait.",
            "narrateur|Le cheval frotte le bois de la clôture.",
            "narrateur|Le bois tremble un peu.",
            "narrateur|Mila pose une main sur le piquet.",
            "enfant-f|Hiii.",
            "papa|C'est son cri.",
            "narrateur|La pomme du haut brille encore.",
            "narrateur|Celle de terre a suffi.",
            "narrateur|Une mouche repart vers l'herbe.",
            "enfant-f|Il hennit encore.",
            "papa|Oui.",
            "narrateur|Le crottin chaud sent moins, maintenant.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le museau du cheval sent encore la pomme.",
            "narrateur|Mila prend la main de papa.",
            "enfant-f|Il a mangé.",
            "papa|Oui.",
            "narrateur|Le pommier penche, tout tranquille.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "hennit",
        "accepted_examples": "hennit | il hennit | hiii | le cri | le cheval",
        "retry_prompt": "Le cheval hennit. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-04",
    "La pomme du cheval",
    "Mila veut une pomme pour le cheval. Trop haute. Une à terre. Papa la donne.",
    "- Désir : donner la pomme.\n"
    "- POS : on ne donne pas sans adulte.\n"
    "- Troupe D16 : Mila, papa. Fin : museau sucré.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-05  N1  Nino, maman  — ferme, coq, paille dans la botte
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-05",
    "Nino veut le coq de la ferme. Une paille pique dans sa botte. Maman la retire. Puis le coq chante.",
    "La paille dans la botte",
    "Nino, maman",
    "cour de ferme, paille sèche",
    {
        "CHK_T0000_P0000": [
            "narrateur|La cour de la ferme sent la paille sèche.",
            "narrateur|Un brin jaune colle au bois.",
            "narrateur|Le soleil tape sur les tuiles.",
            "narrateur|Une ombre passe sur le gravier.",
            "maman|Tu sens la paille, Nino ?",
            "enfant-m|Oui.",
            "enfant-m|Elle pique un peu.",
            "maman|On va voir le coq ?",
            "enfant-m|Oui.",
            "enfant-m|Je veux le coq.",
            "narrateur|En ce moment, Nino marche.",
            "narrateur|Sa botte fait un bruit mou.",
            "narrateur|Un caillou roule sous la semelle.",
            "narrateur|Nino lève le pied.",
            "narrateur|Un brin de paille dépasse.",
            "enfant-m|Ça pique.",
            "maman|Dans la botte ?",
            "enfant-m|Oui.",
            "narrateur|Maman s'accroupit.",
            "narrateur|Elle tire le brin tout doux.",
            "narrateur|La paille sort, toute jaune.",
            "enfant-m|Elle est sortie.",
            "maman|On remet la botte ?",
            "enfant-m|Oui.",
            "narrateur|Nino enfile la botte.",
            "narrateur|Le pied est à l'aise.",
            "narrateur|Ils avancent vers le mur.",
            "narrateur|La cour craque sous les bottes.",
            "narrateur|Une plume grise dort dans la poussière.",
            "narrateur|Un grain de blé brille au soleil.",
            "enfant-m|Le coq est où ?",
            "maman|On écoute.",
            "narrateur|Le silence pèse un peu.",
            "narrateur|Puis un cri monte du mur.",
            "narrateur|Cocorico.",
            "enfant-m|Le coq !",
            "maman|Tu as entendu ?",
            "enfant-m|Cocorico.",
            "maman|Le coq chante.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino entend cocorico.",
            "narrateur|Quel est le cri du coq ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le coq est sur le mur chaud.",
            "narrateur|Sa crête est rouge et molle.",
            "enfant-m|Je le vois.",
            "maman|Merci d'avoir attendu, Nino.",
            "maman|Tu as trouvé son cri.",
            "enfant-m|Il chante.",
            "maman|Oui.",
            "maman|Cocorico.",
            "narrateur|Le coq secoue ses plumes.",
            "narrateur|Une poussière d'or tombe.",
            "narrateur|Nino reste près de maman.",
            "maman|On le regarde d'ici ?",
            "enfant-m|Oui.",
            "narrateur|La botte ne pique plus.",
            "narrateur|Le gravier craque sous le talon.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le coq marche sur le mur.",
            "narrateur|Ses ongles râpent la pierre.",
            "enfant-m|Il est grand.",
            "maman|Tu voulais le coq.",
            "maman|Le voilà.",
            "narrateur|Nino pose le brin de paille.",
            "narrateur|Le brin reste sur le bois.",
            "narrateur|Le coq chante encore une fois.",
            "enfant-m|Cocorico.",
            "maman|C'est son cri.",
            "narrateur|Une poule gratte loin, tout doux.",
            "narrateur|Nino ne la suit pas.",
            "narrateur|Il écoute le coq.",
            "narrateur|La botte est douce maintenant.",
            "enfant-m|Plus de paille.",
            "maman|Le pied va bien ?",
            "enfant-m|Oui.",
            "narrateur|Un grain roule près du mur.",
            "narrateur|Le coq le regarde, puis chante.",
            "narrateur|Nino pose la main sur le mur chaud.",
            "narrateur|La pierre gratte un peu.",
            "enfant-m|Il est beau.",
            "maman|Tu as bien écouté.",
            "narrateur|Le brin jaune ne pique plus.",
            "narrateur|Nino regarde encore le mur.",
            "narrateur|Le coq ouvre le bec.",
            "enfant-m|Encore.",
            "maman|Il chante pour la cour.",
            "narrateur|La poussière d'or retombe.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le cocorico reste dans la cour chaude.",
            "narrateur|Nino tient la main de maman.",
            "enfant-m|Le coq a chanté.",
            "maman|Oui.",
            "narrateur|La paille jaune brille sur le bois.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "cocorico",
        "accepted_examples": "cocorico | il chante | le cri | le coq | chante",
        "retry_prompt": "Le coq chante. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-05",
    "La paille dans la botte",
    "Nino veut le coq. Une paille pique. Maman la retire. Le coq chante sur le mur.",
    "- N1, phrases courtes.\n"
    "- Imprévu : paille dans la botte.\n"
    "- Troupe D16 : Nino, maman. Fin : paille sur le bois.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-06  N2  Nina, maman  — basse-cour, oie trop bruyante
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-06",
    "Nina veut voir l'oie de la basse-cour. L'oie cacarde trop fort. Elles reculent près de maman et regardent d'ici.",
    "L'oie trop bruyante",
    "Nina, maman",
    "basse-cour, grillage chaud, plumes blanches",
    {
        "CHK_T0000_P0000": [
            "narrateur|Des plumes blanches collent au grillage chaud.",
            "narrateur|Un grain de maïs roule dans la poussière.",
            "narrateur|La basse-cour sent le son et l'eau tiède.",
            "narrateur|Une gamelle de fer brille au soleil.",
            "maman|Tu vois les plumes, Nina ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux l'oie.",
            "maman|L'oie blanche ?",
            "enfant-f|Celle qui crie.",
            "narrateur|En ce moment, Nina s'approche du grillage.",
            "narrateur|Le métal est chaud sous ses doigts.",
            "narrateur|Un cou long se lève derrière le fil.",
            "narrateur|L'oie ouvre le bec.",
            "narrateur|Ça ça, très fort.",
            "enfant-f|Oh.",
            "maman|Elle cacarde.",
            "narrateur|Le cri tape les oreilles de Nina.",
            "narrateur|L'oie avance, les ailes un peu ouvertes.",
            "enfant-f|Elle est trop bruyante.",
            "maman|On recule près de moi ?",
            "enfant-f|Oui.",
            "narrateur|Nina lâche le grillage.",
            "narrateur|Elle vient contre la jambe de maman.",
            "narrateur|Le tissu du pantalon est frais.",
            "maman|On reste avec l'adulte, près des animaux.",
            "maman|On écoute d'ici.",
            "enfant-f|D'accord.",
            "narrateur|L'oie cacarde encore, plus loin.",
            "narrateur|Ça ça, moins fort maintenant.",
            "enfant-f|Ça ça.",
            "maman|C'est son cri.",
            "narrateur|Une plume blanche s'envole vers Nina.",
            "narrateur|Elle ne la chasse pas.",
            "narrateur|Elle reste contre maman.",
            "narrateur|Le soleil tape encore le grillage.",
            "enfant-f|On reste ici.",
            "maman|Oui.",
            "narrateur|Nina sent le son chaud de la cour.",
            "narrateur|Une plume blanche se colle à sa chaussette.",
            "enfant-f|Une plume.",
            "maman|On la laisse.",
            "narrateur|Nina ne s'approche plus du fil.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina entend ça ça.",
            "narrateur|Quel est le cri de l'oie ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'oie picore le grain, le cou plié.",
            "narrateur|Ses pattes orangées tapent la terre.",
            "enfant-f|Je la vois d'ici.",
            "maman|Merci d'être revenue près de moi.",
            "maman|On reste avec l'adulte.",
            "enfant-f|Elle cacarde.",
            "maman|Oui.",
            "maman|Ça ça.",
            "narrateur|Nina pose la main sur le pantalon.",
            "narrateur|Le cri ne tape plus autant.",
            "maman|On la regarde d'ici ?",
            "enfant-f|Oui.",
            "narrateur|Le grillage fait un petit tic au soleil.",
            "narrateur|La gamelle de fer reste vide un moment.",
            "narrateur|L'oie s'éloigne vers l'auge.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Une autre plume colle au fil chaud.",
            "narrateur|Nina ne s'approche plus.",
            "enfant-f|Elle est moins forte.",
            "maman|Tu voulais l'oie.",
            "maman|On l'a vue, près de moi.",
            "narrateur|Le maïs roule encore d'un doigt.",
            "narrateur|L'oie le suit, tout blanche.",
            "enfant-f|Ça ça.",
            "maman|C'est son cri.",
            "narrateur|Nina souffle.",
            "narrateur|Ses épaules redescendent.",
            "maman|Tu es restée avec moi.",
            "narrateur|Le grain de maïs a disparu.",
            "narrateur|L'oie boit à l'auge, le cou plié.",
            "enfant-f|Elle ne crie plus.",
            "maman|On peut rester encore un peu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|L'oie picore au loin, toute blanche.",
            "narrateur|Nina tient la main de maman.",
            "enfant-f|On l'a vue.",
            "maman|Oui.",
            "narrateur|Une plume blanche dort encore au grillage.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "cacarde",
        "accepted_examples": "cacarde | ça ça | le cri | l'oie | elle cacarde",
        "retry_prompt": "L'oie cacarde. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-06",
    "L'oie trop bruyante",
    "Nina veut l'oie. Le cri est trop fort. Elles reculent près de maman.",
    "- POS : rester avec l'adulte près des animaux.\n"
    "- Désir : voir l'oie, pas un catalogue.\n"
    "- Troupe D16 : Nina, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-07  N3  Raphaël, papa  — ferme matin (poule) puis soir (hibou)
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-07",
    "Raphaël veut la poule du matin. Elle glousse près du seau. Le soir, un hibou hulule loin sur les toits.",
    "La poule du matin",
    "Raphaël, papa",
    "ferme, cuisine puis cour, matin et soir",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le seau de lait fume encore dans la cuisine.",
            "narrateur|Une goutte blanche sèche sur le bois.",
            "narrateur|La fenêtre donne sur la cour grise.",
            "narrateur|Un râteau s'appuie contre le mur froid.",
            "papa|Tu sens le lait, Raphaël ?",
            "enfant-m|Oui.",
            "enfant-m|Il est chaud.",
            "enfant-m|Je veux la poule.",
            "papa|Celle qui a pondu ?",
            "enfant-m|Oui.",
            "narrateur|En ce moment, Raphaël ouvre la porte.",
            "narrateur|L'air de la cour pique un peu.",
            "narrateur|La terre est encore mouillée de rosée.",
            "narrateur|Un cot cot arrive près du seau vide.",
            "enfant-m|La poule !",
            "papa|Tu as entendu ?",
            "enfant-m|Cot cot.",
            "papa|La poule glousse.",
            "narrateur|La poule brune gratte sous le râteau.",
            "narrateur|Un œuf sale brille dans la paille.",
            "enfant-m|Elle a pondu.",
            "papa|On la regarde d'ici ?",
            "enfant-m|Oui.",
            "narrateur|Raphaël s'accroupit près du seau.",
            "narrateur|La poule tourne l'œil, tout rond.",
            "narrateur|Elle glousse encore, plus doux.",
            "enfant-m|Cot cot.",
            "papa|C'est son cri.",
            "narrateur|Le lait de la cuisine sent encore.",
            "narrateur|La poule picore un grain près du bois.",
            "narrateur|Raphaël ne la prend pas.",
            "papa|On la laisse.",
            "papa|Elle a son œuf.",
            "narrateur|Raphaël touche le seau vide, tout froid.",
            "narrateur|La poule glousse une dernière fois.",
            "enfant-m|Je l'ai eue.",
            "papa|Le matin, c'est elle.",
            "narrateur|Un grain reste collé au bec de la poule.",
            "narrateur|Raphaël rit tout bas.",
            "enfant-m|Cot cot.",
            "papa|Tu as son cri.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël entend cot cot.",
            "narrateur|Quel est le cri de la poule ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Plus tard, la cour devient bleue.",
            "narrateur|Le seau de lait a disparu de la table.",
            "narrateur|Papa ferme le petit volet de bois.",
            "enfant-m|La poule dort ?",
            "papa|Oui.",
            "papa|Elle est rentrée.",
            "narrateur|Un cri rond arrive des toits.",
            "narrateur|Hou hou, tout loin.",
            "enfant-m|Ce n'est pas la poule.",
            "papa|Tu entends, Raphaël ?",
            "enfant-m|Hou hou.",
            "papa|Un hibou hulule.",
            "narrateur|Raphaël lève le nez vers les tuiles noires.",
            "narrateur|Rien ne bouge, seulement le cri.",
            "papa|Merci d'avoir écouté le soir aussi.",
            "narrateur|Le hou hou revient, plus mince.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La poule ne glousse plus.",
            "narrateur|Le hibou reste loin, sur les toits.",
            "enfant-m|Deux cris.",
            "papa|Le matin, la poule.",
            "papa|Le soir, le hibou.",
            "narrateur|Raphaël pose l'oreille vers la cour.",
            "narrateur|L'air est froid maintenant.",
            "enfant-m|Hou hou.",
            "papa|C'est son cri, à lui.",
            "narrateur|Une étoile perce au-dessus du râteau.",
            "narrateur|Le bois du volet sent la poussière.",
            "papa|On rentre ?",
            "enfant-m|Encore un peu.",
            "narrateur|Raphaël compte deux silences.",
            "narrateur|Celui de la poule, celui du hibou.",
            "enfant-m|Le hou hou est loin.",
            "papa|Oui.",
            "narrateur|La rosée du matin a disparu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le hou hou s'efface dans les toits noirs.",
            "narrateur|Raphaël prend la main de papa.",
            "enfant-m|La poule, puis le hibou.",
            "papa|Oui.",
            "narrateur|Le seau vide brille encore sous la fenêtre.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "cot cot",
        "accepted_examples": "cot cot | glousse | elle glousse | le cri | la poule",
        "retry_prompt": "La poule glousse. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-07",
    "La poule du matin",
    "Raphaël veut la poule le matin. Cot cot. Le soir, un hibou hulule loin.",
    "- Deux moments : matin poule, soir hibou.\n"
    "- Pas un catalogue. N3 oral.\n"
    "- Troupe D16 : Raphaël, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-08  N2  Chouchou, maman  — jardin, merle puis chat
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-08",
    "Chouchou veut le merle du cerisier. Il siffle. Un chat miaule. Le merle s'envole. Elles restent près du tronc.",
    "Le merle du jardin",
    "Chouchou, maman",
    "jardin derrière la maison, terre noire",
    {
        "CHK_T0000_P0000": [
            "narrateur|La terre du jardin reste noire et grasse.",
            "narrateur|Un ver rose se plie sous une feuille.",
            "narrateur|Le cerisier penche au fond, encore mouillé.",
            "narrateur|Ça sent l'humus et l'eau de pluie.",
            "maman|Tu vois le ver, Chouchou ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux le merle.",
            "maman|Celui du cerisier ?",
            "enfant-f|Celui qui siffle.",
            "narrateur|En ce moment, Chouchou avance entre les rames.",
            "narrateur|Une goutte tombe d'une feuille sur son nez.",
            "narrateur|Un sifflet clair part du cerisier.",
            "enfant-f|Le merle !",
            "maman|Tu as entendu ?",
            "enfant-f|Il siffle.",
            "maman|Le merle siffle.",
            "narrateur|Un point noir se pose sur une branche.",
            "narrateur|Le bec est jaune, tout net.",
            "enfant-f|Je le vois.",
            "narrateur|Chouchou s'arrête près du tronc.",
            "narrateur|L'écorce est rêche sous sa paume.",
            "narrateur|Le merle siffle encore, plus haut.",
            "enfant-f|Tio tio.",
            "maman|C'est son cri.",
            "narrateur|Un bruit plus bas arrive de l'allée.",
            "narrateur|Miaou, tout proche.",
            "enfant-f|Qui c'est ?",
            "maman|On écoute.",
            "narrateur|Un chat gris glisse le long des rames.",
            "narrateur|Le merle s'envole d'un coup.",
            "narrateur|Une plume noire tombe dans l'herbe.",
            "enfant-f|Il est parti.",
            "maman|Le chat a miaulé.",
            "narrateur|Le sifflet du merle ne revient pas.",
            "narrateur|Chouchou reste collée au tronc.",
            "narrateur|L'écorce marque sa paume.",
            "enfant-f|Il a sifflé avant.",
            "maman|Oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou a entendu le merle.",
            "narrateur|Quel est le cri du merle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le chat s'assoit sous le cerisier.",
            "narrateur|Il lèche une patte, tout calme.",
            "enfant-f|Le merle n'est plus là.",
            "maman|Tu l'as entendu siffler.",
            "maman|Merci d'avoir écouté, Chouchou.",
            "enfant-f|Il sifflait.",
            "maman|Oui.",
            "maman|Tio tio.",
            "narrateur|Chouchou ramasse la plume noire.",
            "narrateur|Elle est légère, un peu humide.",
            "maman|On reste près du tronc ?",
            "enfant-f|Oui.",
            "narrateur|Le chat miaule encore, plus doux.",
            "narrateur|Chouchou ne court pas vers lui.",
            "narrateur|Elle garde la plume dans la main.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le cerisier redevient silencieux.",
            "narrateur|Le ver s'est caché sous la feuille.",
            "enfant-f|Le merle va revenir ?",
            "maman|Peut-être.",
            "maman|Tu as eu son cri.",
            "narrateur|Une goutte tombe encore du bois.",
            "narrateur|Elle fait un trou dans la terre noire.",
            "enfant-f|Tio tio.",
            "maman|C'était le merle.",
            "narrateur|Le chat part vers l'allée.",
            "narrateur|Chouchou reste près du tronc mouillé.",
            "maman|Tu voulais le merle.",
            "maman|Tu l'as eu.",
            "narrateur|Chouchou souffle sur la plume.",
            "narrateur|Elle tremble, puis se pose.",
            "enfant-f|Elle sent le jardin.",
            "maman|Oui.",
            "narrateur|Le cerisier goutte encore un peu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Une plume du merle reste dans l'herbe.",
            "narrateur|Chouchou tient la main de maman.",
            "enfant-f|Il a sifflé.",
            "maman|Oui.",
            "narrateur|La terre du jardin reste noire et grasse.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "siffle",
        "accepted_examples": "siffle | il siffle | tio tio | le cri | le merle",
        "retry_prompt": "Le merle siffle. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-08",
    "Le merle du jardin",
    "Chouchou veut le merle. Il siffle. Un chat miaule. Le merle s'envole. Une plume reste.",
    "- Pas une liste : un désir, puis le chat.\n"
    "- Troupe D16 : Chouchou, maman.\n"
    "- Fin : plume dans l'herbe.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.001-09  N3  Victorino, papa  — ferme, veau caché, hors de l'enclos
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-09",
    "Victorino veut le veau. Il se cache. Un meuglement guide. Ils le trouvent du sentier, hors de l'enclos.",
    "Le veau derrière la barrière",
    "Victorino, papa",
    "ferme, sentier le long de l'enclos",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le râtelier penche au bord du sentier.",
            "narrateur|Un brin de foin tombe dans la poussière.",
            "narrateur|Ça sent le lait tiède et la paille.",
            "narrateur|Une corde usée pend au piquet.",
            "papa|Tu sens le lait, Victorino ?",
            "enfant-m|Oui.",
            "enfant-m|Je veux le veau.",
            "papa|Celui de l'enclos ?",
            "enfant-m|Je l'ai entendu.",
            "narrateur|En ce moment, Victorino marche sur le sentier.",
            "narrateur|Le bois de la barrière est chaud et rêche.",
            "narrateur|L'enclos semble vide, tout calme.",
            "enfant-m|Il n'est pas là.",
            "papa|On reste sur le chemin.",
            "papa|On ne rentre pas dans l'enclos.",
            "narrateur|Victorino pose les deux mains sur le bois.",
            "narrateur|Un meuglement court arrive, tout bas.",
            "enfant-m|Là !",
            "papa|Tu as entendu ?",
            "enfant-m|Meuh, tout petit.",
            "papa|Le veau meugle.",
            "narrateur|Le cri vient du coin d'ombre.",
            "narrateur|Un tas de paille cache un flanc roux.",
            "enfant-m|Il se cache.",
            "papa|On le cherche du sentier ?",
            "enfant-m|Oui.",
            "narrateur|Ils avancent le long de la barrière.",
            "narrateur|Victorino ne passe pas la jambe.",
            "narrateur|Le meuglement revient, plus clair.",
            "enfant-m|Meuh.",
            "papa|C'est son cri.",
            "narrateur|Une oreille bouge dans le foin.",
            "narrateur|Puis un œil noir.",
            "narrateur|Victorino se baisse pour mieux voir.",
            "narrateur|Les genoux touchent la poussière du sentier.",
            "enfant-m|Il est petit.",
            "papa|C'est un veau.",
            "narrateur|Le foin cache encore le dos.",
            "narrateur|Le sentier sent le lait, tout près.",
            "enfant-m|Il meugle encore.",
            "papa|On avance le long du bois.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorino entend meuh.",
            "narrateur|Quel est le cri du veau ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le veau sort le museau du tas de paille.",
            "narrateur|Il meugle encore, tout près de la barrière.",
            "enfant-m|Je le vois.",
            "papa|Merci d'être resté sur le sentier.",
            "papa|On regarde de dehors.",
            "enfant-m|Il meugle.",
            "papa|Oui.",
            "papa|Meuh.",
            "narrateur|Victorino garde les mains sur le bois.",
            "narrateur|Il ne glisse pas les doigts entre les planches.",
            "papa|On reste hors de l'enclos ?",
            "enfant-m|Oui.",
            "narrateur|Le veau mâche un brin, de l'autre côté.",
            "narrateur|Sa langue est rose et rêche.",
            "narrateur|Le râtelier penche encore un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le flanc roux se lève tout entier.",
            "narrateur|Le veau n'est plus caché.",
            "enfant-m|Il était sous la paille.",
            "papa|Tu l'as trouvé avec les oreilles.",
            "papa|Puis avec les yeux.",
            "narrateur|Une corde usée tape le piquet.",
            "narrateur|Victorino reste sur la poussière du chemin.",
            "enfant-m|Meuh.",
            "papa|C'est son cri.",
            "narrateur|Le lait tiède sent encore autour de l'enclos.",
            "papa|Tu voulais le veau.",
            "papa|Le voilà, de ce côté-ci.",
            "narrateur|Un brin de foin tombe encore.",
            "narrateur|Il s'accroche à la barre du râtelier.",
            "enfant-m|Il mâche.",
            "papa|On le laisse.",
            "narrateur|La poussière du sentier colle aux genoux.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le veau mâche, de l'autre côté de la barrière.",
            "narrateur|Victorino prend la main de papa.",
            "enfant-m|On l'a trouvé.",
            "papa|Oui.",
            "narrateur|Le sentier reste hors de l'enclos, tout clair.",
        ],
    },
    EMPTY,
    {
        "expected_answer": "meuh",
        "accepted_examples": "meuh | il meugle | meugle | le cri | le veau",
        "retry_prompt": "Le veau meugle. Quel est le cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-09",
    "Le veau derrière la barrière",
    "Victorino veut le veau. Il se cache. Ils l'entendent, le trouvent du sentier, hors de l'enclos.",
    "- POS : rester hors de l'enclos.\n"
    "- Désir : trouver le veau, pas un catalogue.\n"
    "- Troupe D16 : Victorino, papa.",
)
