#!/usr/bin/env python3
"""F-NAR-008 — ATOM-AUT.RAN.001-01..08, leçon implicite (objet perdu sous le bazar)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import LIMITS, relecture, words, write_story


def q_lost(answer: str, examples: str, retry: str) -> dict:
    return {
        "expected_answer": answer,
        "accepted_examples": examples,
        "retry_prompt": retry,
    }


def preview(sid: str, age: str, scripts: dict) -> None:
    lim = LIMITS.get(age) or 12
    n = 0
    for cid, lines in scripts.items():
        for raw in lines:
            phrase = raw.split("|", 1)[1]
            w = words(phrase)
            n += w
            if w > lim:
                raise SystemExit(f"LONG {sid} {cid} {w}>{lim}: {phrase}")
    print(f"preview {sid} {n} mots")


# ---------------------------------------------------------------------------
# 01 N1 Raphaël — nappe à carreaux, cubes, gâteau, doudou sous la tour
# ---------------------------------------------------------------------------
S01 = {
    "CHK_T0000_P0000": [
        "narrateur|La cuillère en bois tape dans le bol.",
        "narrateur|Ça sent la vanille, tout chaud.",
        "narrateur|Une buée perle sur la vitre.",
        "narrateur|Une goutte glisse, tout doucement.",
        "papa|Le gâteau est bientôt prêt.",
        "maman|Il sent bon, papa.",
        "narrateur|Dans le salon, le tapis est épais.",
        "narrateur|Une nappe à carreaux attend.",
        "narrateur|Elle est encore pliée, sur la chaise.",
        "narrateur|Le tissu sent un peu le savon.",
        "narrateur|En ce moment, Raphaël est là.",
        "narrateur|Des cubes verts attendent.",
        "narrateur|Des cubes jaunes aussi.",
        "enfant-m|Je fais une tour, maman.",
        "maman|Pendant que le gâteau refroidit ?",
        "enfant-m|Oui, une tour haute.",
        "narrateur|Raphaël pose un cube vert.",
        "narrateur|Clic.",
        "narrateur|Puis un cube jaune.",
        "narrateur|Clic.",
        "narrateur|La tour grandit au milieu.",
        "papa|Elle est belle, ta tour.",
        "enfant-m|Le cube du haut, c'est le gâteau.",
        "maman|Un gâteau de cubes !",
        "narrateur|Le doudou gris est au pied.",
        "narrateur|Raphaël l'assoit contre la tour.",
        "enfant-m|Toi, tu goûtes avec nous.",
        "narrateur|Il pose encore un cube.",
        "narrateur|Clic.",
        "narrateur|Un cube jaune glisse.",
        "narrateur|La tour penche un peu.",
        "narrateur|Trois cubes tombent sur le doudou.",
        "enfant-m|Oh.",
        "papa|Ça a bougé.",
        "narrateur|Raphaël cherche du regard.",
        "enfant-m|Où est mon doudou ?",
        "maman|Sur la chaise, peut-être ?",
        "narrateur|Il va vers la chaise.",
        "narrateur|La nappe est là, seule.",
        "narrateur|Pas de tissu gris.",
        "enfant-m|Sous la nappe ?",
        "narrateur|Il soulève un coin doux.",
        "narrateur|Rien.",
        "papa|Près du canapé ?",
        "narrateur|Sa main passe sous le coussin.",
        "narrateur|Le coussin est moelleux.",
        "narrateur|Le doudou n'est pas là.",
        "enfant-m|Il est perdu.",
        "maman|La tour est encore au milieu.",
        "narrateur|Le tapis disparaît sous les cubes.",
        "enfant-m|Je veux voir dessous.",
        "narrateur|Raphaël prend le cube du haut.",
        "narrateur|Il le pose dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Le bois sent un peu la forêt.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Raphaël cherche son doudou.",
        "narrateur|Où est-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Un cube vert reste sur le tapis.",
        "narrateur|Raphaël le glisse dans la caisse.",
        "narrateur|Toc.",
        "maman|Tu regardes bien dessous ?",
        "enfant-m|Oui, maman.",
        "narrateur|La tour devient plus petite.",
        "narrateur|Un bout de tapis reparaît.",
        "papa|Encore un, tout doux.",
        "narrateur|Le cube jaune va dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Raphaël écarte un cube bas.",
        "narrateur|Un coin de tissu gris.",
        "enfant-m|Mon doudou !",
        "narrateur|Le doudou était sous la tour.",
        "narrateur|Il sent encore le lit.",
        "narrateur|Raphaël le serre contre sa joue.",
        "narrateur|Le tissu est chaud, tout doux.",
        "maman|Te voilà, petit.",
        "papa|Merci, tu l'as trouvé.",
        "enfant-m|Il était dessous.",
        "narrateur|La caisse a presque tous les cubes.",
        "narrateur|Le tapis est libre, au milieu.",
        "maman|La nappe peut s'ouvrir, maintenant.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Maman déplie la nappe à carreaux.",
        "narrateur|Raphaël tient un coin.",
        "narrateur|Les carreaux sont rouges et blancs.",
        "narrateur|La nappe est plate, enfin.",
        "papa|Le vrai gâteau peut s'asseoir.",
        "narrateur|Papa pose le plat chaud.",
        "narrateur|La vanille remplit le salon.",
        "enfant-m|Le doudou a un carreau.",
        "maman|Oui, le carreau rouge.",
        "narrateur|Raphaël casse un bout tiède.",
        "narrateur|La miette fond un peu.",
        "enfant-m|C'est bon, papa.",
        "papa|On est bien, ici.",
        "maman|Tu veux un peu d'eau ?",
        "enfant-m|Oui, maman.",
        "narrateur|L'eau fait un petit bruit.",
        "narrateur|Le soleil touche un carreau.",
        "narrateur|Le doudou reste contre lui.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le doudou a du gâteau.",
        "maman|Un tout petit bout.",
        "papa|Bravo, tu l'as retrouvé.",
        "narrateur|La vanille reste dans l'air.",
        "narrateur|Les carreaux sont chauds, maintenant.",
    ],
}
preview("ATOM-AUT.RAN.001-01", "N1", S01)
write_story(
    "ATOM-AUT.RAN.001-01",
    "Raphaël veut le gâteau sur la nappe à carreaux, avec son doudou. La tour recouvre le doudou. Il met les cubes dans la caisse pour voir dessous. Le doudou apparaît. Ils goûtent.",
    "La nappe à carreaux",
    "Raphaël, papa, maman",
    "cuisine à la vanille, salon, nappe à carreaux, après-midi du gâteau",
    S01,
    {},
    q_lost(
        "le doudou",
        "le doudou | doudou | sous la tour | sous les cubes | dessous",
        "Il cherche sous les cubes. Où est le doudou ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-01",
    "La nappe à carreaux",
    "Raphaël veut le gâteau sur la nappe. Doudou assis au pied de la tour, cubes tombent dessus. Cherche chaise, nappe, canapé. Cubes dans la caisse. Doudou sous la tour. Nappe plate, vanille.",
    "Pas de ranger dit. Question = où est le doudou. Fin = carreaux chauds.",
)


# ---------------------------------------------------------------------------
# 02 N2 Nina — cacao, peluches, ours perdu sous le pique-nique
# ---------------------------------------------------------------------------
S02 = {
    "CHK_T0000_P0000": [
        "narrateur|Trois notes sortent de la boîte à musique.",
        "narrateur|Ding.",
        "narrateur|Puis plus rien.",
        "narrateur|Une chaussette sèche sur la chaise.",
        "narrateur|Elle est encore un peu tiède.",
        "narrateur|Dehors, les feuilles sont mouillées.",
        "papa|Il fait frais, ce soir.",
        "maman|Le cacao est sur le feu.",
        "narrateur|Dans la chambre, le tapis est épais.",
        "narrateur|Un ours en peluche attend sur l'oreiller.",
        "narrateur|Il est tout doux, un peu chaud.",
        "narrateur|En ce moment, Nina est à genoux.",
        "narrateur|Elle prend l'ours contre sa joue.",
        "enfant-f|Toi, tu viens au tapis.",
        "narrateur|Un lapin et une poule attendent déjà.",
        "narrateur|Nina pose trois tasses en bois.",
        "narrateur|Les tasses font clic.",
        "enfant-f|C'est un pique-nique !",
        "maman|Un pique-nique pour les peluches.",
        "narrateur|Nina donne une tasse à l'ours.",
        "narrateur|Elle donne une tasse au lapin.",
        "narrateur|La poule a la petite tasse.",
        "papa|Ils sont bien installés.",
        "enfant-f|Ils boivent du cacao, papa.",
        "papa|Du cacao en bois, alors.",
        "narrateur|Nina souffle au-dessus d'une tasse.",
        "enfant-f|Ffff.",
        "maman|Le vrai cacao arrive bientôt.",
        "enfant-f|On le boit ici, sur le tapis ?",
        "maman|Oui, au milieu, tout chaud.",
        "narrateur|Maman entre avec la grande tasse.",
        "narrateur|Ça sent le cacao, tout près.",
        "narrateur|Une petite vapeur monte.",
        "narrateur|Nina cherche un rond pour la tasse.",
        "narrateur|Une tasse en bois est déjà là.",
        "narrateur|La patte du lapin est dessus.",
        "enfant-f|L'ours veut le vrai cacao aussi.",
        "maman|Où est-il, ton ours ?",
        "narrateur|Nina regarde l'oreiller.",
        "narrateur|L'oreiller est plat, vide.",
        "enfant-f|Il n'est plus sur le lit.",
        "papa|Sous la couverture ?",
        "narrateur|Elle soulève la couverture rose.",
        "narrateur|Rien, seulement le drap tiède.",
        "enfant-f|Il est perdu.",
        "narrateur|Les peluches et les tasses couvrent le tapis.",
        "enfant-f|Je n'ai pas de place.",
        "maman|Il faut un petit rond, au milieu.",
        "narrateur|Nina prend une tasse en bois.",
        "narrateur|Elle la pose dans la caisse ronde.",
        "narrateur|Clic.",
        "enfant-f|Je cherche dessous.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nina cherche son ours.",
        "narrateur|Où est-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|La deuxième tasse va dans la caisse.",
        "narrateur|Clic.",
        "narrateur|Nina prend le lapin tout doux.",
        "narrateur|Elle le glisse dans la caisse.",
        "maman|Tu regardes bien sous les peluches ?",
        "enfant-f|Oui, maman.",
        "narrateur|La poule est encore au milieu.",
        "papa|Un coin de tapis reparaît.",
        "narrateur|Nina soulève la poule.",
        "narrateur|Un museau brun est dessous.",
        "enfant-f|Mon ours !",
        "narrateur|L'ours était sous la poule.",
        "narrateur|Une tasse en bois l'avait caché.",
        "narrateur|Nina le serre contre sa joue.",
        "narrateur|Le poil est chaud, un peu écrasé.",
        "papa|Merci, tu l'as trouvé.",
        "enfant-f|Il buvait en dessous.",
        "maman|Te voilà, petit ours.",
        "narrateur|La dernière tasse va dans la caisse.",
        "narrateur|Le tapis a un rond vide, au milieu.",
        "narrateur|Nina pose l'ours contre son genou.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Maman pose la vraie tasse au milieu.",
        "narrateur|La vapeur sent le cacao.",
        "enfant-f|Il est chaud.",
        "papa|On souffle un peu.",
        "narrateur|Nina souffle.",
        "narrateur|Ffff.",
        "narrateur|Elle boit une petite gorgée.",
        "narrateur|Le cacao est doux, un peu sucré.",
        "enfant-f|L'ours a une goutte, papa.",
        "papa|Une toute petite goutte.",
        "maman|Tu veux encore un peu ?",
        "enfant-f|Oui, maman.",
        "narrateur|La pluie tapote plus doucement.",
        "narrateur|La chaussette sur la chaise est sèche.",
        "narrateur|Nina tient l'ours d'une main.",
        "narrateur|De l'autre, elle tient la tasse.",
        "maman|On est bien, ici.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|L'ours a bu du cacao.",
        "maman|Toi aussi.",
        "papa|Bravo, tu l'as retrouvé.",
        "narrateur|La vapeur s'en va tout doux.",
        "narrateur|Le tapis reste chaud sous les genoux.",
    ],
}
preview("ATOM-AUT.RAN.001-02", "N2", S02)
write_story(
    "ATOM-AUT.RAN.001-02",
    "Nina veut le vrai cacao sur le tapis, avec son ours. L'ours disparaît sous le pique-nique. Elle met tasses et peluches dans la caisse pour chercher. L'ours apparaît sous la poule. Ils boivent.",
    "Le cacao de Nina",
    "Nina, papa, maman",
    "chambre, pluie, boîte à musique, fin d'après-midi un peu froide",
    S02,
    {},
    q_lost(
        "l'ours",
        "l'ours | ours | nounours | sous la poule | sous les peluches | dessous",
        "Elle cherche sous les peluches. Où est l'ours ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-02",
    "Le cacao de Nina",
    "Nina veut le cacao au milieu du tapis. Ours au pique-nique, perdu sous poule et tasses. Cherche lit, couverture. Tasses et peluches dans la caisse. Ours sous la poule. Cacao.",
    "Pas de ranger dit. Question = où est l'ours. Fin = tapis chaud.",
)


# ---------------------------------------------------------------------------
# 03 N3 Amir — pain chaud, cubes, voitures, doudou sous la maison puis les voitures
# ---------------------------------------------------------------------------
S03 = {
    "CHK_T0000_P0000": [
        "narrateur|Au loin, une clochette de vélo.",
        "narrateur|Ting.",
        "narrateur|Papa a de la farine sur le tablier.",
        "narrateur|Une baguette craque quand il la casse.",
        "narrateur|L'odeur du pain chaud remplit la maison.",
        "maman|Il est encore tout chaud.",
        "papa|Oui, il craque.",
        "narrateur|Le couloir est un peu frais.",
        "narrateur|Le tapis du salon est épais.",
        "narrateur|En ce moment, Amir est à genoux.",
        "narrateur|Des cubes rouges et bleus attendent.",
        "enfant-m|Je fais la boulangerie, maman.",
        "maman|Une maison pour le pain ?",
        "enfant-m|Oui, avec une porte.",
        "narrateur|Amir pose un cube rouge.",
        "narrateur|Puis un cube bleu.",
        "narrateur|La maison grandit au milieu du tapis.",
        "narrateur|Les cubes font un bruit sec.",
        "papa|Ta maison a une porte ?",
        "enfant-m|Une petite porte, papa.",
        "narrateur|Amir laisse un trou.",
        "narrateur|C'est la porte de la boulangerie.",
        "narrateur|Le doudou beige est assis contre le mur.",
        "enfant-m|Toi, tu attends le pain.",
        "narrateur|Papa pose un morceau tiède près de la porte.",
        "enfant-m|Les voitures vont le livrer.",
        "papa|Jusqu'au bout du couloir ?",
        "enfant-m|Oui, on le mange là-bas.",
        "narrateur|Amir prend une petite voiture rouge.",
        "narrateur|Les roues font un bruit léger.",
        "narrateur|La voiture avance.",
        "narrateur|Elle bute contre un cube.",
        "narrateur|Un pan de la maison glisse.",
        "narrateur|Des cubes tombent sur le doudou.",
        "enfant-m|Oh.",
        "maman|La maison a bougé.",
        "narrateur|Amir cherche le tissu beige.",
        "enfant-m|Où est mon doudou ?",
        "papa|Derrière la porte de la boulangerie ?",
        "narrateur|Amir regarde le trou.",
        "narrateur|Seulement le pain tiède.",
        "enfant-m|Sous la table ?",
        "narrateur|Il se penche.",
        "narrateur|L'ombre est vide.",
        "enfant-m|Il est perdu.",
        "maman|Les cubes sont encore tout autour.",
        "enfant-m|Je veux voir dessous.",
        "narrateur|Amir prend un cube rouge.",
        "narrateur|Il le pose dans la caisse en bois.",
        "narrateur|Toc.",
        "narrateur|Le bois sent un peu la forêt.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Amir cherche son doudou.",
        "narrateur|Où est-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Un cube bleu va dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Amir écarte encore un mur.",
        "maman|Tu regardes bien sous la maison ?",
        "enfant-m|Oui, maman.",
        "narrateur|Le tapis reparaît, un peu.",
        "narrateur|Pas de tissu beige.",
        "papa|Peut-être plus loin, vers le couloir.",
        "narrateur|Amir prend le morceau de pain.",
        "narrateur|Il le pose sur la voiture rouge.",
        "enfant-m|On va au bout.",
        "narrateur|Le couloir est un peu frais.",
        "narrateur|D'autres petites voitures attendent.",
        "narrateur|Une voiture bleue barre le chemin.",
        "narrateur|Une jaune aussi.",
        "enfant-m|Elles cachent le sol.",
        "narrateur|Amir glisse la bleue dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Puis la jaune.",
        "narrateur|Un bout de tissu dépasse près de la porte.",
        "enfant-m|Mon doudou !",
        "narrateur|Le doudou était sous les voitures.",
        "narrateur|Il sent encore le tapis du salon.",
        "narrateur|Amir le serre contre sa joue.",
        "papa|Merci, tu l'as trouvé.",
        "maman|Te voilà, petit.",
        "enfant-m|Il était sous les roues.",
        "narrateur|Le bout du couloir est libre, maintenant.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|L'horloge fait tic-tac, tout doux.",
        "narrateur|Amir s'assoit au bout du couloir.",
        "narrateur|Le doudou est sur ses genoux.",
        "narrateur|Papa lui tend le morceau de pain.",
        "narrateur|La croûte craque encore.",
        "enfant-m|Il est chaud.",
        "maman|On le mange ici, comme prévu.",
        "papa|Tu veux une petite miette pour lui ?",
        "enfant-m|Une toute petite.",
        "narrateur|Amir pose une miette sur le tissu.",
        "narrateur|Le doudou reste bien droit.",
        "narrateur|L'odeur du pain remplit le couloir.",
        "maman|On est bien, ici.",
        "enfant-m|La voiture a fini la course.",
        "papa|Oui, jusqu'au bout.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|Le doudou a du pain.",
        "maman|Toi aussi.",
        "papa|Bravo, tu l'as retrouvé.",
        "narrateur|La farine reste un peu sur le tablier.",
        "narrateur|Le couloir sent encore la croûte chaude.",
    ],
}
preview("ATOM-AUT.RAN.001-03", "N3", S03)
write_story(
    "ATOM-AUT.RAN.001-03",
    "Amir veut livrer le pain chaud au bout du couloir, avec son doudou. La maison de cubes tombe sur le doudou. Il cherche, met cubes puis voitures dans la caisse. Le doudou apparaît sous les voitures. Ils goûtent.",
    "Le pain d'Amir",
    "Amir, papa, maman",
    "salon puis couloir, farine, clochette de vélo, après la fournée",
    S03,
    {},
    q_lost(
        "le doudou",
        "le doudou | doudou | sous les voitures | sous les cubes | dessous | près de la porte",
        "Il cherche sous les cubes et les voitures. Où est le doudou ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-03",
    "Le pain d'Amir",
    "Amir veut le pain au bout du couloir. Doudou contre la boulangerie, cubes tombent. Cherche porte, table. Cubes dans la caisse, pas encore. Voitures du couloir dans la caisse. Doudou sous les roues. Pain chaud.",
    "Pas de ranger dit. Question = où est le doudou. Fin = croûte chaude.",
)


# ---------------------------------------------------------------------------
# 04 N1 Sarah — cabane sous la table, voitures bleues, doudou sous les voitures
# ---------------------------------------------------------------------------
S04 = {
    "CHK_T0000_P0000": [
        "narrateur|Une ombre de chaise coupe le tapis.",
        "narrateur|L'ombre est longue, un peu froide.",
        "narrateur|La nappe sent encore le savon.",
        "narrateur|Une cuillère tinte, loin, dans un verre.",
        "papa|J'essuie la table, Sarah.",
        "maman|Je prends un coussin.",
        "narrateur|Sous la table, il fait sombre.",
        "narrateur|C'est calme, tout petit.",
        "narrateur|En ce moment, Sarah glisse dessous.",
        "narrateur|Ses genoux trouvent le tapis.",
        "narrateur|Des voitures bleues attendent.",
        "narrateur|Elles sont lisses, un peu froides.",
        "enfant-f|Elles roulent, papa.",
        "papa|Elles roulent dans l'ombre.",
        "narrateur|Sarah pousse une voiture.",
        "narrateur|Vroom.",
        "narrateur|Puis une autre.",
        "narrateur|Vroom.",
        "narrateur|Elle aligne trois voitures bleues.",
        "narrateur|Elles se touchent, tout doucement.",
        "maman|C'est un parking ?",
        "enfant-f|Oui, sous la table.",
        "narrateur|Le doudou rose est près d'elle.",
        "enfant-f|Toi, tu restes dans la cabane.",
        "narrateur|Sarah le pose contre un pied.",
        "narrateur|Une voiture glisse vers lui.",
        "narrateur|Puis une autre.",
        "narrateur|Les voitures le recouvrent un peu.",
        "enfant-f|Après, c'est ma cabane.",
        "maman|Avec le coussin ?",
        "enfant-f|Oui, une cabane.",
        "narrateur|Maman tend le coussin.",
        "narrateur|Il est moelleux.",
        "narrateur|Sarah veut le glisser dessous.",
        "narrateur|Une voiture touche son genou.",
        "enfant-f|Aïe.",
        "papa|La voiture est là.",
        "enfant-f|Où est mon doudou ?",
        "maman|Sur la chaise, peut-être ?",
        "narrateur|Sarah sort la tête.",
        "narrateur|La chaise est vide.",
        "enfant-f|Dans le coussin ?",
        "narrateur|Elle fouille le tissu.",
        "narrateur|Rien.",
        "enfant-f|Il est perdu.",
        "papa|Les voitures sont encore au sol.",
        "enfant-f|Je veux voir dessous.",
        "narrateur|Sarah prend une voiture bleue.",
        "narrateur|Elle la pose dans la caisse bleue.",
        "narrateur|Clac.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Sarah cherche son doudou.",
        "narrateur|Où est-il ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Une deuxième voiture va dans la caisse.",
        "narrateur|Clac.",
        "maman|Tu regardes bien sous les roues ?",
        "enfant-f|Oui, maman.",
        "narrateur|Un bout de tapis reparaît.",
        "papa|Encore une, tout doux.",
        "narrateur|Sarah glisse la troisième.",
        "narrateur|Clac.",
        "narrateur|Un coin de tissu rose.",
        "enfant-f|Mon doudou !",
        "narrateur|Le doudou était sous les voitures.",
        "narrateur|Il sent encore le savon de la nappe.",
        "narrateur|Sarah le serre contre sa joue.",
        "narrateur|Le tissu est chaud, tout doux.",
        "papa|Merci, tu l'as trouvé.",
        "maman|Te voilà, petit.",
        "enfant-f|Il était dessous.",
        "narrateur|La caisse bleue est presque pleine.",
        "narrateur|Sous la table, le tapis est libre.",
        "narrateur|L'ombre de la chaise reste là.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Sarah glisse le coussin sous la table.",
        "narrateur|Le coussin est moelleux.",
        "enfant-f|C'est ma cabane.",
        "maman|Une cabane toute douce.",
        "narrateur|Elle s'assoit, le doudou sur les genoux.",
        "narrateur|La nappe fait un plafond.",
        "papa|On frappe avant d'entrer ?",
        "enfant-f|Toc toc.",
        "papa|On peut entrer ?",
        "enfant-f|Oui, papa.",
        "narrateur|Papa se penche un peu.",
        "narrateur|L'ombre est calme, maintenant.",
        "maman|Tu veux un peu d'eau ?",
        "enfant-f|Oui, maman.",
        "narrateur|Sarah boit une gorgée.",
        "narrateur|Le doudou reste contre elle.",
        "narrateur|Une ligne claire est encore au sol.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Le doudou est dans la cabane.",
        "maman|Toi aussi.",
        "papa|Bravo, tu l'as retrouvé.",
        "narrateur|La nappe sent encore le savon.",
        "narrateur|L'ombre de la chaise est douce, maintenant.",
    ],
}
preview("ATOM-AUT.RAN.001-04", "N1", S04)
write_story(
    "ATOM-AUT.RAN.001-04",
    "Sarah veut une cabane sous la table, avec son doudou. Les voitures bleues recouvrent le doudou. Elle les met dans la caisse pour voir dessous. Le doudou apparaît. La cabane est douce.",
    "La cabane sous la table",
    "Sarah, papa, maman",
    "salon, sous la table, nappe savon, après le déjeuner",
    S04,
    {},
    q_lost(
        "le doudou",
        "le doudou | doudou | sous les voitures | dessous | sous les roues",
        "Elle cherche sous les voitures. Où est le doudou ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-04",
    "La cabane sous la table",
    "Sarah veut la cabane. Doudou contre le pied, voitures glissent dessus. Cherche chaise, coussin. Voitures dans la caisse bleue. Doudou sous les roues. Coussin, nappe-plafond.",
    "Pas de ranger dit. Question = où est le doudou. Fin = ombre douce.",
)


# ---------------------------------------------------------------------------
# 05 N2 Victorino — voitures, merle, voiture rouge perdue sous la route
# ---------------------------------------------------------------------------
S05 = {
    "CHK_T0000_P0000": [
        "narrateur|Une odeur d'orange entre dans la chambre.",
        "narrateur|Maman a pelé un fruit, dans la cuisine.",
        "narrateur|La lumière est couleur de miel.",
        "narrateur|Une abeille bourdonne dehors.",
        "narrateur|Puis elle s'en va.",
        "papa|Tu as entendu l'abeille, Victorino ?",
        "enfant-m|Oui, papa, elle est partie.",
        "narrateur|Le rideau est à moitié fermé.",
        "narrateur|Un merle est sur la gouttière.",
        "narrateur|On l'entend un peu.",
        "maman|Il chante tout doux.",
        "narrateur|Le tapis de la chambre est épais.",
        "narrateur|En ce moment, Victorino est à genoux.",
        "narrateur|Il a des voitures rouges et bleues.",
        "narrateur|Il fait une route.",
        "narrateur|La route va de la fenêtre jusqu'au lit.",
        "enfant-m|Vroom.",
        "papa|Ta route est longue.",
        "narrateur|La voiture rouge avance en tête.",
        "narrateur|Une voiture bleue la suit.",
        "narrateur|Les roues font un petit bruit.",
        "narrateur|Victorino pose les mains en pont.",
        "enfant-m|C'est un garage, papa.",
        "papa|Un garage au bord de la route.",
        "enfant-m|Après, tu racontes, maman ?",
        "maman|Oui, au lit, avec le rideau ouvert.",
        "enfant-m|La rouge vient avec moi.",
        "narrateur|Victorino la pousse vers le lit.",
        "narrateur|D'autres voitures se poussent.",
        "narrateur|La bleue passe par-dessus.",
        "narrateur|La rouge disparaît sous la pile.",
        "enfant-m|Oh.",
        "papa|Elles se sont bousculées.",
        "enfant-m|Où est ma voiture rouge ?",
        "maman|Sous le lit, peut-être ?",
        "narrateur|Victorino se penche.",
        "narrateur|De la poussière, un chausson.",
        "narrateur|Pas de rouge.",
        "enfant-m|Dans le garage ?",
        "narrateur|Il ouvre ses deux mains.",
        "narrateur|Le pont de doigts est vide.",
        "enfant-m|Elle est perdue.",
        "papa|La route est encore au sol.",
        "enfant-m|Je veux voir dessous.",
        "narrateur|Victorino prend une voiture bleue.",
        "narrateur|Il la pose dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Le bois glisse un peu.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Victorino cherche sa voiture rouge.",
        "narrateur|Où est-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Une autre bleue va dans la caisse.",
        "narrateur|Toc.",
        "maman|Tu regardes bien sous la route ?",
        "enfant-m|Oui, maman.",
        "narrateur|Un bout de tapis reparaît.",
        "papa|Encore une, tout doux.",
        "narrateur|Victorino soulève une voiture noire.",
        "narrateur|Un toit rouge brille dessous.",
        "enfant-m|Ma rouge !",
        "narrateur|La voiture rouge était sous les autres.",
        "narrateur|Elle sent encore le tapis.",
        "narrateur|Victorino la tient dans la paume.",
        "narrateur|Le métal est un peu froid.",
        "papa|Merci, tu l'as trouvée.",
        "maman|Te voilà, petite rouge.",
        "enfant-m|Elle était dessous.",
        "narrateur|Les dernières voitures vont dans la caisse.",
        "narrateur|Le chemin du lit est libre.",
        "narrateur|Le merle chante encore un peu.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Victorino pousse la caisse sous le lit.",
        "narrateur|Le bois glisse tout doucement.",
        "enfant-m|On ouvre le rideau ?",
        "papa|Oui, tout grand.",
        "narrateur|Le merle est encore sur la gouttière.",
        "narrateur|Il penche la tête.",
        "narrateur|Victorino grimpe sur le lit.",
        "narrateur|La voiture rouge est sur l'oreiller.",
        "maman|Je raconte ?",
        "enfant-m|Oui, maman.",
        "narrateur|Maman s'assoit au bord.",
        "narrateur|Sa voix est basse, tout près.",
        "papa|Tu veux un quartier d'orange ?",
        "enfant-m|Oui, papa.",
        "narrateur|L'orange sent fort, sucrée.",
        "narrateur|Le jus brille un peu sur le doigt.",
        "narrateur|Le merle écoute aussi, on dirait.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|La rouge est sur l'oreiller.",
        "maman|Toi aussi, tu es bien.",
        "papa|Bravo, tu l'as retrouvée.",
        "narrateur|L'odeur d'orange reste dans la chambre.",
        "narrateur|Le merle se tait, tout doux.",
    ],
}
preview("ATOM-AUT.RAN.001-05", "N2", S05)
write_story(
    "ATOM-AUT.RAN.001-05",
    "Victorino veut l'histoire au lit avec sa voiture rouge, et voir le merle. Les autres voitures recouvrent la rouge. Il les met dans la caisse pour chercher. La rouge apparaît. Rideau, orange, merle.",
    "La voiture rouge",
    "Victorino, papa, maman",
    "chambre, lumière de miel, odeur d'orange, merle sur la gouttière",
    S05,
    {},
    q_lost(
        "la voiture rouge",
        "la voiture rouge | la rouge | voiture rouge | sous la route | sous les voitures | dessous",
        "Il cherche sous les voitures. Où est la voiture rouge ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-05",
    "La voiture rouge",
    "Victorino veut l'histoire au lit avec la rouge. Pile de voitures, la rouge disparaît. Cherche sous le lit, dans les mains. Voitures dans la caisse. Rouge sous la noire. Rideau, merle, orange.",
    "Pas de ranger dit. Question = où est la voiture rouge. Fin = merle se tait.",
)


# ---------------------------------------------------------------------------
# 06 N1 Mila — radiateur, cubes, chaussettes de laine perdues sous la tour
# ---------------------------------------------------------------------------
S06 = {
    "CHK_T0000_P0000": [
        "narrateur|Le radiateur chante un tout petit air.",
        "narrateur|Psss.",
        "narrateur|Des chaussettes de laine attendent.",
        "narrateur|Elles sont épaisses, près du canapé.",
        "narrateur|Elles sentent le linge propre.",
        "maman|Les chaussettes sont chaudes, papa.",
        "papa|Oui, on les laisse près du chaud.",
        "narrateur|Une caisse en bois est au salon.",
        "narrateur|Elle sent un peu la forêt.",
        "narrateur|En ce moment, Mila est près du canapé.",
        "narrateur|Elle touche un cube.",
        "narrateur|Le cube est lisse.",
        "enfant-f|Il est chaud, papa.",
        "papa|C'est le radiateur, Mila.",
        "enfant-f|Je fais une petite tour.",
        "maman|Une tour, avant les chaussettes ?",
        "enfant-f|Oui, une tour petite.",
        "narrateur|Mila pose un cube.",
        "narrateur|Puis un autre cube.",
        "narrateur|Clic.",
        "narrateur|Elle fait une petite tour.",
        "papa|Ta tour est jolie.",
        "enfant-f|Elle est petite, papa.",
        "narrateur|Mila pose un cube rouge.",
        "narrateur|Clic.",
        "narrateur|La tour grandit un peu.",
        "narrateur|Ses pieds sont près du radiateur.",
        "enfant-f|Après, les chaussettes chaudes.",
        "maman|Oui, pour les orteils.",
        "narrateur|Mila pose encore un cube.",
        "narrateur|La tour penche vers les chaussettes.",
        "narrateur|Deux cubes glissent.",
        "narrateur|Ils tombent sur la laine.",
        "enfant-f|Oh.",
        "papa|La tour a bougé.",
        "enfant-f|Où sont mes chaussettes ?",
        "maman|Sur le canapé, peut-être ?",
        "narrateur|Mila monte un genou.",
        "narrateur|Le coussin est vide.",
        "enfant-f|Dans mes mains ?",
        "narrateur|Elle ouvre les paumes.",
        "narrateur|Rien.",
        "enfant-f|Elles sont perdues.",
        "papa|Les cubes sont encore au pied.",
        "enfant-f|Je veux voir dessous.",
        "narrateur|Mila prend un cube.",
        "narrateur|Elle le pose dans la caisse.",
        "narrateur|Toc.",
        "narrateur|Une petite voiture attend aussi.",
        "narrateur|Elle va dans la caisse.",
        "narrateur|Toc.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Mila cherche ses chaussettes.",
        "narrateur|Où sont-elles ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Un cube rouge reste au sol.",
        "narrateur|Mila le glisse dans la caisse.",
        "narrateur|Toc.",
        "maman|Tu regardes bien sous la tour ?",
        "enfant-f|Oui, maman.",
        "narrateur|Un bout de tapis reparaît.",
        "papa|Encore un, tout doux.",
        "narrateur|Mila écarte le dernier cube.",
        "narrateur|Un coin de laine épaisse.",
        "enfant-f|Mes chaussettes !",
        "narrateur|Les chaussettes étaient sous la tour.",
        "narrateur|Elles sont encore chaudes.",
        "narrateur|Mila les serre contre sa joue.",
        "narrateur|La laine sent le savon.",
        "papa|Merci, tu les as trouvées.",
        "maman|Te voilà, petite laine.",
        "enfant-f|Elles étaient dessous.",
        "narrateur|La caisse a les cubes, maintenant.",
        "narrateur|Le tapis près du radiateur est libre.",
        "narrateur|Le radiateur chante encore un peu.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Maman tend les chaussettes.",
        "narrateur|Mila enfile la première.",
        "narrateur|Puis la deuxième.",
        "enfant-f|Elles sont douces.",
        "papa|Les orteils sont au chaud.",
        "narrateur|Mila s'assoit près du radiateur.",
        "narrateur|Le métal chante tout bas.",
        "maman|On reste un moment ?",
        "enfant-f|Oui, maman.",
        "narrateur|Ses pieds touchent le tapis libre.",
        "narrateur|La laine est épaisse, un peu lourde.",
        "papa|Tu veux le livre du canard ?",
        "enfant-f|Oui, papa.",
        "narrateur|Papa ouvre le livre.",
        "narrateur|La couverture est lisse.",
        "narrateur|Mila pose un pied sur l'autre.",
        "narrateur|Les chaussettes restent bien chaudes.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-f|Mes pieds sont au chaud.",
        "maman|La laine a été retrouvée.",
        "papa|Bravo, tu les as trouvées.",
        "narrateur|Le radiateur chante encore.",
        "narrateur|La laine reste douce sur les orteils.",
    ],
}
preview("ATOM-AUT.RAN.001-06", "N1", S06)
write_story(
    "ATOM-AUT.RAN.001-06",
    "Mila veut les chaussettes de laine près du radiateur. La tour de cubes tombe dessus. Elle cherche, met cubes et voiture dans la caisse. Les chaussettes apparaissent. Pieds au chaud, livre du canard.",
    "Les chaussettes du radiateur",
    "Mila, papa, maman",
    "salon, soir, radiateur, laine et caisse de bois",
    S06,
    {},
    q_lost(
        "les chaussettes",
        "les chaussettes | chaussettes | la laine | sous la tour | sous les cubes | dessous",
        "Elle cherche sous les cubes. Où sont les chaussettes ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-06",
    "Les chaussettes du radiateur",
    "Mila veut les chaussettes chaudes. Tour penche, cubes sur la laine. Cherche canapé, mains. Cubes et voiture dans la caisse. Chaussettes sous la tour. Orteils, livre du canard.",
    "Pas de ranger dit. Question = où sont les chaussettes. Fin = laine sur les orteils.",
)


# ---------------------------------------------------------------------------
# 07 N3 Aniss — ferme, perles, histoire au lit, vache perdue sous la ferme
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|Un papillon de nuit frappe la vitre.",
        "narrateur|Tout doucement.",
        "narrateur|L'air sent la terre mouillée.",
        "narrateur|La fenêtre est un peu ouverte.",
        "narrateur|Le plancher craque.",
        "maman|Le soir est calme.",
        "papa|Oui, un petit soir doux.",
        "narrateur|Des animaux en bois attendent en rang.",
        "narrateur|La vache est lisse.",
        "narrateur|Le cheval sent le bois.",
        "narrateur|En ce moment, Aniss est à genoux.",
        "narrateur|Il est dans le rond d'or de la lampe.",
        "enfant-m|C'est une ferme, maman.",
        "maman|Une ferme sur le tapis.",
        "narrateur|Aniss pose la vache.",
        "narrateur|Il pose le cheval.",
        "narrateur|Les bêtes tapent doucement.",
        "narrateur|Il pose aussi un mouton.",
        "papa|Elles sont bien, tes bêtes.",
        "enfant-m|La vache mange, papa.",
        "maman|Et le mouton ?",
        "enfant-m|Il dort près de la vache.",
        "narrateur|Aniss sort des perles.",
        "narrateur|Elles sont rondes.",
        "narrateur|Elles brillent un peu dans la lampe.",
        "enfant-m|Je fais un collier pour la vache.",
        "maman|Un collier tout doux.",
        "narrateur|Aniss enfile une perle.",
        "narrateur|Puis une autre perle.",
        "narrateur|Les perles font un tout petit bruit.",
        "narrateur|Il pose le collier sur le cou de la vache.",
        "enfant-m|Elle est belle.",
        "papa|Oui, elle est belle.",
        "enfant-m|Après, tu racontes une histoire, maman ?",
        "maman|Oui, près de toi, au lit.",
        "enfant-m|La vache vient aussi.",
        "narrateur|Maman s'approche du tapis.",
        "narrateur|Le cheval bascule.",
        "narrateur|Une perle roule.",
        "narrateur|Le mouton glisse sur la vache.",
        "enfant-m|Oh.",
        "papa|La ferme a bougé.",
        "enfant-m|Où est ma vache ?",
        "maman|Sous le lit, peut-être ?",
        "narrateur|Aniss se penche dans l'ombre.",
        "narrateur|Le bois du lit est froid.",
        "narrateur|Pas de vache.",
        "enfant-m|Dans le rond d'or ?",
        "narrateur|Il cherche au milieu de la lumière.",
        "narrateur|Des perles, le cheval, le mouton.",
        "enfant-m|Elle est perdue.",
        "maman|J'ai besoin d'un petit coin, pour raconter.",
        "enfant-m|Je veux voir dessous.",
        "narrateur|Aniss prend le cheval.",
        "narrateur|Il le pose dans la caisse.",
        "narrateur|Toc.",
        "narrateur|La caisse sent le bois.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Aniss cherche sa vache.",
        "narrateur|Où est-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le mouton va dans la caisse.",
        "narrateur|Toc.",
        "maman|Tu regardes bien sous les bêtes ?",
        "enfant-m|Oui, maman.",
        "narrateur|Aniss ramasse une perle.",
        "narrateur|Puis une autre.",
        "narrateur|Elles cliquettent dans la caisse.",
        "papa|Un bout de tapis reparaît.",
        "narrateur|Sous le dernier mouton, un dos lisse.",
        "enfant-m|Ma vache !",
        "narrateur|La vache était sous le mouton.",
        "narrateur|Le collier est encore autour du cou.",
        "narrateur|Aniss la serre dans ses deux mains.",
        "narrateur|Le bois est tiède, un peu lisse.",
        "papa|Merci, tu l'as trouvée.",
        "maman|Te voilà, petite vache.",
        "enfant-m|Elle dormait dessous.",
        "narrateur|Les dernières perles vont dans la caisse.",
        "narrateur|Le rond d'or est vide, au milieu.",
        "narrateur|Le tapis est libre près du lit.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Aniss grimpe sur le lit.",
        "narrateur|La vache est sur la couverture.",
        "narrateur|Le collier brille un peu.",
        "maman|Je m'assoie ?",
        "enfant-m|Oui, maman.",
        "narrateur|Maman s'assoit au bord.",
        "narrateur|Sa voix est basse, tout près.",
        "papa|Tu veux un verre d'eau, avant ?",
        "enfant-m|Une gorgée, papa.",
        "narrateur|L'eau est tiède.",
        "narrateur|Aniss pose la vache contre l'oreiller.",
        "narrateur|Le papillon de nuit repose sur la vitre.",
        "maman|On écoute l'histoire, maintenant.",
        "enfant-m|La vache écoute aussi.",
        "papa|Oui, tout le monde écoute.",
        "narrateur|La lampe fait encore son rond d'or.",
        "narrateur|L'air sent la terre mouillée.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|La vache est sur l'oreiller.",
        "maman|Toi aussi, tu es bien.",
        "papa|Bravo, tu l'as retrouvée.",
        "narrateur|Le papillon repose ses ailes.",
        "narrateur|Le rond d'or reste sur la couverture.",
    ],
}
preview("ATOM-AUT.RAN.001-07", "N3", S07)
write_story(
    "ATOM-AUT.RAN.001-07",
    "Aniss veut l'histoire au lit avec sa vache en bois. Le mouton et les perles la recouvrent. Il cherche, met bêtes et perles dans la caisse. La vache apparaît. Maman raconte.",
    "La vache d'or",
    "Aniss, papa, maman",
    "chambre, soir, lampe ronde, papillon de nuit, fenêtre entrouverte",
    S07,
    {},
    q_lost(
        "la vache",
        "la vache | vache | sous le mouton | sous la ferme | dessous | sous les bêtes",
        "Il cherche sous les bêtes. Où est la vache ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-07",
    "La vache d'or",
    "Aniss veut l'histoire au lit avec la vache. Ferme bascule, mouton sur la vache. Cherche sous le lit, dans le rond d'or. Cheval, mouton, perles dans la caisse. Vache sous le mouton. Couverture, voix basse.",
    "Pas de ranger dit. Question = où est la vache. Fin = rond d'or sur la couverture.",
)


# ---------------------------------------------------------------------------
# 08 N2 Nino — pont de cubes, petite voiture perdue, linge chaud
# ---------------------------------------------------------------------------
S08 = {
    "CHK_T0000_P0000": [
        "narrateur|Le carrelage sent encore le citron.",
        "narrateur|Papa vient de passer la serpillière.",
        "narrateur|Les carreaux sont un peu frais.",
        "narrateur|Puis le tapis du salon est épais.",
        "maman|Ça sent le propre.",
        "papa|Oui, tout propre.",
        "narrateur|Près du canapé, une pile de linge attend.",
        "narrateur|Un petit t-shirt est encore chaud.",
        "narrateur|En ce moment, Nino est au milieu du tapis.",
        "narrateur|Il a des cubes.",
        "narrateur|Il construit un pont.",
        "narrateur|Les cubes tapent.",
        "enfant-m|C'est un pont, papa.",
        "papa|Un pont bien solide ?",
        "enfant-m|Oui, il est solide.",
        "maman|Il va jusqu'où, ton pont ?",
        "enfant-m|Jusqu'au canapé, maman.",
        "narrateur|Nino pose encore un cube.",
        "narrateur|Clic.",
        "narrateur|Il pose un cube à gauche.",
        "narrateur|Puis un cube à droite.",
        "narrateur|Le pont a une arche.",
        "maman|Je vois l'arche, Nino.",
        "enfant-m|Une petite voiture peut passer.",
        "papa|On essaie.",
        "narrateur|Nino prend une petite voiture.",
        "narrateur|Il la pousse vers l'arche.",
        "narrateur|Un cube glisse.",
        "narrateur|L'arche a un trou.",
        "narrateur|La voiture bute.",
        "enfant-m|Oh, elle ne passe pas.",
        "papa|Le cube est tombé.",
        "narrateur|Nino repose le cube.",
        "narrateur|Clic.",
        "narrateur|L'arche est ronde, encore.",
        "narrateur|La voiture passe dessous.",
        "enfant-m|Elle est passée !",
        "maman|Elle rentre à la maison ?",
        "enfant-m|Oui, puis on s'assoit.",
        "narrateur|Nino veut le t-shirt chaud.",
        "narrateur|Il pousse encore la voiture.",
        "narrateur|Trois cubes tombent d'un coup.",
        "narrateur|L'arche s'écroule sur la voiture.",
        "enfant-m|Oh.",
        "papa|Le pont est tombé.",
        "enfant-m|Où est ma petite voiture ?",
        "maman|Dans la pile de linge ?",
        "narrateur|Nino fouille le t-shirt chaud.",
        "narrateur|Le tissu sent le savon.",
        "narrateur|Pas de voiture.",
        "enfant-m|Sous le canapé ?",
        "narrateur|Il se penche.",
        "narrateur|De la poussière, un fil.",
        "enfant-m|Elle est perdue.",
        "papa|Les cubes sont encore au milieu.",
        "enfant-m|Je veux voir dessous.",
        "narrateur|Nino prend un cube.",
        "narrateur|Il le pose dans la caisse.",
        "narrateur|Toc.",
        "narrateur|La caisse sent le bois.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nino cherche sa petite voiture.",
        "narrateur|Où est-elle ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Un cube de l'arche va dans la caisse.",
        "narrateur|Toc.",
        "maman|Tu regardes bien sous le pont ?",
        "enfant-m|Oui, maman.",
        "narrateur|Nino écarte un cube à gauche.",
        "papa|Un bout de tapis reparaît.",
        "narrateur|Puis un cube à droite.",
        "narrateur|Un toit minuscule brille.",
        "enfant-m|Ma voiture !",
        "narrateur|La petite voiture était sous l'arche.",
        "narrateur|Elle sent encore le bois des cubes.",
        "narrateur|Nino la tient dans la paume.",
        "narrateur|Les roues sont un peu froides.",
        "papa|Merci, tu l'as trouvée.",
        "maman|Te voilà, petite.",
        "enfant-m|Elle était dessous.",
        "narrateur|Les derniers cubes vont dans la caisse.",
        "narrateur|Le tapis devant le canapé est libre.",
        "narrateur|Le t-shirt chaud attend encore.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Nino pousse la caisse sous la table.",
        "narrateur|Le bois glisse un peu.",
        "maman|Le t-shirt, maintenant ?",
        "enfant-m|Oui, il est chaud.",
        "narrateur|Maman lui tend le t-shirt.",
        "narrateur|Nino l'enfile.",
        "narrateur|Le tissu sent le savon, tout chaud.",
        "papa|On s'assoit ?",
        "enfant-m|Oui, papa.",
        "narrateur|Nino grimpe sur le canapé.",
        "narrateur|La petite voiture est sur ses genoux.",
        "maman|Tu veux un verre d'eau ?",
        "enfant-m|Oui, maman.",
        "narrateur|L'eau est fraîche, après le citron.",
        "narrateur|Nino boit une gorgée.",
        "papa|Le pont a fini sa journée.",
        "enfant-m|La voiture aussi.",
        "narrateur|La pile de linge reste douce, près d'eux.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "enfant-m|La voiture est sur mes genoux.",
        "maman|Toi aussi, tu es au chaud.",
        "papa|Bravo, tu l'as retrouvée.",
        "narrateur|Le t-shirt garde encore la chaleur.",
        "narrateur|Le citron du carrelage s'en va, tout doux.",
    ],
}
preview("ATOM-AUT.RAN.001-08", "N2", S08)
write_story(
    "ATOM-AUT.RAN.001-08",
    "Nino veut s'asseoir dans le t-shirt chaud, avec la petite voiture qui a passé sous le pont. L'arche s'écroule sur la voiture. Il cherche, met les cubes dans la caisse. La voiture apparaît. Canapé, linge chaud.",
    "Le pont de Nino",
    "Nino, papa, maman",
    "salon après la serpillière au citron, pile de linge chaud, après-midi",
    S08,
    {},
    q_lost(
        "la petite voiture",
        "la petite voiture | la voiture | sous le pont | sous l'arche | sous les cubes | dessous",
        "Il cherche sous les cubes. Où est la petite voiture ?",
    ),
)
relecture(
    "ATOM-AUT.RAN.001-08",
    "Le pont de Nino",
    "Nino veut le t-shirt chaud et la voiture du pont. Arche s'écroule. Cherche linge, canapé. Cubes dans la caisse. Voiture sous l'arche. Canapé, tissu chaud, citron.",
    "Pas de ranger dit. Question = où est la petite voiture. Fin = citron qui s'en va.",
)
