#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-SOC.TRA.001-03..06 et ATOM-SOC.TRA.002-01..04."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-03  N2  Sarah, papa — avion vu de la terrasse
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-03",
    "Sarah veut voir l'avion depuis la terrasse. Un nuage le cache. Elle attend avec papa. L'avion reparaît, argenté.",
    "L'avion derrière le nuage",
    "Sarah, papa",
    "terrasse d'immeuble, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une feuille de géranium garde une goutte.",
            "narrateur|La goutte brille sur le velours vert.",
            "narrateur|Le fer de la rambarde est tiède.",
            "narrateur|Un torchon blanc sèche sur le fil.",
            "narrateur|Ça sent le café et la terre chaude.",
            "narrateur|Sarah vit ici, avec papa.",
            "papa|Tu as vu le torchon, Sarah ?",
            "enfant-f|Il danse un peu.",
            "papa|Le vent le touche.",
            "narrateur|En ce moment, Sarah lève les yeux.",
            "narrateur|Le ciel est large et pâle.",
            "enfant-f|Papa, l'avion va passer ?",
            "papa|Oui.",
            "papa|On le regarde d'ici.",
            "narrateur|Ils restent sur la terrasse.",
            "narrateur|Sarah se tient près de papa.",
            "papa|On reste avec un adulte.",
            "papa|C'est plus simple.",
            "narrateur|Un bruit monte, très loin.",
            "narrateur|Le bruit devient un souffle.",
            "enfant-f|Je l'entends !",
            "papa|Oui.",
            "papa|C'est un avion.",
            "papa|C'est le nom du véhicule.",
            "enfant-f|Un avion.",
            "narrateur|Un point argenté glisse entre les toits.",
            "narrateur|Sarah pointe le ciel du doigt.",
            "enfant-f|Le voilà !",
            "narrateur|Un nuage gras passe devant.",
            "narrateur|Le point argenté disparaît.",
            "enfant-f|Il est parti ?",
            "papa|Il est derrière le nuage.",
            "papa|On attend ici ?",
            "enfant-f|Oui.",
            "narrateur|Sarah reste près de papa.",
            "narrateur|Ses pieds restent sur les carreaux chauds.",
            "narrateur|Une abeille visite le géranium.",
            "papa|Tu restes avec moi ?",
            "enfant-f|Oui, papa.",
            "narrateur|Dans la vallée, un train file tout petit.",
            "papa|Tu entends le train ?",
            "enfant-f|Tchou tchou.",
            "papa|Oui.",
            "papa|C'est un train.",
            "narrateur|Sarah écoute, sans bouger.",
            "narrateur|Le nuage avance tout doucement.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah nomme le véhicule du ciel.",
            "narrateur|Lequel ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le nuage s'étire, puis se fend.",
            "narrateur|Un éclat d'argent revient.",
            "enfant-f|L'avion !",
            "papa|Oui.",
            "papa|Tu as dit le nom.",
            "papa|Bravo.",
            "narrateur|Sarah lève la main.",
            "narrateur|Elle salue le point brillant.",
            "narrateur|L'avion trace un trait blanc.",
            "papa|On reste sur la terrasse ?",
            "enfant-f|Oui.",
            "narrateur|Sarah se colle un peu à papa.",
            "narrateur|Le souffle s'éloigne.",
            "narrateur|Sur la table, une soucoupe d'eau attend.",
            "narrateur|Un bateau de papier y flotte.",
            "papa|Et ça, c'est un bateau.",
            "enfant-f|Un bateau.",
            "narrateur|Sarah souffle tout doux.",
            "narrateur|La voile de papier penche.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|L'avion devient un grain de riz.",
            "narrateur|Sarah le suit encore des yeux.",
            "enfant-f|Il est tout petit.",
            "papa|Il va loin.",
            "papa|Nous, on reste ici.",
            "narrateur|Le torchon s'est arrêté de danser.",
            "narrateur|La goutte a quitté la feuille.",
            "narrateur|Une tache sombre reste sur le velours.",
            "papa|Tu as vu l'avion ?",
            "enfant-f|Oui.",
            "enfant-f|Derrière le nuage, puis après.",
            "papa|Merci d'avoir attendu.",
            "narrateur|Sarah pose le doigt sur la rambarde.",
            "narrateur|Le fer est encore tiède.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le ciel redevient large et pâle.",
            "enfant-f|L'avion est passé.",
            "papa|Oui.",
            "narrateur|Le géranium sent encore la terre.",
            "narrateur|La rambarde garde la chaleur du jour.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "avion",
        "accepted_examples": "avion | un avion | l'avion | train | bateau",
        "retry_prompt": "Elle a vu un avion. Quel véhicule ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-03",
    "L'avion derrière le nuage",
    "Sarah veut voir l'avion depuis la terrasse. Un nuage le cache. Elle attend avec papa. L'avion reparaît.",
    "- Désir : voir l'avion, pas monter (POS).\n"
    "- Ouverture : goutte sur le géranium, rambarde tiède.\n"
    "- Imprévu : le nuage. Résolution : attendre, nommer.\n"
    "- Troupe D16 : Sarah, papa. Fin vécue : rambarde chaude.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-04  N1  Amir, papa — train, goûter, assis
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-04",
    "Amir veut manger son goûter dans le train. Ils montent. Une miette tombe. Il reste assis, près de papa.",
    "Le goûter du train",
    "Amir, papa",
    "gare puis wagon, après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'horloge de la gare fait tic.",
            "narrateur|Ça sent l'huile et le pain.",
            "narrateur|Le sac de papa est en toile.",
            "narrateur|Le papier du goûter craque.",
            "narrateur|Amir vit ici, avec papa.",
            "papa|Tu as entendu l'horloge ?",
            "enfant-m|Elle fait tic.",
            "papa|Oui.",
            "papa|Le train arrive.",
            "narrateur|En ce moment, le quai vibre.",
            "narrateur|Un souffle chaud passe.",
            "enfant-m|C'est le train ?",
            "papa|Oui.",
            "papa|C'est le nom du véhicule.",
            "enfant-m|Un train.",
            "papa|On monte avec un adulte.",
            "narrateur|Ils montent avec papa.",
            "narrateur|Amir s'assoit près de papa.",
            "narrateur|Le siège est un peu dur.",
            "narrateur|Le sac repose sur les genoux.",
            "papa|Tu restes assis ?",
            "enfant-m|Oui, papa.",
            "narrateur|Le train part tout doux.",
            "narrateur|Les maisons glissent.",
            "papa|On ouvre le goûter ?",
            "enfant-m|Oui !",
            "narrateur|Papa défait le papier.",
            "narrateur|Ça sent le beurre tiède.",
            "enfant-m|Une madeleine !",
            "papa|Une petite.",
            "narrateur|Amir croque, assis.",
            "narrateur|Une miette tombe.",
            "narrateur|La miette reste sur le siège.",
            "enfant-m|Oh.",
            "papa|Tu la prends, assis ?",
            "enfant-m|Oui.",
            "narrateur|Amir la prend, tout doux.",
            "narrateur|Il reste près de papa.",
            "narrateur|Le papier craque encore un peu.",
            "papa|Tu bois une gorgée ?",
            "enfant-m|Oui.",
            "narrateur|La gourde est fraîche.",
            "narrateur|L'eau sent le plastique.",
            "narrateur|Amir remet le bouchon, assis.",
            "papa|On garde le papier ?",
            "enfant-m|Pour les miettes.",
            "narrateur|Une autre miette attend.",
            "narrateur|Amir la pose dans le papier.",
            "narrateur|Le wagon fait un long souffle.",
            "papa|Tu vois les arbres ?",
            "enfant-m|Ils courent.",
            "papa|Nous, on reste assis.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir nomme le véhicule.",
            "narrateur|Lequel ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Par la fenêtre, le ciel est bleu.",
            "narrateur|Un trait blanc traverse.",
            "papa|Tu vois ça ?",
            "enfant-m|Un avion.",
            "papa|Oui.",
            "papa|C'est un avion.",
            "narrateur|Plus loin, une rivière brille.",
            "narrateur|Un bateau glisse, tout petit.",
            "papa|Et ça ?",
            "enfant-m|Un bateau.",
            "papa|Bravo.",
            "narrateur|Amir mâche encore.",
            "narrateur|La madeleine est douce.",
            "narrateur|Le papier repose sur le sac.",
            "papa|Tu restes assis ?",
            "enfant-m|Oui.",
            "narrateur|Ses pieds touchent le plancher.",
            "narrateur|Le wagon fait un petit toc.",
            "narrateur|Amir plie le papier.",
            "narrateur|Les miettes restent dedans.",
            "papa|Tu as encore faim ?",
            "enfant-m|Un peu.",
            "papa|On garde une miette.",
            "narrateur|Amir sourit, assis.",
            "narrateur|Le ciel file tout bleu.",
            "narrateur|Un oiseau suit le train.",
            "enfant-m|Il vole vite.",
            "papa|Oui.",
            "papa|Toi, tu restes ici.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le train ralentit.",
            "narrateur|Les maisons redeviennent grandes.",
            "papa|On arrive.",
            "papa|On reste assis encore.",
            "enfant-m|D'accord.",
            "narrateur|Amir tient le papier vide.",
            "narrateur|Le train s'arrête.",
            "papa|Maintenant on se lève.",
            "narrateur|Ils se lèvent ensemble.",
            "narrateur|Amir donne la main à papa.",
            "papa|Tu as mangé assis.",
            "enfant-m|C'était bon.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le quai, l'air sent le pain.",
            "enfant-m|Le train est arrêté.",
            "papa|Oui.",
            "narrateur|Une miette reste dans le papier.",
            "narrateur|Amir la garde dans la main.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "train",
        "accepted_examples": "train | un train | le train | avion | bateau",
        "retry_prompt": "Il a pris le train. Quel véhicule ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-04",
    "Le goûter du train",
    "Amir monte dans le train avec papa. Il veut son goûter. Une miette tombe. Il reste assis.",
    "- Désir : le goûter dans le train.\n"
    "- Ouverture : horloge, huile, papier qui craque.\n"
    "- POS-001 : rester assis, pas de fenêtre ouverte.\n"
    "- Troupe D16 : Amir, papa. Fin : miette dans la main.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-05  N1  Mila, papa — peluche sous le siège
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-05",
    "Mila veut garder sa peluche dans le train. L'ours glisse sous le siège. Papa l'attrape. Elle reste assise.",
    "La peluche sous le siège",
    "Mila, papa",
    "gare puis wagon, jour gris",
    {
        "CHK_T0000_P0000": [
            "narrateur|La laine de la peluche sent le savon.",
            "narrateur|L'ours a une oreille pliée.",
            "narrateur|Le banc du quai est froid.",
            "narrateur|Une feuille sèche tourne.",
            "narrateur|Mila vit ici, avec papa.",
            "papa|Tu tiens bien l'ours ?",
            "enfant-f|Oui, papa.",
            "papa|Le train arrive.",
            "narrateur|En ce moment, le quai vibre.",
            "narrateur|Les lumières du train passent.",
            "enfant-f|C'est le train ?",
            "papa|Oui.",
            "papa|C'est le nom du véhicule.",
            "enfant-f|Un train.",
            "papa|On monte avec un adulte.",
            "narrateur|Ils montent avec papa.",
            "narrateur|Mila s'assoit près de papa.",
            "narrateur|L'ours est sur ses genoux.",
            "narrateur|Le wagon part tout doux.",
            "narrateur|Les arbres défilent, gris.",
            "enfant-f|L'ours regarde dehors.",
            "papa|Toi, tu restes assise ?",
            "enfant-f|Oui.",
            "narrateur|Le wagon penche un peu.",
            "narrateur|L'ours glisse.",
            "narrateur|Il passe sous le siège.",
            "enfant-f|Mon ours !",
            "papa|Tu restes assise, Mila.",
            "papa|Papa le prend.",
            "narrateur|Mila reste sur le siège.",
            "narrateur|Ses mains attendent, ouvertes.",
            "narrateur|Papa se baisse, tout près.",
            "narrateur|La laine reparaît.",
            "narrateur|Un peu de poussière vole.",
            "papa|Tu restes assise ?",
            "enfant-f|Oui.",
            "narrateur|Mila attend, les mains ouvertes.",
            "narrateur|Le wagon roule tout droit.",
            "narrateur|Les arbres sont encore gris.",
            "enfant-f|Il a eu peur ?",
            "papa|Un petit peu.",
            "papa|Maintenant il revient.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila nomme le véhicule.",
            "narrateur|Lequel ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Papa pose l'ours sur les genoux.",
            "enfant-f|Merci.",
            "papa|Tu es restée assise.",
            "papa|Bravo.",
            "narrateur|Mila serre l'oreille pliée.",
            "narrateur|La laine est un peu poussiéreuse.",
            "papa|On souffle ?",
            "enfant-f|Oui.",
            "narrateur|Elle souffle tout doux.",
            "narrateur|Un fil de poussière danse.",
            "narrateur|Par la fenêtre, le ciel s'ouvre.",
            "papa|Tu vois le trait blanc ?",
            "enfant-f|Un avion.",
            "papa|Oui.",
            "papa|C'est un avion.",
            "narrateur|Une rivière apparaît.",
            "narrateur|Un bateau y glisse.",
            "papa|Et ça ?",
            "enfant-f|Un bateau.",
            "narrateur|Mila reste assise, l'ours contre elle.",
            "papa|Tu tiens l'ours, assise ?",
            "enfant-f|Oui.",
            "narrateur|L'oreille pliée chatouille le poignet.",
            "narrateur|Mila la lisse, tout doux.",
            "narrateur|Le ciel devient un peu plus bleu.",
            "papa|L'ours regarde encore dehors ?",
            "enfant-f|Oui.",
            "enfant-f|Moi aussi.",
            "narrateur|Ses pieds restent sur le plancher.",
            "narrateur|Le wagon fait un petit toc.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le train ralentit.",
            "narrateur|Les toits redeviennent proches.",
            "papa|On arrive.",
            "papa|On reste assis encore.",
            "enfant-f|L'ours aussi.",
            "narrateur|Le train s'arrête.",
            "papa|Maintenant on se lève.",
            "narrateur|Ils se lèvent ensemble.",
            "narrateur|Mila donne la main à papa.",
            "narrateur|L'ours est serré sous le bras.",
            "papa|Tu as gardé ta place.",
            "enfant-f|Et l'ours.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le quai, le vent est frais.",
            "enfant-f|L'ours est revenu.",
            "papa|Oui.",
            "narrateur|L'oreille pliée sent encore le savon.",
            "narrateur|Mila la frotte contre sa joue.",
            "narrateur|Un fil de laine brille au soleil.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "train",
        "accepted_examples": "train | un train | le train | avion | bateau",
        "retry_prompt": "Elle a pris le train. Quel véhicule ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-05",
    "La peluche sous le siège",
    "Mila veut sa peluche dans le train. L'ours glisse. Papa l'attrape. Elle reste assise.",
    "- Désir : garder l'ours.\n"
    "- Ouverture : laine, savon, banc froid.\n"
    "- Imprévu : l'ours sous le siège. Elle reste assise.\n"
    "- Troupe D16 : Mila, papa. Fin : oreille contre la joue.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.001-06  N1  Nino, maman — bac, vent, rester près
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.001-06",
    "Nino veut traverser le fleuve en bac. Le vent pousse. Il reste près de maman. L'autre rive arrive.",
    "Le vent du bac",
    "Nino, maman",
    "port puis bac, vent d'ouest",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le sel du bac pique la lèvre.",
            "narrateur|Une corde épaisse sent le goudron.",
            "narrateur|L'eau clapote contre le quai.",
            "narrateur|Une mouette crie, toute blanche.",
            "narrateur|Nino vit ici, avec maman.",
            "maman|Tu as goûté le sel ?",
            "enfant-m|Ça pique.",
            "maman|Oui.",
            "maman|Le bac arrive.",
            "narrateur|En ce moment, le ponton vibre.",
            "narrateur|Le bateau se colle au quai.",
            "enfant-m|C'est un bateau ?",
            "maman|Oui.",
            "maman|C'est le nom du véhicule.",
            "enfant-m|Un bateau.",
            "maman|On reste avec un adulte.",
            "narrateur|Ils montent avec maman.",
            "narrateur|Nino se tient près d'elle.",
            "narrateur|Le vent tire le manteau.",
            "narrateur|Le bac part tout doux.",
            "enfant-m|Ça bouge !",
            "maman|Oui.",
            "maman|Tu restes près de moi ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le vent devient plus fort.",
            "narrateur|Le capuchon de Nino saute.",
            "enfant-m|Mon capuchon !",
            "maman|Tu restes près.",
            "maman|Maman le remet.",
            "narrateur|Nino reste contre maman.",
            "narrateur|Le capuchon revient sur la tête.",
            "narrateur|L'eau fait des petits blancs.",
            "maman|Tu restes près ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le manteau claque encore.",
            "narrateur|Nino serre le tissu de maman.",
            "narrateur|Une goutte d'eau saute sur le pont.",
            "enfant-m|L'eau saute.",
            "maman|Oui.",
            "maman|Nous, on reste ici.",
            "narrateur|Le capuchon tient, cette fois.",
            "narrateur|Le sel pique encore la lèvre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino nomme le véhicule.",
            "narrateur|Lequel ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le vent pousse encore.",
            "narrateur|Nino serre la main de maman.",
            "maman|Tu es resté près.",
            "maman|Bravo.",
            "enfant-m|Le sel pique encore.",
            "maman|Oui.",
            "narrateur|Dans le ciel, un trait blanc.",
            "maman|Tu vois ça ?",
            "enfant-m|Un avion.",
            "maman|Oui.",
            "maman|C'est un avion.",
            "narrateur|Sur l'autre rive, des rails.",
            "narrateur|Un train file, tout petit.",
            "maman|Et ça ?",
            "enfant-m|Un train.",
            "narrateur|Nino reste près de maman.",
            "narrateur|Le manteau claque, puis se calme.",
            "narrateur|L'eau devient plus lisse.",
            "maman|Tu as encore froid ?",
            "enfant-m|Un peu.",
            "narrateur|Maman rentre le col du manteau.",
            "narrateur|Nino reste collé contre elle.",
            "narrateur|Le bac avance tout droit.",
            "enfant-m|L'autre rive grandit.",
            "maman|Oui.",
            "maman|On reste près jusqu'au quai.",
            "narrateur|Une mouette suit le bac.",
            "narrateur|Ses ailes sont bien ouvertes.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|L'autre rive se rapproche.",
            "narrateur|Les arbres deviennent grands.",
            "maman|On arrive.",
            "maman|On reste près encore.",
            "enfant-m|D'accord.",
            "narrateur|Le bac se colle au quai.",
            "maman|Maintenant on descend.",
            "narrateur|Ils descendent ensemble.",
            "narrateur|Nino donne la main à maman.",
            "maman|Tu es resté près.",
            "enfant-m|Le vent était fort.",
            "narrateur|Le quai est mouillé et sombre.",
            "narrateur|Une flaque tremble encore.",
            "maman|Tu as les pieds au sec ?",
            "enfant-m|Oui.",
            "narrateur|Nino marche près de maman.",
            "narrateur|Le capuchon reste sur sa tête.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le quai, le sel reste aux lèvres.",
            "enfant-m|On a traversé.",
            "maman|Oui.",
            "narrateur|La corde sent encore le goudron.",
            "narrateur|Une mouette crie, plus loin.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "bateau",
        "accepted_examples": "bateau | un bateau | le bateau | le bac | avion | train",
        "retry_prompt": "Il a pris le bac. Quel véhicule ?",
    },
)
relecture(
    "ATOM-SOC.TRA.001-06",
    "Le vent du bac",
    "Nino veut traverser en bac. Le vent pousse le capuchon. Il reste près de maman.",
    "- Désir : l'autre rive.\n"
    "- Ouverture : sel, corde, mouette.\n"
    "- Imprévu : le vent. POS : rester près.\n"
    "- Troupe D16 : Nino, maman. Fin : sel aux lèvres.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.002-01  N2  Nina, maman — voiture, vaches, rester assise
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.002-01",
    "Nina veut voir les vaches. Elle se lève un peu. Maman attend qu'elle se rasseye. Ensuite les vaches, toutes proches.",
    "Les vaches de Nina",
    "Nina, maman",
    "voiture sur la route de campagne, matin clair",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'herbe du pré brille encore.",
            "narrateur|Une paille colle au tapis de la voiture.",
            "narrateur|Ça sent le foin et le cuir tiède.",
            "narrateur|Le siège de Nina est un peu chaud.",
            "narrateur|Nina vit ici, avec maman.",
            "maman|Tu as senti le foin, Nina ?",
            "enfant-f|Oui.",
            "enfant-f|Ça pique le nez.",
            "maman|On va voir les vaches.",
            "narrateur|En ce moment, Nina s'assoit.",
            "narrateur|Maman attache la ceinture.",
            "narrateur|Le dos de Nina touche le dossier.",
            "maman|On reste assis, avec l'adulte.",
            "enfant-f|D'accord.",
            "narrateur|La voiture part tout doux.",
            "narrateur|Les haies défilent, vertes.",
            "enfant-f|Les vaches, c'est loin ?",
            "maman|Bientôt.",
            "narrateur|Un pré s'ouvre, tout large.",
            "narrateur|Des taches blanches bougent.",
            "enfant-f|Les vaches !",
            "narrateur|Nina veut voir plus près.",
            "narrateur|Elle se lève un peu.",
            "maman|Nina, tu restes assise.",
            "narrateur|Maman attend.",
            "narrateur|La route est calme.",
            "maman|Ta place est sur le siège ?",
            "enfant-f|Oui.",
            "narrateur|Nina se rassoit.",
            "narrateur|Son dos retrouve le dossier.",
            "narrateur|Ses mains reprennent le doudou.",
            "maman|Tu es assise ?",
            "enfant-f|Oui, maman.",
            "narrateur|La ceinture est encore là.",
            "narrateur|Les haies défilent plus lentement.",
            "narrateur|Un oiseau part du pré.",
            "enfant-f|Il a peur des vaches ?",
            "maman|Non.",
            "maman|Il va plus loin.",
            "narrateur|Nina reste sur le siège.",
            "narrateur|Le doudou sent un peu le foin.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina est dans la voiture.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina est assise, avec maman.",
            "maman|Merci.",
            "maman|Maintenant, regarde.",
            "narrateur|Une vache s'approche de la haie.",
            "narrateur|Elle a des cils très longs.",
            "narrateur|Son museau est rose et humide.",
            "enfant-f|Elle me voit !",
            "maman|Oui.",
            "maman|Toi, tu restes assise.",
            "enfant-f|Je reste assise.",
            "narrateur|La vache mâche, tout lentement.",
            "narrateur|Une cloche fait un son rond.",
            "maman|Tu as entendu la cloche ?",
            "enfant-f|Oui.",
            "narrateur|Nina colle sa joue à la vitre.",
            "narrateur|La vitre est fraîche.",
            "narrateur|Le doudou reste sur ses genoux.",
            "maman|Bravo.",
            "maman|Tu as gardé ta place.",
            "narrateur|Une autre vache lève la tête.",
            "narrateur|Elle a une tache en forme de lune.",
            "enfant-f|Une lune sur le dos !",
            "maman|Oui.",
            "maman|Tu la vois, assise.",
            "narrateur|Nina compte tout bas.",
            "enfant-f|Une, deux, trois.",
            "maman|Il y en a plus.",
            "narrateur|Le pré est large et mouillé.",
            "narrateur|Une flaque reflète une vache.",
            "enfant-f|Elle a deux têtes.",
            "maman|C'est l'eau.",
            "narrateur|Nina rit, assise.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La voiture reprend la route.",
            "narrateur|Les taches blanches deviennent petites.",
            "enfant-f|Au revoir, les vaches.",
            "maman|Au revoir.",
            "narrateur|Nina reste assise.",
            "narrateur|Le foin sent encore un peu.",
            "narrateur|La paille bouge sur le tapis.",
            "maman|On s'arrête au village.",
            "narrateur|La voiture s'arrête.",
            "maman|Maintenant on se lève.",
            "narrateur|Maman défait la ceinture.",
            "narrateur|Nina donne la main à maman.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le trottoir, l'air sent le foin.",
            "enfant-f|J'ai vu les cils.",
            "maman|Oui.",
            "narrateur|Le doudou garde un peu de chaleur.",
            "narrateur|Une cloche sonne encore, très loin.",
        ],
    },
    {
        "CHK_T0000_P0000": "voiture_passe",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "assise",
        "accepted_examples": "assise | rester assise | avec maman | avec l'adulte | assis",
        "retry_prompt": "Sa place est sur le siège. Que fait Nina ?",
    },
)
relecture(
    "ATOM-SOC.TRA.002-01",
    "Les vaches de Nina",
    "Nina veut voir les vaches. Elle se lève un peu. Maman attend. Nina se rassoit. Ensuite les cils de la vache.",
    "- Désir : les vaches, pas « rester assise » tout seul.\n"
    "- Ouverture : herbe, paille, foin.\n"
    "- POS-001 : pas de ceinture ôtée, pas de portière.\n"
    "- Troupe D16 : Nina, maman. Fin : cloche lointaine.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.002-02  N3  Raphaël, papa — bus, deux arrêts, vitre embuée
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.002-02",
    "Raphaël veut dessiner sur la buée du bus. Premier arrêt : il reste assis. Au deuxième, papa et lui se lèvent ensemble.",
    "La buée du bus",
    "Raphaël, papa",
    "bus de ville, matin humide",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vitre du bus a un petit nuage.",
            "narrateur|Le nuage, c'est de la buée tiède.",
            "narrateur|Un ticket jaune sent encore l'encre.",
            "narrateur|Le plancher du bus est mouillé par endroits.",
            "narrateur|Raphaël vit ici, avec papa.",
            "papa|Tu as vu la buée, Raphaël ?",
            "enfant-m|Oui.",
            "enfant-m|Je peux dessiner ?",
            "papa|Oui.",
            "papa|Assis, avec un adulte.",
            "narrateur|En ce moment, ils montent dans le bus.",
            "narrateur|Papa montre la place près de la vitre.",
            "narrateur|Raphaël s'assoit.",
            "narrateur|Son dos touche le dossier.",
            "papa|On reste assis, avec l'adulte.",
            "enfant-m|D'accord.",
            "narrateur|Le bus part.",
            "narrateur|Les magasins glissent, flous.",
            "narrateur|Raphaël trace un rond dans la buée.",
            "enfant-m|Un soleil.",
            "papa|Il est beau.",
            "papa|Tu restes assis, Raphaël ?",
            "enfant-m|Oui.",
            "narrateur|Le soleil de buée s'efface un peu.",
            "narrateur|Raphaël le redessine, assis.",
            "narrateur|Le bus ralentit.",
            "papa|Premier arrêt.",
            "papa|Nous, on reste assis.",
            "narrateur|Des gens descendent.",
            "narrateur|Raphaël reste sur sa place.",
            "narrateur|Le ticket jaune crisse dans sa main.",
            "enfant-m|On reste encore ?",
            "papa|Oui.",
            "papa|Jusqu'à notre arrêt.",
            "narrateur|Raphaël redessine un rayon.",
            "narrateur|La buée perle sous le doigt.",
            "narrateur|Une goutte descend, toute lente.",
            "papa|Ton soleil a une larme.",
            "enfant-m|C'est la buée.",
            "narrateur|Le bus reprend, plus fort.",
            "narrateur|Les magasins redeviennent nets.",
            "narrateur|Raphaël reste sur le siège.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël est dans le bus.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le bus repart.",
            "narrateur|La buée revient sur la vitre.",
            "enfant-m|Je refais le soleil.",
            "papa|Oui.",
            "papa|Tu es resté assis.",
            "papa|Bravo.",
            "narrateur|Le doigt de Raphaël laisse un trait.",
            "narrateur|Un peu d'eau coule vers le bas.",
            "papa|Tu as froid au doigt ?",
            "enfant-m|Un peu.",
            "narrateur|Papa pose sa main près de la sienne.",
            "narrateur|Le bus ralentit encore.",
            "papa|Deuxième arrêt.",
            "papa|Celui-là, c'est le nôtre.",
            "narrateur|Raphaël reste assis encore un instant.",
            "papa|Maintenant on se lève.",
            "narrateur|Ils se lèvent ensemble.",
            "narrateur|Raphaël donne la main à papa.",
            "narrateur|Le soleil de buée reste derrière.",
            "enfant-m|Il va s'effacer.",
            "papa|Oui.",
            "papa|Toi, tu as gardé ta place.",
            "narrateur|Le plancher est encore un peu mouillé.",
            "narrateur|Leurs pas font un bruit court.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils descendent sur le trottoir.",
            "narrateur|L'air froid pique les joues.",
            "enfant-m|Mon soleil est resté là-bas.",
            "papa|La buée le gardera un peu.",
            "narrateur|Le bus repart, tout gris.",
            "narrateur|Une trace de doigt brille encore.",
            "papa|Tu as gardé ta place.",
            "enfant-m|Jusqu'à notre arrêt.",
            "papa|Oui.",
            "narrateur|Le ticket jaune est un peu froissé.",
            "narrateur|Raphaël le met dans la poche de papa.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le trottoir, une flaque reflète le bus.",
            "enfant-m|Le soleil est parti.",
            "papa|Il reviendra, sur une autre vitre.",
            "narrateur|Le doigt de Raphaël est encore frais.",
            "narrateur|La poche de papa sent l'encre du ticket.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "assis",
        "accepted_examples": "assis | rester assis | avec papa | avec l'adulte",
        "retry_prompt": "Sa place est sur le siège. Que fait Raphaël ?",
    },
)
relecture(
    "ATOM-SOC.TRA.002-02",
    "La buée du bus",
    "Raphaël veut un soleil sur la buée. Premier arrêt : il reste assis. Deuxième : ils se lèvent ensemble.",
    "- Désir : dessiner sur la buée.\n"
    "- Ouverture : nuage sur la vitre, ticket jaune.\n"
    "- Deux arrêts vécus. POS-001 : pas de portière en marche.\n"
    "- Troupe D16 : Raphaël, papa. Fin : doigt frais, encre.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.002-03  N3  Chouchou, maman — train, tunnel, lumière
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.002-03",
    "Chouchou veut voir la lumière après le tunnel. Le wagon s'assombrit. Elle reste assise, près de maman. Les champs reviennent.",
    "Le tunnel de Chouchou",
    "Chouchou, maman",
    "train de campagne, après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La lampe du wagon fait un rond jaune.",
            "narrateur|Le rond tremble un peu sur les genoux.",
            "narrateur|Un carré de chocolat sent le cacao.",
            "narrateur|Le tissu du siège est rêche et bleu.",
            "narrateur|Chouchou vit ici, avec maman.",
            "maman|Tu as vu le rond jaune, Chouchou ?",
            "enfant-f|Il danse.",
            "maman|Oui.",
            "maman|Le train va entrer dans un tunnel.",
            "narrateur|En ce moment, Chouchou s'assoit.",
            "narrateur|Maman s'assoit à côté.",
            "narrateur|Le dos de Chouchou touche le dossier.",
            "maman|On reste assis, avec l'adulte.",
            "enfant-f|D'accord.",
            "narrateur|Le train roule.",
            "narrateur|Les champs défilent, verts.",
            "enfant-f|Après le tunnel, il y a la lumière ?",
            "maman|Oui.",
            "maman|On la regarde, assises.",
            "narrateur|La colline se rapproche.",
            "narrateur|Un trou noir s'ouvre.",
            "enfant-f|Le tunnel !",
            "narrateur|Le wagon s'assombrit d'un coup.",
            "narrateur|Le rond jaune devient plus fort.",
            "narrateur|Chouchou serre la main de maman.",
            "maman|Tu restes assise ?",
            "enfant-f|Oui.",
            "narrateur|Le train fait un bruit creux.",
            "narrateur|Les oreilles de Chouchou chantent un peu.",
            "narrateur|Elle reste sur sa place.",
            "enfant-f|C'est long, le noir ?",
            "maman|Un peu.",
            "maman|On reste assises.",
            "narrateur|Chouchou sent le cacao sur ses doigts.",
            "narrateur|Le rond jaune tremble plus fort.",
            "narrateur|Un bruit d'eau passe sous le train.",
            "maman|Tu as entendu l'eau ?",
            "enfant-f|Oui.",
            "enfant-f|Elle court dessous.",
            "narrateur|Chouchou serre encore la main.",
            "narrateur|Ses pieds restent sur le plancher.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou est dans le train.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Un trait de jour perce devant.",
            "narrateur|Le trait grandit, tout blanc.",
            "enfant-f|La lumière !",
            "maman|Oui.",
            "maman|Tu es restée assise.",
            "maman|Bravo.",
            "narrateur|Les champs reviennent, plus clairs.",
            "narrateur|Le rond jaune s'affaiblit sur les genoux.",
            "narrateur|Chouchou cligne des yeux.",
            "maman|Tu as vu la lumière ?",
            "enfant-f|Elle était forte.",
            "narrateur|Maman casse le carré de chocolat.",
            "narrateur|Une moitié pour Chouchou.",
            "enfant-f|Il fond.",
            "maman|Oui.",
            "maman|On le mange, assises.",
            "narrateur|Le cacao sent bon.",
            "narrateur|Le tissu bleu gratte un peu le mollet.",
            "maman|Tu veux l'autre moitié ?",
            "enfant-f|Après.",
            "enfant-f|Je regarde les champs.",
            "narrateur|Un cheval gris lève la tête.",
            "narrateur|Sa crinière part dans le vent.",
            "enfant-f|Il court pas.",
            "maman|Il nous regarde.",
            "narrateur|Chouchou reste assise.",
            "narrateur|Le chocolat fond encore un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le train ralentit près d'un village.",
            "narrateur|Des toits rouges passent.",
            "maman|On arrive.",
            "maman|On reste assises encore.",
            "enfant-f|D'accord.",
            "narrateur|Le train s'arrête.",
            "maman|Maintenant on se lève.",
            "narrateur|Elles se lèvent ensemble.",
            "narrateur|Chouchou donne la main à maman.",
            "maman|Tu as attendu la lumière, assise.",
            "enfant-f|Elle est revenue.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le quai, le jour est large.",
            "enfant-f|Mes genoux sont encore chauds.",
            "maman|Le rond jaune est resté un peu.",
            "narrateur|Un goût de cacao reste sur la lèvre.",
            "narrateur|Le tunnel est derrière, tout noir et fini.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "assise",
        "accepted_examples": "assise | rester assise | avec maman | avec l'adulte | assis",
        "retry_prompt": "Sa place est sur le siège. Que fait Chouchou ?",
    },
)
relecture(
    "ATOM-SOC.TRA.002-03",
    "Le tunnel de Chouchou",
    "Chouchou veut la lumière après le tunnel. Le wagon s'assombrit. Elle reste assise. Les champs reviennent.",
    "- Désir : la lumière, pas la leçon seule.\n"
    "- Ouverture : rond jaune, chocolat, tissu bleu.\n"
    "- Imprévu : le noir. POS-001 : rester assise.\n"
    "- Troupe D16 : Chouchou, maman. Fin : cacao, genoux chauds.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.TRA.002-04  N2  Victorina, maman — bus, sac qui bascule
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.TRA.002-04",
    "Victorina veut garder le pain dans le sac. Le sac bascule. Elle reste assise. Maman rattrape le sac.",
    "Le sac de Victorina",
    "Victorina, maman",
    "bus vers la boulangerie du village, fin de matinée",
    {
        "CHK_T0000_P0000": [
            "narrateur|La sangle du sac tape le genou.",
            "narrateur|Ça sent le pain encore tiède.",
            "narrateur|Une croûte a percé le papier.",
            "narrateur|Le soleil entre par la vitre du bus.",
            "narrateur|Victorina vit ici, avec maman.",
            "maman|Tu as senti le pain, Victorina ?",
            "enfant-f|Il est chaud.",
            "maman|Oui.",
            "maman|On le ramène à la maison.",
            "narrateur|En ce moment, elles montent dans le bus.",
            "narrateur|Maman montre la place.",
            "narrateur|Victorina s'assoit.",
            "narrateur|Le sac repose contre sa jambe.",
            "maman|On reste assis, avec l'adulte.",
            "enfant-f|D'accord.",
            "narrateur|Le bus part.",
            "narrateur|Les platanes défilent.",
            "enfant-f|Le pain va rester entier ?",
            "maman|Oui.",
            "maman|Si le sac reste près.",
            "narrateur|Le bus tourne.",
            "narrateur|Le sac bascule vers l'allée.",
            "enfant-f|Le sac !",
            "maman|Tu restes assise.",
            "narrateur|Victorina reste sur le siège.",
            "narrateur|Maman rattrape la sangle.",
            "narrateur|Le sac revient contre la jambe.",
            "maman|Tu as gardé ta place ?",
            "enfant-f|Oui.",
            "narrateur|Le papier du pain craque un peu.",
            "maman|Le pain est encore entier ?",
            "enfant-f|Oui.",
            "narrateur|Victorina pose le sac entre elle et maman.",
            "narrateur|La sangle repose sur ses genoux.",
            "narrateur|Le bus reprend tout droit.",
            "enfant-f|Il a failli partir.",
            "maman|Le sac, oui.",
            "maman|Toi, tu es restée.",
            "narrateur|Une miette de croûte brille au soleil.",
            "narrateur|Victorina la pousse dans le papier, assise.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorina est dans le bus.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorina est assise, avec maman.",
            "maman|Bravo.",
            "maman|Le pain est encore là.",
            "narrateur|Victorina pose la main sur le papier.",
            "narrateur|La croûte est un peu chaude.",
            "enfant-f|Il a fait un bruit.",
            "maman|Un petit toc.",
            "maman|Toi, tu es restée assise.",
            "narrateur|Le soleil fait un carré sur le sac.",
            "narrateur|La sangle ne tape plus.",
            "maman|Tu tiens la sangle, assise ?",
            "enfant-f|Oui.",
            "narrateur|Victorina tient la sangle.",
            "narrateur|Le pain reste contre sa jambe.",
            "narrateur|Le bus roule plus droit.",
            "narrateur|Les platanes font de l'ombre, puis du jour.",
            "maman|Tu as chaud au pain ?",
            "enfant-f|Un peu.",
            "narrateur|Victorina souffle sur le papier.",
            "narrateur|Le carré de soleil bouge.",
            "enfant-f|On descend à la place ?",
            "maman|Oui.",
            "maman|On reste assises jusqu'à l'arrêt.",
            "narrateur|Le bus ralentit, puis reprend.",
            "narrateur|Ce n'est pas encore le leur.",
            "narrateur|Victorina reste sur le siège.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le bus ralentit près de la place.",
            "narrateur|La fontaine brille.",
            "maman|On arrive.",
            "maman|On reste assises encore.",
            "enfant-f|D'accord.",
            "narrateur|Le bus s'arrête.",
            "maman|Maintenant on se lève.",
            "narrateur|Elles se lèvent ensemble.",
            "narrateur|Victorina donne la main à maman.",
            "narrateur|L'autre main tient la sangle.",
            "maman|Le pain a voyagé, entier.",
            "enfant-f|Moi aussi, assise.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le trottoir, le pain sent encore le four.",
            "enfant-f|La croûte est chaude.",
            "maman|Oui.",
            "narrateur|La sangle repose dans la main de Victorina.",
            "narrateur|Un peu de farine blanche reste au papier.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q={
        "expected_answer": "assise",
        "accepted_examples": "assise | rester assise | avec maman | avec l'adulte | assis",
        "retry_prompt": "Sa place est sur le siège. Que fait Victorina ?",
    },
)
relecture(
    "ATOM-SOC.TRA.002-04",
    "Le sac de Victorina",
    "Victorina veut ramener le pain entier. Le sac bascule. Elle reste assise. Maman rattrape la sangle.",
    "- Désir : le pain entier, pas la leçon seule.\n"
    "- Ouverture : sangle, croûte, soleil.\n"
    "- Imprévu : le sac. POS-001 : rester assise.\n"
    "- Troupe D16 : Victorina, maman. Fin : farine au papier.",
)
