#!/usr/bin/env python3
"""F-NAR-008 — ATOM-SOC.ARG.002-08 + ATOM-SOC.CUI.001-01..07."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-SOC.ARG.002-08  N1  Nino, papa  — biscuit du marché
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.ARG.002-08",
    "Nino veut un biscuit doré à l'étal. Un pigeon le fait sursauter. Il demande à papa. La pièce cliquette. Ils croquent près de la fontaine.",
    "Le biscuit doré de Nino",
    "Nino, papa",
    "place du village, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les cloches du village sonnent quatre fois.",
            "narrateur|La place sent le pain chaud.",
            "narrateur|Un pigeon marche près des étals.",
            "narrateur|La lumière est basse, toute dorée.",
            "papa|Tu as vu la lumière, Nino ?",
            "enfant-m|Elle est jaune.",
            "papa|Oui.",
            "papa|C'est la fin de l'après-midi.",
            "narrateur|En ce moment, Nino s'arrête.",
            "narrateur|Un étal a des biscuits ronds.",
            "narrateur|Ça sent le beurre et le sucre.",
            "enfant-m|Je veux ce biscuit.",
            "enfant-m|Le doré.",
            "papa|Tu le veux vraiment ?",
            "enfant-m|Oui, papa.",
            "narrateur|Nino tend un peu la main.",
            "narrateur|Le biscuit est tout près.",
            "narrateur|Un pigeon bat des ailes.",
            "narrateur|Nino sursaute.",
            "narrateur|Sa main va vers l'étal.",
            "narrateur|Puis il s'arrête.",
            "narrateur|L'argent est dans la poche.",
            "narrateur|C'est la poche de papa.",
            "enfant-m|S'il te plaît ?",
            "enfant-m|Je peux l'avoir ?",
            "papa|Tu me demandes ?",
            "enfant-m|Oui.",
            "papa|Merci, Nino.",
            "papa|On demande à l'adulte.",
            "narrateur|Papa sort une pièce.",
            "narrateur|La pièce fait un petit bruit.",
            "narrateur|Le marchand tend le biscuit.",
            "narrateur|Nino le prend à deux mains.",
            "narrateur|Le biscuit est encore tiède.",
            "enfant-m|Il sent le beurre.",
            "papa|Oui.",
            "papa|Tu as demandé.",
            "narrateur|Ils s'éloignent de l'étal.",
            "narrateur|La place devient plus calme.",
            "narrateur|Le pigeon picore une miette.",
            "papa|On s'assoit près de la fontaine ?",
            "enfant-m|Oui.",
            "narrateur|L'eau de la fontaine chante.",
            "narrateur|Le banc de pierre est tiède.",
            "narrateur|Nino casse un petit bout.",
            "narrateur|Ça croque.",
            "enfant-m|C'est bon.",
            "papa|Le beurre reste sur tes doigts.",
            "enfant-m|J'ai demandé.",
            "papa|Oui.",
            "papa|L'argent est resté avec moi.",
            "narrateur|Une cloche sonne encore, loin.",
            "narrateur|L'ombre de l'église s'allonge.",
            "narrateur|Nino souffle une miette.",
            "narrateur|Le pigeon s'approche, tout doux.",
            "papa|Tu as encore faim ?",
            "enfant-m|Un tout petit bout.",
            "papa|On le partage.",
            "narrateur|Papa casse un coin.",
            "narrateur|Nino croque le sien.",
            "narrateur|Ça sent encore le four.",
            "enfant-m|Il est chaud.",
            "papa|Oui, tout tiède.",
            "narrateur|Le soleil glisse sur les toits.",
            "narrateur|Une femme range son étal.",
            "narrateur|Nino essuie sa bouche.",
            "papa|On rentre par la ruelle ?",
            "enfant-m|Oui, papa.",
            "narrateur|La ruelle sent la pierre chaude.",
            "narrateur|Nino tient le dernier bout.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino veut un biscuit.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino a demandé à papa.",
            "narrateur|Papa a écouté.",
            "narrateur|La pièce a cliqueté.",
            "papa|Tu as demandé, Nino.",
            "enfant-m|S'il te plaît.",
            "papa|Oui.",
            "papa|C'est le bon geste.",
            "narrateur|Le biscuit tiède est dans ses mains.",
            "narrateur|Le pigeon marche encore.",
            "narrateur|L'eau de la fontaine chante.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils se lèvent du banc.",
            "narrateur|Nino a des miettes aux doigts.",
            "papa|On range le papier ?",
            "enfant-m|Oui.",
            "narrateur|Le papier sent encore le beurre.",
            "narrateur|Nino le plie tout petit.",
            "papa|Merci d'avoir demandé.",
            "enfant-m|Le biscuit était doré.",
            "papa|Oui.",
            "narrateur|La place se vide un peu.",
            "narrateur|Les cloches se taisent.",
            "narrateur|Le soleil touche les tuiles.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nino serre la main de papa.",
            "narrateur|Le dernier bout fond.",
            "enfant-m|Il sent encore le four.",
            "papa|Oui.",
            "narrateur|La ruelle sent la pierre chaude.",
            "narrateur|Le biscuit tiède sent le beurre.",
        ],
    },
    {},
    {
        "expected_answer": "demander",
        "accepted_examples": "demander | il demande | à papa | s'il te plaît | il demande à papa",
        "retry_prompt": "Nino veut le biscuit. Que fait-il ?",
    },
)
relecture(
    "ATOM-SOC.ARG.002-08",
    "Le biscuit doré de Nino",
    "Nino veut un biscuit doré à l'étal du village. Un pigeon le fait sursauter. Il demande à papa. Ils croquent près de la fontaine.",
    "- Désir : le biscuit, pas la leçon collée.\n"
    "- Ouverture : cloches, place, pigeon, lumière dorée.\n"
    "- Imprévu : le pigeon, la main vers l'étal, puis il s'arrête.\n"
    "- Leçon greffée : on demande à l'adulte. Troupe : Nino, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-01  N1  Sarah, maman  — banane, fourchette glisse
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-01",
    "Sarah veut un goûter jaune. La fourchette glisse. Elles rient et recommencent. La banane devient un nuage. Elles goûtent près du carreau.",
    "Le goûter jaune de Sarah",
    "Sarah, maman",
    "cuisine l'après-midi, rayon sur la table",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un rayon jaune traverse le carreau.",
            "narrateur|La table a un carré de soleil.",
            "narrateur|Une banane attend dans le bol.",
            "narrateur|Elle sent le sucre mûr.",
            "maman|Tu as vu le rayon, Sarah ?",
            "enfant-f|Il est jaune.",
            "maman|Oui.",
            "maman|Comme la banane.",
            "narrateur|En ce moment, Sarah a faim.",
            "enfant-f|Je veux le goûter jaune.",
            "maman|On l'écrase ensemble ?",
            "enfant-f|Oui.",
            "enfant-f|Je peux aider ?",
            "maman|Oui, avec moi.",
            "narrateur|Maman pose une fourchette.",
            "narrateur|Sarah tient le bol des deux mains.",
            "narrateur|La banane est molle et tiède.",
            "narrateur|Sarah appuie un peu.",
            "narrateur|La fourchette glisse.",
            "narrateur|Elle fait un petit clac.",
            "enfant-f|Elle part !",
            "maman|On la reprend ?",
            "enfant-f|Oui.",
            "narrateur|Elles rient toutes les deux.",
            "narrateur|Sarah reprend la fourchette.",
            "narrateur|Elle appuie plus doucement.",
            "narrateur|La banane s'écrase, tout jaune.",
            "enfant-f|Ça devient un nuage.",
            "maman|Oui.",
            "maman|Tu aides bien.",
            "narrateur|Le bol sent le fruit mûr.",
            "narrateur|Un peu de jaune reste au bord.",
            "narrateur|Sarah tourne encore la fourchette.",
            "maman|C'est assez mou ?",
            "enfant-f|Oui.",
            "maman|Merci, Sarah.",
            "narrateur|Maman pose deux petites cuillères.",
            "narrateur|Sarah apporte le bol à table.",
            "narrateur|Le rayon touche encore le bois.",
            "enfant-f|On goûte ?",
            "maman|Oui.",
            "narrateur|Sarah prend une cuillerée.",
            "narrateur|C'est doux et un peu sucré.",
            "enfant-f|C'est jaune.",
            "maman|C'est ton goûter.",
            "narrateur|Une mouche passe près du carreau.",
            "narrateur|Sarah souffle tout doux.",
            "maman|Tu as encore faim ?",
            "enfant-f|Encore un peu.",
            "narrateur|Elles mangent près de la fenêtre.",
            "narrateur|Le bois de la table est chaud.",
            "narrateur|Sarah lèche un peu de jaune.",
            "maman|Tu as écrasé avec moi.",
            "enfant-f|La fourchette a glissé.",
            "maman|Puis on a recommencé.",
            "narrateur|Le bol se vide tout doux.",
            "narrateur|Le rayon glisse vers le mur.",
            "enfant-f|Il est bon, le jaune.",
            "maman|Oui.",
            "narrateur|Sarah pose sa cuillère.",
            "narrateur|Elle a un point jaune au nez.",
            "maman|Un petit nuage, là.",
            "enfant-f|Sur mon nez ?",
            "maman|Oui.",
            "narrateur|Sarah rit encore.",
            "narrateur|Maman essuie le point jaune.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah veut le goûter jaune.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah a écrasé la banane.",
            "narrateur|La fourchette a glissé.",
            "narrateur|Elles ont ri, puis repris.",
            "maman|Tu as aidé, Sarah.",
            "enfant-f|Le goûter est jaune.",
            "maman|Oui.",
            "narrateur|Le bol sent encore le fruit.",
            "narrateur|Le rayon touche la table.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sarah apporte le bol vide.",
            "maman|On le pose près de l'évier ?",
            "enfant-f|Oui.",
            "narrateur|L'eau chante un peu.",
            "narrateur|Sarah rince sa cuillère.",
            "maman|Merci pour le goûter.",
            "enfant-f|Il était jaune.",
            "maman|Oui, tout doux.",
            "narrateur|Le carreau a encore du soleil.",
            "narrateur|La table garde un carré chaud.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sarah s'assoit près du carreau.",
            "enfant-f|Le nuage était bon.",
            "maman|Oui.",
            "narrateur|Un peu de jaune brille au bol.",
            "narrateur|Le goûter jaune sent encore le fruit.",
        ],
    },
    {},
    {
        "expected_answer": "écraser",
        "accepted_examples": "écraser | elle écrase | la banane | elle aide | avec maman | le goûter",
        "retry_prompt": "Sarah aide maman. Que fait-elle ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-01",
    "Le goûter jaune de Sarah",
    "Sarah veut un goûter jaune. La fourchette glisse. Elles rient et recommencent. La banane devient un nuage. Elles goûtent près du carreau.",
    "- Désir : le goûter jaune.\n"
    "- Ouverture : rayon, table, banane mûre. Pas la cloche du village.\n"
    "- Imprévu : fourchette qui glisse, rire, on recommence.\n"
    "- Troupe : Sarah, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-02  N2  Amir, papa  — soupe, croûton, chat
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-02",
    "Amir veut une soupe avec des croûtons. Un cube tombe. Le chat le regarde. Ils en font un autre. La vapeur danse. Ils croquent.",
    "Les croûtons d'Amir",
    "Amir, papa",
    "cuisine le soir, casserole et chat",
    {
        "CHK_T0000_P0000": [
            "narrateur|La casserole chante tout bas.",
            "narrateur|Un nuage monte vers le plafond.",
            "narrateur|La fenêtre s'embue un peu.",
            "narrateur|Ça sent la carotte et le thym.",
            "papa|Tu as entendu la casserole, Amir ?",
            "enfant-m|Elle chante.",
            "papa|Oui.",
            "papa|La soupe est presque prête.",
            "narrateur|En ce moment, Amir veut des croûtons.",
            "enfant-m|Je veux des cubes dans la soupe.",
            "papa|On les fait ensemble ?",
            "enfant-m|Oui.",
            "enfant-m|Je peux aider ?",
            "papa|Oui, avec moi.",
            "narrateur|Papa pose une planche près du feu.",
            "narrateur|Le pain est un peu rassis.",
            "narrateur|Amir le tient des deux mains.",
            "narrateur|Papa coupe, tout doux.",
            "narrateur|Amir range les cubes dans l'assiette.",
            "enfant-m|Ils sont durs.",
            "papa|Ils vont dorer.",
            "narrateur|Un cube glisse du bord.",
            "narrateur|Il tombe près de la chaise.",
            "narrateur|Le chat s'approche, tout silencieux.",
            "narrateur|Il regarde le cube par terre.",
            "enfant-m|Il le veut !",
            "papa|On en fait un autre ?",
            "enfant-m|Oui.",
            "narrateur|Amir prend un bout de pain.",
            "narrateur|Papa l'aide à le couper.",
            "narrateur|Le nouveau cube rejoint l'assiette.",
            "papa|Merci, Amir.",
            "papa|Tu as aidé.",
            "narrateur|Les cubes vont dans la poêle.",
            "narrateur|Ils font un petit bruit.",
            "narrateur|Ça sent le pain chaud.",
            "enfant-m|Ils dorent.",
            "papa|Tu les vois devenir dorés ?",
            "enfant-m|Oui.",
            "narrateur|Le chat reste près de la chaise.",
            "narrateur|Le cube tombé ne bouge plus.",
            "narrateur|Papa verse la soupe dans deux bols.",
            "narrateur|La vapeur danse au-dessus.",
            "enfant-m|Je mets les croûtons ?",
            "papa|Oui.",
            "narrateur|Amir pose trois cubes dans son bol.",
            "narrateur|Ils flottent, puis s'enfoncent.",
            "papa|On s'assoit près de la fenêtre ?",
            "enfant-m|Oui.",
            "narrateur|La vitre est un peu blanche.",
            "narrateur|Dehors, le jardin devient bleu.",
            "narrateur|Amir souffle sur la vapeur.",
            "enfant-m|C'est chaud.",
            "papa|On attend un peu.",
            "narrateur|Le chat saute sur le rebord.",
            "narrateur|Il regarde encore le cube.",
            "enfant-m|Il a son croûton, lui.",
            "papa|Et toi, tu as les tiens.",
            "narrateur|Amir croque un cube.",
            "narrateur|Ça fait un bruit net.",
            "enfant-m|C'est bon.",
            "papa|La soupe sent le thym.",
            "narrateur|Amir plonge la cuillère.",
            "narrateur|Un croûton revient, tout mouillé.",
            "enfant-m|Il a bu la soupe.",
            "papa|Oui.",
            "narrateur|La casserole se tait sur le feu.",
            "narrateur|Le chat se lèche la patte.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir prépare la soupe avec papa.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir a rangé les cubes.",
            "narrateur|Un croûton est tombé.",
            "narrateur|Le chat l'a regardé.",
            "narrateur|Ils en ont fait un autre.",
            "papa|Tu as aidé, Amir.",
            "enfant-m|J'ai mis les croûtons.",
            "papa|Oui.",
            "narrateur|La vapeur danse encore.",
            "narrateur|Le bol sent le thym.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Amir pose sa cuillère.",
            "papa|Il reste un croûton ?",
            "enfant-m|Le dernier.",
            "narrateur|Il le pousse dans la soupe.",
            "narrateur|Il croque, tout chaud.",
            "papa|Merci pour les cubes.",
            "enfant-m|Le chat a le sien.",
            "papa|Oui, par terre.",
            "narrateur|La fenêtre reste un peu blanche.",
            "narrateur|Le jardin est presque noir.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Amir souffle une dernière vapeur.",
            "enfant-m|La soupe était bonne.",
            "papa|Oui.",
            "narrateur|Le chat s'endort près de la chaise.",
            "narrateur|Le bol tiède sent encore le thym.",
        ],
    },
    {},
    {
        "expected_answer": "aider",
        "accepted_examples": "aider | les croûtons | il aide | avec papa | les cubes | la soupe",
        "retry_prompt": "Amir aide papa. Que fait-il ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-02",
    "Les croûtons d'Amir",
    "Amir veut des croûtons dans la soupe du soir. Un cube tombe. Le chat le regarde. Ils en font un autre. Ils croquent près de la vitre embuée.",
    "- Désir : la soupe aux croûtons.\n"
    "- Ouverture : casserole qui chante, vapeur, thym.\n"
    "- Imprévu : cube tombé, chat, un autre cube.\n"
    "- Troupe : Amir, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-03  N3  Mila, papa, maman  — salade midi / purée soir
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-03",
    "Mila veut le jardin dans l'assiette. À midi, une feuille de salade s'envole. Le soir, la purée est trop ferme. La cuisine donne sur les tomates.",
    "La cuisine ouverte sur le jardin",
    "Mila, papa, maman",
    "cuisine qui donne sur le jardin, midi puis soir",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les tomates pendent encore au jardin.",
            "narrateur|La porte-fenêtre est grande ouverte.",
            "narrateur|Une abeille passe près du romarin.",
            "narrateur|La table sent l'herbe coupée.",
            "papa|Tu as vu les tomates, Mila ?",
            "enfant-f|Elles sont rouges.",
            "papa|Oui.",
            "papa|On les met dans la salade ?",
            "narrateur|En ce moment, Mila veut le jardin dans l'assiette.",
            "enfant-f|Je veux aider.",
            "papa|On lave les feuilles ensemble.",
            "enfant-f|Oui.",
            "narrateur|L'eau de l'évier est froide et claire.",
            "narrateur|Mila tient une feuille trop grande.",
            "narrateur|Un souffle entre par la porte.",
            "narrateur|La feuille s'envole vers le carreau.",
            "enfant-f|Elle part au jardin !",
            "papa|On la rattrape ?",
            "enfant-f|Oui.",
            "narrateur|Mila court jusqu'au seuil.",
            "narrateur|La feuille s'est posée sur la pierre.",
            "narrateur|Mila la ramène au saladier.",
            "papa|Merci, Mila.",
            "papa|Tu as aidé.",
            "narrateur|Ils coupent une tomate du jardin.",
            "narrateur|Le jus coule un peu sur le bois.",
            "narrateur|Mila pose la salade au milieu.",
            "enfant-f|Ça sent le vert.",
            "papa|On mange près de la porte ?",
            "enfant-f|Oui.",
            "narrateur|Le midi, le jardin entre dans la pièce.",
            "narrateur|Une tomate brille dans le saladier.",
            "narrateur|Mila croque une feuille froide.",
            "enfant-f|C'est le jardin.",
            "papa|Oui, dans l'assiette.",
            "narrateur|Plus tard, le soleil descend.",
            "narrateur|Les tomates deviennent plus sombres.",
            "narrateur|Maman allume la petite lampe.",
            "maman|On fait la purée, Mila ?",
            "enfant-f|Oui.",
            "enfant-f|Je peux aider encore ?",
            "maman|Oui, avec moi.",
            "narrateur|Les pommes de terre fument dans la casserole.",
            "narrateur|La vapeur va vers le jardin noir.",
            "narrateur|Mila écrase avec le pilon.",
            "enfant-f|C'est dur.",
            "maman|On ajoute un peu de lait ?",
            "enfant-f|Oui.",
            "narrateur|La purée devient plus douce.",
            "narrateur|Elle fait un nuage blanc.",
            "maman|Tu as vu le jardin, ce soir ?",
            "enfant-f|Il s'endort.",
            "maman|Oui.",
            "narrateur|Mila apporte deux assiettes.",
            "narrateur|La purée est chaude et pâle.",
            "narrateur|Dehors, les tomates ne se voient plus.",
            "enfant-f|Le jardin est dans l'assiette, encore.",
            "maman|Oui.",
            "maman|Midi la salade, soir la purée.",
            "narrateur|Mila souffle sur sa cuillerée.",
            "narrateur|Ça sent le lait et la terre douce.",
            "papa|Tu as aidé deux fois.",
            "enfant-f|Midi et soir.",
            "papa|Oui.",
            "narrateur|La porte-fenêtre reste un peu ouverte.",
            "narrateur|Le romarin sent encore, tout près.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila aide en cuisine.",
            "narrateur|Comment ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|À midi, Mila a rattrapé la feuille.",
            "narrateur|Le soir, elle a écrasé la purée.",
            "maman|Tu as aidé deux fois.",
            "enfant-f|La salade, puis la purée.",
            "papa|Oui.",
            "papa|Avec nous.",
            "narrateur|La porte-fenêtre donne encore sur le noir.",
            "narrateur|Le romarin sent tout près.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Mila pose sa cuillère.",
            "maman|Il reste un nuage de purée ?",
            "enfant-f|Le dernier.",
            "narrateur|Elle le mange, tout chaud.",
            "papa|Merci pour le jardin dans l'assiette.",
            "enfant-f|Midi et soir.",
            "maman|Oui.",
            "narrateur|La petite lampe dore la table.",
            "narrateur|Les tomates du jardin se reposent.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Mila regarde le seuil sombre.",
            "enfant-f|Le jardin a mangé avec nous.",
            "maman|Oui.",
            "narrateur|Un peu de vapeur reste près du bois.",
            "narrateur|La purée tiède sent le lait doux.",
        ],
    },
    {},
    {
        "expected_answer": "aider",
        "accepted_examples": "aider | la salade | la purée | avec papa | avec maman | deux fois",
        "retry_prompt": "Mila aide en cuisine. Comment ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-03",
    "La cuisine ouverte sur le jardin",
    "Mila veut le jardin dans l'assiette. Midi : une feuille s'envole, elle la ramène. Soir : la purée trop ferme, elle ajoute du lait. La porte-fenêtre reste ouverte.",
    "- Unique : cuisine qui donne sur le jardin.\n"
    "- Deux repas : salade midi, purée soir.\n"
    "- Troupe : Mila, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-04  N3  Aniss, papa, maman  — crêpes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-04",
    "Aniss veut une crêpe dorée. La première reste trop pâle. Ils attendent. La deuxième dore. Ils la plient, tiède, près de la fenêtre.",
    "La crêpe dorée d'Aniss",
    "Aniss, papa, maman",
    "cuisine le dimanche, poêle et vapeur",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un nuage blanc sort de la poêle.",
            "narrateur|Ça sent le beurre qui fond.",
            "narrateur|La fenêtre laisse entrer un carré clair.",
            "narrateur|Un torchon pend près du bois.",
            "papa|Tu as vu le nuage, Aniss ?",
            "enfant-m|Il monte.",
            "papa|Oui.",
            "papa|La poêle est chaude.",
            "narrateur|En ce moment, Aniss veut une crêpe dorée.",
            "enfant-m|Je veux celle qui brille.",
            "maman|On la fait ensemble ?",
            "enfant-m|Oui.",
            "enfant-m|Je peux aider ?",
            "maman|Oui, avec nous.",
            "narrateur|Aniss tient le bol des deux mains.",
            "narrateur|La pâte est lisse, un peu épaisse.",
            "narrateur|Papa verse un rond dans la poêle.",
            "narrateur|Ça fait un petit chuintement.",
            "enfant-m|Elle est blanche.",
            "papa|On attend ?",
            "enfant-m|Oui.",
            "narrateur|Ils regardent le rond pâle.",
            "narrateur|Les bords restent trop clairs.",
            "narrateur|Papa la retourne.",
            "narrateur|L'autre côté est pâle aussi.",
            "enfant-m|Elle n'est pas dorée.",
            "maman|La première est souvent comme ça.",
            "maman|On en fait une autre ?",
            "enfant-m|Oui.",
            "narrateur|Aniss verse un peu de pâte.",
            "narrateur|Maman guide sa main.",
            "narrateur|Le second rond s'étale, plus mince.",
            "papa|On laisse le temps.",
            "narrateur|Un bord devient brun tout doux.",
            "narrateur|Ça sent plus fort le beurre.",
            "enfant-m|Elle dore !",
            "maman|Tu vois la couleur ?",
            "enfant-m|Oui, comme le soleil.",
            "narrateur|Papa la tourne.",
            "narrateur|Le dessous est tacheté, tout beau.",
            "maman|Merci, Aniss.",
            "maman|Tu as versé avec moi.",
            "narrateur|Ils plient la crêpe en deux.",
            "narrateur|Puis encore, en petit triangle.",
            "narrateur|Aniss l'apporte à table.",
            "enfant-m|Elle est tiède.",
            "papa|On s'assoit près du carreau ?",
            "enfant-m|Oui.",
            "narrateur|Maman pose un peu de sucre.",
            "narrateur|Aniss croque le coin.",
            "narrateur|Ça craque, puis c'est mou.",
            "enfant-m|C'est doré.",
            "papa|La deuxième a réussi.",
            "narrateur|La première, trop pâle, attend.",
            "narrateur|Papa la plie aussi, pour lui.",
            "enfant-m|La mienne brille.",
            "maman|Oui.",
            "narrateur|Un peu de vapeur sort encore.",
            "narrateur|Le torchon a une tache de beurre.",
            "papa|Tu as aidé pour la deuxième.",
            "enfant-m|On a attendu.",
            "papa|Oui.",
            "narrateur|Le carré clair glisse sur la table.",
            "narrateur|Aniss lèche un grain de sucre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss aide pour les crêpes.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La première crêpe était trop pâle.",
            "narrateur|Aniss a versé la deuxième.",
            "narrateur|Elle a doré.",
            "maman|Tu as aidé, Aniss.",
            "enfant-m|On a attendu.",
            "papa|Oui.",
            "narrateur|Le triangle tiède est dans l'assiette.",
            "narrateur|Ça sent encore le beurre.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Aniss plie le dernier coin.",
            "papa|Il reste du sucre ?",
            "enfant-m|Sur mes doigts.",
            "maman|Merci pour la pâte.",
            "enfant-m|La mienne était dorée.",
            "papa|Oui.",
            "narrateur|La poêle se tait.",
            "narrateur|Le nuage blanc n'est plus là.",
            "narrateur|Le torchon sent le beurre.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Aniss regarde le carré de lumière.",
            "enfant-m|Elle était comme le soleil.",
            "maman|Oui.",
            "narrateur|Un grain de sucre brille encore.",
            "narrateur|La crêpe tiède sent le beurre.",
        ],
    },
    {},
    {
        "expected_answer": "verser",
        "accepted_examples": "verser | aider | la crêpe | avec papa | avec maman | il verse | attendre",
        "retry_prompt": "Aniss aide pour les crêpes. Que fait-il ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-04",
    "La crêpe dorée d'Aniss",
    "Aniss veut une crêpe dorée. La première reste pâle. Ils attendent. La deuxième dore. Ils la plient près du carreau.",
    "- Désir : la crêpe dorée.\n"
    "- Ouverture : nuage de la poêle, beurre.\n"
    "- Imprévu : première trop pâle, deuxième qui dore.\n"
    "- Troupe : Aniss, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-05  N2  Raphaël, papa  — pain perdu
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-05",
    "Raphaël veut un pain perdu doré. L'œuf glisse. Papa le rattrape au-dessus du bol. Ils trempent le pain. Ça sent la cannelle.",
    "Le pain perdu de Raphaël",
    "Raphaël, papa",
    "cuisine un soir de pluie, bol et poêle",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le pain rassis attend dans le saladier.",
            "narrateur|La pluie tape le carreau, tout doux.",
            "narrateur|Une goutte fait un trait sur la vitre.",
            "narrateur|Ça sent déjà un peu la cannelle.",
            "papa|Tu as entendu la pluie, Raphaël ?",
            "enfant-m|Elle tape.",
            "papa|Oui.",
            "papa|On reste au chaud.",
            "narrateur|En ce moment, Raphaël veut du pain perdu.",
            "enfant-m|Je veux le pain tout doré.",
            "papa|On le fait ensemble ?",
            "enfant-m|Oui.",
            "enfant-m|Je peux aider ?",
            "papa|Oui, avec moi.",
            "narrateur|Papa pose un bol près du saladier.",
            "narrateur|Raphaël tient l'œuf des deux mains.",
            "narrateur|La coquille est froide et lisse.",
            "narrateur|L'œuf glisse un peu.",
            "enfant-m|Il part !",
            "narrateur|Papa ouvre les mains au-dessus du bol.",
            "narrateur|Il rattrape l'œuf, tout juste.",
            "papa|On l'a.",
            "enfant-m|Il n'est pas par terre.",
            "papa|Non.",
            "papa|Il va dans le bol.",
            "narrateur|Ils cassent l'œuf, cette fois ensemble.",
            "narrateur|Le jaune tombe, tout rond.",
            "narrateur|Raphaël bat avec la fourchette.",
            "papa|Tu vois le mélange ?",
            "enfant-m|Il est jaune.",
            "narrateur|Papa pose une tranche de pain.",
            "narrateur|Raphaël la pousse dans le bol.",
            "narrateur|Le pain boit le jaune, tout mou.",
            "enfant-m|Il est lourd.",
            "papa|On le met dans la poêle ?",
            "enfant-m|Oui.",
            "narrateur|Ça chuinte un peu.",
            "narrateur|Un nuage sent la cannelle.",
            "narrateur|Le pain dore sur un bord.",
            "papa|Tu le tournes avec moi ?",
            "enfant-m|Oui.",
            "narrateur|Ils le retournent, tout doux.",
            "narrateur|L'autre face devient brune.",
            "papa|Merci, Raphaël.",
            "papa|Tu as aidé.",
            "narrateur|Papa glisse le pain dans l'assiette.",
            "narrateur|Raphaël l'apporte à table.",
            "narrateur|La pluie chante encore.",
            "enfant-m|Il est chaud.",
            "papa|On souffle ?",
            "enfant-m|Oui.",
            "narrateur|Raphaël coupe un coin avec la fourchette.",
            "narrateur|Le dedans est mou, le bord croque.",
            "enfant-m|Ça sent la cannelle.",
            "papa|Oui.",
            "narrateur|Une goutte descend encore la vitre.",
            "narrateur|Raphaël regarde le trait d'eau.",
            "enfant-m|L'œuf a glissé.",
            "papa|Et on l'a rattrapé.",
            "enfant-m|Au-dessus du bol.",
            "papa|Oui.",
            "narrateur|Le saladier n'a plus de pain rassis.",
            "narrateur|L'assiette a un pain doré.",
            "enfant-m|C'est celui que je voulais.",
            "papa|Oui.",
            "narrateur|La poêle se tait.",
            "narrateur|Le carreau reste tout mouillé.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël prépare le pain perdu.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'œuf a glissé.",
            "narrateur|Papa l'a rattrapé au-dessus du bol.",
            "narrateur|Raphaël a trempé le pain.",
            "papa|Tu as aidé, Raphaël.",
            "enfant-m|Il est doré.",
            "papa|Oui.",
            "narrateur|La cannelle sent encore.",
            "narrateur|La pluie tape le carreau.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Raphaël pose sa fourchette.",
            "papa|Il reste un coin ?",
            "enfant-m|Le plus doré.",
            "narrateur|Il le mange, tout tiède.",
            "papa|Merci pour le bol.",
            "enfant-m|L'œuf n'est pas tombé.",
            "papa|Non.",
            "narrateur|La vitre a encore des traits d'eau.",
            "narrateur|La cuisine sent la cannelle.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Raphaël écoute encore la pluie.",
            "enfant-m|Le pain était doré.",
            "papa|Oui.",
            "narrateur|Un peu de cannelle reste au bord.",
            "narrateur|Le pain perdu sent encore le chaud.",
        ],
    },
    {},
    {
        "expected_answer": "aider",
        "accepted_examples": "aider | le pain | tremper | avec papa | l'œuf | le bol",
        "retry_prompt": "Raphaël aide papa. Que fait-il ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-05",
    "Le pain perdu de Raphaël",
    "Raphaël veut un pain perdu doré un soir de pluie. L'œuf glisse. Papa le rattrape au-dessus du bol. Ils trempent le pain. Ça sent la cannelle.",
    "- Désir : le pain perdu doré.\n"
    "- Ouverture : pain rassis, pluie, cannelle.\n"
    "- Imprévu : œuf qui glisse, rattrapé au-dessus du bol.\n"
    "- Troupe : Raphaël, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-06  N3  Nina, papa, maman  — compote + yaourt, fenêtre
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-06",
    "Nina veut le chaud et le froid dans le même bol. La cuillère de compote est trop chaude. Elles attendent. Le yaourt refroidit le nuage. La fenêtre reste blanche.",
    "La fenêtre blanche de Nina",
    "Nina, papa, maman",
    "cuisine, fenêtre embuée, compote puis yaourt",
    {
        "CHK_T0000_P0000": [
            "narrateur|La fenêtre de la cuisine est blanche.",
            "narrateur|On ne voit plus le cerisier.",
            "narrateur|La casserole fait un nuage bas.",
            "narrateur|Ça sent la pomme cuite.",
            "papa|Tu as vu la fenêtre, Nina ?",
            "enfant-f|Elle est toute blanche.",
            "papa|Oui.",
            "papa|C'est la vapeur.",
            "narrateur|En ce moment, Nina veut le chaud et le froid.",
            "enfant-f|Je veux la pomme et le yaourt.",
            "papa|On fait la compote ensemble ?",
            "enfant-f|Oui.",
            "enfant-f|Je peux aider ?",
            "papa|Oui, avec moi.",
            "narrateur|Les morceaux de pomme dansent dans l'eau.",
            "narrateur|Nina tient le bois du pilon.",
            "narrateur|Papa l'aide à écraser, tout doux.",
            "narrateur|La pomme devient un nuage rose.",
            "enfant-f|C'est chaud.",
            "papa|On souffle.",
            "narrateur|Nina prend une petite cuillerée.",
            "narrateur|Elle la repose tout de suite.",
            "enfant-f|Trop chaud !",
            "papa|On attend un peu ?",
            "enfant-f|Oui.",
            "narrateur|Ils soufflent ensemble sur le nuage.",
            "narrateur|Un rond se dessine sur la vitre.",
            "narrateur|Nina y pose un doigt.",
            "enfant-f|Un œil !",
            "papa|Le cerisier est derrière.",
            "narrateur|La compote n'est plus brûlante.",
            "papa|Merci, Nina.",
            "papa|Tu as écrasé avec moi.",
            "narrateur|Plus tard, maman ouvre le yaourt.",
            "narrateur|Le couvercle fait un petit clac.",
            "maman|On met le froid sur le chaud ?",
            "enfant-f|Oui.",
            "enfant-f|Je peux aider encore ?",
            "maman|Oui, avec moi.",
            "narrateur|Nina verse le yaourt au milieu.",
            "narrateur|Le blanc fait une île dans le rose.",
            "maman|Tu tournes tout doux ?",
            "enfant-f|Oui.",
            "narrateur|Le chaud et le froid se mêlent un peu.",
            "narrateur|Ça sent encore la pomme.",
            "narrateur|Nina apporte le bol à table.",
            "maman|On s'assoit près de la fenêtre ?",
            "enfant-f|Oui.",
            "narrateur|Le cerisier apparaît dans le rond.",
            "narrateur|Nina goûte une cuillerée.",
            "enfant-f|C'est tiède et froid.",
            "maman|Les deux.",
            "papa|Tu as fait les deux préparations.",
            "enfant-f|La pomme, puis le yaourt.",
            "papa|Oui.",
            "narrateur|Un peu de vapeur reste au plafond.",
            "narrateur|La casserole se tait.",
            "enfant-f|La fenêtre a un œil.",
            "maman|On voit le cerisier.",
            "narrateur|Nina lèche le bord du bol.",
            "narrateur|Le rose et le blanc restent un peu.",
            "maman|Tu as aidé deux fois.",
            "enfant-f|Avec papa, puis avec toi.",
            "maman|Oui.",
            "narrateur|Le rond sur la vitre s'agrandit.",
            "narrateur|Une feuille du cerisier bouge.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina aide en cuisine.",
            "narrateur|Comment ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina a écrasé la pomme avec papa.",
            "narrateur|Elle a versé le yaourt avec maman.",
            "maman|Tu as aidé deux fois.",
            "enfant-f|Le chaud et le froid.",
            "papa|Oui.",
            "narrateur|La fenêtre reste un peu blanche.",
            "narrateur|Le cerisier se voit dans le rond.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina pose sa cuillère.",
            "maman|Il reste une île blanche ?",
            "enfant-f|La dernière.",
            "narrateur|Elle la mange, tiède et froide.",
            "papa|Merci pour la pomme.",
            "maman|Merci pour le yaourt.",
            "enfant-f|Les deux.",
            "narrateur|Le rond sur la vitre s'efface un peu.",
            "narrateur|Le cerisier redevient flou.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Nina souffle sur le dernier nuage.",
            "enfant-f|C'était chaud et froid.",
            "maman|Oui.",
            "narrateur|Un doigt a laissé un trait sur le blanc.",
            "narrateur|Le bol sent encore la pomme cuite.",
        ],
    },
    {},
    {
        "expected_answer": "aider",
        "accepted_examples": "aider | la compote | le yaourt | avec papa | avec maman | écraser | verser",
        "retry_prompt": "Nina aide en cuisine. Comment ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-06",
    "La fenêtre blanche de Nina",
    "Nina veut le chaud et le froid. La cuillère de compote brûle. Elles attendent. Le yaourt fait une île. La fenêtre embuée montre le cerisier.",
    "- Unique : fenêtre embuée, cerisier.\n"
    "- Deux préparations : compote puis yaourt.\n"
    "- Troupe : Nina, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SOC.CUI.001-07  N2  Chouchou, papa, maman  — gâteau, farine, part tiède
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SOC.CUI.001-07",
    "Chouchou veut une part tiède. La farine lui met un nuage sur le nez. Ils rient. Le gâteau sort. Elle croque près du four encore chaud.",
    "La part tiède de Chouchou",
    "Chouchou, papa, maman",
    "cuisine l'après-midi, four et farine",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un sac de farine penche sur la table.",
            "narrateur|Un peu de poudre a déjà sauté.",
            "narrateur|Le four fait un petit ronron.",
            "narrateur|Ça sent le beurre, déjà.",
            "papa|Tu as vu le sac, Chouchou ?",
            "enfant-f|Il penche.",
            "papa|Oui.",
            "papa|On le tient ensemble.",
            "narrateur|En ce moment, Chouchou veut une part tiède.",
            "enfant-f|Je veux le gâteau encore chaud.",
            "maman|On le fait ensemble ?",
            "enfant-f|Oui.",
            "enfant-f|Je peux aider ?",
            "maman|Oui, avec nous.",
            "narrateur|Chouchou verse un peu de farine.",
            "narrateur|Un nuage blanc s'élève.",
            "narrateur|Il lui met un point sur le nez.",
            "enfant-f|J'ai de la neige !",
            "papa|Sur le nez ?",
            "enfant-f|Oui.",
            "narrateur|Papa et maman rient tout bas.",
            "narrateur|Chouchou rit aussi.",
            "maman|On essuie, puis on continue ?",
            "enfant-f|Oui.",
            "narrateur|Maman passe le torchon, tout doux.",
            "narrateur|Le nez redevient rose.",
            "narrateur|Chouchou mélange dans le saladier.",
            "narrateur|La pâte devient lisse, un peu épaisse.",
            "papa|Tu la verses dans le moule ?",
            "enfant-f|Oui.",
            "narrateur|Maman guide le saladier.",
            "narrateur|La pâte tombe, lourde et douce.",
            "narrateur|Papa glisse le moule dans le four.",
            "enfant-f|Il va dorer.",
            "maman|On attend près de la fenêtre ?",
            "enfant-f|Oui.",
            "narrateur|Le four ronronne plus fort.",
            "narrateur|Un parfum de gâteau emplit la pièce.",
            "narrateur|Chouchou dessine un rond sur le bois.",
            "papa|Tu as de la farine au pouce.",
            "enfant-f|Encore un nuage.",
            "papa|Oui.",
            "narrateur|Plus tard, maman ouvre la porte.",
            "narrateur|Un nuage chaud sort du four.",
            "narrateur|Le gâteau est doré, tout rond.",
            "enfant-f|Il est tiède ?",
            "maman|On attend un tout petit peu.",
            "narrateur|Papa pose le moule sur le bois.",
            "narrateur|Chouchou le regarde, tout près.",
            "maman|Tu coupes une part, avec moi ?",
            "enfant-f|Oui.",
            "narrateur|La part se lève, encore chaude.",
            "narrateur|Chouchou l'apporte à table.",
            "maman|Merci, Chouchou.",
            "maman|Tu as aidé.",
            "narrateur|Elle s'assoit près du four.",
            "narrateur|Le bois de la table est tiède.",
            "enfant-f|Je croque ?",
            "papa|Oui.",
            "narrateur|Chouchou croque le bord.",
            "narrateur|C'est doux, un peu sucré.",
            "enfant-f|C'est la part tiède.",
            "papa|Celle que tu voulais.",
            "narrateur|Un peu de farine brille encore au sac.",
            "narrateur|Le nez de Chouchou est propre.",
            "enfant-f|J'avais de la neige.",
            "maman|Puis on a essuyé.",
            "narrateur|Le four se tait tout doux.",
            "narrateur|La part laisse une miette chaude.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou aide pour le gâteau.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La farine a mis un nuage au nez.",
            "narrateur|Chouchou a versé la pâte.",
            "narrateur|Le gâteau est sorti, doré.",
            "maman|Tu as aidé, Chouchou.",
            "enfant-f|J'ai la part tiède.",
            "papa|Oui.",
            "narrateur|Le four sent encore le beurre.",
            "narrateur|Une miette reste sur le bois.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Chouchou pose sa fourchette.",
            "papa|Il reste un coin ?",
            "enfant-f|Le plus tiède.",
            "narrateur|Elle le mange près du four.",
            "maman|Merci pour la farine.",
            "enfant-f|J'avais de la neige au nez.",
            "papa|Oui.",
            "narrateur|Le sac penche moins.",
            "narrateur|Le moule est encore chaud.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Chouchou lèche un grain de sucre.",
            "enfant-f|La part était tiède.",
            "maman|Oui.",
            "narrateur|Le four garde un peu de chaleur.",
            "narrateur|La miette chaude sent encore le beurre.",
        ],
    },
    {},
    {
        "expected_answer": "aider",
        "accepted_examples": "aider | le gâteau | verser | avec papa | avec maman | la farine | la part",
        "retry_prompt": "Chouchou aide pour le gâteau. Que fait-elle ?",
    },
)
relecture(
    "ATOM-SOC.CUI.001-07",
    "La part tiède de Chouchou",
    "Chouchou veut une part tiède. La farine lui met un nuage sur le nez. Ils rient. Le gâteau sort. Elle croque près du four.",
    "- Désir : la part tiède.\n"
    "- Ouverture : sac de farine, four qui ronronne.\n"
    "- Imprévu : farine sur le nez.\n"
    "- Troupe : Chouchou, papa, maman.",
)
