#!/usr/bin/env python3
"""Réécriture réelle ATOM-COL.ECO.001-01..08. Texte seulement."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REWRITES = ROOT / "rewrites"

NAR, PAPA, MAMAN, EM, EF, MAIT = (
    "narrateur",
    "papa",
    "maman",
    "enfant-m",
    "enfant-f",
    "maitresse",
)


def lines_to_script(lines: list[tuple[str, str]]) -> str:
    return "\n".join(f"{r}|{t}" for r, t in lines)


def lines_to_text(lines: list[tuple[str, str]]) -> str:
    return " ".join(t for _, t in lines)


def chk(
    chunk_id: str,
    kind: str,
    lines: list[tuple[str, str]],
    *,
    sons: str = "",
    scale: float = 1.22,
    rate: str = "medium",
    pause: int = 400,
    expected_answer: str | None = None,
    accepted_examples: str | None = None,
    retry_prompt: str | None = None,
) -> dict:
    d: dict = {
        "chunk_id": chunk_id,
        "kind": kind,
        "text": lines_to_text(lines),
        "script": lines_to_script(lines),
        "sons": sons,
        "length_scale_piper": scale,
        "rate_label": rate,
        "pause_after_ms": pause,
    }
    if expected_answer:
        d["expected_answer"] = expected_answer
        d["accepted_examples"] = accepted_examples
        d["retry_prompt"] = retry_prompt
    return d


def dump_story(meta: dict, chunks: list[dict]) -> None:
    sid = meta["story_id"]
    src = json.loads((REWRITES / sid / "source.json").read_text(encoding="utf-8"))
    by_id = {c["chunk_id"]: c for c in chunks}
    out_chunks = []
    for old in src["chunks"]:
        cid = old["chunk_id"]
        if cid not in by_id:
            raise SystemExit(f"{sid}: chunk manquant {cid}")
        out_chunks.append(by_id[cid])
    if {c["chunk_id"] for c in chunks} != {c["chunk_id"] for c in src["chunks"]}:
        raise SystemExit(f"{sid}: ids différents")
    payload = dict(src)
    payload.update(meta)
    payload["chunks"] = out_chunks
    path = REWRITES / sid / "merged.json"
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    nwords = sum(len(c["text"].split()) for c in out_chunks)
    print(f"{sid}\t{nwords} mots\t{meta['title']}")


def max_phrase(lines: list[tuple[str, str]], cap: int, sid: str, where: str) -> None:
    for role, t in lines:
        n = len(t.split())
        if n > cap:
            raise SystemExit(f"{sid} {where} ({role}): {n} mots > {cap}: {t}")


# ---------------------------------------------------------------------------
# 01 Aniss N2 — pluie, bottes jaunes, crayon, gouttière
# ---------------------------------------------------------------------------
P01 = [
    (NAR, "La gouttière chante sur le toit."),
    (NAR, "La pluie tape la fenêtre de la cuisine."),
    (NAR, "Une petite flaque brille près des bottes jaunes."),
    (NAR, "Ça sent encore la soupe d'hier."),
    (NAR, "Papa range les cuillères dans le tiroir."),
    (NAR, "Maman essuie la table en bois."),
    (NAR, "La maison est douce, un peu sombre."),
    (PAPA, "La pluie fait une vraie chanson, Aniss."),
    (MAMAN, "Tes bottes jaunes t'attendent près de la porte."),
    (NAR, "En ce moment, Aniss tient son crayon jaune."),
    (NAR, "Le bois est lisse sous ses doigts."),
    (EM, "Je veux dessiner la pluie."),
    (EM, "Avec le crayon jaune."),
    (MAMAN, "Il va dans le cartable."),
    (MAMAN, "Tu le poses tout seul ?"),
    (EM, "Oui, maman."),
    (NAR, "Aniss glisse le crayon dans la poche."),
    (NAR, "Le cartable sent le papier."),
    (PAPA, "On enfile les bottes d'abord."),
    (NAR, "Aniss enfile la botte gauche."),
    (NAR, "La botte est froide, un peu lisse."),
    (EM, "Elle colle, maman."),
    (MAMAN, "Tire doucement."),
    (MAMAN, "Et l'autre maintenant."),
    (NAR, "Aniss enfile la botte droite."),
    (PAPA, "Tes deux pieds sont au chaud."),
    (PAPA, "On y va ?"),
    (EM, "On y va."),
    (PAPA, "Tu dis au revoir à maman ?"),
    (EM, "Au revoir, maman."),
    (MAMAN, "Au revoir, Aniss."),
    (MAMAN, "Je t'écoute ce soir."),
    (NAR, "Dehors, la rue brille."),
    (NAR, "Les gouttes tapent le capuchon."),
    (NAR, "L'école sent le savon et le bois des casiers."),
    (NAR, "La classe est claire, malgré la pluie."),
    (NAR, "Un carré d'eau coule sur la vitre."),
    (NAR, "La maîtresse parle près du tableau."),
    (MAIT, "Bonjour les enfants."),
    (MAIT, "On range les crayons."),
    (EM, "Bonjour, maîtresse."),
    (NAR, "Aniss écoute."),
    (NAR, "Il sort le crayon jaune."),
    (NAR, "Il le pose dans la boîte, tout droit."),
    (NAR, "Le bois tape un tout petit coup."),
    (MAIT, "Merci, Aniss."),
    (MAIT, "Vous avez bien écouté."),
    (NAR, "Aniss garde le bruit de la gouttière."),
    (NAR, "Il le gardera pour le dessin, plus tard."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, tout près de l'oreille."),
    (NAR, "Aniss sent un malaise."),
    (NAR, "Son ventre se serre, tout petit."),
    (NAR, "Il respire."),
    (NAR, "Il reste près de sa chaise."),
    (NAR, "Il pose les mains à plat."),
    (NAR, "Il se souvient de la cuisine."),
    (NAR, "Le soir, la gouttière chante encore."),
    (NAR, "La porte s'ouvre."),
    (NAR, "Ça sent le cacao."),
    (PAPA, "Te voilà, Aniss."),
    (PAPA, "Tes bottes sont bien mouillées."),
    (MAMAN, "Viens."),
    (MAMAN, "Le cacao est chaud."),
    (NAR, "Aniss pose les bottes près de la flaque."),
    (NAR, "Il s'assoit."),
    (NAR, "Le ventre est encore serré."),
    (NAR, "Il regarde papa."),
    (NAR, "Il regarde maman."),
]
C01 = [
    (EM, "Papa."),
    (EM, "Maman."),
    (EM, "J'ai eu un malaise."),
    (EM, "Quelqu'un a parlé tout bas."),
    (PAPA, "On t'écoute."),
    (MAMAN, "Viens près de la tasse."),
    (NAR, "Aniss parle, tout doucement."),
    (NAR, "Papa écoute sans couper."),
    (NAR, "Maman pose une main tiède sur son dos."),
    (MAMAN, "Tu as bien fait de venir le dire."),
    (PAPA, "À l'école, on écoute la maîtresse."),
    (PAPA, "Si tu as un malaise, tu viens raconter."),
    (NAR, "Le ventre d'Aniss se desserre, un peu."),
    (MAMAN, "Tu as fini ta tasse ?"),
    (EM, "Presque, maman."),
]
E01 = [
    (NAR, "Aniss sort le crayon jaune du cartable."),
    (NAR, "Le bois est encore un peu froid."),
    (EM, "Je dessine la gouttière."),
    (PAPA, "Tu lui fais une place sur la feuille ?"),
    (EM, "Oui."),
    (EM, "Ici, au milieu."),
    (NAR, "Aniss trace une ligne jaune, tout long."),
    (NAR, "La ligne descend, comme l'eau."),
    (MAMAN, "On entend presque la chanson."),
    (NAR, "Aniss ajoute une petite flaque ronde."),
    (PAPA, "Et les bottes, à côté ?"),
    (EM, "Deux bottes jaunes."),
    (NAR, "Il souffle sur la feuille."),
    (EM, "Fffff."),
    (NAR, "La pluie ralentit derrière la vitre."),
]
F01 = [
    (NAR, "Les bottes sèchent près de la porte."),
    (NAR, "La feuille jaune reste sur la table."),
    (MAMAN, "On t'a écouté, Aniss."),
    (PAPA, "La gouttière chante encore, plus loin."),
    (NAR, "L'histoire est finie."),
]
Q01 = [
    (NAR, "Aniss a un malaise."),
    (NAR, "Que fait-il ?"),
]

# ---------------------------------------------------------------------------
# 02 Mila N3 — rayon, buée, lait, chanson
# ---------------------------------------------------------------------------
P02 = [
    (NAR, "Un rayon jaune s'étale sur les carreaux."),
    (NAR, "Il touche le bord de la table ronde."),
    (NAR, "De la buée couvre encore la vitre."),
    (NAR, "Maman dessine un rond clair avec la main."),
    (NAR, "Un oiseau passe tout près, tout vite."),
    (NAR, "Le pain grille."),
    (NAR, "Ça sent le beurre."),
    (NAR, "Papa glisse une pomme dans la boîte."),
    (MAMAN, "Tu as vu le petit rond dans la buée ?"),
    (EF, "Oui."),
    (EF, "On voit le toit d'en face."),
    (PAPA, "Le soleil est là, même avec la buée."),
    (NAR, "En ce moment, Mila souffle sur son lait."),
    (NAR, "Une petite fumée danse au-dessus du bol."),
    (MAMAN, "Doucement."),
    (MAMAN, "Il est encore chaud."),
    (EF, "Il sent le matin, maman."),
    (EF, "À l'école, on chante aujourd'hui."),
    (PAPA, "Tu te souviens du refrain ?"),
    (EF, "Un peu."),
    (EF, "Je veux le chanter avec la classe."),
    (MAMAN, "Tu dis bonjour à la maîtresse."),
    (EF, "Oui."),
    (EF, "Bonjour, et merci."),
    (NAR, "Mila pose le bol."),
    (NAR, "Une goutte de lait reste sur la lèvre."),
    (PAPA, "Viens."),
    (PAPA, "J'essuie."),
    (NAR, "Plus tard, l'école sent la craie et les cahiers."),
    (NAR, "Le rayon entre aussi dans la classe."),
    (NAR, "Il pose un carré d'or sur le tapis."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les crayons, tout doux."),
    (EF, "Bonjour, maîtresse."),
    (NAR, "Mila écoute."),
    (NAR, "Elle pose son crayon bleu dans la boîte."),
    (NAR, "Le bleu tape un tout petit coup."),
    (MAIT, "Merci, Mila."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, tout près."),
    (NAR, "Mila sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Elle pose les mains à plat sur la table."),
    (NAR, "Elle reste assise."),
    (NAR, "L'après-midi, la maîtresse parle encore."),
    (MAIT, "On chante tout doux."),
    (MAIT, "On écoute le refrain."),
    (NAR, "Mila écoute encore."),
    (NAR, "Elle chante avec la classe."),
    (NAR, "Sa voix est petite."),
    (NAR, "Son ventre est encore serré."),
    (NAR, "Le soir, le rayon est parti de la cuisine."),
    (NAR, "Il reste une lumière rose sur le mur."),
    (NAR, "La porte s'ouvre."),
    (MAMAN, "Te voilà."),
    (MAMAN, "Tu as faim ?"),
    (NAR, "Mila pose son cartable."),
    (NAR, "Elle regarde le mur rose."),
    (NAR, "Le ventre est encore serré."),
]
C02 = [
    (EF, "Maman."),
    (EF, "J'ai eu un malaise."),
    (EF, "Quelqu'un a parlé d'un secret, tout bas."),
    (EF, "J'ai écouté le matin."),
    (EF, "J'ai écouté l'après-midi."),
    (EF, "Puis j'ai chanté, un peu."),
    (MAMAN, "On t'écoute."),
    (PAPA, "Viens t'asseoir."),
    (NAR, "Mila parle près de la tartine."),
    (NAR, "Maman serre sa main."),
    (NAR, "La main est tiède."),
    (MAMAN, "Tu as bien fait de raconter."),
    (PAPA, "À l'école, on écoute la maîtresse."),
    (MAMAN, "Si tu as un malaise, tu viens le dire."),
    (NAR, "Mila se sent plus légère, comme le rayon."),
]
E02 = [
    (PAPA, "Tu as fini ta tartine ?"),
    (EF, "Oui."),
    (EF, "Merci, papa."),
    (NAR, "Maman verse un verre d'eau."),
    (NAR, "L'eau chante un peu contre le verre."),
    (MAMAN, "Tu veux boire ?"),
    (EF, "Oui, maman."),
    (NAR, "Mila boit une gorgée."),
    (NAR, "C'est frais."),
    (PAPA, "On reste encore un peu près de la fenêtre ?"),
    (EF, "Oui."),
    (EF, "Le toit d'en face est rose."),
    (NAR, "Mila chante le refrain, tout bas."),
    (NAR, "Papa écoute."),
    (NAR, "Maman écoute."),
    (MAMAN, "Je le reconnais."),
    (EF, "C'est celui de la classe."),
    (NAR, "La buée revient un peu."),
    (NAR, "La cuisine est calme."),
]
F02 = [
    (NAR, "Le rayon a quitté les carreaux."),
    (NAR, "Le toit d'en face reste rose."),
    (PAPA, "On t'a écoutée, Mila."),
    (MAMAN, "Tu as chanté, puis tu as raconté."),
    (NAR, "L'histoire est finie."),
]
Q02 = [
    (NAR, "Mila a un malaise."),
    (NAR, "Que fait-elle ?"),
]

# ---------------------------------------------------------------------------
# 03 Victorino N2 — pain tiède, miette, ciseaux
# ---------------------------------------------------------------------------
P03 = [
    (NAR, "Le sac de pain craque encore un peu."),
    (NAR, "Une miette tombe sur la nappe à carreaux."),
    (NAR, "Ça sent le four du village."),
    (NAR, "La rue est calme, tout près."),
    (NAR, "Un vélo passe au loin, tout léger."),
    (NAR, "Papa coupe une tartine."),
    (NAR, "La croûte est dorée."),
    (NAR, "Maman verse un peu de lait."),
    (PAPA, "Le pain est encore tiède, tu sens ?"),
    (MAMAN, "Une petite miette a voyagé jusqu'à la nappe."),
    (NAR, "En ce moment, Victorino touche la croûte tiède."),
    (EM, "Elle est chaude, papa."),
    (PAPA, "Une bouchée, puis on part."),
    (NAR, "Victorino croque."),
    (NAR, "La croûte fait un petit bruit."),
    (EM, "À l'école, je veux découper un rond."),
    (EM, "Un rond comme le pain."),
    (MAMAN, "Tu essuies tes doigts d'abord."),
    (NAR, "Victorino passe le torchon."),
    (NAR, "Le lait laisse une petite moustache blanche."),
    (MAMAN, "Viens."),
    (MAMAN, "J'essuie."),
    (EM, "Merci, maman."),
    (PAPA, "Le village sent le pain, ce matin."),
    (MAMAN, "Tu as entendu le vélo, tout à l'heure ?"),
    (EM, "Oui."),
    (EM, "Il était loin."),
    (PAPA, "Tu dis bonjour à la maîtresse."),
    (EM, "Oui."),
    (NAR, "L'école sent le papier et le savon des mains."),
    (NAR, "Les chaises font un petit bruit sur le sol."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les ciseaux, maintenant."),
    (EM, "Bonjour, maîtresse."),
    (NAR, "Victorino écoute."),
    (NAR, "Il pose les ciseaux dans le pot, les pointes en bas."),
    (MAIT, "Merci."),
    (MAIT, "Maintenant, on découpe un rond."),
    (NAR, "Victorino prend une feuille."),
    (NAR, "Il suit la ligne, tout doux."),
    (NAR, "Le rond tombe sur la table."),
    (EM, "Il ressemble au pain."),
    (MAIT, "Oui, Victorino."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, tout près de l'oreille."),
    (NAR, "Victorino sent un malaise."),
    (NAR, "Son ventre se serre, comme un nœud."),
    (NAR, "Il reste assis."),
    (NAR, "Il pose le rond de papier près du pot."),
    (NAR, "Les ciseaux brillent dans le pot, tout sages."),
    (NAR, "Le soir, le sac de pain est encore sur la table."),
    (NAR, "Ça sent le cacao et la croûte."),
    (NAR, "La porte s'ouvre."),
    (MAMAN, "Te voilà."),
    (MAMAN, "Tu as faim ?"),
    (NAR, "Victorino pose le rond de papier sur la nappe."),
    (NAR, "À côté de la miette."),
    (NAR, "Le ventre est encore serré."),
]
C03 = [
    (EM, "J'ai eu un malaise, maman."),
    (EM, "Quelqu'un a parlé tout bas."),
    (MAMAN, "On t'écoute."),
    (PAPA, "Assieds-toi."),
    (NAR, "Victorino parle près du rond de papier."),
    (NAR, "Papa écoute."),
    (NAR, "Maman écoute."),
    (MAMAN, "Tu as bien fait de raconter."),
    (PAPA, "À l'école, on écoute."),
    (MAMAN, "Si tu as un malaise, tu viens le dire à la maison."),
    (NAR, "Le nœud dans le ventre se desserre."),
]
E03 = [
    (MAMAN, "Tu as fini ta tartine du soir ?"),
    (EM, "Oui, maman."),
    (NAR, "Une miette reste sur la nappe."),
    (NAR, "Victorino rit un peu."),
    (PAPA, "La miette a voyagé encore."),
    (NAR, "Maman pose une pomme et un morceau de pain."),
    (MAMAN, "Viens t'asseoir, Victorino."),
    (NAR, "Victorino s'assoit."),
    (NAR, "La chaise est stable."),
    (PAPA, "Tes pieds touchent la barre ?"),
    (EM, "Oui, papa."),
    (NAR, "Le pain craque encore, tout doux."),
    (EM, "Mon rond de papier est là."),
    (MAMAN, "On le pose près du vrai pain."),
    (NAR, "Les deux ronds se regardent."),
    (EM, "Merci, maman."),
    (EM, "Merci, papa."),
]
F03 = [
    (NAR, "Le sac de pain se tait."),
    (NAR, "Le rond de papier reste sur la nappe."),
    (PAPA, "On t'a écouté, Victorino."),
    (MAMAN, "Le pain était tiède."),
    (NAR, "L'histoire est finie."),
]
Q03 = [
    (NAR, "Victorino a un malaise."),
    (NAR, "Que fait-il ?"),
]

# ---------------------------------------------------------------------------
# 04 Sarah N2 — linge, torchon rouge, soleil papier
# ---------------------------------------------------------------------------
P04 = [
    (NAR, "Le linge danse sur la corde du jardin."),
    (NAR, "Un torchon rouge claque un peu, tout léger."),
    (NAR, "Le vent du matin est tiède."),
    (NAR, "Le portillon fait un petit bruit de fer."),
    (NAR, "Papa accroche une pince en bois."),
    (NAR, "Maman plie une serviette encore chaude de soleil."),
    (PAPA, "Le torchon rouge fait comme un drapeau."),
    (MAMAN, "Tu as senti l'herbe, Sarah ?"),
    (NAR, "En ce moment, Sarah sent l'herbe encore mouillée."),
    (EF, "Elle est froide, et un peu piquante."),
    (MAMAN, "Tes chaussures restent dans l'allée, d'accord ?"),
    (EF, "D'accord, maman."),
    (NAR, "Sarah pose les chaussures sur les cailloux."),
    (PAPA, "Tes deux pieds sont sur les cailloux."),
    (NAR, "Un oiseau chante dans le cerisier."),
    (PAPA, "Tu as entendu l'oiseau ?"),
    (EF, "Oui, papa."),
    (EF, "Il est haut."),
    (EF, "À l'école, je veux poser le soleil."),
    (EF, "Le soleil en papier."),
    (MAMAN, "Il est dans le cartable."),
    (MAMAN, "On part."),
    (MAMAN, "Tu dis au revoir au jardin."),
    (EF, "Au revoir, jardin."),
    (NAR, "La classe sent les feutres et le papier."),
    (NAR, "La maîtresse parle du temps."),
    (MAIT, "Aujourd'hui, il y a du soleil."),
    (EF, "Bonjour, maîtresse."),
    (NAR, "Sarah écoute."),
    (NAR, "Elle prend le rond jaune, tout léger."),
    (NAR, "Elle pose le soleil sur le tableau."),
    (NAR, "Le papier est lisse."),
    (NAR, "Il tient avec une pince."),
    (MAIT, "Merci, Sarah."),
    (NAR, "Plus tard, c'est la sortie."),
    (NAR, "La cour est chaude."),
    (NAR, "Des voix jouent au loin."),
    (NAR, "Près du portail, une voix parle trop près."),
    (NAR, "Sarah sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Elle reste près du groupe."),
    (NAR, "Elle regarde la maîtresse."),
    (NAR, "Elle se souvient du jardin."),
    (NAR, "Le soir, le linge est rentré."),
    (NAR, "Le jardin est calme."),
    (NAR, "La porte s'ouvre."),
    (PAPA, "Te voilà."),
    (PAPA, "Tes chaussures ont un peu de poussière."),
    (NAR, "Sarah pose les chaussures dans l'allée."),
    (NAR, "Elle regarde le cerisier."),
    (NAR, "Le ventre est encore serré."),
]
C04 = [
    (EF, "Papa."),
    (EF, "J'ai eu un malaise au portail."),
    (PAPA, "On t'écoute."),
    (MAMAN, "Viens près de la fenêtre."),
    (NAR, "Sarah parle, tout bas."),
    (NAR, "Papa écoute."),
    (NAR, "Maman écoute."),
    (PAPA, "Tu as bien fait de raconter."),
    (MAMAN, "À l'école, on écoute la maîtresse."),
    (PAPA, "Si tu as un malaise, tu viens le dire."),
    (NAR, "Sarah se sent plus légère."),
    (NAR, "Le torchon rouge repose, plié."),
]
E04 = [
    (NAR, "Sarah range son cartable près de la porte."),
    (NAR, "Papa prépare le goûter."),
    (NAR, "Une pêche, un peu d'eau."),
    (MAMAN, "Tu t'assois près de la fenêtre ?"),
    (EF, "Oui."),
    (EF, "On voit le cerisier."),
    (PAPA, "Tes pieds sont sur le tapis."),
    (NAR, "Sarah croque la pêche."),
    (NAR, "Elle est sucrée."),
    (EF, "Le vrai soleil est sur le cerisier."),
    (MAMAN, "Et le papier était sur le tableau."),
    (EF, "Oui."),
    (EF, "Il tenait avec la pince."),
    (NAR, "Le jardin sent l'herbe sèche."),
    (NAR, "Le vent s'est calmé."),
    (EF, "Merci, papa."),
    (EF, "Merci, maman."),
]
F04 = [
    (NAR, "Le torchon rouge dort dans le panier."),
    (NAR, "Le cerisier garde un peu de soleil."),
    (PAPA, "On t'a écoutée, Sarah."),
    (MAMAN, "Tu as posé le soleil."),
    (NAR, "L'histoire est finie."),
]
Q04 = [
    (NAR, "Sarah a un malaise."),
    (NAR, "Que fait-elle ?"),
]

# ---------------------------------------------------------------------------
# 05 Nino N3 — chaussette bleue, escalier, cacao, ciseaux
# ---------------------------------------------------------------------------
P05 = [
    (NAR, "Une chaussette bleue attend sur la première marche."),
    (NAR, "L'escalier en bois craque, tout doux."),
    (NAR, "Une lumière ronde vient de la cuisine."),
    (NAR, "Ça sent le cacao, un peu sucré."),
    (NAR, "Maman chante tout bas, près de la casserole."),
    (NAR, "Papa cherche l'autre chaussette sous le banc."),
    (PAPA, "La voilà."),
    (PAPA, "Elle s'était cachée."),
    (MAMAN, "La bleue t'attendait, Nino."),
    (NAR, "En ce moment, Nino s'assoit pour l'enfiler."),
    (NAR, "La laine est un peu rêche, un peu chaude."),
    (EM, "Elle chatouille, papa."),
    (PAPA, "Tire jusqu'au talon."),
    (PAPA, "Et l'autre."),
    (NAR, "Nino enfile la deuxième."),
    (MAMAN, "Tes deux pieds sont au chaud."),
    (EM, "Merci, maman."),
    (EM, "À l'école, je veux découper une bande."),
    (EM, "Une bande bleue, comme la chaussette."),
    (PAPA, "Les ciseaux attendent dans la classe."),
    (MAMAN, "Tu écoutes d'abord."),
    (EM, "Oui."),
    (NAR, "Nino pose le pied sur la marche."),
    (NAR, "L'escalier craque encore."),
    (NAR, "À l'école, la classe sent les feuilles neuves."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les ciseaux."),
    (EM, "Bonjour, maîtresse."),
    (NAR, "Nino écoute."),
    (NAR, "Il pose les ciseaux, les pointes en bas."),
    (MAIT, "Maintenant, on découpe une bande."),
    (NAR, "Nino choisit le papier bleu."),
    (NAR, "Il découpe tout doux."),
    (NAR, "La bande tombe, longue et fine."),
    (EM, "Elle ressemble à ma chaussette."),
    (MAIT, "Oui, Nino."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, d'un secret."),
    (NAR, "Nino sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Il repose les mains sur ses genoux."),
    (NAR, "Il reste près de sa chaise."),
    (NAR, "La bande bleue attend sur la table."),
    (NAR, "Le soir, la chaussette bleue sèche près du radiateur."),
    (NAR, "La porte s'ouvre."),
    (MAMAN, "Te voilà."),
    (MAMAN, "Le cacao est prêt."),
    (NAR, "Nino pose la bande bleue sur la marche."),
    (NAR, "À côté de l'endroit de ce matin."),
    (NAR, "Le ventre est encore serré."),
]
C05 = [
    (EM, "Maman."),
    (EM, "J'ai eu un malaise."),
    (EM, "Quelqu'un a parlé d'un secret."),
    (MAMAN, "On t'écoute."),
    (PAPA, "Viens près du cacao."),
    (NAR, "Nino parle."),
    (NAR, "Maman écoute."),
    (NAR, "Papa écoute."),
    (MAMAN, "Tu as bien fait."),
    (PAPA, "À l'école, on écoute la maîtresse."),
    (MAMAN, "Si tu as un malaise, tu viens raconter."),
    (NAR, "Nino souffle sur le cacao."),
    (NAR, "Une petite fumée danse."),
    (NAR, "Le ventre se desserre, un peu."),
]
E05 = [
    (NAR, "Nino boit une gorgée."),
    (NAR, "C'est chaud, un peu sucré."),
    (PAPA, "Tu as fini ta tasse ?"),
    (EM, "Presque."),
    (NAR, "Maman tient sa main."),
    (NAR, "La main est tiède."),
    (EM, "Ma bande bleue est sur la marche."),
    (MAMAN, "On la laisse sécher, comme la chaussette."),
    (NAR, "Le lendemain, l'escalier craque encore."),
    (NAR, "La chaussette bleue attend de nouveau."),
    (PAPA, "Même marche."),
    (PAPA, "Même chaussette."),
    (PAPA, "Tu es prêt ?"),
    (EM, "Je suis prêt, papa."),
    (NAR, "Nino enfile la laine."),
    (NAR, "Elle chatouille encore."),
    (NAR, "Le ventre est calme."),
    (MAMAN, "On t'écoute, chaque jour."),
    (EM, "Je le sais."),
]
F05 = [
    (NAR, "La bande bleue reste près du radiateur."),
    (NAR, "La chaussette aussi."),
    (PAPA, "On t'a écouté, Nino."),
    (MAMAN, "Le cacao a attendu."),
    (NAR, "L'histoire est finie."),
]
Q05 = [
    (NAR, "Nino a un malaise."),
    (NAR, "Que fait-il ?"),
]

# ---------------------------------------------------------------------------
# 06 Nina N2 — moufles, radiateur, hiver, crayon rouge
# ---------------------------------------------------------------------------
P06 = [
    (NAR, "Les moufles sèchent sur le radiateur."),
    (NAR, "Elles font un tout petit nuage, tout blanc."),
    (NAR, "La laine sent le froid d'en dehors."),
    (NAR, "La fenêtre tremble un peu."),
    (NAR, "Papa pose le cartable contre le mur."),
    (NAR, "Maman boutonne le manteau, une, deux, trois."),
    (NAR, "Ça sent la soupe qui attend dans la casserole."),
    (PAPA, "Les moufles fument, tu vois ?"),
    (MAMAN, "La laine redevient douce."),
    (NAR, "En ce moment, Nina pose sa joue près de la laine tiède."),
    (EF, "C'est chaud, maman."),
    (MAMAN, "Encore un moment, puis on part."),
    (EF, "Je veux dessiner le nuage des moufles."),
    (EF, "Avec le crayon rouge."),
    (PAPA, "Le crayon est dans la pochette."),
    (PAPA, "Tes deux mains seront au chaud."),
    (MAMAN, "Le bouton du haut est bien fermé ?"),
    (EF, "Oui, maman."),
    (EF, "Un, deux, trois."),
    (NAR, "Nina enfile les moufles."),
    (NAR, "La laine est douce, encore tiède."),
    (NAR, "Dehors, l'air pique un peu le nez."),
    (NAR, "Les pas sonnent sur les cailloux gelés."),
    (MAMAN, "On tient la main."),
    (NAR, "L'école est plus chaude que la rue."),
    (NAR, "Ça sent les manteaux mouillés, près des crochets."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les crayons."),
    (EF, "Bonjour, maîtresse."),
    (NAR, "Nina écoute."),
    (NAR, "Elle range son crayon rouge, tout droit."),
    (NAR, "Le rouge tape un petit coup dans la boîte."),
    (MAIT, "Merci, Nina."),
    (MAIT, "Vous avez bien écouté."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, d'un secret."),
    (NAR, "Nina sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Elle garde les mains sur la table."),
    (NAR, "Elle reste près de sa chaise."),
    (NAR, "Le soir, les moufles sont sèches, toutes douces."),
    (NAR, "La porte s'ouvre."),
    (MAMAN, "Te voilà."),
    (MAMAN, "Le manteau est lourd de froid."),
    (NAR, "Nina pose les moufles sur le radiateur."),
    (NAR, "Le petit nuage revient."),
    (NAR, "Le ventre est encore serré."),
]
C06 = [
    (EF, "Maman."),
    (EF, "J'ai eu un malaise."),
    (EF, "Quelqu'un a parlé d'un secret."),
    (MAMAN, "On t'écoute."),
    (PAPA, "Viens près de la soupe."),
    (NAR, "Nina parle."),
    (NAR, "Maman écoute."),
    (NAR, "Papa écoute."),
    (MAMAN, "Tu as bien fait de raconter."),
    (PAPA, "À l'école, on écoute la maîtresse."),
    (MAMAN, "Si tu as un malaise, tu viens le dire."),
    (NAR, "Le ventre de Nina se desserre, tout doucement."),
]
E06 = [
    (NAR, "Maman verse la soupe."),
    (NAR, "La vapeur fait de la buée."),
    (PAPA, "Tu as tes deux mains libres ?"),
    (EF, "Oui, papa."),
    (NAR, "Nina souffle sur la cuillère."),
    (NAR, "C'est chaud, comme les moufles."),
    (MAMAN, "Tu as fini ta bolée ?"),
    (EF, "Presque."),
    (NAR, "Nina pose encore la joue près de la laine."),
    (EF, "Le nuage est revenu."),
    (PAPA, "On le laisse sécher."),
    (NAR, "La fenêtre tremble moins."),
    (NAR, "La cuisine est calme."),
    (EF, "Merci, maman."),
    (EF, "Merci, papa."),
]
F06 = [
    (NAR, "Les moufles reposent, toutes douces."),
    (NAR, "La soupe n'envoie plus de nuage."),
    (MAMAN, "On t'a écoutée, Nina."),
    (PAPA, "Tes mains sont au chaud."),
    (NAR, "L'histoire est finie."),
]
Q06 = [
    (NAR, "Nina a un malaise."),
    (NAR, "Que fait-elle ?"),
]

# ---------------------------------------------------------------------------
# 07 Amir N2 — craie, platane, feutre vert
# ---------------------------------------------------------------------------
P07 = [
    (NAR, "De la craie blanche poudre le pas de la porte."),
    (NAR, "Un platane du village bouge, tout lent."),
    (NAR, "Une feuille tourne, puis s'arrête."),
    (NAR, "Papa secoue le tapis."),
    (NAR, "Un nuage gris s'envole."),
    (NAR, "Maman ferme la boîte des feutres, clic."),
    (NAR, "Ça sent le bois du tapis et l'air du matin."),
    (PAPA, "Il reste de la marelle, d'hier."),
    (MAMAN, "La craie a fait un petit chemin blanc."),
    (NAR, "En ce moment, Amir souffle sur la craie."),
    (NAR, "La poudre vole, puis retombe."),
    (EM, "Elle pique le nez, papa."),
    (PAPA, "Souffle à côté."),
    (NAR, "Amir souffle sur le côté."),
    (NAR, "La poudre part vers le platane."),
    (PAPA, "Tes pieds restent sur la pierre."),
    (EM, "Je veux emporter le feutre vert."),
    (EM, "Pour la marelle, plus tard."),
    (MAMAN, "Tu as tes feutres dans la boîte ?"),
    (EM, "Oui, maman."),
    (EM, "Clic."),
    (PAPA, "Le platane a encore des feuilles jaunes, tu vois ?"),
    (EM, "Oui."),
    (EM, "Une est tombée."),
    (MAMAN, "On la laisse."),
    (MAMAN, "Elle est jolie par terre."),
    (PAPA, "On y va."),
    (PAPA, "Tu dis au revoir à maman."),
    (EM, "Au revoir, maman."),
    (MAMAN, "Je t'écoute ce soir, Amir."),
    (NAR, "L'école sent les feutres et le papier."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les feutres."),
    (EM, "Bonjour, maîtresse."),
    (NAR, "Amir écoute."),
    (NAR, "Il range son feutre vert, le bouchon bien fermé."),
    (NAR, "Le vert sent un peu fort, tout près."),
    (MAIT, "Merci, Amir."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, d'un secret."),
    (NAR, "Amir sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Il repose les mains sur ses genoux."),
    (NAR, "Il reste près de sa chaise."),
    (NAR, "Le soir, la craie est encore sur la pierre."),
    (NAR, "La porte s'ouvre."),
    (PAPA, "Te voilà."),
    (PAPA, "Le tapis est rentré."),
    (NAR, "Amir regarde le chemin blanc."),
    (NAR, "La feuille jaune est encore là."),
    (NAR, "Le ventre est encore serré."),
]
C07 = [
    (EM, "Papa."),
    (EM, "J'ai eu un malaise."),
    (EM, "Quelqu'un a parlé d'un secret."),
    (PAPA, "On t'écoute."),
    (MAMAN, "Viens sur la pierre, près de nous."),
    (NAR, "Amir parle."),
    (NAR, "Papa écoute."),
    (NAR, "Maman écoute."),
    (PAPA, "Tu as bien fait de raconter."),
    (MAMAN, "À l'école, on écoute la maîtresse."),
    (PAPA, "Si tu as un malaise, tu viens le dire."),
    (NAR, "Le ventre d'Amir se desserre."),
]
E07 = [
    (NAR, "Maman verse un peu d'eau dans un verre."),
    (NAR, "L'eau fait un petit bruit clair."),
    (MAMAN, "Tu veux un peu d'eau ?"),
    (EM, "Oui."),
    (EM, "Merci, maman."),
    (NAR, "Amir boit une gorgée."),
    (PAPA, "Tu as tes pieds sur la pierre ?"),
    (EM, "Oui, papa."),
    (NAR, "Amir souffle encore, à côté de la craie."),
    (NAR, "Un peu de poudre s'envole."),
    (EM, "Elle ne pique plus."),
    (MAMAN, "La feuille jaune est toujours là."),
    (EM, "On la laisse."),
    (PAPA, "On reste encore un peu ensemble ?"),
    (EM, "Oui, papa."),
    (NAR, "Le platane bouge, tout lent."),
]
F07 = [
    (NAR, "Le chemin de craie s'efface un peu."),
    (NAR, "La feuille jaune reste sous le platane."),
    (PAPA, "On t'a écouté, Amir."),
    (MAMAN, "Tu as rangé ton feutre, puis tu as raconté."),
    (NAR, "L'histoire est finie."),
]
Q07 = [
    (NAR, "Amir a un malaise."),
    (NAR, "Que fait-il ?"),
]

# ---------------------------------------------------------------------------
# 08 Raphaël N3 — cartable, horloge, gourde, feutre orange
# ---------------------------------------------------------------------------
P08 = [
    (NAR, "Le cartable s'appuie contre le bois de la porte."),
    (NAR, "Le bois est froid, un peu lisse."),
    (NAR, "L'horloge du couloir fait tic, tic."),
    (NAR, "Une poussière dore dans le rayon du matin."),
    (NAR, "Maman noue les lacets, un nœud, puis l'autre."),
    (NAR, "Papa glisse une gourde dans la poche."),
    (NAR, "Ça sent le cuir du cartable et le pain du petit déjeuner."),
    (MAMAN, "L'horloge a une voix, tu l'entends ?"),
    (EM, "Tic, tic."),
    (EM, "Elle est lente."),
    (PAPA, "Elle nous dit : c'est l'heure."),
    (NAR, "En ce moment, Raphaël écoute le tic de l'horloge."),
    (NAR, "Il pose la main sur le cartable."),
    (NAR, "Le tissu est rêche."),
    (EM, "Il est lourd, papa."),
    (EM, "Je veux le porter jusqu'à l'école."),
    (PAPA, "La gourde est dedans."),
    (PAPA, "On le porte ensemble jusqu'à la porte."),
    (NAR, "Raphaël soulève le cartable."),
    (NAR, "Il avance d'un pas, puis un autre."),
    (MAMAN, "Tu dis bonjour à la maîtresse."),
    (MAMAN, "Et merci à la fin."),
    (EM, "Oui, maman."),
    (NAR, "L'école sent les feutres."),
    (NAR, "Les casiers claquent tout doux."),
    (MAIT, "Bonjour."),
    (MAIT, "On range les feutres."),
    (EM, "Bonjour, maîtresse."),
    (NAR, "Raphaël écoute."),
    (NAR, "Il range son feutre orange, le bouchon bien enfoncé."),
    (NAR, "L'orange sent fort, comme une peau d'agrume."),
    (MAIT, "Merci, Raphaël."),
    (NAR, "Plus tard, quelqu'un s'approche."),
    (NAR, "Une voix parle tout bas, d'un secret."),
    (NAR, "Raphaël sent un malaise."),
    (NAR, "Son ventre se serre."),
    (NAR, "Il écoute encore la classe, tout près de sa chaise."),
    (NAR, "Il se souvient du tic de l'horloge, à la maison."),
    (NAR, "Le soir, le cartable s'appuie encore contre la porte."),
    (NAR, "L'horloge fait tic, tic, plus lent, plus doux."),
    (NAR, "La porte s'ouvre."),
    (PAPA, "Te voilà."),
    (PAPA, "La gourde est vide ?"),
    (NAR, "Raphaël pose le cartable."),
    (NAR, "Le tissu est encore rêche."),
    (NAR, "Le ventre est encore serré."),
]
C08 = [
    (EM, "Papa."),
    (EM, "J'ai eu un malaise."),
    (EM, "Quelqu'un a parlé d'un secret."),
    (PAPA, "On t'écoute."),
    (MAMAN, "Viens près de l'horloge."),
    (NAR, "Raphaël parle."),
    (NAR, "Papa écoute."),
    (NAR, "Maman écoute."),
    (PAPA, "Tu as bien fait de raconter."),
    (MAMAN, "À l'école, on écoute la maîtresse."),
    (PAPA, "Si tu as un malaise, tu viens le dire."),
    (EM, "L'horloge m'a rappelé la maison."),
    (PAPA, "Et tu es venu nous le dire."),
    (NAR, "Le ventre de Raphaël se desserre, au rythme du tic."),
]
E08 = [
    (NAR, "Maman prend la gourde."),
    (NAR, "L'eau chante dans le goulot."),
    (MAMAN, "On la remplit pour demain ?"),
    (EM, "Oui, maman."),
    (NAR, "Raphaël tient la gourde des deux mains."),
    (NAR, "Elle redevient lourde, un peu froide."),
    (PAPA, "Tu la glisses dans la poche ?"),
    (EM, "Oui."),
    (NAR, "Le cartable reprend son poids."),
    (NAR, "Raphaël l'appuie contre le bois."),
    (EM, "Tic, tic."),
    (MAMAN, "Elle dit : demain, c'est encore l'heure."),
    (PAPA, "On reste encore un peu dans le couloir ?"),
    (EM, "Oui, papa."),
    (NAR, "La poussière dore encore, plus bas."),
]
F08 = [
    (NAR, "Le cartable attend contre la porte."),
    (NAR, "L'horloge fait tic, tout doux."),
    (PAPA, "On t'a écouté, Raphaël."),
    (MAMAN, "La gourde est pleine, pour demain."),
    (NAR, "L'histoire est finie."),
]
Q08 = [
    (NAR, "Raphaël a un malaise."),
    (NAR, "Que fait-il ?"),
]


def main() -> None:
    stories = [
        (
            {
                "story_id": "ATOM-COL.ECO.001-01",
                "fil_rouge": "Aniss veut dessiner la pluie avec son crayon jaune. À l'école il écoute et range le crayon. Un chuchotement serre son ventre. Le soir, il raconte, puis il dessine la gouttière.",
                "title": "La gouttière et le crayon d'Aniss",
                "characters": "Aniss, papa, maman, maîtresse",
                "setting": "cuisine sous la pluie, école, puis table du soir",
                "age_band": "N2",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P01, sons="pluie,porte", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q01,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | il raconte | à papa | à la maison | écouter",
                    retry_prompt="Il raconte à papa. Que fait Aniss ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C01, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E01, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F01, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-02",
                "fil_rouge": "Mila veut chanter le refrain en classe. Le rayon d'or l'accompagne. Un chuchotement serre son ventre. Elle chante quand même. Le soir, elle raconte, puis elle reprend le refrain près de la fenêtre.",
                "title": "Le rayon de Mila",
                "characters": "Mila, papa, maman, maîtresse",
                "setting": "cuisine à la buée, classe au tapis d'or, puis mur rose",
                "age_band": "N3",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P02, sons="oiseau,porte", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q02,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | elle raconte | à maman | à la maison | écouter",
                    retry_prompt="Elle raconte à maman. Que fait Mila ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C02, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E02, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F02, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-03",
                "fil_rouge": "Victorino veut découper un rond de papier comme le pain tiède. À l'école il écoute et pose les ciseaux. Un chuchotement serre son ventre. Le soir, il raconte, et les deux ronds se regardent sur la nappe.",
                "title": "Le pain chaud de Victorino",
                "characters": "Victorino, papa, maman, maîtresse",
                "setting": "cuisine au pain du village, classe, puis nappe du soir",
                "age_band": "N2",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P03, sons="porte,pas", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q03,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | à la maison | maman | écouter",
                    retry_prompt="Il écoute la maîtresse. S'il a un malaise ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C03, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E03, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F03, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-04",
                "fil_rouge": "Sarah veut poser le soleil en papier sur le tableau. Le linge danse au jardin. Au portail, une voix trop près serre son ventre. Le soir, elle raconte, puis elle croque une pêche au vrai soleil.",
                "title": "Le soleil de Sarah",
                "characters": "Sarah, papa, maman, maîtresse",
                "setting": "jardin au linge, classe, puis fenêtre sur le cerisier",
                "age_band": "N2",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P04, sons="enfants_parc,porte", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q04,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="écouter",
                    accepted_examples="écouter | raconter | à la maison | papa | malaise",
                    retry_prompt="Elle écoute la maîtresse. Puis elle raconte à la maison. Que fait Sarah ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C04, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E04, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F04, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-05",
                "fil_rouge": "Nino trouve sa chaussette bleue, puis découpe une bande pareille à l'école. Un chuchotement serre son ventre. Le soir, il raconte près du cacao. Le lendemain, la chaussette l'attend, le ventre est calme.",
                "title": "La chaussette de Nino",
                "characters": "Nino, papa, maman, maîtresse",
                "setting": "escalier de bois, classe, radiateur du soir",
                "age_band": "N3",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P05, sons="pas,porte", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q05,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | il raconte | à maman | à la maison | écouter",
                    retry_prompt="Il raconte à maman. Que fait Nino ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C05, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E05, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F05, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-06",
                "fil_rouge": "Nina veut réchauffer ses moufles, puis poser son crayon rouge. L'air pique. Un chuchotement serre son ventre. Le soir, elle raconte, et le nuage des moufles revient sur le radiateur.",
                "title": "Les moufles de Nina",
                "characters": "Nina, papa, maman, maîtresse",
                "setting": "entrée d'hiver, école, soupe du soir",
                "age_band": "N2",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P06, sons="pluie,porte", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q06,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | elle raconte | à maman | à la maison | écouter",
                    retry_prompt="Elle raconte à maman. Que fait Nina ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C06, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E06, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F06, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-07",
                "fil_rouge": "Amir souffle la poudre de marelle, puis ferme son feutre vert à l'école. Un chuchotement serre son ventre. Le soir, il raconte, et la feuille jaune reste sous le platane.",
                "title": "La craie d'Amir",
                "characters": "Amir, papa, maman, maîtresse",
                "setting": "pas de la porte, platane du village, pierre du soir",
                "age_band": "N2",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P07, sons="porte,pas", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q07,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | il raconte | à papa | à la maison | écouter",
                    retry_prompt="Il raconte à papa. Que fait Amir ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C07, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E07, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F07, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
        (
            {
                "story_id": "ATOM-COL.ECO.001-08",
                "fil_rouge": "Raphaël veut porter le cartable lourd jusqu'à l'école. L'horloge fait tic. Un chuchotement serre son ventre. Le soir, il raconte, et on remplit la gourde pour demain.",
                "title": "Le cartable de Raphaël",
                "characters": "Raphaël, papa, maman, maîtresse",
                "setting": "couloir à l'horloge, école, porte du soir",
                "age_band": "N3",
            },
            [
                chk("CHK_T0000_P0000", "passage_debut", P08, sons="porte,horloge", scale=1.22, pause=400),
                chk(
                    "CHK_T0000_P0000_Q0001",
                    "passage_question",
                    Q08,
                    sons="",
                    scale=1.28,
                    rate="slow",
                    pause=250,
                    expected_answer="raconter",
                    accepted_examples="raconter | il raconte | à papa | à la maison | écouter",
                    retry_prompt="Il raconte à papa. Que fait Raphaël ?",
                ),
                chk("CHK_T0000_P0000_C0001", "passage", C08, sons="", scale=1.18, pause=450),
                chk("CHK_T0000_P0000_END", "passage", E08, sons="", scale=1.22, pause=450),
                chk("CHK_T0000_P0000_END_F0001", "passage_fin", F08, sons="", scale=1.22, rate="slow", pause=600),
            ],
            16,
        ),
    ]

    for meta, chunks, cap in stories:
        sid = meta["story_id"]
        for c in chunks:
            lines = []
            for ln in c["script"].splitlines():
                role, phrase = ln.split("|", 1)
                lines.append((role, phrase))
            max_phrase(lines, cap, sid, c["chunk_id"])
            if "bravo" in c["text"].lower() and "bon travail" in c["text"].lower():
                raise SystemExit(f"{sid} {c['chunk_id']}: refrain bravo+bon travail")
        dump_story(meta, chunks)


if __name__ == "__main__":
    main()
