#!/usr/bin/env python3
"""Réécrit ATOM-TMP.MET.001-06..08 et ATOM-TMP.MOI.001-01..05."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-TMP.MET.001-06 N2 Aniss, papa — pain, pluie, flaque
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-06",
    "Aniss veut le pain chaud du village. Il pleut. Il prend manteau et bottes. Une flaque barre le chemin. Les bottes font splish. Le pain rentre dans la corbeille.",
    "La corbeille vide",
    "Aniss, papa",
    "maison, rue du village sous la pluie, boulangerie",
    {
        "CHK_T0000_P0000": [
            "narrateur|La corbeille à pain est encore vide.",
            "narrateur|Elle attend sur la table de bois.",
            "narrateur|Une miette sèche y reste, toute seule.",
            "papa|Il n'y a plus de pain, Aniss.",
            "enfant-m|On va en chercher ?",
            "papa|Oui.",
            "papa|Chez le boulanger.",
            "narrateur|Dehors, la pluie tape le volet.",
            "narrateur|Le volet claque un peu.",
            "narrateur|L'air qui entre est froid.",
            "narrateur|Il pique les joues.",
            "enfant-m|J'ai froid aux mains.",
            "papa|Tu prends le manteau.",
            "papa|Il fait froid.",
            "narrateur|Le manteau bleu pend au crochet.",
            "narrateur|Aniss le prend.",
            "narrateur|Il glisse la manche gauche.",
            "narrateur|Puis la droite.",
            "narrateur|Le tissu est un peu rêche, déjà chaud.",
            "papa|Le zip, tout doux.",
            "narrateur|Papa ferme le zip.",
            "narrateur|Ça fait zzz.",
            "enfant-m|Je suis au chaud.",
            "papa|Il pleut aussi.",
            "papa|Tu mets les bottes.",
            "narrateur|Les bottes jaunes attendent près du paillasson.",
            "narrateur|Le paillasson est déjà mouillé.",
            "narrateur|Aniss pose le pied gauche.",
            "narrateur|La botte colle un peu.",
            "narrateur|Puis le pied droit.",
            "enfant-m|Elles sont jaunes.",
            "papa|Oui.",
            "papa|Tes pieds resteront au sec.",
            "papa|Tu as tes bottes ?",
            "enfant-m|Oui, papa.",
            "narrateur|En ce moment, papa ouvre la porte.",
            "narrateur|La pluie sent la terre.",
            "narrateur|L'eau court dans le zinc.",
            "enfant-m|Ça chante.",
            "papa|C'est la pluie.",
            "narrateur|Ils marchent vers le village.",
            "narrateur|Le chemin brille.",
            "narrateur|Une grande flaque barre le passage.",
            "enfant-m|Une mer !",
            "papa|Une flaque.",
            "papa|On la contourne ?",
            "enfant-m|Je peux dessus.",
            "papa|Avec tes bottes, oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait froid.",
            "narrateur|Il pleut.",
            "narrateur|Que prend Aniss ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss pose un pied dans l'eau.",
            "narrateur|Ça fait splish.",
            "narrateur|L'eau monte un peu.",
            "narrateur|Elle n'entre pas.",
            "enfant-m|Mes pieds sont au sec !",
            "papa|Le manteau te tient chaud.",
            "papa|Les bottes te tiennent au sec.",
            "narrateur|Il pose l'autre pied.",
            "narrateur|Splish encore.",
            "narrateur|Une feuille tourne dans la flaque.",
            "enfant-m|Elle nage.",
            "papa|On continue.",
            "papa|Le pain nous attend.",
            "narrateur|Le village sent la farine mouillée.",
            "narrateur|La vitrine de la boulangerie est embuée.",
            "enfant-m|Je vois le pain !",
            "papa|Il est tout chaud.",
            "narrateur|Papa pousse la porte.",
            "narrateur|Une clochette sonne.",
            "narrateur|L'air dedans sent le four.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le boulanger tend un pain doré.",
            "narrateur|La croûte craque un peu.",
            "enfant-m|Il est lourd.",
            "papa|Tu le portes ?",
            "enfant-m|Oui.",
            "narrateur|Aniss serre le pain contre le manteau.",
            "narrateur|Le pain chauffe le tissu.",
            "papa|Merci, Aniss.",
            "papa|Tu tiens bien.",
            "narrateur|Ils retraversent la rue brillante.",
            "narrateur|La flaque est encore là.",
            "enfant-m|Splish !",
            "papa|Tes bottes travaillent.",
            "narrateur|Une goutte glisse sur le pain.",
            "narrateur|Aniss le cache un peu.",
            "papa|Le manteau le garde.",
            "enfant-m|Il reste chaud.",
            "narrateur|La maison se rapproche.",
            "narrateur|Le volet claque encore, plus doux.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Papa ouvre la porte.",
            "narrateur|L'odeur du pain entre avant eux.",
            "narrateur|Aniss pose le pain dans la corbeille.",
            "narrateur|La corbeille n'est plus vide.",
            "enfant-m|Il est rentré.",
            "papa|Oui.",
            "papa|Tu poses les bottes ?",
            "narrateur|Les bottes gouttent près du paillasson.",
            "narrateur|Le manteau s'égoutte au crochet.",
            "narrateur|Une miette chaude reste sur la table.",
            "enfant-m|Je la prends.",
            "papa|Elle est à toi.",
            "narrateur|Dehors, la flaque brille encore.",
            "narrateur|Dedans, le pain sent le four.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | bottes | le manteau | les bottes",
        "retry_prompt": "Froid, manteau. Pluie, bottes. Que prend-il ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-06",
    "La corbeille vide",
    "Aniss et papa vont chercher le pain sous la pluie. Manteau, bottes, flaque, pain chaud dans la corbeille.",
    "Leçon greffée : froid manteau, pluie bottes. Imprévu : la flaque. Pas de liste de mois. D16 Aniss, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MET.001-07 N3 Mila, maman — orage, poules, trou de soleil
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-07",
    "Mila veut porter le grain aux poules. L'orage tape le poulailler. Elle met manteau et bottes. Un trou de soleil s'ouvre. Les poules sortent. Le grain tombe dans l'auge mouillée.",
    "Le trou de soleil",
    "Mila, maman",
    "maison, jardin, poulailler après l'orage",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le toit du poulailler sonne comme un tambour.",
            "narrateur|Les gouttes frappent le zinc, fort.",
            "narrateur|Une poule grise s'abrite sous la planche.",
            "enfant-f|Elles ont faim, maman.",
            "maman|L'orage passe encore.",
            "maman|On attend un peu.",
            "narrateur|La cuisine sent le grain dans le seau.",
            "narrateur|Le seau est rouge, un peu ébréché.",
            "enfant-f|Je veux le porter.",
            "maman|Oui.",
            "maman|Quand le ciel s'ouvre.",
            "narrateur|La vitre est toute striée.",
            "narrateur|Un éclair lointain blanchit le cerisier.",
            "enfant-f|J'ai froid aux bras.",
            "maman|Tu prends le manteau.",
            "maman|Il fait froid.",
            "narrateur|Le manteau vert pend près des crochets.",
            "narrateur|Mila glisse les manches.",
            "narrateur|Le tissu sent encore la pluie d'hier.",
            "maman|Le zip, tout au bout.",
            "narrateur|Mila tire le zip.",
            "narrateur|Ça fait zzz, puis ça coince.",
            "enfant-f|Il ne veut pas.",
            "maman|Doucement.",
            "narrateur|Maman aide le curseur.",
            "narrateur|Le zip part.",
            "enfant-f|Il est passé.",
            "maman|Il pleut encore un peu.",
            "maman|Tu mets les bottes.",
            "narrateur|Les bottes bleues attendent sous le banc.",
            "narrateur|Mila y pose les pieds.",
            "narrateur|La semelle colle au talon.",
            "maman|Tu as tes bottes ?",
            "enfant-f|Oui, maman.",
            "narrateur|En ce moment, un trou de soleil perce le nuage.",
            "narrateur|Un carré clair tombe sur l'herbe.",
            "enfant-f|Le ciel a un trou !",
            "maman|L'orage s'en va.",
            "maman|On peut aller aux poules.",
            "narrateur|Maman prend le seau de grain.",
            "narrateur|Mila tient l'anse avec elle.",
            "narrateur|La porte du jardin craque.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait froid.",
            "narrateur|Il pleut.",
            "narrateur|Que prend Mila ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'herbe mouillée chatouille les bottes.",
            "narrateur|Ça fait floc, floc.",
            "narrateur|Une flaque étroite coupe le sentier.",
            "enfant-f|Je passe.",
            "maman|Avec tes bottes, oui.",
            "narrateur|Mila enjambe l'eau.",
            "narrateur|Une goutte tombe encore du cerisier.",
            "narrateur|Elle tape le manteau.",
            "enfant-f|Je suis au chaud.",
            "maman|Le manteau travaille.",
            "narrateur|Le poulailler sent la paille mouillée.",
            "narrateur|La poule grise sort la tête.",
            "enfant-f|Coucou.",
            "maman|Elles t'attendaient.",
            "narrateur|Mila pose le seau près de l'auge.",
            "narrateur|Le grain glisse.",
            "narrateur|Ça fait chh sur le bois mouillé.",
            "maman|Tu verses bien.",
            "enfant-f|Pour elles.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Trois poules viennent, encore humides.",
            "narrateur|Leurs plumes brillent.",
            "narrateur|Une rouge picore tout près de la botte.",
            "enfant-f|Elle n'a pas peur.",
            "maman|Tu es restée douce.",
            "maman|Merci, Mila.",
            "narrateur|Le trou de soleil s'élargit.",
            "narrateur|Une vapeur monte de l'auge.",
            "enfant-f|Ça fume.",
            "maman|L'eau s'en va.",
            "narrateur|Mila recule d'un pas.",
            "narrateur|Une botte glisse un peu dans la boue.",
            "maman|Doucement.",
            "enfant-f|Je tiens.",
            "narrateur|La poule grise rentre sous la planche.",
            "narrateur|Puis elle ressort, le jabot plein.",
            "maman|On rentre ?",
            "enfant-f|Encore une minute.",
            "maman|D accord.",
            "narrateur|Un dernier grain roule vers l'herbe.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Mila referme le loquet du poulailler.",
            "narrateur|Le zinc ne sonne plus.",
            "enfant-f|Le tambour s'est tu.",
            "maman|L'orage est parti.",
            "narrateur|Elles marchent vers la maison.",
            "narrateur|Le manteau vert s'égoutte un peu.",
            "narrateur|Les bottes laissent deux traces sombres.",
            "maman|Tu poses les bottes près du banc ?",
            "enfant-f|Oui.",
            "narrateur|Le seau vide sonne, léger.",
            "narrateur|Le trou de soleil reste sur le cerisier.",
            "narrateur|Une poule chante, tout bas.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | le manteau | bottes | les bottes",
        "retry_prompt": "Froid : manteau. Pluie : bottes. Que prend-elle ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-07",
    "Le trou de soleil",
    "Mila veut porter le grain aux poules. Orage, manteau, bottes, puis trou de soleil. Les poules picorent.",
    "Leçon greffée dans la sortie vers le poulailler. Imprévu : zip coincé, botte dans la boue. D16 Mila, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MET.001-08 N3 Nino, maman, papa — deux sorties
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-08",
    "Nino veut glisser une lettre dans la boîte rouge. Le matin, il pleut : manteau et bottes. Le soir, le ciel s'ouvre : encore le manteau, l'air reste frais. La lettre part. Le jardin sent la terre.",
    "La lettre sous la pluie",
    "Nino, maman, papa",
    "maison, rue sous la pluie, jardin à l'éclaircie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le lait du matin fume encore dans le bol.",
            "narrateur|Une peau fine danse à la surface.",
            "narrateur|Sur la table, une enveloppe attend, un peu trop grande.",
            "enfant-m|C'est ma lettre.",
            "maman|Pour la boîte rouge.",
            "papa|Il pleut fort.",
            "papa|On y va quand même.",
            "narrateur|Les gouttes tapent le rebord de la fenêtre.",
            "narrateur|Le jardin est tout gris.",
            "enfant-m|J'ai froid.",
            "maman|Tu prends le manteau.",
            "maman|Il fait froid.",
            "narrateur|Le manteau gris sent la laine.",
            "narrateur|Nino enfile les manches.",
            "narrateur|Un bouton résiste.",
            "papa|Celui du milieu.",
            "narrateur|Nino pousse le bouton.",
            "narrateur|Il passe, enfin.",
            "enfant-m|Il est entré.",
            "papa|Il pleut.",
            "papa|Tu mets les bottes.",
            "narrateur|Les bottes noires sont près du seau.",
            "narrateur|Nino y glisse les pieds.",
            "maman|Tu as tes bottes ?",
            "enfant-m|Oui, maman.",
            "narrateur|Papa tend l'enveloppe.",
            "narrateur|Un coin est déjà un peu mou.",
            "enfant-m|Oh.",
            "papa|On la cache sous le manteau.",
            "narrateur|Nino serre la lettre contre lui.",
            "narrateur|En ce moment, ils ouvrent la porte.",
            "narrateur|La pluie sent le zinc et la terre.",
            "maman|Je reste ici.",
            "maman|Je prépare le soir.",
            "papa|On revient vite.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait froid, puis il pleut.",
            "narrateur|Que prend Nino ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La boîte rouge brille sous l'auvent.",
            "narrateur|Une goutte veut tomber sur l'enveloppe.",
            "papa|Le manteau au-dessus.",
            "narrateur|Nino lève le pan du manteau.",
            "narrateur|La lettre reste sèche.",
            "enfant-m|Je la glisse.",
            "narrateur|L'enveloppe rentre, chh.",
            "narrateur|La fente referme sa bouche.",
            "papa|Elle est partie.",
            "papa|Merci, Nino.",
            "enfant-m|Même sous la pluie.",
            "papa|Manteau et bottes.",
            "narrateur|Ils rentrent.",
            "narrateur|Les bottes font floc dans la cour.",
            "narrateur|Maman ouvre avant qu'ils toquent.",
            "maman|Vous êtes trempés ?",
            "enfant-m|Le manteau a travaillé.",
            "maman|Bien.",
            "narrateur|Les bottes gouttent près du seau.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Plus tard, le ciel se déchire.",
            "narrateur|Un rose pâle se pose sur le jardin.",
            "enfant-m|L'éclaircie !",
            "maman|On sort encore.",
            "maman|Voir si les salades tiennent.",
            "papa|L'air reste frais.",
            "papa|On reprend le manteau ?",
            "enfant-m|Oui.",
            "narrateur|Nino reprend le manteau gris.",
            "narrateur|Il est encore un peu humide.",
            "maman|Les bottes aussi.",
            "maman|La terre est molle.",
            "narrateur|Le jardin sent la terre ouverte.",
            "narrateur|Une salade s'est couchée.",
            "enfant-m|Je la redresse.",
            "narrateur|Nino la relève, tout doux.",
            "maman|Elle va boire.",
            "papa|Tu as tes bottes dans la boue.",
            "enfant-m|Mes pieds sont au sec.",
            "narrateur|Une dernière goutte tombe du cerisier.",
            "narrateur|Elle tape l'épaule du manteau.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Ils rentrent quand le rose s'éteint.",
            "narrateur|Le manteau reprend le crochet.",
            "narrateur|Les bottes se touchent près du seau.",
            "enfant-m|Deux sorties.",
            "maman|Un manteau.",
            "papa|Et des bottes, pour la pluie.",
            "narrateur|L'enveloppe n'est plus sur la table.",
            "narrateur|La boîte rouge la garde.",
            "enfant-m|Elle dort là-bas.",
            "maman|Oui.",
            "narrateur|Le lait du soir n'a plus de peau.",
            "narrateur|Le jardin, derrière la vitre, respire.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | le manteau | bottes | les bottes",
        "retry_prompt": "Froid, manteau. Pluie, bottes. Que prend-il ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-08",
    "La lettre sous la pluie",
    "Nino glisse une lettre sous la pluie du matin, manteau et bottes. Le soir, éclaircie, même manteau, jardin mouillé.",
    "Deux sorties, leçon greffée. Imprévu : enveloppe un peu molle, goutte. D16 Nino, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-01 N2 Sarah, maman — juin, fraises
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-01",
    "C'est l'anniversaire de Sarah, en juin, quand les fraises du jardin sont mûres. Elle en cueille une trop verte. La rouge est bonne. Le gâteau attend, parfumé.",
    "La fraise trop verte",
    "Sarah, maman",
    "jardin de fraisiers, puis table de la cuisine",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sous les feuilles, une fraise cache sa joue rouge.",
            "narrateur|Le jardin sent le sucre et la terre chaude.",
            "narrateur|Une abeille passe loin, très loin.",
            "maman|C'est juin, Sarah.",
            "maman|Les fraises sont prêtes.",
            "enfant-f|C'est mon mois.",
            "maman|Oui.",
            "maman|Ton anniversaire.",
            "narrateur|Le petit panier de paille attend près du pied.",
            "narrateur|Sarah s'accroupit.",
            "narrateur|Une feuille lui chatouille le poignet.",
            "enfant-f|J en vois une.",
            "maman|Tu la prends ?",
            "narrateur|Sarah tire.",
            "narrateur|La fraise vient, trop claire.",
            "narrateur|Elle est presque blanche, un peu dure.",
            "enfant-f|Elle est petite.",
            "maman|Elle est trop verte.",
            "maman|Elle n'est pas prête.",
            "narrateur|Sarah la pose dans l'herbe.",
            "narrateur|La fraise verte reste au pied.",
            "enfant-f|Je la laisse.",
            "maman|Oui.",
            "maman|On cherche une rouge.",
            "narrateur|En ce moment, Sarah lève une feuille.",
            "narrateur|Une fraise sombre brille dessous.",
            "enfant-f|Celle-là.",
            "maman|Elle est mûre.",
            "narrateur|Sarah la cueille, tout doux.",
            "narrateur|Le fruit est chaud de soleil.",
            "maman|Tu la sens ?",
            "enfant-f|Ça sent le gâteau.",
            "maman|On en mettra dessus.",
            "narrateur|Le panier reçoit trois rouges.",
            "narrateur|Puis une quatrième, un peu plus petite.",
            "maman|Juin donne les fraises.",
            "maman|Et toi, tu as un an de plus.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah a un gâteau en juin.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Elles rentrent.",
            "narrateur|La cuisine sent déjà la pâte chaude.",
            "narrateur|Le gâteau repose, tout nu.",
            "enfant-f|Il attend les fraises.",
            "maman|Oui.",
            "maman|Parce que c'est ton anniversaire.",
            "narrateur|Sarah pose une rouge au milieu.",
            "narrateur|Le jus tache un peu le dessus.",
            "enfant-f|Une étoile.",
            "maman|Une fraise.",
            "narrateur|Elle en pose deux autres, tout autour.",
            "maman|La verte reste au jardin.",
            "enfant-f|Elle grandira.",
            "maman|En juin, les rouges d'abord.",
            "narrateur|Maman coupe une part mince.",
            "narrateur|Sarah tient l'assiette à deux mains.",
            "maman|Tu goûtes ?",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sarah croque la fraise du dessus.",
            "narrateur|Le jus sucré lui reste au menton.",
            "enfant-f|Elle est bonne.",
            "maman|Parce qu elle était rouge.",
            "narrateur|Une graine minuscule colle au doigt.",
            "narrateur|Sarah la souffle.",
            "maman|Merci, Sarah.",
            "maman|Tu as choisi les mûres.",
            "enfant-f|Pas la verte.",
            "maman|Pas la verte.",
            "narrateur|Le panier a encore deux fruits.",
            "narrateur|Ils sentent le soleil de juin.",
            "enfant-f|C'est mon mois.",
            "maman|Le mois de ton anniversaire.",
            "narrateur|Une mouche tourne près de la fenêtre.",
            "maman|On range le reste au frais.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sarah essuie le menton d'un revers.",
            "narrateur|Il reste une trace rose.",
            "enfant-f|Encore un peu de jus.",
            "maman|C'est le goût de juin.",
            "narrateur|Le gâteau a un trou au milieu.",
            "narrateur|Là où la fraise était.",
            "enfant-f|Elle est dans mon ventre.",
            "maman|Oui.",
            "narrateur|Dehors, la verte attend sous sa feuille.",
            "narrateur|Dedans, le panier sent encore le jardin.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "anniversaire",
        "accepted_examples": "anniversaire | son anniversaire | juin | le mois | fraises",
        "retry_prompt": "C'est son anniversaire. Pourquoi le gâteau ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-01",
    "La fraise trop verte",
    "Anniversaire de Sarah en juin : fraises du jardin. Une trop verte, les rouges sur le gâteau.",
    "Le mois est dit parce que les fraises sont mûres, pas une liste. Imprévu : fraise verte. D16 Sarah, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-02 N2 Amir, papa — calendrier, juin, pique-nique
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-02",
    "Amir veut marquer le pique-nique sur le calendrier mural. Papa tourne les pages. Avril trop tôt, mai presque, juin : les fraises et la nappe. Une page colle. Amir la décolle. L'étoile est sur juin.",
    "La page de juin",
    "Amir, papa",
    "cuisine, calendrier mural près de la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le calendrier mural a une page un peu recourbée.",
            "narrateur|Un coin d'encre a pâli au soleil.",
            "narrateur|La cuisine sent le café froid de papa.",
            "enfant-m|On cherche notre pique-nique.",
            "papa|Oui.",
            "papa|Il faut le bon mois.",
            "narrateur|Une nappe à carreaux attend sur la chaise.",
            "enfant-m|Pour près de la rivière.",
            "papa|Quand le mois sera le bon.",
            "narrateur|Papa accroche mieux le clou.",
            "narrateur|Le calendrier se tient droit.",
            "enfant-m|Je tourne ?",
            "papa|Doucement.",
            "narrateur|Amir tire une page.",
            "narrateur|Le papier fait un petit fsh.",
            "papa|C'est encore avril.",
            "enfant-m|Les tulipes.",
            "papa|Trop tôt pour le pique-nique.",
            "papa|La nappe grelotterait.",
            "narrateur|Amir tourne encore.",
            "narrateur|Une abeille est dessinée dans un coin.",
            "papa|Mai.",
            "enfant-m|Les fleurs.",
            "papa|Presque.",
            "papa|Les fraises ne sont pas là.",
            "narrateur|En ce moment, Amir tire la page suivante.",
            "narrateur|Elle colle un peu à mai.",
            "enfant-m|Elle ne veut pas.",
            "papa|Un peu de patience.",
            "narrateur|Amir souffle sur le bord.",
            "narrateur|Il décolle le papier, tout fin.",
            "papa|Voilà.",
            "papa|Juin.",
            "enfant-m|Juin !",
            "papa|Les fraises.",
            "papa|Et notre pique-nique.",
            "narrateur|Une nappe à carreaux est dessinée, minuscule.",
            "enfant-m|Je mets une étoile ?",
            "papa|Oui.",
            "papa|Sur juin.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir a un mois sur le calendrier.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Papa tend le crayon gras.",
            "narrateur|La mine est un peu molle.",
            "enfant-m|Une étoile.",
            "narrateur|Amir dessine cinq branches, inégales.",
            "narrateur|Une branche dépasse sur le dimanche.",
            "papa|C'est joli.",
            "papa|C'est le mois du pique-nique.",
            "enfant-m|Parce que c'est juin.",
            "papa|Oui.",
            "papa|Un mois pour une fête.",
            "narrateur|Le crayon laisse une poussière bleue.",
            "narrateur|Amir souffle.",
            "papa|Tu as trouvé la page.",
            "papa|Merci, Amir.",
            "enfant-m|Elle collait.",
            "papa|Tu l'as décollée.",
            "narrateur|Avril et mai restent derrière.",
            "narrateur|Juin regarde la cuisine.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa range le crayon dans le tiroir.",
            "narrateur|Le tiroir sent le bois.",
            "enfant-m|On prend la nappe ?",
            "papa|Pas encore.",
            "papa|Le jour n'est pas venu.",
            "narrateur|Amir touche l'étoile du doigt.",
            "narrateur|Le papier est un peu rêche.",
            "papa|Tu veux un verre d'eau ?",
            "enfant-m|Oui.",
            "narrateur|L'eau claque dans le verre.",
            "narrateur|Une goutte reste sur la table.",
            "papa|Juin arrivera.",
            "enfant-m|Avec les fraises.",
            "papa|Avec la nappe.",
            "narrateur|Une mouche se pose sur le mot mai, derrière.",
            "enfant-m|Pas celle-là.",
            "papa|Mai reste caché.",
            "narrateur|Le soleil avance sur le calendrier.",
            "narrateur|Il touche juste le mot juin.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Amir recule d'un pas.",
            "narrateur|L'étoile se voit de la table.",
            "enfant-m|Elle brille un peu.",
            "papa|Comme le pique-nique.",
            "narrateur|La page recourbée s'est calmée.",
            "narrateur|Elle tient maintenant, à plat.",
            "enfant-m|On ne la perd plus.",
            "papa|Non.",
            "narrateur|Le café froid n'a plus d'odeur.",
            "narrateur|Le mot juin reste au mur, tout net.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "juin",
        "accepted_examples": "juin | un mois | pique-nique | fête | anniversaire",
        "retry_prompt": "C'est le mois du pique-nique. Quel mois cherchent-ils ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-02",
    "La page de juin",
    "Amir et papa cherchent juin sur le calendrier mural pour le pique-nique. Avril, mai, puis juin. Page collée.",
    "Pas de liste des douze mois. Deux ou trois nommés en tournant. Imprévu : page collée. D16 Amir, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-03 N2 Nina, papa, maman — mars, narcisse, bougie
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-03",
    "C'est l'anniversaire de Nina, en mars, quand le premier narcisse ouvre. La tige est trop courte pour le vase. Ils la mettent dans un gobelet. Nina souffle la bougie.",
    "Le premier narcisse",
    "Nina, papa, maman",
    "jardin encore froid, puis table près de la fenêtre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Dans l'herbe encore froide, un narcisse ouvre son jaune.",
            "narrateur|La corolle sent le miel pâle.",
            "narrateur|Un peu de terre reste au pied.",
            "enfant-f|Il est venu !",
            "papa|Le premier.",
            "maman|C'est mars, Nina.",
            "maman|Ton mois.",
            "enfant-f|Mon anniversaire.",
            "papa|Oui.",
            "narrateur|Le vent de mars pince les oreilles.",
            "narrateur|Nina se baisse.",
            "narrateur|Ses genoux touchent l'herbe humide.",
            "maman|On le coupe ?",
            "enfant-f|Pour la table.",
            "papa|Tout près de la terre.",
            "narrateur|Papa tend les ciseaux ronds.",
            "narrateur|Nina tient la tige.",
            "narrateur|Clic.",
            "enfant-f|Il est à nous.",
            "maman|Il viendra près du gâteau.",
            "narrateur|Ils rentrent.",
            "narrateur|La cuisine sent la pâte et le beurre.",
            "narrateur|Un gâteau rond attend, sans bougie.",
            "enfant-f|La fleur d'abord.",
            "narrateur|Maman sort le grand vase bleu.",
            "narrateur|Nina glisse le narcisse.",
            "narrateur|La tige est trop courte.",
            "narrateur|La tête bascule, elle disparaît.",
            "enfant-f|On ne le voit plus !",
            "papa|Trop grand, ce vase.",
            "maman|On cherche un gobelet ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, Nina ouvre le placard.",
            "narrateur|Un gobelet blanc s'y cache.",
            "enfant-f|Il est petit.",
            "maman|Comme la tige.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina a un gâteau en mars.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina pose le gobelet près du gâteau.",
            "narrateur|Elle y glisse le narcisse.",
            "narrateur|La tête jaune se tient, droite.",
            "enfant-f|Je le vois.",
            "maman|Il est à sa taille.",
            "papa|Comme toi.",
            "narrateur|Papa plante une bougie au milieu.",
            "narrateur|La cire est blanche, un peu molle.",
            "maman|C'est ton anniversaire.",
            "maman|En mars.",
            "enfant-f|Avec le premier narcisse.",
            "papa|Tu souffles ?",
            "narrateur|La flamme penche.",
            "narrateur|Nina souffle, tout doux.",
            "narrateur|La fumée fait un fil gris.",
            "papa|Merci, Nina.",
            "papa|Tu as trouvé le gobelet.",
            "enfant-f|Le vase était trop grand.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman coupe une part.",
            "narrateur|La miette tombe près du gobelet.",
            "enfant-f|Pour le narcisse.",
            "maman|Les fleurs ne mangent pas le gâteau.",
            "papa|Elles boivent l'eau.",
            "narrateur|Nina goûte.",
            "narrateur|Le gâteau est tiède, un peu citron.",
            "enfant-f|Ça pique.",
            "maman|C'est le citron de mars.",
            "narrateur|Le narcisse penche vers la part.",
            "narrateur|Comme s'il écoutait.",
            "papa|On le remettra au jardin demain ?",
            "enfant-f|Non.",
            "enfant-f|Il reste la nuit.",
            "maman|D'accord.",
            "narrateur|Une goutte d'eau glisse sur le gobelet.",
            "narrateur|Une miette sucrée reste au coin de la bouche.",
            "papa|Tu l'as ?",
            "enfant-f|Oui.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La bougie a un petit cratère de cire.",
            "narrateur|Nina y pose le doigt, plus froid maintenant.",
            "enfant-f|Elle a fini.",
            "papa|Toi, tu commences ton année.",
            "maman|En mars.",
            "narrateur|Le narcisse garde son jaune près de la vitre.",
            "narrateur|Dehors, l'herbe attend le deuxième.",
            "enfant-f|Il viendra.",
            "maman|Oui.",
            "narrateur|La table sent le citron et le miel pâle.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "anniversaire",
        "accepted_examples": "anniversaire | son anniversaire | mars | le mois | narcisse",
        "retry_prompt": "C'est son anniversaire. Pourquoi le gâteau ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-03",
    "Le premier narcisse",
    "Anniversaire de Nina en mars : premier narcisse, tige trop courte, gobelet, bougie.",
    "Mars dit parce que le narcisse ouvre, pas une liste. Imprévu : vase trop grand. D16 Nina, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-04 N3 Raphaël, maman, papa — octobre, châtaignes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-04",
    "C'est l'anniversaire de Raphaël, en octobre, quand les châtaignes tombent. Le vent pousse les feuilles. Une châtaigne est trop fermée. Ils en trouvent une ouverte, la font chauffer. Le gâteau attend.",
    "La châtaigne trop fermée",
    "Raphaël, maman, papa",
    "allée sous le châtaignier, puis cuisine venteuse",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le vent pousse les feuilles jusqu'au perron.",
            "narrateur|Elles tapent le bois, sèches, brunes.",
            "narrateur|Le châtaignier grince un peu.",
            "enfant-m|C'est mon jour.",
            "maman|C'est octobre, Raphaël.",
            "maman|Ton anniversaire.",
            "papa|Les châtaignes tombent.",
            "papa|On en cherche pour le goûter.",
            "narrateur|Raphaël enfile ses gants rêches.",
            "narrateur|Le cuir sent le grenier.",
            "enfant-m|Ils sont trop grands.",
            "papa|Tu les gardes quand même.",
            "narrateur|Une feuille se colle à sa manche.",
            "enfant-m|Elle me suit.",
            "maman|Le vent la promène.",
            "narrateur|Sous l'arbre, une bogue pique encore.",
            "narrateur|Raphaël la retourne du bout du pied.",
            "enfant-m|Elle est fermée.",
            "papa|Trop fermée.",
            "papa|La châtaigne n'est pas sortie.",
            "narrateur|Il cherche plus loin.",
            "narrateur|Le vent lui jette trois feuilles au visage.",
            "enfant-m|Pff.",
            "maman|Tu vois une ouverte ?",
            "narrateur|En ce moment, une bogue fendue brille dans l'herbe.",
            "narrateur|Deux châtaignes lisses y dorment.",
            "enfant-m|Celles-là.",
            "maman|Elles sont prêtes.",
            "narrateur|Papa les sort, tout doux.",
            "narrateur|Elles sont froides, luisantes.",
            "enfant-m|Pour le gâteau ?",
            "papa|À côté.",
            "papa|On les chauffe.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël a un gâteau en octobre.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La cuisine sent déjà la pâte aux noisettes.",
            "narrateur|Le gâteau d'octobre attend sur la grille.",
            "maman|C'est ton anniversaire.",
            "enfant-m|En octobre.",
            "papa|Oui.",
            "narrateur|Papa pose les châtaignes dans la poêle.",
            "narrateur|Il les fend d'un cran, tout petit.",
            "enfant-m|Pour qu'elles n'explosent pas.",
            "papa|Oui.",
            "narrateur|Ça crépite.",
            "narrateur|Une peau se fend, chaude.",
            "maman|Tu souffles un peu.",
            "narrateur|Raphaël souffle.",
            "narrateur|La vapeur lui chatouille le nez.",
            "enfant-m|Ça sent le bois.",
            "maman|C'est octobre.",
            "papa|Merci, Raphaël.",
            "papa|Tu as trouvé les ouvertes.",
            "enfant-m|Pas la fermée.",
            "maman|La fermée restera sous l'arbre.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman pose une châtaigne chaude près du gâteau.",
            "narrateur|L'autre reste dans la petite coupelle.",
            "enfant-m|Je pèle.",
            "narrateur|La peau craque.",
            "narrateur|Le dedans est jaune, tout doux.",
            "papa|Tu goûtes ?",
            "enfant-m|Elle brûle un peu.",
            "maman|On attend.",
            "narrateur|Le vent frappe encore la vitre.",
            "narrateur|Une feuille reste collée, comme une étoile.",
            "enfant-m|Elle veut entrer.",
            "papa|Elle reste dehors.",
            "narrateur|Raphaël souffle encore sur la châtaigne.",
            "narrateur|Il la mange, enfin.",
            "maman|Et le gâteau ?",
            "enfant-m|Après.",
            "papa|C'est ton jour.",
            "narrateur|Une miette de peau tombe sur la table.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La poêle se tait.",
            "narrateur|Il reste une odeur de bois chaud.",
            "enfant-m|Octobre est bon.",
            "maman|C'est ton mois.",
            "papa|Celui de ton anniversaire.",
            "narrateur|Raphaël pose le gant près de la porte.",
            "narrateur|Une feuille sèche y reste coincée.",
            "enfant-m|Elle m'a suivi.",
            "maman|Tu peux la garder.",
            "narrateur|Le gâteau attend encore une part.",
            "narrateur|Dehors, la bogue fermée dort sous le vent.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "anniversaire",
        "accepted_examples": "anniversaire | son anniversaire | octobre | le mois | châtaignes",
        "retry_prompt": "C'est son anniversaire. Pourquoi le gâteau ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-04",
    "La châtaigne trop fermée",
    "Anniversaire de Raphaël en octobre : vent, châtaignes, une trop fermée, les ouvertes dans la poêle, gâteau.",
    "Octobre dit par les châtaignes, pas une liste. Imprévu : bogue fermée. D16 Raphaël, papa, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-TMP.MOI.001-05 N3 Victorina, papa, maman — mai, cerisier, pétale
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MOI.001-05",
    "C'est l'anniversaire de Victorina, en mai, sous le cerisier en fleur. Un pétale tombe dans son verre. Elle le sort avec la cuillère. Le gâteau sent l'amande. La nappe est rose de pétales.",
    "Le pétale dans le verre",
    "Victorina, papa, maman",
    "table sous le cerisier en fleur, jardin de mai",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un pétale rose tourne au-dessus de la nappe.",
            "narrateur|Le cerisier a mis sa robe claire.",
            "narrateur|Il n'y a pas encore de cerises, seulement des fleurs.",
            "enfant-f|C'est trop tôt pour les manger.",
            "papa|C'est mai, Victorina.",
            "papa|Le mois des fleurs.",
            "maman|Et le tien.",
            "maman|Ton anniversaire.",
            "narrateur|La nappe blanche déjà attrape trois pétales.",
            "narrateur|Un verre d'eau attend près de l'assiette.",
            "enfant-f|Je bois.",
            "narrateur|Elle lève le verre.",
            "narrateur|Un pétale y flotte, tout plat.",
            "enfant-f|Il est tombé dedans !",
            "maman|Un invité.",
            "papa|Tu le sors ?",
            "narrateur|En ce moment, Victorina prend la petite cuillère.",
            "narrateur|Elle pêche le pétale.",
            "narrateur|L'eau tremble.",
            "enfant-f|Je l'ai.",
            "maman|Tu le poses où ?",
            "enfant-f|Sur la nappe.",
            "narrateur|Le pétale s'ouvre encore, mouillé.",
            "narrateur|Il fait une tache plus foncée.",
            "papa|Le gâteau arrive.",
            "narrateur|Maman pose le plat.",
            "narrateur|Ça sent l'amande tiède.",
            "enfant-f|Il a des fleurs aussi.",
            "maman|Des pétales de sucre.",
            "papa|Pas ceux de l'arbre.",
            "narrateur|Une abeille passe très haut, dans le blanc.",
            "enfant-f|Elle ne descend pas.",
            "maman|Les fleurs lui suffisent.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorina a un gâteau en mai.",
            "narrateur|Pourquoi ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Papa plante une bougie rose.",
            "narrateur|La cire sent le miel.",
            "maman|C'est ton anniversaire.",
            "enfant-f|En mai.",
            "papa|Oui.",
            "papa|Sous le cerisier.",
            "narrateur|Victorina souffle.",
            "narrateur|Un pétale part avec le souffle.",
            "narrateur|Il atterrit sur le gâteau, tout vrai.",
            "enfant-f|Encore un !",
            "maman|On le retire.",
            "narrateur|Maman le lève du bout de la fourchette.",
            "enfant-f|Les vrais restent à l'arbre.",
            "papa|Les sucrés restent au gâteau.",
            "narrateur|Victorina rit, tout bas.",
            "maman|Merci, Victorina.",
            "maman|Tu as pêché le premier.",
            "enfant-f|Avec la cuillère.",
            "narrateur|Elle boit enfin.",
            "narrateur|L'eau a un goût de fleur, à peine.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman coupe une part.",
            "narrateur|L'amande craque un peu sous la dent.",
            "enfant-f|C'est bon.",
            "papa|Mai est doux.",
            "narrateur|Un autre pétale se pose sur l'épaule de papa.",
            "enfant-f|Toi aussi.",
            "papa|Je suis invité.",
            "narrateur|La nappe devient un petit jardin.",
            "narrateur|Cinq pétales, six.",
            "maman|On ne les compte pas tous.",
            "enfant-f|On les laisse.",
            "maman|Oui.",
            "narrateur|Victorina pose sa part.",
            "narrateur|Elle regarde trop haut, dans les fleurs.",
            "papa|Les cerises viendront plus tard.",
            "enfant-f|Pas en mai.",
            "maman|En mai, les fleurs.",
            "maman|Et toi.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le verre est vide, sans pétale.",
            "narrateur|La cuillère brille à côté.",
            "enfant-f|Mon mois est rose.",
            "papa|Mai.",
            "maman|Celui de ton anniversaire.",
            "narrateur|Un dernier pétale se pose sur le plat vide.",
            "narrateur|Victorina le laisse.",
            "enfant-f|Il a fini le gâteau avec nous.",
            "papa|Oui.",
            "narrateur|Le cerisier respire au-dessus de la nappe.",
            "narrateur|La table sent l'amande et la fleur froide.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "anniversaire",
        "accepted_examples": "anniversaire | son anniversaire | mai | le mois | cerisier | pétale",
        "retry_prompt": "C'est son anniversaire. Pourquoi le gâteau ?",
    },
)
relecture(
    "ATOM-TMP.MOI.001-05",
    "Le pétale dans le verre",
    "Anniversaire de Victorina en mai sous le cerisier. Un pétale dans le verre, pêche à la cuillère, gâteau à l'amande.",
    "Mai dit par la floraison, pas une liste. Imprévu : pétale dans le verre. D16 Victorina, papa, maman.",
)
