#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-SEC.RUE.002-08/09 et ATOM-SEC.RUE.003-01..06."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.002-08  N1  Victorino, papa — ruelle, linge, feu vert
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.002-08",
    "Victorino veut le pain chaud au bout de la ruelle. Un drap claque. Au bord, il attend le feu vert, la main dans la main. Puis le pain tiède.",
    "Le drap de la ruelle",
    "Victorino, papa",
    "ruelle de village, linge aux fenêtres, après le soleil du matin",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un drap blanc claque au-dessus de la ruelle.",
            "narrateur|Le savon des draps sent encore le soleil.",
            "narrateur|Une pince de bois pend trop bas.",
            "narrateur|La pierre de la ruelle est chaude.",
            "narrateur|Un géranium rouge dépasse d'une fenêtre.",
            "narrateur|Ça sent le pain, tout au bout.",
            "narrateur|Victorino vit ici, avec papa.",
            "enfant-m|Papa, le drap danse !",
            "papa|Oui.",
            "papa|Il sèche au vent.",
            "papa|Tu as vu la pince ?",
            "enfant-m|Elle brille.",
            "narrateur|En ce moment, Victorino tend la main.",
            "narrateur|La main de papa est chaude.",
            "narrateur|Ils marchent sur le trottoir.",
            "narrateur|Le drap claque encore une fois.",
            "narrateur|Une goutte tombe sur le nez.",
            "enfant-m|Oh, c'est froid !",
            "papa|Le drap est encore mouillé.",
            "enfant-m|Je veux le pain chaud !",
            "papa|Bientôt.",
            "papa|On reste sur le trottoir.",
            "narrateur|Le beurre sent plus fort.",
            "narrateur|Un chat miaule derrière un drap.",
            "enfant-m|Le chat !",
            "papa|On le verra après.",
            "narrateur|Le bord du trottoir arrive.",
            "narrateur|Une petite lumière rouge attend.",
            "papa|On s'arrête.",
            "papa|On attend le feu vert.",
            "papa|Tu donnes la main ?",
            "narrateur|Victorino serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "enfant-m|J'attends.",
            "papa|Bravo.",
            "narrateur|Le drap claque comme une voile.",
            "narrateur|La pince tape contre le mur.",
            "enfant-m|Elle fait tic !",
            "papa|Oui.",
            "papa|On attend encore ?",
            "enfant-m|Oui, papa.",
            "narrateur|La lumière reste rouge un peu.",
            "narrateur|Victorino sent le four tout près.",
            "papa|Tu tiens bien ma main ?",
            "enfant-m|Oui.",
            "narrateur|Puis la lumière devient verte.",
            "papa|Feu vert.",
            "papa|On avance avec papa.",
            "narrateur|Ils avancent ensemble, tout doux.",
            "narrateur|Victorino garde la main.",
            "narrateur|Le pain est tout près maintenant.",
            "enfant-m|Ça sent trop bon !",
            "papa|Merci d'avoir attendu.",
            "narrateur|Le drap blanc tremble encore.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorino est avec papa.",
            "narrateur|Que fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorino a donné la main.",
            "narrateur|Il a attendu le feu vert.",
            "narrateur|Ses pieds sont restés au bord.",
            "papa|Tu as attendu le feu vert ?",
            "enfant-m|Oui.",
            "enfant-m|J'ai donné la main.",
            "papa|Bravo, Victorino.",
            "papa|On avance avec papa.",
            "narrateur|La main de papa reste chaude.",
            "narrateur|Le drap claque loin derrière.",
            "narrateur|Le pain sent encore plus fort.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La clochette de la boulangerie fait ding.",
            "papa|Tu prends le pain ?",
            "narrateur|Victorino tient le pain tiède.",
            "enfant-m|Il est chaud !",
            "papa|Oui.",
            "papa|Tu as bien attendu.",
            "narrateur|Le papier du pain est un peu rêche.",
            "narrateur|Ça sent le beurre et la farine.",
            "enfant-m|On revoit le chat ?",
            "papa|On rentre par la ruelle.",
            "narrateur|Ils tiennent encore la main.",
            "narrateur|Le drap blanc sèche au soleil.",
            "narrateur|Le chat se lèche sur le rebord.",
            "enfant-m|Il est là !",
            "papa|Oui.",
            "papa|Et toi, tu as gardé la main.",
            "narrateur|Victorino serre le pain contre lui.",
            "narrateur|La pierre de la ruelle est chaude.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le pain sent le four.",
            "papa|Oui.",
            "papa|Merci d'être resté près.",
            "narrateur|Le chat cligne des yeux.",
            "narrateur|Une pince brille encore.",
            "narrateur|Le drap blanc sent encore le savon chaud.",
        ],
    },
    {"CHK_T0000_P0000": "oiseau"},
    {
        "expected_answer": "attendre le feu vert",
        "accepted_examples": "attendre | feu vert | la main | avec papa | il attend | donner la main",
        "retry_prompt": "Il attend le feu vert. Que fait Victorino ?",
    },
)
relecture(
    "ATOM-SEC.RUE.002-08",
    "Le drap de la ruelle",
    "Victorino veut le pain chaud au bout de la ruelle. Un drap claque, une goutte tombe. Au bord, il attend le feu vert, main dans la main. Le pain tiède, le chat, le savon des draps.",
    "- Désir : le pain, pas le feu. Ouverture : drap, savon, pince. POS-001 : attendre, main, trottoir.\n"
    "- Troupe D16 : Victorino, papa. Fin : pain, chat, drap.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.002-09  N1  Victorina, maman — marché, cagettes, feu vert
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.002-09",
    "Victorina veut une fraise dans la cagette rouge. Une pêche roule. Au bord, elle attend le feu vert, la main dans la main. Puis le jus sucré.",
    "La cagette rouge",
    "Victorina, maman",
    "trottoir vers le marché, cagettes au soleil",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le bois des cagettes craque sous le soleil.",
            "narrateur|Les fraises brillent, toutes rouges.",
            "narrateur|Ça sent le sucré et le bois chaud.",
            "narrateur|Une pêche ronde dort tout au bord.",
            "narrateur|Le marché chante un peu plus loin.",
            "narrateur|Victorina vit ici, avec maman.",
            "enfant-f|Maman, les fraises brillent !",
            "maman|Oui.",
            "maman|Elles sentent le soleil.",
            "maman|Tu as vu la cagette rouge ?",
            "enfant-f|Elle est trop belle.",
            "narrateur|En ce moment, Victorina tend la main.",
            "narrateur|La main de maman est douce.",
            "narrateur|Elles marchent sur le trottoir.",
            "narrateur|Le bois des cagettes craque encore.",
            "enfant-f|Je veux une fraise !",
            "maman|Bientôt.",
            "maman|On reste sur le trottoir.",
            "narrateur|Une pêche roule tout doux.",
            "narrateur|Elle s'arrête près d'une caisse.",
            "enfant-f|La pêche !",
            "maman|On la verra après.",
            "narrateur|Le bord du trottoir arrive.",
            "narrateur|Une petite lumière rouge attend.",
            "maman|On s'arrête.",
            "maman|On attend le feu vert.",
            "maman|Tu donnes la main ?",
            "narrateur|Victorina serre la main.",
            "narrateur|Ses pieds restent sur le trottoir.",
            "enfant-f|J'attends.",
            "maman|Bravo.",
            "narrateur|Une abeille tourne au-dessus des fruits.",
            "narrateur|Les fraises sentent plus fort.",
            "enfant-f|Elle bourdonne !",
            "maman|Oui.",
            "maman|On attend encore ?",
            "enfant-f|Oui, maman.",
            "narrateur|La lumière reste rouge un peu.",
            "narrateur|Victorina sent le sucré tout près.",
            "maman|Tu tiens bien ma main ?",
            "enfant-f|Oui.",
            "narrateur|Puis la lumière devient verte.",
            "maman|Feu vert.",
            "maman|On avance avec maman.",
            "narrateur|Elles avancent ensemble, tout doux.",
            "narrateur|Victorina garde la main.",
            "narrateur|La cagette rouge est tout près.",
            "enfant-f|Ça sent trop bon !",
            "maman|Merci d'avoir attendu.",
            "narrateur|Le bois chaud craque encore.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorina est avec maman.",
            "narrateur|Que fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorina a donné la main.",
            "narrateur|Elle a attendu le feu vert.",
            "narrateur|Ses pieds sont restés au bord.",
            "maman|Tu as attendu le feu vert ?",
            "enfant-f|Oui.",
            "enfant-f|J'ai donné la main.",
            "maman|Bravo, Victorina.",
            "maman|On avance avec maman.",
            "narrateur|La main de maman reste douce.",
            "narrateur|Les fraises brillent plus fort.",
            "narrateur|La pêche dort encore près de la caisse.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman parle à l'étal.",
            "maman|Tu prends une fraise ?",
            "narrateur|Victorina tient une fraise tiède.",
            "enfant-f|Elle est sucrée !",
            "maman|Oui.",
            "maman|Tu as bien attendu.",
            "narrateur|Le jus brille un peu au coin des lèvres.",
            "narrateur|Le bois de la cagette est rêche.",
            "enfant-f|Et la pêche ?",
            "maman|Elle reste à l'étal.",
            "narrateur|Elles tiennent encore la main.",
            "narrateur|Le marché sent le sucré et le thym.",
            "narrateur|Une cagette vide sonne tout creux.",
            "enfant-f|Elle fait toc !",
            "maman|Oui.",
            "maman|Et toi, tu as gardé la main.",
            "narrateur|Victorina lèche un doigt rouge.",
            "narrateur|Le soleil chauffe encore le bois.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|La fraise sent le soleil.",
            "maman|Oui.",
            "maman|Merci d'être restée près.",
            "narrateur|Une abeille s'éloigne.",
            "narrateur|La cagette rouge reste pleine.",
            "narrateur|Le jus de fraise brille sur ses doigts.",
        ],
    },
    {"CHK_T0000_P0000": "marche"},
    {
        "expected_answer": "attendre le feu vert",
        "accepted_examples": "attendre | feu vert | la main | avec maman | elle attend | donner la main",
        "retry_prompt": "Elle attend le feu vert. Que fait Victorina ?",
    },
)
relecture(
    "ATOM-SEC.RUE.002-09",
    "La cagette rouge",
    "Victorina veut une fraise. Une pêche roule. Au bord, elle attend le feu vert, main dans la main. Puis le jus sucré sur les doigts.",
    "- Désir : la fraise, pas le feu. Ouverture : bois des cagettes. POS-001 : attendre, main, trottoir.\n"
    "- Troupe D16 : Victorina, maman. Fin : jus, abeille, cagette.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-01  N1  Amir, papa — librairie jaune, pigeon
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-01",
    "Amir veut voir le bateau dans la vitrine jaune. Un pigeon bat des ailes. Amir recule contre papa, reste près, main sur le manteau. Puis le bateau brille.",
    "La librairie jaune",
    "Amir, papa",
    "rue du village vers la librairie jaune",
    {
        "CHK_T0000_P0000": [
            "narrateur|La façade jaune luit entre deux toits gris.",
            "narrateur|Le soleil pose un carré sur le mur.",
            "narrateur|Ça sent le papier et un peu de poussière.",
            "narrateur|Un bateau peint dort derrière la vitre.",
            "narrateur|La rue du village est calme.",
            "narrateur|Amir vit ici, avec papa.",
            "enfant-m|Papa, la maison est jaune !",
            "papa|Oui.",
            "papa|C'est la librairie.",
            "papa|Tu as vu le bateau ?",
            "enfant-m|Il a une voile blanche.",
            "narrateur|En ce moment, Amir prend le manteau.",
            "narrateur|Le manteau de papa est laineux.",
            "narrateur|Ils marchent tout près l'un de l'autre.",
            "enfant-m|Je veux voir le bateau !",
            "papa|On y va.",
            "papa|Tu restes près de moi.",
            "narrateur|Un pigeon gris picore une miette.",
            "narrateur|Ses plumes brillent un peu.",
            "enfant-m|Le pigeon !",
            "papa|Il cherche du pain.",
            "narrateur|Le pigeon bat des ailes, tout près.",
            "narrateur|Ça fait un bruit de vent.",
            "enfant-m|Oh !",
            "narrateur|Amir recule contre papa.",
            "narrateur|Son dos touche le manteau chaud.",
            "papa|Tu es près de moi.",
            "papa|Tu tiens le manteau ?",
            "enfant-m|Oui.",
            "papa|Bravo.",
            "narrateur|Le pigeon se pose sur un toit.",
            "narrateur|Amir garde le tissu laineux.",
            "papa|On reste près ?",
            "enfant-m|Oui, papa.",
            "narrateur|La façade jaune est plus proche.",
            "narrateur|Le bateau grossit dans la vitre.",
            "papa|Tu marches à côté ?",
            "enfant-m|À côté.",
            "narrateur|Leurs pieds vont ensemble.",
            "narrateur|Le papier sent plus fort.",
            "enfant-m|Je vois la voile !",
            "papa|Merci d'être resté près.",
            "narrateur|Amir serre encore le manteau.",
            "narrateur|Le carré de soleil a bougé.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir marche dans la rue.",
            "narrateur|Où est-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir est près de papa.",
            "narrateur|La main tient le manteau.",
            "narrateur|Il a reculé contre papa.",
            "papa|Tu es resté près de moi ?",
            "enfant-m|Oui.",
            "enfant-m|J'ai tenu le manteau.",
            "papa|Bravo, Amir.",
            "papa|Près de moi.",
            "narrateur|Le manteau laineux reste doux.",
            "narrateur|Le pigeon roucoule sur le toit.",
            "narrateur|La vitre jaune est tout près.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils s'arrêtent devant la librairie.",
            "papa|Tu vois le bateau ?",
            "narrateur|Amir pose le nez sur la vitre.",
            "enfant-m|La voile est blanche !",
            "papa|Oui.",
            "papa|Tu es resté près.",
            "narrateur|Le verre est un peu froid.",
            "narrateur|Le bateau a une petite ancre.",
            "enfant-m|Il peut flotter ?",
            "papa|Dans l'histoire, oui.",
            "narrateur|Amir garde le manteau d'une main.",
            "narrateur|De l'autre, il montre le bateau.",
            "narrateur|Le soleil chauffe le mur jaune.",
            "enfant-m|C'est tout chaud !",
            "papa|Oui.",
            "papa|On rentre près l'un de l'autre.",
            "narrateur|Le pigeon a trouvé sa miette.",
            "narrateur|La poussière danse dans le carré jaune.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai vu le bateau.",
            "papa|Oui.",
            "papa|Merci d'être resté près.",
            "narrateur|Le mur jaune reste chaud.",
            "narrateur|Le bateau du livre brille dans le soleil jaune.",
        ],
    },
    {"CHK_T0000_P0000": "oiseau"},
    {
        "expected_answer": "près de papa",
        "accepted_examples": "près | près de papa | à côté | la main | le manteau | contre papa",
        "retry_prompt": "Il reste près de papa. Où est Amir ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-01",
    "La librairie jaune",
    "Amir veut voir le bateau dans la vitrine jaune. Un pigeon bat des ailes. Amir recule contre papa, tient le manteau. Le bateau, le mur chaud.",
    "- Désir : le bateau, pas la leçon. Imprévu : pigeon. POS-001 : recule contre papa, pas dans la rue.\n"
    "- Troupe D16 : Amir, papa. Fin : vitre, voile, soleil jaune.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-02  N2  Sarah, maman — vitrine des chaussons
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-02",
    "Sarah veut voir le chausson bleu derrière la vitre. Son foulard glisse. Elle reste près de maman, main sur le manteau. Puis le chausson tout doux.",
    "Le chausson bleu",
    "Sarah, maman",
    "rue du village, vitrine des chaussons, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un chausson bleu dort derrière la vitre.",
            "narrateur|Le soleil bas pose une bande d'or sur le cuir.",
            "narrateur|La rue sent la laine et un peu de savon.",
            "narrateur|Le foulard de Sarah chatouille son cou.",
            "narrateur|Sarah vit ici, avec maman.",
            "enfant-f|Maman, le chausson est bleu comme la mer !",
            "maman|Oui.",
            "maman|Il a l'air tout doux.",
            "maman|Tu as vu le pompon ?",
            "enfant-f|Il est rond.",
            "narrateur|En ce moment, Sarah prend le manteau de maman.",
            "narrateur|Le tissu est épais, un peu rêche au bord.",
            "enfant-f|Je veux voir le chausson de près.",
            "maman|On y va.",
            "maman|Tu restes près de moi.",
            "narrateur|Elles marchent côte à côte sur le trottoir.",
            "narrateur|Une feuille sèche tourne contre la vitrine.",
            "narrateur|Le foulard de Sarah glisse vers l'épaule.",
            "enfant-f|Mon foulard !",
            "maman|On le rattrape ici.",
            "maman|Près de moi.",
            "narrateur|Sarah s'arrête contre maman.",
            "narrateur|Le foulard pend, tout léger, sur le trottoir.",
            "maman|Tu tiens le manteau ?",
            "enfant-f|Oui.",
            "narrateur|Maman ramasse le foulard près de leurs pieds.",
            "narrateur|La laine sent encore le cou de Sarah.",
            "enfant-f|Il était par terre.",
            "maman|Oui.",
            "maman|Et toi, tu es restée près.",
            "maman|Bravo.",
            "narrateur|Sarah remet le foulard, tout chaud.",
            "narrateur|Elle garde le manteau de l'autre main.",
            "maman|On reste près ?",
            "enfant-f|Près de toi.",
            "narrateur|La vitrine est plus proche maintenant.",
            "narrateur|Le chausson bleu grossit derrière le verre.",
            "maman|Tu marches à côté ?",
            "enfant-f|À côté.",
            "narrateur|Leurs ombres se touchent sur le trottoir.",
            "narrateur|Le cuir du chausson luit un peu.",
            "enfant-f|Je vois le pompon !",
            "maman|Merci d'être restée près.",
            "narrateur|Sarah serre encore le manteau.",
            "narrateur|La bande d'or a glissé sur le bleu.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah marche dans la rue.",
            "narrateur|Où est-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah est près de maman.",
            "narrateur|La main tient le manteau.",
            "narrateur|Le foulard est revenu autour du cou.",
            "maman|Tu es restée près de moi ?",
            "enfant-f|Oui.",
            "enfant-f|J'ai tenu le manteau.",
            "maman|Bravo, Sarah.",
            "maman|Près de moi.",
            "narrateur|Le manteau reste épais sous les doigts.",
            "narrateur|Le foulard sent encore la laine chaude.",
            "narrateur|La vitrine est tout près.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles s'arrêtent devant les chaussons.",
            "maman|Tu vois le bleu ?",
            "narrateur|Sarah pose la joue près de la vitre.",
            "enfant-f|Le pompon a l'air tout mou !",
            "maman|Oui.",
            "maman|Tu es restée près.",
            "narrateur|Le verre est frais contre sa joue.",
            "narrateur|Le chausson a une petite couture blanche.",
            "enfant-f|On peut le toucher ?",
            "maman|Dedans, oui.",
            "narrateur|La clochette de la boutique fait un ding doux.",
            "narrateur|Sarah garde le manteau d'une main.",
            "narrateur|Maman lui tend le chausson bleu.",
            "enfant-f|Il est trop doux !",
            "maman|Oui.",
            "maman|On rentre près l'une de l'autre.",
            "narrateur|Le foulard tient bien, cette fois.",
            "narrateur|Le cuir sent encore le soleil bas.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le chausson sent la laine.",
            "maman|Oui.",
            "maman|Merci d'être restée près.",
            "narrateur|Le pompon reste rond dans sa paume.",
            "narrateur|Le chausson bleu reste doux contre sa joue.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "près de maman",
        "accepted_examples": "près | près de maman | à côté | la main | le manteau | près de moi",
        "retry_prompt": "Elle reste près de maman. Où est Sarah ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-02",
    "Le chausson bleu",
    "Sarah veut voir le chausson bleu. Son foulard glisse sur le trottoir. Elle reste près de maman. Puis le pompon, le cuir, la joue contre la vitre.",
    "- Désir : le chausson, pas la leçon. Imprévu : foulard. POS-001 : ramassé près d'elles, pas dans la rue.\n"
    "- Troupe D16 : Sarah, maman. Fin : pompon, laine.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-03  N3  Chouchou, papa — deux rues, boulangerie puis square
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-03",
    "Chouchou veut un pain au lait, puis la balançoire du square. Deux rues. Un vélo sonne, une feuille vole. Elle reste près de papa. Puis le pain tiède et le bois de la balançoire.",
    "Le pain et le square",
    "Chouchou, papa",
    "rue de la boulangerie puis rue du square, après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La farine poudre le seuil de la boulangerie.",
            "narrateur|Elle fait un nuage blanc, tout léger, dès qu'on ouvre.",
            "narrateur|Ça sent le beurre chaud et un peu de vanille.",
            "narrateur|Chouchou vit ici, avec papa.",
            "enfant-f|Papa, ça sent le pain au lait !",
            "papa|Oui.",
            "papa|Il est encore tiède.",
            "papa|Tu as vu la farine sur le seuil ?",
            "enfant-f|On dirait de la neige.",
            "narrateur|En ce moment, Chouchou prend la main de papa.",
            "narrateur|La main est chaude, un peu farineuse déjà.",
            "enfant-f|Je veux le pain au lait.",
            "papa|On y va.",
            "papa|Tu restes près de moi.",
            "narrateur|Ils marchent sur le trottoir de la première rue.",
            "narrateur|Un vélo passe, tout près.",
            "narrateur|Sa sonnette fait dring.",
            "enfant-f|Il va vite !",
            "papa|Nous, on reste près.",
            "papa|Tu tiens ma main ?",
            "enfant-f|Oui.",
            "narrateur|Chouchou serre plus fort.",
            "narrateur|Leurs épaules se touchent un instant.",
            "papa|Bravo.",
            "narrateur|La clochette de la boulangerie fait ding.",
            "narrateur|Papa glisse le pain au lait dans le sac.",
            "enfant-f|Il est chaud à travers le papier !",
            "papa|Oui.",
            "papa|Maintenant, le square.",
            "papa|Autre rue.",
            "papa|Même chose.",
            "narrateur|La deuxième rue sent l'herbe coupée.",
            "narrateur|Le square montre déjà une balançoire rouge.",
            "enfant-f|La balançoire !",
            "papa|On y va près l'un de l'autre.",
            "narrateur|Une feuille sèche vole très bas.",
            "narrateur|Elle tapote la chaussure de Chouchou.",
            "enfant-f|Elle me chatouille !",
            "papa|Tu restes près de moi ?",
            "enfant-f|Près de toi.",
            "narrateur|Chouchou tient le manteau, puis la main.",
            "narrateur|Le sac de pain tape doucement contre la jambe.",
            "papa|Tu marches à côté ?",
            "enfant-f|À côté.",
            "narrateur|Le bois de la balançoire est plus proche.",
            "narrateur|L'herbe du square brille un peu.",
            "papa|Merci d'être restée près.",
            "papa|Les deux rues.",
            "narrateur|Chouchou garde encore la main.",
            "narrateur|Le pain au lait parfume le sac.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou marche dans la rue.",
            "narrateur|Où reste-t-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou est près de papa.",
            "narrateur|À la boulangerie, puis au square.",
            "narrateur|La main tient le manteau, ou la main.",
            "papa|Tu es restée près, dans les deux rues ?",
            "enfant-f|Oui.",
            "enfant-f|Près de toi.",
            "papa|Bravo, Chouchou.",
            "papa|Près de moi.",
            "narrateur|Le sac sent encore le beurre chaud.",
            "narrateur|La farine du seuil est loin maintenant.",
            "narrateur|La balançoire rouge attend dans l'herbe.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa ouvre le sac près du banc.",
            "papa|Tu manges un bout ?",
            "narrateur|Chouchou mord le pain au lait, tout tiède.",
            "enfant-f|Il est doux !",
            "papa|Oui.",
            "papa|Tu es restée près.",
            "narrateur|Une miette tombe dans l'herbe.",
            "narrateur|Un moineau la regarde, la tête de côté.",
            "enfant-f|Je peux aller à la balançoire ?",
            "papa|On y va ensemble.",
            "narrateur|Chouchou tient encore la main jusqu'au bois.",
            "narrateur|Le siège rouge est un peu rêche, un peu chaud.",
            "enfant-f|Pousse tout doux.",
            "papa|Je te vois.",
            "papa|Tu es restée près, puis ici.",
            "narrateur|Le square sent l'herbe et la vanille.",
            "narrateur|Le pain au lait repose dans le sac ouvert.",
            "narrateur|La sonnette du vélo s'est tue.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le pain sent encore le four.",
            "papa|Oui.",
            "papa|Merci d'être restée près.",
            "narrateur|La balançoire se tait, tout doux.",
            "narrateur|Le pain tiède parfume encore le square.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "près de papa",
        "accepted_examples": "près | près de papa | à côté | la main | le manteau | les deux rues",
        "retry_prompt": "Elle reste près de papa. Où reste Chouchou ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-03",
    "Le pain et le square",
    "Chouchou veut un pain au lait, puis la balançoire. Deux rues. Un vélo sonne, une feuille vole. Elle reste près. Pain tiède, bois rouge.",
    "- Désir : pain puis square. Leçon greffée aux deux rues. POS-001 : près, main, pas de course.\n"
    "- Troupe D16 : Chouchou, papa. Fin : vanille, herbe, balançoire.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-04  N3  Raphaël, papa — deux rues, palissade / chantier
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-04",
    "Raphaël veut voir la pelle jaune derrière la palissade, puis dessiner au kiosque. Un panneau claque. Il reste près de papa, il regarde. Puis le crayon, le pin, la pelle.",
    "La pelle derrière la palissade",
    "Raphaël, papa",
    "rue du chantier puis rue du kiosque, après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une palissade bleue sent encore le pin neuf.",
            "narrateur|Derrière les lattes, une pelle jaune lève un peu de terre.",
            "narrateur|Ça sent le bois, la poussière, un peu d'essence.",
            "narrateur|Raphaël vit ici, avec papa.",
            "enfant-m|Papa, la pelle est trop grande !",
            "papa|Oui.",
            "papa|On la regarde d'ici.",
            "papa|Tu as vu le trou rond ?",
            "enfant-m|Il fume un peu.",
            "narrateur|En ce moment, Raphaël prend le manteau de papa.",
            "narrateur|Le tissu est épais.",
            "narrateur|Une poussière y colle déjà.",
            "enfant-m|Je veux la voir de tout près.",
            "papa|On regarde.",
            "papa|On reste près de moi.",
            "narrateur|Ils marchent sur le trottoir de la première rue.",
            "narrateur|Un panneau de bois claque contre un autre.",
            "enfant-m|Ça a fait peur !",
            "papa|On reste près.",
            "papa|Tu tiens le manteau ?",
            "enfant-m|Oui.",
            "narrateur|Raphaël se serre contre papa.",
            "narrateur|Ils regardent la pelle entre deux lattes.",
            "papa|Bravo.",
            "papa|On regarde.",
            "papa|On reste près.",
            "narrateur|La pelle jaune plonge, puis se relève.",
            "narrateur|Un caillou roule derrière la palissade.",
            "enfant-m|Je veux la dessiner.",
            "papa|Le kiosque a des crayons.",
            "papa|Autre rue.",
            "papa|Même chose.",
            "narrateur|La deuxième rue sent le papier et l'encre.",
            "narrateur|Le kiosque a un auvent rayé, un peu défraîchi.",
            "enfant-m|Les crayons !",
            "papa|On y va près l'un de l'autre.",
            "narrateur|Une feuille de journal s'envole le long du mur.",
            "narrateur|Elle tapote la chaussure de Raphaël.",
            "enfant-m|Elle veut partir !",
            "papa|Toi, tu restes près de moi ?",
            "enfant-m|Près de toi.",
            "narrateur|Raphaël tient le manteau jusqu'au kiosque.",
            "narrateur|Le pin de la palissade reste dans l'air.",
            "papa|Tu marches à côté ?",
            "enfant-m|À côté.",
            "narrateur|L'auvent rayé fait une ombre fraîche.",
            "narrateur|Un crayon jaune attend dans un pot.",
            "papa|Merci d'être resté près.",
            "papa|Les deux rues.",
            "narrateur|Raphaël garde encore le manteau.",
            "narrateur|La poussière du chantier brille au soleil.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël marche dans la rue.",
            "narrateur|Où est-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël est près de papa.",
            "narrateur|Au chantier, puis au kiosque.",
            "narrateur|La main tient le manteau.",
            "papa|Tu es resté près, dans les deux rues ?",
            "enfant-m|Oui.",
            "enfant-m|J'ai regardé près de toi.",
            "papa|Bravo, Raphaël.",
            "papa|Près de moi.",
            "narrateur|Le manteau sent encore le pin neuf.",
            "narrateur|La palissade claque loin derrière.",
            "narrateur|Le crayon jaune attend dans le pot.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa achète le crayon jaune.",
            "papa|Tu veux dessiner la pelle ?",
            "narrateur|Raphaël pose le papier sur le rebord du kiosque.",
            "enfant-m|Elle a une grande bouche !",
            "papa|Oui.",
            "papa|Tu es resté près.",
            "narrateur|Le crayon gratte, un peu gras.",
            "narrateur|Une ligne jaune devient une pelle.",
            "enfant-m|Elle lève la terre.",
            "papa|Comme tout à l'heure.",
            "narrateur|Raphaël tient encore le manteau d'une main.",
            "narrateur|De l'autre, il colorie le trou rond.",
            "enfant-m|Ça sent le pin, encore.",
            "papa|Oui.",
            "papa|On rentre près l'un de l'autre.",
            "narrateur|Le dessin sent le bois du crayon.",
            "narrateur|L'auvent rayé cliquette un peu.",
            "narrateur|La palissade bleue reste au bout de la rue.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai vu la pelle.",
            "papa|Oui.",
            "papa|Merci d'être resté près.",
            "narrateur|Le crayon jaune repose sur le papier.",
            "narrateur|La palissade sent encore le pin, tout calme.",
        ],
    },
    {"CHK_T0000_P0000": "voiture_passe"},
    {
        "expected_answer": "près de papa",
        "accepted_examples": "près | près de papa | à côté | la main | le manteau | regarder près",
        "retry_prompt": "Il reste près de papa. Où est Raphaël ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-04",
    "La pelle derrière la palissade",
    "Raphaël veut voir la pelle jaune, puis la dessiner. Un panneau claque. Il reste près, il regarde entre les lattes. Crayon, pin, pelle.",
    "- Désir : voir et dessiner, pas la leçon. Deux rues. POS-001 : regarder près de papa, pas s'approcher seul.\n"
    "- Troupe D16 : Raphaël, papa. Fin : crayon, pin.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-05  N1  Mila, maman — fontaine du village
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-05",
    "Mila veut poser une feuille jaune dans la fontaine. Une éclaboussure mouille sa chaussure. Elle reste près de maman. Puis la feuille tourne dans l'eau.",
    "La feuille de la fontaine",
    "Mila, maman",
    "place du village, fontaine de pierre, fin de matin",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'eau de la fontaine chante sur la pierre.",
            "narrateur|Une feuille jaune tremble au bord.",
            "narrateur|Ça sent la mousse et le froid.",
            "narrateur|La place du village est calme.",
            "narrateur|Un pigeon boit, tout petit.",
            "narrateur|Mila vit ici, avec maman.",
            "enfant-f|Maman, l'eau chante !",
            "maman|Oui.",
            "maman|Elle est toute claire.",
            "maman|Tu as vu la feuille jaune ?",
            "enfant-f|Elle veut nager.",
            "narrateur|En ce moment, Mila prend la main.",
            "narrateur|La main de maman est tiède.",
            "enfant-f|Je veux la mettre dans l'eau !",
            "maman|On y va.",
            "maman|Tu restes près de moi.",
            "narrateur|Elles marchent sur les dalles.",
            "narrateur|Les dalles sont un peu humides.",
            "narrateur|L'eau saute et retombe.",
            "enfant-f|Elle fait des ronds !",
            "maman|Oui.",
            "narrateur|Une goutte plus grosse éclabousse.",
            "narrateur|La chaussure de Mila devient sombre.",
            "enfant-f|Oh, c'est mouillé !",
            "maman|L'eau a sauté.",
            "maman|Tu restes près de moi ?",
            "enfant-f|Oui.",
            "narrateur|Mila se serre contre maman.",
            "narrateur|Elle garde la main.",
            "maman|Bravo.",
            "narrateur|La feuille jaune attend encore.",
            "narrateur|L'eau chante, plus douce.",
            "maman|On s'approche tout doux ?",
            "enfant-f|Tout doux.",
            "narrateur|Leurs pieds restent près.",
            "narrateur|La pierre de la vasque est froide.",
            "maman|Tu tiens ma main ?",
            "enfant-f|Oui, maman.",
            "narrateur|Mila tend la feuille, tout près.",
            "narrateur|Maman l'aide, juste à côté.",
            "enfant-f|Elle flotte !",
            "maman|Merci d'être restée près.",
            "narrateur|La feuille tourne dans un petit rond.",
            "narrateur|L'eau claire la porte.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila marche près de la fontaine.",
            "narrateur|Où est-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila est près de maman.",
            "narrateur|La main tient la main.",
            "narrateur|Elle s'est serrée contre maman.",
            "maman|Tu es restée près de moi ?",
            "enfant-f|Oui.",
            "enfant-f|J'ai tenu ta main.",
            "maman|Bravo, Mila.",
            "maman|Près de moi.",
            "narrateur|La main de maman reste tiède.",
            "narrateur|La chaussure sèche un peu.",
            "narrateur|La feuille jaune tourne encore.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles regardent l'eau ensemble.",
            "maman|Tu vois ta feuille ?",
            "narrateur|Mila pose le menton sur la pierre.",
            "enfant-f|Elle fait un bateau !",
            "maman|Oui.",
            "maman|Tu es restée près.",
            "narrateur|L'eau est froide sous un doigt.",
            "narrateur|La mousse est toute verte, toute douce.",
            "enfant-f|Ça sent la pierre mouillée.",
            "maman|Oui.",
            "narrateur|Mila garde la main de maman.",
            "narrateur|La feuille passe sous un filet d'eau.",
            "enfant-f|Elle brille !",
            "maman|Oui.",
            "maman|On rentre près l'une de l'autre.",
            "narrateur|Les dalles sèchent au soleil.",
            "narrateur|Le pigeon s'envole vers le toit.",
            "narrateur|La fontaine chante encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Ma feuille nage.",
            "maman|Oui.",
            "maman|Merci d'être restée près.",
            "narrateur|Un rond d'eau s'élargit.",
            "narrateur|La feuille jaune tourne dans l'eau claire.",
        ],
    },
    {"CHK_T0000_P0000": "eau"},
    {
        "expected_answer": "près de maman",
        "accepted_examples": "près | près de maman | à côté | la main | contre maman",
        "retry_prompt": "Elle reste près de maman. Où est Mila ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-05",
    "La feuille de la fontaine",
    "Mila veut poser une feuille jaune dans la fontaine. Une éclaboussure mouille sa chaussure. Elle reste près. La feuille tourne.",
    "- Désir : la feuille-bateau. Imprévu : éclaboussure. POS-001 : près de maman, dalles, main.\n"
    "- Troupe D16 : Mila, maman. Fin : eau claire, mousse.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.RUE.003-06  N1  Nino, maman — sente de montagne, puis rue
# ---------------------------------------------------------------------------
write_story(
    "ATOM-SEC.RUE.003-06",
    "Nino veut une fleur bleue pour la table, puis le pain du village. Un caillou roule sur la sente. Il reste près de maman. La sente rejoint la rue. Puis la fleur et le pain.",
    "La sente et la fleur",
    "Nino, maman",
    "sente de montagne qui rejoint la rue du village",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un caillou chaud roule dans l'herbe sèche.",
            "narrateur|La sente sent le thym et la poussière.",
            "narrateur|Une fleur bleue penche au bord du chemin.",
            "narrateur|Loin, une clochette de chèvre tinte.",
            "narrateur|Le vent porte un peu de résine.",
            "narrateur|Nino vit ici, avec maman.",
            "enfant-m|Maman, la fleur est bleue !",
            "maman|Oui.",
            "maman|Elle sent un peu le miel.",
            "maman|Tu as entendu la clochette ?",
            "enfant-m|La chèvre est là-haut.",
            "narrateur|En ce moment, Nino prend le manteau.",
            "narrateur|Le manteau de maman sent le thym.",
            "enfant-m|Je veux la fleur pour la table !",
            "maman|On y va.",
            "maman|Tu restes près de moi.",
            "narrateur|Ils marchent sur la sente étroite.",
            "narrateur|L'herbe sèche racle les chaussures.",
            "narrateur|Le caillou chaud redescend un peu.",
            "enfant-m|Il roule !",
            "maman|On le laisse.",
            "maman|Toi, tu restes près.",
            "narrateur|Nino se serre contre maman.",
            "narrateur|Il garde le manteau.",
            "maman|Bravo.",
            "narrateur|Maman cueille la fleur, tout près.",
            "narrateur|Nino la voit, sans lâcher le tissu.",
            "enfant-m|Elle est douce.",
            "maman|Oui.",
            "maman|Maintenant, la rue.",
            "narrateur|La sente rejoint les premières maisons.",
            "narrateur|La rue sent déjà le pain.",
            "enfant-m|Le village !",
            "maman|On reste près aussi.",
            "maman|Tu tiens le manteau ?",
            "enfant-m|Oui.",
            "narrateur|Nino marche à côté, sur le trottoir.",
            "narrateur|La fleur bleue tremble dans la main de maman.",
            "maman|Tu marches à côté ?",
            "enfant-m|À côté.",
            "narrateur|Leurs ombres se collent au mur.",
            "narrateur|La clochette tinte plus loin.",
            "enfant-m|Je veux le pain aussi.",
            "maman|Merci d'être resté près.",
            "narrateur|Nino serre encore le manteau.",
            "narrateur|Le thym de la sente reste dans l'air.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino marche sur la sente.",
            "narrateur|Où est-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino est près de maman.",
            "narrateur|La main tient le manteau.",
            "narrateur|Sur la sente, puis dans la rue.",
            "maman|Tu es resté près de moi ?",
            "enfant-m|Oui.",
            "enfant-m|J'ai tenu le manteau.",
            "maman|Bravo, Nino.",
            "maman|Près de moi.",
            "narrateur|Le manteau sent encore le thym.",
            "narrateur|La fleur bleue tremble un peu.",
            "narrateur|Le pain du village sent plus fort.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La boulangerie ouvre sa porte.",
            "maman|Tu prends le pain ?",
            "narrateur|Nino tient le pain, et le manteau.",
            "enfant-m|Il est chaud !",
            "maman|Oui.",
            "maman|Tu es resté près.",
            "narrateur|La fleur bleue voyage à côté.",
            "narrateur|Ça sent le miel et le four.",
            "enfant-m|Pour la table.",
            "maman|Oui.",
            "narrateur|Ils rentrent par la rue, tout près.",
            "narrateur|Puis la sente remonte un peu.",
            "enfant-m|La chèvre tinte encore.",
            "maman|Oui.",
            "maman|On rentre près l'un de l'autre.",
            "narrateur|L'herbe sèche racle encore.",
            "narrateur|Le pain chauffe les mains de Nino.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|La fleur sent le miel.",
            "maman|Oui.",
            "maman|Merci d'être resté près.",
            "narrateur|Le pain repose près de la fleur bleue.",
            "narrateur|La clochette de la chèvre tinte tout loin.",
        ],
    },
    {"CHK_T0000_P0000": "oiseau"},
    {
        "expected_answer": "près de maman",
        "accepted_examples": "près | près de maman | à côté | la main | le manteau | sur la sente",
        "retry_prompt": "Il reste près de maman. Où est Nino ?",
    },
)
relecture(
    "ATOM-SEC.RUE.003-06",
    "La sente et la fleur",
    "Nino veut une fleur bleue, puis le pain. Un caillou roule. Il reste près sur la sente, puis dans la rue. Fleur, pain, clochette.",
    "- Désir : fleur et pain. Imprévu : caillou. POS-001 : près, manteau, sente puis trottoir.\n"
    "- Troupe D16 : Nino, maman. Fin : miel, pain, clochette.",
)
