#!/usr/bin/env python3
"""F-NAR-008 — vraies histoires ATOM-AUT.AFF.001-01..08 (le sac se greffe)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import LIMITS, relecture, words, write_story


def q_sac(name: str, elle: bool = False) -> dict:
    pron = "Elle" if elle else "Il"
    return {
        "expected_answer": "le sac",
        "accepted_examples": "le sac | dans le sac | il met | elle met | mettre",
        "retry_prompt": f"{pron} met les affaires dans le sac. Où les met {name} ?",
    }


def preview(sid: str, age: str, scripts: dict) -> None:
    lim = LIMITS.get(age) or 12
    n = 0
    for cid, lines in scripts.items():
        for raw in lines:
            phrase = raw.split("|", 1)[1]
            w = words(phrase)
            n += w
            if w > lim:
                raise SystemExit(f"LONG {sid} {cid} {w}>{lim}: {phrase}")
    print(f"preview {sid} {n} mots")


# ---------------------------------------------------------------------------
# 01 N1 Amir, papa — village, four, doudou oublié
# ---------------------------------------------------------------------------
S01 = {
    "CHK_T0000_P0000": [
        "narrateur|Le four du village sent déjà le pain.",
        "narrateur|L'odeur glisse sous la porte.",
        "narrateur|Elle est tiède, un peu sucrée.",
        "narrateur|Une miette dore encore sur la table.",
        "narrateur|Papa essuie le bois du plat.",
        "narrateur|Les chaussures sentent le cuir.",
        "narrateur|Un manteau bleu pend au crochet.",
        "narrateur|Le tapis de l'entrée gratte un peu.",
        "narrateur|Un carré de soleil touche le bois.",
        "narrateur|Dehors, un oiseau fait un petit cri.",
        "papa|Amir, tu sens le pain ?",
        "enfant-m|Oui, papa.",
        "enfant-m|Il est chaud.",
        "papa|On va le voir, tout près.",
        "narrateur|En ce moment, Amir touche le sac.",
        "narrateur|Le sac bleu est par terre.",
        "narrateur|La sangle est lisse, un peu froide.",
        "enfant-m|Il est bleu, papa.",
        "papa|Oui, c'est le tien.",
        "papa|Prends de l'eau, pour le chemin.",
        "narrateur|Amir prend la gourde bleue.",
        "narrateur|Le bouchon est froid sous le doigt.",
        "narrateur|Il fait clic, tout petit.",
        "narrateur|Amir pose la gourde dans le sac.",
        "enfant-m|Elle est un peu froide.",
        "papa|Elle se réchauffera dehors.",
        "papa|Ton doudou voudra le four aussi.",
        "enfant-m|Où est mon doudou ?",
        "narrateur|Le sac a un creux tout vide.",
        "narrateur|Le doudou n'est pas là.",
        "papa|Il attend sur le lit ?",
        "enfant-m|Je vais le chercher.",
        "narrateur|Amir part vers la chambre.",
        "narrateur|Le couloir sent encore le pain.",
        "narrateur|Le plancher est un peu froid.",
        "narrateur|Sur le lit, le doudou attend.",
        "narrateur|Il sent encore l'oreiller.",
        "enfant-m|Te voilà.",
        "narrateur|Amir le serre contre sa joue.",
        "narrateur|Le tissu est chaud, tout doux.",
        "papa|Tu l'as trouvé ?",
        "enfant-m|Oui.",
        "enfant-m|Il vient avec nous.",
        "papa|Glisse-le dans le sac.",
        "narrateur|Amir revient vers l'entrée.",
        "narrateur|La sangle reste coincée sous la chaise.",
        "enfant-m|Ça ne veut pas, papa.",
        "papa|Tire tout doucement.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Amir prépare le sac.",
        "narrateur|Où met-il les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Amir tire la sangle, tout doux.",
        "narrateur|La chaise bouge un tout petit peu.",
        "narrateur|La sangle se libère, lisse encore.",
        "enfant-m|Elle est libre.",
        "papa|Merci, Amir.",
        "narrateur|Il glisse le doudou dans le sac.",
        "narrateur|Le creux n'est plus vide.",
        "papa|Prends aussi le petit livre.",
        "narrateur|Le livre est sur le banc.",
        "narrateur|La couverture est lisse, un peu froide.",
        "narrateur|Amir le pose près de l'eau.",
        "enfant-m|Il est dedans.",
        "papa|Tu fermes, maintenant ?",
        "narrateur|Amir appuie sur la fermeture.",
        "narrateur|Ça fait zzz, tout bas.",
        "narrateur|Le sac bleu est fermé.",
        "papa|Le sac est prêt ?",
        "enfant-m|Oui, papa.",
        "narrateur|Amir pose la main sur le tissu.",
        "narrateur|Le tissu est un peu rêche.",
        "narrateur|Le creux tout doux est plein.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On met tes chaussures ?",
        "narrateur|Amir enfile ses chaussures.",
        "narrateur|Une semelle est encore froide.",
        "papa|Tu as fini tes chaussures ?",
        "enfant-m|Oui, papa.",
        "papa|On ouvre la porte.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|L'air sent le pain du village.",
        "narrateur|Le sac bleu tape doucement.",
        "enfant-m|On va voir le pain ?",
        "papa|Oui, il est tout près.",
        "narrateur|Ils marchent sur le chemin.",
        "narrateur|Une miette de soleil reste au sol.",
        "narrateur|Le village sent le four, de plus en plus.",
        "enfant-m|Je le vois, papa ?",
        "papa|Bientôt.",
        "papa|On continue.",
        "narrateur|Une poule traverse tout loin.",
        "narrateur|Le chemin est un peu poudreux.",
        "narrateur|Amir sent le pain sur sa langue.",
        "enfant-m|Ça sent bon.",
        "papa|Oui, très bon.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Ils s'arrêtent devant le four tiède.",
        "narrateur|La chaleur touche les joues d'Amir.",
        "enfant-m|Le pain est là.",
        "papa|Oui, tout chaud.",
        "narrateur|Le sac repose contre sa hanche.",
        "narrateur|Le doudou sent le four, lui aussi.",
        "papa|Tu as bien préparé le chemin.",
        "enfant-m|On le sent, papa.",
        "narrateur|Le four tiède réchauffe encore ses joues.",
    ],
}
preview("ATOM-AUT.AFF.001-01", "N1", S01)
write_story(
    "ATOM-AUT.AFF.001-01",
    "Amir veut sentir le pain du village. Le doudou est sur le lit, la sangle coincée. Il les range dans le sac bleu. Le four lui chauffe les joues.",
    "Le four du village",
    "Amir, papa",
    "maison du village puis chemin du four",
    S01,
    {},
    q_sac("Amir"),
)
relecture(
    "ATOM-AUT.AFF.001-01",
    "Le four du village",
    "Amir veut le pain chaud. Doudou oublié, sangle coincée. Il agit, le sac ferme, le four est tiède.",
    "Plus de liste gourde-doudou-livre. Fin sensorielle, pas mécanique.",
)


# ---------------------------------------------------------------------------
# 02 N1 Sarah, maman — immeuble, cour, amie, sangle coincée
# ---------------------------------------------------------------------------
S02 = {
    "CHK_T0000_P0000": [
        "narrateur|Dans la cour, un linge blanc sèche.",
        "narrateur|Il claque un peu contre le fil.",
        "narrateur|Les marches de l'immeuble sentent le savon.",
        "narrateur|Une plante verte pousse dans un pot.",
        "narrateur|Le pot est fêlé, tout doux au bord.",
        "narrateur|Un chat gris passe dans l'ombre.",
        "narrateur|La cage d'escalier est un peu fraîche.",
        "narrateur|Au troisième, la porte de Sarah est ouverte.",
        "narrateur|La cuisine sent l'orange pressée.",
        "maman|Sarah, tu as vu le linge ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Il danse.",
        "maman|Chouchou t'attend en bas.",
        "enfant-f|Je veux la voir.",
        "maman|On descend, avec le sac.",
        "narrateur|En ce moment, Sarah prend le sac vert.",
        "narrateur|Le tissu est un peu rêche.",
        "enfant-f|Il est vert, maman.",
        "maman|Oui, c'est le tien.",
        "maman|Mets de l'eau, pour la cour.",
        "narrateur|Sarah prend la gourde.",
        "narrateur|Elle est fraîche contre ses doigts.",
        "narrateur|Sarah la glisse dans le sac.",
        "maman|Ton chapeau aussi, le soleil tape.",
        "narrateur|Sarah cherche près de la chaise.",
        "narrateur|La chaise est vide.",
        "enfant-f|Il n'est pas là.",
        "maman|Regarde sous le siège.",
        "narrateur|Le chapeau souple est par terre.",
        "narrateur|Sarah le plie tout doucement.",
        "narrateur|Elle le pose dans le sac.",
        "enfant-f|Et mon doudou ?",
        "maman|Il voudra Chouchou aussi.",
        "narrateur|Le doudou gris a les oreilles plates.",
        "narrateur|Il sent encore l'oreiller.",
        "narrateur|Sarah le serre, puis le glisse.",
        "narrateur|La sangle se coince dans le zip.",
        "enfant-f|Ça reste, maman.",
        "maman|Doucement, tu peux l'aider.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Sarah prépare le sac.",
        "narrateur|Où met-elle les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Sarah pince le tissu coincé.",
        "narrateur|Elle le tire vers elle, tout bas.",
        "narrateur|Le zip avance, petit à petit.",
        "enfant-f|Il part.",
        "maman|Merci, Sarah.",
        "maman|Tu l'as aidé.",
        "narrateur|Sarah appuie encore un peu.",
        "narrateur|Ça fait zzz, tout doux.",
        "narrateur|Le sac vert est fermé.",
        "maman|Le sac est prêt ?",
        "enfant-f|Oui, maman.",
        "narrateur|Sarah pose le sac contre sa jambe.",
        "narrateur|Le vert brille un peu.",
        "narrateur|Le cheval de bois reste sur le lit.",
        "maman|Le cheval reste ici.",
        "enfant-f|Le doudou vient.",
        "maman|On descend voir Chouchou ?",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Sarah porte le sac.",
        "narrateur|Les bretelles sont souples.",
        "maman|On va vers la porte.",
        "narrateur|Elles quittent l'appartement.",
        "narrateur|La cage d'escalier sent le savon.",
        "maman|Tu as ton sac ?",
        "enfant-f|Oui, maman.",
        "narrateur|Les marches sont un peu froides.",
        "narrateur|Un voisin ferme une porte, tout loin.",
        "narrateur|Elles arrivent dans la cour.",
        "narrateur|Le linge blanc claque encore.",
        "narrateur|Chouchou est près du pot fêlé.",
        "enfant-f|Je suis là !",
        "maman|Elle t'attendait.",
        "narrateur|Sarah s'accroupit près du pot.",
        "narrateur|La terre du pot est un peu sèche.",
        "enfant-f|Le linge danse, tu vois ?",
        "maman|Oui, pour vous deux.",
        "narrateur|Un chat gris revient dans l'ombre.",
        "narrateur|Sarah ouvre un tout petit peu le sac.",
        "enfant-f|Doudou, tu vois Chouchou ?",
        "maman|Il la voit, dedans.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Les deux filles se tiennent la main.",
        "narrateur|Le linge fait une ombre sur le sol.",
        "enfant-f|On est dans la cour.",
        "maman|Oui, tu es arrivée.",
        "narrateur|Le sac vert repose près du pot.",
        "narrateur|L'orange de la cuisine sent encore.",
        "maman|Bravo, tu as préparé tout ça.",
        "narrateur|Le linge blanc sèche encore, tout calme.",
    ],
}
preview("ATOM-AUT.AFF.001-02", "N1", S02)
write_story(
    "ATOM-AUT.AFF.001-02",
    "Sarah veut retrouver Chouchou dans la cour de l'immeuble. Le chapeau est sous la chaise, la sangle coincée. Elle range, descend. Le linge danse pour elles.",
    "La cour de Sarah",
    "Sarah, maman",
    "appartement d'immeuble puis cour",
    S02,
    {},
    q_sac("Sarah", elle=True),
)
relecture(
    "ATOM-AUT.AFF.001-02",
    "La cour de Sarah",
    "Sarah veut Chouchou en bas. Chapeau sous la chaise, zip coincé. Elle agit. La cour, le linge, la main.",
    "Pas de refrain d'objets. Fin = le désir (la cour, l'amie).",
)


# ---------------------------------------------------------------------------
# 03 N1 Nino, maman — montagne, pique-nique, gourde trop froide
# ---------------------------------------------------------------------------
S03 = {
    "CHK_T0000_P0000": [
        "narrateur|Le vent de la pente plie l'herbe.",
        "narrateur|L'herbe sent le foin, tout sec.",
        "narrateur|La maison de bois craque un peu.",
        "narrateur|Une casserole chuchote dans la cuisine.",
        "narrateur|Ça sent le biscuit tout chaud.",
        "narrateur|Une vapeur légère danse près du four.",
        "narrateur|Dehors, une pierre grise chauffe déjà.",
        "narrateur|Un oiseau de montagne crie, tout haut.",
        "maman|Nino, le biscuit est prêt.",
        "enfant-m|On le mange dehors ?",
        "maman|Oui, sur la pente.",
        "maman|Un pique-nique, tout petit.",
        "narrateur|En ce moment, Nino s'accroupit.",
        "narrateur|Le sac rouge est par terre.",
        "narrateur|La sangle est lisse, un peu froide.",
        "enfant-m|Il est rouge, maman.",
        "maman|Oui, c'est le tien.",
        "maman|Le goûter d'abord, encore chaud.",
        "narrateur|Nino prend le petit paquet.",
        "narrateur|Le papier fait un bruit doux.",
        "narrateur|Ça sent encore le biscuit.",
        "enfant-m|Je le mange maintenant ?",
        "maman|Plus tard, dans l'herbe.",
        "maman|D'abord, dans le sac.",
        "narrateur|Nino pose le goûter dedans.",
        "maman|Prends aussi de l'eau.",
        "narrateur|Nino prend la gourde verte.",
        "narrateur|Elle est trop froide pour ses doigts.",
        "enfant-m|Aïe, elle pique.",
        "maman|Enveloppe-la dans le linge.",
        "narrateur|Un linge à carreaux attend sur la table.",
        "narrateur|Nino l'enroule autour de l'eau.",
        "narrateur|Le froid s'en va un peu.",
        "enfant-m|C'est mieux.",
        "narrateur|Il pose la gourde dans le sac.",
        "enfant-m|Où est le chapeau ?",
        "narrateur|Le crochet du bas est vide.",
        "narrateur|Le chapeau est trop haut.",
        "maman|Je te le tends ?",
        "enfant-m|Oui, s'il te plaît.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nino prépare le sac.",
        "narrateur|Où met-il les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Maman tend le chapeau.",
        "narrateur|Il est tout mou, un peu chaud.",
        "narrateur|Nino le met dans le sac.",
        "enfant-m|Il est dedans.",
        "maman|Merci, Nino.",
        "maman|Tu as aidé tes doigts aussi.",
        "narrateur|Nino appuie sur la fermeture.",
        "narrateur|Ça fait zzz.",
        "narrateur|Le sac rouge est fermé.",
        "maman|Le sac est prêt ?",
        "enfant-m|Oui, maman.",
        "narrateur|Nino pose la main sur le rouge.",
        "narrateur|Le papier du goûter se tait.",
        "maman|Le biscuit voyage avec nous.",
        "enfant-m|Dans le sac.",
        "maman|On met tes chaussures ?",
        "enfant-m|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Nino enfile ses chaussures.",
        "narrateur|La semelle gratte le bois.",
        "maman|Tu as fini tes chaussures ?",
        "enfant-m|Oui, maman.",
        "narrateur|Maman ouvre la porte.",
        "narrateur|L'air de la pente entre, frais.",
        "narrateur|L'herbe est un peu sèche.",
        "narrateur|Ils s'assoient près d'une pierre chaude.",
        "enfant-m|Le goûter, maintenant ?",
        "maman|Oui, il est dans le sac.",
        "narrateur|Nino ouvre un tout petit peu.",
        "narrateur|Le papier fait encore un bruit.",
        "narrateur|Une fourmi passe dans l'herbe.",
        "enfant-m|Elle veut le biscuit ?",
        "maman|Elle a son chemin.",
        "maman|Nous, le nôtre.",
        "narrateur|Nino sort le paquet.",
        "narrateur|Le biscuit est encore un peu chaud.",
        "enfant-m|Il sent bon.",
        "maman|Tu croques ?",
        "enfant-m|Oui.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Nino croque le biscuit.",
        "narrateur|La croûte casse, toute légère.",
        "enfant-m|Il est encore chaud.",
        "maman|Comme le four, tout à l'heure.",
        "narrateur|Le sac rouge repose dans l'herbe.",
        "narrateur|Le vent de la pente passe encore.",
        "maman|Bravo, tu as préparé le pique-nique.",
        "narrateur|La pierre grise reste chaude sous la main.",
    ],
}
preview("ATOM-AUT.AFF.001-03", "N1", S03)
write_story(
    "ATOM-AUT.AFF.001-03",
    "Nino veut pique-niquer le biscuit sur la pente. La gourde pique, le chapeau est trop haut. Il enveloppe, range, croque dans l'herbe.",
    "Le pique-nique de la pente",
    "Nino, maman",
    "chalet de montagne puis herbe de la pente",
    S03,
    {},
    q_sac("Nino"),
)
relecture(
    "ATOM-AUT.AFF.001-03",
    "Le pique-nique de la pente",
    "Nino veut le biscuit dehors. Gourde trop froide, chapeau trop haut. Il agit. Croûte chaude, pierre, vent.",
    "Leçon greffée (sac) sans liste chantée.",
)


# ---------------------------------------------------------------------------
# 04 N2 Mila, maman — port, bateau, loquet, doudou dans le manteau
# ---------------------------------------------------------------------------
S04 = {
    "CHK_T0000_P0000": [
        "narrateur|L'eau du port claque contre le bois.",
        "narrateur|Une corde mouillée sent le sel.",
        "narrateur|Les mâts bougent un tout petit peu.",
        "narrateur|Dans l'appartement au-dessus du quai, ça sent le savon.",
        "narrateur|Une mouette crie, tout près de la vitre.",
        "narrateur|Le dessin de Mila sèche près de la fenêtre.",
        "narrateur|Il sent encore un peu la peinture.",
        "narrateur|Un bateau bleu attend au bout du quai.",
        "maman|Mila, tu entends l'eau ?",
        "enfant-f|Oui, maman.",
        "enfant-f|Je veux le bateau.",
        "maman|On y va, avec le sac.",
        "narrateur|En ce moment, Mila touche la sangle.",
        "narrateur|Maman pose le sac bleu près des chaussures.",
        "narrateur|Le tissu est un peu rêche.",
        "narrateur|Une chaussure rouge est là.",
        "narrateur|L'autre n'est pas là.",
        "enfant-f|Il est bleu, maman.",
        "maman|Oui, prends de l'eau pour le quai.",
        "narrateur|Mila prend la gourde.",
        "narrateur|Elle est froide contre ses doigts.",
        "narrateur|Elle la met dans le sac.",
        "narrateur|Le goûter sent la pomme.",
        "narrateur|Le papier fait un petit bruit.",
        "maman|Glisse aussi le goûter.",
        "narrateur|Mila le glisse près de l'eau.",
        "enfant-f|Et mon doudou ?",
        "narrateur|Le doudou n'est pas près des chaussures.",
        "maman|Regarde dans la poche du manteau.",
        "narrateur|Mila cherche dans la poche.",
        "narrateur|Le doudou sent le coton.",
        "enfant-f|Il était caché.",
        "narrateur|Elle le glisse dans le sac.",
        "maman|On ouvre ?",
        "narrateur|Le loquet de la porte résiste.",
        "enfant-f|Il reste, maman.",
        "maman|Pousse le petit bouton, tout doux.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Mila prépare le sac.",
        "narrateur|Où met-elle les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Mila pousse le bouton du loquet.",
        "narrateur|Le métal est un peu froid.",
        "narrateur|Le loquet cède, tout à coup.",
        "enfant-f|Il part.",
        "maman|Merci, Mila.",
        "narrateur|Mila ferme le zip du sac.",
        "narrateur|Ça fait zzz.",
        "narrateur|Le sac bleu est fermé.",
        "maman|Le sac est prêt ?",
        "enfant-f|Oui, maman.",
        "narrateur|Mila pose le sac contre sa jambe.",
        "narrateur|Une chaussure rouge touche le sac.",
        "narrateur|Le dessin jaune attend encore.",
        "maman|Tu prends aussi ton dessin ?",
        "enfant-f|Oui, pour le bateau.",
        "maman|On cherche l'autre chaussure ?",
        "enfant-f|Sous le banc.",
    ],
    "CHK_T0000_P0000_END": [
        "maman|On met tes chaussures, maintenant.",
        "narrateur|Mila enfile une chaussure rouge.",
        "narrateur|L'autre est sous le banc.",
        "narrateur|Elle la tire tout doucement.",
        "narrateur|La semelle froide se réchauffe.",
        "maman|Tu as fini tes chaussures ?",
        "enfant-f|Oui, maman.",
        "narrateur|Mila reprend le sac.",
        "narrateur|Elle tient aussi son dessin.",
        "maman|On va vers le quai ?",
        "enfant-f|Oui, mon dessin est dans ma main.",
        "narrateur|Elles descendent les marches du port.",
        "narrateur|L'air sent le sel et le bois mouillé.",
        "narrateur|Le bateau bleu tape un peu l'eau.",
        "enfant-f|Il est là.",
        "maman|Oui, tout près.",
        "narrateur|Mila tient le dessin tout droit.",
        "enfant-f|Il ne plie pas.",
        "maman|Tu le tiens bien.",
        "narrateur|Une mouette passe tout bas.",
        "narrateur|L'eau claque encore contre le quai.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Mila pose le pied sur le bois du bateau.",
        "narrateur|Le bateau bouge, tout doux.",
        "enfant-f|On flotte, maman.",
        "maman|Oui, tu es arrivée.",
        "narrateur|Le sac bleu voyage contre sa hanche.",
        "narrateur|Le sel pique un peu les lèvres.",
        "maman|Bravo, tu as préparé la sortie.",
        "narrateur|L'eau du port claque encore, tout près.",
    ],
}
preview("ATOM-AUT.AFF.001-04", "N2", S04)
write_story(
    "ATOM-AUT.AFF.001-04",
    "Mila veut le bateau bleu du port. Le doudou est dans le manteau, le loquet résiste. Elle pousse, range, pose le pied sur le bois.",
    "Le bateau de Mila",
    "Mila, maman",
    "appartement au-dessus du quai puis bateau du port",
    S04,
    {},
    q_sac("Mila", elle=True),
)
relecture(
    "ATOM-AUT.AFF.001-04",
    "Le bateau de Mila",
    "Mila veut le bateau. Doudou caché, loquet coincé. Elle agit. Sel, bois, flot.",
    "Pas de liste d'objets en refrain.",
)


# ---------------------------------------------------------------------------
# 05 N1 Raphaël, papa — jardin, escargot, zip, livre
# ---------------------------------------------------------------------------
S05 = {
    "CHK_T0000_P0000": [
        "narrateur|Une feuille mouillée colle au seau.",
        "narrateur|Le jardin sent la terre après la pluie.",
        "narrateur|Une goutte tombe encore d'une branche.",
        "narrateur|Elle fait un petit cercle dans une flaque.",
        "narrateur|Papa ouvre le tiroir de laine.",
        "narrateur|Ça fait un petit bruit.",
        "narrateur|Les vitres sont un peu grises.",
        "narrateur|Une tasse fume près de la fenêtre.",
        "papa|Raphaël, tu entends la goutte ?",
        "enfant-m|Oui.",
        "enfant-m|Je veux l'escargot.",
        "papa|Il est dans le jardin, tout lent.",
        "papa|On y va, avec le sac.",
        "narrateur|En ce moment, Raphaël s'accroupit.",
        "narrateur|Le sac vert est par terre.",
        "narrateur|Le tissu est un peu rêche.",
        "enfant-m|Il est vert, papa.",
        "papa|Oui, c'est le tien.",
        "papa|Prends de l'eau, même s'il a plu.",
        "narrateur|Raphaël prend la gourde.",
        "narrateur|Elle est froide comme la pluie.",
        "narrateur|Il la met dans le sac.",
        "papa|Le bonnet aussi, le vent est humide.",
        "narrateur|Raphaël prend le bonnet.",
        "narrateur|Il est tout doux.",
        "narrateur|Il sent la laine du tiroir.",
        "enfant-m|Il est chaud.",
        "narrateur|Il le met dans le sac.",
        "papa|Et le livre, si on s'assoit.",
        "narrateur|Le livre est près de la tasse.",
        "narrateur|La couverture est lisse.",
        "narrateur|Une goutte glisse encore sur la vitre.",
        "narrateur|Raphaël tire le zip.",
        "narrateur|Le zip reste un peu.",
        "enfant-m|Ça ne veut pas, papa.",
        "papa|Doucement, tu aides le zip ?",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Raphaël prépare le sac.",
        "narrateur|Où met-il les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Raphaël pousse encore, tout doux.",
        "narrateur|Le zip avance.",
        "narrateur|Il glisse le livre dans le sac.",
        "enfant-m|Il est au chaud.",
        "papa|Merci, Raphaël.",
        "narrateur|Raphaël ferme le sac.",
        "narrateur|Ça fait zzz.",
        "narrateur|Le sac vert est fermé.",
        "papa|Le sac est prêt ?",
        "enfant-m|Oui, papa.",
        "narrateur|Raphaël pose la main sur le sac.",
        "narrateur|Le vert est un peu sombre.",
        "narrateur|Une goutte glisse sur la vitre.",
        "papa|Le livre est au chaud, maintenant.",
        "enfant-m|Dans le sac.",
        "papa|On met le manteau ?",
        "enfant-m|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Raphaël enfile le manteau.",
        "narrateur|Le manteau sent encore la pluie.",
        "papa|Tu as fini ton manteau ?",
        "enfant-m|Oui, papa.",
        "papa|On ouvre la porte.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|L'air sent la terre mouillée.",
        "narrateur|Le seau a encore sa feuille collée.",
        "narrateur|Une flaque fait un petit cercle.",
        "enfant-m|Elle est ronde, papa.",
        "papa|Oui, on la regarde.",
        "narrateur|Ils restent un moment.",
        "narrateur|Sous une feuille, un escargot avance.",
        "narrateur|Sa coquille est brillante, un peu brune.",
        "enfant-m|Il est là.",
        "papa|Tout lent, comme toi tout à l'heure.",
        "narrateur|Une goutte tombe dans la flaque.",
        "narrateur|Le cercle grandit un peu.",
        "enfant-m|Encore, papa.",
        "papa|On en regarde une autre ?",
        "enfant-m|Oui.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|L'escargot pose une corne, puis l'autre.",
        "narrateur|La feuille tremble un tout petit peu.",
        "enfant-m|Il avance.",
        "papa|Oui, tu l'as trouvé.",
        "narrateur|Le sac vert repose près du seau.",
        "narrateur|Le livre reste au chaud, dedans.",
        "papa|Bravo, tu as préparé le jardin.",
        "narrateur|La flaque ronde brille encore.",
    ],
}
preview("ATOM-AUT.AFF.001-05", "N1", S05)
write_story(
    "ATOM-AUT.AFF.001-05",
    "Raphaël veut l'escargot du jardin après la pluie. Le zip résiste. Il pousse, glisse le livre, trouve la coquille brillante.",
    "L'escargot du jardin",
    "Raphaël, papa",
    "maison puis jardin après la pluie",
    S05,
    {"CHK_T0000_P0000": "pluie"},
    q_sac("Raphaël"),
)
relecture(
    "ATOM-AUT.AFF.001-05",
    "L'escargot du jardin",
    "Raphaël veut l'escargot. Zip coincé. Il agit. Coquille, flaque, terre.",
    "Pas de refrain d'objets ni fin mécanique.",
)


# ---------------------------------------------------------------------------
# 06 N2 Nina, papa, maman — hall du marché, pomme, cuillère, chapeau
# ---------------------------------------------------------------------------
S06 = {
    "CHK_T0000_P0000": [
        "narrateur|Les caisses du hall râpent le pavé.",
        "narrateur|Même d'ici, ça sent les pommes.",
        "narrateur|La bouilloire chante dans la cuisine.",
        "narrateur|La vapeur fait un petit nuage.",
        "narrateur|Papa essuie la table.",
        "narrateur|Ça sent le thé.",
        "narrateur|Une tasse fume encore.",
        "narrateur|Maman plie le torchon.",
        "narrateur|Le tiroir fait un petit clic.",
        "narrateur|Près de la porte, la vitre est un peu floue.",
        "papa|Tu vois le hall, Nina ?",
        "enfant-f|Oui.",
        "enfant-f|Je veux une pomme qui brille.",
        "maman|On y va, avec le sac.",
        "narrateur|En ce moment, Nina cherche le sac.",
        "narrateur|Papa sort le sac bleu.",
        "narrateur|Le tissu sent le coton.",
        "papa|Prends de l'eau, le hall est long.",
        "narrateur|Nina met la gourde.",
        "narrateur|La gourde est froide.",
        "narrateur|Elle voit une cuillère en bois.",
        "narrateur|Elle la pose dans le sac.",
        "narrateur|La cuillère fait un bruit dur.",
        "papa|La cuillère reste à la cuisine.",
        "maman|Le hall n'en a pas besoin.",
        "narrateur|Nina retire la cuillère.",
        "enfant-f|Où est le chapeau ?",
        "narrateur|Le chapeau jaune n'est pas là.",
        "maman|Sous la chaise, peut-être.",
        "narrateur|Nina se penche.",
        "narrateur|Le chapeau est souple, un peu poussiéreux.",
        "narrateur|Elle le secoue, tout doux.",
        "narrateur|Elle le met dans le sac.",
        "papa|Ton doudou voudra la pomme aussi.",
        "narrateur|Le doudou sent le coton.",
        "enfant-f|Il est tout doux.",
        "narrateur|Nina le met dans le sac.",
        "maman|Tu fermes ?",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Nina prépare le sac.",
        "narrateur|Où met-elle les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Nina ferme le sac.",
        "narrateur|Ça fait zzz.",
        "narrateur|Le sac bleu est prêt.",
        "maman|Le sac est prêt ?",
        "enfant-f|Oui, maman.",
        "papa|Merci, Nina.",
        "papa|Tu as laissé la cuillère ici.",
        "narrateur|Le petit nuage de la bouilloire s'en va.",
        "maman|On peut sortir, maintenant.",
        "enfant-f|La pomme m'attend.",
        "papa|Oui, elle brille déjà, là-bas.",
        "narrateur|Nina enfile le sac.",
        "narrateur|Le sac est sur le dos de Nina.",
        "maman|Tu as ton sac, Nina ?",
        "enfant-f|Oui, maman.",
        "papa|On ouvre la porte.",
        "narrateur|Papa ouvre la porte.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Ils sortent.",
        "narrateur|L'air sent les caisses et le fruit.",
        "narrateur|Le hall n'est plus flou.",
        "enfant-f|Il est vrai, maintenant.",
        "papa|Oui, on y va ensemble.",
        "narrateur|Une pomme rouge brille sur une caisse.",
        "narrateur|Nina s'accroupit.",
        "narrateur|Elle touche la peau lisse.",
        "narrateur|Elle est un peu froide, un peu sucrée.",
        "enfant-f|Elle brille, maman.",
        "maman|Tu la choisis ?",
        "enfant-f|Celle-là.",
        "narrateur|Nina ferme la main autour de la pomme.",
        "narrateur|Le fruit reste un moment, tout rond.",
        "papa|On la sent ensemble ?",
        "enfant-f|Oui.",
        "narrateur|Nina approche la pomme de son nez.",
        "narrateur|Ça sent le sucre et la peau.",
        "maman|Tu l'as trouvée.",
        "narrateur|Une caisse râpe encore le pavé, tout loin.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Nina ouvre encore la main.",
        "narrateur|La pomme rouge brille dans sa paume.",
        "enfant-f|Elle est à moi.",
        "papa|Oui, tu es arrivée au hall.",
        "narrateur|Le sac bleu tape le dos de Nina.",
        "narrateur|Le thé de la cuisine est loin, maintenant.",
        "maman|Bravo, tu as préparé la sortie.",
        "narrateur|La peau lisse reste froide contre sa main.",
    ],
}
preview("ATOM-AUT.AFF.001-06", "N2", S06)
write_story(
    "ATOM-AUT.AFF.001-06",
    "Nina veut une pomme brillante au hall. Elle pose une cuillère, la retire, trouve le chapeau. La pomme est froide dans sa main.",
    "La pomme du marché",
    "Nina, papa, maman",
    "cuisine puis hall du marché",
    S06,
    {},
    q_sac("Nina", elle=True),
)
relecture(
    "ATOM-AUT.AFF.001-06",
    "La pomme du marché",
    "Nina veut la pomme du hall. Cuillère en trop, chapeau sous la chaise. Elle agit. Peau lisse, sucre.",
    "Pas de liste chantée. Fin = la pomme.",
)


# ---------------------------------------------------------------------------
# 07 N2 Aniss, papa — lisière du bois, oiseau, chapeau, doudou
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|Une branche frotte le chemin du bois.",
        "narrateur|Les aiguilles de pin sentent le chaud.",
        "narrateur|Une tartine croustille sur l'assiette.",
        "narrateur|Ça sent le beurre.",
        "narrateur|Un oiseau chante déjà dehors.",
        "narrateur|Les crochets cliquettent un peu.",
        "narrateur|Le tapis de l'entrée est un peu rêche.",
        "narrateur|Une miette tombe près de la tasse.",
        "narrateur|Papa verse un peu d'eau.",
        "narrateur|L'eau fait un bruit clair.",
        "narrateur|La tartine a un bord doré.",
        "enfant-m|Elle croustille, papa.",
        "papa|Une dernière bouchée ?",
        "enfant-m|Oui.",
        "papa|Aniss, tu entends l'oiseau ?",
        "enfant-m|Oui, je veux le voir dans le bois.",
        "papa|On y va, avec le sac.",
        "narrateur|En ce moment, Aniss s'accroupit.",
        "narrateur|Le sac est posé contre la porte.",
        "narrateur|Il est un peu froid.",
        "narrateur|Le sac est bleu.",
        "papa|Prends de l'eau, le chemin est long.",
        "narrateur|Aniss prend la gourde.",
        "narrateur|Elle est fraîche.",
        "narrateur|Il la met dans le sac.",
        "papa|Le chapeau aussi, les branches piquent.",
        "narrateur|Aniss prend le chapeau.",
        "narrateur|Le bord est un peu souple.",
        "narrateur|Le chapeau glisse par terre.",
        "enfant-m|Il est tombé.",
        "papa|Tu le ramasses, puis dans le sac.",
        "narrateur|Aniss ramasse le chapeau.",
        "narrateur|Il le met dans le sac.",
        "enfant-m|Et le doudou ?",
        "narrateur|Le doudou n'est pas près des chaussures.",
        "papa|Regarde la chaise de la cuisine.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Aniss prépare le sac.",
        "narrateur|Où met-il les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le doudou est sur la chaise de la cuisine.",
        "narrateur|Il sent le coton.",
        "narrateur|Il est tout doux.",
        "narrateur|Aniss le met dans le sac.",
        "enfant-m|Te voilà.",
        "papa|Merci, Aniss.",
        "narrateur|Aniss ferme le sac.",
        "narrateur|Ça fait zzz.",
        "narrateur|Il le porte.",
        "papa|Le sac est prêt ?",
        "enfant-m|Oui, papa.",
        "narrateur|La sangle n'est plus froide.",
        "papa|Tu as fini ta tartine ?",
        "enfant-m|Oui, papa.",
        "papa|Alors on va voir l'oiseau.",
        "narrateur|Une miette reste près de la tasse.",
        "papa|On la laisse pour plus tard.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On met tes chaussures.",
        "narrateur|Aniss enfile ses chaussures.",
        "papa|Tu as fini tes chaussures ?",
        "enfant-m|Oui, papa.",
        "papa|On ouvre la porte.",
        "narrateur|Papa ouvre la porte.",
        "narrateur|L'air sent le pin et l'herbe sèche.",
        "narrateur|L'oiseau chante encore.",
        "enfant-m|Je l'entends, papa.",
        "papa|Oui, il est dans le grand arbre.",
        "narrateur|Ils marchent sur le chemin du bois.",
        "narrateur|Le sac tape doucement.",
        "narrateur|La tartine n'est plus sur l'assiette.",
        "narrateur|Ils s'arrêtent sous le grand arbre.",
        "narrateur|Une feuille bouge.",
        "enfant-m|Il est là-haut.",
        "papa|Oui, on écoute encore un peu.",
        "narrateur|L'oiseau fait un petit cri.",
        "narrateur|Aniss lève le menton.",
        "narrateur|Une plume grise est dans l'herbe.",
        "enfant-m|Pour moi ?",
        "papa|Tu la prends tout doux ?",
        "narrateur|Aniss ramasse la plume.",
        "narrateur|Elle est légère, presque rien.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|La plume chatouille le doigt d'Aniss.",
        "narrateur|L'oiseau chante plus fort.",
        "enfant-m|On l'a vu.",
        "papa|On l'a entendu.",
        "narrateur|Le sac voyage sur le dos d'Aniss.",
        "narrateur|Les aiguilles de pin sentent encore le chaud.",
        "papa|Bravo, tu as préparé le chemin.",
        "narrateur|Aniss reste un moment, tout calme, sous l'arbre.",
    ],
}
preview("ATOM-AUT.AFF.001-07", "N2", S07)
write_story(
    "ATOM-AUT.AFF.001-07",
    "Aniss veut l'oiseau du bois. Le chapeau tombe, le doudou est sur la chaise. Il range, marche, une plume lui chatouille le doigt.",
    "La plume d'Aniss",
    "Aniss, papa",
    "maison au bord du bois puis chemin sous l'arbre",
    S07,
    {"CHK_T0000_P0000": "oiseau"},
    q_sac("Aniss"),
)
relecture(
    "ATOM-AUT.AFF.001-07",
    "La plume d'Aniss",
    "Aniss veut l'oiseau. Chapeau tombé, doudou oublié. Il agit. Plume, cri, pin.",
    "Pas de refrain gourde-chapeau-doudou.",
)


# ---------------------------------------------------------------------------
# 08 N2 Victorina, papa, maman — rive, château de sable, seau mouillé
# ---------------------------------------------------------------------------
S08 = {
    "CHK_T0000_P0000": [
        "narrateur|Le sable de la rive est encore froid.",
        "narrateur|L'eau du fleuve cliquette contre les cailloux.",
        "narrateur|Le robinet du jardin goutte encore.",
        "narrateur|Une goutte tombe dans le seau rouge.",
        "narrateur|Le plastique fait un petit toc.",
        "narrateur|L'herbe est encore mouillée.",
        "narrateur|Les bottes brillent un peu.",
        "narrateur|L'entrée sent l'herbe coupée.",
        "narrateur|Un arrosoir attend près des bottes.",
        "narrateur|Le métal est un peu froid.",
        "narrateur|Une abeille passe tout bas.",
        "maman|Victorina, on va à la rive.",
        "enfant-f|Je veux un château de sable.",
        "maman|Avec le seau, alors.",
        "narrateur|En ce moment, Victorina touche le seau.",
        "narrateur|Le plastique est un peu froid.",
        "narrateur|Papa pose le sac près de la porte.",
        "papa|Prends de l'eau, la rive est au soleil.",
        "narrateur|Victorina met la gourde dans le sac.",
        "narrateur|La gourde est fraîche.",
        "narrateur|Une goutte glisse du seau.",
        "narrateur|Elle tombe sur le tapis.",
        "enfant-f|Le seau est mouillé.",
        "papa|On l'essuie, puis dans le sac.",
        "narrateur|Victorina essuie le bord.",
        "narrateur|Elle hésite.",
        "narrateur|Le seau reste un moment dehors.",
        "maman|Le château a besoin du seau.",
        "enfant-f|Il est encore un peu mouillé.",
        "papa|Tu l'essuies encore ?",
        "enfant-f|Oui.",
        "narrateur|Victorina passe le torchon une fois de plus.",
        "narrateur|Le plastique n'est plus luisant.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Victorina prépare le sac.",
        "narrateur|Où met-elle les affaires ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "maman|Le seau vient avec nous.",
        "narrateur|Victorina prend le seau rouge.",
        "narrateur|Elle le met dans le sac.",
        "papa|Merci, Victorina.",
        "narrateur|Victorina ferme le sac.",
        "narrateur|Ça fait zzz.",
        "narrateur|Le sac est prêt.",
        "maman|La gourde est dedans ?",
        "enfant-f|Oui, et le seau aussi.",
        "papa|Le sac est prêt ?",
        "enfant-f|Oui, papa.",
        "narrateur|Dans le sac, la gourde est fraîche.",
        "maman|Le seau aussi.",
        "enfant-f|Pour le château.",
        "papa|Oui, on l'emporte.",
        "papa|On met tes bottes ?",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "papa|On met tes bottes.",
        "narrateur|Victorina enfile ses bottes.",
        "papa|Tu as fini tes bottes ?",
        "enfant-f|Oui, papa.",
        "papa|On ferme la porte.",
        "narrateur|Papa ferme la porte.",
        "maman|Tu as ton sac, Victorina ?",
        "enfant-f|Oui, maman.",
        "narrateur|Le chemin sent l'herbe mouillée, puis le fleuve.",
        "narrateur|Le seau tape un peu, tout doux.",
        "enfant-f|Mon château va être grand.",
        "maman|Oui, le sable t'attend.",
        "narrateur|Ils arrivent à la rive.",
        "narrateur|Le sable est encore un peu frais.",
        "narrateur|Victorina pose le sac.",
        "narrateur|Elle sort le seau.",
        "narrateur|Le plastique n'est plus mouillé.",
        "enfant-f|Je fais le mur.",
        "papa|Doucement, une poignée, puis une autre.",
        "narrateur|Le sable fait un petit bruit.",
        "narrateur|Un mur tout bas apparaît.",
        "maman|Il tient, ce mur.",
        "enfant-f|Encore une poignée.",
        "narrateur|Victorina appuie tout doucement.",
        "narrateur|Le château a un petit coin rond.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Le petit mur tient encore.",
        "narrateur|L'eau du fleuve cliquette tout près.",
        "enfant-f|Mon château est là.",
        "papa|Oui, tu l'as fait.",
        "narrateur|Le seau rouge repose dans le sable.",
        "narrateur|Le robinet du jardin est loin, maintenant.",
        "maman|Bravo, tu as préparé le seau.",
        "narrateur|Le coin rond du château reste frais sous le doigt.",
    ],
}
preview("ATOM-AUT.AFF.001-08", "N2", S08)
write_story(
    "ATOM-AUT.AFF.001-08",
    "Victorina veut un château sur la rive. Le seau goutte, elle l'essuie, hésite, le met dans le sac. Le mur de sable tient.",
    "Le château de la rive",
    "Victorina, papa, maman",
    "jardin puis rive du fleuve",
    S08,
    {},
    q_sac("Victorina", elle=True),
)
relecture(
    "ATOM-AUT.AFF.001-08",
    "Le château de la rive",
    "Victorina veut le château. Seau mouillé, hésitation, essuyage. Elle agit. Mur, fleuve, sable.",
    "Pas de refrain gourde-seau. Fin = le château.",
)
