#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-TMP.SEM.002-01..07 + ATOM-VIV.ANI.001-01."""
from __future__ import annotations

from _lib import relecture, write_story

Q_SEM = {
    "accepted_examples": "week-end | weekend | samedi | dimanche | le week-end | mercredi",
}


def q_sem(ans: str, retry: str) -> dict:
    return {**Q_SEM, "expected_answer": ans, "retry_prompt": retry}


# ---------------------------------------------------------------------------
# 01 N2 Sarah, papa — mercredi atelier peinture, tache, week-end
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-01",
    "Sarah veut un soleil jaune à la fenêtre. Mercredi, le pinceau trop chargé fait une tache. Ils essuient. Samedi le soleil sèche. Dimanche, week-end, il chauffe la vitre.",
    "Une tache sur le soleil",
    "Sarah, papa",
    "cuisine, table de peinture, mercredi puis week-end",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sur la table, un pot de bleu tremble.",
            "narrateur|La lumière passe dans l'eau du pot.",
            "narrateur|Ça sent la peinture, un peu sucré.",
            "papa|C'est mercredi, Sarah.",
            "papa|Pas de cartable.",
            "enfant-f|On reste ?",
            "papa|Oui.",
            "papa|Mercredi, on reste.",
            "enfant-f|On peint ?",
            "papa|Tu veux un soleil ?",
            "enfant-f|Un grand soleil jaune.",
            "narrateur|Papa pose une grande feuille.",
            "narrateur|Le papier est un peu rêche.",
            "narrateur|Un coin se soulève.",
            "narrateur|Sarah le plaque avec la main.",
            "papa|Tu le tiens bien.",
            "narrateur|En ce moment, Sarah trempe le pinceau.",
            "narrateur|Le jaune est épais, comme du miel.",
            "narrateur|Elle pose un rond au milieu.",
            "enfant-f|Le soleil commence.",
            "papa|Il est chaud déjà ?",
            "enfant-f|Presque.",
            "narrateur|Elle veut un rayon.",
            "narrateur|Le pinceau va vers le bleu.",
            "narrateur|Le bleu est trop chargé.",
            "narrateur|Une goutte tombe.",
            "narrateur|Elle fait une tache sur le jaune.",
            "enfant-f|Oh.",
            "enfant-f|Le soleil a une tache.",
            "papa|Le pinceau avait trop de bleu.",
            "papa|On essuie ?",
            "enfant-f|Oui.",
            "narrateur|Sarah prend le linge près du pot.",
            "narrateur|Le linge est doux, un peu rêche.",
            "narrateur|Elle tapote la tache.",
            "narrateur|Le bleu pâlit.",
            "papa|Tu essuies tout doux.",
            "papa|Merci.",
            "enfant-f|Le jaune revient.",
            "papa|Un peu.",
            "papa|On laisse sécher.",
            "enfant-f|Quand on le verra ?",
            "papa|Samedi, on regardera.",
            "papa|Dimanche, on le mettra à la fenêtre.",
            "papa|Samedi et dimanche, c'est le week-end.",
            "enfant-f|Pas d'école.",
            "papa|Pas d'école.",
            "papa|Comme mercredi.",
            "narrateur|Sarah pose le pinceau sur le bord.",
            "narrateur|Une petite tache bleue reste au coin.",
            "narrateur|Le soleil attend sur la table.",
            "papa|Il sèche, là.",
            "enfant-f|J'attends samedi.",
            "narrateur|Papa rince le pinceau.",
            "narrateur|L'eau devient verte, puis claire.",
            "enfant-f|Le bleu s'en va.",
            "papa|Oui.",
            "papa|Comme la tache.",
            "narrateur|La feuille tremble un peu.",
            "narrateur|Sarah pose une tasse dessus.",
            "papa|Pour le coin.",
            "enfant-f|Il ne vole plus.",
            "papa|Mercredi, on a peint.",
            "papa|Le week-end, on accrochera.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah touche le papier du doigt.",
            "narrateur|Le jaune n'est plus collant.",
            "enfant-f|Samedi.",
            "enfant-f|Et dimanche.",
            "papa|Oui.",
            "papa|C'est le week-end.",
            "papa|Comme mercredi, pas d'école.",
            "enfant-f|On accroche ?",
            "papa|Dimanche, à la fenêtre.",
            "narrateur|Sarah souffle un peu sur le rond.",
            "narrateur|Le papier ne bouge plus.",
            "papa|Il est prêt.",
            "enfant-f|Le bleu a disparu.",
            "papa|Tu as essuyé.",
            "papa|Bravo.",
            "narrateur|Une lueur passe sur le jaune.",
            "papa|Tu vois le rayon ?",
            "enfant-f|Oui, papa.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Dimanche, la vitre est froide.",
            "narrateur|Papa tient le ruban.",
            "enfant-f|Le soleil va là.",
            "papa|Contre le jour.",
            "narrateur|Sarah plaque la feuille.",
            "narrateur|Le ruban fait un petit bruit.",
            "narrateur|Le jaune s'allume.",
            "papa|Il chauffe un peu la pièce.",
            "enfant-f|C'est mon mercredi.",
            "papa|Et le week-end le montre.",
            "narrateur|Une tache pâle reste au bord.",
            "enfant-f|On voit encore le bleu.",
            "papa|Un peu.",
            "papa|On a essuyé ensemble.",
            "enfant-f|Merci, papa.",
            "papa|Merci à toi.",
            "narrateur|Le pot de bleu est vide, presque.",
            "narrateur|Il brille encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le soleil est à la fenêtre.",
            "papa|Il va rester.",
            "narrateur|Le jaune chauffe un peu la vitre.",
            "narrateur|Ça sent encore la peinture, tout doux.",
            "narrateur|Le rayon traverse le rond.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("week-end", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-01",
    "Une tache sur le soleil",
    "Mercredi, Sarah peint un soleil. Le pinceau trop chargé tache le jaune. Elle essuie. Samedi le papier sèche. Dimanche, week-end, le soleil est à la fenêtre.",
    "D16 Sarah, papa. Leçon greffée : mercredi + week-end sans l'école. Pas de liste de jours. Fin sensorielle, pas « L'histoire est finie ».",
)

# ---------------------------------------------------------------------------
# 02 N3 Amir, papa — mercredi square, samedi pique-nique
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-02",
    "Amir veut un pique-nique. Mercredi au square, le banc est mouillé. Ils essuient. Samedi, week-end, le pain et la nappe attendent dans l'herbe.",
    "Le pain du samedi",
    "Amir, papa",
    "square mercredi, herbe du pique-nique samedi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le gravier du square sent encore la pluie.",
            "narrateur|Une flaque garde le ciel, tout petit.",
            "narrateur|Les chaînes des balançoires sont froides.",
            "papa|C'est mercredi, Amir.",
            "papa|Pas d'école.",
            "enfant-m|On reste au square ?",
            "papa|Un moment.",
            "papa|Samedi, on fera le pique-nique.",
            "enfant-m|Avec le pain ?",
            "papa|Avec le pain.",
            "papa|Samedi, c'est le week-end.",
            "narrateur|Amir pose la main sur le banc.",
            "narrateur|Le bois est mouillé, luisant.",
            "enfant-m|Il est froid.",
            "papa|La pluie est restée.",
            "papa|On essuie ?",
            "enfant-m|Oui.",
            "narrateur|Papa tend un linge de poche.",
            "narrateur|En ce moment, Amir frotte le banc.",
            "narrateur|L'eau part en petites traces.",
            "papa|Tu fais une place sèche.",
            "enfant-m|Pour samedi.",
            "papa|Pour samedi.",
            "papa|Et pour maintenant.",
            "narrateur|Ils s'assoient au bord.",
            "narrateur|Le gravier croque sous une chaussure.",
            "enfant-m|Je vois une fourmi.",
            "papa|Elle cherche aussi.",
            "narrateur|Amir suit la fourmi du doigt.",
            "narrateur|Elle contourne la flaque.",
            "papa|Mercredi, on prépare.",
            "papa|Samedi, on mange dehors.",
            "enfant-m|Et dimanche ?",
            "papa|Dimanche aussi, pas d'école.",
            "papa|Samedi et dimanche, le week-end.",
            "narrateur|Un oiseau secoue une branche.",
            "narrateur|Une goutte tombe dans la flaque.",
            "enfant-m|Ploc.",
            "papa|Tu as entendu ?",
            "enfant-m|Oui, papa.",
            "narrateur|Amir pose une feuille sur l'eau.",
            "narrateur|Elle flotte, puis tourne.",
            "papa|Un bateau.",
            "enfant-m|Il va au pique-nique.",
            "papa|Samedi, le vrai pain.",
            "enfant-m|Pas la feuille.",
            "papa|Pas la feuille.",
            "narrateur|Le banc sèche un peu plus.",
            "narrateur|Le linge est lourd d'eau.",
            "papa|On le tord ?",
            "enfant-m|Je tords.",
            "narrateur|L'eau tombe entre les graviers.",
            "papa|Merci.",
            "papa|Le banc est à nous.",
            "enfant-m|J'attends samedi.",
            "narrateur|Le square sent l'herbe mouillée.",
            "narrateur|Une cloche lointaine sonne deux fois.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir tape deux cailloux l'un contre l'autre.",
            "enfant-m|Samedi.",
            "enfant-m|Dimanche.",
            "papa|Oui.",
            "papa|C'est le week-end.",
            "papa|Comme mercredi, on est ensemble.",
            "enfant-m|Le pain.",
            "papa|Samedi, le pain.",
            "narrateur|La flaque n'a plus de feuille.",
            "narrateur|Le petit bateau a coulé.",
            "enfant-m|Il a fini.",
            "papa|Le vrai pique-nique, lui, viendra.",
            "papa|Tu as essuyé le banc.",
            "papa|Bravo.",
            "enfant-m|Il est sec.",
            "papa|Presque.",
            "papa|Le soleil aide.",
            "narrateur|Une tache claire s'élargit sur le bois.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Samedi, l'herbe est plus chaude.",
            "narrateur|Papa pose la nappe près du banc.",
            "enfant-m|Le banc est sec.",
            "papa|Mercredi, tu l'avais préparé.",
            "narrateur|Le pain craque quand on le casse.",
            "narrateur|Une miette tombe dans l'herbe.",
            "enfant-m|Pour la fourmi.",
            "papa|Elle va trouver.",
            "papa|Tu veux le bout croustillant ?",
            "enfant-m|Oui.",
            "narrateur|Le vent soulève un coin de nappe.",
            "narrateur|Amir le plaque avec la main.",
            "papa|Merci.",
            "papa|Dimanche, on finira les pommes.",
            "enfant-m|Encore le week-end.",
            "papa|Encore le week-end.",
            "narrateur|Le square sent le pain et l'herbe.",
            "narrateur|La flaque n'est plus qu'un trait brillant.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le pique-nique est là.",
            "papa|Samedi l'a apporté.",
            "narrateur|Une miette reste dans l'herbe chaude.",
            "narrateur|Le banc garde une trace sèche, claire.",
            "narrateur|Le pain sent encore sous la nappe.",
        ],
    },
    {
        "CHK_T0000_P0000": "enfants_parc",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("samedi", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-02",
    "Le pain du samedi",
    "Mercredi, Amir essuie le banc mouillé du square. Il veut le pique-nique. Samedi, week-end, le pain craque dans l'herbe. Dimanche, les pommes.",
    "D16 Amir, papa. Pas de grand-mère. Leçon greffée mercredi/week-end. Imprévu : banc mouillé. Fin : miette, banc sec.",
)

# ---------------------------------------------------------------------------
# 03 N2 Mila, maman — mercredi bibliothèque, livre qui glisse
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-03",
    "Mila veut un livre de bateau. Mercredi à la bibliothèque, le livre glisse. Elle le rattrape. Le week-end, elle finit l'histoire sur le canapé.",
    "Le livre qui glisse",
    "Mila, maman",
    "bibliothèque mercredi, canapé le week-end",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les livres sentent le papier froid.",
            "narrateur|Une haute fenêtre laisse un carré de jour.",
            "narrateur|Le tapis avale les pas.",
            "maman|C'est mercredi, Mila.",
            "maman|Pas d'école.",
            "enfant-f|On prend un livre ?",
            "maman|Oui.",
            "maman|Tu en veux un ?",
            "enfant-f|Un bateau.",
            "narrateur|Mila suit le rayon du doigt.",
            "narrateur|Les dos sont lisses, un peu poussiéreux.",
            "narrateur|En ce moment, elle tire un livre bleu.",
            "narrateur|Le livre glisse trop vite.",
            "narrateur|Il tombe contre sa poitrine.",
            "enfant-f|Oh.",
            "maman|Tu l'as eu.",
            "enfant-f|Il voulait partir.",
            "maman|Les livres glissent parfois.",
            "maman|On s'assoit ?",
            "narrateur|Elles s'assoient sur le coussin bas.",
            "narrateur|Le coussin est dur, puis il cède.",
            "narrateur|Mila ouvre le livre.",
            "narrateur|Un bateau blanc tient toute une page.",
            "enfant-f|Il a une voile.",
            "maman|Tu la vois ?",
            "enfant-f|Oui.",
            "narrateur|Une page colle un peu.",
            "narrateur|Mila souffle.",
            "narrateur|La page se décolle.",
            "maman|Mercredi, on lit ici.",
            "maman|Samedi, on lira à la maison.",
            "enfant-f|Et dimanche ?",
            "maman|Dimanche aussi.",
            "maman|Samedi et dimanche, c'est le week-end.",
            "enfant-f|Pas d'école.",
            "maman|Pas d'école.",
            "maman|Comme mercredi.",
            "narrateur|Mila tourne encore une page.",
            "narrateur|Le papier fait un petit bruit sec.",
            "enfant-f|Le bateau avance.",
            "maman|Il va où ?",
            "enfant-f|Vers la maison.",
            "maman|Comme nous, samedi.",
            "narrateur|Une dame passe loin, sans parler.",
            "narrateur|Le silence revient tout de suite.",
            "maman|On chuchote.",
            "enfant-f|Le bateau aussi.",
            "narrateur|Mila pose le livre sur ses genoux.",
            "narrateur|La couverture est un peu froide encore.",
            "maman|Tu le gardes ?",
            "enfant-f|Oui.",
            "enfant-f|Jusqu'au week-end.",
            "maman|Jusqu'au week-end.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila referme le livre un moment.",
            "enfant-f|Samedi.",
            "enfant-f|Dimanche.",
            "maman|Oui.",
            "maman|C'est le week-end.",
            "maman|On lira la fin.",
            "enfant-f|À la maison.",
            "maman|À la maison.",
            "narrateur|Elle caresse la voile sur la couverture.",
            "narrateur|Le bleu est usé, doux.",
            "maman|Tu l'as rattrapé.",
            "maman|Bravo.",
            "enfant-f|Il a glissé.",
            "maman|Et tu l'as tenu.",
            "maman|On le range dans le sac ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le sac sent le tissu et le papier.",
            "narrateur|Le livre s'assoit au fond, bien droit.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Samedi, le canapé est plus chaud.",
            "narrateur|Mila ouvre le livre de bateau.",
            "enfant-f|La voile est encore là.",
            "maman|Elle a attendu.",
            "narrateur|Une page tourne toute seule un peu.",
            "narrateur|Mila la rattrape.",
            "maman|Comme mercredi.",
            "enfant-f|Il ne tombe pas.",
            "maman|Tu le tiens.",
            "narrateur|Dimanche, elles lisent la dernière page.",
            "narrateur|Le bateau arrive au quai dessiné.",
            "enfant-f|Il est rentré.",
            "maman|Nous aussi.",
            "maman|C'est le week-end.",
            "enfant-f|Merci, maman.",
            "maman|Merci d'avoir choisi le bateau.",
            "narrateur|Le livre reste ouvert sur les genoux.",
            "narrateur|Le papier n'est plus froid.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le bateau est au quai.",
            "maman|Et le livre est avec nous.",
            "narrateur|La voile blanche tient encore la page.",
            "narrateur|Le canapé garde la chaleur du week-end.",
            "narrateur|Le papier sent un peu la maison.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("samedi", "Samedi et dimanche, c'est le week-end. Quels jours ?"),
)
relecture(
    "ATOM-TMP.SEM.002-03",
    "Le livre qui glisse",
    "Mercredi, Mila veut un livre de bateau. Il glisse. Elle le rattrape. Week-end : samedi et dimanche, la fin sur le canapé.",
    "D16 Mila, maman. Bibliothèque sans adulte nommé. Leçon mercredi/week-end greffée. Fin : voile, chaleur.",
)

# ---------------------------------------------------------------------------
# 04 N3 Nino, maman — mercredi + week-end plage, coquillage
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-04",
    "Nino veut un coquillage entier. Mercredi, le seau revient avec du sable. Le week-end, à la plage, une coquille entière tient dans sa paume.",
    "Le sel et la coquille",
    "Nino, maman",
    "petite plage mercredi, grande plage le week-end",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le sel colle déjà aux vitres.",
            "narrateur|Le vent sent le goémon, un peu fort.",
            "narrateur|Le sable crisse sous la première marche.",
            "maman|C'est mercredi, Nino.",
            "maman|Pas d'école.",
            "enfant-m|On va au bord ?",
            "maman|Oui.",
            "maman|La petite plage.",
            "enfant-m|Je veux un coquillage.",
            "maman|On cherche.",
            "narrateur|Nino porte un seau bleu.",
            "narrateur|Le seau tape sa jambe, toc toc.",
            "narrateur|En ce moment, il creuse près d'une vague.",
            "narrateur|L'eau revient trop vite.",
            "narrateur|Le trou se referme.",
            "enfant-m|Il part.",
            "maman|La mer reprend le sable.",
            "maman|On recule un peu ?",
            "enfant-m|Oui.",
            "narrateur|Il recule.",
            "narrateur|Ses chaussures ont un liseré blanc de sel.",
            "narrateur|Il fouille avec les doigts.",
            "narrateur|Un éclat cassé, rien d'entier.",
            "enfant-m|C'est cassé.",
            "maman|Mercredi, on a le temps court.",
            "maman|Samedi, on reviendra.",
            "enfant-m|La grande plage ?",
            "maman|La grande.",
            "maman|Samedi et dimanche, c'est le week-end.",
            "enfant-m|Pas d'école.",
            "maman|Pas d'école.",
            "maman|Comme mercredi.",
            "narrateur|Nino verse le sable dans le seau.",
            "narrateur|Ça fait chh, puis plus rien.",
            "enfant-m|Pas de coquille.",
            "maman|Du sable pour attendre.",
            "maman|Tu veux rincer tes mains ?",
            "enfant-m|Elles collent.",
            "narrateur|L'eau froide pique un peu.",
            "narrateur|Le sel reste dans les plis.",
            "maman|On rentre.",
            "enfant-m|Le seau vient.",
            "maman|Le seau vient.",
            "narrateur|Une mouette crie, très haut.",
            "narrateur|Nino lève le menton.",
            "maman|Elle a vu la mer.",
            "enfant-m|Moi aussi.",
            "maman|Samedi, tu verras plus loin.",
            "narrateur|Le seau est lourd de sable mouillé.",
            "narrateur|Une goutte tombe sur le bois de la marche.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino pose le seau près des chaussures.",
            "enfant-m|Samedi.",
            "enfant-m|Dimanche.",
            "maman|Oui.",
            "maman|C'est le week-end.",
            "maman|On cherchera encore.",
            "enfant-m|Une entière.",
            "maman|Une entière.",
            "narrateur|Il touche le sable du seau.",
            "narrateur|C'est froid, un peu lourd.",
            "maman|Mercredi a donné le sable.",
            "maman|Le week-end donnera la coquille.",
            "enfant-m|J'attends.",
            "maman|Tu as cherché.",
            "maman|Bravo.",
            "maman|Tu as reculé devant la vague ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le sel sèche en petits cristaux blancs.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Samedi, la grande plage est plus large.",
            "narrateur|Le vent pousse une odeur de goémon doux.",
            "enfant-m|Je cherche.",
            "maman|Près de la laisse de mer.",
            "narrateur|Nino s'agenouille.",
            "narrateur|Une coquille entière, rose au bord.",
            "enfant-m|Elle est entière !",
            "maman|Tu l'as.",
            "narrateur|Il la pose dans le seau, sur le sable.",
            "narrateur|Elle ne se casse pas.",
            "maman|Dimanche, on l'écoutera à la maison.",
            "enfant-m|La mer dedans ?",
            "maman|La mer dedans.",
            "maman|C'est le week-end.",
            "enfant-m|Merci, maman.",
            "maman|Merci d'avoir attendu samedi.",
            "narrateur|La coquille est tiède dans la paume.",
            "narrateur|Le sel brille encore sur le bord rose.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Je l'ai.",
            "maman|Elle est entière.",
            "narrateur|La coquille tient au creux de la main.",
            "narrateur|Un souffle de mer reste dans le trou.",
            "narrateur|Le seau bleu garde un peu de sable clair.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("week-end", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-04",
    "Le sel et la coquille",
    "Mercredi, Nino veut un coquillage. Le seau n'a que du sable. Week-end, grande plage : une coquille entière, rose.",
    "D16 Nino, maman. Pas d'autre adulte. Leçon mercredi/week-end. Imprévu : vague, coquille cassée. Fin : souffle dans la coquille.",
)

# ---------------------------------------------------------------------------
# 05 N3 Nina, papa — mercredi gâteau, dimanche cerf-volant
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-05",
    "Nina veut un gâteau, puis le cerf-volant. Mercredi, la farine fait un nuage. Ils essuient. Dimanche, week-end, le vent prend enfin la toile.",
    "La farine et le vent",
    "Nina, papa",
    "cuisine mercredi, colline dimanche",
    {
        "CHK_T0000_P0000": [
            "narrateur|La farine a fait un nuage blanc.",
            "narrateur|Elle retombe sur le bois de la table.",
            "narrateur|Ça sent le beurre tiède, déjà.",
            "papa|C'est mercredi, Nina.",
            "papa|Pas d'école.",
            "enfant-f|On fait le gâteau ?",
            "papa|Oui.",
            "papa|Pour dimanche.",
            "enfant-f|Le cerf-volant aussi ?",
            "papa|Dimanche, s'il y a du vent.",
            "papa|Samedi et dimanche, c'est le week-end.",
            "narrateur|Nina verse encore un peu de farine.",
            "narrateur|Le nuage revient, plus petit.",
            "enfant-f|Oh.",
            "papa|Trop d'un coup.",
            "papa|On essuie ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, Nina passe le linge.",
            "narrateur|La farine part en traînées blanches.",
            "papa|Tu fais une place nette.",
            "enfant-f|Pour le bol.",
            "papa|Pour le bol.",
            "narrateur|Le bol est lourd, en terre.",
            "narrateur|Nina le pose sans le faire sonner.",
            "papa|Bien.",
            "papa|L'œuf maintenant.",
            "narrateur|L'œuf casse net.",
            "narrateur|Le jaune tient, puis glisse.",
            "enfant-f|Il est orange.",
            "papa|Comme le cerf-volant.",
            "enfant-f|Le grand.",
            "papa|Le grand, dimanche.",
            "narrateur|Ils mélangent.",
            "narrateur|La pâte devient collante, puis lisse.",
            "papa|Tu veux lécher la cuillère ?",
            "enfant-f|Un peu.",
            "narrateur|C'est sucré, un peu rêche encore.",
            "papa|Mercredi, on cuit.",
            "papa|Samedi, il sera froid.",
            "papa|Dimanche, le vent.",
            "enfant-f|Pas d'école.",
            "papa|Pas d'école.",
            "papa|Comme mercredi.",
            "narrateur|Le four souffle un air chaud.",
            "narrateur|Nina s'éloigne d'un pas.",
            "papa|On regarde par la vitre.",
            "enfant-f|Il gonfle.",
            "papa|Il gonfle.",
            "narrateur|Une miette de farine reste sur le nez de Nina.",
            "papa|Là.",
            "narrateur|Papa l'essuie du pouce.",
            "enfant-f|Merci.",
            "papa|Merci d'avoir essuyé la table.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nina sent encore le beurre sur ses doigts.",
            "enfant-f|Samedi.",
            "enfant-f|Dimanche.",
            "papa|Oui.",
            "papa|C'est le week-end.",
            "papa|Le gâteau, puis le vent.",
            "enfant-f|Le cerf-volant.",
            "papa|Dimanche.",
            "narrateur|Le gâteau dore derrière la vitre.",
            "narrateur|Une bulle se fige au milieu.",
            "papa|Tu as versé trop vite, puis tu as essuyé.",
            "papa|Bravo.",
            "enfant-f|Le nuage est parti.",
            "papa|La table est nette.",
            "papa|On attend qu'il descende ?",
            "enfant-f|Oui, papa.",
            "narrateur|La cuisine sent le chaud et le sucre.",
            "narrateur|Le linge blanc a une trace de farine.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Dimanche, le vent tire déjà les herbes.",
            "narrateur|Nina tient le gâteau dans un linge.",
            "enfant-f|Une part pour après.",
            "papa|Après le ciel.",
            "narrateur|Le cerf-volant orange claque une fois.",
            "narrateur|Le fil brûle un peu la main, puis non.",
            "papa|Tu cours dans l'herbe ?",
            "enfant-f|Dans l'herbe.",
            "narrateur|La toile s'élève.",
            "narrateur|Elle penche, puis elle tient.",
            "enfant-f|Il vole !",
            "papa|Comme mercredi le gâteau a gonflé.",
            "papa|C'est le week-end.",
            "enfant-f|Samedi il était froid.",
            "papa|Et dimanche il y a le vent.",
            "papa|Tu tiens bien le fil ?",
            "enfant-f|Oui.",
            "narrateur|Une miette sucrée reste au coin de la bouche.",
            "narrateur|Le ciel tire l'orange tout en haut.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le cerf-volant tient.",
            "papa|Le gâteau aussi, dans le linge.",
            "narrateur|L'orange claque au-dessus de l'herbe.",
            "narrateur|Le fil vibre un peu entre les doigts.",
            "narrateur|Le vent sent encore le sucre du gâteau.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("samedi", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-05",
    "La farine et le vent",
    "Mercredi, Nina fait un gâteau. La farine fait un nuage. Elle essuie. Dimanche, week-end, le cerf-volant orange tient.",
    "D16 Nina, papa. Leçon mercredi/week-end. Imprévu : farine. Fin : fil, sucre, vent.",
)

# ---------------------------------------------------------------------------
# 06 N3 Raphaël, maman — mercredi train miniature, samedi vrai quai
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-06",
    "Raphaël veut voir un vrai train. Mercredi, un wagon déraille sur la table. Ils le remettent. Samedi, week-end, ils regardent depuis le quai, la main dans la main.",
    "Le wagon et le vrai quai",
    "Raphaël, maman",
    "salon mercredi, quai de gare samedi",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le petit train sent le bois et l'huile.",
            "narrateur|Un rail fait un cercle sur la table.",
            "narrateur|La moquette avale un écrou minuscule.",
            "maman|C'est mercredi, Raphaël.",
            "maman|Pas d'école.",
            "enfant-m|On fait le tour ?",
            "maman|Oui.",
            "maman|Tout doux.",
            "enfant-m|Samedi, le vrai ?",
            "maman|Samedi, on ira au quai.",
            "maman|On regardera avec moi.",
            "maman|Samedi et dimanche, c'est le week-end.",
            "narrateur|En ce moment, Raphaël pousse le wagon rouge.",
            "narrateur|Le wagon saute le rail.",
            "narrateur|Il tombe sur le bois, toc.",
            "enfant-m|Il est tombé.",
            "maman|Le virage était trop vite.",
            "maman|On le remet ?",
            "enfant-m|Oui.",
            "narrateur|Il ramasse le wagon.",
            "narrateur|Une petite roue tourne encore dans le vide.",
            "maman|Tu la clipses.",
            "narrateur|Ça fait clic.",
            "enfant-m|Il tient.",
            "maman|Maintenant plus lent.",
            "narrateur|Le train reprend le cercle.",
            "narrateur|Le bois vibre un peu sous les rails.",
            "enfant-m|Il va à la gare.",
            "maman|Notre gare, samedi.",
            "enfant-m|Le vrai quai.",
            "maman|Le vrai quai.",
            "maman|On reste dessus.",
            "maman|On tient la main.",
            "enfant-m|Pas tout seul.",
            "maman|Pas tout seul.",
            "narrateur|Un tunnel de carton attend au bout.",
            "narrateur|Le train y entre, disparaît.",
            "enfant-m|Il est caché.",
            "maman|Il revient.",
            "narrateur|Le wagon rouge ressort, plus calme.",
            "maman|Mercredi, le petit.",
            "maman|Samedi, le grand.",
            "enfant-m|Pas d'école.",
            "maman|Pas d'école.",
            "maman|Comme mercredi.",
            "narrateur|Raphaël souffle sur le rail.",
            "narrateur|Un peu de poussière part.",
            "maman|Tu prépares la voie.",
            "enfant-m|Pour le vrai.",
            "maman|Le vrai a des rails plus gros.",
            "maman|On les regardera du quai.",
            "narrateur|Le petit train s'arrête près du bol.",
            "narrateur|L'huile sent encore, très fin.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël aligne le wagon contre la motrice.",
            "enfant-m|Samedi.",
            "enfant-m|Dimanche.",
            "maman|Oui.",
            "maman|C'est le week-end.",
            "maman|Samedi, le quai.",
            "enfant-m|On tient la main.",
            "maman|On tient la main.",
            "maman|On reste sur le quai.",
            "narrateur|Il caresse le toit rouge.",
            "narrateur|Le bois est lisse, un peu chaud.",
            "maman|Tu as remis la roue.",
            "maman|Bravo.",
            "enfant-m|Clic.",
            "maman|Clic.",
            "maman|Il peut dormir jusqu'à samedi ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le cercle de rails garde une trace d'huile.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Samedi, le quai sent le fer chaud.",
            "narrateur|Une ligne jaune court au bord.",
            "maman|On s'arrête ici.",
            "maman|Derrière la ligne.",
            "enfant-m|Je tiens ta main.",
            "maman|Oui.",
            "narrateur|Un vent arrive avant le train.",
            "narrateur|Les cheveux de Raphaël bougent.",
            "enfant-m|Je le vois !",
            "maman|Le grand.",
            "narrateur|Le train passe, long, profond.",
            "narrateur|Le quai vibre sous les semelles.",
            "enfant-m|Comme la table.",
            "maman|Plus fort.",
            "maman|C'est le week-end.",
            "enfant-m|Merci, maman.",
            "maman|Merci d'être resté avec moi.",
            "narrateur|Le petit wagon, à la maison, attend le cercle.",
            "narrateur|Une odeur de fer reste dans le manteau.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|J'ai vu le vrai.",
            "maman|Depuis le quai.",
            "narrateur|La ligne jaune est encore sous les yeux.",
            "narrateur|La main de maman est chaude.",
            "narrateur|Le manteau garde le vent du train.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("samedi", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-06",
    "Le wagon et le vrai quai",
    "Mercredi, Raphaël pousse le train. Un wagon déraille. Il clips la roue. Samedi, week-end, vrai quai, main dans la main, derrière la ligne.",
    "D16 Raphaël, maman. POS-001 : rester sur le quai, tenir la main, pas de course. Leçon mercredi/week-end. Fin : vent dans le manteau.",
)

# ---------------------------------------------------------------------------
# 07 N2 Chouchou, maman — mercredi soupe, dimanche marché
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.SEM.002-07",
    "Chouchou veut une soupe orange. Mercredi, une carotte roule sous la table. Elle la rattrape. Dimanche, week-end, le marché sent les mêmes carottes.",
    "La vapeur et le marché",
    "Chouchou, maman",
    "cuisine mercredi, marché dimanche",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vapeur de soupe embue la vitre.",
            "narrateur|Un rond de jour flotte dans la buée.",
            "narrateur|Ça sent la carotte chaude.",
            "maman|C'est mercredi, Chouchou.",
            "maman|Pas d'école.",
            "enfant-f|On fait la soupe ?",
            "maman|Oui.",
            "maman|Tu peux la carotte.",
            "enfant-f|La grande.",
            "narrateur|Chouchou prend une carotte mouillée.",
            "narrateur|Elle glisse.",
            "narrateur|Elle roule sous la table.",
            "enfant-f|Elle part !",
            "maman|On la cherche ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, Chouchou se penche.",
            "narrateur|Le carrelage est froid aux genoux.",
            "narrateur|La carotte attend près du pied de chaise.",
            "enfant-f|Je l'ai.",
            "maman|Merci.",
            "maman|Elle voulait se cacher.",
            "narrateur|Chouchou la pose dans le saladier.",
            "narrateur|L'eau fait un petit ploc.",
            "maman|On coupe ensemble.",
            "enfant-f|Des ronds.",
            "maman|Des ronds orange.",
            "narrateur|Les ronds tombent, mous, luisants.",
            "maman|Mercredi, on cuisine.",
            "maman|Dimanche, on ira au marché.",
            "enfant-f|Pour d'autres carottes ?",
            "maman|Pour d'autres.",
            "maman|Samedi et dimanche, c'est le week-end.",
            "enfant-f|Pas d'école.",
            "maman|Pas d'école.",
            "maman|Comme mercredi.",
            "narrateur|La casserole chante un peu.",
            "narrateur|La vapeur sent plus fort.",
            "enfant-f|Je souffle.",
            "maman|Pas trop près.",
            "maman|On goûte plus tard.",
            "narrateur|Chouchou trace un soleil dans la buée.",
            "narrateur|Le doigt laisse une vitre claire.",
            "maman|Tu vois le jardin ?",
            "enfant-f|Un peu.",
            "maman|Samedi, on finira le bol.",
            "maman|Dimanche, le marché.",
            "enfant-f|J'attends dimanche.",
            "narrateur|Une goutte coule sur la carotte retrouvée.",
            "narrateur|Elle brille, toute propre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quels autres jours, comme mercredi, sans l'école ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou essuie ses genoux du plat de la main.",
            "enfant-f|Samedi.",
            "enfant-f|Dimanche.",
            "maman|Oui.",
            "maman|C'est le week-end.",
            "maman|Dimanche, les carottes du marché.",
            "enfant-f|Comme celle-là.",
            "maman|Comme celle que tu as rattrapée.",
            "narrateur|La soupe tourne, orange, épaisse.",
            "narrateur|Une bulle éclate, tout doux.",
            "maman|Tu as cherché sous la table.",
            "maman|Bravo.",
            "enfant-f|Elle roulait.",
            "maman|Et tu l'as eue.",
            "maman|On goûte ?",
            "enfant-f|Oui, maman.",
            "narrateur|La cuillère est chaude au bord des lèvres.",
            "narrateur|La carotte a un goût sucré.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Dimanche, le marché sent la terre mouillée.",
            "narrateur|Une caisse de carottes fume un peu au froid.",
            "enfant-f|Comme la soupe.",
            "maman|Comme mercredi.",
            "narrateur|Chouchou montre une botte orange.",
            "narrateur|Les fanes sont encore vertes, piquantes.",
            "maman|Celles-là ?",
            "enfant-f|Celles-là.",
            "maman|On les prend.",
            "narrateur|Le sac devient lourd, froid.",
            "enfant-f|Pour la prochaine soupe.",
            "maman|Pour la prochaine.",
            "maman|C'est le week-end.",
            "enfant-f|Merci, maman.",
            "maman|Merci d'avoir choisi.",
            "narrateur|Une carotte dépasse du sac.",
            "narrateur|Elle ne roule pas.",
            "enfant-f|Je la tiens.",
            "narrateur|Le marché sonne de cagettes et de voix.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|On a les carottes.",
            "maman|Comme mercredi, en plus grand.",
            "narrateur|Les fanes piquent un peu le poignet.",
            "narrateur|Le sac sent la terre et le sucré.",
            "narrateur|Une vapeur de soupe semble encore là.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_sem("samedi", "Samedi et dimanche. Comment on dit ?"),
)
relecture(
    "ATOM-TMP.SEM.002-07",
    "La vapeur et le marché",
    "Mercredi, Chouchou fait la soupe. Une carotte roule. Elle la rattrape. Dimanche, week-end, le marché rend les mêmes carottes.",
    "D16 Chouchou, maman, enfant-f. Pas de marchand nommé. Leçon mercredi/week-end. Fin : fanes, terre, vapeur.",
)

# ---------------------------------------------------------------------------
# VIV.ANI.001-01 N1 Aniss, papa — ferme, coq qui se tait
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.001-01",
    "Aniss veut entendre le coq. Le coq se tait. Une poule caquette. Puis le coq chante. Aniss a son cri.",
    "Le silence du coq",
    "Aniss, papa",
    "cour de ferme, foin, mur de pierre",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le foin pique les chaussures d'Aniss.",
            "narrateur|La cour sent le bois chaud.",
            "narrateur|Une barrière craque un peu.",
            "papa|Tu entends, Aniss ?",
            "enfant-m|Pas encore.",
            "enfant-m|Je veux le coq.",
            "papa|Le coq du mur ?",
            "enfant-m|Oui.",
            "enfant-m|Son chant.",
            "narrateur|Ils marchent dans la paille.",
            "narrateur|Ça croustille sous les pieds.",
            "narrateur|En ce moment, Aniss lève les yeux.",
            "narrateur|Le coq est sur le mur.",
            "narrateur|Il a des plumes rousses.",
            "narrateur|Il ne chante pas.",
            "enfant-m|Il se tait.",
            "papa|On attend ?",
            "enfant-m|Oui, papa.",
            "narrateur|Une poule arrive près du seau.",
            "narrateur|Elle caquette.",
            "narrateur|Cot cot cot.",
            "enfant-m|Ce n'est pas lui.",
            "papa|C'est la poule.",
            "papa|Elle parle d'abord.",
            "narrateur|Aniss serre la main de papa.",
            "narrateur|Le seau tremble un peu.",
            "narrateur|L'eau fait un cercle.",
            "narrateur|Le coq tourne la tête.",
            "narrateur|Il reste muet.",
            "enfant-m|Pourquoi ?",
            "papa|Il cherche son moment.",
            "papa|Tu restes ?",
            "enfant-m|Je reste.",
            "narrateur|La poule picore près des pieds.",
            "narrateur|Ses plumes sont chaudes de soleil.",
            "narrateur|Aniss ne bouge presque pas.",
            "papa|Tu es patient.",
            "enfant-m|J'écoute.",
            "narrateur|Un silence tient la cour.",
            "narrateur|Le foin sent plus fort.",
            "narrateur|Puis le coq gonfle le cou.",
            "narrateur|Il chante.",
            "narrateur|Cocorico.",
            "enfant-m|Le voilà !",
            "papa|Tu l'as entendu.",
            "papa|Merci d'avoir attendu.",
            "enfant-m|Encore ?",
            "papa|On écoute encore ?",
            "enfant-m|Oui.",
            "narrateur|Le coq se tait une seconde.",
            "narrateur|Puis il reprend.",
            "narrateur|Cocorico.",
            "enfant-m|C'est son cri.",
            "papa|Oui.",
            "papa|Le cri du coq.",
            "narrateur|La poule caquette plus bas.",
            "narrateur|Elle n'est plus la première.",
            "papa|Tu voulais le coq.",
            "enfant-m|Je l'ai.",
            "narrateur|Une plume rousse tombe près du seau.",
            "narrateur|Aniss la regarde, sans la prendre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quel est le cri du coq ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Aniss lève encore le menton.",
            "enfant-m|Cocorico.",
            "papa|Oui.",
            "papa|Le coq chante cocorico.",
            "papa|Bravo.",
            "enfant-m|La poule, cot cot.",
            "papa|La poule d'abord.",
            "papa|Puis le coq.",
            "narrateur|Le mur de pierre est chaud.",
            "narrateur|Les plumes rousses brillent.",
            "papa|Tu as attendu.",
            "enfant-m|Il s'était tu.",
            "papa|Puis il a parlé.",
            "papa|Tu l'entends encore ?",
            "enfant-m|Un peu.",
            "narrateur|Un dernier cocorico part vers le champ.",
            "narrateur|Il s'amincit, puis plus rien.",
            "papa|Il a chanté pour toi.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils redescendent la cour.",
            "narrateur|Le foin pique encore.",
            "enfant-m|J'ai son cri.",
            "papa|Cocorico.",
            "enfant-m|Cocorico.",
            "narrateur|La poule suit un moment.",
            "narrateur|Puis elle s'arrête au seau.",
            "papa|Elle reste ici.",
            "enfant-m|Le coq aussi.",
            "papa|Sur le mur.",
            "narrateur|Aniss se retourne.",
            "narrateur|Le coq est une tache rousse.",
            "papa|Tu veux la plume ?",
            "enfant-m|Oui.",
            "narrateur|Il la prend, toute légère.",
            "papa|Merci d'avoir écouté.",
            "narrateur|La plume chatouille sa paume.",
            "narrateur|La cour sent le bois et l'eau.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le coq a chanté.",
            "papa|Tu l'as entendu.",
            "narrateur|La plume rousse tremble dans la main.",
            "narrateur|Un peu de foin reste sur la chaussure.",
            "narrateur|Le mur garde encore le soleil du coq.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "cocorico",
        "accepted_examples": "cocorico | il chante | coq | le coq | chante | son cri",
        "retry_prompt": "Le coq chante cocorico. Quel est son cri ?",
    },
)
relecture(
    "ATOM-VIV.ANI.001-01",
    "Le silence du coq",
    "Aniss veut le chant du coq. Le coq se tait. Une poule caquette. Puis cocorico. Une plume rousse dans la main.",
    "D16 Aniss, papa. N1. Pas de liste d'animaux. Question : cri du coq. Fin : plume, foin, mur. Pas « L'histoire est finie ».",
)
