#!/usr/bin/env python3
"""F-NAR-008 — ATOM-VIV.ANI.002-01..08 (noms greffés dans une quête)."""
from __future__ import annotations

from _lib import relecture, write_story


def q_petit(attendu: str, indice: str) -> dict:
    return {
        "expected_answer": attendu,
        "accepted_examples": f"{attendu} | le {attendu} | un {attendu}",
        "retry_prompt": indice,
    }


# ---------------------------------------------------------------------------
# 01 N1 Sarah, maman — ferme, chèvre derrière la paille
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-01",
    "Sarah veut parler à la chèvre. Elle voit une poule, puis une vache. La chèvre est derrière le tas de paille, avec le chevreau. Sarah l'appelle, tout doux.",
    "La chèvre derrière la paille",
    "Sarah, maman",
    "ferme, cour, tas de paille, rosée",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sur le toit de la grange, la rosée brille.",
            "narrateur|Elle fait des perles toutes petites.",
            "narrateur|La cour sent le foin tiède.",
            "narrateur|Un seau de zinc brille près du puits.",
            "narrateur|Sarah vit ici, avec maman.",
            "narrateur|Les bottes attendent près de la porte.",
            "narrateur|Elles sont encore un peu humides.",
            "enfant-f|Maman, je veux voir la chèvre.",
            "maman|La chèvre du fond ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux lui parler.",
            "narrateur|En ce moment, Sarah prend sa veste.",
            "narrateur|La veste sent encore le foin.",
            "maman|On va la chercher ensemble ?",
            "enfant-f|Oui, maman.",
            "narrateur|Maman ouvre la porte de la cour.",
            "narrateur|L'air sent la paille chaude.",
            "narrateur|Un peu de poussière dore le soleil.",
            "narrateur|Sarah marche près de maman.",
            "narrateur|Une poule rouge picore près du portail.",
            "enfant-f|Une poule !",
            "maman|Oui.",
            "maman|Elle picore le grain.",
            "narrateur|Sarah s'arrête un peu.",
            "narrateur|Elle regarde la poule, tout doux.",
            "narrateur|Puis elle reprend le chemin.",
            "narrateur|Plus loin, une vache lèche une pierre.",
            "enfant-f|Une vache !",
            "maman|Oui, Sarah.",
            "maman|Elle lèche le sel.",
            "narrateur|Sarah pose la main sur la clôture.",
            "narrateur|Le bois est chaud, un peu rêche.",
            "enfant-f|La chèvre est où ?",
            "maman|On va au pré ?",
            "narrateur|Le pré est vide, tout calme.",
            "narrateur|L'herbe est rase, encore mouillée.",
            "enfant-f|Elle n'est pas là.",
            "maman|On écoute ?",
            "narrateur|Sarah tend l'oreille.",
            "narrateur|Un bêlement vient de derrière.",
            "enfant-f|J'entends !",
            "maman|Derrière le tas de paille ?",
            "enfant-f|Oui !",
            "narrateur|Le tas de paille est haut.",
            "narrateur|Il sent le blé chaud.",
            "narrateur|Sarah tourne autour, tout doucement.",
            "narrateur|Des brins collent à sa veste.",
            "narrateur|Derrière le tas, deux oreilles bougent.",
            "enfant-f|La chèvre !",
            "narrateur|La chèvre lèche un petit chevreau.",
            "maman|Tu vois le petit ?",
            "enfant-f|Le chevreau.",
            "maman|Oui.",
            "maman|Bouc, chèvre, chevreau.",
            "maman|Trois noms de la famille.",
            "narrateur|Sarah s'accroupit près de maman.",
            "enfant-f|Bonjour, chèvre.",
            "narrateur|La chèvre avance un peu.",
            "narrateur|Son poil est rêche, tout chaud.",
            "enfant-f|Je te parlais.",
            "maman|Elle t'écoute, Sarah.",
            "maman|Tu lui parles tout doux.",
            "narrateur|Sarah pose sa voix tout bas.",
            "enfant-f|Tu étais derrière la paille.",
            "maman|Merci d'avoir écouté, Sarah.",
            "maman|Tu as trouvé la chèvre.",
            "enfant-f|Avec le chevreau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Derrière le tas de paille, qui est là ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La chèvre reste derrière la paille.",
            "narrateur|Le chevreau tète encore.",
            "enfant-f|Il est tout petit.",
            "maman|Oui.",
            "maman|C'est le petit de la chèvre.",
            "narrateur|Sarah tend un brin de foin.",
            "narrateur|La chèvre le prend, tout calme.",
            "maman|Tu lui parles encore ?",
            "enfant-f|Oui.",
            "enfant-f|Elle m'écoute.",
            "narrateur|Un brin d'or colle à sa manche.",
            "maman|On reste un peu ?",
            "enfant-f|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils redescendent vers la cour.",
            "narrateur|La poule picore encore.",
            "narrateur|La vache lèche encore la pierre.",
            "enfant-f|Je les ai vues.",
            "maman|La poule, la vache, la chèvre.",
            "enfant-f|Et le chevreau.",
            "maman|Tu lui as parlé ?",
            "enfant-f|Oui.",
            "narrateur|Sarah se retourne une fois.",
            "narrateur|Le tas de paille cache encore les oreilles.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Elle mâche, maman.",
            "maman|Tout près de toi.",
            "narrateur|La chèvre mâche encore, tout près.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("chèvre", "C'est la chèvre. Qui est derrière la paille ?"),
)
relecture(
    "ATOM-VIV.ANI.002-01",
    "La chèvre derrière la paille",
    "Sarah cherche la chèvre pour lui parler. Poule et vache sur le chemin. Chèvre et chevreau derrière le tas.",
    "Noms greffés dans la quête. Pas de liste. Fin vécue, pas « L'histoire est finie ».",
)


# ---------------------------------------------------------------------------
# 02 N3 Amir, maman — livre d'images, puis vraie basse-cour
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-02",
    "Amir veut voir dehors les trois bêtes de son livre. Une page est déchirée ; ils la lissent. Coq, poule et poussin picorent vraiment dans la cour.",
    "Les bêtes du livre",
    "Amir, maman",
    "cuisine, livre d'images, puis basse-cour",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une tache jaune glisse sur la page ouverte.",
            "narrateur|Elle s'arrête sur la crête du coq.",
            "narrateur|La table sent encore la confiture.",
            "narrateur|Un peu de sucre colle au bois.",
            "narrateur|Amir vit ici, avec maman.",
            "narrateur|Le livre d'images est trop grand pour ses genoux.",
            "enfant-m|Maman, ils sont où, les vrais ?",
            "maman|Les bêtes du livre ?",
            "enfant-m|Le coq, la poule, le poussin.",
            "maman|On peut aller les voir dehors.",
            "narrateur|En ce moment, Amir tourne une page.",
            "narrateur|Le papier râpe un peu sous son pouce.",
            "narrateur|Un coin se lève, tout fin, tout blanc.",
            "enfant-m|Oh.",
            "enfant-m|Elle est déchirée.",
            "maman|On la lisse ensemble ?",
            "narrateur|Maman pose sa main à côté de la sienne.",
            "narrateur|Ils recollent le coin, tout doucement.",
            "narrateur|Le coq du livre redevient entier.",
            "enfant-m|Il est réparé.",
            "maman|Merci, Amir.",
            "maman|Tu as été très doux avec la page.",
            "maman|Tu veux encore le livre, ou la cour ?",
            "enfant-m|La cour.",
            "enfant-m|Les vrais.",
            "narrateur|Ils laissent le livre ouvert sur la table.",
            "narrateur|La tache de soleil reste sur le coq.",
            "narrateur|Maman ouvre la porte vers la basse-cour.",
            "narrateur|L'air sent le grain et la terre chaude.",
            "narrateur|Un grillage vibre un peu au vent.",
            "narrateur|Amir marche près de maman, sans courir.",
            "narrateur|Près de l'abreuvoir, un coq secoue sa crête.",
            "enfant-m|Le coq du livre !",
            "maman|Oui.",
            "maman|C'est le coq.",
            "narrateur|Une poule rousse picore juste derrière.",
            "enfant-m|La poule aussi.",
            "maman|Tu la vois bien ?",
            "enfant-m|Oui.",
            "narrateur|Un poussin jaune trottine entre les pattes.",
            "enfant-m|Le poussin !",
            "maman|Coq, poule, poussin.",
            "maman|Trois noms de la famille.",
            "narrateur|Amir s'accroupit près du grillage.",
            "narrateur|Le poussin picore une miette de son ombre.",
            "enfant-m|Ils sont dehors, maman.",
            "maman|Comme dans le livre.",
            "maman|Sauf que ceux-là respirent.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Les trois bêtes du livre, elles sont où ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le coq chante une note courte.",
            "narrateur|La poule rentre un peu sous son aile le poussin.",
            "enfant-m|Il est tout petit.",
            "maman|Oui.",
            "maman|C'est le petit de la poule.",
            "maman|Tu te souviens de la page ?",
            "enfant-m|On l'a lissée.",
            "narrateur|Un peu de poussière dore encore le grillage.",
            "maman|On reste regarder ?",
            "enfant-m|Encore un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils rentrent vers la cuisine.",
            "narrateur|Le livre attend, ouvert, sur la table.",
            "narrateur|La page lissée tient encore.",
            "enfant-m|Le coq du papier est entier.",
            "maman|Et le coq dehors a chanté.",
            "maman|Tu as vu les trois ?",
            "enfant-m|Coq, poule, poussin.",
            "narrateur|Amir pose un doigt sur le papier réparé.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Ils picorent vraiment.",
            "maman|Dehors, dans la lumière.",
            "narrateur|Les trois bêtes picorent dans la poussière d'or.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "dehors",
        "accepted_examples": "dehors | dans la cour | à la basse-cour | la cour",
        "retry_prompt": "Elles sont dehors. Où sont les trois bêtes ?",
    },
)
relecture(
    "ATOM-VIV.ANI.002-02",
    "Les bêtes du livre",
    "Amir veut les bêtes du livre dehors. Page déchirée lissée. Coq, poule, poussin dans la cour.",
    "N3. Leçon greffée (famille du coq) dans la quête. Fin sensorielle.",
)


# ---------------------------------------------------------------------------
# 03 N2 Mila, papa — ferme, poulain, barrière
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-03",
    "Mila veut parler au poulain. Cheval et jument sont au pré. La barrière est fermée. Papa l'ouvre avec elle. Le poulain souffle dans sa paume.",
    "Le poulain derrière la barrière",
    "Mila, papa",
    "ferme, pré, barrière de bois",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le portail peint sent encore le soleil.",
            "narrateur|La peinture est chaude sous les doigts.",
            "narrateur|Un peu de poussière blonde vole au vent.",
            "narrateur|Mila vit ici, avec papa.",
            "narrateur|Ses bottes font un bruit mou dans la terre.",
            "enfant-f|Papa, je veux voir le poulain.",
            "papa|Le petit du pré ?",
            "enfant-f|Oui.",
            "enfant-f|Je veux lui parler.",
            "narrateur|En ce moment, ils marchent vers le pré.",
            "narrateur|L'herbe sent le foin coupé.",
            "narrateur|Un cheval brun broute près du chêne.",
            "enfant-f|Le cheval !",
            "papa|Oui, Mila.",
            "papa|Il mange tout calme.",
            "narrateur|Une jument grise gratte le sol.",
            "enfant-f|La jument aussi.",
            "papa|Tu les vois bien ?",
            "enfant-f|Oui.",
            "enfant-f|Le poulain est où ?",
            "papa|Derrière la barrière, peut-être.",
            "narrateur|La barrière de bois est fermée.",
            "narrateur|Les lattes sentent la résine chaude.",
            "narrateur|Mila pose le front entre deux lattes.",
            "narrateur|Elle ne voit que l'ombre.",
            "enfant-f|Je ne le vois pas.",
            "papa|On ouvre ensemble ?",
            "enfant-f|Oui, papa.",
            "narrateur|Papa soulève le loquet de fer.",
            "narrateur|Mila tient le bois, tout près.",
            "narrateur|La barrière grince un tout petit peu.",
            "narrateur|Dans l'ombre, un poulain avance.",
            "enfant-f|Le poulain !",
            "papa|Cheval, jument, poulain.",
            "papa|Trois noms de la famille.",
            "narrateur|Le poulain souffle contre la main de Mila.",
            "narrateur|L'air est chaud, un peu humide.",
            "enfant-f|Bonjour, petit.",
            "papa|Tu lui parles tout doux.",
            "papa|Merci d'avoir attendu la barrière.",
            "enfant-f|Il sent le foin.",
            "narrateur|La jument s'approche, sans se presser.",
            "narrateur|Elle gratte encore une fois le sol.",
            "enfant-f|Elle le garde.",
            "papa|Oui.",
            "papa|Le petit reste près d'elle.",
            "narrateur|Mila laisse sa main ouverte.",
            "narrateur|Le poil du nez est velours.",
            "enfant-f|Ça chatouille.",
            "papa|On reste de ce côté du bois ?",
            "enfant-f|Oui, papa.",
            "narrateur|Une mouche tourne dans le rai de soleil.",
            "narrateur|Le cheval brun lève un peu la tête.",
            "enfant-f|Il nous a vus.",
            "papa|Il broute encore.",
            "narrateur|Mila pose l'oreille contre une latte.",
            "narrateur|Le bois sent la résine, et le souffle.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Derrière la barrière, qui attend ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le poulain reste près de la latte.",
            "narrateur|Sa crinière est courte, encore en brosse.",
            "enfant-f|Elle pique un peu.",
            "papa|Oui.",
            "papa|C'est le petit de la jument.",
            "papa|On reste de ce côté ?",
            "enfant-f|Oui.",
            "narrateur|Mila laisse sa paume ouverte.",
            "narrateur|Le poulain y pose le nez.",
            "enfant-f|Il me parle aussi.",
            "papa|Tu entends son souffle ?",
            "enfant-f|Oui.",
            "enfant-f|Il est chaud.",
            "narrateur|Une paille blonde colle à sa botte.",
            "papa|On la laisse au pré.",
            "narrateur|Le poulain recule d'un pas, puis revient.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa referme le loquet, tout doux.",
            "narrateur|La barrière retrouve son bois chaud.",
            "enfant-f|Le cheval broute encore.",
            "papa|La jument aussi.",
            "papa|Tu as vu les trois ?",
            "enfant-f|Cheval, jument, poulain.",
            "narrateur|Mila garde l'odeur du souffle dans la main.",
            "papa|Tes doigts sentent le pré.",
            "enfant-f|Et le poulain.",
            "narrateur|Le loquet de fer est redevenu froid.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Il a soufflé, papa.",
            "papa|Dans ta paume.",
            "narrateur|Le poulain souffle encore contre le bois.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("poulain", "C'est le poulain. Qui attend derrière la barrière ?"),
)
relecture(
    "ATOM-VIV.ANI.002-03",
    "Le poulain derrière la barrière",
    "Mila veut le poulain. Barrière fermée. Papa ouvre avec elle. Souffle dans la paume.",
    "N2. Famille cheval greffée. Pas de franchissement dangereux.",
)


# ---------------------------------------------------------------------------
# 04 N2 Nino, maman — jardin du soir, hérisson sous les feuilles
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-04",
    "Nino veut trouver le hérisson du soir. Il voit le chat, puis le merle. Le hérisson est sous les feuilles. Nino les soulève tout doux.",
    "Le hérisson sous les feuilles",
    "Nino, maman",
    "jardin au crépuscule, tas de feuilles",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le ciel du jardin vire au violet.",
            "narrateur|L'air sent la terre encore chaude.",
            "narrateur|Un dernier rayon couche le cerisier.",
            "narrateur|Nino vit ici, avec maman.",
            "narrateur|Ses chaussettes sont un peu humides d'herbe.",
            "enfant-m|Maman, je veux voir le hérisson.",
            "maman|Celui du soir ?",
            "enfant-m|Oui.",
            "enfant-m|Il vient quand il fait doux.",
            "narrateur|En ce moment, ils marchent entre les tomates.",
            "narrateur|Les feuilles sentent le vert coupé.",
            "narrateur|Un chat gris dort sur la pierre chaude.",
            "enfant-m|Le chat !",
            "maman|Oui, Nino.",
            "maman|Il garde le dernier soleil.",
            "narrateur|Plus loin, un merle picore sous le cerisier.",
            "enfant-m|Un merle !",
            "maman|Tu l'entends ?",
            "enfant-m|Il fait un cri court.",
            "narrateur|Nino avance vers le tas de feuilles.",
            "narrateur|Les feuilles sont sèches, couleur cuivre.",
            "enfant-m|Le hérisson n'est pas là.",
            "maman|On cherche dessous ?",
            "narrateur|Nino s'accroupit près de maman.",
            "narrateur|Il soulève une feuille, tout doux.",
            "narrateur|Puis une autre.",
            "narrateur|Rien, sauf une odeur de terre.",
            "enfant-m|Il est où ?",
            "maman|Encore une poignée ?",
            "narrateur|Sous la troisième poignée, quelque chose roule.",
            "narrateur|Un petit dos piquant se serre.",
            "enfant-m|Le hérisson !",
            "maman|Chat, merle, hérisson.",
            "maman|Trois noms, ce soir.",
            "maman|Et le petit du chat, c'est le chaton.",
            "maman|Trois noms de la famille, pour le chat.",
            "narrateur|Le hérisson ne bouge presque plus.",
            "enfant-m|Bonjour, tout doux.",
            "maman|On le laisse sous les feuilles ?",
            "enfant-m|Oui.",
            "maman|Merci d'avoir soulevé tout doucement.",
            "narrateur|Nino repose deux feuilles en toit.",
            "narrateur|Le hérisson disparaît presque.",
            "enfant-m|Il a des piquants courts.",
            "maman|Oui.",
            "maman|On ne les touche pas.",
            "narrateur|Un grillon commence, tout près.",
            "narrateur|Le cerisier perd une dernière lueur.",
            "enfant-m|Le chat dort encore.",
            "maman|Le merle est parti.",
            "narrateur|Nino garde les mains ouvertes, au-dessus.",
            "maman|Tu lui as parlé tout bas ?",
            "enfant-m|Oui, maman.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sous les feuilles, qui se cache ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino repose les feuilles une à une.",
            "narrateur|Le hérisson reste un dôme piquant.",
            "enfant-m|Il a un nez pointu.",
            "maman|Oui.",
            "maman|On le regarde sans le prendre.",
            "maman|Tu as vu le chat, aussi ?",
            "enfant-m|Et le merle.",
            "narrateur|Le ciel devient plus bleu, plus sombre.",
            "maman|On reste encore une minute ?",
            "enfant-m|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils reculent vers le cerisier.",
            "narrateur|Le merle s'est tu.",
            "narrateur|Le chat ouvre un œil, puis le referme.",
            "enfant-m|Le hérisson dort.",
            "maman|Sous sa couverture de feuilles.",
            "maman|Tu lui as parlé ?",
            "enfant-m|Tout bas.",
            "narrateur|Nino garde une feuille cuivre dans la main.",
            "maman|Elle sent encore la terre.",
            "enfant-m|Comme le hérisson.",
            "narrateur|Le violet du ciel devient presque bleu nuit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Il est au chaud.",
            "maman|Sous les feuilles.",
            "narrateur|Les feuilles bougent encore, tout doux.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("hérisson", "C'est le hérisson. Qui se cache sous les feuilles ?"),
)
relecture(
    "ATOM-VIV.ANI.002-04",
    "Le hérisson sous les feuilles",
    "Nino cherche le hérisson du soir. Chat et merle vus. Hérisson sous les feuilles, soulevé tout doux.",
    "N2. Noms greffés. Famille du chat dite une fois. Pas de prise de l'animal.",
)


# ---------------------------------------------------------------------------
# 05 N1 Nina, papa — jardin après la pluie, escargot
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-05",
    "Nina veut trouver l'escargot après la pluie. Elle voit une poule, puis un chat. L'escargot brille sur une feuille. Nina le salue, tout doux.",
    "L'escargot après la pluie",
    "Nina, papa",
    "jardin après la pluie, gouttière, laitue",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une goutte quitte encore la gouttière.",
            "narrateur|Elle tombe dans une flaque ronde.",
            "narrateur|Le jardin sent la terre mouillée.",
            "narrateur|Les laitues brillent, toutes vertes.",
            "narrateur|Nina vit ici, avec papa.",
            "narrateur|Ses bottes jaunes font un bruit mou.",
            "enfant-f|Papa, je veux l'escargot.",
            "papa|Celui de la pluie ?",
            "enfant-f|Oui.",
            "enfant-f|Il laisse un fil d'argent.",
            "narrateur|En ce moment, Nina prend la main de papa.",
            "narrateur|L'herbe est froide, un peu haute.",
            "narrateur|Une poule mouillée picore près du bac.",
            "enfant-f|Une poule !",
            "papa|Oui, Nina.",
            "papa|Elle cherche des vers.",
            "narrateur|Nina la regarde, puis avance.",
            "narrateur|Un chat gris se lèche sur le muret.",
            "enfant-f|Un chat !",
            "papa|Il n'aime pas l'eau.",
            "narrateur|Nina cherche le fil d'argent.",
            "narrateur|Les feuilles sont trop brillantes.",
            "enfant-f|Je ne le vois pas.",
            "papa|On regarde la laitue ?",
            "narrateur|Papa soulève une grande feuille.",
            "narrateur|Nina regarde dessous.",
            "narrateur|Rien, sauf une goutte.",
            "enfant-f|Encore.",
            "narrateur|Sous la deuxième feuille, un point brun.",
            "narrateur|Une coquille luisante avance très lentement.",
            "enfant-f|L'escargot !",
            "papa|Poule, chat, escargot.",
            "papa|Tu les as vus.",
            "papa|Le petit de la poule, c'est le poussin.",
            "papa|Trois noms de la famille.",
            "narrateur|Nina s'accroupit près de la feuille.",
            "enfant-f|Bonjour, tout doux.",
            "narrateur|L'escargot sort deux cornes minuscules.",
            "papa|Il te salue, Nina.",
            "papa|Merci d'avoir cherché sans le prendre.",
            "enfant-f|Il brille.",
            "narrateur|Nina suit le fil d'argent des yeux.",
            "narrateur|Il va d'une nervure à l'autre.",
            "enfant-f|Il va tout seul.",
            "papa|Oui.",
            "papa|Sans qu'on le porte.",
            "narrateur|La poule secoue une goutte de l'aile.",
            "narrateur|Le chat se lèche encore, plus loin.",
            "enfant-f|Ils ne le voient pas.",
            "papa|Toi, tu l'as trouvé.",
            "narrateur|Nina pose un doigt à côté, pas dessus.",
            "papa|Tu restes tout doux ?",
            "enfant-f|Oui, papa.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Après la pluie, qui Nina cherche-t-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'escargot avance sur la nervure.",
            "narrateur|Le fil d'argent suit derrière.",
            "enfant-f|Il est tout lent.",
            "papa|Oui.",
            "papa|On le laisse sur sa feuille.",
            "papa|Tu as vu la poule, aussi ?",
            "enfant-f|Et le chat.",
            "narrateur|Une goutte tombe encore, tout près.",
            "papa|On reste regarder ?",
            "enfant-f|Oui, papa.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils reculent vers la gouttière.",
            "narrateur|La poule secoue une aile mouillée.",
            "narrateur|Le chat bâille sur le muret.",
            "enfant-f|L'escargot reste.",
            "papa|Sur sa feuille brillante.",
            "papa|Tu lui as parlé ?",
            "enfant-f|Oui.",
            "narrateur|Nina garde une goutte au bout du nez.",
            "papa|La gouttière chante encore un peu.",
            "enfant-f|Comme l'escargot, tout lent.",
            "narrateur|Les laitues restent brillantes, toutes ouvertes.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Sa coquille brille.",
            "papa|Après la pluie.",
            "narrateur|La coquille brille sur la feuille mouillée.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("escargot", "C'est l'escargot. Qui Nina cherche-t-elle ?"),
)
relecture(
    "ATOM-VIV.ANI.002-05",
    "L'escargot après la pluie",
    "Nina cherche l'escargot. Poule et chat vus. Escargot sous la laitue. Pas pris.",
    "N1. Noms greffés. Famille poule/poussin dite une fois.",
)


# ---------------------------------------------------------------------------
# 06 N2 Raphaël, papa — ferme, veau, seau qui cliquette
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-06",
    "Raphaël veut voir le veau. Le seau de zinc cliquette. Il le pose. Taureau, vache et veau sont au calme. Le veau boit.",
    "Le veau et le seau",
    "Raphaël, papa",
    "ferme, laiterie, enclos du veau",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le zinc du seau est froid, tout gris.",
            "narrateur|Il sent encore le lait tiède.",
            "narrateur|La laiterie est sombre, un peu fraîche.",
            "narrateur|Raphaël vit ici, avec papa.",
            "narrateur|Une mouche tourne près de la fenêtre.",
            "enfant-m|Papa, je veux voir le veau.",
            "papa|Le petit de la vache ?",
            "enfant-m|Oui.",
            "enfant-m|Je veux lui parler.",
            "narrateur|En ce moment, papa tend le seau.",
            "narrateur|Raphaël le prend à deux mains.",
            "narrateur|Le seau cliquette contre son genou.",
            "narrateur|Cling, cling, sur le seuil de pierre.",
            "enfant-m|Il fait trop de bruit.",
            "papa|On le pose ?",
            "enfant-m|Oui.",
            "narrateur|Raphaël pose le seau près du mur.",
            "narrateur|Le zinc se tait d'un coup.",
            "papa|Merci, Raphaël.",
            "papa|Maintenant on peut avancer doux.",
            "narrateur|Ils marchent vers l'enclos.",
            "narrateur|L'herbe sent le lait et le foin.",
            "narrateur|Un taureau brun reste au fond, calme.",
            "enfant-m|Le taureau.",
            "papa|Oui.",
            "papa|On le salue de loin.",
            "narrateur|Une vache lèche une barre de sel.",
            "enfant-m|La vache !",
            "papa|Tu la vois bien ?",
            "enfant-m|Oui.",
            "enfant-m|Le veau est où ?",
            "papa|Près d'elle, tout contre.",
            "narrateur|Un veau roux lève le museau.",
            "enfant-m|Le veau !",
            "papa|Taureau, vache, veau.",
            "papa|Trois noms de la famille.",
            "narrateur|Raphaël s'accroupit près de la barrière.",
            "enfant-m|Bonjour, petit.",
            "narrateur|Le veau avance, sans bruit.",
            "papa|Sans le seau, il vient.",
            "narrateur|Raphaël reste accroupi, sans bouger le seau.",
            "narrateur|Le veau passe la langue sur le bois.",
            "enfant-m|Il a soif.",
            "papa|La vache l'a déjà nourri.",
            "papa|Toi, tu lui parles.",
            "narrateur|Le taureau baisse la tête au fond.",
            "narrateur|Il broute, sans s'approcher.",
            "enfant-m|Il est grand.",
            "papa|Oui.",
            "papa|On le salue de loin.",
            "narrateur|Une goutte de lait a séché sur le zinc.",
            "papa|Le seau attend au mur.",
            "enfant-m|Il ne cliquette plus.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Le petit de la vache, c'est qui ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le veau passe la langue sur le bois.",
            "narrateur|Le bois est rêche, encore humide.",
            "enfant-m|Il a une langue rêche.",
            "papa|Oui.",
            "papa|C'est le petit de la vache.",
            "papa|On lui laisse le calme ?",
            "enfant-m|Oui, papa.",
            "narrateur|Derrière eux, le seau reste muet.",
            "enfant-m|Il ne cliquette plus.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils reprennent le seau, tout doux.",
            "narrateur|Raphaël le tient loin du genou.",
            "narrateur|Le zinc ne dit plus rien.",
            "enfant-m|Le taureau est resté au fond.",
            "papa|La vache lèche encore le sel.",
            "papa|Tu as vu les trois ?",
            "enfant-m|Taureau, vache, veau.",
            "narrateur|Raphaël pose le seau dans la laiterie.",
            "papa|Sur la pierre froide.",
            "enfant-m|Loin du genou.",
            "narrateur|La fenêtre laisse un carré de jour sur le zinc.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Il a bu, papa.",
            "papa|Sans le bruit.",
            "narrateur|Le veau boit, et le seau se tait.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("veau", "C'est le veau. Quel est le petit de la vache ?"),
)
relecture(
    "ATOM-VIV.ANI.002-06",
    "Le veau et le seau",
    "Raphaël veut le veau. Seau qui cliquette, posé. Famille taureau/vache/veau. Veau qui s'approche.",
    "N2. Bruit du seau = imprévu. Leçon greffée.",
)


# ---------------------------------------------------------------------------
# 07 N2 Chouchou, maman — pré, âne, carotte
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-07",
    "Chouchou veut donner une carotte à l'âne. La carotte glisse dans l'herbe. Elle la retrouve. Âne, ânesse et ânon s'approchent. L'âne croque.",
    "La carotte de l'âne",
    "Chouchou, maman",
    "pré d'été, clôture, carotte",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'herbe du pré sent le foin chaud.",
            "narrateur|Des sauterelles sautent devant les bottes.",
            "narrateur|Le ciel est pâle, presque blanc.",
            "narrateur|Chouchou vit ici, avec maman.",
            "narrateur|Dans sa poche, une carotte fait un rond.",
            "enfant-f|Maman, je veux la donner à l'âne.",
            "maman|La carotte ?",
            "enfant-f|Oui.",
            "enfant-f|Il aime le croquant.",
            "narrateur|En ce moment, elles marchent le long du fil.",
            "narrateur|Le fil est chaud, un peu rouillé.",
            "narrateur|Une ânesse grise broute près du chardon.",
            "enfant-f|L'ânesse !",
            "maman|Oui, Chouchou.",
            "maman|Elle a de grandes oreilles.",
            "narrateur|Un ânon reste collé à son flanc.",
            "enfant-f|L'ânon aussi.",
            "maman|Tu le vois bien ?",
            "enfant-f|Oui.",
            "enfant-f|L'âne est où ?",
            "maman|Plus loin, près du saule.",
            "narrateur|Chouchou sort la carotte.",
            "narrateur|Elle est fraîche, encore un peu terreuse.",
            "narrateur|Un pas trop vite : la carotte glisse.",
            "narrateur|Elle disparaît dans l'herbe haute.",
            "enfant-f|Oh.",
            "enfant-f|Elle est tombée.",
            "maman|On la cherche ensemble ?",
            "narrateur|Chouchou écarte les brins, tout doux.",
            "narrateur|Une pointe orange brille entre deux tiges.",
            "enfant-f|Je l'ai !",
            "maman|Merci d'avoir cherché sans courir.",
            "narrateur|L'âne gris s'approche du fil.",
            "enfant-f|L'âne !",
            "maman|Âne, ânesse, ânon.",
            "maman|Trois noms de la famille.",
            "narrateur|Chouchou tend la carotte sur sa paume.",
            "narrateur|L'âne la prend avec des lèvres de velours.",
            "enfant-f|Ça chatouille.",
            "maman|Tu lui as donné tout calme.",
            "narrateur|L'âne mâche, la mâchoire de travers.",
            "narrateur|Un bout de carotte tombe, puis remonte.",
            "enfant-f|Il a des poils aux oreilles.",
            "maman|Oui.",
            "maman|De grandes oreilles chaudes.",
            "narrateur|L'ânesse avance d'un pas, puis s'arrête.",
            "narrateur|L'ânon reste collé, l'œil sombre.",
            "enfant-f|Il a un peu peur.",
            "maman|On reste de ce côté du fil.",
            "narrateur|Chouchou essuie un peu de terre au pantalon.",
            "maman|Ta poche est vide, maintenant.",
            "enfant-f|La carotte est dans l'âne.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou tend la carotte à qui ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|L'âne croque, lentement.",
            "narrateur|Un peu de jus orange perle au poil.",
            "enfant-f|Il aime ça.",
            "maman|Oui.",
            "maman|C'est l'âne du pré.",
            "maman|L'ânesse regarde, elle aussi.",
            "enfant-f|L'ânon se cache un peu.",
            "narrateur|Chouchou essuie sa paume dans l'herbe.",
            "maman|On reste encore ?",
            "enfant-f|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles reculent vers le chemin de terre.",
            "narrateur|L'ânesse reprend le chardon.",
            "narrateur|L'ânon colle à nouveau son flanc.",
            "enfant-f|L'âne mâche encore.",
            "maman|Ta carotte.",
            "maman|Tu as vu les trois ?",
            "enfant-f|Âne, ânesse, ânon.",
            "narrateur|Chouchou sent encore le sucré sur les doigts.",
            "maman|Et un peu de terre.",
            "enfant-f|De la carotte.",
            "narrateur|Une sauterelle reprend le chemin des bottes.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Il croque, maman.",
            "maman|Tout doux.",
            "narrateur|L'âne croque la carotte, lentement.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "âne",
        "accepted_examples": "âne | l'âne | a l'âne | à l'âne",
        "retry_prompt": "C'est l'âne. À qui tend-elle la carotte ?",
    },
)
relecture(
    "ATOM-VIV.ANI.002-07",
    "La carotte de l'âne",
    "Chouchou veut donner la carotte. Elle glisse, elle la retrouve. Âne, ânesse, ânon. L'âne croque.",
    "N2. Imprévu carotte. Noms greffés. Paume ouverte, pas de geste dangereux.",
)


# ---------------------------------------------------------------------------
# 08 N2 Aniss, maman, papa — écurie, poney, brosse, rester avec les adultes
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-08",
    "Aniss veut brosser le poney. La brosse tombe dans la paille. Il la ramasse près de papa et maman. Cheval, jument, poney. Ils restent ensemble.",
    "La brosse du poney",
    "Aniss, maman, papa",
    "écurie, box, paille",
    {
        "CHK_T0000_P0000": [
            "narrateur|La porte de bois de l'écurie craque.",
            "narrateur|L'air sent le cuir et le foin.",
            "narrateur|Un rai de lumière coupe la paille.",
            "narrateur|Aniss vit ici, avec papa et maman.",
            "narrateur|Ses mains sont déjà un peu poudreuses.",
            "enfant-m|Je veux brosser le poney.",
            "maman|Le poney du box du fond ?",
            "enfant-m|Oui.",
            "papa|On y va ensemble.",
            "narrateur|En ce moment, ils avancent entre les boxes.",
            "narrateur|Un cheval noir souffle près de la porte.",
            "enfant-m|Le cheval !",
            "papa|Oui, Aniss.",
            "papa|On passe près de lui, sans courir.",
            "narrateur|Une jument alezane gratte la litière.",
            "enfant-m|La jument aussi.",
            "maman|Tu les vois bien ?",
            "enfant-m|Oui.",
            "enfant-m|Le poney est au fond.",
            "narrateur|Aniss fait un pas tout seul.",
            "papa|On reste avec nous ?",
            "maman|On brosse ensemble.",
            "enfant-m|Oui.",
            "narrateur|Il revient entre papa et maman.",
            "narrateur|Le poney pie attend, l'œil sombre.",
            "enfant-m|Le poney !",
            "maman|Cheval, jument, poney.",
            "maman|Trois noms de la famille.",
            "narrateur|Papa tend la brosse en crin.",
            "narrateur|Aniss la prend.",
            "narrateur|La brosse glisse, tombe dans la paille.",
            "enfant-m|Oh.",
            "maman|On la cherche, tous les trois ?",
            "narrateur|Aniss écarte la paille près des bottes.",
            "narrateur|Le bois de la brosse reparaît.",
            "enfant-m|Je l'ai.",
            "papa|Merci de rester avec nous.",
            "papa|Tu brosses, on est là.",
            "narrateur|Aniss pose la brosse sur l'encolure.",
            "narrateur|Le poil du poney sent le foin chaud.",
            "enfant-m|Il est doux.",
            "maman|Tout doux, comme ta main.",
            "narrateur|Aniss brosse de l'encolure vers l'épaule.",
            "narrateur|Le poney pie cligne, sans reculer.",
            "enfant-m|Il aime ça.",
            "papa|Oui.",
            "papa|On reste tous les trois.",
            "narrateur|Le cheval noir gratte une fois, plus loin.",
            "narrateur|La jument souffle dans sa litière.",
            "enfant-m|Ils écoutent.",
            "maman|Toi aussi, tu écoutes.",
            "narrateur|Un brin de paille colle à la brosse.",
            "papa|On le retire ensemble ?",
            "enfant-m|Oui, papa.",
            "narrateur|Maman pince le brin, Aniss tient le bois.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss brosse qui, à l'écurie ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le poney baisse un peu le cou.",
            "narrateur|La poussière vole dans le rai de lumière.",
            "enfant-m|Ça le démangeait.",
            "papa|Oui.",
            "papa|C'est le poney du box.",
            "maman|Tu restes avec nous ?",
            "enfant-m|Oui.",
            "enfant-m|On brosse ensemble.",
            "narrateur|La brosse fait un bruit court, régulier.",
            "maman|On reste encore un peu ?",
            "enfant-m|Oui, maman.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils raccrochent la brosse au clou.",
            "narrateur|Le cheval noir souffle encore.",
            "narrateur|La jument gratte une dernière fois.",
            "enfant-m|Le poney est lisse.",
            "papa|Tu as vu les trois ?",
            "enfant-m|Cheval, jument, poney.",
            "maman|Et tu es resté avec nous.",
            "narrateur|Aniss essuie ses mains dans la paille propre.",
            "papa|Tes doigts sentent le poney.",
            "enfant-m|Et le foin.",
            "narrateur|La porte de bois craque encore, un peu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Il sent le foin.",
            "papa|Sur tes mains aussi.",
            "narrateur|Le poil du poney sent encore le foin.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_petit("poney", "C'est le poney. Qui Aniss brosse-t-il ?"),
)
relecture(
    "ATOM-VIV.ANI.002-08",
    "La brosse du poney",
    "Aniss veut brosser le poney. Brosse tombée. Il reste avec papa et maman. Famille cheval/jument/poney.",
    "N2. Rester avec les adultes greffé. Pas de box seul.",
)
