#!/usr/bin/env python3
"""F-NAR-008 — leçons implicites SEC.PAR / SEC.MAI / COL.ECO / VIV.ANI / LAN.MOT."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import relecture, write_story


def story(sid, fil, title, chars, setting, scripts, q, vecu, notes):
    write_story(sid, fil, title, chars, setting, scripts, {}, q)
    relecture(sid, title, vecu, notes)


# ---------------------------------------------------------------------------
# ATOM-SEC.PAR.001-03 N3 Aniss, maman — square, tilleuls, bateau de noix, haie
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.PAR.001-03",
    "Aniss veut faire traverser son bateau de noix. Un papier roule vers la haie. "
    "Maman devient petite. Il revient parce que le bateau est avec elle.",
    "Le bateau de noix d'Aniss",
    "Aniss, maman",
    "square du village, fontaine, tilleuls après le marché",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les tilleuls du square sentent le miel.",
            "narrateur|Une caisse vide sent encore la pêche.",
            "narrateur|L'eau de la fontaine tremble au soleil.",
            "narrateur|Le pain du sac de maman est encore tiède.",
            "narrateur|Une coque de noix attend près du bord.",
            "maman|Tu as vu l'eau, Aniss ?",
            "enfant-m|Elle brille, maman.",
            "maman|Elle est froide, un peu.",
            "narrateur|Une feuille jaune fait un tout petit voile.",
            "narrateur|Aniss la pique dans la noix.",
            "enfant-m|Je veux qu'il traverse.",
            "enfant-m|Jusqu'à l'autre bord.",
            "maman|On le pose ici, près de moi ?",
            "enfant-m|Oui.",
            "narrateur|En ce moment, la coque touche l'eau.",
            "narrateur|L'eau pique les doigts, toute vive.",
            "enfant-m|Il flotte !",
            "maman|Tout doux, avec le doigt.",
            "narrateur|Aniss pousse le voile d'un ongle.",
            "narrateur|Le bateau part, puis il tourne.",
            "narrateur|Une abeille passe au-dessus des tilleuls.",
            "enfant-m|Zzz.",
            "maman|Tu l'entends ?",
            "enfant-m|Oui.",
            "narrateur|Un papier du marché s'envole un peu.",
            "narrateur|Il roule vers la haie, tout au fond.",
            "enfant-m|Je le prends !",
            "narrateur|Aniss fait trois pas vers la haie.",
            "narrateur|La fontaine devient petite derrière lui.",
            "narrateur|Maman devient une petite forme.",
            "narrateur|Le bateau de noix reste près d'elle.",
            "narrateur|Le voile jaune penche, tout seul.",
            "enfant-m|Mon bateau est là.",
            "narrateur|Aniss revient vers l'eau.",
            "narrateur|Les dalles sont chaudes sous ses pieds.",
            "maman|Tu reviens près du bateau ?",
            "enfant-m|Oui.",
            "enfant-m|Il va partir sans moi.",
            "maman|Je te vois mieux, ici.",
            "narrateur|Le voile se redresse sous le doigt.",
            "narrateur|La coque avance, toute lente.",
            "enfant-m|Il va arriver.",
            "maman|Je le vois, et je te vois.",
            "narrateur|Une goutte saute sur le genou d'Aniss.",
            "enfant-m|Elle est froide.",
            "maman|Comme l'eau de la noix.",
            "narrateur|Le bateau touche l'autre bord.",
            "enfant-m|Il a traversé !",
            "maman|Bravo.",
            "maman|Il est resté avec nous.",
            "narrateur|Aniss reprend la coque, tout prudent.",
            "narrateur|La noix est luisante, un peu froide.",
            "maman|On goûte le pain, après ?",
            "enfant-m|Oui, maman.",
            "narrateur|Le sac sent le blé chaud.",
            "narrateur|Une miette tombe près de l'eau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss joue près de l'eau.",
            "narrateur|Où reste-t-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le papier reste coincé dans la haie.",
            "narrateur|Aniss ne va pas le chercher.",
            "narrateur|Il tient encore la noix mouillée.",
            "maman|Le bateau est avec moi, tu vois ?",
            "enfant-m|Oui.",
            "enfant-m|Alors je reste.",
            "maman|Je te vois, près de la fontaine.",
            "narrateur|Une feuille neuve sert de voile.",
            "narrateur|Aniss la pique, tout doux.",
            "enfant-m|Encore une traversée.",
            "maman|Ici, je te vois bien.",
            "narrateur|Le square sent le miel et le pain.",
            "narrateur|L'eau cliquette contre la pierre.",
            "enfant-m|Il tourne encore.",
            "maman|Tu le pousses du doigt ?",
            "enfant-m|Du tout petit doigt.",
            "narrateur|La coque file vers le bord.",
            "narrateur|Maman la suit des yeux, et Aniss aussi.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman rompt le pain tiède.",
            "narrateur|Une miette reste sur le pouce d'Aniss.",
            "maman|Tu as soif ?",
            "enfant-m|Un peu.",
            "narrateur|La gourde est fraîche contre la joue.",
            "enfant-m|Le bateau a traversé.",
            "maman|Oui.",
            "maman|Il était là, avec nous.",
            "narrateur|Aniss essuie la noix sur sa manche.",
            "narrateur|La manche sent le tilleul.",
            "maman|On la pose dans le sac ?",
            "enfant-m|Près du pain.",
            "narrateur|Le square s'ombre un peu.",
            "narrateur|Les tilleuls bougent, tout lents.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La coque de noix brille dans le sac.",
            "enfant-m|Il a traversé.",
            "maman|Oui.",
            "narrateur|Les tilleuls sentent encore le miel.",
            "narrateur|L'eau de la fontaine tremble, calme.",
        ],
    },
    {
        "expected_answer": "espace montré",
        "accepted_examples": "espace montré | près maman | près de maman | le bateau | où maman voit | ici",
        "retry_prompt": "Le bateau est près de maman. Où reste Aniss ?",
    },
    "Aniss veut que sa noix traverse la fontaine. Un papier roule vers la haie. "
    "Maman devient petite. Il revient parce que le bateau est avec elle.",
    "Pas de rue. Pas « la règle ». Désir = le bateau. D16 Aniss, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.PAR.001-06 N3 Sarah, maman — parc salé, tamaris, bateau de papier
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.PAR.001-06",
    "Sarah veut que son bateau de papier flotte dans la flaque salée. "
    "Une coquille brille près de la haie. Maman devient petite. Sarah revient pour le bateau.",
    "Le bateau salé de Sarah",
    "Sarah, maman",
    "parc au bord de la mer, tamaris, flaque de sel",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le vent salé plie les tamaris.",
            "narrateur|Une flaque brille entre les dalles.",
            "narrateur|Elle sent la mer, un peu.",
            "narrateur|Un banc de bois reste encore humide.",
            "narrateur|Une plume grise colle au bois.",
            "maman|Tu as vu la flaque, Sarah ?",
            "enfant-f|Elle tremble, maman.",
            "maman|C'est le vent.",
            "narrateur|Sarah tient un bateau de papier.",
            "narrateur|Le papier est blanc, un peu raide.",
            "enfant-f|Je veux qu'il flotte.",
            "enfant-f|Dans l'eau salée.",
            "maman|On le pose ici, près de moi ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, le papier touche l'eau.",
            "narrateur|L'eau est froide, un peu piquante.",
            "enfant-f|Il flotte.",
            "maman|Tout doucement.",
            "narrateur|Sarah souffle, tout bas.",
            "narrateur|Le bateau avance d'un souffle.",
            "enfant-f|Il part.",
            "maman|Je le vois.",
            "maman|Je te vois aussi.",
            "narrateur|Une coquille rose luit, très loin.",
            "narrateur|Elle est près de la haie de tamaris.",
            "enfant-f|La coquille !",
            "narrateur|Sarah fait quelques pas vers la haie.",
            "narrateur|Le banc devient petit.",
            "narrateur|Maman devient une petite forme.",
            "narrateur|Le bateau penche dans la flaque, tout seul.",
            "enfant-f|Il va se mouiller trop.",
            "narrateur|Sarah revient vers la flaque.",
            "narrateur|Le sel colle déjà sous ses sandales.",
            "maman|Tu reviens près du bateau ?",
            "enfant-f|Oui.",
            "enfant-f|Il est avec toi.",
            "maman|Ici, je te vois bien.",
            "narrateur|Le papier a bu un peu d'eau.",
            "narrateur|Il est mou, encore flottant.",
            "enfant-f|Il est lourd, maintenant.",
            "maman|On le pousse du doigt ?",
            "enfant-f|Oui.",
            "narrateur|Le bateau tourne, tout lent.",
            "narrateur|Une goutte de sel brille sur le pouce.",
            "enfant-f|Ça pique.",
            "maman|C'est la mer, dans la flaque.",
            "narrateur|Le bateau s'arrête contre une dalle.",
            "enfant-f|Il est arrivé.",
            "maman|Bravo.",
            "maman|Il est resté avec nous.",
            "narrateur|Sarah reprend le papier, tout prudent.",
            "narrateur|Il sent le sel et le vent.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah joue près du bateau.",
            "narrateur|Où reste-t-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La coquille rose reste près de la haie.",
            "narrateur|Sarah ne va pas la chercher.",
            "narrateur|Elle tient le papier mouillé.",
            "maman|Le bateau était là, avec moi.",
            "enfant-f|Oui.",
            "enfant-f|Alors je reste.",
            "maman|Je te vois, près de la flaque.",
            "narrateur|Elles soufflent encore une fois.",
            "narrateur|Le papier avance, plus lent.",
            "enfant-f|Il est fatigué.",
            "maman|Il a bu l'eau.",
            "maman|Toi, tu es là.",
            "narrateur|Le vent plie encore les tamaris.",
            "narrateur|La plume grise s'envole du banc.",
            "enfant-f|Elle part.",
            "maman|Le bateau, lui, reste.",
            "narrateur|Sarah pose le papier sur le bois.",
            "narrateur|Le bois est froid, un peu rugueux.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman tend la gourde.",
            "narrateur|L'eau douce lave le sel de la langue.",
            "maman|Tu as soif ?",
            "enfant-f|Oui, maman.",
            "enfant-f|Le bateau a flotté.",
            "maman|Oui.",
            "maman|Il était avec nous.",
            "narrateur|Sarah essuie ses doigts sur le linge.",
            "narrateur|Le linge sent le vent.",
            "maman|On le pose au soleil ?",
            "enfant-f|Pour qu'il sèche.",
            "narrateur|Le papier blanchit un peu, déjà.",
            "narrateur|La flaque tremble encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le bateau sèche sur le banc.",
            "enfant-f|Il a flotté.",
            "maman|Oui.",
            "narrateur|Le sel colle encore aux doigts.",
            "narrateur|Les tamaris plient, tout doux.",
        ],
    },
    {
        "expected_answer": "espace montré",
        "accepted_examples": "espace montré | près maman | près de maman | le bateau | où maman voit | ici",
        "retry_prompt": "Le bateau est près de maman. Où reste Sarah ?",
    },
    "Sarah veut faire flotter son bateau dans la flaque salée. Une coquille brille "
    "près de la haie. Maman devient petite. Sarah revient pour le bateau.",
    "Pas de rue. Pas « la règle ». Désir = le bateau. D16 Sarah, maman.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.MAI.002-04 N3 Sarah, maman — pluie sur zinc, pot sans nom, pain
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.MAI.002-04",
    "Sarah veut du pain tiède avec quelque chose de doux. Un pot fermé n'a pas de nom. "
    "Elle tend la main. La main de maman attend. Sarah dit je peux. Elles goûtent ensemble.",
    "Le pot sans nom",
    "Sarah, maman",
    "cuisine de village, pluie sur le zinc, pain tiède",
    {
        "CHK_T0000_P0000": [
            "narrateur|La pluie chante sur le zinc.",
            "narrateur|La vitre de la cuisine est toute embuée.",
            "narrateur|Ça sent le pain qui sort du four.",
            "narrateur|Un torchon rayé pend près de l'évier.",
            "narrateur|Une miche dorée attend sur la planche.",
            "maman|Tu as vu la buée, Sarah ?",
            "enfant-f|Je fais un rond, maman.",
            "narrateur|Le doigt dessine un petit hublot.",
            "narrateur|Derrière, un toit luisant dégoutte.",
            "enfant-f|Je veux du pain.",
            "enfant-f|Avec quelque chose de doux.",
            "maman|La miche est encore chaude.",
            "maman|On va lui trouver un ami ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, Sarah s'approche de la table.",
            "narrateur|Un petit pot brun est là, fermé.",
            "narrateur|Le couvercle n'a pas de dessin.",
            "narrateur|Le verre est opaque, un peu gras.",
            "enfant-f|Qu'est-ce que c'est ?",
            "narrateur|Sarah tend les doigts vers le verre.",
            "narrateur|La main de maman s'arrête à côté.",
            "narrateur|Elle n'attrape pas.",
            "narrateur|Elle attend, ouverte, tout près.",
            "narrateur|Les doigts de Sarah s'arrêtent aussi.",
            "enfant-f|Maman, je peux ?",
            "maman|Oui.",
            "maman|On ouvre ensemble.",
            "narrateur|Le couvercle fait un petit clic.",
            "narrateur|Une odeur de figue monte, épaisse.",
            "enfant-f|Ça sent le fruit.",
            "maman|C'est de la confiture.",
            "maman|Tu goûtes avec moi ?",
            "enfant-f|Oui.",
            "narrateur|Deux cuillères trempent, toutes petites.",
            "narrateur|Sarah goûte.",
            "enfant-f|C'est sucré.",
            "enfant-f|Et un peu de pépins.",
            "maman|Des figues.",
            "maman|Merci, Sarah.",
            "maman|Tu as attendu ma main.",
            "narrateur|Maman coupe une tranche tiède.",
            "narrateur|La confiture glisse, sombre, sur le pain.",
            "enfant-f|Pour moi ?",
            "maman|Pour toi.",
            "narrateur|Sarah croque.",
            "narrateur|Le pain craque, la figue colle.",
            "enfant-f|C'est bon.",
            "maman|Le zinc chante encore ?",
            "enfant-f|Oui.",
            "narrateur|Une goutte court sur le hublot du doigt.",
            "narrateur|Le pot reste ouvert, entre elles deux.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah voit un pot fermé.",
            "narrateur|Que dit-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La tranche a un trou de confiture.",
            "narrateur|Sarah lèche un pépin sur le pouce.",
            "maman|Tu veux encore un peu ?",
            "enfant-f|Je peux ?",
            "maman|Oui.",
            "narrateur|Elles trempent encore la cuillère.",
            "narrateur|Le verre du pot est tiède, maintenant.",
            "enfant-f|Il n'avait pas de nom.",
            "maman|On ne savait pas.",
            "maman|Alors on a ouvert ensemble.",
            "narrateur|La pluie ralentit sur le zinc.",
            "narrateur|Le hublot du doigt s'efface un peu.",
            "enfant-f|Le pain est encore chaud.",
            "maman|Tu le sens ?",
            "enfant-f|Sous les doigts, oui.",
            "narrateur|Des miettes dorées restent sur la planche.",
            "narrateur|Le torchon rayé sent la figue, maintenant.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Sarah boit une gorgée d'eau.",
            "narrateur|L'eau lave le sucre de la langue.",
            "maman|On referme le pot ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le clic du couvercle est doux.",
            "enfant-f|C'était des figues.",
            "maman|Oui.",
            "maman|On le sait, maintenant.",
            "narrateur|La miche a une tranche en moins.",
            "narrateur|Elle sent encore le four.",
            "maman|Tu as encore faim ?",
            "enfant-f|Non.",
            "enfant-f|C'était bon.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le pain sent encore la figue.",
            "enfant-f|J'ai dit je peux.",
            "maman|Oui.",
            "narrateur|Le zinc est calme, presque.",
            "narrateur|Le pot brun reste entre leurs mains.",
        ],
    },
    {
        "expected_answer": "demander",
        "accepted_examples": "demander | je peux | à maman | un adulte | elle demande | à l'adulte",
        "retry_prompt": "Sarah parle à maman. Que dit-elle ?",
    },
    "Sarah veut du pain avec quelque chose de doux. Pot sans nom. Elle tend la main. "
    "La main de maman attend. Je peux. Elles goûtent la figue ensemble.",
    "Pas de slogan « il faut demander ». D16 Sarah, maman. Fin = pain et figue.",
)

# ---------------------------------------------------------------------------
# ATOM-SEC.MAI.002-05 N2 Mila, maman — crêpe, cour d'immeuble, pot de miel
# ---------------------------------------------------------------------------
story(
    "ATOM-SEC.MAI.002-05",
    "Mila veut une crêpe avec quelque chose de doux. Un petit pot doré n'a pas d'étiquette. "
    "Elle tend la main. La main de maman attend. Mila dit je peux. Elles goûtent le miel.",
    "Le miel de la crêpe",
    "Mila, maman",
    "cuisine d'immeuble, lumière de la cour, crêpe dans la poêle",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une crêpe dore dans la poêle.",
            "narrateur|Le beurre chante tout bas.",
            "narrateur|La lumière de la cour entre, pâle.",
            "narrateur|Un seau d'eau brille cinq étages plus bas.",
            "narrateur|Ça sent la farine chaude.",
            "maman|Tu as vu la crêpe, Mila ?",
            "enfant-f|Elle fait des trous, maman.",
            "maman|C'est le beurre.",
            "enfant-f|Je veux la manger.",
            "enfant-f|Avec quelque chose de doux.",
            "maman|On va lui trouver un ami ?",
            "enfant-f|Oui.",
            "narrateur|En ce moment, Mila pousse le tabouret.",
            "narrateur|Le bois racle le carrelage, tout doux.",
            "narrateur|Un petit pot doré est sur la table.",
            "narrateur|Il n'a pas d'étiquette.",
            "narrateur|Le verre est lisse, un peu collant.",
            "enfant-f|Qu'est-ce que c'est ?",
            "narrateur|Mila tend le doigt vers le couvercle.",
            "narrateur|La main de maman s'arrête à côté.",
            "narrateur|Elle n'attrape pas.",
            "narrateur|Elle attend, ouverte, tout près.",
            "narrateur|Le doigt de Mila s'arrête aussi.",
            "enfant-f|Maman, je peux ?",
            "maman|Oui.",
            "maman|On ouvre ensemble.",
            "narrateur|Le couvercle colle un peu.",
            "narrateur|Puis il vient.",
            "narrateur|Une odeur de fleurs monte, épaisse.",
            "enfant-f|Ça sent l'été.",
            "maman|C'est du miel.",
            "maman|Tu goûtes avec moi ?",
            "enfant-f|Oui.",
            "narrateur|Deux cuillères trempent, toutes lentes.",
            "narrateur|Le fil d'or tombe, tout long.",
            "enfant-f|C'est collant.",
            "enfant-f|Et doux.",
            "maman|Merci, Mila.",
            "maman|Tu as attendu ma main.",
            "narrateur|Maman pose la crêpe dans l'assiette.",
            "narrateur|Le miel glisse au milieu, tout lent.",
            "enfant-f|Pour moi ?",
            "maman|Pour toi.",
            "narrateur|Mila plie la crêpe.",
            "narrateur|Le miel coule un peu sur le pouce.",
            "enfant-f|C'est bon.",
            "maman|La cour est calme, en bas ?",
            "enfant-f|Le seau brille encore.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila voit un pot fermé.",
            "narrateur|Que dit-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Un fil de miel reste sur l'assiette.",
            "narrateur|Mila le prend du doigt.",
            "maman|Tu veux encore un peu ?",
            "enfant-f|Je peux ?",
            "maman|Oui.",
            "narrateur|Elles trempent encore la cuillère.",
            "narrateur|Le pot est tiède, un peu lourd.",
            "enfant-f|Il n'avait pas de nom.",
            "maman|On ne savait pas.",
            "maman|Alors on a ouvert ensemble.",
            "narrateur|La poêle ne chante plus.",
            "narrateur|Il reste une odeur de beurre.",
            "enfant-f|Ma crêpe est douce.",
            "maman|Tu la sens aux doigts ?",
            "enfant-f|Ils collent.",
            "narrateur|La lumière de la cour a bougé un peu.",
            "narrateur|Le seau, en bas, n'est plus au même endroit.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Mila boit une gorgée de lait.",
            "narrateur|Le lait lave le miel de la langue.",
            "maman|On referme le pot ?",
            "enfant-f|Oui, maman.",
            "narrateur|Le couvercle reprend sa place, collant.",
            "enfant-f|C'était du miel.",
            "maman|Oui.",
            "maman|On le sait, maintenant.",
            "narrateur|L'assiette a un rond doré, vide.",
            "maman|Tu as encore faim ?",
            "enfant-f|Non.",
            "enfant-f|C'était bon.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La crêpe a laissé un rond de miel.",
            "enfant-f|J'ai dit je peux.",
            "maman|Oui.",
            "narrateur|La cour est pâle, en bas.",
            "narrateur|Le pot doré reste entre leurs mains.",
        ],
    },
    {
        "expected_answer": "demander",
        "accepted_examples": "demander | je peux | à maman | un adulte | elle demande | à l'adulte",
        "retry_prompt": "Mila parle à maman. Que dit-elle ?",
    },
    "Mila veut une crêpe douce. Pot doré sans étiquette. Elle tend la main. "
    "La main de maman attend. Je peux. Elles goûtent le miel ensemble.",
    "Pas de slogan. N2. D16 Mila, maman. Fin = crêpe et miel.",
)

# ---------------------------------------------------------------------------
# ATOM-COL.ECO.002-01 N2 Amir, maman — boulangerie, petit pain au sucre
# ---------------------------------------------------------------------------
story(
    "ATOM-COL.ECO.002-01",
    "Amir veut le petit pain rond au grain de sucre. Il parle trop tôt. "
    "Le batteur couvre sa voix. Il lève la main, il attend, puis maman l'entend.",
    "Le petit pain d'Amir",
    "Amir, maman",
    "boulangerie du village, vitrine farinée, batteur",
    {
        "CHK_T0000_P0000": [
            "narrateur|La farine poudre le rebord de la vitrine.",
            "narrateur|Ça sent le beurre chaud, très fort.",
            "narrateur|Un batteur tourne derrière le bois.",
            "narrateur|Il fait un gros rrrr, tout grave.",
            "narrateur|Des grains de sucre brillent sur un plateau.",
            "maman|Tu as vu les petits ronds, Amir ?",
            "enfant-m|Oui.",
            "enfant-m|Celui-là a un grain de sucre.",
            "enfant-m|Je le veux.",
            "maman|On va le dire, alors.",
            "narrateur|En ce moment, maman parle vers le bois.",
            "narrateur|Sa voix se mêle au batteur.",
            "narrateur|Amir a les mots tout prêts.",
            "enfant-m|Le petit rond !",
            "enfant-m|Avec le sucre !",
            "narrateur|Les mots tombent dans le rrrr.",
            "narrateur|Personne ne se tourne.",
            "narrateur|Le plateau reste loin, derrière la vitre.",
            "enfant-m|Maman.",
            "narrateur|Maman parle encore, un peu plus fort.",
            "narrateur|Amir ferme la bouche.",
            "narrateur|Il lève la main, tout droit.",
            "narrateur|Sa main reste en l'air, près du bois.",
            "narrateur|Le batteur tourne, tourne.",
            "narrateur|Puis il s'arrête.",
            "narrateur|Le silence est tout chaud, tout soudain.",
            "narrateur|Maman se tourne.",
            "maman|Tu voulais dire quelque chose ?",
            "enfant-m|Le petit rond.",
            "enfant-m|Avec le grain de sucre.",
            "maman|Je t'entends, maintenant.",
            "narrateur|Une pince prend le pain doré.",
            "narrateur|Le sachet craque, un peu gras.",
            "enfant-m|C'est lui.",
            "maman|Merci, Amir.",
            "maman|Tu as attendu, et je t'ai entendu.",
            "narrateur|Le grain de sucre brille encore.",
            "narrateur|Amir le garde du doigt, à travers le papier.",
            "maman|On le mange sur le pas de la porte ?",
            "enfant-m|Oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir veut parler.",
            "narrateur|Que fait-il d'abord ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le pas de la porte est tiède.",
            "narrateur|Amir ouvre le sachet.",
            "narrateur|Le pain est encore chaud dans la paume.",
            "enfant-m|Le grain de sucre est là.",
            "maman|Tu le croques ?",
            "enfant-m|Oui.",
            "narrateur|Le sucre casse, tout fin.",
            "narrateur|La mie est blanche, un peu filante.",
            "enfant-m|Tu m'as entendu.",
            "maman|Oui.",
            "maman|Quand le batteur s'est tu.",
            "maman|Quand ta main était là.",
            "narrateur|Une miette tombe sur la farine du rebord.",
            "narrateur|Amir la pousse du doigt, tout doux.",
            "maman|Il est bon ?",
            "enfant-m|Il est chaud.",
            "narrateur|Le village sent le pain, tout entier.",
            "narrateur|Le sachet vide reste un peu gras.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman essuie un grain de farine.",
            "narrateur|Il était sur la joue d'Amir.",
            "maman|On rentre ?",
            "enfant-m|Oui.",
            "enfant-m|J'ai eu le petit rond.",
            "maman|Oui.",
            "maman|Je t'ai entendu.",
            "narrateur|Le batteur reprend, plus loin, plus bas.",
            "narrateur|Amir lèche un peu de sucre au pouce.",
            "maman|Il en reste ?",
            "enfant-m|Un tout petit peu.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le sachet craque encore dans la poche.",
            "enfant-m|Tu m'as entendu.",
            "maman|Oui.",
            "narrateur|Un grain de sucre brille sur le pouce.",
            "narrateur|La vitrine reste poudreuse, calme.",
        ],
    },
    {
        "expected_answer": "attendre",
        "accepted_examples": "attendre | il attend | lever la main | la main",
        "retry_prompt": "Personne ne l'entend. Que fait Amir d'abord ?",
    },
    "Amir veut le petit pain au sucre. Il parle trop tôt, le batteur couvre. "
    "Il lève la main, il attend, maman l'entend. Ils croquent sur le pas.",
    "Pas « il faut attendre ». D16 Amir, maman. Boulangerie.",
)

# ---------------------------------------------------------------------------
# ATOM-COL.ECO.002-02 N3 Nino, papa — port, coquille, hush de la mer
# ---------------------------------------------------------------------------
story(
    "ATOM-COL.ECO.002-02",
    "Nino veut faire écouter la mer dans sa coquille. Il parle trop tôt. "
    "Les mouettes couvrent sa voix. Il lève la main, il attend, puis papa l'entend.",
    "La mer dans la poche",
    "Nino, papa",
    "port, caisses mouillées, ponton, coquille",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une coquille grince dans la poche de Nino.",
            "narrateur|Le bois du ponton est sombre, encore mouillé.",
            "narrateur|Ça sent le sel et les caisses de poisson.",
            "narrateur|Une écaille brille près d'une corde.",
            "narrateur|Les mouettes crient, très haut.",
            "papa|Tu as vu l'eau, Nino ?",
            "enfant-m|Elle tape le bois.",
            "papa|Elle est verte, ce soir.",
            "narrateur|Nino sort la coquille, toute rêche.",
            "enfant-m|Je veux que tu écoutes.",
            "enfant-m|La mer est dedans.",
            "papa|On l'écoute, alors.",
            "narrateur|En ce moment, papa compte des caisses.",
            "narrateur|Il parle vers le bout du ponton.",
            "narrateur|Sa voix se mêle aux mouettes.",
            "enfant-m|Papa, écoute !",
            "enfant-m|Hush, hush !",
            "narrateur|Les mots tombent dans les cris.",
            "narrateur|Personne ne se tourne.",
            "narrateur|La coquille reste froide dans la paume.",
            "enfant-m|Papa.",
            "narrateur|Papa compte encore, un doigt en l'air.",
            "narrateur|Nino ferme la bouche.",
            "narrateur|Il lève la main, tout droit.",
            "narrateur|La coquille est dans l'autre main.",
            "narrateur|Sa main reste en l'air, près de la corde.",
            "narrateur|Une mouette passe, puis s'éloigne.",
            "narrateur|Papa se tourne.",
            "papa|Tu voulais dire quelque chose ?",
            "enfant-m|La mer.",
            "enfant-m|Dans la coquille.",
            "papa|Je t'entends, maintenant.",
            "narrateur|Papa se baisse.",
            "narrateur|L'oreille touche le bord rêche.",
            "enfant-m|Hush.",
            "papa|Hush, oui.",
            "papa|Merci, Nino.",
            "papa|Tu as attendu, et je t'ai entendu.",
            "narrateur|L'eau tape encore le ponton, tout bas.",
            "narrateur|La coquille garde le même hush.",
            "papa|On la remet dans la poche ?",
            "enfant-m|Pour ce soir.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino veut parler.",
            "narrateur|Que fait-il d'abord ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Ils s'assoient sur une caisse vide.",
            "narrateur|Le bois est froid, un peu salé.",
            "narrateur|Nino tend encore la coquille.",
            "papa|Tu veux que j'écoute encore ?",
            "enfant-m|Oui.",
            "narrateur|Papa écoute, longtemps.",
            "enfant-m|Tu m'as entendu.",
            "papa|Oui.",
            "papa|Quand les mouettes se sont tues un peu.",
            "papa|Quand ta main était là.",
            "narrateur|Une goutte tombe de la corde.",
            "narrateur|Elle fait un rond dans l'eau verte.",
            "papa|Elle est rêche, ta coquille ?",
            "enfant-m|Oui.",
            "enfant-m|Comme le bois.",
            "narrateur|Nino la frotte contre sa manche.",
            "narrateur|Un grain de sable tombe, tout fin.",
            "papa|On la garde ?",
            "enfant-m|Dans la poche.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le ponton sèche par plaques.",
            "narrateur|Papa prend la main de Nino.",
            "papa|On rentre ?",
            "enfant-m|Oui.",
            "enfant-m|Tu as entendu la mer.",
            "papa|Oui.",
            "papa|Je t'ai entendu, toi aussi.",
            "narrateur|La coquille grince encore, tout bas.",
            "narrateur|Les caisses restent alignées, mouillées.",
            "papa|Elle est bien dans la poche ?",
            "enfant-m|Elle hush encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La coquille hush dans la poche.",
            "enfant-m|Tu m'as entendu.",
            "papa|Oui.",
            "narrateur|Le sel colle encore aux doigts.",
            "narrateur|Le ponton claque, tout doux.",
        ],
    },
    {
        "expected_answer": "attendre",
        "accepted_examples": "attendre | il attend | lever la main | la main",
        "retry_prompt": "Personne ne l'entend. Que fait Nino d'abord ?",
    },
    "Nino veut faire écouter la mer dans sa coquille. Il parle trop tôt. "
    "Les mouettes couvrent. Il lève la main, attend, papa l'entend.",
    "Pas « il faut attendre ». D16 Nino, papa. Port.",
)

# ---------------------------------------------------------------------------
# ATOM-COL.ECO.002-03 N3 Mila, maman — hall du marché, fromage de montagne
# ---------------------------------------------------------------------------
story(
    "ATOM-COL.ECO.002-03",
    "Mila veut un bout du fromage qui sent la montagne. Elle parle trop tôt. "
    "Les voix du hall couvrent. Elle lève la main, elle attend, puis maman l'entend.",
    "Le fromage de la montagne",
    "Mila, maman",
    "hall du marché, paille, fromage, carton de lait",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le hall du marché sent le fromage chaud.",
            "narrateur|De la paille craque sous les caisses.",
            "narrateur|Un carton de lait a un chat gris.",
            "narrateur|Les voix montent sous le toit de verre.",
            "narrateur|Une cloche de fromage luit, toute ronde.",
            "maman|Tu as senti, Mila ?",
            "enfant-f|Ça sent la montagne.",
            "enfant-f|Je veux un bout.",
            "maman|On va le dire, alors.",
            "narrateur|En ce moment, maman parle vers la cloche.",
            "narrateur|Sa voix se mêle aux autres voix.",
            "narrateur|Mila a les mots tout prêts.",
            "enfant-f|Un bout !",
            "enfant-f|Celui qui sent la montagne !",
            "narrateur|Les mots tombent sous le toit de verre.",
            "narrateur|Personne ne se tourne.",
            "narrateur|La cloche reste loin, derrière la paille.",
            "enfant-f|Maman.",
            "narrateur|Maman parle encore, un doigt vers le tarif.",
            "narrateur|Mila ferme la bouche.",
            "narrateur|Elle lève la main, tout droit.",
            "narrateur|Sa main reste en l'air, près du carton.",
            "narrateur|Le chat gris du carton la regarde.",
            "narrateur|Une voix s'arrête, puis une autre.",
            "narrateur|Maman se tourne.",
            "maman|Tu voulais dire quelque chose ?",
            "enfant-f|Un bout.",
            "enfant-f|Celui qui sent la montagne.",
            "maman|Je t'entends, maintenant.",
            "narrateur|Un petit triangle blanc arrive dans un papier.",
            "narrateur|Il est frais, un peu gras.",
            "enfant-f|C'est lui.",
            "maman|Merci, Mila.",
            "maman|Tu as attendu, et je t'ai entendue.",
            "narrateur|Mila tient le papier à deux mains.",
            "narrateur|Ça sent le lait et l'herbe sèche.",
            "maman|On goûte sur le banc, dehors ?",
            "enfant-f|Oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Mila veut parler.",
            "narrateur|Que fait-elle d'abord ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le banc dehors est tiède.",
            "narrateur|Mila ouvre le papier.",
            "narrateur|Le triangle a des petits trous.",
            "enfant-f|Ça sent vraiment la montagne.",
            "maman|Tu croques ?",
            "enfant-f|Oui.",
            "narrateur|Le fromage est doux, un peu piquant.",
            "enfant-f|Tu m'as entendue.",
            "maman|Oui.",
            "maman|Quand les voix se sont tues un peu.",
            "maman|Quand ta main était là.",
            "narrateur|Le carton de lait est dans le cabas.",
            "narrateur|Le chat gris les regarde encore.",
            "maman|Il te plaît, le chat ?",
            "enfant-f|Il a des moustaches trop longues.",
            "narrateur|Mila lèche un peu de gras au pouce.",
            "narrateur|Le papier craque, tout léger.",
            "maman|Il en reste ?",
            "enfant-f|Un tout petit bout.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman plie le papier vide.",
            "narrateur|Il sent encore la montagne.",
            "maman|On rentre ?",
            "enfant-f|Oui.",
            "enfant-f|J'ai eu mon bout.",
            "maman|Oui.",
            "maman|Je t'ai entendue.",
            "narrateur|Le hall rumine, plus loin, plus bas.",
            "narrateur|La paille reste collée à une chaussure.",
            "maman|Tu la secoues ?",
            "enfant-f|Oui, maman.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le papier vide sent encore le lait.",
            "enfant-f|Tu m'as entendue.",
            "maman|Oui.",
            "narrateur|Le chat gris reste sur le carton.",
            "narrateur|Le hall est loin, maintenant.",
        ],
    },
    {
        "expected_answer": "attendre",
        "accepted_examples": "attendre | elle attend | lever la main | la main",
        "retry_prompt": "Personne ne l'entend. Que fait Mila d'abord ?",
    },
    "Mila veut le fromage de la montagne. Elle parle trop tôt, le hall couvre. "
    "Elle lève la main, attend, maman l'entend. Elles goûtent sur le banc.",
    "Pas « il faut attendre ». D16 Mila, maman. Marché couvert.",
)

# ---------------------------------------------------------------------------
# ATOM-COL.ECO.002-04 N3 Nina, maman — sentier, mousse, fenêtre du refuge
# ---------------------------------------------------------------------------
story(
    "ATOM-COL.ECO.002-04",
    "Nina veut montrer sa pomme de pin et boire le cacao du refuge. "
    "Elle parle trop tôt. La vapeur et les voix couvrent. Elle lève la main, on l'entend.",
    "Le cacao de la fenêtre",
    "Nina, maman",
    "sentier de mousse, refuge de montagne, fenêtre de cacao",
    {
        "CHK_T0000_P0000": [
            "narrateur|La mousse des sapins colle aux chaussures.",
            "narrateur|L'air sent la résine froide.",
            "narrateur|Une pomme de pin roule dans la poche.",
            "narrateur|Elle chatouille les doigts, tout sec.",
            "narrateur|Le refuge a une fenêtre allumée.",
            "maman|Tu as vu la vapeur, Nina ?",
            "enfant-f|Ça sent le cacao.",
            "enfant-f|Je veux en boire.",
            "enfant-f|Et montrer ma pomme de pin.",
            "maman|On va le dire, à la fenêtre.",
            "narrateur|En ce moment, maman parle vers le bois.",
            "narrateur|Sa voix se mêle à la vapeur.",
            "narrateur|Nina a les mots tout prêts.",
            "enfant-f|Du cacao !",
            "enfant-f|Et ma pomme de pin !",
            "narrateur|Les mots tombent dans la vapeur chaude.",
            "narrateur|Personne ne se tourne.",
            "narrateur|Deux tasses fument, trop loin.",
            "enfant-f|Maman.",
            "narrateur|Maman parle encore, un gant sur le rebord.",
            "narrateur|Nina ferme la bouche.",
            "narrateur|Elle lève la main, tout droit.",
            "narrateur|La pomme de pin est dans l'autre main.",
            "narrateur|Sa main reste en l'air, près de la vitre.",
            "narrateur|La vapeur s'écarte un peu.",
            "narrateur|Maman se tourne.",
            "maman|Tu voulais dire quelque chose ?",
            "enfant-f|Du cacao.",
            "enfant-f|Et ça, pour le rebord.",
            "maman|Je t'entends, maintenant.",
            "narrateur|Une tasse chaude arrive, toute ronde.",
            "narrateur|Nina pose la pomme de pin sur le bois.",
            "enfant-f|Elle ressemble à un hérisson.",
            "maman|Merci, Nina.",
            "maman|Tu as attendu, et je t'ai entendue.",
            "narrateur|Le cacao brûle un peu la lèvre.",
            "narrateur|Il sent le bois et le lait.",
            "maman|On souffle ensemble ?",
            "enfant-f|Fffff.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina veut parler.",
            "narrateur|Que fait-elle d'abord ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La pomme de pin sèche sur le rebord.",
            "narrateur|Nina souffle encore sur la tasse.",
            "narrateur|Un nuage court sur le cacao.",
            "enfant-f|Il est moins chaud.",
            "maman|Tu goûtes ?",
            "enfant-f|Oui.",
            "narrateur|Une moustache brune reste au-dessus de la lèvre.",
            "enfant-f|Tu m'as entendue.",
            "maman|Oui.",
            "maman|Quand la vapeur s'est écartée.",
            "maman|Quand ta main était là.",
            "narrateur|Un grelot tinte, plus bas sur le sentier.",
            "narrateur|La mousse brille encore aux chaussures.",
            "maman|Ta pomme de pin tient bien ?",
            "enfant-f|Sur le bois, oui.",
            "narrateur|Nina la tourne d'un doigt.",
            "narrateur|Les écailles font un tout petit bruit.",
            "maman|On la reprend, après ?",
            "enfant-f|Dans la poche.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|La tasse est vide, encore chaude.",
            "narrateur|Nina reprend la pomme de pin.",
            "maman|On redescend ?",
            "enfant-f|Oui.",
            "enfant-f|J'ai bu le cacao.",
            "maman|Oui.",
            "maman|Je t'ai entendue.",
            "narrateur|Le sentier sent la mousse et le lait.",
            "narrateur|La fenêtre reste allumée, plus loin.",
            "maman|Elle est bien dans la poche ?",
            "enfant-f|Elle chatouille encore.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La pomme de pin chatouille la poche.",
            "enfant-f|Tu m'as entendue.",
            "maman|Oui.",
            "narrateur|Une moustache de cacao sèche un peu.",
            "narrateur|Les sapins sentent encore la résine.",
        ],
    },
    {
        "expected_answer": "attendre",
        "accepted_examples": "attendre | elle attend | lever la main | la main",
        "retry_prompt": "Personne ne l'entend. Que fait Nina d'abord ?",
    },
    "Nina veut du cacao et montrer sa pomme de pin. Elle parle trop tôt. "
    "La vapeur couvre. Elle lève la main, maman l'entend. Elles soufflent.",
    "Pas « il faut attendre ». D16 Nina, maman. Refuge.",
)

# ---------------------------------------------------------------------------
# ATOM-COL.ECO.002-05 N1 Aniss, papa — cour d'immeuble, pompon, ballon
# ---------------------------------------------------------------------------
story(
    "ATOM-COL.ECO.002-05",
    "Aniss veut dire que le ballon est rouge comme son pompon. Il parle trop tôt. "
    "L'écho de la cour couvre. Il lève la main, il attend, puis papa l'entend.",
    "Le ballon du pompon",
    "Aniss, papa, maman",
    "cour d'immeuble, rampe, pierre mouillée, ballon rouge",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le pompon rouge tape la rampe.",
            "narrateur|La laine pique un peu les doigts.",
            "narrateur|La cour sent la pierre mouillée.",
            "narrateur|Un seau laisse une flaque ronde.",
            "narrateur|Une gouttière cliquette, tout bas.",
            "narrateur|Le ballon rouge attend près du mur.",
            "narrateur|Il est un peu lisse, un peu chaud.",
            "papa|Tu as vu le ballon ?",
            "enfant-m|Il est rouge, papa.",
            "enfant-m|Comme mon pompon.",
            "enfant-m|Je veux le dire.",
            "enfant-m|Et le tapoter.",
            "papa|On va le dire, alors.",
            "narrateur|En ce moment, papa parle à maman.",
            "narrateur|Ils sont près de la porte.",
            "narrateur|Leurs voix tapent les murs.",
            "enfant-m|Il est rouge !",
            "enfant-m|Comme le pompon !",
            "narrateur|Les mots tapent les murs aussi.",
            "narrateur|Personne ne se tourne.",
            "narrateur|Le ballon reste contre le mur.",
            "enfant-m|Papa.",
            "narrateur|Papa parle encore à maman.",
            "narrateur|Aniss ferme la bouche.",
            "narrateur|Il lève la main, tout droit.",
            "narrateur|Sa main reste en l'air.",
            "narrateur|Le pompon pend, tout sage.",
            "narrateur|L'écho s'arrête un peu.",
            "narrateur|Papa se tourne.",
            "papa|Tu voulais dire quelque chose ?",
            "enfant-m|Le ballon est rouge.",
            "enfant-m|Comme mon pompon.",
            "papa|Je t'entends, maintenant.",
            "maman|Je t'entends aussi.",
            "narrateur|Aniss tapote le ballon.",
            "narrateur|Le ballon tremble, tout doux.",
            "narrateur|Il revient contre le genou.",
            "enfant-m|Il danse.",
            "papa|Merci, Aniss.",
            "papa|Tu as attendu.",
            "papa|Et je t'ai entendu.",
            "narrateur|Le caoutchouc sent un peu chaud.",
            "narrateur|Le pompon reste sur le manteau.",
            "maman|Tu veux encore un tapot ?",
            "enfant-m|Oui.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Aniss veut parler.",
            "narrateur|Que fait-il d'abord ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le ballon revient, tout lent.",
            "narrateur|Aniss le tapote encore.",
            "narrateur|Il fait un petit floup.",
            "narrateur|La pierre de la cour est froide.",
            "narrateur|Une goutte tombe du seau.",
            "enfant-m|Il est rouge.",
            "papa|Comme le pompon ?",
            "enfant-m|Oui.",
            "enfant-m|Tu m'as entendu.",
            "papa|Oui.",
            "papa|Quand l'écho s'est tu.",
            "papa|Quand ta main était là.",
            "narrateur|Maman pose le doudou sur une marche.",
            "narrateur|Le doudou a une oreille pliée.",
            "maman|Il t'attend, ce soir.",
            "enfant-m|Oui, maman.",
            "narrateur|Aniss frotte le pompon au ballon.",
            "narrateur|Laine et caoutchouc se touchent.",
            "papa|Ils sont pareils, un peu ?",
            "enfant-m|Tous les deux rouges.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa reprend le manteau.",
            "narrateur|Le pompon rebondit encore.",
            "papa|On rentre ?",
            "enfant-m|Oui.",
            "enfant-m|Le ballon a dansé.",
            "papa|Oui.",
            "papa|Je t'ai entendu.",
            "maman|Le doudou est dans le sac.",
            "maman|Tu le prends ?",
            "enfant-m|Oui, maman.",
            "narrateur|La flaque du seau reste ronde.",
            "narrateur|La rampe est froide, maintenant.",
            "narrateur|Le manteau sent la laine mouillée.",
            "narrateur|Le doudou sent la maison.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le pompon tape encore la rampe.",
            "enfant-m|Tu m'as entendu.",
            "papa|Oui.",
            "narrateur|Le ballon reste contre le mur.",
            "narrateur|La cour sent la pierre, calme.",
        ],
    },
    {
        "expected_answer": "attendre",
        "accepted_examples": "attendre | il attend | lever la main | la main",
        "retry_prompt": "Personne ne l'entend. Que fait Aniss d'abord ?",
    },
    "Aniss veut dire que le ballon est rouge comme le pompon. Il parle trop tôt. "
    "L'écho couvre. Il lève la main, papa l'entend. Ils tapotent.",
    "N1. Pas « il faut attendre ». D16 Aniss, papa, maman. Cour d'immeuble.",
)

# ---------------------------------------------------------------------------
# ATOM-VIV.ANI.003-03 N3 Amir, papa — alpage, chèvre puis chien
# ---------------------------------------------------------------------------
story(
    "ATOM-VIV.ANI.003-03",
    "Amir veut que la chèvre boive, pour la regarder manger son pain. "
    "Le seau est vide. Avec papa, ils versent. Le chien halète, lui aussi. Ils remplissent son bol.",
    "L'eau de la chèvre",
    "Amir, papa",
    "alpage en fin de jour, cloche lointaine, pain, seau",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'herbe de l'alpage sent le foin chaud.",
            "narrateur|Une cloche tinte, très loin.",
            "narrateur|Le pain de la musette est encore tiède.",
            "narrateur|Un seau de fer brille près du muret.",
            "papa|Tu as vu la chèvre, Amir ?",
            "enfant-m|Elle a la barbe, papa.",
            "papa|Elle a aussi soif, je crois.",
            "narrateur|Le seau est presque vide.",
            "narrateur|Une croûte sèche au fond.",
            "enfant-m|Je veux qu'elle boive.",
            "enfant-m|Pour la regarder, avec mon pain.",
            "papa|On verse ensemble ?",
            "enfant-m|Oui.",
            "narrateur|En ce moment, Amir tient l'anse avec papa.",
            "narrateur|Le fer est chaud, un peu rêche.",
            "narrateur|Ils penchent tout doux vers l'auge.",
            "narrateur|L'eau arrive, un filet, pas trop.",
            "enfant-m|Elle vient.",
            "papa|On recule un peu.",
            "narrateur|La chèvre avance, tout prudent.",
            "narrateur|Sa langue tape l'eau, toute rapide.",
            "enfant-m|Elle boit.",
            "papa|Oui.",
            "papa|Merci, Amir.",
            "narrateur|Amir croque son pain.",
            "narrateur|Le pain sent le foin, maintenant.",
            "narrateur|Un chien halète près du muret.",
            "narrateur|Sa langue est longue, toute rose.",
            "narrateur|Son bol de terre est sec, tout blanc.",
            "enfant-m|Lui aussi.",
            "enfant-m|Il a soif.",
            "papa|Tu as vu sa langue ?",
            "enfant-m|Oui.",
            "enfant-m|On lui en met ?",
            "papa|Ensemble, encore.",
            "narrateur|Ils portent le seau, plus léger.",
            "narrateur|Un peu d'eau reste, assez pour le bol.",
            "narrateur|Amir pose deux mains, papa aussi.",
            "narrateur|Le filet tombe, tout lent, au centre.",
            "narrateur|Le chien lape, tout près, tout bruyant.",
            "enfant-m|Il boit, lui aussi.",
            "papa|Oui.",
            "papa|Il avait soif.",
            "narrateur|Une goutte tombe dans l'herbe.",
            "narrateur|L'herbe la garde, sombre.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir donne à boire.",
            "narrateur|Comment ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La chèvre se lèche la barbe.",
            "narrateur|Le chien se couche près du bol.",
            "enfant-m|Les deux ont bu.",
            "papa|Oui.",
            "papa|Tu as tenu le seau avec moi.",
            "papa|Tout doux.",
            "papa|Merci, Amir.",
            "papa|Tu as vu la différence ?",
            "enfant-m|L'auge, et le bol.",
            "papa|Et la même eau.",
            "narrateur|La cloche tinte encore, plus bas.",
            "narrateur|Le pain a une marque de dent.",
            "enfant-m|Il goûte l'herbe.",
            "papa|Tu en donnes à la chèvre ?",
            "enfant-m|Un tout petit bout.",
            "narrateur|La chèvre le prend, toute douce.",
            "narrateur|Ses dents font un petit bruit.",
            "papa|On reste un peu ?",
            "enfant-m|Un peu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le soleil glisse derrière le muret.",
            "narrateur|L'ombre est longue, plus froide.",
            "papa|On reprend la musette ?",
            "enfant-m|Oui.",
            "enfant-m|Ils ont bu.",
            "papa|Oui.",
            "papa|Toi aussi, tu as bu l'air du soir.",
            "narrateur|Le seau vide est léger, maintenant.",
            "narrateur|Il tape la jambe, tout doux.",
            "papa|On le pose près des bottes ?",
            "enfant-m|Oui.",
            "narrateur|Le chien ronfle déjà, un peu.",
            "narrateur|La chèvre broute, calme.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Une goutte reste dans l'herbe.",
            "enfant-m|Elle a bu.",
            "enfant-m|Le chien aussi.",
            "papa|Oui.",
            "narrateur|Le pain sent encore le foin chaud.",
            "narrateur|La cloche tinte, très loin.",
        ],
    },
    {
        "expected_answer": "avec papa",
        "accepted_examples": "avec papa | avec un adulte | doux | tout doux | avec l'adulte",
        "retry_prompt": "Amir tient le seau. Comment donne-t-il à boire ?",
    },
    "Amir veut que la chèvre boive pour la regarder avec son pain. Seau vide. "
    "Avec papa, ils versent. Le chien a soif aussi. Ils remplissent le bol.",
    "Pas « même leçon, autre animal ». Second animal = soif vécue. D16 Amir, papa.",
)

# ---------------------------------------------------------------------------
# ATOM-LAN.MOT.001-04 N2 Raphaël, maman — cabas, cheval perdu, mot retrouvé
# ---------------------------------------------------------------------------
story(
    "ATOM-LAN.MOT.001-04",
    "Raphaël veut son cheval de bois pour lui faire sentir la mandarine. "
    "Le cheval est perdu sous le bazar du cabas. En sortant fruits et habits, il le trouve, et le mot aussi.",
    "Le cheval sous la poire",
    "Raphaël, maman",
    "cuisine après la pluie, cabas mouillé, mandarine",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le cabas laisse une flaque près du paillasson.",
            "narrateur|Il sent la mandarine, fort.",
            "narrateur|Des bottes gouttent dans l'entrée.",
            "narrateur|Une écharpe jaune glisse d'une anse.",
            "narrateur|La pluie tapote encore le rebord.",
            "maman|Tu as senti, Raphaël ?",
            "enfant-m|Ça pique le nez.",
            "maman|C'est la mandarine.",
            "enfant-m|Je veux mon cheval.",
            "enfant-m|Il va la sentir, lui aussi.",
            "maman|Il était dans le cabas.",
            "narrateur|En ce moment, Raphaël fouille le tissu.",
            "narrateur|Le tissu est rêche, tout froid.",
            "narrateur|Une poire roule, lisse.",
            "narrateur|Un gant tombe, encore mouillé.",
            "enfant-m|Il n'est pas là.",
            "enfant-m|Où est mon cheval ?",
            "maman|On ne le voit pas, sous tout ça.",
            "narrateur|Raphaël sort la poire.",
            "narrateur|Elle est froide, toute ronde.",
            "enfant-m|Poire.",
            "maman|Elle va avec les ronds froids ?",
            "enfant-m|Dans le saladier.",
            "narrateur|La poire sonne dans le saladier.",
            "narrateur|Il sort la mandarine.",
            "narrateur|La peau est granuleuse, un peu mouillée.",
            "enfant-m|Mandarine.",
            "enfant-m|Avec la poire.",
            "narrateur|Le saladier sent déjà le fruit.",
            "narrateur|Raphaël ramasse l'écharpe jaune.",
            "narrateur|Elle est longue, toute douce, un peu humide.",
            "enfant-m|Écharpe.",
            "maman|Elle va sécher où ?",
            "enfant-m|Sur la chaise.",
            "narrateur|Un papier collé vient avec l'écharpe.",
            "narrateur|Des lettres y sont, un peu délavées.",
            "enfant-m|C'est un mot.",
            "maman|Tu le connais ?",
            "enfant-m|Pas encore.",
            "narrateur|Raphaël prend le gant mouillé.",
            "narrateur|Sous le gant, quelque chose de dur.",
            "enfant-m|Mon cheval !",
            "narrateur|Le petit cheval de bois est froid, luisant.",
            "narrateur|Une oreille a une goutte dessus.",
            "enfant-m|Cheval.",
            "maman|C'est le mot, aussi.",
            "narrateur|Maman montre le papier délavé.",
            "narrateur|Les lettres disent le même nom.",
            "enfant-m|Cheval.",
            "enfant-m|Je l'avais perdu.",
            "maman|Il était sous le gant.",
            "maman|Merci, Raphaël.",
            "maman|Tu as sorti les ronds, et les doux.",
            "narrateur|Raphaël pose le cheval près du saladier.",
            "narrateur|Le bois touche la mandarine.",
            "enfant-m|Il la sent.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël cherche le cheval.",
            "narrateur|Que fait-il des fruits et des habits ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le cabas est presque vide, enfin.",
            "narrateur|Une chaussette reste au fond, oubliée.",
            "enfant-m|Chaussette.",
            "maman|Avec l'écharpe, sur la chaise ?",
            "enfant-m|Oui.",
            "narrateur|La pile de la chaise est douce, un peu humide.",
            "narrateur|Le saladier est plein, tout frais.",
            "maman|Le cheval a trouvé la mandarine ?",
            "enfant-m|Il la sent.",
            "maman|Et toi, tu as trouvé le mot.",
            "enfant-m|Cheval.",
            "narrateur|Raphaël fait avancer le bois sur la table.",
            "narrateur|Toc, toc, tout petit.",
            "maman|Il va jusqu'à la poire ?",
            "enfant-m|Oui.",
            "narrateur|La poire est un grand rocher, pour lui.",
            "narrateur|La mandarine est un soleil.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman épluche la mandarine.",
            "narrateur|Le jus pique un peu les doigts.",
            "maman|C'est acide, un peu ?",
            "enfant-m|Oui.",
            "enfant-m|C'est bon.",
            "narrateur|Raphaël en pose un quartier près du cheval.",
            "enfant-m|Pour lui.",
            "maman|Il est revenu.",
            "maman|Toi aussi, tu as retrouvé le mot.",
            "narrateur|La pluie ralentit sur le rebord.",
            "narrateur|Le cabas sèche, enfin vide.",
            "maman|On garde la poire pour plus tard ?",
            "enfant-m|Oui, maman.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Le cheval de bois sent la mandarine.",
            "enfant-m|Je l'ai retrouvé.",
            "maman|Oui.",
            "narrateur|Le mot sèche près de l'écharpe.",
            "narrateur|Le cabas ne cache plus rien.",
        ],
    },
    {
        "expected_answer": "classer",
        "accepted_examples": "classer | ensemble | ranger | catégorie | le cheval | fruits",
        "retry_prompt": "Les ronds vont au saladier. Les doux sur la chaise. Que fait Raphaël ?",
    },
    "Raphaël veut son cheval de bois pour la mandarine. Perdu sous le cabas. "
    "Il sort poire et écharpe pour le trouver. Le mot cheval revient avec le jouet.",
    "Pas « on va ranger ». Perte vécue, pas leçon. D16 Raphaël, maman.",
)
