#!/usr/bin/env python3
"""F-NAR-008 — ATOM-TMP.JOU.001-06..08 + ATOM-TMP.MET.001-01..05."""
from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# JOU-06 N2 Victorino, maman — pré, vache lointaine, soleil puis lune
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.JOU.001-06",
    "Victorino veut aller voir la vache loin dans le pré. Le soleil chauffe l'herbe. La vache se cache. Ils la retrouvent. Le soir, la lune accroche le toit. Ils rentrent.",
    "La vache loin dans le pré",
    "Victorino, maman",
    "pré au bord de la maison, puis retour la nuit",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le pré sent le foin chaud.",
            "narrateur|Une clôture de bois brûle un peu au soleil.",
            "narrateur|Loin, une vache brune mange l'herbe.",
            "narrateur|Victorino vit ici, avec maman.",
            "narrateur|La maison est petite, au bord du pré.",
            "narrateur|Un seau d'eau brille près du portail.",
            "maman|Tu as vu la vache, là-bas ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Je veux aller la voir.",
            "maman|On marche dans le pré ?",
            "narrateur|En ce moment, Victorino prend le seau.",
            "narrateur|L'eau cliquette contre le métal.",
            "narrateur|Ils passent le portail de bois.",
            "narrateur|L'herbe est haute et tiède.",
            "narrateur|Des insectes chantent dans les chardons.",
            "narrateur|Le soleil chauffe le dos de Victorino.",
            "maman|Le jour, c'est le soleil.",
            "enfant-m|Il est tout rond.",
            "narrateur|Ils marchent vers la vache.",
            "narrateur|Puis la vache disparaît derrière un buisson.",
            "enfant-m|Elle est partie ?",
            "maman|Elle est derrière.",
            "maman|On avance encore ?",
            "narrateur|Victorino avance dans l'herbe.",
            "narrateur|Une pierre tiède attend sous le pied.",
            "narrateur|Il pose la main dessus.",
            "narrateur|Le soleil l'a chauffée.",
            "narrateur|Derrière le buisson, la vache lève la tête.",
            "enfant-m|Je la vois !",
            "maman|Bravo.",
            "maman|Elle nous regarde.",
            "narrateur|Victorino lève la main.",
            "narrateur|La vache mâche, tout doucement.",
            "narrateur|Une clochette sonne, très loin.",
            "narrateur|Ils restent un moment.",
            "narrateur|Le seau pèse un peu.",
            "maman|On lui laisse de l'eau ?",
            "narrateur|Victorino pose le seau près de la clôture.",
            "narrateur|L'eau tremble au soleil.",
            "narrateur|Le ciel change, tout doucement.",
            "narrateur|Le pré devient plus bleu.",
            "narrateur|Le soleil descend derrière le bois.",
            "maman|Le jour s'en va.",
            "narrateur|Victorino a froid aux mains.",
            "narrateur|Ils reprennent le chemin du portail.",
            "narrateur|Derrière eux, la vache est un point brun.",
            "narrateur|Devant, la maison allume une fenêtre.",
            "narrateur|Le ciel devient bleu foncé.",
            "narrateur|Une lune ronde s'accroche au toit.",
            "enfant-m|La lune !",
            "maman|La nuit, c'est la lune.",
            "maman|On rentre.",
            "narrateur|Ils referment le portail.",
            "narrateur|Le pré sent encore le foin, plus frais.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La lune est accrochée au toit.",
            "narrateur|Quel moment est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Victorino pousse la porte de la maison.",
            "narrateur|L'air dedans sent le pain.",
            "enfant-m|C'est la nuit.",
            "maman|Oui.",
            "maman|Le jour, le soleil.",
            "maman|La nuit, la lune.",
            "narrateur|Victorino enlève ses chaussures d'herbe.",
            "narrateur|Des brins restent sur le paillasson.",
            "narrateur|Il met son pyjama à pois.",
            "maman|La nuit, on fait dodo.",
            "enfant-m|La vache aussi ?",
            "maman|Elle mâche encore un peu.",
            "maman|Puis elle dort dans le pré.",
            "narrateur|Victorino grimpe dans le lit.",
            "narrateur|La fenêtre montre encore la lune.",
            "narrateur|Le pré est sombre, tout calme.",
            "enfant-m|Je l'ai vue.",
            "maman|Oui.",
            "maman|Au soleil, puis sous la lune.",
            "narrateur|Il ferme un peu les yeux.",
            "narrateur|Il revoit la clochette, très loin.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman baisse la lumière.",
            "narrateur|La chambre devient douce.",
            "maman|Tu entends le pré ?",
            "enfant-m|Un peu.",
            "narrateur|Un grillon commence, près de la clôture.",
            "narrateur|Victorino respire, tout lentement.",
            "narrateur|Ses mains sentent encore l'herbe.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Dehors, la lune tient le toit.",
            "narrateur|La vache est un point brun, très loin.",
            "narrateur|Le seau repose près de la clôture.",
            "enfant-m|Bonne nuit, vache.",
            "maman|Bonne nuit.",
            "narrateur|Le foin sent encore, tout frais.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "nuit",
        "accepted_examples": "nuit | la nuit | lune | le soir",
        "retry_prompt": "La lune vient la nuit. Quel moment ?",
    },
)
relecture(
    "ATOM-TMP.JOU.001-06",
    "La vache loin dans le pré",
    "Victorino veut voir la vache dans le pré. Soleil, buisson, seau. Le soir la lune accroche le toit. Ils rentrent.",
    "- Désir : la vache, pas « nommer soleil/lune ».\n"
    "- Ouverture : foin, clôture, vache brune.\n"
    "- Imprévu : la vache disparaît. Ils la retrouvent.\n"
    "- Leçon greffée : jour/soleil, nuit/lune. Fin : lune sur le toit.",
)

# ---------------------------------------------------------------------------
# JOU-07 N3 Sarah, maman — fenêtre du toit, compter les étoiles, nuages, une étoile
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.JOU.001-07",
    "Sarah veut compter les étoiles depuis la fenêtre du toit du grenier. Le soleil chauffe les planches. Le soir, trop de nuages. Une étoile passe quand même. Elles la gardent.",
    "L'étoile du grenier",
    "Sarah, maman",
    "grenier à fenêtre du toit, jour puis nuit",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un carré de ciel tient dans la fenêtre du toit.",
            "narrateur|Un rayon traverse la poussière au-dessus du coffre.",
            "narrateur|Les planches du grenier sentent le bois chaud.",
            "narrateur|Sarah vit ici, avec maman.",
            "narrateur|Un tapis râpé attend sous la fenêtre du toit.",
            "narrateur|Un coussin bleu est posé dessus.",
            "maman|Tu veux monter encore ?",
            "enfant-f|Oui, maman.",
            "enfant-f|Je veux compter les étoiles.",
            "maman|Ce soir, si le ciel se dégage.",
            "narrateur|En ce moment, Sarah s'assoit sur le coussin.",
            "narrateur|Le soleil lui chauffe les genoux.",
            "narrateur|Un oiseau passe dans le carré de ciel.",
            "maman|Le jour, c'est le soleil.",
            "enfant-f|Il est trop fort pour les étoiles.",
            "maman|Elles attendent la nuit.",
            "narrateur|Sarah ouvre le coffre un peu.",
            "narrateur|Une couverture à carreaux sent la lavande.",
            "narrateur|Elles la plient près du tapis.",
            "narrateur|Le rayon glisse vers le mur.",
            "narrateur|La poussière danse moins.",
            "narrateur|Le carré de ciel devient plus pâle.",
            "maman|Le jour s'en va.",
            "narrateur|Sarah reste sous la fenêtre du toit.",
            "narrateur|Le grenier refroidit, tout doucement.",
            "narrateur|Le ciel vire au bleu foncé.",
            "enfant-f|Les étoiles ?",
            "narrateur|Des nuages gris bouchent le carré.",
            "narrateur|Pas une étoile.",
            "narrateur|Pas la lune non plus.",
            "enfant-f|Il y en a trop, des nuages.",
            "maman|On attend un peu ?",
            "narrateur|Sarah pose le menton sur le coussin.",
            "narrateur|Maman s'assoit contre le coffre.",
            "narrateur|Le bois craque, tout bas.",
            "narrateur|Un nuage se déchire, très lentement.",
            "narrateur|Une lune ronde entre dans la fenêtre du toit.",
            "enfant-f|La lune !",
            "maman|La nuit, c'est la lune.",
            "narrateur|Sarah cherche les étoiles autour.",
            "narrateur|Le nuage cache encore presque tout.",
            "enfant-f|Je n'en vois pas.",
            "maman|Regarde le bord, tout à droite.",
            "narrateur|Une étoile minuscule pique le ciel.",
            "enfant-f|Une !",
            "maman|Bravo.",
            "maman|Tu l'as trouvée.",
            "narrateur|Sarah la compte tout haut.",
            "narrateur|Un.",
            "narrateur|Le nuage n'en laisse pas d'autre.",
            "enfant-f|C'est déjà beaucoup.",
            "maman|Oui.",
            "maman|Une étoile, et la lune.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La lune est dans la fenêtre du toit.",
            "narrateur|Quel moment est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Sarah garde les yeux sur le carré.",
            "enfant-f|C'est la nuit.",
            "maman|Oui.",
            "maman|Le jour, le soleil.",
            "maman|La nuit, la lune.",
            "narrateur|Elles enroulent la couverture à carreaux.",
            "narrateur|Sarah a les pieds froids.",
            "maman|On descend se coucher ?",
            "enfant-f|Encore une minute.",
            "narrateur|L'étoile tient toujours, toute seule.",
            "narrateur|La lune glisse un peu dans le bois de la fenêtre du toit.",
            "enfant-f|Je l'ai comptée.",
            "maman|Un.",
            "maman|C'était la tienne.",
            "narrateur|Sarah ferme le coffre.",
            "narrateur|La lavande reste dans l'air.",
            "narrateur|Elles descendent l'escalier étroit.",
            "narrateur|Les marches parlent sous les pieds.",
            "narrateur|Dans la chambre, Sarah met son pyjama.",
            "maman|La nuit, on fait dodo.",
            "enfant-f|Mon étoile aussi ?",
            "maman|Elle veille un peu.",
            "narrateur|Sarah se glisse sous le drap.",
            "narrateur|Elle revoit le carré, et le un.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman baisse la lumière.",
            "narrateur|La chambre sent encore le bois du grenier.",
            "maman|Tu la revois ?",
            "enfant-f|Oui.",
            "enfant-f|Tout à droite.",
            "narrateur|Sarah respire, tout doucement.",
            "narrateur|Ses genoux gardent un peu de soleil.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Au-dessus, la fenêtre du toit tient encore le ciel.",
            "narrateur|La lune y est, ronde.",
            "narrateur|L'étoile minuscule pique le bord.",
            "enfant-f|Un.",
            "maman|Un.",
            "narrateur|Le coussin bleu attend sous le carré.",
        ],
    },
    {"CHK_T0000_P0000": "enfants_parc"},
    {
        "expected_answer": "nuit",
        "accepted_examples": "nuit | la nuit | lune | le soir",
        "retry_prompt": "La lune vient la nuit. Quel moment ?",
    },
)
relecture(
    "ATOM-TMP.JOU.001-07",
    "L'étoile du grenier",
    "Sarah veut compter les étoiles depuis la fenêtre du toit. Trop de nuages. Une étoile quand même. Soleil le jour, lune la nuit.",
    "- Désir : compter les étoiles, pas la leçon jour/nuit.\n"
    "- Ouverture : fenêtre du toit, poussière, coffre, lavande.\n"
    "- Imprévu : nuages. Une étoile à droite.\n"
    "- Fin : le un, le coussin bleu.",
)

# ---------------------------------------------------------------------------
# JOU-08 N2 Amir, maman — rivière, soleil sur l'eau, lune depuis le pont
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.JOU.001-08",
    "Amir veut faire flotter une feuille sur la rivière. Le soleil danse sur l'eau. La feuille se coince. Ils la dégagent. Plus tard, la lune depuis le pont.",
    "Le soleil sur l'eau",
    "Amir, maman",
    "rivière et pont de pierre, jour puis nuit",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sous le pont, l'eau cliquette contre les pierres.",
            "narrateur|Un poisson fait un rond sur l'eau.",
            "narrateur|Le soleil casse en paillettes jaunes.",
            "narrateur|Amir vit ici, avec maman.",
            "narrateur|La maison est juste après le chemin d'herbes.",
            "narrateur|Une feuille sèche attend près de la berge.",
            "maman|Tu as vu les paillettes ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Je veux faire flotter la feuille.",
            "maman|On la pose tout doucement ?",
            "narrateur|En ce moment, Amir ramasse la feuille.",
            "narrateur|Elle est sèche, un peu recroquevillée.",
            "narrateur|Il s'accroupit au bord.",
            "narrateur|L'eau lui mouille un peu les doigts.",
            "narrateur|Le soleil lui chauffe la nuque.",
            "maman|Le jour, c'est le soleil.",
            "enfant-m|Il danse sur l'eau.",
            "narrateur|Amir pose la feuille.",
            "narrateur|Elle part, toute légère.",
            "narrateur|Puis elle se coince entre deux pierres.",
            "enfant-m|Elle est bloquée.",
            "maman|On l'aide avec un bout de bois ?",
            "narrateur|Amir prend une brindille.",
            "narrateur|Il pousse la feuille, tout doux.",
            "narrateur|Elle se libère.",
            "narrateur|Elle glisse sous le pont.",
            "enfant-m|Elle est partie !",
            "maman|Bravo.",
            "maman|Tu l'as dégagée.",
            "narrateur|Ils restent à écouter l'eau.",
            "narrateur|Un canard passe, très lent.",
            "narrateur|Le soleil descend derrière les saules.",
            "narrateur|L'eau devient plus sombre.",
            "maman|Le jour s'en va.",
            "narrateur|Ils remontent sur le pont de pierre.",
            "narrateur|Les dalles sont encore tièdes.",
            "narrateur|Le ciel vire au bleu foncé.",
            "narrateur|Une lune ronde se pose sur l'eau.",
            "enfant-m|La lune !",
            "maman|La nuit, c'est la lune.",
            "narrateur|Amir se penche un peu.",
            "narrateur|La lune tremble dans la rivière.",
            "enfant-m|Elle flotte aussi.",
            "maman|Comme ta feuille.",
            "maman|On rentre ?",
            "narrateur|Le pont sent la pierre froide, maintenant.",
            "narrateur|L'eau cliquette encore, en bas.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|La lune tremble sur l'eau.",
            "narrateur|Quel moment est-ce ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Amir et maman quittent le pont.",
            "enfant-m|C'est la nuit.",
            "maman|Oui.",
            "maman|Le jour, le soleil.",
            "maman|La nuit, la lune.",
            "narrateur|Le chemin d'herbes est frais.",
            "narrateur|Des grenouilles parlent dans les roseaux.",
            "narrateur|La maison allume sa fenêtre.",
            "enfant-m|Ma feuille est loin.",
            "maman|Elle voyage.",
            "maman|Toi, tu vas au lit.",
            "narrateur|Amir met son pyjama rayé.",
            "maman|La nuit, on fait dodo.",
            "narrateur|Il grimpe dans le lit.",
            "narrateur|De la chambre, on n'entend plus l'eau.",
            "enfant-m|Je la revois.",
            "maman|Les paillettes, puis la lune.",
            "narrateur|Amir ferme un peu les yeux.",
            "narrateur|Il revoit le rond du poisson.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Maman baisse la lumière.",
            "narrateur|La chambre sent l'herbe du chemin.",
            "maman|Tu entends encore l'eau ?",
            "enfant-m|Un peu, dans ma tête.",
            "narrateur|Amir respire, tout lentement.",
            "narrateur|Ses doigts sont secs, maintenant.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Sur le pont, la lune tient l'eau.",
            "narrateur|La feuille voyage quelque part.",
            "narrateur|Le poisson a fini ses ronds.",
            "enfant-m|Bonne nuit, rivière.",
            "maman|Bonne nuit.",
            "narrateur|Les paillettes attendent le soleil.",
        ],
    },
    {},
    {
        "expected_answer": "nuit",
        "accepted_examples": "nuit | la nuit | lune | le soir",
        "retry_prompt": "La lune vient la nuit. Quel moment ?",
    },
)
relecture(
    "ATOM-TMP.JOU.001-08",
    "Le soleil sur l'eau",
    "Amir veut faire flotter une feuille. Elle se coince. Ils la dégagent. Soleil sur l'eau, lune depuis le pont.",
    "- Désir : la feuille sur l'eau, pas la leçon.\n"
    "- Ouverture : pont, poisson, paillettes.\n"
    "- Imprévu : feuille coincée. Brindille.\n"
    "- Fin : lune sur l'eau, feuille en voyage.",
)

# ---------------------------------------------------------------------------
# MET-01 N1 Mila, maman — pluie, flaque du jardin, botte à l'envers
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-01",
    "Mila veut la flaque du jardin. Il pleut. Une botte est à l'envers. Elles la retournent. Mila pose un pied. Ploc.",
    "La flaque du jardin",
    "Mila, maman",
    "maison puis jardin sous la pluie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Sur la vitre, les gouttes courent très vite.",
            "narrateur|Le cerisier du jardin penche sous l'eau.",
            "narrateur|Une flaque ronde attend près du bac.",
            "narrateur|Mila vit ici, avec maman.",
            "narrateur|La maison sent le cacao tiède.",
            "narrateur|Deux tasses attendent sur la table.",
            "narrateur|Le paillasson est déjà mouillé.",
            "narrateur|Une feuille collée y brille.",
            "maman|Tu as vu la flaque ?",
            "enfant-f|Oui, maman.",
            "enfant-f|Je veux aller dedans.",
            "maman|Il pleut fort, tu entends ?",
            "narrateur|En ce moment, Mila va vers la porte.",
            "narrateur|La pluie tape le bois.",
            "narrateur|Maman tend le manteau bleu.",
            "narrateur|Mila glisse les bras dedans.",
            "narrateur|Le tissu est un peu froid.",
            "narrateur|Puis il réchauffe les épaules.",
            "enfant-f|Mes bottes.",
            "narrateur|Une botte est à l'envers.",
            "narrateur|La semelle regarde le plafond.",
            "enfant-f|Elle est drôle.",
            "maman|On la retourne ensemble ?",
            "narrateur|Mila tire la botte.",
            "narrateur|Maman aide un peu.",
            "narrateur|La botte redevient une botte.",
            "enfant-f|L'autre maintenant.",
            "narrateur|L'autre botte est déjà droite.",
            "narrateur|Mila enfile les deux.",
            "narrateur|Ses pieds sont au chaud.",
            "maman|Prête pour la flaque ?",
            "enfant-f|Oui !",
            "narrateur|Elles ouvrent la porte.",
            "narrateur|L'air sent la terre mouillée.",
            "narrateur|La flaque brille comme un miroir.",
            "narrateur|Mila pose un pied.",
            "narrateur|Ploc.",
            "narrateur|Puis l'autre pied.",
            "narrateur|L'eau saute sur le manteau.",
            "enfant-f|Elle est froide !",
            "maman|Tes pieds restent au sec ?",
            "enfant-f|Oui, maman.",
            "maman|Merci.",
            "maman|Tu as retourné la botte.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il pleut dans le jardin.",
            "narrateur|Que met Mila ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Mila reste dans la flaque.",
            "narrateur|Une feuille tourne sur l'eau.",
            "enfant-f|Un bateau !",
            "maman|Tu le pousses ?",
            "narrateur|Mila pousse la feuille.",
            "narrateur|Elle va jusqu'au bord.",
            "narrateur|Le cerisier goutte sur le manteau.",
            "narrateur|Toc toc.",
            "enfant-f|Le cerisier parle.",
            "maman|Il est plein d'eau.",
            "narrateur|Mila fait un autre ploc.",
            "narrateur|L'eau fait des ronds.",
            "narrateur|Le miroir se casse, puis revient.",
            "enfant-f|Encore !",
            "maman|Tu vois tes pieds ?",
            "enfant-f|Ils sont jaunes, en dessous.",
            "narrateur|Les bottes brillent sous l'eau.",
            "maman|Encore un, puis on rentre ?",
            "narrateur|Mila saute tout petit.",
            "narrateur|Un oiseau s'enfuit du cerisier.",
            "narrateur|Ses pieds restent au sec.",
            "narrateur|Le manteau bleu est mouillé dehors.",
            "narrateur|Dedans, Mila a chaud.",
            "narrateur|Une goutte coule jusqu'au nez.",
            "enfant-f|Elle chatouille.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles rentrent.",
            "narrateur|Le cacao est encore tiède.",
            "maman|On pose les bottes ?",
            "enfant-f|Près de la porte.",
            "narrateur|Mila les aligne.",
            "narrateur|Elles sont mouillées, droites.",
            "narrateur|Plus à l'envers.",
            "narrateur|Le manteau goutte sur le crochet.",
            "narrateur|Mila souffle sur sa tasse.",
            "narrateur|La vapeur lui chatouille le nez.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Dehors, la flaque brille encore.",
            "narrateur|La feuille bateau attend au bord.",
            "enfant-f|Ma flaque.",
            "maman|Oui.",
            "narrateur|Les gouttes courent toujours sur la vitre.",
        ],
    },
    {},
    {
        "expected_answer": "bottes",
        "accepted_examples": "bottes | les bottes | manteau | le manteau",
        "retry_prompt": "Il met les bottes. Que met Mila s'il pleut ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-01",
    "La flaque du jardin",
    "Mila veut la flaque. Une botte à l'envers. Elles la retournent. Ploc. La feuille-bateau.",
    "- Désir : la flaque, pas une liste manteau-bottes.\n"
    "- Imprévu : botte à l'envers.\n"
    "- Ouverture : vitre, cerisier, flaque ronde.\n"
    "- Fin : flaque, feuille, gouttes.",
)

# ---------------------------------------------------------------------------
# MET-02 N3 Nino, maman — pluie forte, cabane, gouttière
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-02",
    "Nino veut rejoindre la cabane au fond du jardin. La pluie est forte. La gouttière déborde devant la porte. Ils passent sur le côté. Ils écoutent le toit.",
    "La cabane sous la gouttière",
    "Nino, maman",
    "jardin sous l'orage, cabane au fond",
    {
        "CHK_T0000_P0000": [
            "narrateur|La gouttière déborde dans le bac à fleurs.",
            "narrateur|L'eau tombe en rideau devant les géraniums.",
            "narrateur|Le jardin est un grand bruit.",
            "narrateur|Nino vit ici, avec maman.",
            "narrateur|La cabane de planches attend au fond.",
            "narrateur|Sa porte verte est à peine visible.",
            "maman|Tu entends la gouttière ?",
            "enfant-m|Oui, maman.",
            "enfant-m|Je veux aller dans la cabane.",
            "maman|Sous cette pluie-là ?",
            "enfant-m|Oui.",
            "enfant-m|Pour écouter le toit.",
            "narrateur|En ce moment, Nino prend le manteau épais.",
            "narrateur|Il passe les bras.",
            "narrateur|Le tissu sent encore la pluie d'hier.",
            "narrateur|Maman tend les bottes jaunes.",
            "narrateur|Nino les enfile près du paillasson.",
            "maman|Prêt ?",
            "enfant-m|Prêt.",
            "narrateur|Ils ouvrent la porte.",
            "narrateur|La pluie leur tape les capuches.",
            "narrateur|Le chemin de dalles a disparu sous l'eau.",
            "narrateur|Ils marchent quand même.",
            "narrateur|Les bottes font ploc, ploc, ploc.",
            "narrateur|Devant la cabane, la gouttière verse un mur d'eau.",
            "enfant-m|On ne peut pas entrer.",
            "maman|Le rideau est trop fort.",
            "maman|On passe sur le côté ?",
            "narrateur|Nino glisse le long du mur.",
            "narrateur|L'herbe est haute et mouillée.",
            "narrateur|Maman suit.",
            "narrateur|Ils rejoignent la petite fenêtre.",
            "narrateur|Nino pousse la porte par l'intérieur du cadre.",
            "narrateur|Elle cède.",
            "narrateur|Ils se faufilent.",
            "enfant-m|On est dedans !",
            "maman|Bravo.",
            "maman|Tu as trouvé le côté.",
            "narrateur|La cabane sent le bois mouillé.",
            "narrateur|La pluie tambourine le toit.",
            "narrateur|Nino s'assoit sur la caisse.",
            "narrateur|Une goutte entre par une fente.",
            "narrateur|Elle tombe sur sa botte.",
            "enfant-m|Toc.",
            "maman|Le toit parle.",
            "narrateur|Dehors, la gouttière continue son rideau.",
            "narrateur|Dedans, Nino a chaud dans le manteau.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il fait froid, et il pleut fort.",
            "narrateur|Que met Nino ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Nino pose l'oreille contre une planche.",
            "enfant-m|Ça roule, au-dessus.",
            "maman|C'est l'eau sur le toit.",
            "narrateur|Un seau de bois attend dans le coin.",
            "narrateur|Nino y pose une pomme de pin.",
            "enfant-m|Elle écoute aussi.",
            "maman|On reste encore un peu ?",
            "enfant-m|Oui.",
            "narrateur|La fente laisse encore une goutte.",
            "narrateur|Toc, sur la botte jaune.",
            "narrateur|Nino rit tout bas.",
            "narrateur|Maman s'assoit sur le seuil intérieur.",
            "narrateur|Le rideau d'eau s'affaiblit un peu.",
            "maman|La gouttière se calme.",
            "enfant-m|On pourra sortir par devant.",
            "maman|Bientôt.",
            "narrateur|Ils attendent.",
            "narrateur|Le bois craque, tout doux.",
            "narrateur|Les géraniums, dehors, sont pliés.",
            "narrateur|Nino les voit par la fenêtre verte.",
            "enfant-m|Ils ont trop bu.",
            "maman|Comme la gouttière.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le rideau d'eau n'est plus qu'un filet.",
            "maman|On rentre se sécher ?",
            "enfant-m|Oui.",
            "narrateur|Ils sortent par la porte, cette fois.",
            "narrateur|Les dalles réapparaissent.",
            "narrateur|Nino pose la pomme de pin sur la caisse.",
            "narrateur|La cabane garde le bruit du toit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Au fond du jardin, la porte verte se ferme.",
            "narrateur|La gouttière chante plus bas.",
            "enfant-m|Le toit a parlé.",
            "maman|Oui.",
            "narrateur|Les bottes jaunes sèchent près du paillasson.",
        ],
    },
    {},
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | bottes | le manteau | les bottes",
        "retry_prompt": "Froid et pluie. Manteau ou bottes ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-02",
    "La cabane sous la gouttière",
    "Nino veut la cabane pour écouter le toit. Rideau d'eau devant la porte. Ils passent sur le côté.",
    "- Désir : la cabane, pas la liste d'habits.\n"
    "- Ouverture : gouttière, géraniums, porte verte.\n"
    "- Imprévu : mur d'eau. Passage de côté.\n"
    "- Fin : porte verte, gouttière plus basse.",
)

# ---------------------------------------------------------------------------
# MET-03 N3 Nina, papa — neige fondue + pluie, pain chez le voisin
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-03",
    "Nina veut le pain chaud chez le voisin. La neige fond. Il pleut. Le sac se mouille. Ils le protègent. Le pain sent encore le four.",
    "Le pain dans la neige fondue",
    "Nina, papa",
    "trottoir de neige fondue, maison du voisin",
    {
        "CHK_T0000_P0000": [
            "narrateur|La neige fond en filets gris sur le trottoir.",
            "narrateur|Une gouttière du voisin verse dans une flaque sale.",
            "narrateur|L'air sent le pain, déjà, très loin.",
            "narrateur|Nina vit ici, avec papa.",
            "narrateur|La maison du voisin a une fenêtre jaune.",
            "narrateur|De la vapeur y danse.",
            "papa|Tu as senti le pain ?",
            "enfant-f|Oui, papa.",
            "enfant-f|Je veux y aller.",
            "papa|Il pleut sur la neige fondue.",
            "papa|On se couvre ?",
            "narrateur|En ce moment, Nina prend le manteau lourd.",
            "narrateur|Il sent la laine mouillée d'hier.",
            "narrateur|Papa tend les bottes.",
            "narrateur|Nina les enfile.",
            "narrateur|La neige fondue fait un bruit mou sous la porte.",
            "enfant-f|C'est glissant.",
            "papa|On va doucement.",
            "narrateur|Ils sortent.",
            "narrateur|La pluie pique les capuches.",
            "narrateur|Les filets gris courent vers le caniveau.",
            "narrateur|Nina donne la main à papa.",
            "narrateur|Le sac en toile pend à son poignet.",
            "narrateur|Devant chez le voisin, trois marches luisent.",
            "papa|Tu montes ?",
            "narrateur|Nina pose un pied.",
            "narrateur|La neige fondue fuit sous la botte.",
            "enfant-f|Oups.",
            "papa|Je te tiens.",
            "narrateur|Elle gravit les marches.",
            "narrateur|Papa frappe.",
            "narrateur|La porte s'ouvre sur la vapeur.",
            "narrateur|Le pain est là, trop chaud pour les mains.",
            "enfant-f|Il sent le four !",
            "papa|Merci.",
            "narrateur|Nina tend le sac.",
            "narrateur|Le voisin y glisse le pain.",
            "narrateur|Une goutte de pluie tombe dans le sac.",
            "enfant-f|Le sac est mouillé.",
            "papa|On le serre contre le manteau ?",
            "narrateur|Nina presse le sac contre elle.",
            "narrateur|Le pain reste au chaud, à l'abri.",
            "papa|Bravo.",
            "papa|Tu l'as protégé.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il pleut, et la neige fond.",
            "narrateur|Que met Nina ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Ils redescendent les marches.",
            "narrateur|Nina tient le sac très fort.",
            "enfant-f|Il est encore chaud.",
            "papa|Oui.",
            "papa|On rentre avant qu'il refroidisse.",
            "narrateur|La pluie a grossi les filets gris.",
            "narrateur|Une flaque barre le trottoir.",
            "papa|On la contourne ?",
            "enfant-f|Oui.",
            "narrateur|Nina marche au bord.",
            "narrateur|Ses bottes restent au sec, presque.",
            "narrateur|Le manteau lourd fume un peu.",
            "narrateur|Chez eux, papa ouvre.",
            "narrateur|L'air de la cuisine est plus doux.",
            "narrateur|Nina pose le sac sur la table.",
            "narrateur|Le pain a une croûte dorée.",
            "enfant-f|Pas mouillé !",
            "papa|Tu l'as bien tenu.",
            "narrateur|Papa coupe une tranche.",
            "narrateur|La mie fume.",
            "enfant-f|C'est pour nous.",
            "papa|Oui.",
            "papa|Après la neige fondue.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Nina range les bottes près de la porte.",
            "narrateur|De la neige fondue s'égoutte encore.",
            "papa|Le manteau au crochet ?",
            "enfant-f|Oui.",
            "narrateur|Le pain attend, déjà entamé.",
            "narrateur|La fenêtre du voisin est encore jaune.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|La croûte craque sous les dents.",
            "narrateur|Dehors, les filets gris courent encore.",
            "enfant-f|Il est chaud.",
            "papa|Oui.",
            "narrateur|Le sac mouillé sèche sur la chaise.",
        ],
    },
    {},
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | bottes | le manteau | les bottes",
        "retry_prompt": "Pluie et neige fondue. Que met-on ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-03",
    "Le pain dans la neige fondue",
    "Nina veut le pain du voisin. Neige fondue, pluie, marches luisantes. Le sac se mouille. Elle serre le pain contre le manteau.",
    "- Désir : le pain, pas la leçon d'habits.\n"
    "- Ouverture : filets gris, vapeur, fenêtre jaune.\n"
    "- Imprévu : sac mouillé, marche glissante.\n"
    "- Fin : croûte, mie qui fume.",
)

# ---------------------------------------------------------------------------
# MET-04 N1 Raphaël, papa — averse, poster une lettre, lettre froissée
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-04",
    "Raphaël veut poster une lettre. L'averse arrive. La lettre est un peu froissée. Ils la lissent. Elle tombe dans la boîte rouge.",
    "La lettre sous l'averse",
    "Raphaël, papa",
    "maison puis boîte aux lettres rouge sous l'averse",
    {
        "CHK_T0000_P0000": [
            "narrateur|Une enveloppe attend près du bol de cerises.",
            "narrateur|Elle est blanche, un peu pliée.",
            "narrateur|Les cerises sont rouges, toutes brillantes.",
            "narrateur|Dehors, l'averse commence sur le toit.",
            "narrateur|Ça sent la poussière mouillée.",
            "narrateur|Raphaël vit ici, avec papa.",
            "narrateur|La table est collante d'un jus.",
            "narrateur|La boîte aux lettres rouge est au portail.",
            "narrateur|On la voit par la fenêtre.",
            "enfant-m|Papa, la lettre.",
            "papa|Tu veux la poster ?",
            "enfant-m|Oui.",
            "papa|Il pleut fort, tu entends ?",
            "narrateur|En ce moment, Raphaël prend l'enveloppe.",
            "narrateur|Un coin est froissé.",
            "enfant-m|Elle est bizarre.",
            "papa|On la lisse ?",
            "narrateur|Raphaël passe la main.",
            "narrateur|Papa aide, tout doux.",
            "narrateur|Le coin se déplie, presque.",
            "papa|Bravo.",
            "papa|Elle peut partir.",
            "narrateur|L'averse tape plus fort.",
            "narrateur|Papa tend le manteau.",
            "narrateur|Raphaël glisse les bras.",
            "narrateur|Le manteau sent le tissu froid.",
            "enfant-m|Mes mains.",
            "papa|Dans les poches ?",
            "narrateur|La lettre va dans la grande poche.",
            "narrateur|Elle est à l'abri.",
            "narrateur|Ils ouvrent la porte.",
            "narrateur|L'averse leur pique les joues.",
            "narrateur|Le chemin jusqu'au portail est court.",
            "narrateur|Des flaques déjà.",
            "narrateur|Une gouttière chante à côté.",
            "narrateur|Raphaël marche près de papa.",
            "narrateur|Ses mains restent dans les poches.",
            "narrateur|La poche de la lettre est sèche.",
            "narrateur|La boîte rouge brille sous l'eau.",
            "narrateur|Un oiseau s'est caché dessous.",
            "enfant-m|Elle est là.",
            "papa|Tu sors la lettre ?",
            "narrateur|Raphaël sort l'enveloppe.",
            "narrateur|Un peu froissée, encore.",
            "narrateur|Pas mouillée.",
            "narrateur|Il lève le rabat de la boîte.",
            "narrateur|La lettre tombe dedans.",
            "enfant-m|Toc.",
            "papa|Elle est partie.",
            "papa|Merci.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il pleut fort.",
            "narrateur|Que met Raphaël ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Raphaël referme le rabat.",
            "narrateur|La boîte rouge goutte.",
            "enfant-m|Elle est dedans.",
            "papa|Oui.",
            "papa|Au sec.",
            "narrateur|L'averse chante sur le métal.",
            "narrateur|Raphaël pose la main dessus.",
            "narrateur|C'est froid.",
            "enfant-m|La lettre a chaud ?",
            "papa|Elle est à l'abri.",
            "papa|Tu l'as bien lissée.",
            "narrateur|Ils restent un peu.",
            "narrateur|Une cerise d'eau glisse sur la boîte.",
            "narrateur|L'oiseau sous la boîte picore.",
            "narrateur|Puis ils rentrent.",
            "narrateur|Les chaussures font un bruit mou.",
            "narrateur|Le bol de cerises attend encore.",
            "enfant-m|J'en prends une ?",
            "papa|Oui.",
            "narrateur|Raphaël croque.",
            "narrateur|Le jus est sucré.",
            "narrateur|Il lui reste aux doigts.",
            "narrateur|Dehors, l'averse continue.",
            "narrateur|La fenêtre se voile.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Papa aide à retirer le manteau.",
            "narrateur|Le manteau goutte près de la porte.",
            "papa|La lettre a voyagé ?",
            "enfant-m|Dans la boîte.",
            "narrateur|Raphaël regarde le bol.",
            "narrateur|L'enveloppe n'y est plus.",
            "narrateur|Il prend une autre cerise.",
            "narrateur|Le noyau est dur, tout petit.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Au portail, la boîte rouge brille.",
            "narrateur|La lettre dort dedans.",
            "narrateur|Le coin n'est presque plus froissé.",
            "enfant-m|Toc.",
            "papa|Oui.",
            "narrateur|L'averse chante encore sur le métal.",
            "narrateur|L'oiseau a repris le chemin du toit.",
        ],
    },
    {},
    {
        "expected_answer": "manteau",
        "accepted_examples": "manteau | bottes | le manteau | les bottes",
        "retry_prompt": "Il pleut. Que met Raphaël ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-04",
    "La lettre sous l'averse",
    "Raphaël veut poster la lettre. Coin froissé. Ils la lissent. Poche du manteau. Toc dans la boîte rouge.",
    "- Désir : poster la lettre, pas la liste d'habits.\n"
    "- Ouverture : enveloppe, cerises, averse.\n"
    "- Imprévu : lettre froissée.\n"
    "- Fin : boîte rouge, toc, averse sur le métal.",
)

# ---------------------------------------------------------------------------
# MET-05 N3 Chouchou, maman — manteau trop petit / le bon, square mouillé
# ---------------------------------------------------------------------------
write_story(
    "ATOM-TMP.MET.001-05",
    "Chouchou veut le square mouillé. Le premier manteau est trop petit. Elle prend le bon. Elles vont au tourniquet qui goutte. Chouchou tourne.",
    "Le bon manteau du square",
    "Chouchou, maman",
    "entrée puis square mouillé après la pluie",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le tourniquet du square goutte encore.",
            "narrateur|Les barres brillent, toutes sombres.",
            "narrateur|L'odeur de terre mouillée entre par la porte.",
            "narrateur|Chouchou vit ici, avec maman.",
            "narrateur|Le square est juste après le passage.",
            "enfant-f|Je veux le tourniquet.",
            "maman|Il a plu, tu as vu ?",
            "enfant-f|Oui.",
            "enfant-f|Il goutte.",
            "maman|On se couvre, alors.",
            "narrateur|En ce moment, Chouchou prend un manteau sur le crochet.",
            "narrateur|C'est le rouge, le plus près.",
            "narrateur|Elle passe un bras.",
            "narrateur|L'autre bras résiste.",
            "enfant-f|Il est bizarre.",
            "maman|Les manches s'arrêtent trop tôt.",
            "maman|Il est trop petit, tu sens ?",
            "narrateur|Chouchou le retire.",
            "narrateur|Le rouge retombe sur le crochet.",
            "narrateur|Maman tend l'autre, le bleu.",
            "narrateur|Chouchou glisse les deux bras.",
            "narrateur|Les manches arrivent aux poignets.",
            "enfant-f|Celui-là, oui.",
            "maman|Le bon.",
            "narrateur|Chouchou enfile les bottes près du paillasson.",
            "narrateur|Elles sont encore un peu humides.",
            "maman|Prête pour le square ?",
            "enfant-f|Oui !",
            "narrateur|Elles sortent.",
            "narrateur|Le passage sent la pierre mouillée.",
            "narrateur|Une flaque barre une dalle.",
            "narrateur|Chouchou la contourne.",
            "narrateur|Le square s'ouvre, tout luisant.",
            "narrateur|Le tourniquet tourne tout seul, un peu, sous le vent.",
            "enfant-f|Il m'attend.",
            "maman|Tu y vas ?",
            "narrateur|Chouchou pose les mains sur une barre.",
            "narrateur|C'est froid, et mouillé.",
            "narrateur|Elle pousse.",
            "narrateur|Le tourniquet part.",
            "enfant-f|Ça glisse !",
            "maman|Bravo.",
            "maman|Tu l'as fait démarrer.",
            "narrateur|L'eau saute des barres.",
            "narrateur|Le manteau bleu la reçoit.",
            "narrateur|Chouchou a chaud dedans.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Il a plu, le square est mouillé.",
            "narrateur|Que met Chouchou ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Chouchou tourne encore.",
            "narrateur|Les bottes tapent les dalles mouillées.",
            "enfant-f|Plus vite !",
            "maman|Un peu, pas trop.",
            "narrateur|Le tourniquet chante, tout rouillé.",
            "narrateur|Une goutte part d'une barre.",
            "narrateur|Elle atterrit sur le nez de Chouchou.",
            "enfant-f|Ah !",
            "maman|Le square te salue.",
            "narrateur|Chouchou ralentit.",
            "narrateur|Elle descend.",
            "narrateur|Ses joues sont rouges.",
            "narrateur|Le manteau bleu est mouillé aux manches.",
            "narrateur|Les manches, assez longues, l'ont protégée.",
            "enfant-f|Le rouge n'aurait pas suffi.",
            "maman|Tu as bien choisi.",
            "narrateur|Elles vont jusqu'au banc.",
            "narrateur|Le bois est sombre, encore plein d'eau.",
            "maman|On s'assoit un moment ?",
            "enfant-f|Oui.",
            "narrateur|Chouchou s'assoit au bord.",
            "narrateur|Le tourniquet s'arrête, goutte encore.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Elles rentrent par le passage.",
            "narrateur|Chouchou retire le manteau bleu.",
            "maman|Le rouge reste au crochet ?",
            "enfant-f|Pour plus tard.",
            "narrateur|Les bottes s'alignent près du paillasson.",
            "narrateur|De l'eau de square s'égoutte.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "narrateur|Au square, le tourniquet goutte encore.",
            "narrateur|Les barres brillent, plus calmes.",
            "enfant-f|Il m'a attendue.",
            "maman|Oui.",
            "narrateur|Le manteau bleu sèche, les manches longues.",
        ],
    },
    {},
    {
        "expected_answer": "bottes",
        "accepted_examples": "bottes | les bottes | manteau | le manteau",
        "retry_prompt": "Il met les bottes. Que met Chouchou s'il pleut ?",
    },
)
relecture(
    "ATOM-TMP.MET.001-05",
    "Le bon manteau du square",
    "Chouchou veut le tourniquet mouillé. Le manteau rouge est trop petit. Elle prend le bleu. Elle tourne. Une goutte sur le nez.",
    "- Désir : le square, pas la checklist.\n"
    "- Ouverture : tourniquet qui goutte, terre mouillée.\n"
    "- Imprévu : manteau trop petit.\n"
    "- Fin : tourniquet, manches longues qui sèchent.",
)
