#!/usr/bin/env python3
"""F-NAR-008 — merged.json ATOM-VIV.ANI.002-09 + ATOM-VIV.ANI.003-01..07."""
from __future__ import annotations

from _lib import relecture, write_story

# ---------------------------------------------------------------------------
# 002-09 N1 Mila, maman, papa — pré, barrière, poulain blanc
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.002-09",
    "Mila veut que le poulain blanc vienne près de la barrière. Ils restent avec papa et maman. Le poulain s'approche. Elle dit les trois noms.",
    "Le poulain blanc",
    "Mila, maman, papa",
    "pré derrière la barrière, matin brumeux",
    {
        "CHK_T0000_P0000": [
            "narrateur|La brume repose sur le pré.",
            "narrateur|L'herbe brille, toute mouillée.",
            "narrateur|Ça sent le foin humide.",
            "narrateur|Une goutte tombe du bois.",
            "narrateur|La barrière est froide.",
            "maman|Tes boutons, Mila.",
            "narrateur|Maman noue le manteau.",
            "papa|On va voir les bêtes ?",
            "enfant-f|Le blanc.",
            "enfant-f|Je veux le blanc.",
            "papa|On marche ensemble.",
            "narrateur|Le chemin est gras.",
            "narrateur|Les bottes font un petit bruit.",
            "narrateur|Floc, floc.",
            "maman|Tu tiens ma main ?",
            "enfant-f|Oui, maman.",
            "narrateur|Un oiseau part du buisson.",
            "narrateur|Le pré s'ouvre, tout large.",
            "narrateur|En ce moment, Mila tient la barrière.",
            "narrateur|Le bois est rêche sous ses doigts.",
            "narrateur|Trois bêtes mangent l'herbe.",
            "papa|Tu les vois ?",
            "enfant-f|Oui.",
            "narrateur|Un cheval brun lève la tête.",
            "narrateur|Sa crinière est sombre.",
            "narrateur|Une jument grise broute près de lui.",
            "narrateur|Son ventre est rond, tout calme.",
            "narrateur|Derrière, un poulain blanc.",
            "narrateur|Il est petit.",
            "narrateur|Il a une étoile au front.",
            "enfant-f|Le blanc !",
            "enfant-f|Il vient ?",
            "maman|On reste ici.",
            "maman|Près de la barrière.",
            "papa|Avec nous.",
            "narrateur|Mila pose un pied vers l'herbe.",
            "narrateur|L'herbe du pré, de l'autre côté.",
            "maman|Les pieds restent ici, Mila.",
            "maman|On regarde.",
            "enfant-f|Il est loin.",
            "papa|On attend.",
            "papa|Tout doux.",
            "narrateur|Le poulain se cache un peu.",
            "narrateur|La jument passe devant.",
            "narrateur|On ne voit plus l'étoile.",
            "enfant-f|Il est parti ?",
            "maman|Non.",
            "maman|Il est là.",
            "papa|Cheval.",
            "papa|Jument.",
            "papa|Poulain.",
            "maman|Trois noms de la famille.",
            "enfant-f|Cheval.",
            "enfant-f|Jument.",
            "enfant-f|Poulain.",
            "maman|Le petit, c'est le poulain.",
            "narrateur|Mila répète, tout bas.",
            "enfant-f|Poulain.",
            "narrateur|Un souffle blanc sort du pré.",
            "narrateur|Le poulain avance d'un pas.",
            "narrateur|Puis d'un autre.",
            "papa|Tu vois l'étoile ?",
            "enfant-f|Oui, papa.",
            "narrateur|Le bois de la barrière tremble un peu.",
            "narrateur|Mila serre le bois.",
            "narrateur|Elle ne tend pas la main.",
            "maman|On reste près de nous.",
            "enfant-f|Je reste.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Quel est le petit de la jument ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le poulain blanc s'approche encore.",
            "narrateur|Ses sabots tapent l'herbe mouillée.",
            "narrateur|Toc, tout mou.",
            "papa|Le petit, c'est le poulain.",
            "enfant-f|Poulain.",
            "maman|Bravo.",
            "maman|Tu as dit les trois noms.",
            "narrateur|Le cheval brun écoute.",
            "narrateur|La jument grise broute.",
            "narrateur|Le poulain lève le nez.",
            "narrateur|Sa moustache est mouillée.",
            "enfant-f|Il a une étoile.",
            "papa|Oui.",
            "papa|Comme un dessin.",
            "maman|Tu restes à la barrière ?",
            "enfant-f|Oui, maman.",
            "narrateur|Mila a les mains sur le bois.",
            "narrateur|Le bois sent la pluie d'hier.",
            "narrateur|Le poulain vient tout près.",
            "narrateur|On entend son souffle.",
            "papa|Il est venu.",
            "enfant-f|Pour moi.",
            "maman|Pour regarder.",
            "maman|On est doux.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le poulain blanc boit la rosée.",
            "narrateur|Sa langue prend une goutte.",
            "enfant-f|Il boit.",
            "papa|Oui.",
            "papa|Comme nous, le matin.",
            "maman|Cheval, jument, poulain.",
            "enfant-f|Trois noms.",
            "narrateur|Mila chuchote encore.",
            "enfant-f|Poulain.",
            "narrateur|L'étoile au front brille un peu.",
            "narrateur|La brume s'en va.",
            "papa|On rentre ?",
            "enfant-f|Encore un peu.",
            "maman|Un peu, oui.",
            "narrateur|Ils restent contre le bois.",
            "narrateur|Le pré sent l'herbe coupée.",
            "narrateur|Le poulain secoue l'oreille.",
            "maman|Merci, Mila.",
            "maman|Tu as regardé sans bouger.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le blanc est venu.",
            "papa|Le poulain, oui.",
            "narrateur|Une goutte glisse sur la barrière.",
            "narrateur|Elle tombe dans l'herbe.",
            "narrateur|Le pré redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "poulain",
        "accepted_examples": "poulain | le poulain | petit | le petit",
        "retry_prompt": "Le petit du cheval et de la jument. Qui est-ce ?",
    },
)
relecture(
    "ATOM-VIV.ANI.002-09",
    "Le poulain blanc",
    "Pré brumeux, barrière froide, désir du poulain blanc. Ils restent. Le poulain vient.",
    "N1. Trois noms: cheval, jument, poulain. POS: pas dans le pré. Troupe Mila, papa, maman.",
)

# ---------------------------------------------------------------------------
# 003-01 N2 Sarah, papa — Minou, gamelle trop pleine
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-01",
    "Sarah veut que Minou boive. La gamelle est vide. Ils versent trop. L'eau déborde. Ils essuient. Minou lape.",
    "La gamelle trop pleine",
    "Sarah, papa",
    "cuisine au soleil, carrelage tiède",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le carrelage de la cuisine est tiède.",
            "narrateur|Un carré de soleil pose une nappe jaune.",
            "narrateur|Ça sent le pain d'hier, un peu.",
            "narrateur|Une miette brille près du buffet.",
            "papa|Tes pieds sont chauds, Sarah.",
            "enfant-f|Le sol est doux.",
            "narrateur|Un miaulement arrive du couloir.",
            "narrateur|Minou le chat vient.",
            "narrateur|Ses pattes tapent le bois.",
            "narrateur|Toc, toc, tout léger.",
            "narrateur|En ce moment, Sarah regarde la gamelle.",
            "narrateur|La gamelle de Minou est vide.",
            "narrateur|Le fond est sec, un peu blanc.",
            "enfant-f|Il a soif, papa.",
            "enfant-f|Je veux qu'il boive.",
            "papa|On le fait ensemble.",
            "papa|Avec un adulte.",
            "papa|On est doux.",
            "papa|Tu tiens le bol avec moi ?",
            "enfant-f|Oui.",
            "narrateur|Sarah pose les deux mains sur le bol.",
            "narrateur|Le bol est froid.",
            "narrateur|Papa ouvre le robinet.",
            "narrateur|L'eau chante, mince.",
            "enfant-f|Doucement.",
            "papa|Un peu seulement.",
            "narrateur|Sarah penche le bol trop vite.",
            "narrateur|L'eau monte, monte.",
            "narrateur|Elle déborde.",
            "narrateur|Une flaque glisse sur le carrelage.",
            "enfant-f|Oh.",
            "enfant-f|C'est trop.",
            "papa|On arrête.",
            "papa|On essuie.",
            "narrateur|Papa prend le linge de la chaise.",
            "narrateur|Le linge sent le savon.",
            "narrateur|Sarah appuie avec lui.",
            "narrateur|La flaque part, tout doux.",
            "papa|Le bol, on le vide un peu ?",
            "enfant-f|Un peu.",
            "narrateur|Ils versent l'eau en trop dans l'évier.",
            "narrateur|Ça fait ploc.",
            "narrateur|Il reste une lame d'eau, claire.",
            "papa|Maintenant, on pose.",
            "papa|Tout doux.",
            "narrateur|Sarah pose la gamelle.",
            "narrateur|Sa main va lentement.",
            "narrateur|Le bol touche le carrelage sans bruit.",
            "narrateur|Minou s'approche.",
            "narrateur|Ses moustaches tremblent.",
            "enfant-f|Il vient.",
            "papa|On recule un peu.",
            "papa|On reste près de moi.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Sarah donne l'eau au chat.",
            "narrateur|Comment fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Minou pose la langue.",
            "narrateur|Lape, lape, lape.",
            "narrateur|L'eau baisse, tout doux.",
            "enfant-f|Il boit.",
            "papa|Oui.",
            "papa|Tu as été douce.",
            "papa|Avec un adulte.",
            "papa|Merci, Sarah.",
            "narrateur|Sarah reste assise près de papa.",
            "narrateur|Elle ne prend pas Minou.",
            "narrateur|Ses mains sont sur ses genoux.",
            "enfant-f|La flaque est partie.",
            "papa|Oui.",
            "papa|On a essuyé ensemble.",
            "papa|Tu as vu le trop d'eau ?",
            "enfant-f|Ça déborde.",
            "papa|Alors on verse peu.",
            "narrateur|Minou lève la tête.",
            "narrateur|Une goutte brille sur sa moustache.",
            "narrateur|Il se lèche la patte.",
            "enfant-f|Il est content.",
            "papa|Il a bu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le carré de soleil a bougé.",
            "narrateur|Il touche maintenant la gamelle.",
            "narrateur|L'eau restante fait un petit miroir.",
            "enfant-f|Je vois Minou dedans.",
            "papa|Un Minou tout petit.",
            "narrateur|Minou s'allonge près du buffet.",
            "narrateur|Son ventre va, vient.",
            "narrateur|Un ronron commence, bas.",
            "papa|Tu entends ?",
            "enfant-f|Oui.",
            "narrateur|Sarah pose l'oreille vers le sol.",
            "narrateur|Le ronron est chaud.",
            "papa|On range le linge.",
            "narrateur|Sarah donne le linge à papa.",
            "narrateur|Le carrelage est sec.",
            "enfant-f|Il a bu, papa.",
            "papa|C'était ça, ton envie.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Minou a de l'eau.",
            "papa|Un peu, tout doux.",
            "narrateur|Une miette reste près du buffet.",
            "narrateur|Le soleil la laisse d'or.",
            "narrateur|La cuisine redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "douce",
        "accepted_examples": "douce | doux | avec papa | avec un adulte",
        "retry_prompt": "Elle est douce, avec papa. Comment fait Sarah ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-01",
    "La gamelle trop pleine",
    "Sarah veut que Minou boive. Trop d'eau, flaque, essuyage, peu d'eau, Minou lape.",
    "N2. Doux, avec un adulte. Pas de saisie du chat. Troupe Sarah, papa.",
)

# ---------------------------------------------------------------------------
# 003-02 N2 Nino, papa — poule, glace du matin
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-02",
    "Nino veut que la poule boive. Au matin, une fine glace ferme l'eau. Avec papa, ils la cassent tout doux. La poule boit.",
    "La fine glace de la poule",
    "Nino, papa",
    "jardin gelé, poulailler au petit jour",
    {
        "CHK_T0000_P0000": [
            "narrateur|Le givre dessine des plumes sur la vitre.",
            "narrateur|Chaque plume de glace brille un peu.",
            "narrateur|La cuisine sent le lait chaud.",
            "narrateur|Un nuage sort de la tasse de papa.",
            "papa|Dehors, c'est blanc, Nino.",
            "enfant-m|Comme du sucre.",
            "papa|On va voir la poule ?",
            "enfant-m|Elle a soif.",
            "enfant-m|Je veux qu'elle boive.",
            "papa|On met les bottes.",
            "narrateur|Les bottes sont froides, un peu raides.",
            "narrateur|Nino enfile la gauche.",
            "narrateur|Papa aide pour la droite.",
            "narrateur|La porte s'ouvre.",
            "narrateur|L'air pique le nez.",
            "narrateur|En ce moment, Nino marche vers le grillage.",
            "narrateur|L'herbe craque sous les bottes.",
            "narrateur|Cric, cric.",
            "narrateur|Une poule rousse attend près du bois.",
            "narrateur|Elle rentre le cou.",
            "enfant-m|Elle a froid, papa.",
            "papa|On reste près de moi.",
            "papa|On est doux.",
            "papa|Avec un adulte.",
            "narrateur|L'abreuvoir est bas.",
            "narrateur|Une peau de glace le ferme.",
            "narrateur|La glace est fine, toute claire.",
            "enfant-m|L'eau est dure.",
            "papa|Une fine glace.",
            "papa|On la casse tout doux ?",
            "enfant-m|Oui.",
            "narrateur|Papa pose un doigt sur la glace.",
            "narrateur|Nino pose le sien avec lui.",
            "narrateur|Ça pique.",
            "narrateur|Ils appuient, tout lentement.",
            "narrateur|La glace fend.",
            "narrateur|Clic.",
            "narrateur|Un peu d'eau apparaît, noire et claire.",
            "enfant-m|Elle peut boire.",
            "papa|On verse encore un peu ?",
            "enfant-m|Un peu.",
            "narrateur|Nino tient le petit seau avec papa.",
            "narrateur|Le seau est lourd, un peu.",
            "narrateur|Ils versent un filet.",
            "narrateur|Pas trop.",
            "narrateur|L'eau fume un tout petit nuage.",
            "papa|On pose, tout doux.",
            "narrateur|Nino pose l'abreuvoir.",
            "narrateur|Sa main va lentement.",
            "narrateur|La poule avance d'un pas.",
            "papa|On recule.",
            "papa|On la laisse.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nino donne l'eau à la poule.",
            "narrateur|Comment fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|La poule penche le bec.",
            "narrateur|Elle boit, un coup, puis un autre.",
            "narrateur|Sa gorge va, vient.",
            "enfant-m|Elle boit, papa.",
            "papa|Oui.",
            "papa|Tu as été doux.",
            "papa|Avec un adulte.",
            "papa|Merci, Nino.",
            "narrateur|Nino essuie ses doigts au manteau.",
            "narrateur|Ils sont mouillés, un peu rouges.",
            "enfant-m|La glace est partie.",
            "papa|Une fine glace, seulement.",
            "papa|On a appuyé ensemble.",
            "papa|Tu as vu le clic ?",
            "enfant-m|Oui.",
            "narrateur|La poule secoue une goutte.",
            "narrateur|La goutte tombe sur le givre.",
            "narrateur|Elle fait un petit trou noir.",
            "enfant-m|Un trou.",
            "papa|L'eau a travaillé.",
            "narrateur|Nino reste près de papa.",
            "narrateur|Il ne prend pas la poule.",
            "narrateur|Ses mains sont dans ses poches.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le soleil perce le givre de la vitre, là-bas.",
            "narrateur|Un carré d'or tombe sur le grillage.",
            "narrateur|La poule picore près de l'eau.",
            "enfant-m|Elle n'a plus soif.",
            "papa|Elle a bu.",
            "papa|C'était ça, ton envie.",
            "narrateur|Le seau repose près des bottes.",
            "narrateur|Une dentelle de glace reste au bord.",
            "papa|On rentre se réchauffer ?",
            "enfant-m|Les mains, oui.",
            "narrateur|Ils marchent vers la maison.",
            "narrateur|L'herbe craque encore.",
            "narrateur|Derrière, la poule boit une dernière fois.",
            "papa|Tu as tenu le seau.",
            "enfant-m|Avec toi.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|La poule a de l'eau.",
            "papa|Tout doux, avec un adulte.",
            "narrateur|Le givre fond sur la vitre.",
            "narrateur|Une plume de glace devient une goutte.",
            "narrateur|Le jardin sent le bois mouillé.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "avec papa",
        "accepted_examples": "avec papa | doux | avec un adulte | tout doux",
        "retry_prompt": "Papa est avec lui. Nino verse. Comment ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-02",
    "La fine glace de la poule",
    "Nino veut que la poule boive. Fine glace sur l'eau, clic doux, la poule boit.",
    "N2. Doux, avec un adulte. Pas de saisie. Troupe Nino, papa.",
)

# ---------------------------------------------------------------------------
# 003-03 N3 Amir, papa — chat puis poules
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-03",
    "Amir veut soigner deux soifs: Minou d'abord, puis les poules. Avec papa, doux, deux fois.",
    "Deux soifs, deux soins",
    "Amir, papa",
    "cuisine puis jardin, matin de cacao",
    {
        "CHK_T0000_P0000": [
            "narrateur|La vapeur du cacao sent le matin.",
            "narrateur|Elle monte en petit nuage au-dessus de la tasse.",
            "narrateur|Le bois de la table est encore froid.",
            "papa|Bois un peu, Amir.",
            "enfant-m|C'est chaud.",
            "narrateur|Un miaulement arrive du radiateur.",
            "narrateur|Minou le chat s'étire.",
            "narrateur|Sa gamelle, près du buffet, est sèche.",
            "enfant-m|Il a soif, papa.",
            "enfant-m|Je veux qu'il boive.",
            "papa|On le fait ensemble.",
            "papa|Avec un adulte.",
            "papa|On est doux.",
            "narrateur|En ce moment, Amir tient le bol avec papa.",
            "narrateur|L'eau arrive, un filet, pas trop.",
            "narrateur|Le bol se pose sans bruit.",
            "narrateur|Minou lape, tout près.",
            "enfant-m|Il boit.",
            "papa|Premier soin.",
            "papa|On reste près de moi.",
            "narrateur|Plus tard, la porte du jardin s'ouvre.",
            "narrateur|L'air sent l'herbe et le grain.",
            "narrateur|Deux poules picorent près du grillage.",
            "narrateur|Leur abreuvoir est bas, presque vide.",
            "enfant-m|Elles aussi.",
            "enfant-m|Elles ont soif.",
            "papa|Même leçon.",
            "papa|Autre animal.",
            "papa|On verse avec un adulte ?",
            "enfant-m|Oui, papa.",
            "narrateur|Amir porte le seau avec papa.",
            "narrateur|Le seau tape sa jambe, tout léger.",
            "narrateur|Ils versent un peu d'eau.",
            "narrateur|Puis un peu de grain, tout doux.",
            "narrateur|Les poules viennent.",
            "papa|On recule.",
            "narrateur|Amir met les mains dans ses poches.",
            "narrateur|Il ne prend pas les poules.",
            "enfant-m|Deux soins.",
            "papa|Chat, puis poules.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Amir donne à boire ou à manger.",
            "narrateur|Comment ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Minou, à la maison, se lèche encore.",
            "narrateur|Au jardin, les poules boivent à tour de rôle.",
            "enfant-m|Les deux ont bu.",
            "papa|Oui.",
            "papa|Tu as été doux.",
            "papa|Avec un adulte.",
            "papa|Deux fois.",
            "papa|Merci, Amir.",
            "papa|Tu as vu la différence ?",
            "enfant-m|Le bol, et le seau.",
            "papa|Et le même geste.",
            "papa|Doux.",
            "narrateur|Une poule secoue le bec.",
            "narrateur|Une goutte tombe dans l'herbe.",
            "narrateur|L'herbe la garde.",
            "enfant-m|Comme Minou, tout à l'heure.",
            "papa|Même soif.",
            "papa|Même soin.",
            "narrateur|Amir reste près de papa.",
            "narrateur|Le seau vide est léger maintenant.",
            "narrateur|Il le porte jusqu'au perron.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Ils rentrent.",
            "narrateur|Le cacao a refroidi, un peu.",
            "narrateur|Amir reprend une gorgée.",
            "enfant-m|Nous aussi, on boit.",
            "papa|Oui.",
            "papa|Chacun sa tasse, chacun sa gamelle.",
            "narrateur|Minou s'est recouché au radiateur.",
            "narrateur|Son ronron revient, bas.",
            "narrateur|Dehors, une poule chante un petit coucou.",
            "papa|Tu as soigné deux soifs.",
            "enfant-m|Avec toi.",
            "papa|Avec un adulte.",
            "narrateur|La vapeur n'est plus là.",
            "narrateur|Il reste l'odeur du cacao, et du grain.",
            "papa|On range le seau près des bottes ?",
            "enfant-m|Oui.",
            "narrateur|Le seau trouve sa place.",
            "narrateur|Le bois du perron est sec.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Minou a bu.",
            "enfant-m|Les poules aussi.",
            "papa|Deux soins, tout doux.",
            "narrateur|Une plume reste collée au grillage.",
            "narrateur|Le matin sent encore le cacao.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "avec papa",
        "accepted_examples": "avec papa | avec un adulte | doux | tout doux | avec l'adulte",
        "retry_prompt": "Il le fait avec un adulte. Il est doux. Comment fait Amir ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-03",
    "Deux soifs, deux soins",
    "Amir soigne Minou puis les poules. Même leçon, deux animaux.",
    "N3 oral. Doux, avec un adulte. Pas de saisie. Troupe Amir, papa.",
)

# ---------------------------------------------------------------------------
# 003-04 N2 Nina, maman — lapin, bouteille coincée
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-04",
    "Nina veut que le lapin boive. La bouteille à l'envers est coincée. Maman aide. Le lapin boit.",
    "La bouteille coincée",
    "Nina, maman",
    "jardin, clapier à l'ombre du figuier",
    {
        "CHK_T0000_P0000": [
            "narrateur|Les fanes de carotte sentent la terre.",
            "narrateur|Elles sont encore un peu humides.",
            "narrateur|Sur la table du jardin, un couteau de bois attend.",
            "maman|On garde les fanes, Nina.",
            "maman|Pour le lapin.",
            "enfant-f|Il a faim ?",
            "enfant-f|Il a soif aussi.",
            "enfant-f|Je veux qu'il boive.",
            "maman|On y va ensemble.",
            "narrateur|Le figuier fait une ombre ronde.",
            "narrateur|Des feuilles tapent, tout doux.",
            "narrateur|En ce moment, Nina est devant le clapier.",
            "narrateur|Le lapin gris remue le nez.",
            "narrateur|Sa bouteille d'eau est à l'envers.",
            "narrateur|Le goulot devrait donner une goutte.",
            "narrateur|Rien ne tombe.",
            "enfant-f|Il n'a plus d'eau.",
            "maman|Regarde.",
            "maman|Elle est coincée.",
            "narrateur|La bouteille a tourné de travers.",
            "narrateur|Le fil de fer la pince trop fort.",
            "enfant-f|Je tire ?",
            "maman|On le fait avec un adulte.",
            "maman|On est doux.",
            "maman|Tu tiens le bol, moi le fil ?",
            "enfant-f|Oui, maman.",
            "narrateur|Nina tient le petit bol.",
            "narrateur|Maman desserre le fil, tout lentement.",
            "narrateur|La bouteille se redresse.",
            "narrateur|Une goutte apparaît.",
            "narrateur|Puis une autre.",
            "enfant-f|Ça marche.",
            "maman|On remplit aussi le bol ?",
            "enfant-f|Un peu.",
            "narrateur|Elles versent l'eau ensemble.",
            "narrateur|Le bol se pose près de la grille, tout doux.",
            "narrateur|Nina recule d'un pas.",
            "maman|On reste près de moi.",
            "narrateur|Le lapin s'approche.",
            "narrateur|Son nez touche la goutte de la bouteille.",
            "enfant-f|Il boit.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Nina donne l'eau au lapin.",
            "narrateur|Comment fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lapin lape le bol aussi.",
            "narrateur|Ses moustaches bougent, très vite.",
            "enfant-f|Il avait vraiment soif.",
            "maman|Oui.",
            "maman|Tu as été douce.",
            "maman|Avec un adulte.",
            "maman|Merci, Nina.",
            "maman|Tu as vu le fil ?",
            "enfant-f|Il pinçait.",
            "maman|On a desserré ensemble.",
            "narrateur|Nina pose une fane près de la grille.",
            "narrateur|Sa main va lentement.",
            "narrateur|Elle ne prend pas le lapin.",
            "narrateur|Le lapin croque, puis boit encore.",
            "enfant-f|Carotte, et eau.",
            "maman|Les deux.",
            "narrateur|Une goutte tombe du goulot.",
            "narrateur|Elle brille, puis elle part.",
            "enfant-f|Encore une.",
            "maman|La bouteille n'est plus coincée.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le figuier laisse passer un carré de soleil.",
            "narrateur|Il tombe sur le dos du lapin.",
            "narrateur|Le poil gris devient presque or.",
            "enfant-f|Il brille.",
            "maman|Il a bu.",
            "maman|C'était ça, ton envie.",
            "narrateur|Nina s'assoit sur le petit banc.",
            "narrateur|Maman s'assoit près d'elle.",
            "narrateur|Le clapier sent le foin propre.",
            "maman|On range les fanes ?",
            "enfant-f|Dans le saladier, oui.",
            "narrateur|Il en reste deux, pour plus tard.",
            "narrateur|Le lapin remue encore le nez.",
            "enfant-f|Merci, maman.",
            "maman|On l'a fait ensemble.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le lapin a de l'eau.",
            "maman|La bouteille donne encore des gouttes.",
            "narrateur|Une feuille de figuier tapote le bois.",
            "narrateur|Le jardin sent la terre et la carotte.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "douce",
        "accepted_examples": "douce | doux | avec maman | avec un adulte",
        "retry_prompt": "Elle est douce, avec maman. Comment fait Nina ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-04",
    "La bouteille coincée",
    "Nina veut que le lapin boive. Bouteille à l'envers coincée, maman desserre, le lapin boit.",
    "N2. Doux, avec un adulte. Pas de saisie. Troupe Nina, maman.",
)

# ---------------------------------------------------------------------------
# 003-05 N2 Raphaël, papa — lapin, foin qui cache le biberon
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-05",
    "Raphaël veut que le lapin boive. Le foin cache le biberon d'eau. Avec papa, ils écartent le foin. Le lapin boit.",
    "Le foin devant l'eau",
    "Raphaël, papa",
    "jardin, clapier, poussière de foin dans le soleil",
    {
        "CHK_T0000_P0000": [
            "narrateur|Un rayon coupe le foin en paillettes.",
            "narrateur|Les paillettes dansent, toutes d'or.",
            "narrateur|Ça sent le champ coupé, et le bois sec.",
            "papa|Le clapier a besoin d'air, Raphaël.",
            "enfant-m|Et d'eau.",
            "enfant-m|Je veux qu'il boive.",
            "papa|On y va ensemble.",
            "narrateur|Le chemin de dalles est chaud.",
            "narrateur|Une abeille passe, sans s'arrêter.",
            "narrateur|En ce moment, Raphaël est devant le clapier.",
            "narrateur|Le lapin gris frotte son nez.",
            "narrateur|Un tas de foin a glissé.",
            "narrateur|Il cache le biberon d'eau.",
            "enfant-m|Je ne vois plus l'eau.",
            "papa|Le foin est passé devant.",
            "papa|On écarte, tout doux.",
            "papa|Avec un adulte.",
            "papa|Tu prends le foin avec moi ?",
            "enfant-m|Oui, papa.",
            "narrateur|Raphaël pince une poignée.",
            "narrateur|Le foin pique un peu les doigts.",
            "narrateur|Papa pince l'autre côté.",
            "narrateur|Ils posent le foin plus loin, dans le râtelier.",
            "narrateur|Le biberon réapparaît.",
            "narrateur|Il est presque vide.",
            "enfant-m|Presque plus d'eau.",
            "papa|On remplit.",
            "papa|Tout doux.",
            "narrateur|Raphaël tient le biberon avec papa.",
            "narrateur|Le robinet du jardin chante.",
            "narrateur|L'eau monte, pas trop.",
            "papa|On referme.",
            "narrateur|Ils recrochent le biberon.",
            "narrateur|La main de Raphaël va lentement.",
            "narrateur|Une goutte apparaît au goulot.",
            "papa|On recule.",
            "papa|On reste près de moi.",
            "narrateur|Le lapin s'approche.",
            "narrateur|Il lape la goutte.",
            "enfant-m|Il boit.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Raphaël donne l'eau au lapin.",
            "narrateur|Comment fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lapin boit encore, tout calme.",
            "narrateur|Ses oreilles vont, viennent.",
            "enfant-m|Le foin cachait tout.",
            "papa|Oui.",
            "papa|Tu as été doux.",
            "papa|Avec un adulte.",
            "papa|Merci, Raphaël.",
            "papa|Tu as vu les paillettes ?",
            "enfant-m|Elles dansaient.",
            "papa|Le foin, maintenant, est à sa place.",
            "narrateur|Raphaël pose une poignée dans le râtelier.",
            "narrateur|Pas devant l'eau.",
            "narrateur|Il ne prend pas le lapin.",
            "narrateur|Ses mains sentent le champ.",
            "enfant-m|Ça pique encore.",
            "papa|On se rince au robinet ?",
            "enfant-m|Oui.",
            "narrateur|L'eau du jardin est fraîche.",
            "narrateur|Elle enlève les paillettes.",
            "enfant-m|Le lapin a de l'eau.",
            "papa|Et du foin, à côté.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le rayon a bougé.",
            "narrateur|Il touche maintenant le biberon.",
            "narrateur|L'eau dedans fait un petit or.",
            "enfant-m|Ça brille.",
            "papa|Il a bu.",
            "papa|C'était ça, ton envie.",
            "narrateur|Le lapin croque une tige.",
            "narrateur|Puis il revient à la goutte.",
            "papa|Foin, et eau.",
            "enfant-m|Les deux.",
            "narrateur|Raphaël s'assoit sur la dalle chaude.",
            "narrateur|Papa s'assoit près de lui.",
            "narrateur|Une paillette reste sur le genou.",
            "papa|On la souffle ?",
            "enfant-m|Oui.",
            "narrateur|La paillette s'en va, toute légère.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le biberon n'est plus caché.",
            "papa|Le lapin trouve l'eau.",
            "narrateur|Le foin sent encore le champ.",
            "narrateur|Le jardin redevient calme.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "doux",
        "accepted_examples": "doux | douce | avec papa | avec un adulte",
        "retry_prompt": "Il est doux, avec papa. Comment fait Raphaël ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-05",
    "Le foin devant l'eau",
    "Raphaël veut que le lapin boive. Foin devant le biberon, ils l'écartent, le lapin boit.",
    "N2. Doux, avec un adulte. Pas de saisie. Troupe Raphaël, papa.",
)

# ---------------------------------------------------------------------------
# 003-06 N1 Chouchou, maman — chat, eau tiède
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-06",
    "Chouchou veut que le chat boive. Elle pense au lait. Le lait est trop froid. Maman verse un peu d'eau tiède. Le chat lape.",
    "L'eau tiède du chat",
    "Chouchou, maman",
    "cuisine, bouilloire, fin d'après-midi",
    {
        "CHK_T0000_P0000": [
            "narrateur|La bouilloire fait tic, tic, tic.",
            "narrateur|Elle refroidit, tout doux.",
            "narrateur|La cuisine sent le pain grillé.",
            "narrateur|Une miette reste sur la planche.",
            "maman|Tu entends, Chouchou ?",
            "enfant-f|Tic, tic.",
            "narrateur|Le chat miaule près du buffet.",
            "narrateur|Sa gamelle est vide.",
            "enfant-f|Il a soif.",
            "enfant-f|Du lait ?",
            "maman|Le lait est trop froid.",
            "maman|Le chat boit de l'eau.",
            "maman|Un peu d'eau tiède.",
            "enfant-f|Je veux qu'il boive.",
            "maman|On le fait ensemble.",
            "maman|Avec un adulte.",
            "maman|On est doux.",
            "narrateur|En ce moment, Chouchou tient le bol.",
            "narrateur|Le bol est lisse, un peu froid.",
            "maman|Tu tiens avec moi ?",
            "enfant-f|Oui, maman.",
            "narrateur|Maman verse un peu d'eau.",
            "narrateur|L'eau est tiède.",
            "narrateur|Pas trop.",
            "narrateur|Ça fait un petit chh.",
            "enfant-f|C'est chaud ?",
            "maman|Tiède, seulement.",
            "maman|On pose, tout doux.",
            "narrateur|Chouchou pose la gamelle.",
            "narrateur|Sa main va lentement.",
            "narrateur|Le bol touche le carrelage.",
            "narrateur|Presque pas de bruit.",
            "narrateur|Le chat s'approche.",
            "narrateur|Ses pattes tapent le carrelage.",
            "narrateur|Toc, toc, tout léger.",
            "maman|On recule un peu.",
            "maman|On reste près de moi.",
            "enfant-f|Je reste.",
            "narrateur|Le chat pose la langue.",
            "narrateur|Lape, lape.",
            "enfant-f|Il boit.",
            "maman|Oui.",
            "narrateur|Une moustache tremble.",
            "narrateur|Une goutte brille.",
            "enfant-f|Pas de lait.",
            "maman|De l'eau.",
            "maman|Pour lui.",
            "narrateur|Le bol sent encore la vapeur.",
            "narrateur|Une petite vapeur, déjà partie.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Chouchou donne l'eau au chat.",
            "narrateur|Comment fait-elle ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le chat lape encore.",
            "narrateur|Le bol se vide, tout doux.",
            "enfant-f|Il avait soif.",
            "maman|Oui.",
            "maman|Tu as été douce.",
            "maman|Avec un adulte.",
            "maman|Merci, Chouchou.",
            "maman|Tu as vu l'eau tiède ?",
            "enfant-f|Pas froide.",
            "maman|Un peu tiède.",
            "narrateur|Chouchou a les mains sur ses genoux.",
            "narrateur|Elle ne prend pas le chat.",
            "narrateur|Le chat se lèche la patte.",
            "enfant-f|Il est content.",
            "maman|Il a bu.",
            "narrateur|La bouilloire a fini ses tics.",
            "narrateur|Elle est calme.",
            "enfant-f|Tic plus.",
            "maman|Elle s'est reposée.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le chat s'allonge près du buffet.",
            "narrateur|Son poil est chaud, un peu.",
            "narrateur|Un ronron commence.",
            "enfant-f|J'entends.",
            "maman|Moi aussi.",
            "narrateur|Chouchou s'assoit près de maman.",
            "narrateur|La planche sent encore le pain.",
            "maman|On range le bol demain.",
            "enfant-f|Il a de l'eau.",
            "maman|C'était ça, ton envie.",
            "narrateur|Une miette reste sur le bois.",
            "narrateur|Le chat ferme un œil.",
            "enfant-f|Dodo.",
            "maman|Un petit dodo, oui.",
            "narrateur|Le carrelage est tiède, comme l'eau.",
            "maman|Tu as tenu le bol.",
            "enfant-f|Avec toi.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-f|Le chat a bu.",
            "maman|De l'eau tiède, tout doux.",
            "narrateur|La bouilloire ne fait plus tic.",
            "narrateur|La cuisine sent le pain, encore.",
            "narrateur|Le ronron remplit la pièce.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "doux",
        "accepted_examples": "doux | douce | avec maman | avec un adulte | tout doux",
        "retry_prompt": "Elle est avec maman. Elle est douce. Comment fait-elle ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-06",
    "L'eau tiède du chat",
    "Chouchou veut que le chat boive. Pas le lait froid: un peu d'eau tiède. Le chat lape.",
    "N1. Doux, avec un adulte. Pas de saisie. Troupe Chouchou, maman.",
)

# ---------------------------------------------------------------------------
# 003-07 N2 Victorino, papa — lapin, oreille à la grille
# ---------------------------------------------------------------------------
write_story(
    "ATOM-VIV.ANI.003-07",
    "Victorino veut soigner le lapin qui a soif. Une oreille passe la grille. Ils restent, tout doux. Le lapin boit.",
    "L'oreille à la grille",
    "Victorino, papa",
    "jardin, clapier, fin de journée",
    {
        "CHK_T0000_P0000": [
            "narrateur|L'ombre du grillage barre le chemin.",
            "narrateur|Les barres sont longues, toutes bleues.",
            "narrateur|Ça sent le thym du bord, et le foin.",
            "papa|Le jour baisse, Victorino.",
            "enfant-m|Le lapin a soif.",
            "enfant-m|Je veux qu'il boive.",
            "papa|On y va ensemble.",
            "narrateur|Les cigales se taisent, une à une.",
            "narrateur|Une dalle est encore chaude sous le pied.",
            "narrateur|En ce moment, Victorino est devant le clapier.",
            "narrateur|Le lapin gris est tout près de la grille.",
            "narrateur|Une oreille passe entre les fils.",
            "narrateur|L'oreille est rose, un peu.",
            "enfant-m|Son oreille, papa.",
            "papa|On reste ici.",
            "papa|On ne tire pas.",
            "papa|On est doux.",
            "papa|Avec un adulte.",
            "papa|Tu vois la gamelle ?",
            "enfant-m|Elle est vide.",
            "papa|On remplit.",
            "papa|Toi le bol, moi l'eau.",
            "narrateur|Victorino tient le bol.",
            "narrateur|Papa verse un filet.",
            "narrateur|Pas trop.",
            "narrateur|L'eau cliquette.",
            "enfant-m|Tout doux.",
            "papa|On pose près de la grille.",
            "narrateur|Victorino pose le bol.",
            "narrateur|Sa main va lentement.",
            "narrateur|Il ne touche pas l'oreille.",
            "narrateur|Le bol se pose sans bruit.",
            "papa|On recule.",
            "papa|On reste près de moi.",
            "narrateur|Le lapin rentre l'oreille.",
            "narrateur|Elle glisse, toute seule.",
            "narrateur|Puis il s'approche de l'eau.",
            "enfant-m|Il boit.",
            "papa|Oui.",
            "narrateur|Les moustaches bougent.",
            "narrateur|L'eau baisse.",
        ],
        "CHK_T0000_P0000_Q0001": [
            "narrateur|Victorino donne de l'eau au lapin.",
            "narrateur|Comment fait-il ?",
        ],
        "CHK_T0000_P0000_C0001": [
            "narrateur|Le lapin lape encore.",
            "narrateur|L'oreille est rentrée, bien à lui.",
            "enfant-m|Elle est rentrée.",
            "papa|Toute seule.",
            "papa|Tu as été doux.",
            "papa|Avec un adulte.",
            "papa|Merci, Victorino.",
            "papa|Tu as vu l'oreille ?",
            "enfant-m|Je n'ai pas tiré.",
            "papa|On a donné l'eau.",
            "narrateur|Victorino a les mains dans les poches.",
            "narrateur|Il ne prend pas le lapin.",
            "narrateur|Papa verse aussi un peu de foin.",
            "narrateur|Victorino pose le foin, tout doux.",
            "enfant-m|Pour après.",
            "papa|Pour croquer, oui.",
            "narrateur|Le lapin boit une dernière goutte.",
            "narrateur|Puis il croque.",
            "enfant-m|Il n'a plus soif.",
            "papa|Il a bu.",
        ],
        "CHK_T0000_P0000_END": [
            "narrateur|Le jour est presque parti.",
            "narrateur|L'ombre du grillage s'est allongée.",
            "narrateur|Elle touche maintenant les dalles.",
            "enfant-m|C'est plus bleu.",
            "papa|Le soir arrive.",
            "papa|C'était ça, ton envie.",
            "papa|Qu'il boive.",
            "narrateur|Victorino s'assoit sur la dalle tiède.",
            "narrateur|Papa s'assoit près de lui.",
            "narrateur|Le thym sent plus fort, le soir.",
            "papa|On rentre bientôt ?",
            "enfant-m|Encore un peu.",
            "narrateur|Le lapin se lèche la patte.",
            "narrateur|L'oreille rose est bien dedans.",
            "enfant-m|Bien rentrée.",
            "papa|Oui.",
        ],
        "CHK_T0000_P0000_END_F0001": [
            "enfant-m|Le lapin a de l'eau.",
            "papa|Tout doux, près de la grille.",
            "narrateur|Une cigale fait un dernier chant.",
            "narrateur|Le jardin sent le thym et le foin.",
        ],
    },
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    {
        "expected_answer": "avec papa",
        "accepted_examples": "avec papa | avec un adulte | doux | douce | doucement",
        "retry_prompt": "Papa est avec lui. Il est doux. Comment fait-il ?",
    },
)
relecture(
    "ATOM-VIV.ANI.003-07",
    "L'oreille à la grille",
    "Victorino veut que le lapin boive. Oreille à la grille, ils ne tirent pas, ils donnent l'eau.",
    "N2. Doux, avec un adulte. POS: pas tirer l'oreille. Troupe Victorino, papa.",
)
