#!/usr/bin/env python3
"""ATOM-SOC.MET.001-01..07 + SOC.PAY.001-01 — récit greffé, pas un quiz."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import LIMITS, relecture, words, write_story


def q_met(hint: str) -> dict:
    return {
        "expected_answer": "métier",
        "accepted_examples": "métier | un métier | son métier | le métier | c'est un métier",
        "retry_prompt": hint,
    }


Q_PAY = {
    "expected_answer": "mer",
    "accepted_examples": "mer | la mer | le mer | vagues | la mer de France | paysage",
    "retry_prompt": "Sur la carte, le bleu, c'est quoi ?",
}


def precheck(sid: str, age: str, scripts: dict) -> None:
    lim = LIMITS[age]
    for cid, lines in scripts.items():
        for ln in lines:
            role, phrase = ln.split("|", 1)
            n = words(phrase)
            if n > lim:
                raise SystemExit(f"PRE {sid} {cid} {n}>{lim}: {phrase}")


def go(sid, fil, title, chars, setting, scripts, sons, q, vecu, notes, age):
    precheck(sid, age, scripts)
    write_story(sid, fil, title, chars, setting, scripts, sons, q)
    relecture(sid, title, vecu, notes)


# ---------------------------------------------------------------------------
# 01 N1 Amir, maman — boulanger, volet fermé un instant
# ---------------------------------------------------------------------------
S01 = {
    "CHK_T0000_P0000": [
        "narrateur|Le volet de bois claque tout doux.",
        "narrateur|Un chat gris dort sur le rebord.",
        "narrateur|La rue du village sent la croûte.",
        "narrateur|Le soleil tape les pavés clairs.",
        "narrateur|Amir vit ici, avec maman.",
        "narrateur|Le panier d'osier attend près de la porte.",
        "narrateur|Il est vide, un peu rêche.",
        "maman|Tu as faim, Amir ?",
        "enfant-m|Je veux du pain chaud.",
        "enfant-m|Pour la table.",
        "maman|On prend le panier.",
        "narrateur|En ce moment, Amir prend l'anse.",
        "narrateur|L'anse est lisse, un peu froide.",
        "narrateur|Ils marchent sur les pavés.",
        "narrateur|Un oiseau crie sur un toit.",
        "narrateur|Ça sent déjà le four.",
        "enfant-m|Maman, ça sent bon !",
        "maman|Oui.",
        "maman|C'est le boulanger.",
        "narrateur|La boutique est encore fermée.",
        "narrateur|Le volet reste baissé.",
        "enfant-m|C'est fermé.",
        "maman|Un instant, Amir.",
        "maman|On attend ici ?",
        "enfant-m|Oui, maman.",
        "narrateur|Ils s'assoient sur le banc.",
        "narrateur|Le banc est tiède sous les mains.",
        "narrateur|Derrière le bois, ça sent le blé.",
        "narrateur|Un bruit de farine tombe.",
        "narrateur|Toc, toc, dans le four.",
        "enfant-m|Il est là ?",
        "maman|Oui.",
        "maman|Il prépare le pain.",
        "maman|C'est son métier.",
        "enfant-m|Boulanger.",
        "maman|Oui, boulanger.",
        "narrateur|Une farine passe sous le volet.",
        "narrateur|Elle est blanche, comme de la neige.",
        "narrateur|Amir touche le bois chaud.",
        "maman|Tu entends le four ?",
        "enfant-m|Il fait toc toc.",
        "narrateur|Le chat se lève sur le rebord.",
        "narrateur|Il bâille, tout doux.",
        "maman|On reste encore un peu.",
        "narrateur|Le panier repose sur les genoux.",
        "narrateur|L'osier pique un peu.",
        "enfant-m|J'ai faim, maman.",
        "maman|Bientôt.",
        "maman|Le pain va sortir.",
        "narrateur|Une mouche tourne près du volet.",
        "narrateur|Le soleil avance sur le banc.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Le boulanger fait du pain.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le volet monte, tout d'un coup.",
        "narrateur|La boutique s'ouvre.",
        "narrateur|Le boulanger a de la farine aux mains.",
        "narrateur|Ses mains sont blanches.",
        "narrateur|Ça sent le pain tout chaud.",
        "enfant-m|Tes mains sont blanches !",
        "maman|Il a pétri le pain.",
        "maman|C'est son métier.",
        "enfant-m|Boulanger.",
        "maman|Bravo, Amir.",
        "maman|Tu as trouvé le boulanger.",
        "narrateur|Amir tend le panier.",
        "narrateur|Le pain est doré, encore tiède.",
        "narrateur|Il glisse dans l'osier.",
        "maman|Merci.",
        "enfant-m|Merci.",
        "narrateur|La croûte craque un tout petit peu.",
        "maman|Tu le tiens bien ?",
        "enfant-m|Oui, maman.",
        "narrateur|Le chat regarde le panier.",
        "maman|On rentre, Amir.",
        "narrateur|Amir serre l'anse contre lui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Ils marchent vers la maison.",
        "narrateur|Le panier chauffe contre le bras.",
        "narrateur|L'odeur suit toute la rue.",
        "narrateur|Un pavé brille encore.",
        "enfant-m|Il est chaud, maman.",
        "maman|Oui.",
        "maman|Le boulanger l'a préparé.",
        "maman|Pour nous.",
        "narrateur|La porte de la maison claque doux.",
        "narrateur|La table est prête.",
        "narrateur|Une nappe à carreaux attend.",
        "narrateur|Amir pose le pain.",
        "narrateur|Un peu de vapeur monte.",
        "maman|Tu veux un bout ?",
        "enfant-m|Oui.",
        "maman|Tu as bien attendu.",
        "maman|Merci d'avoir tenu le panier.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Le bout de pain est tiède.",
        "narrateur|La croûte craque sous les dents.",
        "enfant-m|C'est bon.",
        "maman|Oui.",
        "maman|Le boulanger a bien travaillé.",
        "narrateur|Le chat revient sur le rebord.",
        "narrateur|Le soleil reste sur la nappe.",
        "narrateur|Le panier d'osier se repose, vide et tiède.",
    ],
}

go(
    "ATOM-SOC.MET.001-01",
    "Amir veut du pain chaud pour la table. Le volet est baissé un instant. Ils attendent. Le boulanger ouvre, farine aux mains. Le pain glisse dans l'osier.",
    "Le volet du boulanger",
    "Amir, maman",
    "village, rue pavée, boutique du boulanger, fin de matinée",
    S01,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Il prépare le pain. C'est quoi ?"),
    "Amir et maman vont chercher le pain. Boutique fermée un instant, banc tiède, four qui tape. Le boulanger ouvre, mains blanches. Pain dans le panier, croûte à la table.",
    "Leçon greffée : boulanger, métier, pain. Pas de liste médecin/maîtresse. Ouverture volet. Imprévu volet baissé. Fin nappe et panier vide.",
    "N1",
)


# ---------------------------------------------------------------------------
# 02 N2 Sarah, papa — médecin du village, poupée
# ---------------------------------------------------------------------------
S02 = {
    "CHK_T0000_P0000": [
        "narrateur|La poupée penche sur la chaise de bois.",
        "narrateur|Un petit pansement se décolle au genou.",
        "narrateur|Le tissu est froissé, un peu gris.",
        "narrateur|La chambre sent encore le linge propre.",
        "narrateur|Un rayon passe sur le parquet.",
        "narrateur|Sarah vit ici, avec papa.",
        "enfant-f|Elle a un bob, papa.",
        "papa|Au genou de la poupée ?",
        "enfant-f|Oui.",
        "enfant-f|Je veux la consoler.",
        "narrateur|Sarah pose sa main sur le genou de tissu.",
        "narrateur|Le tissu est rêche, un peu froid.",
        "papa|Le pansement ne tient plus.",
        "papa|On va chez le médecin du village ?",
        "enfant-f|Pour la poupée ?",
        "papa|Pour la poupée.",
        "papa|Et pour toi, si ça pique.",
        "narrateur|En ce moment, Sarah serre la poupée.",
        "narrateur|Le bras de chiffon pend un peu.",
        "narrateur|Ils descendent l'escalier de pierre.",
        "narrateur|Dehors, le tilleul sent le miel.",
        "narrateur|Un oiseau saute dans l'herbe.",
        "enfant-f|Elle a mal, je crois.",
        "papa|On marche doucement.",
        "papa|Tu la tiens bien ?",
        "enfant-f|Oui, papa.",
        "narrateur|La plaque du médecin brille au soleil.",
        "narrateur|Elle est ronde, un peu chaude.",
        "narrateur|La porte sent le savon clair.",
        "papa|On frappe, tout doux.",
        "narrateur|Toc, toc.",
        "narrateur|Le médecin ouvre.",
        "narrateur|Sa blouse est blanche, un peu froissée.",
        "enfant-f|Ma poupée a un bob.",
        "papa|Sarah veut la consoler.",
        "papa|C'est le médecin.",
        "papa|C'est son métier.",
        "enfant-f|Médecin.",
        "narrateur|Sarah montre le genou de tissu.",
        "narrateur|Le vieux pansement pend.",
        "narrateur|Le médecin parle tout bas.",
        "papa|Il soigne, Sarah.",
        "papa|Tu restes près de moi ?",
        "enfant-f|Oui.",
        "narrateur|Sarah a aussi un petit bob au genou.",
        "narrateur|Ça pique, tout doux, rien de grave.",
        "enfant-f|Moi aussi, un peu.",
        "papa|On montre, sans courir.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Le médecin soigne le genou.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le médecin pose un pansement neuf.",
        "narrateur|D'abord sur le genou de Sarah.",
        "narrateur|Le tissu est doux, un peu frais.",
        "enfant-f|Il est froid.",
        "papa|Oui.",
        "papa|Il tient bien.",
        "narrateur|Ensuite, un tout petit pansement.",
        "narrateur|Pour le genou de la poupée.",
        "narrateur|Sarah appuie le bord, tout doux.",
        "enfant-f|Voilà.",
        "papa|Bravo, Sarah.",
        "papa|Tu as consolé la poupée.",
        "papa|Le médecin t'a aidée.",
        "enfant-f|Merci.",
        "papa|Merci.",
        "papa|C'est son métier.",
        "enfant-f|Il soigne.",
        "narrateur|La poupée tient droite, contre l'épaule.",
        "narrateur|Le rayon revient sur la blouse.",
        "papa|On rentre, les deux genoux au chaud ?",
        "enfant-f|Oui, papa.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Ils reprennent le chemin du tilleul.",
        "narrateur|Les feuilles bougent, tout léger.",
        "narrateur|Sarah marche sans se presser.",
        "narrateur|La poupée regarde le ciel, un peu de travers.",
        "enfant-f|Elle n'a plus mal.",
        "papa|Toi non plus ?",
        "enfant-f|Ça pique moins.",
        "papa|Bien.",
        "narrateur|La chaise de bois attend dans la chambre.",
        "narrateur|Sarah assied la poupée.",
        "narrateur|Le pansement tient, tout droit.",
        "papa|Tu lui parles ?",
        "enfant-f|Tu es brave, poupée.",
        "papa|Et toi aussi.",
        "narrateur|Sarah pose sa main sur les deux genoux.",
        "narrateur|Le sien, et celui de chiffon.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Le rayon revient sur le parquet.",
        "narrateur|Le linge sent encore le propre.",
        "enfant-f|Elle est consolée.",
        "papa|Oui.",
        "papa|Le médecin a bien travaillé.",
        "narrateur|La poupée penche moins, sur la chaise.",
        "narrateur|Le petit pansement reste collé, tout calme.",
    ],
}

go(
    "ATOM-SOC.MET.001-02",
    "Sarah veut consoler sa poupée, pansement décollé au genou. Chez le médecin du village, un pansement neuf pour Sarah, un tout petit pour la poupée. Pas de sang.",
    "Le bob de la poupée",
    "Sarah, papa",
    "chambre, chemin du tilleul, cabinet du médecin du village",
    S02,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Il soigne. C'est quoi ?"),
    "Sarah console la poupée. Pansement qui se décolle. Médecin du village, blouse froissée. Pansement frais pour Sarah, tout petit pour la poupée. Retour chaise de bois.",
    "Leçon greffée : médecin, métier, soigner. POS-001 : bob léger, pas de sang. Désir : consoler, pas nommer une liste de métiers.",
    "N2",
)


# ---------------------------------------------------------------------------
# 03 N3 Nino, papa — facteur puis boulanger
# ---------------------------------------------------------------------------
S03 = {
    "CHK_T0000_P0000": [
        "narrateur|La boîte aux lettres brille au soleil.",
        "narrateur|Le métal est chaud, un peu piqué de poussière.",
        "narrateur|Un oiseau a laissé une plume grise sur le couvercle.",
        "narrateur|Nino vit ici, avec papa.",
        "narrateur|La rue sent le jasmin, tout bas.",
        "enfant-m|Je veux voir le courrier, papa.",
        "papa|Dans la boîte ?",
        "enfant-m|Oui.",
        "enfant-m|J'ai mis un dessin, hier.",
        "papa|Alors on attend le facteur.",
        "narrateur|En ce moment, Nino s'accroupit près du pied de la boîte.",
        "narrateur|L'herbe chatouille ses chevilles.",
        "narrateur|La fente est étroite, sombre, un peu froide.",
        "enfant-m|Elle est vide.",
        "papa|Pas encore.",
        "papa|On reste ici un moment ?",
        "enfant-m|Oui.",
        "narrateur|Un vélo grince au bout de la rue.",
        "narrateur|Une sacoche tape contre une jambe.",
        "narrateur|Le facteur s'arrête, casquette un peu de travers.",
        "enfant-m|Le voilà !",
        "papa|Oui.",
        "papa|C'est le facteur.",
        "papa|C'est son métier.",
        "enfant-m|Il porte les lettres.",
        "narrateur|Le facteur glisse une enveloppe dans la fente.",
        "narrateur|Ça fait un petit clap, tout sec.",
        "narrateur|Puis une carte, bleue, un peu pliée.",
        "enfant-m|Mon dessin ?",
        "papa|Peut-être une réponse.",
        "papa|Tu ouvres, tout doux ?",
        "narrateur|Nino tourne la clé.",
        "narrateur|La boîte sent le papier chaud.",
        "narrateur|La carte est là, avec le dessin revenu, un mot au dos.",
        "enfant-m|Il a mis le courrier !",
        "papa|Bravo, Nino.",
        "papa|Tu as attendu le facteur.",
        "narrateur|Nino serre la carte contre sa chemise.",
        "papa|On a encore faim ?",
        "enfant-m|Je veux du pain.",
        "papa|Chez le boulanger, alors.",
        "narrateur|Ils marchent, la carte au chaud.",
        "narrateur|Le jasmin suit un peu.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Le facteur glisse le courrier.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|La boutique du pain est ouverte, cette fois.",
        "narrateur|Ça sent la croûte et le beurre.",
        "narrateur|Le boulanger tape la planche, toc toc.",
        "enfant-m|Et lui ?",
        "papa|C'est le boulanger.",
        "papa|C'est son métier, lui aussi.",
        "enfant-m|Il fait le pain.",
        "papa|Oui.",
        "narrateur|Nino pose la carte sur le comptoir, une seconde.",
        "narrateur|Puis il la reprend, vite.",
        "papa|Tu la gardes.",
        "papa|Le pain va dans le sac.",
        "narrateur|Une baguette encore souple glisse dans le drap.",
        "narrateur|Un peu de farine vole.",
        "papa|Merci.",
        "enfant-m|Merci.",
        "papa|Deux métiers, ce matin.",
        "papa|Le facteur, puis le boulanger.",
        "enfant-m|Tous les deux utiles.",
        "papa|Oui.",
        "papa|Tu veux porter le sac ?",
        "enfant-m|Et la carte.",
        "narrateur|Nino a les deux, sac et papier.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Ils reprennent la rue du jasmin.",
        "narrateur|La boîte aux lettres est déjà derrière.",
        "narrateur|Le métal ne brille plus autant.",
        "enfant-m|Le facteur reviendra demain ?",
        "papa|Oui.",
        "papa|C'est son métier, chaque jour.",
        "narrateur|À la maison, Nino pose la carte près de la fenêtre.",
        "narrateur|Le dessin regarde le jardin.",
        "narrateur|Papa casse le pain, tout tiède.",
        "papa|Un bout pour toi ?",
        "enfant-m|Oui.",
        "narrateur|La croûte tombe en miettes blondes.",
        "enfant-m|Le facteur a bien travaillé.",
        "papa|Et le boulanger aussi.",
        "papa|Merci d'avoir attendu près de la boîte.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|La carte bleue reste au soleil.",
        "narrateur|Le pain sent encore le four.",
        "enfant-m|Le courrier est rentré.",
        "papa|Oui.",
        "narrateur|Nino souffle sur une miette.",
        "narrateur|Elle part vers le dessin, tout léger.",
        "narrateur|La plume grise dort encore sur le couvercle, dehors.",
    ],
}

go(
    "ATOM-SOC.MET.001-03",
    "Nino veut voir le courrier dans la boîte. Le facteur glisse une carte. Puis ils vont chez le boulanger. Deux moments, deux métiers, pain et papier.",
    "La lettre dans la boîte",
    "Nino, papa",
    "rue du village, boîte aux lettres, puis boutique du pain",
    S03,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Il porte les lettres. C'est quoi ?"),
    "Nino attend près de la boîte. Vélo, sacoche, clap dans la fente. Carte bleue. Puis pain. Facteur et boulanger, pas une liste récité.",
    "Deux moments demandés : facteur puis boulanger. Courrier dans la boîte. Ouverture métal au soleil.",
    "N3",
)


# ---------------------------------------------------------------------------
# 04 N3 Mila, papa — horticultrice du square + boulanger
# ---------------------------------------------------------------------------
S04 = {
    "CHK_T0000_P0000": [
        "narrateur|Un arrosoir laisse une goutte sur la pierre.",
        "narrateur|La goutte brille, puis elle file dans une fissure.",
        "narrateur|Le square sent la terre mouillée et la menthe.",
        "narrateur|Mila vit ici, tout près, avec papa.",
        "narrateur|Un banc de bois encore froid attend sous le tilleul.",
        "enfant-f|Je veux une petite plante, papa.",
        "enfant-f|Pour la fenêtre.",
        "papa|On demande à l'horticultrice ?",
        "enfant-f|Celle du square.",
        "papa|Oui.",
        "narrateur|En ce moment, Mila suit la trace d'eau sur les dalles.",
        "narrateur|Les dalles sont rudes, un peu vertes.",
        "narrateur|L'horticultrice est accroupie près des géraniums.",
        "narrateur|Ses gants sont bruns, collés de terre.",
        "enfant-f|Elle arrose.",
        "papa|C'est l'horticultrice.",
        "papa|C'est son métier.",
        "enfant-f|Elle soigne les plantes.",
        "papa|Oui.",
        "narrateur|Mila s'arrête trop près de l'arrosoir.",
        "narrateur|L'arrosoir penche.",
        "narrateur|Un filet d'eau part vers la chaussure de papa.",
        "papa|Oh.",
        "papa|On recule un peu.",
        "enfant-f|Pardon.",
        "papa|On reste sur la dalle sèche ?",
        "enfant-f|Oui.",
        "narrateur|L'horticultrice redresse l'arrosoir.",
        "narrateur|Elle tend un petit pot, terre encore sombre.",
        "narrateur|Une feuille ronde, toute neuve, au milieu.",
        "enfant-f|Pour la fenêtre ?",
        "papa|Si tu la portes sans la serrer.",
        "narrateur|Mila prend le pot à deux mains.",
        "narrateur|La terre sent le jardin, tout fort.",
        "papa|Merci.",
        "enfant-f|Merci.",
        "papa|Bravo, Mila.",
        "papa|Tu as trouvé l'horticultrice.",
        "enfant-f|J'ai faim, maintenant.",
        "papa|Le boulanger est juste après le square.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|L'horticultrice arrose les plantes.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Ils longent la grille, le pot bien droit.",
        "narrateur|Une feuille tape le menton de Mila.",
        "narrateur|La boutique du pain ouvre ses deux battants.",
        "narrateur|Ça sent le sésame et la croûte.",
        "enfant-f|Le boulanger !",
        "papa|Oui.",
        "papa|Lui aussi a un métier.",
        "enfant-f|Le pain.",
        "papa|Il prépare le pain.",
        "narrateur|Mila pose le pot sur le bord du comptoir.",
        "narrateur|Le boulanger farine ses mains, encore.",
        "narrateur|Un pain rond, un peu doré, part dans le sac.",
        "papa|Merci.",
        "enfant-f|Le pot, je le reprends.",
        "papa|Les deux, plante et pain.",
        "narrateur|Le sac tape la hanche, tout léger.",
        "narrateur|La feuille ronde tremble à chaque pas.",
        "papa|Tu tiens bien ?",
        "enfant-f|Oui, papa.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La fenêtre de la cuisine est déjà ouverte.",
        "narrateur|Un peu de vent entre, avec la menthe du square.",
        "narrateur|Mila pose le pot sur le rebord.",
        "narrateur|La terre reste sombre, bien tenue.",
        "enfant-f|Elle voit le square, d'ici.",
        "papa|Oui.",
        "papa|L'horticultrice l'a choisie pour toi.",
        "narrateur|Papa coupe le pain rond.",
        "narrateur|La mie est blanche, encore tiède.",
        "papa|Un morceau près du pot ?",
        "enfant-f|Pour moi.",
        "papa|Pour toi.",
        "papa|La plante boit l'eau, pas le pain.",
        "enfant-f|Je le savais.",
        "papa|Merci d'avoir porté le pot sans le serrer.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|La feuille ronde tourne vers le jour.",
        "narrateur|Une goutte reste encore sur la terre.",
        "enfant-f|Elle est bien, là.",
        "papa|Oui.",
        "narrateur|Le square continue, tout près, avec son arrosoir.",
        "narrateur|Le pain tiède sent le sésame, sur la table.",
        "narrateur|La fenêtre garde la petite plante, et le vent.",
    ],
}

go(
    "ATOM-SOC.MET.001-04",
    "Mila veut une petite plante pour la fenêtre. L'arrosoir penche. L'horticultrice du square tend un pot. Puis le boulanger glisse un pain rond dans le sac.",
    "L'arrosoir du square",
    "Mila, papa",
    "square du village, terre mouillée, puis boutique du pain, fenêtre de la cuisine",
    S04,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Elle soigne les plantes. C'est quoi ?"),
    "Square, goutte, horticultrice, gants de terre. Arrosoir qui penche. Pot à deux mains. Boulanger après la grille. Plante au rebord, pain rond.",
    "Deux métiers vécus : horticultrice puis boulanger. Pas de quiz médecin/maîtresse. Imprévu filet d'eau.",
    "N3",
)


# ---------------------------------------------------------------------------
# 05 N1 Nina, papa, maman — pompier vu de loin
# ---------------------------------------------------------------------------
S05 = {
    "CHK_T0000_P0000": [
        "narrateur|Au loin, une sirène chante très bas.",
        "narrateur|Le son arrive au-dessus des toits.",
        "narrateur|La rue du village est calme, encore.",
        "narrateur|Nina vit ici, avec papa et maman.",
        "narrateur|Le trottoir est chaud sous les sandales.",
        "enfant-f|J'entends le camion !",
        "papa|Oui, Nina.",
        "maman|On reste ici.",
        "maman|Sur le trottoir.",
        "enfant-f|Je veux voir le rouge.",
        "papa|On regarde de loin.",
        "narrateur|En ce moment, Nina prend deux mains.",
        "narrateur|La main de papa, la main de maman.",
        "narrateur|Un oiseau part d'un toit.",
        "narrateur|La sirène reste loin, tout bas.",
        "enfant-f|Il est où ?",
        "maman|Là-bas.",
        "maman|Près de la caserne.",
        "narrateur|Un point rouge avance, tout petit.",
        "narrateur|Il brille entre deux maisons.",
        "enfant-f|Le camion !",
        "papa|Oui.",
        "papa|C'est le pompier.",
        "papa|C'est son métier.",
        "enfant-f|Pompier.",
        "maman|Il aide.",
        "maman|On le regarde d'ici.",
        "narrateur|Nina se penche un peu.",
        "narrateur|Ses sandales restent sur le trottoir.",
        "papa|On reste ici, Nina.",
        "papa|Pieds sur le trottoir.",
        "maman|On tient les mains.",
        "enfant-f|Je tiens.",
        "narrateur|La sirène descend, encore plus loin.",
        "narrateur|Le point rouge passe, tout petit.",
        "enfant-f|Il va vite.",
        "maman|Oui.",
        "maman|Nous, on reste.",
        "papa|Tu vois le camion ?",
        "enfant-f|Oui, papa.",
        "narrateur|Un chien aboie derrière une porte.",
        "narrateur|Puis il se tait.",
        "narrateur|L'air sent la poussière chaude.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Le pompier a un camion.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le point rouge devient tout petit.",
        "narrateur|La sirène n'est plus qu'un fil.",
        "enfant-f|Il est parti.",
        "papa|Oui.",
        "papa|Le pompier fait son métier.",
        "maman|Et nous, on est restés ici.",
        "maman|Sur le trottoir.",
        "enfant-f|J'ai vu le rouge.",
        "papa|Bravo, Nina.",
        "papa|Tu as regardé de loin.",
        "maman|Merci d'avoir tenu les mains.",
        "narrateur|Nina serre encore les deux mains.",
        "narrateur|Les sandales sont un peu poussiéreuses.",
        "maman|On rentre ?",
        "enfant-f|Oui.",
        "papa|On marche sur le trottoir.",
        "narrateur|Un toit cache déjà la caserne.",
        "narrateur|Il ne reste qu'un peu de silence.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|La maison sent le linge au soleil.",
        "narrateur|Nina s'assoit sur le pas de la porte.",
        "narrateur|Ses sandales tapent la pierre, tout doux.",
        "enfant-f|Le camion était rouge.",
        "maman|Oui.",
        "maman|Vu de loin.",
        "papa|Le pompier aide, là-bas.",
        "papa|Nous, on reste près de la maison.",
        "enfant-f|J'ai tenu les mains.",
        "maman|Oui.",
        "maman|Tu as bien fait.",
        "papa|Tu veux de l'eau ?",
        "enfant-f|Oui, papa.",
        "narrateur|L'eau est fraîche dans le verre.",
        "narrateur|Nina boit, un peu trop vite.",
        "maman|Doucement.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|La rue redevient calme.",
        "narrateur|Plus de sirène, plus de point rouge.",
        "enfant-f|Je l'ai vu.",
        "papa|Oui.",
        "maman|De loin, sur le trottoir.",
        "narrateur|Les sandales sèchent sur la pierre.",
        "narrateur|Le toit garde le village, tout tranquille.",
    ],
}

go(
    "ATOM-SOC.MET.001-05",
    "Nina veut voir le camion rouge. Sirène au loin. Papa et maman tiennent les mains, sur le trottoir. La caserne reste loin. Ils regardent, puis rentrent.",
    "Le camion rouge au loin",
    "Nina, papa, maman",
    "trottoir du village, caserne vue de loin, pas de la porte",
    S05,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Il aide avec le camion. C'est quoi ?"),
    "Sirène lointaine, point rouge entre les maisons. Nina penche, reste sur le trottoir, deux mains. POS-001 : dire de rester, pas décrire une course. Eau fraîche au pas de la porte.",
    "Un seul métier vécu : pompier. Pas de liste. Caserne vue de loin. Stay back.",
    "N1",
)


# ---------------------------------------------------------------------------
# 06 N3 Raphaël, papa, maman — marin au port + boulanger
# ---------------------------------------------------------------------------
S06 = {
    "CHK_T0000_P0000": [
        "narrateur|Les filets sentent le sel et l'eau.",
        "narrateur|Ils pendent le long du quai, encore goutte à goutte.",
        "narrateur|Une mouette crie au-dessus du mât.",
        "narrateur|Raphaël vit près d'ici, avec papa et maman.",
        "narrateur|Le bois du quai est gris, piqué de sel.",
        "enfant-m|Je veux voir les filets, papa.",
        "papa|On reste sur le quai.",
        "maman|Près de moi.",
        "narrateur|En ce moment, Raphaël pose les deux mains sur la rambarde.",
        "narrateur|Le métal est froid, un peu collant.",
        "narrateur|Un marin tire un filet, lentement.",
        "narrateur|L'eau tombe en perles, sur le bois.",
        "enfant-m|Il est fort.",
        "papa|C'est le marin.",
        "papa|C'est son métier.",
        "enfant-m|Il ramène les filets.",
        "maman|Oui.",
        "narrateur|Le filet glisse, trop vite, un instant.",
        "narrateur|Une gerbe d'eau saute vers les chaussures.",
        "maman|Oh.",
        "maman|On recule d'un pas.",
        "papa|On reste derrière la rambarde ?",
        "enfant-m|Oui.",
        "narrateur|Raphaël essuie une goutte sur sa manche.",
        "narrateur|Ça sent encore plus le sel.",
        "enfant-m|Mes mains sont mouillées.",
        "maman|Le marin travaille dans l'eau.",
        "papa|Toi, tu regardes.",
        "narrateur|Le marin range le filet en rond, tout serré.",
        "narrateur|Une écaille brille, puis elle disparaît.",
        "enfant-m|Merci, marin !",
        "papa|Merci.",
        "maman|Bravo, Raphaël.",
        "maman|Tu as regardé sans te pencher trop.",
        "enfant-m|J'ai faim, maintenant.",
        "papa|Le boulanger du port est ouvert.",
        "maman|Du pain, avec le sel encore dans l'air.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Le marin tire les filets.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Ils quittent le quai, pas à pas.",
        "narrateur|Le bois sonne sous les chaussures.",
        "narrateur|La boutique du pain est toute proche, peinte en bleu.",
        "narrateur|Ça sent le beurre, après le sel.",
        "enfant-m|Le boulanger !",
        "maman|Oui.",
        "maman|Lui aussi a un métier.",
        "papa|Il prépare le pain.",
        "enfant-m|Pour nous.",
        "narrateur|Raphaël a encore une goutte de sel au poignet.",
        "narrateur|Il la sent, puis il tend les mains au sac.",
        "narrateur|Un pain long, encore chaud, plie le papier.",
        "papa|Merci.",
        "maman|Tu le portes ?",
        "enfant-m|Oui.",
        "papa|Les filets, et le pain.",
        "enfant-m|Deux métiers.",
        "maman|Oui.",
        "narrateur|Une mouette les suit un instant, puis elle part.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Sur un banc face à l'eau, ils s'assoient.",
        "narrateur|Le pain craque, tout fort.",
        "narrateur|Des miettes tombent, trop petites pour les poissons.",
        "enfant-m|Ça sent le sel, et le four.",
        "papa|Oui.",
        "papa|Le marin, puis le boulanger.",
        "maman|Tu as vu les filets ?",
        "enfant-m|Oui.",
        "enfant-m|Ils gouttaient.",
        "maman|Et toi, tu es resté derrière la rambarde.",
        "papa|Merci d'avoir reculé, tout de suite.",
        "narrateur|L'eau clapote contre le bois, tout régulier.",
        "narrateur|Le sac de pain pèse encore un peu, sur les genoux.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Une dernière goutte tombe d'un filet, au loin.",
        "narrateur|Elle fait un rond, puis plus rien.",
        "enfant-m|Le pain est bon.",
        "maman|Oui.",
        "papa|Le port garde le sel.",
        "narrateur|Raphaël essuie sa manche, déjà sèche.",
        "narrateur|Le papier du pain claque un peu, dans le vent.",
    ],
}

go(
    "ATOM-SOC.MET.001-06",
    "Raphaël veut voir les filets au port. Une gerbe d'eau saute. Ils reculent derrière la rambarde. Puis le boulanger du port glisse un pain chaud dans le papier.",
    "Les filets du port",
    "Raphaël, papa, maman",
    "quai, filets, rambarde, boutique bleue du pain, banc face à l'eau",
    S06,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Il ramène les filets. C'est quoi ?"),
    "Sel, filets, mouette, rambarde froide. Gerbe d'eau, un pas en arrière. Marin puis boulanger du port. Pain sur le banc, clapotis.",
    "Deux moments : marin, boulanger. POS-001 : rester derrière la rambarde, reculer. Pas de quiz.",
    "N3",
)


# ---------------------------------------------------------------------------
# 07 N2 Victorina, maman, papa — libraire puis fleuriste
# ---------------------------------------------------------------------------
S07 = {
    "CHK_T0000_P0000": [
        "narrateur|La clochette de la librairie tinte deux fois.",
        "narrateur|Les pages sentent le papier neuf et la colle.",
        "narrateur|Un rayon penche, trop haut pour une main d'enfant.",
        "narrateur|Victorina vit dans ce quartier, avec maman et papa.",
        "narrateur|Dehors, un platane jette des ombres rondes.",
        "enfant-f|Je veux un livre, maman.",
        "enfant-f|Un livre avec des fleurs.",
        "maman|On demande à la libraire ?",
        "papa|Elle est derrière le comptoir.",
        "narrateur|En ce moment, Victorina suit le dos des livres.",
        "narrateur|Le dos est lisse, un peu froid.",
        "narrateur|Le livre aux fleurs est trop haut.",
        "enfant-f|Je ne l'ai pas.",
        "maman|On reste en bas.",
        "maman|On appelle.",
        "papa|La libraire peut le prendre.",
        "narrateur|La libraire avance, lunettes sur le nez.",
        "narrateur|Elle glisse le livre, tout doux, vers les mains de Victorina.",
        "enfant-f|Merci.",
        "maman|C'est la libraire.",
        "maman|C'est son métier.",
        "enfant-f|Elle range les livres.",
        "papa|Elle les trouve, aussi.",
        "narrateur|Victorina ouvre une page.",
        "narrateur|Une rose y est dessinée, trop plate.",
        "enfant-f|Je veux une vraie.",
        "papa|Chez la fleuriste, alors.",
        "maman|Juste après la librairie.",
        "narrateur|La clochette tinte encore, en partant.",
        "narrateur|Le livre tape un peu la hanche.",
        "papa|Tu le tiens ?",
        "enfant-f|Oui, papa.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|La libraire range les livres.",
        "narrateur|C'est quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Le seau de la fleuriste est plein d'eau claire.",
        "narrateur|Ça sent la rose et la tige coupée.",
        "narrateur|Une goutte court sur le zinc.",
        "enfant-f|La fleuriste !",
        "maman|Oui.",
        "maman|Elle aussi a un métier.",
        "papa|Elle choisit les fleurs.",
        "enfant-f|Pour moi, une rose.",
        "narrateur|Victorina pose le livre trop près du seau.",
        "narrateur|Une goutte vise la couverture.",
        "papa|Le livre ici, le seau là.",
        "enfant-f|Pardon.",
        "narrateur|Elle recule le livre, tout de suite.",
        "narrateur|La fleuriste tend une rose courte, encore fraîche.",
        "maman|Merci.",
        "enfant-f|Merci.",
        "papa|Bravo, Victorina.",
        "papa|Tu as gardé le livre au sec.",
        "narrateur|La rose sent plus fort que la page.",
        "narrateur|Victorina a les deux, papier et pétale.",
        "maman|On rentre ?",
        "enfant-f|Oui.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Le platane fait encore des ronds sur le trottoir.",
        "narrateur|Papa ouvre la porte de la maison.",
        "narrateur|Maman cherche un verre d'eau, pour la rose.",
        "enfant-f|Le livre, sur la table.",
        "maman|Et la rose, dans le verre.",
        "papa|Les deux métiers t'ont aidée.",
        "papa|La libraire, puis la fleuriste.",
        "enfant-f|Le livre, et la vraie.",
        "maman|Tu veux que je tourne une page ?",
        "enfant-f|Celle de la rose.",
        "narrateur|La page et la tige se regardent, un peu.",
        "narrateur|Une goutte glisse dans le verre, sans bruit.",
        "papa|Merci d'avoir reculé le livre.",
        "maman|Il est resté sec.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|La rose s'ouvre un peu, dans l'eau.",
        "narrateur|La page reste plate, et sent encore la colle.",
        "enfant-f|J'ai les deux.",
        "papa|Oui.",
        "maman|Le quartier les a gardées pour toi.",
        "narrateur|La clochette, tout au loin, ne tinte plus.",
        "narrateur|Le verre chante une toute petite note, contre la table.",
    ],
}

go(
    "ATOM-SOC.MET.001-07",
    "Victorina veut un livre de fleurs, puis une vraie rose. Le livre est trop haut. La libraire le glisse. Chez la fleuriste, une goutte vise la couverture. Livre au sec, rose dans le verre.",
    "La clochette et la rose",
    "Victorina, maman, papa",
    "librairie du quartier, seau de la fleuriste, table de la maison",
    S07,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    q_met("Elle trouve les livres. C'est quoi ?"),
    "Clochette, papier, livre trop haut. Libraire. Puis fleuriste, goutte, rose courte. Page et tige sur la table.",
    "Deux moments : libraire puis fleuriste. Pas chauffeur/médecin en liste. Imprévu goutte sur le livre.",
    "N2",
)


# ---------------------------------------------------------------------------
# PAY-01 N2 Aniss, papa — carte, coquillage, mer de France
# ---------------------------------------------------------------------------
S08 = {
    "CHK_T0000_P0000": [
        "narrateur|La carte de France dépasse du tapis bleu.",
        "narrateur|Les plis sont usés, un peu brillants.",
        "narrateur|Un coquillage blanc attend près du livre.",
        "narrateur|Il sent encore un peu le sel, tout loin.",
        "narrateur|Aniss vit ici, avec papa.",
        "narrateur|La fenêtre est ouverte, sans vague.",
        "enfant-m|Je veux entendre la mer, papa.",
        "papa|Avec le coquillage ?",
        "enfant-m|Oui.",
        "enfant-m|Et voir les vagues.",
        "papa|On pose le doigt sur la carte, d'abord.",
        "narrateur|En ce moment, Aniss s'assoit en tailleur.",
        "narrateur|Le tapis gratte un peu les genoux.",
        "narrateur|Papa déplie un grand bleu, sur la gauche.",
        "papa|Ça, c'est la France.",
        "enfant-m|La France.",
        "papa|Et ce bleu, c'est la mer.",
        "papa|La mer de France.",
        "enfant-m|Les vagues sont là ?",
        "papa|Sur la carte, c'est tout calme.",
        "papa|Dans le coquillage, on peut les imaginer.",
        "narrateur|Aniss tend la main vers le coquillage.",
        "narrateur|Le coquillage roule.",
        "narrateur|Il file sous le tapis, tout de suite.",
        "enfant-m|Il s'est caché !",
        "papa|Sous le tapis ?",
        "enfant-m|Oui.",
        "papa|On soulève le bord, tout doux ?",
        "narrateur|Le tapis est lourd, un peu rêche.",
        "narrateur|Une poussière danse dans le rayon.",
        "enfant-m|Je ne le vois pas.",
        "papa|Plus loin, peut-être.",
        "papa|On cherche ensemble.",
        "narrateur|Aniss glisse la main, paume ouverte.",
        "narrateur|Le tapis sent la laine tiède.",
        "narrateur|Rien, d'abord, sauf un fil.",
        "papa|Tu entends encore la mer, sans lui ?",
        "enfant-m|Non.",
        "enfant-m|Je veux le coquillage.",
    ],
    "CHK_T0000_P0000_Q0001": [
        "narrateur|Aniss nomme la France.",
        "narrateur|Il nomme aussi quoi ?",
    ],
    "CHK_T0000_P0000_C0001": [
        "narrateur|Les doigts d'Aniss touchent une bosse dure.",
        "narrateur|Le coquillage est là, sous la laine.",
        "enfant-m|Je l'ai !",
        "papa|Bravo, Aniss.",
        "papa|Tu l'as trouvé.",
        "narrateur|Il est un peu tiède, un peu poussiéreux.",
        "narrateur|Papa souffle, tout doux.",
        "narrateur|La poussière part vers la fenêtre.",
        "enfant-m|Je l'écoute.",
        "papa|Contre l'oreille.",
        "narrateur|Aniss pose le coquillage.",
        "narrateur|Un souffle lointain, comme une vague petite.",
        "enfant-m|J'entends la mer !",
        "papa|La mer de France.",
        "papa|Le bleu, sur la carte.",
        "enfant-m|Les vagues.",
        "papa|Tu les entends, dedans.",
        "papa|Merci d'avoir cherché sous le tapis.",
        "narrateur|Le bord du tapis retombe, tout plat.",
        "narrateur|La France reste ouverte, avec son bleu.",
    ],
    "CHK_T0000_P0000_END": [
        "narrateur|Aniss garde le coquillage contre l'oreille.",
        "narrateur|L'autre main reste sur le bleu de la carte.",
        "enfant-m|Ça chante, papa.",
        "papa|Oui.",
        "papa|Même ici, sans le vent du port.",
        "papa|Tu veux que je nomme encore ?",
        "enfant-m|La France.",
        "enfant-m|Et la mer.",
        "papa|Un pays, un paysage.",
        "narrateur|Papa replie un coin de carte, pas trop.",
        "narrateur|Le bleu reste visible, comme une porte.",
        "enfant-m|Je referme les yeux.",
        "papa|Les vagues sont là, dedans.",
        "narrateur|Le tapis ne cache plus rien.",
        "narrateur|Juste la laine, et les genoux.",
    ],
    "CHK_T0000_P0000_END_F0001": [
        "narrateur|Le coquillage reste au creux de la main.",
        "narrateur|Le souffle lointain continue, tout petit.",
        "enfant-m|La mer est là.",
        "papa|Oui.",
        "papa|La mer de France, sur le tapis.",
        "narrateur|La fenêtre n'a toujours pas de vague.",
        "narrateur|Aniss en a une, contre l'oreille, quand même.",
    ],
}

go(
    "ATOM-SOC.PAY.001-01",
    "Aniss veut entendre les vagues dans le coquillage. Papa déplie la France, le bleu de la mer. Le coquillage file sous le tapis. Aniss le trouve, l'écoute, garde la main sur la carte.",
    "Le coquillage sous le tapis",
    "Aniss, papa",
    "salon, tapis bleu, carte de France, fenêtre ouverte",
    S08,
    {
        "CHK_T0000_P0000": "",
        "CHK_T0000_P0000_Q0001": "",
        "CHK_T0000_P0000_C0001": "",
        "CHK_T0000_P0000_END": "",
        "CHK_T0000_P0000_END_F0001": "",
    },
    Q_PAY,
    "Carte trop grande, coquillage salé. Désir : les vagues. Imprévu : le coquillage sous le tapis. France et mer nommées dans le geste, pas en quiz. Oreille, bleu, laine.",
    "Pays greffé : France, paysage mer. Pas de liste montagne collée. Ouverture carte qui dépasse. Fin : souffle contre l'oreille.",
    "N2",
)
